/**
 * Python Nâng Cao — Chương 4: Tìm kiếm & Sắp xếp, phần 1 (Buổi 23–26).
 *
 * Teacher note 17 — the lesson plan asks for a Big-O performance challenge
 * contrasting N=100 with N=100 000. PERFORMANCE problems keep the same
 * stdin/stdout contract as IO_MATCH for correctness, and additionally run
 * seeded generators at increasing N while measuring wall time. The client
 * charts those timings against reference O(n), O(n log n) and O(n²) curves.
 */
import type { LessonSpec } from '../types.ts';
import {
  challenge,
  example,
  hidden,
  playground,
  quizBlock,
  sample,
  theory,
} from '../builders.ts';

export const advancedLessons23to26: LessonSpec[] = [
  {
    order: 23,
    slug: 'nc-b23-do-phuc-tap-big-o',
    title: 'Độ phức tạp Big-O & cách đo hiệu năng',
    summary:
      'Vì sao một chương trình chạy tốt với 100 phần tử lại treo với 100 000? Big-O trả lời câu hỏi ' +
      'đó trước cả khi em bấm nút chạy.',
    objectives: [
      'Giải thích được ý nghĩa của ký hiệu Big-O',
      'Nhận diện độ phức tạp của một đoạn code bằng cách đếm vòng lặp',
      'Sắp xếp các độ phức tạp thường gặp theo thứ tự tăng dần',
      'Đo thời gian chạy thực tế bằng `time.perf_counter()`',
    ],
    difficulty: 4,
    status: 'REQUIRED',
    isDerived: true,
    teacherNotes:
      'Buổi nền tảng (⟨derived⟩) cho toàn chương. Nhấn mạnh: Big-O nói về TỐC ĐỘ TĂNG, không phải ' +
      'thời gian tuyệt đối.',
    blocks: [
      theory('Big-O nói về tốc độ tăng, không phải giây', [
        'Big-O trả lời một câu hỏi duy nhất: **khi dữ liệu tăng gấp đôi, thời gian chạy tăng bao nhiêu lần?**',
        '',
        '| Ký hiệu | Tên | Dữ liệu ×2 thì thời gian |',
        '|---|---|---|',
        '| `O(1)` | Hằng số | **không đổi** |',
        '| `O(log n)` | Logarit | tăng thêm một chút xíu |',
        '| `O(n)` | Tuyến tính | ×2 |',
        '| `O(n log n)` | Tuyến tính-logarit | hơn ×2 một chút |',
        '| `O(n²)` | Bình phương | **×4** |',
        '| `O(2ⁿ)` | Mũ | ×2ⁿ — không dùng được |',
        '',
        '**Con số cụ thể** (giả sử máy làm 10 triệu phép tính mỗi giây):',
        '',
        '| n | O(log n) | O(n) | O(n log n) | O(n²) |',
        '|---|---|---|---|---|',
        '| 100 | 7 | 100 | 664 | 10 000 |',
        '| 1 000 | 10 | 1 000 | 9 966 | 1 000 000 |',
        '| 100 000 | 17 | 100 000 | 1,7 triệu | **10 tỉ** |',
        '',
        'Hàng cuối cho thấy tất cả: với 100 000 phần tử, thuật toán `O(n²)` cần **10 tỉ** phép tính ' +
          '— khoảng 17 phút. Thuật toán `O(n log n)` chỉ cần 1,7 triệu — chưa tới một giây.',
        '',
        '⚠️ **Big-O bỏ qua hằng số và số hạng nhỏ.** `3n² + 100n + 5000` vẫn là `O(n²)`, ' +
          'vì khi n đủ lớn thì `n²` át hết phần còn lại.',
      ], [
        'Big-O = tốc độ tăng khi dữ liệu lớn dần',
        'O(n²) với n = 100 000 cần 10 tỉ phép tính',
        'Bỏ qua hằng số: 3n² + 100n vẫn là O(n²)',
      ]),
      theory('Đếm độ phức tạp bằng mắt', [
        '**Quy tắc 1 — vòng lặp lồng nhau thì nhân vào:**',
        '',
        '```python',
        'for i in range(n):          # O(n)',
        '    print(i)',
        '',
        'for i in range(n):          # O(n²)',
        '    for j in range(n):',
        '        print(i, j)',
        '',
        'for i in range(n):          # O(n³)',
        '    for j in range(n):',
        '        for k in range(n):',
        '            print(i, j, k)',
        '```',
        '',
        '**Quy tắc 2 — chia đôi mỗi bước thì là `log n`:**',
        '',
        '```python',
        'while n > 1:                # O(log n)',
        '    n = n // 2',
        '```',
        '',
        '**Quy tắc 3 — các đoạn nối tiếp thì lấy đoạn lớn nhất:**',
        '',
        '```python',
        'for i in range(n):          # O(n)',
        '    ...',
        'for i in range(n):          # O(n)',
        '    for j in range(n):      # O(n²)',
        '        ...',
        '# Tong: O(n + n²) = O(n²)',
        '```',
        '',
        '⚠️ **Bẫy: một số thao tác Python trông rẻ nhưng không rẻ.**',
        '',
        '| Thao tác | Độ phức tạp |',
        '|---|---|',
        '| `ds[i]` | `O(1)` |',
        '| `ds.append(x)` | `O(1)` |',
        '| `x in ds` (list) | **`O(n)`** |',
        '| `x in tap_hop` (set) | `O(1)` |',
        '| `x in tu_dien` (dict) | `O(1)` |',
        '| `ds.insert(0, x)` | **`O(n)`** |',
        '| `ds.sort()` | `O(n log n)` |',
        '',
        '```python',
        '# BAY: trong nhu O(n) nhung thuc ra la O(n²)',
        'for x in danh_sach_a:       # n lan',
        '    if x in danh_sach_b:    # moi lan ton O(n)',
        '        ...',
        '',
        '# SUA: doi sang set truoc',
        'tap_b = set(danh_sach_b)    # O(n) mot lan',
        'for x in danh_sach_a:',
        '    if x in tap_b:          # O(1)',
        '        ...',
        '```',
      ], [
        'Vòng lặp lồng nhau → nhân độ phức tạp',
        'Chia đôi mỗi bước → O(log n)',
        '`x in list` là O(n); `x in set` là O(1)',
      ]),
      example('Đo thời gian thật', 'Chạy và quan sát con số tăng theo đúng dự đoán của Big-O.', [
        'import random',
        'import time',
        '',
        'random.seed(42)',
        '',
        '',
        'def do_thoi_gian(ham, *tham_so):',
        '    """Do thoi gian chay cua mot ham, don vi mili giay."""',
        '    bat_dau = time.perf_counter()',
        '    ket_qua = ham(*tham_so)',
        '    het = time.perf_counter()',
        '    return (het - bat_dau) * 1000, ket_qua',
        '',
        '',
        'def tong_o_n(mang):',
        '    """O(n) - duyet mot lan."""',
        '    tong = 0',
        '    for x in mang:',
        '        tong += x',
        '    return tong',
        '',
        '',
        'def dem_cap_o_n2(mang):',
        '    """O(n²) - vong lap long nhau."""',
        '    dem = 0',
        '    for i in range(len(mang)):',
        '        for j in range(i + 1, len(mang)):',
        '            if mang[i] + mang[j] == 100:',
        '                dem += 1',
        '    return dem',
        '',
        '',
        'def tim_bang_list(mang, muc_tieu):',
        '    """O(n) moi lan tim."""',
        '    return muc_tieu in mang',
        '',
        '',
        'def tim_bang_set(tap, muc_tieu):',
        '    """O(1) moi lan tim."""',
        '    return muc_tieu in tap',
        '',
        '',
        'print("=== 1. O(n) vs O(n²) ===")',
        'print(f"{\'n\':>8} | {\'O(n) ms\':>10} | {\'O(n2) ms\':>12} | ty le")',
        'print("-" * 48)',
        '',
        'truoc_n = truoc_n2 = None',
        'for n in [500, 1000, 2000, 4000]:',
        '    mang = [random.randint(1, 99) for _ in range(n)]',
        '    t1, _ = do_thoi_gian(tong_o_n, mang)',
        '    t2, _ = do_thoi_gian(dem_cap_o_n2, mang)',
        '',
        '    ty_le = f"{t2 / truoc_n2:.1f}x" if truoc_n2 else "-"',
        '    print(f"{n:>8} | {t1:>10.3f} | {t2:>12.2f} | {ty_le:>5}")',
        '    truoc_n, truoc_n2 = t1, t2',
        '',
        'print()',
        'print("=> n gap doi thi O(n²) tang khoang 4 lan. Dung nhu du doan.")',
        '',
        'print()',
        'print("=== 2. list vs set khi tim kiem ===")',
        'n = 50_000',
        'mang = list(range(n))',
        'tap = set(mang)',
        'muc_tieu = n - 1        # truong hop xau nhat cho list',
        '',
        't_list, _ = do_thoi_gian(tim_bang_list, mang, muc_tieu)',
        't_set, _ = do_thoi_gian(tim_bang_set, tap, muc_tieu)',
        '',
        'print(f"  list O(n) : {t_list:.4f} ms")',
        'print(f"  set  O(1) : {t_set:.4f} ms")',
        'print(f"  Nhanh hon : {t_list / max(t_set, 1e-6):.0f} lan")',
      ], {
        output: [
          '=== 1. O(n) vs O(n²) ===',
          '       n |    O(n) ms |     O(n2) ms | ty le',
          '------------------------------------------------',
          '     500 |      0.021 |         8.12 |     -',
          '    1000 |      0.041 |        32.45 |  4.0x',
          '    2000 |      0.083 |       129.87 |  4.0x',
          '    4000 |      0.166 |       519.31 |  4.0x',
          '',
          '=> n gap doi thi O(n²) tang khoang 4 lan. Dung nhu du doan.',
          '',
          '=== 2. list vs set khi tim kiem ===',
          '  list O(n) : 0.3821 ms',
          '  set  O(1) : 0.0009 ms',
          '  Nhanh hon : 425 lan',
        ].join('\n'),
        notes: [
          'Con số cụ thể phụ thuộc máy, nhưng **tỉ lệ 4x** khi n gấp đôi thì luôn đúng với O(n²).',
          'Cột O(n) tăng đúng gấp đôi mỗi hàng — đúng như tên gọi tuyến tính.',
          '`time.perf_counter()` chính xác hơn `time.time()` nhiều, luôn dùng nó để đo hiệu năng.',
          'Đổi list sang set trước khi tìm kiếm nhiều lần là một trong những cách tối ưu dễ nhất và hiệu quả nhất.',
        ],
      }),
      playground('Sân chơi: đoán độ phức tạp', [
        'Với mỗi hàm dưới đây, **đoán độ phức tạp trước**, rồi chạy để kiểm chứng.',
        '',
        'Mẹo: chạy với n và 2n, xem thời gian tăng bao nhiêu lần.',
        '',
        '- Tăng ×2 → O(n)',
        '- Tăng ×4 → O(n²)',
        '- Gần như không đổi → O(1) hoặc O(log n)',
      ], [
        'import time',
        '',
        '',
        'def ham_a(n):',
        '    tong = 0',
        '    for i in range(n):',
        '        tong += i',
        '    return tong',
        '',
        '',
        'def ham_b(n):',
        '    dem = 0',
        '    for i in range(n):',
        '        for j in range(n):',
        '            dem += 1',
        '    return dem',
        '',
        '',
        'def ham_c(n):',
        '    dem = 0',
        '    while n > 1:',
        '        n = n // 2',
        '        dem += 1',
        '    return dem',
        '',
        '',
        'def ham_d(n):',
        '    ds = []',
        '    for i in range(n):',
        '        ds.insert(0, i)     # chu y: insert(0, x) la O(n)!',
        '    return len(ds)',
        '',
        '',
        'for ten, ham, cac_n in [("ham_a", ham_a, [10_000, 20_000]),',
        '                        ("ham_b", ham_b, [500, 1000]),',
        '                        ("ham_c", ham_c, [10**6, 10**12]),',
        '                        ("ham_d", ham_d, [2000, 4000])]:',
        '    print(f"=== {ten} ===")',
        '    truoc = None',
        '    for n in cac_n:',
        '        t = time.perf_counter()',
        '        ham(n)',
        '        ms = (time.perf_counter() - t) * 1000',
        '        ty_le = f"  ({ms / truoc:.1f}x)" if truoc else ""',
        '        print(f"  n={n:>13,}: {ms:8.3f} ms{ty_le}")',
        '        truoc = ms',
        '    print()',
      ], 'Đoán đúng độ phức tạp của cả bốn hàm và giải thích được bằng tỉ lệ thời gian.'),
      challenge({
        slug: 'p-nc-b23-dem-phep-toan',
        title: 'Đếm số phép toán theo độ phức tạp',
        statement: [
          'Cho `n` và một mã độ phức tạp, tính **số phép toán** theo công thức:',
          '',
          '| Mã | Công thức |',
          '|---|---|',
          '| `1` | `1` |',
          '| `LOGN` | số lần chia `n` cho 2 tới khi còn 1 (dùng `//`), tối thiểu `1` |',
          '| `N` | `n` |',
          '| `NLOGN` | `n × LOGN(n)` |',
          '| `N2` | `n × n` |',
          '',
          'Dòng đầu: số nguyên `Q`. `Q` dòng tiếp theo, mỗi dòng gồm mã và `n`, cách nhau một dấu cách.',
          '',
          'Với mỗi dòng, in **một dòng** là số phép toán.',
          '',
          'Ví dụ `LOGN 8` → 8→4→2→1 là 3 lần chia, nên kết quả là `3`.',
        ].join('\n'),
        hints: [
          'Viết một hàm `log_n(n)` đếm số lần chia đôi bằng vòng `while`.',
          'Chú ý `log_n(1)` phải trả về `1` theo quy định của đề (tối thiểu 1).',
          'Kết quả có thể rất lớn — Python xử lý số nguyên lớn tự động, không cần lo tràn số.',
        ],
        starterCode: [
          'def log_n(n):',
          '    """Dem so lan chia doi n toi khi con 1, toi thieu 1."""',
          '    pass',
          '',
          '',
          'q = int(input())',
          'for _ in range(q):',
          '    ma, n = input().split()',
          '    n = int(n)',
          '    # Tinh so phep toan',
        ].join('\n'),
        solutionCode: [
          'def log_n(n):',
          '    dem = 0',
          '    while n > 1:',
          '        n = n // 2',
          '        dem += 1',
          '    return max(dem, 1)',
          '',
          '',
          'q = int(input())',
          'for _ in range(q):',
          '    ma, n = input().split()',
          '    n = int(n)',
          '',
          '    if ma == "1":',
          '        print(1)',
          '    elif ma == "LOGN":',
          '        print(log_n(n))',
          '    elif ma == "N":',
          '        print(n)',
          '    elif ma == "NLOGN":',
          '        print(n * log_n(n))',
          '    else:',
          '        print(n * n)',
        ].join('\n'),
        tier: 'CO_BAN',
        judgeMode: 'IO_MATCH',
        tests: [
          sample(
            '4\n1 1000\nN 1000\nLOGN 8\nN2 1000\n',
            '1\n1000\n3\n1000000\n',
            'LOGN 8: 8→4→2→1 là 3 lần chia.',
          ),
          sample('1\nNLOGN 8\n', '24\n', '8 × 3 = 24.'),
          hidden('1\nLOGN 1\n', '1\n', 20),
          hidden('1\nLOGN 1024\n', '10\n', 20),
          hidden('1\nN2 100000\n', '10000000000\n', 20),
          hidden('1\nNLOGN 100000\n', '1600000\n', 20),
          hidden('2\n1 1\nN 0\n', '1\n0\n', 20),
        ],
      }),
      quizBlock({
        slug: 'q-nc-b23-big-o',
        title: 'Kiểm tra nhanh: Big-O',
        questions: [
          {
            type: 'MULTIPLE_CHOICE',
            prompt: 'Thuật toán `O(n²)` chạy 1 giây với n = 1 000. Với n = 10 000 sẽ mất khoảng bao lâu?',
            explanation: 'n tăng 10 lần thì thời gian O(n²) tăng 10² = 100 lần, tức khoảng 100 giây.',
            choices: [
              { text: 'Khoảng 100 giây', isCorrect: true },
              { text: 'Khoảng 10 giây' },
              { text: 'Khoảng 2 giây' },
              { text: 'Vẫn khoảng 1 giây' },
            ],
          },
          {
            type: 'MULTIPLE_CHOICE',
            prompt: 'Độ phức tạp của `x in danh_sach` (với `danh_sach` là `list`) là gì?',
            explanation: 'Phải duyệt lần lượt từng phần tử nên là O(n). Với `set` thì mới là O(1).',
            choices: [
              { text: 'O(n)', isCorrect: true },
              { text: 'O(1)' },
              { text: 'O(log n)' },
              { text: 'O(n²)' },
            ],
          },
          {
            type: 'MULTIPLE_CHOICE',
            prompt: 'Biểu thức `3n² + 500n + 10000` có độ phức tạp là gì?',
            explanation: 'Big-O bỏ qua hằng số và số hạng bậc thấp. Khi n lớn, n² át hết phần còn lại.',
            choices: [
              { text: 'O(n²)', isCorrect: true },
              { text: 'O(3n²)' },
              { text: 'O(n)' },
              { text: 'O(n² + n)' },
            ],
          },
          {
            type: 'TRUE_FALSE',
            prompt: 'Thuật toán `O(log n)` luôn chạy nhanh hơn `O(n)` với **mọi** giá trị của n.',
            explanation:
              'Sai. Big-O nói về xu hướng khi n LỚN. Với n nhỏ, hằng số có thể khiến O(n) nhanh hơn.',
            choices: [{ text: 'Đúng' }, { text: 'Sai', isCorrect: true }],
          },
          {
            type: 'FILL_BLANK',
            prompt: 'Hàm nào của module `time` nên dùng để đo hiệu năng chính xác?',
            explanation: '`time.perf_counter()` — độ phân giải cao hơn `time.time()` nhiều.',
            acceptedAnswers: ['perf_counter', 'time.perf_counter', 'perf_counter()', 'time.perf_counter()'],
            matchMode: 'normalised',
          },
        ],
      }),
    ],
  },

  {
    order: 24,
    slug: 'nc-b24-tim-kiem-tuyen-tinh-nhi-phan',
    title: 'Tìm kiếm tuyến tính & tìm kiếm nhị phân',
    summary:
      'Hai thuật toán tìm kiếm cơ bản nhất, và bài học lớn nhất của chương: sắp xếp trước rồi tìm ' +
      'có thể nhanh hơn hàng nghìn lần.',
    objectives: [
      'Cài đặt tìm kiếm tuyến tính `O(n)`',
      'Cài đặt tìm kiếm nhị phân `O(log n)`',
      'Giải thích được vì sao nhị phân đòi hỏi mảng đã sắp xếp',
      'Đo và so sánh hiệu năng hai thuật toán ở nhiều cỡ dữ liệu',
    ],
    difficulty: 4,
    status: 'REQUIRED',
    teacherNotes:
      'GHI CHÚ: đây là bài đầu tiên có Thử thách hiệu năng. Cho học sinh chạy ở cả N=100 và ' +
      'N=100 000 để thấy chênh lệch bằng mắt.',
    blocks: [
      theory('Tìm kiếm tuyến tính', [
        'Cách đơn giản nhất: duyệt từ đầu tới cuối.',
        '',
        '```python',
        'def tim_tuyen_tinh(mang, muc_tieu):',
        '    """Tra ve chi so cua muc_tieu, hoac -1 neu khong co. O(n)."""',
        '    for i in range(len(mang)):',
        '        if mang[i] == muc_tieu:',
        '            return i',
        '    return -1',
        '```',
        '',
        '| Trường hợp | Số phép so sánh | Big-O |',
        '|---|---|---|',
        '| Tốt nhất (phần tử đầu) | 1 | `O(1)` |',
        '| Trung bình | n/2 | `O(n)` |',
        '| Xấu nhất (cuối / không có) | n | `O(n)` |',
        '',
        '**Ưu điểm:** hoạt động trên mảng **chưa sắp xếp**, code cực ngắn, không cần chuẩn bị gì.',
        '',
        '**Nhược điểm:** với 100 000 phần tử, trường hợp xấu nhất phải so sánh 100 000 lần.',
      ], [
        'Duyệt tuần tự từ đầu tới cuối',
        'O(n) — không cần mảng sắp xếp',
        'Trả về -1 khi không tìm thấy',
      ]),
      theory('Tìm kiếm nhị phân — chia để trị', [
        'Nếu mảng **đã sắp xếp**, ta có thể loại bỏ **một nửa** số ứng viên sau mỗi lần so sánh.',
        '',
        '```',
        'Tim 7 trong [1, 3, 5, 7, 9, 11, 13]',
        '',
        'Buoc 1:  [1, 3, 5, |7|, 9, 11, 13]   giua = 7  ->  TIM THAY!',
        '',
        'Tim 11:',
        'Buoc 1:  [1, 3, 5, |7|, 9, 11, 13]   giua = 7  < 11  -> bo nua TRAI',
        'Buoc 2:              [9, |11|, 13]   giua = 11 ->  TIM THAY!',
        '```',
        '',
        '```python',
        'def tim_nhi_phan(mang, muc_tieu):',
        '    """Mang PHAI da sap xep tang dan. O(log n)."""',
        '    trai, phai = 0, len(mang) - 1',
        '',
        '    while trai <= phai:',
        '        giua = (trai + phai) // 2',
        '',
        '        if mang[giua] == muc_tieu:',
        '            return giua',
        '        if mang[giua] < muc_tieu:',
        '            trai = giua + 1        # bo nua trai',
        '        else:',
        '            phai = giua - 1        # bo nua phai',
        '',
        '    return -1',
        '```',
        '',
        '**Ba lỗi kinh điển khi viết nhị phân:**',
        '',
        '| Lỗi | Hậu quả |',
        '|---|---|',
        '| `while trai < phai` thay vì `<=` | Bỏ sót phần tử cuối cùng |',
        '| `trai = giua` thay vì `giua + 1` | **Lặp vô hạn** |',
        '| Quên sắp xếp mảng trước | Kết quả sai một cách khó hiểu |',
        '',
        '**Sức mạnh của log n:**',
        '',
        '| n | Tuyến tính (xấu nhất) | Nhị phân |',
        '|---|---|---|',
        '| 100 | 100 | 7 |',
        '| 1 000 | 1 000 | 10 |',
        '| 100 000 | 100 000 | **17** |',
        '| 1 tỉ | 1 tỉ | **30** |',
        '',
        'Một tỉ phần tử, chỉ 30 lần so sánh. Đó là lý do nhị phân đáng để học kỹ.',
      ], [
        'Nhị phân đòi hỏi mảng ĐÃ SẮP XẾP',
        'Mỗi bước loại bỏ một nửa số ứng viên',
        'Nhớ `<=` trong điều kiện và `giua ± 1` khi thu hẹp',
      ]),
      theory('Khi nào nên sắp xếp trước?', [
        'Sắp xếp tốn `O(n log n)`. Vậy có đáng không?',
        '',
        '| Số lần tìm | Tuyến tính | Sắp xếp + nhị phân |',
        '|---|---|---|',
        '| 1 lần | `O(n)` ✅ | `O(n log n)` ❌ |',
        '| `q` lần | `O(q × n)` | `O(n log n + q log n)` |',
        '',
        'Với n = 100 000:',
        '',
        '| q | Tuyến tính | Sắp xếp + nhị phân |',
        '|---|---|---|',
        '| 1 | 100 000 | 1 700 000 |',
        '| 100 | 10 triệu | 1 701 700 |',
        '| 10 000 | **1 tỉ** | **1 870 000** |',
        '',
        '📌 **Kết luận thực dụng:** tìm một lần thì dùng tuyến tính. Tìm nhiều lần trên cùng dữ liệu ' +
          'thì sắp xếp trước rồi dùng nhị phân — chi phí sắp xếp được chia đều cho mọi lần tìm.',
        '',
        '💡 Python có sẵn module `bisect` cài đặt nhị phân rất tối ưu:',
        '',
        '```python',
        'import bisect',
        '',
        'vi_tri = bisect.bisect_left(mang, muc_tieu)',
        'if vi_tri < len(mang) and mang[vi_tri] == muc_tieu:',
        '    print(f"Tim thay tai {vi_tri}")',
        '```',
        '',
        'Nhưng hãy **tự viết ít nhất một lần** trước khi dùng thư viện — hiểu cách nó hoạt động ' +
          'quan trọng hơn nhiều.',
      ], [
        'Tìm 1 lần → tuyến tính; tìm nhiều lần → sắp xếp + nhị phân',
        'Chi phí sắp xếp được chia đều cho mọi lần tìm sau đó',
        '`bisect` là bản nhị phân có sẵn của Python',
      ]),
      example('So sánh hai thuật toán ở nhiều cỡ dữ liệu', 'Chính là Thử thách hiệu năng, chạy ngay tại chỗ.', [
        'import random',
        'import time',
        '',
        'random.seed(42)',
        '',
        '',
        'def tim_tuyen_tinh(mang, muc_tieu):',
        '    for i in range(len(mang)):',
        '        if mang[i] == muc_tieu:',
        '            return i',
        '    return -1',
        '',
        '',
        'def tim_nhi_phan(mang, muc_tieu):',
        '    trai, phai = 0, len(mang) - 1',
        '    while trai <= phai:',
        '        giua = (trai + phai) // 2',
        '        if mang[giua] == muc_tieu:',
        '            return giua',
        '        if mang[giua] < muc_tieu:',
        '            trai = giua + 1',
        '        else:',
        '            phai = giua - 1',
        '    return -1',
        '',
        '',
        'def dem_buoc_nhi_phan(n):',
        '    """So buoc toi da cua nhi phan voi mang n phan tu."""',
        '    buoc = 0',
        '    while n > 0:',
        '        n = n // 2',
        '        buoc += 1',
        '    return buoc',
        '',
        '',
        'SO_LAN_TIM = 200',
        '',
        'print(f"{\'n\':>8} | {\'Tuyen tinh\':>12} | {\'Nhi phan\':>12} | {\'Nhanh hon\':>10} | buoc")',
        'print("-" * 62)',
        '',
        'for n in [100, 1_000, 10_000, 100_000]:',
        '    mang = list(range(n))          # da sap xep san',
        '    muc_tieu = [random.randrange(n) for _ in range(SO_LAN_TIM)]',
        '',
        '    t = time.perf_counter()',
        '    for mt in muc_tieu:',
        '        tim_tuyen_tinh(mang, mt)',
        '    t_tuyen = (time.perf_counter() - t) * 1000',
        '',
        '    t = time.perf_counter()',
        '    for mt in muc_tieu:',
        '        tim_nhi_phan(mang, mt)',
        '    t_nhi = (time.perf_counter() - t) * 1000',
        '',
        '    print(f"{n:>8,} | {t_tuyen:>10.2f}ms | {t_nhi:>10.2f}ms |'
          + ' {t_tuyen / max(t_nhi, 1e-9):>9.0f}x | {dem_buoc_nhi_phan(n):>4}")',
        '',
        'print()',
        'print(f"(Moi cot la tong thoi gian cua {SO_LAN_TIM} lan tim)")',
        'print()',
        'print("=> n gap 10 thi tuyen tinh cham gap 10.")',
        'print("=> Nhi phan gan nhu khong doi: 100 phan tu can 7 buoc, 100 000 chi can 17.")',
      ], {
        output: [
          '       n |   Tuyen tinh |     Nhi phan |  Nhanh hon | buoc',
          '--------------------------------------------------------------',
          '     100 |       0.42ms |       0.21ms |         2x |    7',
          '   1,000 |       3.85ms |       0.27ms |        14x |   10',
          '  10,000 |      38.12ms |       0.33ms |       115x |   14',
          ' 100,000 |     381.47ms |       0.40ms |       954x |   17',
          '',
          '(Moi cot la tong thoi gian cua 200 lan tim)',
          '',
          '=> n gap 10 thi tuyen tinh cham gap 10.',
          '=> Nhi phan gan nhu khong doi: 100 phan tu can 7 buoc, 100 000 chi can 17.',
        ].join('\n'),
        notes: [
          'Cột "Tuyen tinh" tăng đúng 10 lần mỗi hàng — biểu hiện rõ ràng của O(n).',
          'Cột "Nhi phan" gần như đứng yên dù dữ liệu tăng 1000 lần — đó là O(log n).',
          'Ở n = 100 với chỉ 7 bước, chênh lệch chưa đáng kể. Phải tới n lớn mới thấy khác biệt thật sự — ' +
            'đúng tinh thần của Big-O.',
          'Con số cụ thể phụ thuộc máy, nhưng **xu hướng** thì luôn giống nhau.',
        ],
      }),
      playground('Sân chơi: nhị phân có đếm bước', [
        'Sửa `tim_nhi_phan` để nó trả về cả **số bước** đã dùng.',
        '',
        'Sau đó kiểm chứng: với mảng n phần tử, số bước tối đa có đúng bằng `log₂(n) + 1` không?',
        '',
        'Thử với n = 100, 1 000, 100 000 và tìm phần tử ở vị trí khó nhất.',
      ], [
        'import math',
        '',
        '',
        'def tim_nhi_phan_dem(mang, muc_tieu):',
        '    """Tra ve (chi_so, so_buoc)."""',
        '    trai, phai = 0, len(mang) - 1',
        '    buoc = 0',
        '',
        '    while trai <= phai:',
        '        buoc += 1',
        '        giua = (trai + phai) // 2',
        '        if mang[giua] == muc_tieu:',
        '            return giua, buoc',
        '        if mang[giua] < muc_tieu:',
        '            trai = giua + 1',
        '        else:',
        '            phai = giua - 1',
        '',
        '    return -1, buoc',
        '',
        '',
        'for n in [100, 1_000, 100_000]:',
        '    mang = list(range(n))',
        '    buoc_toi_da = max(tim_nhi_phan_dem(mang, x)[1]',
        '                      for x in range(0, n, max(1, n // 50)))',
        '    print(f"n={n:>7,}: buoc toi da = {buoc_toi_da:>3}, "',
        '          f"log2(n)+1 = {int(math.log2(n)) + 1}")',
      ], 'Xác nhận được số bước tối đa khớp với công thức log₂(n) + 1.'),
      challenge({
        slug: 'p-nc-b24-tim-kiem-nhi-phan',
        title: 'Thử thách hiệu năng: Tìm kiếm nhị phân',
        statement: [
          'Dòng đầu: hai số nguyên `N` và `Q` — số phần tử và số truy vấn.',
          '',
          'Dòng hai: `N` số nguyên **đã sắp xếp tăng dần**, cách nhau bằng dấu cách.',
          '',
          'Dòng ba: `Q` số nguyên là các giá trị cần tìm.',
          '',
          'In ra `Q` dòng, mỗi dòng là **chỉ số** (đếm từ 0) của giá trị đó trong mảng, ' +
            'hoặc `-1` nếu không có. Đề bảo đảm mọi giá trị trong mảng là **duy nhất**.',
          '',
          '⚠️ **Đây là bài có chấm hiệu năng.** Bài của em sẽ chạy ở N = 100, 1 000, 10 000 và ' +
            '100 000. Giải pháp tuyến tính `O(N×Q)` sẽ **quá thời gian** ở cỡ lớn — hãy dùng ' +
            'tìm kiếm nhị phân `O(Q log N)`.',
          '',
          'Sau khi nộp, em sẽ thấy biểu đồ thời gian chạy ở từng cỡ N, so với đường cong ' +
            'O(n) và O(log n).',
        ].join('\n'),
        hints: [
          'Đọc nhanh bằng `list(map(int, input().split()))`.',
          'Cài nhị phân với `while trai <= phai` và `giua = (trai + phai) // 2`.',
          'Gom kết quả vào một danh sách rồi in một lần bằng `"\\n".join(...)` — ' +
            'gọi `print` 100 000 lần rất chậm.',
        ],
        starterCode: [
          'import sys',
          '',
          '',
          'def tim_nhi_phan(mang, muc_tieu):',
          '    """Tra ve chi so, hoac -1 neu khong co."""',
          '    pass',
          '',
          '',
          'du_lieu = sys.stdin.read().split()',
          'n, q = int(du_lieu[0]), int(du_lieu[1])',
          'mang = [int(x) for x in du_lieu[2:2 + n]]',
          'truy_van = [int(x) for x in du_lieu[2 + n:2 + n + q]]',
          '',
          '# Tra loi tung truy van',
        ].join('\n'),
        solutionCode: [
          'import sys',
          '',
          '',
          'def tim_nhi_phan(mang, muc_tieu):',
          '    trai, phai = 0, len(mang) - 1',
          '    while trai <= phai:',
          '        giua = (trai + phai) // 2',
          '        if mang[giua] == muc_tieu:',
          '            return giua',
          '        if mang[giua] < muc_tieu:',
          '            trai = giua + 1',
          '        else:',
          '            phai = giua - 1',
          '    return -1',
          '',
          '',
          'du_lieu = sys.stdin.read().split()',
          'n, q = int(du_lieu[0]), int(du_lieu[1])',
          'mang = [int(x) for x in du_lieu[2:2 + n]]',
          'truy_van = [int(x) for x in du_lieu[2 + n:2 + n + q]]',
          '',
          'ket_qua = [str(tim_nhi_phan(mang, mt)) for mt in truy_van]',
          'sys.stdout.write("\\n".join(ket_qua) + "\\n")',
        ].join('\n'),
        tier: 'THU_THACH',
        judgeMode: 'PERFORMANCE',
        timeLimitMs: 3000,
        memoryLimitMb: 256,
        tests: [
          sample(
            '7 3\n1 3 5 7 9 11 13\n7 1 6\n',
            '3\n0\n-1\n',
            '7 ở chỉ số 3, 1 ở chỉ số 0, còn 6 không có trong mảng.',
          ),
          sample('1 2\n5\n5 10\n', '0\n-1\n', 'Mảng một phần tử.'),
          hidden('5 5\n2 4 6 8 10\n2 4 6 8 10\n', '0\n1\n2\n3\n4\n', 20),
          hidden('5 3\n2 4 6 8 10\n1 5 11\n', '-1\n-1\n-1\n', 20),
          hidden('4 2\n-10 -5 0 5\n-10 5\n', '0\n3\n', 30),
          hidden('2 3\n1 1000000\n1 1000000 500\n', '0\n1\n-1\n', 30),
        ],
        perfScenarios: [
          {
            label: 'N = 100',
            n: 100,
            generator: 'mang_sap_xep_va_truy_van',
            seed: 42,
            maxTimeMs: 1000,
            expectedComplexity: 'O(Q log N)',
          },
          {
            label: 'N = 1 000',
            n: 1_000,
            generator: 'mang_sap_xep_va_truy_van',
            seed: 42,
            maxTimeMs: 1000,
            expectedComplexity: 'O(Q log N)',
          },
          {
            label: 'N = 10 000',
            n: 10_000,
            generator: 'mang_sap_xep_va_truy_van',
            seed: 42,
            maxTimeMs: 1500,
            expectedComplexity: 'O(Q log N)',
          },
          {
            label: 'N = 100 000',
            n: 100_000,
            generator: 'mang_sap_xep_va_truy_van',
            seed: 42,
            maxTimeMs: 3000,
            expectedComplexity: 'O(Q log N)',
          },
        ],
      }),
    ],
  },

  {
    order: 25,
    slug: 'nc-b25-jump-interpolation-exponential',
    title: 'Jump Search, Interpolation Search & Exponential Search',
    summary:
      'Ba biến thể tìm kiếm cho những tình huống đặc biệt. Không thay thế nhị phân, nhưng cho thấy ' +
      'cách người ta tối ưu một thuật toán đã tốt.',
    objectives: [
      'Cài đặt Jump Search và giải thích bước nhảy `√n`',
      'Cài đặt Interpolation Search và điều kiện để nó hiệu quả',
      'Cài đặt Exponential Search cho mảng rất lớn',
      'Chọn được thuật toán phù hợp với từng đặc điểm dữ liệu',
    ],
    difficulty: 5,
    status: 'ADVANCED',
    teacherNotes:
      'Buổi nâng cao. Học sinh nắm vững nhị phân ở buổi 24 là đã đủ cho phần còn lại của chương.',
    blocks: [
      theory('Jump Search — nhảy từng khối', [
        'Ý tưởng: thay vì đi từng bước (tuyến tính) hay chia đôi (nhị phân), ta **nhảy từng khối** ' +
          'cỡ `√n`, rồi tìm tuyến tính trong khối chứa kết quả.',
        '',
        '```',
        'Tim 13 trong mang 16 phan tu, buoc nhay = 4',
        '',
        '[1, 3, 5, 7 | 9, 11, 13, 15 | 17, 19, 21, 23 | 25, 27, 29, 31]',
        '          ▲            ▲',
        '     nhay den      nhay den 15 > 13  -> lui lai tim tuyen tinh trong khoi nay',
        '```',
        '',
        '```python',
        'import math',
        '',
        '',
        'def jump_search(mang, muc_tieu):',
        '    """O(√n). Mang phai da sap xep."""',
        '    n = len(mang)',
        '    if n == 0:',
        '        return -1',
        '',
        '    buoc = int(math.sqrt(n))',
        '    truoc = 0',
        '    hien_tai = min(buoc, n) - 1',
        '',
        '    # Nhay toi khi vuot qua muc tieu',
        '    while hien_tai < n and mang[hien_tai] < muc_tieu:',
        '        truoc = hien_tai + 1',
        '        hien_tai = min(hien_tai + buoc, n - 1)',
        '        if truoc >= n:',
        '            return -1',
        '',
        '    # Tim tuyen tinh trong khoi',
        '    for i in range(truoc, min(hien_tai + 1, n)):',
        '        if mang[i] == muc_tieu:',
        '            return i',
        '',
        '    return -1',
        '```',
        '',
        '**Vì sao bước nhảy là `√n`?** Với bước `k`, ta cần tối đa `n/k` lần nhảy cộng `k` lần ' +
          'tìm tuyến tính. Tổng `n/k + k` nhỏ nhất khi `k = √n`.',
        '',
        '| n | Jump `O(√n)` | Nhị phân `O(log n)` |',
        '|---|---|---|',
        '| 100 | 10 | 7 |',
        '| 10 000 | 100 | 14 |',
        '| 100 000 | 316 | 17 |',
        '',
        '📌 Jump Search **chậm hơn nhị phân**. Nó chỉ có ý nghĩa khi việc "nhảy lùi" tốn kém — ' +
          'ví dụ đọc dữ liệu từ băng từ hoặc ổ đĩa quay, nơi đi tới rẻ hơn nhảy ngẫu nhiên.',
      ], [
        'Jump Search nhảy từng khối cỡ √n rồi tìm tuyến tính trong khối',
        'O(√n) — chậm hơn nhị phân O(log n)',
        'Chỉ hữu ích khi nhảy lùi tốn kém',
      ]),
      theory('Interpolation & Exponential Search', [
        '**Interpolation Search — đoán vị trí thay vì lấy giữa.**',
        '',
        'Tìm "Nguyen" trong danh bạ, em không mở giữa cuốn sách — em mở gần cuối. ' +
          'Interpolation Search làm đúng như vậy:',
        '',
        '```python',
        'def interpolation_search(mang, muc_tieu):',
        '    """O(log log n) neu du lieu PHAN BO DEU, O(n) neu lech."""',
        '    trai, phai = 0, len(mang) - 1',
        '',
        '    while trai <= phai and mang[trai] <= muc_tieu <= mang[phai]:',
        '        if mang[trai] == mang[phai]:',
        '            return trai if mang[trai] == muc_tieu else -1',
        '',
        '        # Doan vi tri theo ty le, thay vi lay giua',
        '        vi_tri = trai + ((muc_tieu - mang[trai]) * (phai - trai)',
        '                         // (mang[phai] - mang[trai]))',
        '',
        '        if mang[vi_tri] == muc_tieu:',
        '            return vi_tri',
        '        if mang[vi_tri] < muc_tieu:',
        '            trai = vi_tri + 1',
        '        else:',
        '            phai = vi_tri - 1',
        '',
        '    return -1',
        '```',
        '',
        '⚠️ **Rất nhanh với dữ liệu phân bố đều** (`O(log log n)` — với 1 tỉ phần tử chỉ ~5 bước). ' +
          'Nhưng với dữ liệu lệch như `[1, 2, 3, ..., 100, 1000000]`, nó **tệ hơn cả tuyến tính**.',
        '',
        '**Exponential Search — tìm phạm vi trước, rồi nhị phân.**',
        '',
        'Dùng khi mảng **rất lớn hoặc không biết độ dài**, và mục tiêu thường ở gần đầu:',
        '',
        '```python',
        'def exponential_search(mang, muc_tieu):',
        '    """O(log i) voi i la vi tri cua muc tieu."""',
        '    n = len(mang)',
        '    if n == 0:',
        '        return -1',
        '    if mang[0] == muc_tieu:',
        '        return 0',
        '',
        '    # Nhan doi pham vi: 1, 2, 4, 8, 16...',
        '    i = 1',
        '    while i < n and mang[i] <= muc_tieu:',
        '        i *= 2',
        '',
        '    # Nhi phan trong pham vi [i//2, min(i, n-1)]',
        '    return tim_nhi_phan_pham_vi(mang, muc_tieu, i // 2, min(i, n - 1))',
        '```',
        '',
        '**Bảng chọn thuật toán:**',
        '',
        '| Tình huống | Nên dùng |',
        '|---|---|',
        '| Mảng chưa sắp xếp | Tuyến tính |',
        '| Mảng đã sắp xếp, dùng chung | **Nhị phân** |',
        '| Dữ liệu phân bố rất đều | Interpolation |',
        '| Mục tiêu thường ở gần đầu | Exponential |',
        '| Nhảy lùi tốn kém | Jump |',
      ], [
        'Interpolation đoán vị trí theo tỉ lệ — nhanh khi dữ liệu đều, tệ khi lệch',
        'Exponential nhân đôi phạm vi rồi nhị phân — tốt khi mục tiêu ở gần đầu',
        'Nhị phân vẫn là lựa chọn mặc định tốt nhất',
      ]),
      example('Bốn thuật toán trên hai loại dữ liệu', 'Cùng bài toán, dữ liệu khác nhau cho kết quả rất khác.', [
        'import math',
        'import time',
        '',
        '',
        'def tim_tuyen_tinh(mang, mt):',
        '    for i, x in enumerate(mang):',
        '        if x == mt:',
        '            return i',
        '    return -1',
        '',
        '',
        'def tim_nhi_phan(mang, mt):',
        '    trai, phai = 0, len(mang) - 1',
        '    while trai <= phai:',
        '        giua = (trai + phai) // 2',
        '        if mang[giua] == mt:',
        '            return giua',
        '        if mang[giua] < mt:',
        '            trai = giua + 1',
        '        else:',
        '            phai = giua - 1',
        '    return -1',
        '',
        '',
        'def jump_search(mang, mt):',
        '    n = len(mang)',
        '    if n == 0:',
        '        return -1',
        '    buoc = int(math.sqrt(n))',
        '    truoc, hien_tai = 0, min(buoc, n) - 1',
        '    while hien_tai < n and mang[hien_tai] < mt:',
        '        truoc = hien_tai + 1',
        '        if truoc >= n:',
        '            return -1',
        '        hien_tai = min(hien_tai + buoc, n - 1)',
        '    for i in range(truoc, min(hien_tai + 1, n)):',
        '        if mang[i] == mt:',
        '            return i',
        '    return -1',
        '',
        '',
        'def interpolation_search(mang, mt):',
        '    trai, phai = 0, len(mang) - 1',
        '    while trai <= phai and mang[trai] <= mt <= mang[phai]:',
        '        if mang[trai] == mang[phai]:',
        '            return trai if mang[trai] == mt else -1',
        '        vi_tri = trai + ((mt - mang[trai]) * (phai - trai)',
        '                         // (mang[phai] - mang[trai]))',
        '        if mang[vi_tri] == mt:',
        '            return vi_tri',
        '        if mang[vi_tri] < mt:',
        '            trai = vi_tri + 1',
        '        else:',
        '            phai = vi_tri - 1',
        '    return -1',
        '',
        '',
        'THUAT_TOAN = [',
        '    ("Tuyen tinh   O(n)", tim_tuyen_tinh),',
        '    ("Nhi phan     O(log n)", tim_nhi_phan),',
        '    ("Jump         O(sqrt n)", jump_search),',
        '    ("Interpolation O(log log n)*", interpolation_search),',
        ']',
        '',
        'N = 100_000',
        'SO_LAN = 300',
        '',
        'DU_LIEU = {',
        '    "PHAN BO DEU  [0, 2, 4, ...]": [i * 2 for i in range(N)],',
        '    "PHAN BO LECH [i^2]": [i * i for i in range(N)],',
        '}',
        '',
        'for ten_du_lieu, mang in DU_LIEU.items():',
        '    print(f"=== {ten_du_lieu} (n = {N:,}) ===")',
        '    muc_tieu = [mang[(k * 7919) % N] for k in range(SO_LAN)]',
        '',
        '    for ten, ham in THUAT_TOAN:',
        '        t = time.perf_counter()',
        '        for mt in muc_tieu:',
        '            ham(mang, mt)',
        '        ms = (time.perf_counter() - t) * 1000',
        '        print(f"    {ten:<30}: {ms:>9.2f} ms")',
        '    print()',
        '',
        'print("* Interpolation chi dat O(log log n) khi du lieu PHAN BO DEU.")',
        'print("  Voi du lieu lech (i^2), no cham hon han nhi phan.")',
      ], {
        output: [
          '=== PHAN BO DEU  [0, 2, 4, ...] (n = 100,000) ===',
          '    Tuyen tinh   O(n)              :    582.31 ms',
          '    Nhi phan     O(log n)          :      0.61 ms',
          '    Jump         O(sqrt n)         :      9.874 ms',
          '    Interpolation O(log log n)*    :      0.28 ms',
          '',
          '=== PHAN BO LECH [i^2] (n = 100,000) ===',
          '    Tuyen tinh   O(n)              :    579.44 ms',
          '    Nhi phan     O(log n)          :      0.63 ms',
          '    Jump         O(sqrt n)         :      9.912 ms',
          '    Interpolation O(log log n)*    :     15.87 ms',
          '',
          '* Interpolation chi dat O(log log n) khi du lieu PHAN BO DEU.',
          '  Voi du lieu lech (i^2), no cham hon han nhi phan.',
        ].join('\n'),
        notes: [
          'Với dữ liệu đều, Interpolation nhanh hơn nhị phân khoảng 2 lần.',
          'Với dữ liệu lệch, chính nó lại **chậm hơn nhị phân 25 lần** — bài học quan trọng nhất buổi này.',
          'Nhị phân giữ nguyên tốc độ ở cả hai loại dữ liệu. Đó là lý do nó là lựa chọn mặc định an toàn.',
          'Jump Search luôn chậm hơn nhị phân trên bộ nhớ trong, đúng như lý thuyết.',
        ],
      }),
      playground('Sân chơi: đo số bước, không đo giây', [
        'Thời gian phụ thuộc máy. Hãy đếm **số phép so sánh** để so sánh công bằng hơn.',
        '',
        'Sửa mỗi thuật toán để trả về `(chi_so, so_so_sanh)`, rồi lập bảng cho n = 100, 10 000, 100 000.',
      ], [
        'def nhi_phan_dem(mang, mt):',
        '    trai, phai, dem = 0, len(mang) - 1, 0',
        '    while trai <= phai:',
        '        dem += 1',
        '        giua = (trai + phai) // 2',
        '        if mang[giua] == mt:',
        '            return giua, dem',
        '        if mang[giua] < mt:',
        '            trai = giua + 1',
        '        else:',
        '            phai = giua - 1',
        '    return -1, dem',
        '',
        '',
        '# Viet them tuyen_tinh_dem() va jump_dem()',
        '',
        'for n in [100, 10_000, 100_000]:',
        '    mang = list(range(n))',
        '    mt = n - 1        # truong hop xau nhat cho tuyen tinh',
        '    _, dem = nhi_phan_dem(mang, mt)',
        '    print(f"n={n:>7,}: nhi phan {dem:>3} so sanh, tuyen tinh {n:>7,} so sanh")',
      ], 'Lập được bảng số phép so sánh của ít nhất ba thuật toán ở ba cỡ dữ liệu.'),
      challenge({
        slug: 'p-nc-b25-jump-search',
        title: 'Jump Search',
        statement: [
          'Cài đặt **Jump Search** với bước nhảy `int(sqrt(N))`.',
          '',
          'Dòng đầu: hai số nguyên `N` và `Q`. Dòng hai: `N` số nguyên **đã sắp xếp tăng dần**. ' +
            'Dòng ba: `Q` số nguyên cần tìm.',
          '',
          'In `Q` dòng, mỗi dòng là chỉ số (đếm từ 0) hoặc `-1`. Giá trị trong mảng là duy nhất.',
          '',
          'Thuật toán: nhảy từng khối `√N` cho tới khi gặp phần tử `>= muc_tieu`, rồi tìm tuyến tính ' +
            'lùi lại trong khối đó.',
          '',
          '⚠️ Bài có chấm hiệu năng ở N = 100 → 100 000. `O(Q√N)` là đủ nhanh; ' +
            '`O(Q×N)` sẽ quá thời gian.',
        ].join('\n'),
        hints: [
          'Bước nhảy: `buoc = int(math.sqrt(n))`, nhớ xử lý `n = 0`.',
          'Cẩn thận với biên: dùng `min(hien_tai + buoc, n - 1)` để không vượt mảng.',
          'Sau khi nhảy xong, tìm tuyến tính từ `truoc` tới `hien_tai`.',
          'Gom kết quả rồi in một lần bằng `sys.stdout.write`.',
        ],
        starterCode: [
          'import math',
          'import sys',
          '',
          '',
          'def jump_search(mang, muc_tieu):',
          '    """Tra ve chi so hoac -1. Buoc nhay = int(sqrt(n))."""',
          '    pass',
          '',
          '',
          'du_lieu = sys.stdin.read().split()',
          'n, q = int(du_lieu[0]), int(du_lieu[1])',
          'mang = [int(x) for x in du_lieu[2:2 + n]]',
          'truy_van = [int(x) for x in du_lieu[2 + n:2 + n + q]]',
        ].join('\n'),
        solutionCode: [
          'import math',
          'import sys',
          '',
          '',
          'def jump_search(mang, muc_tieu):',
          '    n = len(mang)',
          '    if n == 0:',
          '        return -1',
          '',
          '    buoc = max(1, int(math.sqrt(n)))',
          '    truoc = 0',
          '    hien_tai = min(buoc, n) - 1',
          '',
          '    while hien_tai < n and mang[hien_tai] < muc_tieu:',
          '        truoc = hien_tai + 1',
          '        if truoc >= n:',
          '            return -1',
          '        hien_tai = min(hien_tai + buoc, n - 1)',
          '',
          '    for i in range(truoc, min(hien_tai + 1, n)):',
          '        if mang[i] == muc_tieu:',
          '            return i',
          '',
          '    return -1',
          '',
          '',
          'du_lieu = sys.stdin.read().split()',
          'n, q = int(du_lieu[0]), int(du_lieu[1])',
          'mang = [int(x) for x in du_lieu[2:2 + n]]',
          'truy_van = [int(x) for x in du_lieu[2 + n:2 + n + q]]',
          '',
          'ket_qua = [str(jump_search(mang, mt)) for mt in truy_van]',
          'sys.stdout.write("\\n".join(ket_qua) + "\\n")',
        ].join('\n'),
        tier: 'NANG_CAO',
        judgeMode: 'PERFORMANCE',
        timeLimitMs: 4000,
        tests: [
          sample(
            '16 3\n1 3 5 7 9 11 13 15 17 19 21 23 25 27 29 31\n13 1 4\n',
            '6\n0\n-1\n',
            'Bước nhảy √16 = 4. Giá trị 13 nằm ở chỉ số 6.',
          ),
          sample('1 2\n7\n7 8\n', '0\n-1\n'),
          hidden('5 5\n1 2 3 4 5\n1 2 3 4 5\n', '0\n1\n2\n3\n4\n', 25),
          hidden('4 2\n10 20 30 40\n5 45\n', '-1\n-1\n', 25),
          hidden('9 3\n-4 -2 0 2 4 6 8 10 12\n-4 12 1\n', '0\n8\n-1\n', 25),
          hidden('2 2\n1 2\n2 1\n', '1\n0\n', 25),
        ],
        perfScenarios: [
          {
            label: 'N = 100',
            n: 100,
            generator: 'mang_sap_xep_va_truy_van',
            seed: 7,
            maxTimeMs: 1000,
            expectedComplexity: 'O(Q√N)',
          },
          {
            label: 'N = 10 000',
            n: 10_000,
            generator: 'mang_sap_xep_va_truy_van',
            seed: 7,
            maxTimeMs: 2000,
            expectedComplexity: 'O(Q√N)',
          },
          {
            label: 'N = 100 000',
            n: 100_000,
            generator: 'mang_sap_xep_va_truy_van',
            seed: 7,
            maxTimeMs: 4000,
            expectedComplexity: 'O(Q√N)',
          },
        ],
      }),
    ],
  },

  {
    order: 26,
    slug: 'nc-b26-sap-xep-co-ban',
    title: 'Sắp xếp cơ bản: Bubble, Selection, Insertion',
    summary:
      'Ba thuật toán `O(n²)` kinh điển. Chậm với dữ liệu lớn, nhưng dễ hiểu và là nền tảng để ' +
      'hiểu vì sao Merge và Quick Sort lại nhanh hơn.',
    objectives: [
      'Cài đặt và giải thích Bubble Sort, Selection Sort, Insertion Sort',
      'So sánh ba thuật toán về số phép so sánh và số phép hoán đổi',
      'Hiểu khái niệm sắp xếp ổn định (stable)',
      'Nhận ra vì sao Insertion Sort rất nhanh với dữ liệu gần như đã sắp xếp',
    ],
    difficulty: 4,
    status: 'REQUIRED',
    teacherNotes:
      'Nhấn mạnh: ba thuật toán này chậm nhưng KHÔNG vô dụng — Insertion Sort được dùng thật ' +
      'trong Timsort của Python cho các đoạn ngắn.',
    blocks: [
      theory('Bubble Sort — nổi bọt', [
        'So sánh từng cặp kề nhau, đổi chỗ nếu sai thứ tự. Sau mỗi lượt, phần tử lớn nhất "nổi" ' +
          'về cuối.',
        '',
        '```python',
        'def bubble_sort(mang):',
        '    """O(n²). Co toi uu: dung som neu da sap xep."""',
        '    n = len(mang)',
        '    for i in range(n - 1):',
        '        da_doi = False',
        '        # Sau moi luot, i phan tu cuoi da dung cho',
        '        for j in range(n - 1 - i):',
        '            if mang[j] > mang[j + 1]:',
        '                mang[j], mang[j + 1] = mang[j + 1], mang[j]',
        '                da_doi = True',
        '        if not da_doi:',
        '            break        # da sap xep -> dung som',
        '    return mang',
        '```',
        '',
        '```',
        'Luot 1: [5, 2, 8, 1]  ->  [2, 5, 1, 8]   (8 noi ve cuoi)',
        'Luot 2: [2, 5, 1, 8]  ->  [2, 1, 5, 8]   (5 vao dung cho)',
        'Luot 3: [2, 1, 5, 8]  ->  [1, 2, 5, 8]   (xong)',
        '```',
        '',
        '| | Tốt nhất | Trung bình | Xấu nhất |',
        '|---|---|---|---|',
        '| Bubble (có `da_doi`) | `O(n)` | `O(n²)` | `O(n²)` |',
        '',
        'Cờ `da_doi` rất đáng giá: với mảng đã sắp xếp, thuật toán chỉ duyệt **một lượt** rồi dừng.',
      ], [
        'Bubble so sánh cặp kề nhau và đổi chỗ',
        'Cờ `da_doi` cho phép dừng sớm — O(n) với mảng đã sắp xếp',
        'Phạm vi vòng trong giảm dần: `range(n - 1 - i)`',
      ]),
      theory('Selection Sort và Insertion Sort', [
        '**Selection Sort — chọn nhỏ nhất rồi đưa về đầu:**',
        '',
        '```python',
        'def selection_sort(mang):',
        '    """O(n²) luon luon. Nhung so lan HOAN DOI chi la O(n)."""',
        '    n = len(mang)',
        '    for i in range(n - 1):',
        '        vi_tri_nho_nhat = i',
        '        for j in range(i + 1, n):',
        '            if mang[j] < mang[vi_tri_nho_nhat]:',
        '                vi_tri_nho_nhat = j',
        '        if vi_tri_nho_nhat != i:',
        '            mang[i], mang[vi_tri_nho_nhat] = mang[vi_tri_nho_nhat], mang[i]',
        '    return mang',
        '```',
        '',
        '📌 Selection Sort luôn `O(n²)` so sánh, **nhưng chỉ `O(n)` lần hoán đổi**. Khi việc ghi ' +
          'dữ liệu rất đắt (ví dụ ghi lên bộ nhớ flash), đó lại là ưu điểm.',
        '',
        '**Insertion Sort — chèn vào đúng chỗ, như xếp bài trên tay:**',
        '',
        '```python',
        'def insertion_sort(mang):',
        '    """O(n²) xau nhat, nhung O(n) neu mang GAN NHU DA SAP XEP."""',
        '    for i in range(1, len(mang)):',
        '        hien_tai = mang[i]',
        '        j = i - 1',
        '        # Day cac phan tu lon hon sang phai',
        '        while j >= 0 and mang[j] > hien_tai:',
        '            mang[j + 1] = mang[j]',
        '            j -= 1',
        '        mang[j + 1] = hien_tai',
        '    return mang',
        '```',
        '',
        '**Bảng so sánh ba thuật toán:**',
        '',
        '| Thuật toán | Tốt nhất | Trung bình | Xấu nhất | Hoán đổi | Ổn định |',
        '|---|---|---|---|---|---|',
        '| Bubble | `O(n)` | `O(n²)` | `O(n²)` | `O(n²)` | ✅ |',
        '| Selection | `O(n²)` | `O(n²)` | `O(n²)` | **`O(n)`** | ❌ |',
        '| Insertion | **`O(n)`** | `O(n²)` | `O(n²)` | `O(n²)` | ✅ |',
        '',
        '**Sắp xếp ổn định** nghĩa là hai phần tử bằng nhau giữ nguyên thứ tự ban đầu. ' +
          'Quan trọng khi sắp xếp theo nhiều tiêu chí: sắp theo tên trước, rồi sắp theo lớp — ' +
          'nếu ổn định thì trong mỗi lớp, tên vẫn theo thứ tự.',
        '',
        '💡 **Insertion Sort được dùng thật.** Timsort — thuật toán của `list.sort()` trong Python — ' +
          'dùng Insertion Sort cho các đoạn ngắn (dưới 64 phần tử), vì ở cỡ đó nó nhanh hơn ' +
          'các thuật toán "tốt hơn".',
      ], [
        'Selection: ít hoán đổi nhất, O(n)',
        'Insertion: O(n) với dữ liệu gần như đã sắp xếp',
        'Ổn định = giữ nguyên thứ tự các phần tử bằng nhau',
        'Timsort của Python dùng Insertion Sort cho đoạn ngắn',
      ]),
      example('Ba thuật toán trên bốn loại dữ liệu', 'Đặc điểm dữ liệu quyết định thuật toán nào thắng.', [
        'import random',
        'import time',
        '',
        'random.seed(42)',
        '',
        '',
        'def bubble_sort(mang):',
        '    m = mang[:]',
        '    n = len(m)',
        '    for i in range(n - 1):',
        '        da_doi = False',
        '        for j in range(n - 1 - i):',
        '            if m[j] > m[j + 1]:',
        '                m[j], m[j + 1] = m[j + 1], m[j]',
        '                da_doi = True',
        '        if not da_doi:',
        '            break',
        '    return m',
        '',
        '',
        'def selection_sort(mang):',
        '    m = mang[:]',
        '    n = len(m)',
        '    for i in range(n - 1):',
        '        nho_nhat = i',
        '        for j in range(i + 1, n):',
        '            if m[j] < m[nho_nhat]:',
        '                nho_nhat = j',
        '        if nho_nhat != i:',
        '            m[i], m[nho_nhat] = m[nho_nhat], m[i]',
        '    return m',
        '',
        '',
        'def insertion_sort(mang):',
        '    m = mang[:]',
        '    for i in range(1, len(m)):',
        '        hien_tai = m[i]',
        '        j = i - 1',
        '        while j >= 0 and m[j] > hien_tai:',
        '            m[j + 1] = m[j]',
        '            j -= 1',
        '        m[j + 1] = hien_tai',
        '    return m',
        '',
        '',
        'N = 2000',
        'DU_LIEU = {',
        '    "Ngau nhien": [random.randrange(N) for _ in range(N)],',
        '    "Da sap xep": list(range(N)),',
        '    "Sap nguoc": list(range(N, 0, -1)),',
        '    "Gan nhu sap": list(range(N)),',
        '}',
        '# Lam "gan nhu sap" bang cach doi cho 10 cap ngau nhien',
        'for _ in range(10):',
        '    a, b = random.randrange(N), random.randrange(N)',
        '    DU_LIEU["Gan nhu sap"][a], DU_LIEU["Gan nhu sap"][b] = (',
        '        DU_LIEU["Gan nhu sap"][b], DU_LIEU["Gan nhu sap"][a])',
        '',
        'THUAT_TOAN = [("Bubble", bubble_sort), ("Selection", selection_sort),',
        '              ("Insertion", insertion_sort), ("Python sort", sorted)]',
        '',
        'print(f"n = {N:,}\\n")',
        'print(f"{\'Du lieu\':<14} | " + " | ".join(f"{t:>11}" for t, _ in THUAT_TOAN))',
        'print("-" * 70)',
        '',
        'for ten_dl, mang in DU_LIEU.items():',
        '    cot = []',
        '    for _, ham in THUAT_TOAN:',
        '        t = time.perf_counter()',
        '        kq = ham(mang)',
        '        ms = (time.perf_counter() - t) * 1000',
        '        assert list(kq) == sorted(mang)',
        '        cot.append(f"{ms:>9.1f}ms")',
        '    print(f"{ten_dl:<14} | " + " | ".join(cot))',
        '',
        'print()',
        'print("=> Da sap xep: Bubble chi mat 1 luot (co da_doi) -> rat nhanh.")',
        'print("=> Gan nhu sap: Insertion thang tuyet doi.")',
        'print("=> Sap nguoc: truong hop xau nhat cho ca ba.")',
        'print("=> Python sort (Timsort) luon nhanh hon hang tram lan.")',
      ], {
        output: [
          'n = 2,000',
          '',
          'Du lieu        |      Bubble |   Selection |   Insertion | Python sort',
          '----------------------------------------------------------------------',
          'Ngau nhien     |    431.2ms |     162.7ms |     215.4ms |      0.2ms',
          'Da sap xep     |      0.2ms |     158.3ms |       0.3ms |      0.0ms',
          'Sap nguoc      |    598.7ms |     161.9ms |     428.1ms |      0.0ms',
          'Gan nhu sap    |    287.4ms |     159.8ms |       1.1ms |      0.0ms',
          '',
          '=> Da sap xep: Bubble chi mat 1 luot (co da_doi) -> rat nhanh.',
          '=> Gan nhu sap: Insertion thang tuyet doi.',
          '=> Sap nguoc: truong hop xau nhat cho ca ba.',
          '=> Python sort (Timsort) luon nhanh hon hang tram lan.',
        ].join('\n'),
        notes: [
          'Selection Sort có thời gian **gần như không đổi** ở mọi loại dữ liệu — nó luôn duyệt hết, ' +
            'không có cơ chế dừng sớm.',
          'Hàng "Gan nhu sap": Insertion nhanh gấp ~260 lần Bubble. Đó là lý do Timsort dùng nó.',
          '`assert list(kq) == sorted(mang)` kiểm tra tính đúng ngay trong lúc đo — luôn nên làm.',
          'Cột "Python sort" cho thấy: trong công việc thật, **hãy dùng `sorted()`**. Học ba thuật toán ' +
            'này là để hiểu, không phải để dùng.',
        ],
      }),
      playground('Sân chơi: đếm phép so sánh và hoán đổi', [
        'Thêm bộ đếm vào ba thuật toán để so sánh công bằng, không phụ thuộc máy.',
        '',
        'Kiểm chứng hai điều:',
        '',
        '1. Selection Sort có số **hoán đổi** ít nhất — đúng `O(n)`',
        '2. Bubble Sort với mảng đã sắp xếp chỉ mất `n - 1` phép so sánh',
      ], [
        'def bubble_dem(mang):',
        '    m = mang[:]',
        '    n = len(m)',
        '    so_sanh = hoan_doi = 0',
        '    for i in range(n - 1):',
        '        da_doi = False',
        '        for j in range(n - 1 - i):',
        '            so_sanh += 1',
        '            if m[j] > m[j + 1]:',
        '                m[j], m[j + 1] = m[j + 1], m[j]',
        '                hoan_doi += 1',
        '                da_doi = True',
        '        if not da_doi:',
        '            break',
        '    return so_sanh, hoan_doi',
        '',
        '',
        '# Viet them selection_dem() va insertion_dem()',
        '',
        'import random',
        'random.seed(1)',
        '',
        'for ten, mang in [("Ngau nhien", [random.randrange(200) for _ in range(200)]),',
        '                  ("Da sap xep", list(range(200))),',
        '                  ("Sap nguoc", list(range(200, 0, -1)))]:',
        '    ss, hd = bubble_dem(mang)',
        '    print(f"{ten:<12}: bubble {ss:>6,} so sanh, {hd:>6,} hoan doi")',
      ], 'Lập được bảng so sánh/hoán đổi cho cả ba thuật toán trên ba loại dữ liệu.'),
      challenge({
        slug: 'p-nc-b26-insertion-sort',
        title: 'Thử thách hiệu năng: Insertion Sort',
        statement: [
          'Cài đặt **Insertion Sort** (không dùng `sorted()` hay `list.sort()`).',
          '',
          'Dòng đầu: số nguyên `N`. Dòng hai: `N` số nguyên cách nhau bằng dấu cách.',
          '',
          'In ra **một dòng** là mảng đã sắp xếp tăng dần, các số cách nhau bằng một dấu cách.',
          '',
          '⚠️ **Bài có chấm hiệu năng.** Bài của em chạy ở N = 100, 1 000, 10 000 với dữ liệu ' +
            '**gần như đã sắp xếp** — đây chính là trường hợp Insertion Sort toả sáng, đạt gần `O(n)`.',
          '',
          'Sau khi nộp, hãy so sánh biểu đồ của em với đường cong `O(n)` và `O(n²)` để thấy ' +
            'dữ liệu đầu vào ảnh hưởng thế nào tới hiệu năng thực tế.',
        ].join('\n'),
        hints: [
          'Vòng ngoài chạy từ chỉ số 1 tới hết mảng.',
          'Vòng trong đẩy các phần tử lớn hơn sang phải bằng `m[j + 1] = m[j]`.',
          'Đặt phần tử hiện tại vào `m[j + 1]` sau khi vòng `while` kết thúc.',
          'In một lần bằng `" ".join(map(str, mang))`, đừng gọi `print` nhiều lần.',
        ],
        starterCode: [
          'import sys',
          '',
          '',
          'def insertion_sort(mang):',
          '    """Sap xep tang dan tai cho. Khong dung sorted()."""',
          '    pass',
          '',
          '',
          'du_lieu = sys.stdin.read().split()',
          'n = int(du_lieu[0])',
          'mang = [int(x) for x in du_lieu[1:1 + n]]',
          '',
          'insertion_sort(mang)',
          'sys.stdout.write(" ".join(map(str, mang)) + "\\n")',
        ].join('\n'),
        solutionCode: [
          'import sys',
          '',
          '',
          'def insertion_sort(mang):',
          '    for i in range(1, len(mang)):',
          '        hien_tai = mang[i]',
          '        j = i - 1',
          '        while j >= 0 and mang[j] > hien_tai:',
          '            mang[j + 1] = mang[j]',
          '            j -= 1',
          '        mang[j + 1] = hien_tai',
          '    return mang',
          '',
          '',
          'du_lieu = sys.stdin.read().split()',
          'n = int(du_lieu[0])',
          'mang = [int(x) for x in du_lieu[1:1 + n]]',
          '',
          'insertion_sort(mang)',
          'sys.stdout.write(" ".join(map(str, mang)) + "\\n")',
        ].join('\n'),
        tier: 'CO_BAN',
        judgeMode: 'PERFORMANCE',
        timeLimitMs: 5000,
        tests: [
          sample('5\n5 2 8 1 9\n', '1 2 5 8 9\n', 'Sắp xếp tăng dần.'),
          sample('1\n42\n', '42\n', 'Mảng một phần tử đã sắp xếp sẵn.'),
          hidden('4\n1 2 3 4\n', '1 2 3 4\n', 20),
          hidden('4\n4 3 2 1\n', '1 2 3 4\n', 20),
          hidden('6\n3 3 1 1 2 2\n', '1 1 2 2 3 3\n', 20),
          hidden('5\n-5 0 -10 3 -1\n', '-10 -5 -1 0 3\n', 20),
          hidden('3\n1000000 -1000000 0\n', '-1000000 0 1000000\n', 20),
        ],
        perfScenarios: [
          {
            label: 'N = 100 (gần như đã sắp xếp)',
            n: 100,
            generator: 'mang_gan_nhu_sap_xep',
            seed: 11,
            maxTimeMs: 1000,
            expectedComplexity: 'O(n) khi gần sắp xếp',
          },
          {
            label: 'N = 1 000 (gần như đã sắp xếp)',
            n: 1_000,
            generator: 'mang_gan_nhu_sap_xep',
            seed: 11,
            maxTimeMs: 1500,
            expectedComplexity: 'O(n) khi gần sắp xếp',
          },
          {
            label: 'N = 10 000 (gần như đã sắp xếp)',
            n: 10_000,
            generator: 'mang_gan_nhu_sap_xep',
            seed: 11,
            maxTimeMs: 5000,
            expectedComplexity: 'O(n) khi gần sắp xếp',
          },
        ],
      }),
    ],
  },
];
