/**
 * Python Nâng Cao — Chương 3: Regex & Web API (Buổi 17–22).
 *
 * Teacher note 16 — "the judge must support specific dependency environments".
 * Web problems run on RuntimeImage.PY_WEB, which ships `requests` plus a local
 * mock API bound to 127.0.0.1:8000 fed by each problem's `mockFixtures`.
 * `requests` works, results are reproducible, and the sandbox still has no egress.
 */
import type { LessonSpec, ModuleSpec } from '../types.ts';
import {
  challenge,
  example,
  hidden,
  playground,
  projectBlock,
  quizBlock,
  sample,
  theory,
} from '../builders.ts';

/** Shared fixture set served on 127.0.0.1:8000 for the Web API lessons. */
const FIXTURES_HOC_SINH = {
  baseUrl: 'http://127.0.0.1:8000',
  routes: [
    {
      method: 'GET',
      path: '/api/hoc-sinh',
      status: 200,
      json: {
        tong: 5,
        ket_qua: [
          { id: 1, ho_ten: 'Nguyen Thi Lan', lop: '7A1', diem: 8.5 },
          { id: 2, ho_ten: 'Tran Van Minh', lop: '7A1', diem: 7.0 },
          { id: 3, ho_ten: 'Le Thi Hoa', lop: '7A2', diem: 9.5 },
          { id: 4, ho_ten: 'Pham Van Nam', lop: '7A2', diem: 5.5 },
          { id: 5, ho_ten: 'Vo Thi Mai', lop: '7A1', diem: 6.0 },
        ],
      },
    },
    {
      method: 'GET',
      path: '/api/hoc-sinh/1',
      status: 200,
      json: { id: 1, ho_ten: 'Nguyen Thi Lan', lop: '7A1', diem: 8.5 },
    },
    {
      method: 'GET',
      path: '/api/hoc-sinh/999',
      status: 404,
      json: { loi: 'Khong tim thay hoc sinh' },
    },
    {
      method: 'POST',
      path: '/api/hoc-sinh',
      status: 201,
      json: { id: 6, trang_thai: 'da_tao' },
    },
    { method: 'GET', path: '/api/loi-server', status: 500, json: { loi: 'Su co may chu' } },
  ],
} as const;

const advancedLessons17to22: LessonSpec[] = [
  {
    order: 17,
    slug: 'nc-b17-regex-co-ban',
    title: 'Biểu thức chính quy: cú pháp `re` cơ bản',
    summary:
      'Một ngôn ngữ nhỏ để mô tả **mẫu** trong văn bản. Thay vì viết 30 dòng kiểm tra chuỗi, ' +
      'em viết một dòng regex.',
    objectives: [
      'Dùng các hàm `re.search`, `re.match`, `re.findall`, `re.sub`',
      'Viết mẫu với lớp ký tự và bộ định lượng',
      'Dùng neo `^`, `$` và ranh giới từ `\\b`',
      'Kiểm tra được định dạng email và số điện thoại',
    ],
    difficulty: 4,
    status: 'REQUIRED',
    teacherNotes:
      'Regex khó nhớ — cho học sinh dùng bảng tra cứu thoải mái. Mục tiêu là ĐỌC HIỂU và viết được ' +
      'mẫu đơn giản, không phải học thuộc.',
    blocks: [
      theory('Bảng tra cứu regex', [
        '**Lớp ký tự — khớp một ký tự:**',
        '',
        '| Mẫu | Khớp với |',
        '|---|---|',
        '| `\\d` | Một chữ số `0-9` |',
        '| `\\w` | Chữ cái, chữ số hoặc `_` |',
        '| `\\s` | Khoảng trắng, tab, xuống dòng |',
        '| `.` | Ký tự bất kỳ (trừ xuống dòng) |',
        '| `[abc]` | Một trong a, b, c |',
        '| `[a-z]` | Một chữ thường |',
        '| `[^abc]` | Bất kỳ ký tự nào **trừ** a, b, c |',
        '',
        'Viết hoa thì đảo nghĩa: `\\D` = **không** phải chữ số, `\\W`, `\\S` tương tự.',
        '',
        '**Bộ định lượng — số lần lặp:**',
        '',
        '| Mẫu | Ý nghĩa |',
        '|---|---|',
        '| `*` | 0 lần trở lên |',
        '| `+` | 1 lần trở lên |',
        '| `?` | 0 hoặc 1 lần |',
        '| `{3}` | Đúng 3 lần |',
        '| `{2,5}` | Từ 2 đến 5 lần |',
        '| `{2,}` | Từ 2 lần trở lên |',
        '',
        '**Neo — vị trí:**',
        '',
        '| Mẫu | Ý nghĩa |',
        '|---|---|',
        '| `^` | Đầu chuỗi |',
        '| `$` | Cuối chuỗi |',
        '| `\\b` | Ranh giới từ |',
        '',
        '⚠️ **Luôn dùng chuỗi thô `r"..."`** cho regex. Không có `r`, Python sẽ hiểu `\\d` theo cách khác ' +
          'và mẫu của em sẽ sai một cách khó hiểu.',
      ], [
        '`\\d` số, `\\w` chữ, `\\s` khoảng trắng',
        '`+` một lần trở lên, `*` không hoặc nhiều, `?` không hoặc một',
        '`^` đầu chuỗi, `$` cuối chuỗi',
        'LUÔN dùng `r"..."` cho mẫu regex',
      ]),
      theory('Năm hàm của module `re`', [
        '```python',
        'import re',
        '',
        'van_ban = "Lien he: lan@dyelms.vn hoac minh@gmail.com"',
        '',
        '# 1. search - tim khop DAU TIEN o BAT KY dau',
        'kq = re.search(r"\\w+@\\w+\\.\\w+", van_ban)',
        'print(kq.group())          # lan@dyelms.vn',
        'print(kq.start())          # 9  - vi tri bat dau',
        '',
        '# 2. match - chi khop tu DAU chuoi',
        'print(re.match(r"Lien", van_ban))     # co khop',
        'print(re.match(r"minh", van_ban))     # None - vi khong o dau',
        '',
        '# 3. findall - tim TAT CA, tra ve danh sach',
        'print(re.findall(r"\\w+@\\w+\\.\\w+", van_ban))',
        '# [\'lan@dyelms.vn\', \'minh@gmail.com\']',
        '',
        '# 4. sub - thay the',
        'print(re.sub(r"\\w+@\\w+\\.\\w+", "[an]", van_ban))',
        '# Lien he: [an] hoac [an]',
        '',
        '# 5. split - tach chuoi theo mau',
        'print(re.split(r"[,;]\\s*", "a, b; c,d"))',
        '# [\'a\', \'b\', \'c\', \'d\']',
        '```',
        '',
        '⚠️ **`search` và `match` trả về `None` khi không khớp**, không phải chuỗi rỗng. ' +
          'Gọi `.group()` trên `None` sẽ gây `AttributeError`:',
        '',
        '```python',
        'kq = re.search(mau, van_ban)',
        'if kq:                     # LUON kiem tra truoc',
        '    print(kq.group())',
        '```',
        '',
        '💡 Dùng cùng một mẫu nhiều lần thì nên **biên dịch trước** cho nhanh:',
        '',
        '```python',
        'MAU_EMAIL = re.compile(r"\\w+@\\w+\\.\\w+")',
        'MAU_EMAIL.findall(van_ban)',
        '```',
      ], [
        '`search` tìm ở bất kỳ đâu, `match` chỉ ở đầu chuỗi',
        '`findall` trả danh sách, `sub` thay thế, `split` tách',
        '`search`/`match` trả `None` khi không khớp — luôn kiểm tra',
        '`re.compile()` khi dùng lại nhiều lần',
      ]),
      example('Bộ kiểm tra định dạng', 'Năm mẫu regex thực dụng, dùng được ngay.', [
        'import re',
        '',
        'MAU = {',
        '    "Email":        r"^[\\w.+-]+@[\\w-]+\\.[\\w.]+$",',
        '    "SDT Viet Nam": r"^0\\d{9}$",',
        '    "Ma hoc sinh":  r"^HS\\d{4}$",',
        '    "Ngay dd/mm/yyyy": r"^\\d{2}/\\d{2}/\\d{4}$",',
        '    "Mat khau manh": r"^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d).{8,}$",',
        '}',
        '',
        'DU_LIEU = {',
        '    "Email": ["lan@dyelms.vn", "minh.van+hoc@gmail.com", "sai@", "@sai.com"],',
        '    "SDT Viet Nam": ["0912345678", "0987654321", "912345678", "09123456789"],',
        '    "Ma hoc sinh": ["HS0001", "HS1234", "HS12", "AB1234"],',
        '    "Ngay dd/mm/yyyy": ["16/08/2026", "1/8/2026", "16-08-2026"],',
        '    "Mat khau manh": ["Abcd1234", "abcd1234", "ABCD1234", "Ab1"],',
        '}',
        '',
        'for ten, mau in MAU.items():',
        '    print(f"=== {ten} ===")',
        '    print(f"    mau: {mau}")',
        '    for gia_tri in DU_LIEU[ten]:',
        '        khop = "OK " if re.match(mau, gia_tri) else "SAI"',
        '        print(f"    [{khop}] {gia_tri}")',
        '    print()',
        '',
        'print("=== Trich xuat tu van ban ===")',
        'van_ban = """Lop 7A1 co 32 hoc sinh.',
        'Lien he co Lan: lan@dyelms.vn hoac 0912345678.',
        'Lop 7A2 co 30 hoc sinh, thay Minh: minh@dyelms.vn."""',
        '',
        'print("So :", re.findall(r"\\d+", van_ban))',
        'print("Mail:", re.findall(r"[\\w.+-]+@[\\w.-]+", van_ban))',
        'print("Lop:", re.findall(r"\\b\\d[A-Z]\\d\\b", van_ban))',
      ], {
        output: [
          '=== Email ===',
          '    [OK ] lan@dyelms.vn',
          '    [OK ] minh.van+hoc@gmail.com',
          '    [SAI] sai@',
          '    [SAI] @sai.com',
          '',
          '=== SDT Viet Nam ===',
          '    [OK ] 0912345678',
          '    [SAI] 912345678',
          '    [SAI] 09123456789',
          '',
          '=== Trich xuat tu van ban ===',
          "So : ['7', '1', '32', '0912345678', '7', '2', '30']",
          "Mail: ['lan@dyelms.vn', 'minh@dyelms.vn']",
          "Lop: ['7A1', '7A2']",
        ].join('\n'),
        notes: [
          '`^` và `$` rất quan trọng: thiếu chúng, `"09123456789"` (11 số) vẫn khớp mẫu 10 số ở phần đầu.',
          'Mẫu mật khẩu dùng `(?=...)` — lookahead, sẽ học kỹ ở buổi 18.',
          '`\\b\\d[A-Z]\\d\\b` khớp mã lớp như `7A1`; `\\b` bảo đảm không cắt giữa một từ dài hơn.',
        ],
      }),
      playground('Sân chơi: viết mẫu của em', [
        'Viết regex cho từng yêu cầu, rồi kiểm tra bằng các trường hợp cho sẵn:',
        '',
        '1. Mã số thuế Việt Nam: 10 chữ số',
        '2. Biển số xe máy: `59-X1 123.45`',
        '3. Giờ 24h: `HH:MM` từ `00:00` đến `23:59`',
        '4. Tên tệp ảnh: kết thúc bằng `.jpg`, `.png` hoặc `.gif`',
      ], [
        'import re',
        '',
        'BAI_TAP = [',
        '    ("Ma so thue", r"^\\d{10}$",',
        '     ["0123456789", "012345678", "01234567890", "abcdefghij"]),',
        '    ("Gio 24h", r"^([01]\\d|2[0-3]):[0-5]\\d$",',
        '     ["09:30", "23:59", "24:00", "9:30"]),',
        '    ("Ten anh", r"", ["hinh.jpg", "anh.PNG", "tai_lieu.pdf"]),',
        ']',
        '',
        'for ten, mau, cac_gia_tri in BAI_TAP:',
        '    print(f"=== {ten} ===")',
        '    if not mau:',
        '        print("    (chua viet mau)")',
        '        continue',
        '    for gt in cac_gia_tri:',
        '        print(f"    [{\'OK \' if re.match(mau, gt) else \'SAI\'}] {gt}")',
      ], 'Viết được ít nhất ba mẫu đúng, xử lý được cả trường hợp hợp lệ lẫn không hợp lệ.'),
      challenge({
        slug: 'p-nc-b17-trich-xuat-thong-tin',
        title: 'Trích xuất thông tin bằng regex',
        statement: [
          'Dòng đầu: số nguyên `N`. `N` dòng tiếp theo là văn bản cần xử lý.',
          '',
          'Ghép **tất cả** các dòng lại (nối bằng ký tự xuống dòng) rồi in ra **ba dòng**:',
          '',
          '```',
          'Email: <danh sach>',
          'SDT: <danh sach>',
          'So: <tong>',
          '```',
          '',
          '- `Email` — mọi email khớp mẫu `[\\w.+-]+@[\\w-]+\\.[\\w.-]+`, nối bằng dấu phẩy và ' +
            'một dấu cách. Không có thì in `khong co`.',
          '- `SDT` — mọi số điện thoại gồm **đúng 10 chữ số bắt đầu bằng 0**, có ranh giới từ ' +
            '(`\\b0\\d{9}\\b`). Không có thì in `khong co`.',
          '- `So` — **tổng** của tất cả các cụm chữ số liên tiếp (`\\d+`) trong văn bản, ' +
            'kể cả những cụm đã nằm trong email hay số điện thoại.',
        ].join('\n'),
        hints: [
          'Đọc N dòng vào danh sách rồi `"\\n".join(...)`.',
          '`re.findall` trả về danh sách; dùng `", ".join(...)` để in.',
          'Tổng số: `sum(int(x) for x in re.findall(r"\\d+", van_ban))`.',
          'Nhớ `\\b` ở mẫu số điện thoại, nếu không sẽ khớp nhầm 10 số đầu của một số 11 chữ số.',
        ],
        starterCode: [
          'import re',
          '',
          'n = int(input())',
          'cac_dong = [input() for _ in range(n)]',
          'van_ban = "\\n".join(cac_dong)',
          '',
          '# Trich xuat email, sdt, va tinh tong so',
        ].join('\n'),
        solutionCode: [
          'import re',
          '',
          'n = int(input())',
          'cac_dong = [input() for _ in range(n)]',
          'van_ban = "\\n".join(cac_dong)',
          '',
          'email = re.findall(r"[\\w.+-]+@[\\w-]+\\.[\\w.-]+", van_ban)',
          'sdt = re.findall(r"\\b0\\d{9}\\b", van_ban)',
          'tong = sum(int(x) for x in re.findall(r"\\d+", van_ban))',
          '',
          'print(f"Email: {\', \'.join(email) if email else \'khong co\'}")',
          'print(f"SDT: {\', \'.join(sdt) if sdt else \'khong co\'}")',
          'print(f"So: {tong}")',
        ].join('\n'),
        tier: 'THU_THACH',
        judgeMode: 'IO_MATCH',
        tests: [
          sample(
            '2\nLien he lan@dyelms.vn hoac 0912345678\nLop 7A1 co 32 ban\n',
            'Email: lan@dyelms.vn\nSDT: 0912345678\nSo: 912345758\n',
            'Tổng gồm cả 0912345678 (số điện thoại) cộng 7, 1 và 32.',
          ),
          sample('1\nKhong co gi ca\n', 'Email: khong co\nSDT: khong co\nSo: 0\n'),
          hidden(
            '1\na@b.vn c@d.com\n',
            'Email: a@b.vn, c@d.com\nSDT: khong co\nSo: 0\n',
            20,
          ),
          hidden('1\n09123456789\n', 'Email: khong co\nSDT: khong co\nSo: 9123456789\n', 25),
          hidden('1\n1 2 3\n', 'Email: khong co\nSDT: khong co\nSo: 6\n', 25),
          hidden(
            '2\n0987654321\n0123456789\n',
            'Email: khong co\nSDT: 0987654321, 0123456789\nSo: 1111111110\n',
            30,
          ),
        ],
      }),
    ],
  },

  {
    order: 18,
    slug: 'nc-b18-regex-nang-cao',
    title: 'Regex nâng cao: nhóm, lookahead, thay thế',
    summary:
      'Nhóm cho phép **lấy ra** từng phần của kết quả khớp. Lookahead cho phép kiểm tra điều kiện ' +
      'mà không tiêu tốn ký tự.',
    objectives: [
      'Dùng nhóm `( )` để trích xuất từng phần',
      'Đặt tên nhóm bằng `(?P<ten>...)`',
      'Dùng lookahead `(?=...)` và lookbehind `(?<=...)`',
      'Thay thế nâng cao với tham chiếu ngược',
    ],
    difficulty: 5,
    status: 'ADVANCED',
    isDerived: true,
    teacherNotes:
      'Buổi mở rộng (⟨derived⟩) cho học sinh học nhanh. Nhóm có tên là phần thực dụng nhất, nên nhấn mạnh.',
    blocks: [
      theory('Nhóm — lấy ra từng phần', [
        '```python',
        'import re',
        '',
        'ngay = "16/08/2026"',
        'kq = re.match(r"(\\d{2})/(\\d{2})/(\\d{4})", ngay)',
        '',
        'print(kq.group())     # 16/08/2026  - toan bo',
        'print(kq.group(1))    # 16          - nhom 1',
        'print(kq.group(2))    # 08          - nhom 2',
        'print(kq.group(3))    # 2026        - nhom 3',
        'print(kq.groups())    # (\'16\', \'08\', \'2026\')',
        '```',
        '',
        '**Nhóm có tên** — dễ đọc hơn nhiều so với đếm số:',
        '',
        '```python',
        'MAU = r"(?P<ngay>\\d{2})/(?P<thang>\\d{2})/(?P<nam>\\d{4})"',
        'kq = re.match(MAU, "16/08/2026")',
        '',
        'print(kq.group("nam"))     # 2026',
        'print(kq.groupdict())      # {\'ngay\': \'16\', \'thang\': \'08\', \'nam\': \'2026\'}',
        '```',
        '',
        '`groupdict()` trả về từ điển — cực kỳ tiện khi phân tích log hay dữ liệu có cấu trúc.',
        '',
        '**`findall` với nhóm** trả về danh sách các tuple:',
        '',
        '```python',
        're.findall(r"(\\w+)@(\\w+)", "a@x b@y")',
        '# [(\'a\', \'x\'), (\'b\', \'y\')]',
        '```',
        '',
        '💡 **Nhóm không bắt** `(?:...)` — khi cần gom nhóm để dùng `|` hoặc `+` nhưng không muốn ' +
          'nó xuất hiện trong kết quả:',
        '',
        '```python',
        're.findall(r"(?:https?)://(\\w+)", "http://a https://b")',
        '# [\'a\', \'b\']  - khong co http/https trong ket qua',
        '```',
      ], [
        '`( )` tạo nhóm, `.group(n)` lấy nhóm thứ n',
        '`(?P<ten>...)` đặt tên nhóm, `.groupdict()` cho từ điển',
        '`(?:...)` gom nhóm mà không bắt',
      ]),
      theory('Lookahead, lookbehind và thay thế nâng cao', [
        '**Lookahead** kiểm tra phía sau **mà không tiêu tốn ký tự**:',
        '',
        '| Cú pháp | Ý nghĩa |',
        '|---|---|',
        '| `(?=...)` | Phía sau **phải** khớp |',
        '| `(?!...)` | Phía sau **không được** khớp |',
        '| `(?<=...)` | Phía trước **phải** khớp |',
        '| `(?<!...)` | Phía trước **không được** khớp |',
        '',
        '**Ứng dụng kinh điển — kiểm tra mật khẩu mạnh:**',
        '',
        '```python',
        'MAU = r"^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[!@#$%]).{8,}$"',
        '#        │           │           │        │          └─ it nhat 8 ky tu',
        '#        │           │           │        └─ phai co ky tu dac biet',
        '#        │           │           └─ phai co chu so',
        '#        │           └─ phai co chu HOA',
        '#        └─ phai co chu thuong',
        '```',
        '',
        'Bốn điều kiện được kiểm tra **cùng lúc trên toàn chuỗi**, rồi `.{8,}` mới thật sự khớp. ' +
          'Không có lookahead thì phải viết bốn lệnh `re.search` riêng.',
        '',
        '**Thay thế với tham chiếu ngược** — `\\1`, `\\2` trỏ tới nhóm đã bắt:',
        '',
        '```python',
        '# Doi dd/mm/yyyy thanh yyyy-mm-dd',
        're.sub(r"(\\d{2})/(\\d{2})/(\\d{4})", r"\\3-\\2-\\1", "16/08/2026")',
        '# 2026-08-16',
        '',
        '# Voi nhom co ten',
        're.sub(r"(?P<ho>\\w+) (?P<ten>\\w+)", r"\\g<ten> \\g<ho>", "Nguyen Lan")',
        '# Lan Nguyen',
        '```',
        '',
        '**Thay thế bằng hàm** — khi cần logic phức tạp:',
        '',
        '```python',
        'def tang_gap_doi(kq):',
        '    return str(int(kq.group()) * 2)',
        '',
        're.sub(r"\\d+", tang_gap_doi, "co 3 quyen va 5 cay but")',
        '# co 6 quyen va 10 cay but',
        '```',
      ], [
        '`(?=...)` kiểm tra phía sau mà không tiêu tốn ký tự',
        'Nhiều lookahead nối tiếp = nhiều điều kiện cùng lúc',
        '`\\1`, `\\g<ten>` để tham chiếu ngược khi thay thế',
        '`re.sub` nhận được cả một hàm thay cho chuỗi',
      ]),
      example('Phân tích log bằng nhóm có tên', 'Bài toán thực tế nhất của regex.', [
        'import re',
        '',
        'LOG = """2026-08-16 09:15:23 INFO  user=lan action=dang_nhap ip=192.168.1.10',
        '2026-08-16 09:16:02 ERROR user=minh action=nop_bai ip=192.168.1.22',
        '2026-08-16 09:17:45 INFO  user=hoa action=xem_bai ip=10.0.0.5',
        '2026-08-16 09:18:11 WARN  user=lan action=sai_mat_khau ip=192.168.1.10',
        '2026-08-16 09:20:00 ERROR user=nam action=nop_bai ip=172.16.0.3"""',
        '',
        'MAU_LOG = re.compile(',
        '    r"(?P<ngay>\\d{4}-\\d{2}-\\d{2})\\s+"',
        '    r"(?P<gio>\\d{2}:\\d{2}:\\d{2})\\s+"',
        '    r"(?P<muc>\\w+)\\s+"',
        '    r"user=(?P<nguoi_dung>\\w+)\\s+"',
        '    r"action=(?P<hanh_dong>\\w+)\\s+"',
        '    r"ip=(?P<ip>[\\d.]+)"',
        ')',
        '',
        'ban_ghi = []',
        'for dong in LOG.split("\\n"):',
        '    kq = MAU_LOG.match(dong)',
        '    if kq:',
        '        ban_ghi.append(kq.groupdict())',
        '',
        'print(f"Da phan tich {len(ban_ghi)} ban ghi\\n")',
        '',
        'print("=== Cac loi ===")',
        'for b in ban_ghi:',
        '    if b["muc"] == "ERROR":',
        '        print(f"  {b[\'gio\']} {b[\'nguoi_dung\']:<6} {b[\'hanh_dong\']}")',
        '',
        'print()',
        'print("=== Thong ke theo nguoi dung ===")',
        'dem = {}',
        'for b in ban_ghi:',
        '    dem[b["nguoi_dung"]] = dem.get(b["nguoi_dung"], 0) + 1',
        'for nguoi in sorted(dem):',
        '    print(f"  {nguoi:<6}: {dem[nguoi]} hanh dong")',
        '',
        'print()',
        'print("=== IP noi bo (192.168.x.x) ===")',
        'ip_noi_bo = {b["ip"] for b in ban_ghi if re.match(r"^192\\.168\\.", b["ip"])}',
        'print(" ", sorted(ip_noi_bo))',
        '',
        'print()',
        'print("=== An dia chi IP ===")',
        'print(re.sub(r"ip=[\\d.]+", "ip=***", LOG.split("\\n")[0]))',
      ], {
        output: [
          'Da phan tich 5 ban ghi',
          '',
          '=== Cac loi ===',
          '  09:16:02 minh   nop_bai',
          '  09:20:00 nam    nop_bai',
          '',
          '=== Thong ke theo nguoi dung ===',
          '  hoa   : 1 hanh dong',
          '  lan   : 2 hanh dong',
          '  minh  : 1 hanh dong',
          '  nam   : 1 hanh dong',
          '',
          '=== IP noi bo (192.168.x.x) ===',
          "  ['192.168.1.10', '192.168.1.22']",
          '',
          '=== An dia chi IP ===',
          '2026-08-16 09:15:23 INFO  user=lan action=dang_nhap ip=***',
        ].join('\n'),
        notes: [
          'Mẫu được viết trên nhiều dòng — Python tự nối các chuỗi liền nhau, nên regex dài vẫn đọc được.',
          '`groupdict()` biến mỗi dòng log thành một từ điển, sau đó xử lý như dữ liệu bình thường.',
          'Đây chính là cách các công cụ phân tích log thật hoạt động.',
        ],
      }),
      playground('Sân chơi: chuẩn hoá dữ liệu', [
        'Dùng `re.sub` để làm sạch một danh sách dữ liệu lộn xộn:',
        '',
        '1. Đổi mọi ngày `dd/mm/yyyy` và `dd-mm-yyyy` thành `yyyy-mm-dd`',
        '2. Chuẩn hoá số điện thoại: bỏ mọi dấu cách, chấm, gạch',
        '3. Ẩn email: `lan@dyelms.vn` → `l***@dyelms.vn`',
      ], [
        'import re',
        '',
        'DU_LIEU = [',
        '    "Ngay sinh: 16/08/2012",',
        '    "Ngay vao: 01-09-2024",',
        '    "SDT: 091 234 5678",',
        '    "SDT: 098.765.4321",',
        '    "Mail: lan@dyelms.vn",',
        ']',
        '',
        '',
        'def chuan_hoa_ngay(s):',
        '    return re.sub(r"(\\d{2})[/-](\\d{2})[/-](\\d{4})", r"\\3-\\2-\\1", s)',
        '',
        '',
        'def chuan_hoa_sdt(s):',
        '    # Bo dau cach, cham, gach trong cum so',
        '    return re.sub(r"(?<=\\d)[\\s.-](?=\\d)", "", s)',
        '',
        '',
        'def an_email(s):',
        '    # Viet ham thay the o day',
        '    return s',
        '',
        '',
        'for dong in DU_LIEU:',
        '    kq = an_email(chuan_hoa_sdt(chuan_hoa_ngay(dong)))',
        '    print(f"{dong:<28} -> {kq}")',
      ], 'Cả ba phép chuẩn hoá hoạt động đúng trên mọi dòng dữ liệu.'),
      challenge({
        slug: 'p-nc-b18-phan-tich-log',
        title: 'Phân tích dòng log bằng nhóm có tên',
        statement: [
          'Mỗi dòng log có định dạng:',
          '',
          '```',
          '<YYYY-MM-DD> <HH:MM:SS> <MUC> user=<ten> action=<hanh_dong>',
          '```',
          '',
          'Dòng đầu: số nguyên `N`. `N` dòng tiếp theo là các dòng log — có thể có dòng **sai định dạng**.',
          '',
          'In ra **ba dòng**:',
          '',
          '```',
          'Hop le: <so_dong_hop_le>',
          'Loi: <so_dong_muc_ERROR>',
          'Nguoi dung: <danh_sach>',
          '```',
          '',
          '`<danh_sach>` là tên người dùng **duy nhất** từ các dòng hợp lệ, sắp xếp theo bảng chữ cái, ' +
            'nối bằng dấu phẩy và một dấu cách. Không có thì in `khong co`.',
          '',
          'Dòng sai định dạng bị bỏ qua hoàn toàn.',
        ].join('\n'),
        hints: [
          'Dùng `re.match` với mẫu có `^` ở đầu và `$` ở cuối để loại dòng sai định dạng.',
          'Nhóm có tên giúp lấy `muc` và `ten` dễ đọc: `(?P<muc>\\w+)`.',
          'Dùng `set()` để loại trùng tên người dùng, rồi `sorted()`.',
        ],
        starterCode: [
          'import re',
          '',
          'MAU = re.compile(',
          '    r"^(?P<ngay>\\d{4}-\\d{2}-\\d{2}) "',
          '    r"(?P<gio>\\d{2}:\\d{2}:\\d{2}) "',
          '    r"(?P<muc>\\w+) "',
          '    r"user=(?P<ten>\\w+) "',
          '    r"action=(?P<hanh_dong>\\w+)$"',
          ')',
          '',
          'n = int(input())',
          '# Doc va phan tich n dong',
        ].join('\n'),
        solutionCode: [
          'import re',
          '',
          'MAU = re.compile(',
          '    r"^(?P<ngay>\\d{4}-\\d{2}-\\d{2}) "',
          '    r"(?P<gio>\\d{2}:\\d{2}:\\d{2}) "',
          '    r"(?P<muc>\\w+) "',
          '    r"user=(?P<ten>\\w+) "',
          '    r"action=(?P<hanh_dong>\\w+)$"',
          ')',
          '',
          'n = int(input())',
          'hop_le = 0',
          'so_loi = 0',
          'nguoi_dung = set()',
          '',
          'for _ in range(n):',
          '    dong = input().rstrip("\\n")',
          '    kq = MAU.match(dong)',
          '    if not kq:',
          '        continue',
          '    hop_le += 1',
          '    if kq.group("muc") == "ERROR":',
          '        so_loi += 1',
          '    nguoi_dung.add(kq.group("ten"))',
          '',
          'print(f"Hop le: {hop_le}")',
          'print(f"Loi: {so_loi}")',
          'ds = sorted(nguoi_dung)',
          'print(f"Nguoi dung: {\', \'.join(ds) if ds else \'khong co\'}")',
        ].join('\n'),
        tier: 'NANG_CAO',
        judgeMode: 'IO_MATCH',
        tests: [
          sample(
            '3\n2026-08-16 09:15:23 INFO user=lan action=dang_nhap\n2026-08-16 09:16:02 ERROR user=minh action=nop_bai\ndong sai dinh dang\n',
            'Hop le: 2\nLoi: 1\nNguoi dung: lan, minh\n',
            'Dòng thứ ba bị bỏ qua vì không khớp mẫu.',
          ),
          sample('1\nkhong phai log\n', 'Hop le: 0\nLoi: 0\nNguoi dung: khong co\n'),
          hidden(
            '2\n2026-01-01 00:00:00 ERROR user=a action=x\n2026-01-01 00:00:01 ERROR user=a action=y\n',
            'Hop le: 2\nLoi: 2\nNguoi dung: a\n',
            25,
          ),
          hidden(
            '3\n2026-01-01 00:00:00 INFO user=zz action=x\n2026-01-01 00:00:00 INFO user=aa action=x\n2026-01-01 00:00:00 WARN user=mm action=x\n',
            'Hop le: 3\nLoi: 0\nNguoi dung: aa, mm, zz\n',
            25,
          ),
          hidden(
            '2\n2026-1-1 00:00:00 INFO user=a action=x\n2026-01-01 00:00:00 INFO user=b action=y\n',
            'Hop le: 1\nLoi: 0\nNguoi dung: b\n',
            25,
          ),
          hidden(
            '1\n2026-01-01 00:00:00 INFO user=a action=x them_thua\n',
            'Hop le: 0\nLoi: 0\nNguoi dung: khong co\n',
            25,
          ),
        ],
      }),
    ],
  },

  {
    order: 19,
    slug: 'nc-b19-requests-get',
    title: '`requests` — GET & query params',
    summary:
      'Chương trình của em bắt đầu nói chuyện với thế giới bên ngoài. Thư viện `requests` biến ' +
      'toàn bộ HTTP của buổi 12 thành vài dòng code.',
    objectives: [
      'Gửi yêu cầu GET bằng `requests`',
      'Truyền tham số truy vấn an toàn bằng `params`',
      'Đọc `status_code`, `headers` và `json()`',
      'Xử lý lỗi mạng và mã trạng thái lỗi',
    ],
    difficulty: 4,
    status: 'REQUIRED',
    teacherNotes:
      'GHI CHÚ BẢO MẬT: môi trường chấm bài dùng ảnh PY_WEB có sẵn máy chủ mô phỏng tại ' +
      '127.0.0.1:8000. Học sinh viết code requests thật, nhưng sandbox KHÔNG có mạng ra ngoài. ' +
      'Kết quả vì thế luôn tái lập được.',
    blocks: [
      theory('GET với `requests`', [
        'Ở buổi 12 em đã thấy một yêu cầu HTTP thô dài thế nào. `requests` gói tất cả vào một dòng:',
        '',
        '```python',
        'import requests',
        '',
        'r = requests.get("http://127.0.0.1:8000/api/hoc-sinh")',
        '',
        'print(r.status_code)      # 200',
        'print(r.headers["Content-Type"])',
        'print(r.text)             # chuoi tho',
        'print(r.json())           # doi thang thanh dict/list Python',
        '```',
        '',
        '**Tham số truy vấn** — đừng bao giờ tự nối chuỗi:',
        '',
        '```python',
        '# SAI: de loi khi gia tri co dau cach hoac ky tu dac biet',
        'url = f"http://api/tim?ten={ten}&lop={lop}"',
        '',
        '# DUNG: requests tu ma hoa an toan',
        'r = requests.get("http://127.0.0.1:8000/api/hoc-sinh",',
        '                 params={"lop": "7A1", "sap_xep": "diem"})',
        'print(r.url)   # .../api/hoc-sinh?lop=7A1&sap_xep=diem',
        '```',
        '',
        '`params` tự xử lý dấu cách, dấu tiếng Việt và ký tự đặc biệt. Tự nối chuỗi là nguồn gốc ' +
          'của rất nhiều lỗi khó tìm.',
        '',
        '**Thời gian chờ — luôn đặt:**',
        '',
        '```python',
        'r = requests.get(url, timeout=5)     # toi da 5 giay',
        '```',
        '',
        '⚠️ Không có `timeout`, chương trình có thể treo **vĩnh viễn** nếu server không trả lời. ' +
          'Đây là lỗi rất phổ biến trong code thật.',
      ], [
        '`requests.get(url)` thay cho hàng chục dòng socket',
        'Dùng `params=` thay vì tự nối chuỗi URL',
        '`.json()` đổi thẳng phản hồi thành dict/list',
        'LUÔN đặt `timeout=`',
      ]),
      theory('Xử lý lỗi đúng cách', [
        'Có **hai loại lỗi** hoàn toàn khác nhau, và phải xử lý riêng:',
        '',
        '**Loại 1 — không kết nối được** (ném ngoại lệ):',
        '',
        '```python',
        'try:',
        '    r = requests.get(url, timeout=5)',
        'except requests.exceptions.Timeout:',
        '    print("Server phan hoi qua lau")',
        'except requests.exceptions.ConnectionError:',
        '    print("Khong ket noi duoc")',
        'except requests.exceptions.RequestException as loi:',
        '    print(f"Loi khac: {loi}")',
        '```',
        '',
        '**Loại 2 — kết nối được nhưng server báo lỗi** (KHÔNG ném ngoại lệ):',
        '',
        '```python',
        'r = requests.get(url)',
        'print(r.status_code)      # 404 - nhung KHONG co ngoai le nao',
        '```',
        '',
        '⚠️ **Đây là điểm nhiều người nhầm.** `requests` coi `404` và `500` là "yêu cầu đã hoàn tất ' +
          'thành công, và câu trả lời là lỗi". Em phải tự kiểm tra:',
        '',
        '```python',
        'if r.status_code == 200:',
        '    du_lieu = r.json()',
        'elif r.status_code == 404:',
        '    print("Khong tim thay")',
        'else:',
        '    print(f"Loi {r.status_code}")',
        '```',
        '',
        'Hoặc dùng `r.raise_for_status()` để biến `4xx`/`5xx` thành ngoại lệ:',
        '',
        '```python',
        'try:',
        '    r = requests.get(url, timeout=5)',
        '    r.raise_for_status()          # nem HTTPError neu 4xx hoac 5xx',
        '    du_lieu = r.json()',
        'except requests.exceptions.HTTPError as loi:',
        '    print(f"Server tra ve loi: {loi.response.status_code}")',
        'except requests.exceptions.RequestException as loi:',
        '    print(f"Khong goi duoc: {loi}")',
        '```',
        '',
        '💡 `r.ok` là cách viết tắt cho `r.status_code < 400`.',
      ], [
        'Lỗi kết nối → ngoại lệ; lỗi HTTP 4xx/5xx → KHÔNG ngoại lệ',
        'Luôn kiểm tra `status_code` hoặc gọi `raise_for_status()`',
        '`RequestException` là lớp cha bắt được mọi lỗi của requests',
      ]),
      example('Gọi API và xử lý đầy đủ', 'Chạy trong môi trường có máy chủ mô phỏng tại 127.0.0.1:8000.', [
        'import requests',
        '',
        'GOC = "http://127.0.0.1:8000"',
        '',
        '',
        'def goi_api(duong_dan, params=None):',
        '    """Goi API va tra ve (thanh_cong, du_lieu_hoac_thong_bao)."""',
        '    try:',
        '        r = requests.get(f"{GOC}{duong_dan}", params=params, timeout=5)',
        '    except requests.exceptions.Timeout:',
        '        return False, "Server phan hoi qua lau"',
        '    except requests.exceptions.ConnectionError:',
        '        return False, "Khong ket noi duoc server"',
        '    except requests.exceptions.RequestException as loi:',
        '        return False, f"Loi goi API: {loi}"',
        '',
        '    if r.status_code == 200:',
        '        return True, r.json()',
        '    if r.status_code == 404:',
        '        return False, "Khong tim thay du lieu"',
        '    if r.status_code >= 500:',
        '        return False, f"Server gap su co ({r.status_code})"',
        '    return False, f"Loi {r.status_code}"',
        '',
        '',
        'print("=== 1. Lay danh sach hoc sinh ===")',
        'ok, du_lieu = goi_api("/api/hoc-sinh")',
        'if ok:',
        '    print(f"  Tong: {du_lieu[\'tong\']} hoc sinh")',
        '    for hs in du_lieu["ket_qua"]:',
        '        print(f"    {hs[\'ho_ten\']:<20} {hs[\'lop\']:<6} {hs[\'diem\']}")',
        'else:',
        '    print(f"  Loi: {du_lieu}")',
        '',
        'print()',
        'print("=== 2. Lay mot hoc sinh ===")',
        'ok, hs = goi_api("/api/hoc-sinh/1")',
        'print(f"  {hs if ok else \'Loi: \' + str(hs)}")',
        '',
        'print()',
        'print("=== 3. Hoc sinh khong ton tai ===")',
        'ok, thong_bao = goi_api("/api/hoc-sinh/999")',
        'print(f"  Thanh cong: {ok}")',
        'print(f"  Ket qua   : {thong_bao}")',
        '',
        'print()',
        'print("=== 4. Server gap su co ===")',
        'ok, thong_bao = goi_api("/api/loi-server")',
        'print(f"  Thanh cong: {ok}")',
        'print(f"  Ket qua   : {thong_bao}")',
      ], {
        output: [
          '=== 1. Lay danh sach hoc sinh ===',
          '  Tong: 5 hoc sinh',
          '    Nguyen Thi Lan       7A1    8.5',
          '    Tran Van Minh        7A1    7.0',
          '    Le Thi Hoa           7A2    9.5',
          '    Pham Van Nam         7A2    5.5',
          '    Vo Thi Mai           7A1    6.0',
          '',
          '=== 3. Hoc sinh khong ton tai ===',
          '  Thanh cong: False',
          '  Ket qua   : Khong tim thay du lieu',
          '',
          '=== 4. Server gap su co ===',
          '  Thanh cong: False',
          '  Ket qua   : Server gap su co (500)',
          ].join('\n'),
        notes: [
          'Mẫu `(thanh_cong, du_lieu)` giúp nơi gọi luôn phải xử lý trường hợp lỗi — không thể quên.',
          '`404` và `500` đều **không** ném ngoại lệ; hàm tự kiểm tra `status_code`.',
          'Địa chỉ `127.0.0.1:8000` là máy chủ mô phỏng ngay trong sandbox — không có kết nối ra Internet.',
        ],
      }),
      playground('Sân chơi: khám phá API', [
        'Thử gọi các đường dẫn khác nhau của máy chủ mô phỏng và quan sát:',
        '',
        '- `/api/hoc-sinh` — danh sách đầy đủ',
        '- `/api/hoc-sinh/1` — một học sinh',
        '- `/api/hoc-sinh/999` — mã 404',
        '- `/api/loi-server` — mã 500',
        '',
        'Với mỗi lần gọi, in `status_code`, `headers` và `json()`.',
      ], [
        'import requests',
        '',
        'GOC = "http://127.0.0.1:8000"',
        '',
        'for duong_dan in ["/api/hoc-sinh", "/api/hoc-sinh/1",',
        '                  "/api/hoc-sinh/999", "/api/loi-server"]:',
        '    r = requests.get(GOC + duong_dan, timeout=5)',
        '    print(f"=== {duong_dan} ===")',
        '    print(f"  Ma       : {r.status_code}")',
        '    print(f"  Loai     : {r.headers.get(\'Content-Type\')}")',
        '    print(f"  Du lieu  : {str(r.json())[:80]}")',
        '    print()',
      ], 'Gọi được cả bốn đường dẫn và phân biệt được phản hồi thành công với phản hồi lỗi.'),
      challenge({
        slug: 'p-nc-b19-goi-api-hoc-sinh',
        title: 'Gọi API danh sách học sinh',
        statement: [
          'Máy chủ mô phỏng chạy tại `http://127.0.0.1:8000`. Đường dẫn `/api/hoc-sinh` trả về:',
          '',
          '```json',
          '{ "tong": 5, "ket_qua": [ { "id": 1, "ho_ten": "...", "lop": "...", "diem": 8.5 }, ... ] }',
          '```',
          '',
          'Viết ba hàm:',
          '',
          '**`lay_danh_sach()`** — gọi `GET /api/hoc-sinh` với `timeout=5`. Trả về **danh sách** ' +
            'trong khoá `ket_qua` nếu `status_code == 200`, ngược lại trả về danh sách **rỗng**. ' +
            'Mọi ngoại lệ của `requests` cũng phải trả về danh sách rỗng.',
          '',
          '**`loc_theo_lop(danh_sach, lop)`** — trả về danh sách các học sinh có `lop` khớp.',
          '',
          '**`diem_trung_binh(danh_sach)`** — trung bình cộng của khoá `diem`; trả về `0.0` ' +
            'nếu danh sách rỗng.',
          '',
          'Hai hàm sau là **thuần logic** và được kiểm tra riêng, không cần gọi mạng.',
        ].join('\n'),
        hints: [
          'Bọc lời gọi trong `try`/`except requests.exceptions.RequestException`.',
          'Nhớ kiểm tra `r.status_code == 200` trước khi gọi `.json()`.',
          '`loc_theo_lop` viết gọn bằng list comprehension.',
          '`diem_trung_binh` phải kiểm tra danh sách rỗng trước khi chia.',
        ],
        starterCode: [
          'import requests',
          '',
          'GOC = "http://127.0.0.1:8000"',
          '',
          '',
          'def lay_danh_sach():',
          '    """Tra ve danh sach hoc sinh, hoac [] neu that bai."""',
          '    pass',
          '',
          '',
          'def loc_theo_lop(danh_sach, lop):',
          '    pass',
          '',
          '',
          'def diem_trung_binh(danh_sach):',
          '    pass',
        ].join('\n'),
        solutionCode: [
          'import requests',
          '',
          'GOC = "http://127.0.0.1:8000"',
          '',
          '',
          'def lay_danh_sach():',
          '    try:',
          '        r = requests.get(f"{GOC}/api/hoc-sinh", timeout=5)',
          '    except requests.exceptions.RequestException:',
          '        return []',
          '',
          '    if r.status_code != 200:',
          '        return []',
          '    return r.json().get("ket_qua", [])',
          '',
          '',
          'def loc_theo_lop(danh_sach, lop):',
          '    return [hs for hs in danh_sach if hs.get("lop") == lop]',
          '',
          '',
          'def diem_trung_binh(danh_sach):',
          '    if not danh_sach:',
          '        return 0.0',
          '    return sum(hs["diem"] for hs in danh_sach) / len(danh_sach)',
        ].join('\n'),
        tier: 'THU_THACH',
        judgeMode: 'UNIT_TEST',
        runtimeImage: 'PY_WEB',
        networkPolicy: 'NONE',
        mockFixtures: FIXTURES_HOC_SINH,
        timeLimitMs: 10000,
        unitTestCode: [
          'from solution import diem_trung_binh, lay_danh_sach, loc_theo_lop',
          '',
          'MAU = [',
          '    {"id": 1, "ho_ten": "A", "lop": "7A1", "diem": 8.0},',
          '    {"id": 2, "ho_ten": "B", "lop": "7A2", "diem": 6.0},',
          '    {"id": 3, "ho_ten": "C", "lop": "7A1", "diem": 10.0},',
          ']',
          '',
          '',
          'def test_lay_danh_sach_tu_api():',
          '    ds = lay_danh_sach()',
          '    assert isinstance(ds, list)',
          '    assert len(ds) == 5',
          '    assert ds[0]["ho_ten"] == "Nguyen Thi Lan"',
          '    assert ds[2]["diem"] == 9.5',
          '',
          '',
          'def test_moi_ban_ghi_du_khoa():',
          '    for hs in lay_danh_sach():',
          '        for khoa in ("id", "ho_ten", "lop", "diem"):',
          '            assert khoa in hs',
          '',
          '',
          'def test_loc_theo_lop():',
          '    assert len(loc_theo_lop(MAU, "7A1")) == 2',
          '    assert len(loc_theo_lop(MAU, "7A2")) == 1',
          '    assert loc_theo_lop(MAU, "8B1") == []',
          '',
          '',
          'def test_loc_tren_du_lieu_that():',
          '    ds = lay_danh_sach()',
          '    assert len(loc_theo_lop(ds, "7A1")) == 3',
          '    assert len(loc_theo_lop(ds, "7A2")) == 2',
          '',
          '',
          'def test_diem_trung_binh():',
          '    assert abs(diem_trung_binh(MAU) - 8.0) < 1e-9',
          '',
          '',
          'def test_diem_trung_binh_rong():',
          '    assert diem_trung_binh([]) == 0.0',
          '',
          '',
          'def test_ket_hop():',
          '    ds = lay_danh_sach()',
          '    lop_7a1 = loc_theo_lop(ds, "7A1")',
          '    assert abs(diem_trung_binh(lop_7a1) - 7.1666666) < 1e-4',
        ].join('\n'),
        totalPoints: 100,
      }),
    ],
  },

  {
    order: 20,
    slug: 'nc-b20-post-headers-status',
    title: 'POST, headers, status code & xử lý lỗi HTTP',
    summary:
      'Gửi dữ liệu lên server, đính kèm thông tin xác thực, và xây một lớp client API dùng lại được.',
    objectives: [
      'Gửi dữ liệu bằng `POST` với `json=`',
      'Đính kèm header, kể cả header xác thực',
      'Dùng `Session` để tái sử dụng cấu hình',
      'Cài đặt cơ chế thử lại có độ trễ tăng dần',
    ],
    difficulty: 4,
    status: 'REQUIRED',
    isDerived: true,
    teacherNotes:
      'Buổi mở rộng (⟨derived⟩) hoàn thiện phần requests. Phần Session và retry là kiến thức thực dụng ' +
      'mà học sinh dùng được ngay ở dự án buổi 22.',
    blocks: [
      theory('POST và headers', [
        '```python',
        'import requests',
        '',
        '# Gui JSON - cach dung nhieu nhat voi API hien dai',
        'r = requests.post(',
        '    "http://127.0.0.1:8000/api/hoc-sinh",',
        '    json={"ho_ten": "Nguyen Van A", "lop": "7A1", "diem": 8.0},',
        '    timeout=5,',
        ')',
        'print(r.status_code)      # 201 Created',
        'print(r.json())',
        '```',
        '',
        '**Ba cách gửi dữ liệu, đừng nhầm:**',
        '',
        '| Tham số | Kiểu dữ liệu gửi đi | Content-Type |',
        '|---|---|---|',
        '| `json={...}` | JSON | `application/json` |',
        '| `data={...}` | Form | `application/x-www-form-urlencoded` |',
        '| `files={...}` | Tệp | `multipart/form-data` |',
        '',
        'Dùng `json=` thì `requests` tự đặt `Content-Type` và tự chuyển dict thành JSON. ' +
          'Không cần `json.dumps()` thủ công.',
        '',
        '**Headers — thông tin đi kèm yêu cầu:**',
        '',
        '```python',
        'r = requests.get(url, headers={',
        '    "Authorization": "Bearer abc123",     # xac thuc',
        '    "Accept": "application/json",         # muon nhan dinh dang gi',
        '    "User-Agent": "DYE-LMS/1.0",          # ung dung nao dang goi',
        '})',
        '```',
        '',
        '🔒 **Không bao giờ viết thẳng khoá bí mật vào code.** Đọc từ biến môi trường:',
        '',
        '```python',
        'import os',
        '',
        'khoa = os.environ.get("API_KEY")',
        'if not khoa:',
        '    raise RuntimeError("Chua dat bien moi truong API_KEY")',
        '```',
        '',
        'Viết khoá vào code rồi đưa lên GitHub là sự cố bảo mật rất phổ biến và rất tốn kém.',
      ], [
        '`json=` cho API hiện đại, `data=` cho form',
        'Headers mang thông tin xác thực và định dạng mong muốn',
        'KHÔNG BAO GIỜ viết khoá bí mật vào code — dùng biến môi trường',
      ]),
      theory('Session và thử lại', [
        '**`Session`** giữ lại cấu hình chung và tái sử dụng kết nối TCP — nhanh hơn hẳn khi gọi nhiều lần:',
        '',
        '```python',
        'phien = requests.Session()',
        'phien.headers.update({',
        '    "Authorization": "Bearer abc123",',
        '    "Accept": "application/json",',
        '})',
        '',
        '# Moi lan goi deu tu co header tren',
        'r1 = phien.get(f"{GOC}/api/hoc-sinh")',
        'r2 = phien.get(f"{GOC}/api/hoc-sinh/1")',
        '',
        'phien.close()',
        '```',
        '',
        '**Thử lại với độ trễ tăng dần** — lỗi mạng thường chỉ là tạm thời:',
        '',
        '```python',
        'import time',
        '',
        '',
        'def goi_co_thu_lai(url, so_lan=3):',
        '    """Thu lai voi do tre tang dan: 1s, 2s, 4s."""',
        '    for lan in range(so_lan):',
        '        try:',
        '            r = requests.get(url, timeout=5)',
        '            if r.status_code < 500:',
        '                return r          # 4xx la loi cua ta, thu lai vo ich',
        '        except requests.exceptions.RequestException:',
        '            pass',
        '',
        '        if lan < so_lan - 1:',
        '            time.sleep(2 ** lan)   # 1, 2, 4 giay',
        '    return None',
        '```',
        '',
        '⚠️ **Chỉ thử lại với lỗi `5xx` và lỗi mạng.** Lỗi `4xx` là do yêu cầu của em sai — ' +
          'gửi lại y hệt thì vẫn sai, chỉ tốn thời gian và làm phiền server.',
        '',
        'Độ trễ tăng dần (1s, 2s, 4s) gọi là **exponential backoff**. Nó tránh việc hàng nghìn ' +
          'client cùng dội vào một server vừa hồi phục.',
      ], [
        '`Session` giữ header chung và tái dùng kết nối',
        'Chỉ thử lại với 5xx và lỗi mạng, không thử lại 4xx',
        'Độ trễ tăng dần tránh dội server đang hồi phục',
      ]),
      example('Lớp client API dùng lại được', 'Bộ khung em dùng cho dự án buổi 22.', [
        'import time',
        '',
        'import requests',
        '',
        '',
        'class ApiClient:',
        '    """Client goi API co xu ly loi va thu lai."""',
        '',
        '    def __init__(self, goc, timeout=5, so_lan_thu=3):',
        '        self.goc = goc.rstrip("/")',
        '        self.timeout = timeout',
        '        self.so_lan_thu = so_lan_thu',
        '        self.phien = requests.Session()',
        '        self.phien.headers.update({',
        '            "Accept": "application/json",',
        '            "User-Agent": "DYE-LMS/1.0",',
        '        })',
        '',
        '    def __enter__(self):',
        '        return self',
        '',
        '    def __exit__(self, *args):',
        '        self.phien.close()',
        '        return False',
        '',
        '    def _goi(self, phuong_thuc, duong_dan, **kwargs):',
        '        url = f"{self.goc}{duong_dan}"',
        '        kwargs.setdefault("timeout", self.timeout)',
        '',
        '        for lan in range(self.so_lan_thu):',
        '            try:',
        '                r = self.phien.request(phuong_thuc, url, **kwargs)',
        '            except requests.exceptions.RequestException:',
        '                r = None',
        '',
        '            if r is not None and r.status_code < 500:',
        '                return r          # thanh cong hoac loi 4xx: khong thu lai',
        '',
        '            if lan < self.so_lan_thu - 1:',
        '                time.sleep(0.1 * (2 ** lan))',
        '',
        '        return None',
        '',
        '    def get(self, duong_dan, params=None):',
        '        return self._goi("GET", duong_dan, params=params)',
        '',
        '    def post(self, duong_dan, du_lieu):',
        '        return self._goi("POST", duong_dan, json=du_lieu)',
        '',
        '',
        'with ApiClient("http://127.0.0.1:8000") as api:',
        '    print("=== GET danh sach ===")',
        '    r = api.get("/api/hoc-sinh")',
        '    print(f"  Ma: {r.status_code}, so hoc sinh: {r.json()[\'tong\']}")',
        '',
        '    print()',
        '    print("=== POST tao moi ===")',
        '    r = api.post("/api/hoc-sinh", {"ho_ten": "Nguyen Van A", "lop": "7A1", "diem": 8.0})',
        '    print(f"  Ma: {r.status_code}")',
        '    print(f"  Ket qua: {r.json()}")',
        '',
        '    print()',
        '    print("=== GET khong ton tai (khong thu lai) ===")',
        '    r = api.get("/api/hoc-sinh/999")',
        '    print(f"  Ma: {r.status_code} - {r.json()}")',
        '',
        '    print()',
        '    print("=== GET loi server (co thu lai) ===")',
        '    r = api.get("/api/loi-server")',
        '    print(f"  Ket qua sau khi thu lai: {r}")',
      ], {
        output: [
          '=== GET danh sach ===',
          '  Ma: 200, so hoc sinh: 5',
          '',
          '=== POST tao moi ===',
          '  Ma: 201',
          "  Ket qua: {'id': 6, 'trang_thai': 'da_tao'}",
          '',
          '=== GET khong ton tai (khong thu lai) ===',
          "  Ma: 404 - {'loi': 'Khong tim thay hoc sinh'}",
          '',
          '=== GET loi server (co thu lai) ===',
          '  Ket qua sau khi thu lai: None',
        ].join('\n'),
        notes: [
          '`404` trả về ngay ở lần đầu — không lãng phí thời gian thử lại lỗi của chính mình.',
          '`500` được thử lại đủ 3 lần rồi mới trả về `None`.',
          'Lớp có `__enter__`/`__exit__` nên dùng được với `with` — kỹ thuật từ buổi 4.',
          '`self.phien.request(phuong_thuc, ...)` cho phép một hàm dùng chung cho cả GET lẫn POST.',
        ],
      }),
      playground('Sân chơi: mở rộng client', [
        'Thêm vào lớp `ApiClient`:',
        '',
        '1. Phương thức `put()` và `delete()`',
        '2. Đếm số lần gọi và tổng thời gian (thống kê đơn giản)',
        '3. Bộ nhớ đệm: cùng một URL GET gọi hai lần thì lần sau lấy từ bộ nhớ',
        '4. Ghi nhật ký mỗi lần gọi: phương thức, đường dẫn, mã trạng thái',
      ], [
        'import time',
        '',
        'import requests',
        '',
        '',
        'class ApiClient:',
        '    def __init__(self, goc, timeout=5):',
        '        self.goc = goc.rstrip("/")',
        '        self.timeout = timeout',
        '        self.phien = requests.Session()',
        '        self.so_lan_goi = 0',
        '        self.bo_nho_dem = {}',
        '        self.nhat_ky = []',
        '',
        '    def get(self, duong_dan, dung_dem=True):',
        '        if dung_dem and duong_dan in self.bo_nho_dem:',
        '            self.nhat_ky.append(f"GET {duong_dan} (tu bo nho dem)")',
        '            return self.bo_nho_dem[duong_dan]',
        '',
        '        r = self.phien.get(f"{self.goc}{duong_dan}", timeout=self.timeout)',
        '        self.so_lan_goi += 1',
        '        self.nhat_ky.append(f"GET {duong_dan} -> {r.status_code}")',
        '        if dung_dem and r.status_code == 200:',
        '            self.bo_nho_dem[duong_dan] = r',
        '        return r',
        '',
        '    # Them put(), delete() o day',
        '',
        '',
        'api = ApiClient("http://127.0.0.1:8000")',
        'api.get("/api/hoc-sinh")',
        'api.get("/api/hoc-sinh")     # lan nay lay tu bo nho dem',
        'print(f"So lan goi that: {api.so_lan_goi}")',
        'for dong in api.nhat_ky:',
        '    print(" ", dong)',
      ], 'Thêm được ít nhất hai tính năng và bộ nhớ đệm hoạt động đúng.'),
      challenge({
        slug: 'p-nc-b20-client-api-co-xu-ly-loi',
        title: 'Client API có xử lý lỗi',
        statement: [
          'Máy chủ mô phỏng tại `http://127.0.0.1:8000` có các đường dẫn:',
          '',
          '| Đường dẫn | Mã | Nội dung |',
          '|---|---|---|',
          '| `GET /api/hoc-sinh` | 200 | `{"tong": 5, "ket_qua": [...]}` |',
          '| `GET /api/hoc-sinh/1` | 200 | một học sinh |',
          '| `GET /api/hoc-sinh/999` | 404 | `{"loi": "..."}` |',
          '| `POST /api/hoc-sinh` | 201 | `{"id": 6, "trang_thai": "da_tao"}` |',
          '| `GET /api/loi-server` | 500 | `{"loi": "..."}` |',
          '',
          'Viết lớp `ApiClient`:',
          '',
          '- `__init__(self, goc, timeout=5)` → lưu `self.goc` (đã bỏ `/` ở cuối), `self.timeout`, ' +
            'và `self.nhat_ky = []` (danh sách rỗng **mới**)',
          '- `lay(self, duong_dan)` → gọi GET. Trả về **tuple** `(status_code, du_lieu)` với ' +
            '`du_lieu` là `r.json()`. Nếu có ngoại lệ của `requests`, trả về `(0, None)`. ' +
            'Mọi lần gọi đều thêm `f"GET {duong_dan} -> {ma}"` vào `self.nhat_ky`',
          '- `tao(self, duong_dan, du_lieu)` → gọi POST với `json=du_lieu`, trả về tuple giống trên, ' +
            'ghi nhật ký dạng `f"POST {duong_dan} -> {ma}"`',
          '- `thanh_cong(self)` → số lần gọi có mã trong khoảng `200–299`, đếm từ `self.nhat_ky`',
        ].join('\n'),
        hints: [
          '`goc.rstrip("/")` để bỏ dấu `/` thừa ở cuối.',
          'Bọc lời gọi trong `try/except requests.exceptions.RequestException` rồi trả `(0, None)`.',
          '`thanh_cong` có thể tách mã từ nhật ký: `int(dong.split("-> ")[1])`.',
          'Nhớ ghi nhật ký cả khi thất bại — với mã `0`.',
        ],
        starterCode: [
          'import requests',
          '',
          '',
          'class ApiClient:',
          '    def __init__(self, goc, timeout=5):',
          '        pass',
          '',
          '    def lay(self, duong_dan):',
          '        pass',
          '',
          '    def tao(self, duong_dan, du_lieu):',
          '        pass',
          '',
          '    def thanh_cong(self):',
          '        pass',
        ].join('\n'),
        solutionCode: [
          'import requests',
          '',
          '',
          'class ApiClient:',
          '    def __init__(self, goc, timeout=5):',
          '        self.goc = goc.rstrip("/")',
          '        self.timeout = timeout',
          '        self.nhat_ky = []',
          '',
          '    def lay(self, duong_dan):',
          '        try:',
          '            r = requests.get(f"{self.goc}{duong_dan}", timeout=self.timeout)',
          '        except requests.exceptions.RequestException:',
          '            self.nhat_ky.append(f"GET {duong_dan} -> 0")',
          '            return 0, None',
          '',
          '        self.nhat_ky.append(f"GET {duong_dan} -> {r.status_code}")',
          '        return r.status_code, r.json()',
          '',
          '    def tao(self, duong_dan, du_lieu):',
          '        try:',
          '            r = requests.post(f"{self.goc}{duong_dan}", json=du_lieu,',
          '                              timeout=self.timeout)',
          '        except requests.exceptions.RequestException:',
          '            self.nhat_ky.append(f"POST {duong_dan} -> 0")',
          '            return 0, None',
          '',
          '        self.nhat_ky.append(f"POST {duong_dan} -> {r.status_code}")',
          '        return r.status_code, r.json()',
          '',
          '    def thanh_cong(self):',
          '        dem = 0',
          '        for dong in self.nhat_ky:',
          '            ma = int(dong.split("-> ")[1])',
          '            if 200 <= ma <= 299:',
          '                dem += 1',
          '        return dem',
        ].join('\n'),
        tier: 'NANG_CAO',
        judgeMode: 'UNIT_TEST',
        runtimeImage: 'PY_WEB',
        networkPolicy: 'NONE',
        mockFixtures: FIXTURES_HOC_SINH,
        timeLimitMs: 15000,
        unitTestCode: [
          'from solution import ApiClient',
          '',
          'GOC = "http://127.0.0.1:8000"',
          '',
          '',
          'def test_khoi_tao():',
          '    c = ApiClient(GOC + "/")',
          '    assert c.goc == GOC',
          '    assert c.timeout == 5',
          '    assert c.nhat_ky == []',
          '',
          '',
          'def test_nhat_ky_khong_dung_chung():',
          '    a, b = ApiClient(GOC), ApiClient(GOC)',
          '    a.lay("/api/hoc-sinh")',
          '    assert b.nhat_ky == []',
          '',
          '',
          'def test_lay_thanh_cong():',
          '    c = ApiClient(GOC)',
          '    ma, du_lieu = c.lay("/api/hoc-sinh")',
          '    assert ma == 200',
          '    assert du_lieu["tong"] == 5',
          '    assert len(du_lieu["ket_qua"]) == 5',
          '',
          '',
          'def test_lay_mot_hoc_sinh():',
          '    ma, du_lieu = ApiClient(GOC).lay("/api/hoc-sinh/1")',
          '    assert ma == 200',
          '    assert du_lieu["ho_ten"] == "Nguyen Thi Lan"',
          '',
          '',
          'def test_lay_404():',
          '    ma, du_lieu = ApiClient(GOC).lay("/api/hoc-sinh/999")',
          '    assert ma == 404',
          '    assert "loi" in du_lieu',
          '',
          '',
          'def test_lay_500():',
          '    ma, _ = ApiClient(GOC).lay("/api/loi-server")',
          '    assert ma == 500',
          '',
          '',
          'def test_tao_moi():',
          '    ma, du_lieu = ApiClient(GOC).tao(',
          '        "/api/hoc-sinh", {"ho_ten": "Nguyen Van A", "lop": "7A1", "diem": 8.0}',
          '    )',
          '    assert ma == 201',
          '    assert du_lieu["trang_thai"] == "da_tao"',
          '',
          '',
          'def test_nhat_ky_ghi_dung():',
          '    c = ApiClient(GOC)',
          '    c.lay("/api/hoc-sinh")',
          '    c.lay("/api/hoc-sinh/999")',
          '    assert c.nhat_ky == [',
          '        "GET /api/hoc-sinh -> 200",',
          '        "GET /api/hoc-sinh/999 -> 404",',
          '    ]',
          '',
          '',
          'def test_dem_thanh_cong():',
          '    c = ApiClient(GOC)',
          '    c.lay("/api/hoc-sinh")',
          '    c.lay("/api/hoc-sinh/1")',
          '    c.lay("/api/hoc-sinh/999")',
          '    c.lay("/api/loi-server")',
          '    c.tao("/api/hoc-sinh", {"ho_ten": "X"})',
          '    assert c.thanh_cong() == 3',
        ].join('\n'),
        totalPoints: 100,
      }),
    ],
  },

  {
    order: 21,
    slug: 'nc-b21-phan-tich-json-mo-hinh-hoa',
    title: 'Phân tích JSON & mô hình hoá dữ liệu API',
    summary:
      'Dữ liệu API về là một mớ dict lồng nhau. Buổi này học cách biến nó thành các lớp Python ' +
      'gọn gàng — ghép Chương 1 với Chương 3.',
    objectives: [
      'Truy cập an toàn dữ liệu JSON lồng nhau',
      'Chuyển JSON thành đối tượng Python',
      'Dùng `dataclass` để viết lớp dữ liệu ngắn gọn',
      'Xử lý dữ liệu thiếu hoặc sai định dạng',
    ],
    difficulty: 4,
    status: 'REQUIRED',
    teacherNotes:
      'Buổi nối Chương 1 (OOP) với Chương 3 (API). Nhấn mạnh: đừng để dict thô lan khắp chương trình.',
    blocks: [
      theory('Truy cập JSON an toàn', [
        'Dữ liệu API thật thường lồng nhau nhiều tầng và **có thể thiếu khoá**:',
        '',
        '```python',
        'du_lieu = {',
        '    "lop": {',
        '        "ten": "7A1",',
        '        "giao_vien": {"ho_ten": "Co Lan"},',
        '        "hoc_sinh": [{"ho_ten": "Minh", "diem": {"toan": 8}}],',
        '    }',
        '}',
        '```',
        '',
        '```python',
        '# NGUY HIEM: thieu mot khoa la vo chuong trinh',
        'ten_gv = du_lieu["lop"]["giao_vien"]["ho_ten"]',
        '',
        '# AN TOAN: .get() voi gia tri mac dinh',
        'ten_gv = du_lieu.get("lop", {}).get("giao_vien", {}).get("ho_ten", "Chua ro")',
        '```',
        '',
        'Viết chuỗi `.get()` dài thì rối. Hãy tự viết một hàm tiện ích:',
        '',
        '```python',
        'def lay_sau(du_lieu, duong_dan, mac_dinh=None):',
        '    """Lay gia tri long nhau: lay_sau(d, "lop.giao_vien.ho_ten")."""',
        '    hien_tai = du_lieu',
        '    for khoa in duong_dan.split("."):',
        '        if isinstance(hien_tai, dict) and khoa in hien_tai:',
        '            hien_tai = hien_tai[khoa]',
        '        else:',
        '            return mac_dinh',
        '    return hien_tai',
        '',
        '',
        'lay_sau(du_lieu, "lop.giao_vien.ho_ten")        # Co Lan',
        'lay_sau(du_lieu, "lop.dia_chi.so_nha", "?")     # ?',
        '```',
        '',
        '⚠️ **Đừng bao giờ tin dữ liệu từ mạng.** Khoá có thể thiếu, kiểu có thể sai, giá trị có thể ' +
          '`null`. Luôn có phương án dự phòng.',
      ], [
        'Dùng `.get(khoa, mac_dinh)` thay vì `d[khoa]`',
        'Viết hàm tiện ích cho dữ liệu lồng nhiều tầng',
        'Không bao giờ tin dữ liệu từ mạng là đầy đủ và đúng kiểu',
      ]),
      theory('Từ dict sang lớp — và `dataclass`', [
        '**Vì sao không để dict thô khắp nơi?**',
        '',
        '| dict thô | Đối tượng |',
        '|---|---|',
        '| `hs["ho_ten"]` — gõ sai khoá không ai báo | `hs.ho_ten` — sai là lỗi ngay |',
        '| Không có phương thức | `hs.xep_loai()` gắn liền dữ liệu |',
        '| Không kiểm tra kiểu | Kiểm tra ngay trong `__init__` |',
        '',
        '**Mẫu chuẩn — phương thức lớp `tu_json`:**',
        '',
        '```python',
        'class HocSinh:',
        '    def __init__(self, id, ho_ten, lop, diem):',
        '        self.id = id',
        '        self.ho_ten = ho_ten',
        '        self.lop = lop',
        '        self.diem = diem',
        '',
        '    @classmethod',
        '    def tu_json(cls, d):',
        '        """Tao HocSinh tu mot dict JSON, co gia tri mac dinh."""',
        '        return cls(',
        '            id=d.get("id", 0),',
        '            ho_ten=d.get("ho_ten", "Khong ro"),',
        '            lop=d.get("lop", ""),',
        '            diem=float(d.get("diem", 0)),',
        '        )',
        '',
        '    def xep_loai(self):',
        '        if self.diem >= 8:',
        '            return "Gioi"',
        '        return "Kha" if self.diem >= 6.5 else "Trung binh"',
        '```',
        '',
        '`@classmethod` nhận `cls` (chính lớp đó) thay vì `self`. Đây là cách chuẩn để tạo ' +
          '"constructor thứ hai".',
        '',
        '**`dataclass` — viết ngắn hơn nhiều:**',
        '',
        '```python',
        'from dataclasses import dataclass',
        '',
        '',
        '@dataclass',
        'class HocSinh:',
        '    id: int',
        '    ho_ten: str',
        '    lop: str',
        '    diem: float',
        '',
        '    @classmethod',
        '    def tu_json(cls, d):',
        '        return cls(d.get("id", 0), d.get("ho_ten", "?"),',
        '                   d.get("lop", ""), float(d.get("diem", 0)))',
        '```',
        '',
        '`@dataclass` tự sinh `__init__`, `__repr__` và `__eq__`. Bốn dòng thay cho hai chục dòng.',
      ], [
        '`@classmethod tu_json(cls, d)` là mẫu chuẩn để đổi JSON thành đối tượng',
        '`@dataclass` tự sinh `__init__`, `__repr__`, `__eq__`',
        'Đối tượng bắt được lỗi gõ sai khoá; dict thô thì không',
      ]),
      example('Từ API tới đối tượng', 'Ghép Chương 1 và Chương 3 thành một luồng hoàn chỉnh.', [
        'from dataclasses import dataclass, field',
        '',
        'import requests',
        '',
        'GOC = "http://127.0.0.1:8000"',
        '',
        '',
        'def lay_sau(du_lieu, duong_dan, mac_dinh=None):',
        '    """Truy cap an toan du lieu long nhau."""',
        '    hien_tai = du_lieu',
        '    for khoa in duong_dan.split("."):',
        '        if isinstance(hien_tai, dict) and khoa in hien_tai:',
        '            hien_tai = hien_tai[khoa]',
        '        else:',
        '            return mac_dinh',
        '    return hien_tai',
        '',
        '',
        '@dataclass',
        'class HocSinh:',
        '    id: int',
        '    ho_ten: str',
        '    lop: str',
        '    diem: float',
        '',
        '    @classmethod',
        '    def tu_json(cls, d):',
        '        return cls(',
        '            id=int(d.get("id", 0)),',
        '            ho_ten=str(d.get("ho_ten", "Khong ro")).strip(),',
        '            lop=str(d.get("lop", "")),',
        '            diem=float(d.get("diem", 0) or 0),',
        '        )',
        '',
        '    @property',
        '    def xep_loai(self):',
        '        if self.diem >= 8:',
        '            return "Gioi"',
        '        if self.diem >= 6.5:',
        '            return "Kha"',
        '        return "Trung binh" if self.diem >= 5 else "Can co gang"',
        '',
        '',
        '@dataclass',
        'class Lop:',
        '    ten: str',
        '    hoc_sinh: list = field(default_factory=list)',
        '',
        '    @property',
        '    def si_so(self):',
        '        return len(self.hoc_sinh)',
        '',
        '    @property',
        '    def diem_trung_binh(self):',
        '        if not self.hoc_sinh:',
        '            return 0.0',
        '        return sum(h.diem for h in self.hoc_sinh) / self.si_so',
        '',
        '    def gioi_nhat(self):',
        '        return max(self.hoc_sinh, key=lambda h: h.diem) if self.hoc_sinh else None',
        '',
        '',
        'r = requests.get(f"{GOC}/api/hoc-sinh", timeout=5)',
        'du_lieu = r.json()',
        '',
        '# Doi tung dict thanh doi tuong',
        'tat_ca = [HocSinh.tu_json(d) for d in lay_sau(du_lieu, "ket_qua", [])]',
        '',
        '# Nhom theo lop',
        'cac_lop = {}',
        'for hs in tat_ca:',
        '    cac_lop.setdefault(hs.lop, Lop(ten=hs.lop)).hoc_sinh.append(hs)',
        '',
        'for ten in sorted(cac_lop):',
        '    lop = cac_lop[ten]',
        '    print(f"=== Lop {lop.ten} ({lop.si_so} hoc sinh) ===")',
        '    for hs in lop.hoc_sinh:',
        '        print(f"    {hs.ho_ten:<20} {hs.diem:>4} - {hs.xep_loai}")',
        '    print(f"    Trung binh: {lop.diem_trung_binh:.2f}")',
        '    print(f"    Gioi nhat : {lop.gioi_nhat().ho_ten}")',
        '    print()',
        '',
        'print("=== Du lieu thieu khoa van xu ly duoc ===")',
        'thieu = HocSinh.tu_json({"ho_ten": "  Ban moi  "})',
        'print(f"  {thieu}")',
        'print(f"  Xep loai: {thieu.xep_loai}")',
      ], {
        output: [
          '=== Lop 7A1 (3 hoc sinh) ===',
          '    Nguyen Thi Lan        8.5 - Gioi',
          '    Tran Van Minh         7.0 - Kha',
          '    Vo Thi Mai            6.0 - Trung binh',
          '    Trung binh: 7.17',
          '    Gioi nhat : Nguyen Thi Lan',
          '',
          '=== Lop 7A2 (2 hoc sinh) ===',
          '    Le Thi Hoa            9.5 - Gioi',
          '    Pham Van Nam          5.5 - Trung binh',
          '    Trung binh: 7.50',
          '    Gioi nhat : Le Thi Hoa',
          '',
          '=== Du lieu thieu khoa van xu ly duoc ===',
          "  HocSinh(id=0, ho_ten='Ban moi', lop='', diem=0.0)",
          '  Xep loai: Can co gang',
        ].join('\n'),
        notes: [
          '`field(default_factory=list)` là cách `dataclass` tránh bẫy danh sách mặc định dùng chung — ' +
            'đúng vấn đề đã học ở buổi 3.',
          '`HocSinh.tu_json({"ho_ten": "..."})` vẫn chạy dù thiếu ba khoá, nhờ giá trị mặc định.',
          '`setdefault` tạo `Lop` mới nếu chưa có, rồi trả về nó — gọn hơn hẳn `if ... else`.',
          'Sau bước chuyển đổi, phần còn lại của chương trình chỉ làm việc với đối tượng, không đụng dict nữa.',
        ],
      }),
      playground('Sân chơi: mô hình hoá API của em', [
        'Chọn một cấu trúc JSON và mô hình hoá thành lớp:',
        '',
        '- Bài viết blog: tiêu đề, tác giả, ngày, thẻ, bình luận (lồng nhau)',
        '- Sản phẩm: tên, giá, đánh giá (danh sách), tồn kho',
        '- Thời tiết: nhiệt độ, độ ẩm, dự báo 7 ngày',
        '',
        'Mỗi lớp cần: `@dataclass`, `tu_json()` có giá trị mặc định, và ít nhất một `@property` tính toán.',
      ], [
        'from dataclasses import dataclass, field',
        '',
        '',
        '@dataclass',
        'class BinhLuan:',
        '    tac_gia: str',
        '    noi_dung: str',
        '',
        '    @classmethod',
        '    def tu_json(cls, d):',
        '        return cls(d.get("tac_gia", "An danh"), d.get("noi_dung", ""))',
        '',
        '',
        '@dataclass',
        'class BaiViet:',
        '    tieu_de: str',
        '    tac_gia: str',
        '    the: list = field(default_factory=list)',
        '    binh_luan: list = field(default_factory=list)',
        '',
        '    @classmethod',
        '    def tu_json(cls, d):',
        '        return cls(',
        '            tieu_de=d.get("tieu_de", "Khong tieu de"),',
        '            tac_gia=d.get("tac_gia", "?"),',
        '            the=d.get("the", []),',
        '            binh_luan=[BinhLuan.tu_json(b) for b in d.get("binh_luan", [])],',
        '        )',
        '',
        '    @property',
        '    def so_binh_luan(self):',
        '        return len(self.binh_luan)',
        '',
        '',
        'bai = BaiViet.tu_json({',
        '    "tieu_de": "Hoc Python",',
        '    "binh_luan": [{"tac_gia": "Lan", "noi_dung": "Hay qua"}],',
        '})',
        'print(bai)',
        'print(f"So binh luan: {bai.so_binh_luan}")',
      ], 'Mô hình hoá được cấu trúc lồng nhau và xử lý đúng khi thiếu khoá.'),
      challenge({
        slug: 'p-nc-b21-mo-hinh-hoa-json',
        title: 'Mô hình hoá dữ liệu học sinh từ API',
        statement: [
          'Viết:',
          '',
          '**`lay_sau(du_lieu, duong_dan, mac_dinh=None)`** — truy cập giá trị lồng nhau theo ' +
            'đường dẫn ngăn bởi dấu chấm. Ví dụ `lay_sau(d, "a.b.c")`. Thiếu khoá ở bất kỳ tầng nào ' +
            'thì trả về `mac_dinh`.',
          '',
          '**Lớp `HocSinh`** với thuộc tính `id`, `ho_ten`, `lop`, `diem` và:',
          '',
          '- `@classmethod tu_json(cls, d)` → tạo từ dict với mặc định: `id=0`, ' +
            '`ho_ten="Khong ro"` (đã `.strip()`), `lop=""`, `diem=0.0`. `diem` luôn ép về `float`',
          '- `xep_loai(self)` → `"Gioi"` từ 8.0, `"Kha"` từ 6.5, `"Trung binh"` từ 5.0, ' +
            'còn lại `"Can co gang"`',
          '',
          '**`tai_va_mo_hinh_hoa()`** — gọi `GET http://127.0.0.1:8000/api/hoc-sinh` với `timeout=5`, ' +
            'lấy danh sách ở khoá `ket_qua`, trả về **danh sách các đối tượng `HocSinh`**. ' +
            'Thất bại thì trả về danh sách rỗng.',
        ].join('\n'),
        hints: [
          '`lay_sau` lặp qua `duong_dan.split(".")`, kiểm tra `isinstance(hien_tai, dict)` mỗi bước.',
          '`float(d.get("diem", 0) or 0)` xử lý được cả trường hợp giá trị là `None`.',
          '`tai_va_mo_hinh_hoa` dùng lại `lay_sau(r.json(), "ket_qua", [])`.',
        ],
        starterCode: [
          'import requests',
          '',
          'GOC = "http://127.0.0.1:8000"',
          '',
          '',
          'def lay_sau(du_lieu, duong_dan, mac_dinh=None):',
          '    pass',
          '',
          '',
          'class HocSinh:',
          '    def __init__(self, id, ho_ten, lop, diem):',
          '        self.id = id',
          '        self.ho_ten = ho_ten',
          '        self.lop = lop',
          '        self.diem = diem',
          '',
          '    @classmethod',
          '    def tu_json(cls, d):',
          '        pass',
          '',
          '    def xep_loai(self):',
          '        pass',
          '',
          '',
          'def tai_va_mo_hinh_hoa():',
          '    pass',
        ].join('\n'),
        solutionCode: [
          'import requests',
          '',
          'GOC = "http://127.0.0.1:8000"',
          '',
          '',
          'def lay_sau(du_lieu, duong_dan, mac_dinh=None):',
          '    hien_tai = du_lieu',
          '    for khoa in duong_dan.split("."):',
          '        if isinstance(hien_tai, dict) and khoa in hien_tai:',
          '            hien_tai = hien_tai[khoa]',
          '        else:',
          '            return mac_dinh',
          '    return hien_tai',
          '',
          '',
          'class HocSinh:',
          '    def __init__(self, id, ho_ten, lop, diem):',
          '        self.id = id',
          '        self.ho_ten = ho_ten',
          '        self.lop = lop',
          '        self.diem = diem',
          '',
          '    @classmethod',
          '    def tu_json(cls, d):',
          '        return cls(',
          '            id=int(d.get("id", 0)),',
          '            ho_ten=str(d.get("ho_ten", "Khong ro")).strip(),',
          '            lop=str(d.get("lop", "")),',
          '            diem=float(d.get("diem", 0) or 0),',
          '        )',
          '',
          '    def xep_loai(self):',
          '        if self.diem >= 8:',
          '            return "Gioi"',
          '        if self.diem >= 6.5:',
          '            return "Kha"',
          '        if self.diem >= 5:',
          '            return "Trung binh"',
          '        return "Can co gang"',
          '',
          '',
          'def tai_va_mo_hinh_hoa():',
          '    try:',
          '        r = requests.get(f"{GOC}/api/hoc-sinh", timeout=5)',
          '    except requests.exceptions.RequestException:',
          '        return []',
          '',
          '    if r.status_code != 200:',
          '        return []',
          '    return [HocSinh.tu_json(d) for d in lay_sau(r.json(), "ket_qua", [])]',
        ].join('\n'),
        tier: 'NANG_CAO',
        judgeMode: 'UNIT_TEST',
        runtimeImage: 'PY_WEB',
        networkPolicy: 'NONE',
        mockFixtures: FIXTURES_HOC_SINH,
        timeLimitMs: 10000,
        unitTestCode: [
          'from solution import HocSinh, lay_sau, tai_va_mo_hinh_hoa',
          '',
          'LONG_NHAU = {"lop": {"ten": "7A1", "gv": {"ho_ten": "Co Lan"}}}',
          '',
          '',
          'def test_lay_sau_co_ban():',
          '    assert lay_sau(LONG_NHAU, "lop.ten") == "7A1"',
          '    assert lay_sau(LONG_NHAU, "lop.gv.ho_ten") == "Co Lan"',
          '',
          '',
          'def test_lay_sau_thieu_khoa():',
          '    assert lay_sau(LONG_NHAU, "lop.dia_chi") is None',
          '    assert lay_sau(LONG_NHAU, "lop.dia_chi.so", "?") == "?"',
          '    assert lay_sau(LONG_NHAU, "khong.co.gi", 0) == 0',
          '',
          '',
          'def test_lay_sau_gap_gia_tri_khong_phai_dict():',
          '    assert lay_sau(LONG_NHAU, "lop.ten.them", "?") == "?"',
          '',
          '',
          'def test_tu_json_day_du():',
          '    hs = HocSinh.tu_json({"id": 3, "ho_ten": "  Lan  ", "lop": "7A1", "diem": "8.5"})',
          '    assert hs.id == 3',
          '    assert hs.ho_ten == "Lan"',
          '    assert hs.lop == "7A1"',
          '    assert hs.diem == 8.5',
          '    assert isinstance(hs.diem, float)',
          '',
          '',
          'def test_tu_json_thieu_khoa():',
          '    hs = HocSinh.tu_json({})',
          '    assert hs.id == 0',
          '    assert hs.ho_ten == "Khong ro"',
          '    assert hs.lop == ""',
          '    assert hs.diem == 0.0',
          '',
          '',
          'def test_tu_json_diem_null():',
          '    assert HocSinh.tu_json({"diem": None}).diem == 0.0',
          '',
          '',
          'def test_xep_loai():',
          '    moc = [(10, "Gioi"), (8, "Gioi"), (7.9, "Kha"), (6.5, "Kha"),',
          '           (6.4, "Trung binh"), (5, "Trung binh"), (4.9, "Can co gang")]',
          '    for diem, mong_doi in moc:',
          '        assert HocSinh.tu_json({"diem": diem}).xep_loai() == mong_doi',
          '',
          '',
          'def test_tai_tu_api():',
          '    ds = tai_va_mo_hinh_hoa()',
          '    assert len(ds) == 5',
          '    assert all(isinstance(x, HocSinh) for x in ds)',
          '    assert ds[0].ho_ten == "Nguyen Thi Lan"',
          '    assert ds[0].xep_loai() == "Gioi"',
          '    assert ds[3].xep_loai() == "Trung binh"',
        ].join('\n'),
        totalPoints: 100,
      }),
    ],
  },

  {
    order: 22,
    slug: 'nc-b22-du-an-tra-cuu-api',
    title: 'Dự án: ứng dụng tra cứu dữ liệu từ API',
    summary:
      'Dự án khép Chương 3: một ứng dụng dòng lệnh gọi API, mô hình hoá dữ liệu, lọc, thống kê ' +
      'và lưu kết quả.',
    objectives: [
      'Xây dựng ứng dụng nhiều tầng: client, mô hình, giao diện',
      'Kết hợp regex, requests và OOP trong một sản phẩm',
      'Lưu kết quả ra JSON và đọc lại',
      'Xử lý mọi trường hợp lỗi một cách lịch sự',
    ],
    difficulty: 5,
    estimatedMinutes: 120,
    status: 'REQUIRED',
    teacherNotes:
      'Dự án khép Chương 3. Máy chủ mô phỏng chạy tại 127.0.0.1:8000 trong môi trường chấm bài — ' +
      'học sinh KHÔNG cần và KHÔNG được gọi API ngoài Internet.',
    blocks: [
      theory('Kiến trúc ba tầng', [
        'Ứng dụng thật luôn tách thành các tầng, mỗi tầng một trách nhiệm:',
        '',
        '```',
        '┌─────────────────────────────────────┐',
        '│  TANG GIAO DIEN  (giao_dien.py)     │  In menu, doc lenh, hien ket qua',
        '│    - khong biet gi ve HTTP          │',
        '└──────────────┬──────────────────────┘',
        '               │',
        '┌──────────────▼──────────────────────┐',
        '│  TANG NGHIEP VU  (dich_vu.py)       │  Loc, thong ke, sap xep',
        '│    - lam viec voi DOI TUONG         │',
        '└──────────────┬──────────────────────┘',
        '               │',
        '┌──────────────▼──────────────────────┐',
        '│  TANG DU LIEU  (api.py, mo_hinh.py) │  Goi API, doi JSON -> doi tuong',
        '│    - noi DUY NHAT biet ve HTTP      │',
        '└─────────────────────────────────────┘',
        '```',
        '',
        '**Vì sao tách tầng?**',
        '',
        '| Lợi ích | Ví dụ cụ thể |',
        '|---|---|',
        '| Đổi nguồn dữ liệu dễ | Đổi từ API sang tệp JSON: chỉ sửa tầng dữ liệu |',
        '| Kiểm thử dễ | Test tầng nghiệp vụ không cần mạng |',
        '| Tìm lỗi nhanh | Hiển thị sai → lỗi ở tầng giao diện, không phải đâu khác |',
        '',
        '⚠️ **Quy tắc quan trọng nhất:** chỉ tầng dữ liệu được `import requests`. ' +
          'Nếu tầng giao diện gọi thẳng `requests`, kiến trúc coi như hỏng.',
      ], [
        'Ba tầng: giao diện → nghiệp vụ → dữ liệu',
        'Chỉ tầng dữ liệu biết về HTTP',
        'Tách tầng giúp đổi nguồn dữ liệu và kiểm thử dễ hơn nhiều',
      ]),
      example('Ứng dụng tra cứu hoàn chỉnh', 'Ba tầng gộp trong một tệp để dễ đọc; dự án của em nên tách tệp.', [
        '"""Ung dung tra cuu hoc sinh - du an ket Chuong 3."""',
        '',
        'import json',
        'import re',
        'from dataclasses import dataclass',
        '',
        'import requests',
        '',
        'GOC = "http://127.0.0.1:8000"',
        '',
        '',
        '# ══════════ TANG DU LIEU ══════════',
        '@dataclass',
        'class HocSinh:',
        '    id: int',
        '    ho_ten: str',
        '    lop: str',
        '    diem: float',
        '',
        '    @classmethod',
        '    def tu_json(cls, d):',
        '        return cls(',
        '            id=int(d.get("id", 0)),',
        '            ho_ten=str(d.get("ho_ten", "Khong ro")).strip(),',
        '            lop=str(d.get("lop", "")),',
        '            diem=float(d.get("diem", 0) or 0),',
        '        )',
        '',
        '    def sang_json(self):',
        '        return {"id": self.id, "ho_ten": self.ho_ten,',
        '                "lop": self.lop, "diem": self.diem}',
        '',
        '',
        'class KhoDuLieu:',
        '    """Noi DUY NHAT biet ve HTTP."""',
        '',
        '    def __init__(self, goc=GOC, timeout=5):',
        '        self.goc = goc.rstrip("/")',
        '        self.timeout = timeout',
        '',
        '    def tat_ca_hoc_sinh(self):',
        '        try:',
        '            r = requests.get(f"{self.goc}/api/hoc-sinh", timeout=self.timeout)',
        '        except requests.exceptions.RequestException as loi:',
        '            return [], f"Khong goi duoc API: {type(loi).__name__}"',
        '',
        '        if r.status_code != 200:',
        '            return [], f"Server tra ve ma {r.status_code}"',
        '',
        '        ds = [HocSinh.tu_json(d) for d in r.json().get("ket_qua", [])]',
        '        return ds, None',
        '',
        '',
        '# ══════════ TANG NGHIEP VU ══════════',
        'class DichVuHocSinh:',
        '    """Loc, thong ke - khong biet gi ve HTTP."""',
        '',
        '    def __init__(self, danh_sach):',
        '        self.danh_sach = danh_sach',
        '',
        '    def tim_theo_ten(self, tu_khoa):',
        '        mau = re.compile(re.escape(tu_khoa), re.IGNORECASE)',
        '        return [h for h in self.danh_sach if mau.search(h.ho_ten)]',
        '',
        '    def loc_theo_lop(self, lop):',
        '        return [h for h in self.danh_sach if h.lop == lop]',
        '',
        '    def loc_theo_diem(self, tu, den=10.0):',
        '        return [h for h in self.danh_sach if tu <= h.diem <= den]',
        '',
        '    def thong_ke(self):',
        '        if not self.danh_sach:',
        '            return {"si_so": 0, "trung_binh": 0.0, "cao_nhat": None, "theo_lop": {}}',
        '',
        '        theo_lop = {}',
        '        for h in self.danh_sach:',
        '            theo_lop[h.lop] = theo_lop.get(h.lop, 0) + 1',
        '',
        '        return {',
        '            "si_so": len(self.danh_sach),',
        '            "trung_binh": sum(h.diem for h in self.danh_sach) / len(self.danh_sach),',
        '            "cao_nhat": max(self.danh_sach, key=lambda h: h.diem),',
        '            "theo_lop": theo_lop,',
        '        }',
        '',
        '    def luu(self, ten_tep):',
        '        with open(ten_tep, "w", encoding="utf-8") as f:',
        '            json.dump([h.sang_json() for h in self.danh_sach], f,',
        '                      ensure_ascii=False, indent=2)',
        '',
        '',
        '# ══════════ TANG GIAO DIEN ══════════',
        'def in_bang(tieu_de, danh_sach):',
        '    print(f"\\n{tieu_de} ({len(danh_sach)} ket qua)")',
        '    print("  " + "-" * 44)',
        '    if not danh_sach:',
        '        print("  (khong co ket qua)")',
        '        return',
        '    for h in danh_sach:',
        '        print(f"  {h.id:>3}  {h.ho_ten:<20} {h.lop:<6} {h.diem:>5}")',
        '',
        '',
        'kho = KhoDuLieu()',
        'danh_sach, loi = kho.tat_ca_hoc_sinh()',
        '',
        'if loi:',
        '    print(f"Loi: {loi}")',
        'else:',
        '    dv = DichVuHocSinh(danh_sach)',
        '',
        '    in_bang("TAT CA HOC SINH", danh_sach)',
        '    in_bang("TIM THEO TEN \'thi\'", dv.tim_theo_ten("thi"))',
        '    in_bang("LOP 7A1", dv.loc_theo_lop("7A1"))',
        '    in_bang("DIEM TU 8.0", dv.loc_theo_diem(8.0))',
        '',
        '    tk = dv.thong_ke()',
        '    print(f"\\nTHONG KE")',
        '    print("  " + "-" * 44)',
        '    print(f"  Si so       : {tk[\'si_so\']}")',
        '    print(f"  Trung binh  : {tk[\'trung_binh\']:.2f}")',
        '    print(f"  Cao nhat    : {tk[\'cao_nhat\'].ho_ten} ({tk[\'cao_nhat\'].diem})")',
        '    print(f"  Theo lop    : {tk[\'theo_lop\']}")',
        '',
        '    dv.luu("ket_qua.json")',
        '    print("\\n  Da luu ket_qua.json")',
      ], {
        output: [
          'TAT CA HOC SINH (5 ket qua)',
          '  --------------------------------------------',
          '    1  Nguyen Thi Lan       7A1      8.5',
          '    2  Tran Van Minh        7A1      7.0',
          '    3  Le Thi Hoa           7A2      9.5',
          '    4  Pham Van Nam         7A2      5.5',
          '    5  Vo Thi Mai           7A1      6.0',
          '',
          "TIM THEO TEN 'thi' (3 ket qua)",
          '  --------------------------------------------',
          '    1  Nguyen Thi Lan       7A1      8.5',
          '    3  Le Thi Hoa           7A2      9.5',
          '    5  Vo Thi Mai           7A1      6.0',
          '',
          'THONG KE',
          '  --------------------------------------------',
          '  Si so       : 5',
          '  Trung binh  : 7.30',
          '  Cao nhat    : Le Thi Hoa (9.5)',
          "  Theo lop    : {'7A1': 3, '7A2': 2}",
          '',
          '  Da luu ket_qua.json',
        ].join('\n'),
        notes: [
          '`re.escape(tu_khoa)` rất quan trọng: nếu người dùng gõ `.` hay `*`, không escape thì nó ' +
            'thành ký tự regex và cho kết quả sai.',
          '`KhoDuLieu` trả về `(danh_sach, loi)` nên tầng trên buộc phải xử lý lỗi.',
          '`DichVuHocSinh` không `import requests` — kiểm thử được mà không cần mạng.',
          'Ba tầng ở đây gộp một tệp cho dễ đọc; dự án của em nên tách thành ba tệp riêng.',
        ],
      }),
      playground('Sân chơi: thêm tính năng', [
        'Mở rộng ứng dụng ở trên:',
        '',
        '1. **Sắp xếp** — theo điểm tăng/giảm, theo tên A→Z',
        '2. **Xuất báo cáo** — ghi ra tệp văn bản có định dạng bảng',
        '3. **Bộ lọc kết hợp** — lớp `7A1` **và** điểm từ 8.0',
        '4. **Menu tương tác** — vòng lặp nhận lệnh từ người dùng',
      ], [
        'class DichVuHocSinh:',
        '    def __init__(self, danh_sach):',
        '        self.danh_sach = danh_sach',
        '',
        '    def sap_xep(self, theo="diem", giam_dan=True):',
        '        """Sap xep theo diem hoac ten."""',
        '        if theo == "ten":',
        '            return sorted(self.danh_sach, key=lambda h: h.ho_ten)',
        '        return sorted(self.danh_sach, key=lambda h: h.diem, reverse=giam_dan)',
        '',
        '    def loc_ket_hop(self, lop=None, diem_tu=None):',
        '        """Ap dung nhieu dieu kien cung luc."""',
        '        kq = self.danh_sach',
        '        if lop:',
        '            kq = [h for h in kq if h.lop == lop]',
        '        if diem_tu is not None:',
        '            kq = [h for h in kq if h.diem >= diem_tu]',
        '        return kq',
        '',
        '    # Them xuat_bao_cao() o day',
        '',
        '',
        '# Menu tuong tac',
        '# while True:',
        '#     print("1. Xem tat ca  2. Tim  3. Thong ke  0. Thoat")',
        '#     lenh = input("Chon: ")',
      ], 'Thêm được ít nhất hai tính năng, giữ nguyên kiến trúc ba tầng.'),
      projectBlock(
        'Dự án Chương 3: Ứng dụng tra cứu của em',
        [
          'Xây dựng một ứng dụng tra cứu dữ liệu từ API mô phỏng tại `http://127.0.0.1:8000`.',
          '',
          '**Yêu cầu bắt buộc:**',
          '',
          '| Yêu cầu | Chi tiết |',
          '|---|---|',
          '| Kiến trúc | Tách rõ ba tầng, chỉ tầng dữ liệu `import requests` |',
          '| Mô hình hoá | Ít nhất một lớp có `tu_json()` và `sang_json()` |',
          '| Regex | Dùng ở ít nhất một chỗ (tìm kiếm hoặc kiểm tra dữ liệu nhập) |',
          '| Xử lý lỗi | Mọi trường hợp: mất mạng, quá thời gian, 404, 500, JSON hỏng |',
          '| Lưu trữ | Ghi kết quả ra JSON và đọc lại được |',
          '| Giao diện | Menu dòng lệnh có ít nhất 4 chức năng |',
          '',
          '**Điểm cộng:** bộ nhớ đệm, sắp xếp nhiều tiêu chí, xuất báo cáo văn bản, thống kê nâng cao.',
          '',
          '🔒 **Chỉ dùng `127.0.0.1:8000`.** Môi trường chấm bài không có mạng ra ngoài, và bài của em ' +
            'cũng không được phụ thuộc vào API bên ngoài.',
          '',
          '**Nộp kèm:** sơ đồ ba tầng và mô tả ngắn về cách em xử lý từng loại lỗi.',
        ],
        'CUSTOM',
        [
          'Tầng dữ liệu: gọi API và mô hình hoá thành đối tượng',
          'Tầng nghiệp vụ: lọc, tìm kiếm bằng regex, thống kê',
          'Tầng giao diện: menu dòng lệnh',
          'Hoàn thiện xử lý lỗi, lưu JSON, nộp kèm sơ đồ',
        ],
        { minutes: 70 },
      ),
      quizBlock({
        slug: 'q-nc-b22-tong-ket-chuong-3',
        title: 'Tổng kết Chương 3: Regex & Web API',
        passingScore: 70,
        questions: [
          {
            type: 'MULTIPLE_CHOICE',
            prompt: 'Vì sao nên dùng `params={...}` thay vì tự nối chuỗi vào URL?',
            explanation:
              '`requests` tự mã hoá dấu cách, dấu tiếng Việt và ký tự đặc biệt — tự nối chuỗi rất dễ sai.',
            choices: [
              { text: 'Vì requests tự mã hoá an toàn các ký tự đặc biệt', isCorrect: true },
              { text: 'Vì tự nối chuỗi chạy chậm hơn' },
              { text: 'Vì `params` mã hoá dữ liệu để bảo mật' },
              { text: 'Không có khác biệt, chỉ là thói quen' },
            ],
          },
          {
            type: 'MULTIPLE_CHOICE',
            prompt: 'Gọi API trả về mã 404. `requests` phản ứng thế nào?',
            explanation:
              'Không ném ngoại lệ — với requests, yêu cầu đã hoàn tất và câu trả lời là lỗi. ' +
              'Em phải tự kiểm tra `status_code` hoặc gọi `raise_for_status()`.',
            choices: [
              { text: 'Không ném ngoại lệ; phải tự kiểm tra `status_code`', isCorrect: true },
              { text: 'Ném `ConnectionError`' },
              { text: 'Ném `HTTPError` tự động' },
              { text: 'Trả về `None`' },
            ],
          },
          {
            type: 'MULTIPLE_CHOICE',
            prompt: 'Nên thử lại (retry) với loại lỗi nào?',
            explanation:
              'Chỉ 5xx và lỗi mạng — đó là sự cố tạm thời. 4xx là yêu cầu của ta sai, gửi lại vẫn sai.',
            choices: [
              { text: 'Lỗi 5xx và lỗi mạng', isCorrect: true },
              { text: 'Mọi lỗi, càng thử lại càng tốt' },
              { text: 'Chỉ lỗi 4xx' },
              { text: 'Không bao giờ nên thử lại' },
            ],
          },
          {
            type: 'MULTIPLE_CHOICE',
            prompt: 'Trong regex, `(?=...)` có tác dụng gì?',
            explanation:
              'Lookahead — kiểm tra phía sau có khớp không mà không tiêu tốn ký tự nào của chuỗi.',
            choices: [
              { text: 'Kiểm tra phía sau phải khớp, nhưng không tiêu tốn ký tự', isCorrect: true },
              { text: 'Tạo một nhóm bắt được' },
              { text: 'Lặp mẫu 0 hoặc 1 lần' },
              { text: 'Đánh dấu đầu chuỗi' },
            ],
          },
          {
            type: 'TRUE_FALSE',
            prompt: 'Nên viết khoá API trực tiếp vào code để tiện sử dụng.',
            explanation:
              'Sai. Khoá bí mật phải đọc từ biến môi trường. Viết vào code rồi đưa lên GitHub là sự cố bảo mật phổ biến.',
            choices: [{ text: 'Đúng' }, { text: 'Sai', isCorrect: true }],
          },
          {
            type: 'SHORT_ANSWER',
            prompt:
              'Trong ứng dụng tra cứu của em, hãy liệt kê các trường hợp lỗi em đã xử lý và ' +
              'cách xử lý từng trường hợp.',
            explanation:
              'Ví dụ: mất mạng (`ConnectionError` → báo và cho thử lại), quá thời gian (`Timeout` → ' +
              'tăng timeout hoặc thử lại), 404 (báo không tìm thấy), 500 (thử lại có độ trễ tăng dần), ' +
              'JSON hỏng (`ValueError` → báo dữ liệu không hợp lệ).',
            points: 25,
          },
        ],
      }),
    ],
  },
];

export const advancedChuong3: ModuleSpec = {
  slug: 'regex-va-web-api',
  title: 'Chương 3 · Regex & Web API',
  description:
    'Hai công cụ để làm việc với dữ liệu thật: biểu thức chính quy để bóc tách văn bản, và ' +
    '`requests` để nói chuyện với máy chủ. Mọi bài tập chạy trên máy chủ mô phỏng tại ' +
    '127.0.0.1:8000, nên kết quả luôn tái lập được và môi trường vẫn an toàn.',
  lessons: advancedLessons17to22,
};
