/**
 * Python Nâng Cao — Chương 2: Lập trình mạng (Buổi 11–16).
 *
 * SECURITY POLICY (teacher note 15): every problem runs with networkPolicy NONE.
 * A `--network=none` container still provisions a loopback interface, so the
 * server and client both run inside the SAME container over 127.0.0.1. Students
 * write real socket code; the sandbox has zero external reachability.
 */
import type { LessonSpec, ModuleSpec } from '../types.ts';
import {
  challenge,
  example,
  hidden,
  playground,
  projectBlock,
  quizBlock,
  sample,
  theory,
} from '../builders.ts';

const advancedLessons11to16: LessonSpec[] = [
  {
    order: 11,
    slug: 'nc-b11-mang-may-tinh-can-ban',
    title: 'Mạng máy tính căn bản: IP, Port, DNS',
    summary:
      'Trước khi lập trình mạng, phải hiểu mạng hoạt động thế nào. Địa chỉ IP là số nhà, cổng là ' +
      'số phòng, DNS là danh bạ.',
    objectives: [
      'Giải thích được vai trò của địa chỉ IP',
      'Phân biệt IPv4 và IPv6, IP riêng và IP công cộng',
      'Hiểu khái niệm cổng và các cổng thông dụng',
      'Mô tả được quá trình phân giải tên miền qua DNS',
    ],
    difficulty: 3,
    status: 'REQUIRED',
    isDerived: true,
    teacherNotes:
      'Buổi nền tảng (⟨derived⟩). Không có socket ở buổi này — học sinh cần hiểu khái niệm trước.',
    blocks: [
      theory('Địa chỉ IP — số nhà của máy tính', [
        'Mỗi thiết bị trên mạng có một **địa chỉ IP** để các thiết bị khác tìm được nó.',
        '',
        '**IPv4** — bốn số từ 0 đến 255, ngăn bởi dấu chấm:',
        '',
        '```',
        '192.168.1.10',
        ' │   │   │  └── may cu the trong mang',
        ' └───┴───┴───── phan mang',
        '```',
        '',
        'IPv4 chỉ có khoảng 4,3 tỉ địa chỉ — đã cạn từ lâu. **IPv6** ra đời với 128 bit, ' +
          'viết dạng `2001:0db8:85a3::8a2e:0370:7334`.',
        '',
        '| Loại IP | Dải | Dùng ở đâu |',
        '|---|---|---|',
        '| Riêng (private) | `10.x.x.x`, `172.16–31.x.x`, `192.168.x.x` | Trong nhà, trong trường |',
        '| Loopback | `127.0.0.1` | **Chính máy này** |',
        '| Công cộng | Còn lại | Trên Internet |',
        '',
        '⚠️ **`127.0.0.1` rất quan trọng với khoá học này.** Nó luôn trỏ về chính máy đang chạy, ' +
          'còn gọi là `localhost`. Mọi bài tập socket của em sẽ chạy trên địa chỉ này — ' +
          'server và client cùng nằm trên một máy, không cần Internet.',
        '',
        'Trong môi trường chấm bài của DYE LMS, mạng ra ngoài bị **tắt hoàn toàn**, nhưng ' +
          'loopback vẫn hoạt động. Nhờ vậy em học được socket thật mà vẫn an toàn tuyệt đối.',
      ], [
        'IPv4 = 4 số 0–255; IPv6 dài hơn nhiều',
        '`127.0.0.1` = localhost = chính máy này',
        'Bài tập của em chạy trên loopback, không cần Internet',
      ]),
      theory('Cổng và DNS', [
        'Một máy chạy nhiều dịch vụ cùng lúc. **Cổng (port)** cho biết dữ liệu dành cho dịch vụ nào.',
        '',
        'Hình dung: IP là số nhà, cổng là số phòng trong nhà đó.',
        '',
        '| Cổng | Dịch vụ |',
        '|---|---|',
        '| 20, 21 | FTP |',
        '| 22 | SSH |',
        '| 25 | SMTP (gửi mail) |',
        '| 53 | DNS |',
        '| 80 | HTTP |',
        '| 443 | HTTPS |',
        '| 3306 | MySQL |',
        '| 5432 | PostgreSQL |',
        '',
        '**Ba nhóm cổng:**',
        '',
        '- `0–1023` — cổng hệ thống, cần quyền quản trị',
        '- `1024–49151` — cổng đăng ký, dùng cho ứng dụng',
        '- `49152–65535` — cổng động, hệ điều hành tự cấp',
        '',
        '💡 Bài tập của em nên dùng cổng **trên 1024** để không cần quyền quản trị.',
        '',
        '**DNS — danh bạ của Internet.** Người nhớ `google.com` dễ hơn `142.250.x.x`, nên DNS làm ' +
          'nhiệm vụ tra cứu:',
        '',
        '```',
        '1. Trinh duyet hoi: "google.com o dau?"',
        '2. May chu DNS tra loi: "142.250.185.78"',
        '3. Trinh duyet ket noi toi dia chi do o cong 443',
        '```',
        '',
        'Một địa chỉ đầy đủ gồm ba phần: `https://example.com:443/trang`',
        '— giao thức, tên miền (được DNS đổi thành IP), cổng, và đường dẫn.',
      ], [
        'IP = số nhà, port = số phòng',
        'Cổng < 1024 cần quyền quản trị — bài tập nên dùng cổng > 1024',
        'DNS đổi tên miền thành địa chỉ IP',
      ]),
      example('Khám phá mạng bằng Python', 'Các hàm này chạy được ngay, không cần thư viện ngoài.', [
        'import socket',
        '',
        'print("=== 1. Thong tin may nay ===")',
        'ten_may = socket.gethostname()',
        'print(f"Ten may  : {ten_may}")',
        'print(f"Loopback : 127.0.0.1 (luon tro ve chinh may nay)")',
        '',
        'print()',
        'print("=== 2. Kiem tra dia chi IPv4 hop le ===")',
        '',
        '',
        'def ip_hop_le(chuoi):',
        '    """Kiem tra mot chuoi co phai IPv4 hop le khong."""',
        '    phan = chuoi.split(".")',
        '    if len(phan) != 4:',
        '        return False',
        '    for p in phan:',
        '        if not p.isdigit():',
        '            return False',
        '        if len(p) > 1 and p[0] == "0":     # khong cho 01, 007',
        '            return False',
        '        if int(p) > 255:',
        '            return False',
        '    return True',
        '',
        '',
        'for ip in ["192.168.1.1", "255.255.255.255", "256.1.1.1",',
        '           "1.2.3", "10.0.0.01", "127.0.0.1"]:',
        '    print(f"  {ip:<18} -> {ip_hop_le(ip)}")',
        '',
        'print()',
        'print("=== 3. Phan loai dia chi ===")',
        '',
        '',
        'def phan_loai(ip):',
        '    """Phan loai IPv4 thanh loopback / rieng / cong cong."""',
        '    a, b = int(ip.split(".")[0]), int(ip.split(".")[1])',
        '    if a == 127:',
        '        return "Loopback"',
        '    if a == 10:',
        '        return "Rieng"',
        '    if a == 172 and 16 <= b <= 31:',
        '        return "Rieng"',
        '    if a == 192 and b == 168:',
        '        return "Rieng"',
        '    return "Cong cong"',
        '',
        '',
        'for ip in ["127.0.0.1", "10.0.0.5", "172.16.0.1", "172.32.0.1",',
        '           "192.168.1.100", "8.8.8.8"]:',
        '    print(f"  {ip:<18} -> {phan_loai(ip)}")',
      ], {
        output: [
          '=== 2. Kiem tra dia chi IPv4 hop le ===',
          '  192.168.1.1        -> True',
          '  255.255.255.255    -> True',
          '  256.1.1.1          -> False',
          '  1.2.3              -> False',
          '  10.0.0.01          -> False',
          '  127.0.0.1          -> True',
          '',
          '=== 3. Phan loai dia chi ===',
          '  127.0.0.1          -> Loopback',
          '  10.0.0.5           -> Rieng',
          '  172.16.0.1         -> Rieng',
          '  172.32.0.1         -> Cong cong',
          '  192.168.1.100      -> Rieng',
          '  8.8.8.8            -> Cong cong',
        ].join('\n'),
        notes: [
          '`172.32.0.1` là **công cộng** vì dải riêng chỉ tới `172.31.x.x` — một chi tiết dễ nhầm.',
          'Phép kiểm tra `p[0] == "0"` loại bỏ `10.0.0.01`, vì số 0 đứng đầu không hợp lệ trong IPv4.',
          '`8.8.8.8` là máy chủ DNS công cộng của Google — địa chỉ dễ nhớ nhất Internet.',
        ],
      }),
      playground('Sân chơi: bộ công cụ mạng', [
        'Viết ba hàm nhỏ:',
        '',
        '- `tach_dia_chi(url)` — tách `https://example.com:8080/trang` thành giao thức, tên miền, cổng, đường dẫn',
        '- `cong_mac_dinh(giao_thuc)` — trả về 80 cho http, 443 cho https',
        '- `la_ip_rieng(ip)` — kiểm tra IP có thuộc dải riêng không',
      ], [
        'def tach_dia_chi(url):',
        '    """Tach URL thanh cac phan."""',
        '    giao_thuc = "http"',
        '    if "://" in url:',
        '        giao_thuc, url = url.split("://", 1)',
        '',
        '    duong_dan = "/"',
        '    if "/" in url:',
        '        url, duong_dan = url.split("/", 1)',
        '        duong_dan = "/" + duong_dan',
        '',
        '    cong = None',
        '    if ":" in url:',
        '        url, cong = url.split(":", 1)',
        '        cong = int(cong)',
        '',
        '    return {"giao_thuc": giao_thuc, "ten_mien": url,',
        '            "cong": cong, "duong_dan": duong_dan}',
        '',
        '',
        'print(tach_dia_chi("https://example.com:8080/api/users"))',
        'print(tach_dia_chi("http://localhost/"))',
        '',
        '# Viet them cong_mac_dinh() va la_ip_rieng()',
      ], 'Ba hàm chạy đúng với ít nhất ba địa chỉ khác nhau mỗi hàm.'),
      challenge({
        slug: 'p-nc-b11-kiem-tra-ipv4',
        title: 'Kiểm tra và phân loại IPv4',
        statement: [
          'Dòng đầu: số nguyên `N`. `N` dòng tiếp theo, mỗi dòng một chuỗi cần kiểm tra.',
          '',
          'Với mỗi chuỗi, in ra **một dòng**:',
          '',
          '- `KHONG HOP LE` — nếu không phải IPv4 hợp lệ',
          '- `LOOPBACK` — nếu bắt đầu bằng `127.`',
          '- `RIENG` — nếu thuộc `10.x.x.x`, `172.16–31.x.x` hoặc `192.168.x.x`',
          '- `CONG CONG` — các trường hợp còn lại',
          '',
          '**IPv4 hợp lệ** cần: đúng 4 phần ngăn bởi dấu chấm, mỗi phần chỉ gồm chữ số, ' +
            'giá trị từ 0 đến 255, và **không có số 0 đứng đầu** (`01` không hợp lệ, `0` thì hợp lệ).',
        ].join('\n'),
        hints: [
          'Tách bằng `.split(".")` rồi kiểm tra `len(...) == 4`.',
          'Dùng `.isdigit()` để bảo đảm chỉ có chữ số — nó cũng loại luôn chuỗi rỗng.',
          'Số 0 đứng đầu: `len(p) > 1 and p[0] == "0"`.',
          'Nhớ kiểm tra hợp lệ TRƯỚC khi phân loại.',
        ],
        starterCode: [
          'def ip_hop_le(chuoi):',
          '    # Kiem tra IPv4 hop le',
          '    pass',
          '',
          '',
          'def phan_loai(ip):',
          '    # Phan loai loopback / rieng / cong cong',
          '    pass',
          '',
          '',
          'n = int(input())',
          'for i in range(n):',
          '    s = input().strip()',
          '    # In ket qua',
        ].join('\n'),
        solutionCode: [
          'def ip_hop_le(chuoi):',
          '    phan = chuoi.split(".")',
          '    if len(phan) != 4:',
          '        return False',
          '    for p in phan:',
          '        if not p.isdigit():',
          '            return False',
          '        if len(p) > 1 and p[0] == "0":',
          '            return False',
          '        if int(p) > 255:',
          '            return False',
          '    return True',
          '',
          '',
          'def phan_loai(ip):',
          '    phan = [int(x) for x in ip.split(".")]',
          '    a, b = phan[0], phan[1]',
          '    if a == 127:',
          '        return "LOOPBACK"',
          '    if a == 10:',
          '        return "RIENG"',
          '    if a == 172 and 16 <= b <= 31:',
          '        return "RIENG"',
          '    if a == 192 and b == 168:',
          '        return "RIENG"',
          '    return "CONG CONG"',
          '',
          '',
          'n = int(input())',
          'for i in range(n):',
          '    s = input().strip()',
          '    if not ip_hop_le(s):',
          '        print("KHONG HOP LE")',
          '    else:',
          '        print(phan_loai(s))',
        ].join('\n'),
        tier: 'CO_BAN',
        judgeMode: 'IO_MATCH',
        tests: [
          sample(
            '4\n127.0.0.1\n192.168.1.5\n8.8.8.8\n256.1.1.1\n',
            'LOOPBACK\nRIENG\nCONG CONG\nKHONG HOP LE\n',
            '256 vượt quá 255 nên không hợp lệ.',
          ),
          sample(
            '2\n172.16.0.1\n172.32.0.1\n',
            'RIENG\nCONG CONG\n',
            'Dải riêng chỉ tới 172.31 — 172.32 đã là công cộng.',
          ),
          hidden('1\n10.0.0.01\n', 'KHONG HOP LE\n', 15),
          hidden('1\n0.0.0.0\n', 'CONG CONG\n', 15),
          hidden('1\n1.2.3\n', 'KHONG HOP LE\n', 15),
          hidden('1\n255.255.255.255\n', 'CONG CONG\n', 15),
          hidden('2\n127.255.255.255\n10.255.255.255\n', 'LOOPBACK\nRIENG\n', 20),
          hidden('2\nabc.def.ghi.jkl\n192.168.1.1.1\n', 'KHONG HOP LE\nKHONG HOP LE\n', 20),
        ],
      }),
    ],
  },

  {
    order: 12,
    slug: 'nc-b12-http-va-client-server',
    title: 'Giao thức HTTP & mô hình Client–Server',
    summary:
      'Toàn bộ web chạy trên một mô hình đơn giản: client hỏi, server trả lời. HTTP là ngôn ngữ ' +
      'của cuộc hội thoại đó.',
    objectives: [
      'Mô tả được mô hình client–server',
      'Đọc hiểu cấu trúc một yêu cầu và một phản hồi HTTP',
      'Nhớ được các phương thức HTTP thông dụng',
      'Phân loại mã trạng thái HTTP theo nhóm',
    ],
    difficulty: 3,
    status: 'REQUIRED',
    teacherNotes: 'Nền tảng cho Chương 3 (requests). Cho học sinh thuộc các nhóm mã trạng thái.',
    blocks: [
      theory('Mô hình Client–Server', [
        '```',
        '   CLIENT                          SERVER',
        '  (trinh duyet,                  (may chu web,',
        '   ung dung)                      may chu API)',
        '      │                                │',
        '      │──── 1. YEU CAU (request) ─────►│',
        '      │     GET /api/users             │  2. Xu ly',
        '      │                                │',
        '      │◄─── 3. PHAN HOI (response) ────│',
        '      │     200 OK + du lieu JSON      │',
        '```',
        '',
        '**Ba đặc điểm cốt lõi của HTTP:**',
        '',
        '1. **Client luôn bắt đầu.** Server không tự gửi gì khi chưa được hỏi.',
        '2. **Không nhớ trạng thái (stateless).** Mỗi yêu cầu độc lập — server không tự nhớ ' +
          'em là ai từ lần trước. Đăng nhập giữ được là nhờ cookie/token gửi kèm mỗi lần.',
        '3. **Một yêu cầu, một phản hồi.** Luôn thành cặp.',
        '',
        'Mô hình này cũng chính là mô hình em sẽ tự tay cài đặt bằng socket ở buổi 14 — ' +
          'chỉ khác là em viết cả hai phía.',
      ], [
        'Client hỏi, server trả lời — client luôn bắt đầu',
        'HTTP không nhớ trạng thái giữa các yêu cầu',
        'Mỗi yêu cầu luôn có đúng một phản hồi',
      ]),
      theory('Cấu trúc yêu cầu và phản hồi', [
        '**Một yêu cầu HTTP thô:**',
        '',
        '```',
        'GET /api/hoc-sinh?lop=7A1 HTTP/1.1     ← dong dau: phuong thuc, duong dan, phien ban',
        'Host: example.com                       ← cac header',
        'Accept: application/json',
        'Authorization: Bearer abc123',
        '                                        ← mot dong TRONG',
        '{"ten": "Lan"}                          ← than (body), co the khong co',
        '```',
        '',
        '**Một phản hồi HTTP thô:**',
        '',
        '```',
        'HTTP/1.1 200 OK                         ← dong dau: phien ban, ma, mo ta',
        'Content-Type: application/json',
        'Content-Length: 47',
        '',
        '{"ket_qua": [{"ten": "Lan", "diem": 8.5}]}',
        '```',
        '',
        '**Các phương thức HTTP:**',
        '',
        '| Phương thức | Việc làm | Có đổi dữ liệu không |',
        '|---|---|---|',
        '| `GET` | Lấy dữ liệu | Không |',
        '| `POST` | Tạo mới | Có |',
        '| `PUT` | Thay thế toàn bộ | Có |',
        '| `PATCH` | Sửa một phần | Có |',
        '| `DELETE` | Xoá | Có |',
        '',
        '⚠️ `GET` **không được** làm thay đổi dữ liệu. Trình duyệt và bộ nhớ đệm có thể gọi lại ' +
          '`GET` bất cứ lúc nào — nếu `GET /xoa-tai-khoan` mà xoá thật thì hậu quả rất nghiêm trọng.',
      ], [
        'Yêu cầu = dòng đầu + header + dòng trống + thân',
        'GET để đọc, POST để tạo, PUT/PATCH để sửa, DELETE để xoá',
        'GET tuyệt đối không được thay đổi dữ liệu',
      ]),
      theory('Mã trạng thái HTTP', [
        'Chữ số đầu tiên cho biết nhóm:',
        '',
        '| Nhóm | Ý nghĩa | Ví dụ |',
        '|---|---|---|',
        '| `1xx` | Thông tin | `100 Continue` |',
        '| `2xx` | **Thành công** | `200 OK`, `201 Created`, `204 No Content` |',
        '| `3xx` | **Chuyển hướng** | `301 Moved Permanently`, `304 Not Modified` |',
        '| `4xx` | **Lỗi phía client** | `400 Bad Request`, `401 Unauthorized`, `403 Forbidden`, `404 Not Found`, `429 Too Many Requests` |',
        '| `5xx` | **Lỗi phía server** | `500 Internal Server Error`, `503 Service Unavailable` |',
        '',
        '**Cách nhớ đơn giản nhất:**',
        '',
        '- `4xx` = **lỗi của em** (gõ sai địa chỉ, thiếu quyền, sai dữ liệu gửi lên)',
        '- `5xx` = **lỗi của họ** (server hỏng, quá tải)',
        '',
        'Phân biệt được hai nhóm này là kỹ năng gỡ lỗi quan trọng: gặp `404` thì kiểm tra lại URL, ' +
          'gặp `500` thì báo cho người quản trị server.',
        '',
        '**Ba mã hay nhầm:**',
        '',
        '- `401 Unauthorized` — *chưa đăng nhập* (dù tên tiếng Anh nghe như "không có quyền")',
        '- `403 Forbidden` — *đã đăng nhập nhưng không đủ quyền*',
        '- `429 Too Many Requests` — gọi quá nhiều, hãy chờ rồi thử lại',
      ], [
        '2xx thành công, 3xx chuyển hướng, 4xx lỗi client, 5xx lỗi server',
        '4xx = lỗi của em, 5xx = lỗi của họ',
        '401 = chưa đăng nhập, 403 = không đủ quyền',
      ]),
      example('Phân tích HTTP bằng Python', 'Tự tay bóc tách một phản hồi HTTP thô.', [
        'PHAN_HOI_THO = """HTTP/1.1 200 OK\\r',
        'Content-Type: application/json; charset=utf-8\\r',
        'Content-Length: 58\\r',
        'Server: DYE-Server/1.0\\r',
        'Cache-Control: no-cache\\r',
        '\\r',
        '{"ten": "Lan", "lop": "7A1", "diem": 8.5, "dat": true}"""',
        '',
        '',
        'def phan_tich(tho):',
        '    """Tach mot phan hoi HTTP tho thanh cac phan."""',
        '    phan_dau, than = tho.split("\\r\\n\\r\\n", 1)',
        '    cac_dong = phan_dau.split("\\r\\n")',
        '',
        '    phien_ban, ma, *mo_ta = cac_dong[0].split(" ")',
        '',
        '    header = {}',
        '    for dong in cac_dong[1:]:',
        '        if ": " in dong:',
        '            khoa, gia_tri = dong.split(": ", 1)',
        '            header[khoa] = gia_tri',
        '',
        '    return {',
        '        "phien_ban": phien_ban,',
        '        "ma": int(ma),',
        '        "mo_ta": " ".join(mo_ta),',
        '        "header": header,',
        '        "than": than,',
        '    }',
        '',
        '',
        'def nhom_ma(ma):',
        '    """Phan loai ma trang thai theo nhom."""',
        '    return {',
        '        1: "Thong tin",',
        '        2: "Thanh cong",',
        '        3: "Chuyen huong",',
        '        4: "Loi phia client",',
        '        5: "Loi phia server",',
        '    }.get(ma // 100, "Khong xac dinh")',
        '',
        '',
        'kq = phan_tich(PHAN_HOI_THO)',
        'print(f"Phien ban : {kq[\'phien_ban\']}")',
        'print(f"Ma        : {kq[\'ma\']} {kq[\'mo_ta\']}  ->  {nhom_ma(kq[\'ma\'])}")',
        'print(f"So header : {len(kq[\'header\'])}")',
        'for k, v in kq["header"].items():',
        '    print(f"    {k:<16}: {v}")',
        'print(f"Than      : {kq[\'than\']}")',
        '',
        'print()',
        'print("=== Phan loai cac ma thuong gap ===")',
        'for ma in [200, 201, 301, 400, 401, 403, 404, 429, 500, 503]:',
        '    print(f"  {ma} -> {nhom_ma(ma)}")',
      ], {
        output: [
          'Phien ban : HTTP/1.1',
          'Ma        : 200 OK  ->  Thanh cong',
          'So header : 4',
          '    Content-Type    : application/json; charset=utf-8',
          '    Content-Length  : 58',
          '    Server          : DYE-Server/1.0',
          '    Cache-Control   : no-cache',
          'Than      : {"ten": "Lan", "lop": "7A1", "diem": 8.5, "dat": true}',
          '',
          '=== Phan loai cac ma thuong gap ===',
          '  200 -> Thanh cong',
          '  404 -> Loi phia client',
          '  500 -> Loi phia server',
        ].join('\n'),
        notes: [
          '`\\r\\n\\r\\n` (một dòng trống) là ranh giới giữa header và thân — quy tắc bất di bất dịch của HTTP.',
          '`ma // 100` lấy chữ số đầu tiên, đủ để phân nhóm.',
          'Cú pháp `phien_ban, ma, *mo_ta = ...` gom phần còn lại vào `mo_ta`, xử lý được cả `404 Not Found` (mô tả hai từ).',
        ],
      }),
      playground('Sân chơi: xây dựng yêu cầu HTTP', [
        'Viết hàm `tao_yeu_cau(phuong_thuc, duong_dan, host, header=None, than=None)` trả về ' +
          'chuỗi yêu cầu HTTP thô đúng chuẩn.',
        '',
        'Nhớ: dòng đầu, các header, một dòng trống, rồi thân.',
        '',
        'Nếu có `than`, nhớ thêm header `Content-Length`.',
      ], [
        'def tao_yeu_cau(phuong_thuc, duong_dan, host, header=None, than=None):',
        '    """Tao chuoi yeu cau HTTP tho."""',
        '    cac_dong = [f"{phuong_thuc} {duong_dan} HTTP/1.1", f"Host: {host}"]',
        '',
        '    if header:',
        '        for k, v in header.items():',
        '            cac_dong.append(f"{k}: {v}")',
        '',
        '    if than:',
        '        cac_dong.append(f"Content-Length: {len(than)}")',
        '',
        '    cac_dong.append("")          # dong trong',
        '    cac_dong.append(than or "")',
        '',
        '    return "\\r\\n".join(cac_dong)',
        '',
        '',
        'print(tao_yeu_cau("GET", "/api/users", "example.com",',
        '                  {"Accept": "application/json"}))',
        'print("---")',
        'print(tao_yeu_cau("POST", "/api/users", "example.com",',
        '                  {"Content-Type": "application/json"},',
        '                  \'{"ten": "Lan"}\'))',
      ], 'Tạo được yêu cầu GET và POST đúng cấu trúc, có Content-Length khi cần.'),
      challenge({
        slug: 'p-nc-b12-phan-loai-ma-http',
        title: 'Phân loại mã trạng thái HTTP',
        statement: [
          'Dòng đầu: số nguyên `N`. `N` dòng tiếp theo, mỗi dòng một số nguyên là mã trạng thái.',
          '',
          'Với mỗi mã, in ra **một dòng** theo mẫu `<ma> <nhom>`, trong đó `<nhom>` là:',
          '',
          '| Dải | Nhóm |',
          '|---|---|',
          '| 100–199 | `THONG TIN` |',
          '| 200–299 | `THANH CONG` |',
          '| 300–399 | `CHUYEN HUONG` |',
          '| 400–499 | `LOI CLIENT` |',
          '| 500–599 | `LOI SERVER` |',
          '| còn lại | `KHONG XAC DINH` |',
          '',
          'Sau tất cả, in thêm **một dòng cuối**: `Loi: <so_luong>` — tổng số mã thuộc nhóm ' +
            '`LOI CLIENT` hoặc `LOI SERVER`.',
        ].join('\n'),
        hints: [
          'Dùng `ma // 100` để lấy chữ số đầu, nhưng nhớ kiểm tra mã nằm trong 100–599 trước.',
          'Một từ điển ánh xạ `{1: "THONG TIN", 2: "THANH CONG", ...}` là cách gọn nhất.',
          'Đếm lỗi bằng cách kiểm tra `400 <= ma <= 599`.',
        ],
        starterCode: [
          'NHOM = {',
          '    1: "THONG TIN",',
          '    2: "THANH CONG",',
          '    3: "CHUYEN HUONG",',
          '    4: "LOI CLIENT",',
          '    5: "LOI SERVER",',
          '}',
          '',
          'n = int(input())',
          'so_loi = 0',
          '',
          'for i in range(n):',
          '    ma = int(input())',
          '    # Phan loai va dem loi',
        ].join('\n'),
        solutionCode: [
          'NHOM = {',
          '    1: "THONG TIN",',
          '    2: "THANH CONG",',
          '    3: "CHUYEN HUONG",',
          '    4: "LOI CLIENT",',
          '    5: "LOI SERVER",',
          '}',
          '',
          'n = int(input())',
          'so_loi = 0',
          '',
          'for i in range(n):',
          '    ma = int(input())',
          '    if 100 <= ma <= 599:',
          '        nhom = NHOM[ma // 100]',
          '    else:',
          '        nhom = "KHONG XAC DINH"',
          '    if 400 <= ma <= 599:',
          '        so_loi += 1',
          '    print(f"{ma} {nhom}")',
          '',
          'print(f"Loi: {so_loi}")',
        ].join('\n'),
        tier: 'CO_BAN',
        judgeMode: 'IO_MATCH',
        tests: [
          sample(
            '4\n200\n404\n500\n301\n',
            '200 THANH CONG\n404 LOI CLIENT\n500 LOI SERVER\n301 CHUYEN HUONG\nLoi: 2\n',
            'Hai mã 404 và 500 được tính là lỗi.',
          ),
          sample('2\n999\n42\n', '999 KHONG XAC DINH\n42 KHONG XAC DINH\nLoi: 0\n'),
          hidden('1\n100\n', '100 THONG TIN\nLoi: 0\n', 15),
          hidden('1\n599\n', '599 LOI SERVER\nLoi: 1\n', 15),
          hidden('1\n600\n', '600 KHONG XAC DINH\nLoi: 0\n', 20),
          hidden(
            '5\n201\n204\n401\n403\n429\n',
            '201 THANH CONG\n204 THANH CONG\n401 LOI CLIENT\n403 LOI CLIENT\n429 LOI CLIENT\nLoi: 3\n',
            25,
          ),
          hidden('2\n0\n99\n', '0 KHONG XAC DINH\n99 KHONG XAC DINH\nLoi: 0\n', 25),
        ],
      }),
    ],
  },

  {
    order: 13,
    slug: 'nc-b13-tcp-vs-udp',
    title: 'TCP vs UDP — so sánh & lựa chọn',
    summary:
      'Hai cách gửi dữ liệu qua mạng, với hai triết lý trái ngược. Biết chọn đúng là kỹ năng ' +
      'thiết kế quan trọng.',
    objectives: [
      'So sánh TCP và UDP về độ tin cậy, thứ tự và tốc độ',
      'Mô tả bắt tay ba bước của TCP',
      'Chọn được giao thức phù hợp cho từng loại ứng dụng',
      'Giải thích được vì sao game online thường dùng UDP',
    ],
    difficulty: 3,
    status: 'REQUIRED',
    teacherNotes: 'Liên hệ với khoá Pygame: vì sao game online chuộng UDP. Học sinh rất hứng thú phần này.',
    blocks: [
      theory('TCP — cuộc gọi điện thoại', [
        'TCP thiết lập một **kết nối** trước khi truyền, giống như gọi điện: phải nhấc máy, ' +
          'chào hỏi, rồi mới nói chuyện.',
        '',
        '**Bắt tay ba bước:**',
        '',
        '```',
        'Client                          Server',
        '   │──── 1. SYN  (Chao, ket noi nhe?) ──►│',
        '   │◄─── 2. SYN-ACK (Duoc, san sang) ────│',
        '   │──── 3. ACK  (Bat dau nhe) ─────────►│',
        '   │                                     │',
        '   │═════ Ket noi da san sang ══════════│',
        '```',
        '',
        '**TCP bảo đảm bốn điều:**',
        '',
        '1. **Đến nơi** — mất gói thì tự gửi lại',
        '2. **Đúng thứ tự** — gói 3 không bao giờ được xử lý trước gói 2',
        '3. **Không trùng lặp** — gói nhận hai lần thì bỏ bớt',
        '4. **Không nghẽn** — tự giảm tốc khi mạng quá tải',
        '',
        'Cái giá phải trả là **chậm hơn** và **tốn tài nguyên hơn**: mỗi kết nối cần bộ nhớ ' +
          'ở cả hai phía, và mỗi gói tin đều cần xác nhận.',
      ], [
        'TCP có kết nối, bắt tay ba bước trước khi truyền',
        'Bảo đảm đến nơi, đúng thứ tự, không trùng, không nghẽn',
        'Đổi lại: chậm hơn và tốn tài nguyên hơn',
      ]),
      theory('UDP — gửi bưu thiếp', [
        'UDP **không thiết lập kết nối**. Cứ gửi, không cần biết bên kia có nhận được không — ' +
          'giống thả bưu thiếp vào hòm thư.',
        '',
        '| Tiêu chí | TCP | UDP |',
        '|---|---|---|',
        '| Kết nối | Có, bắt tay 3 bước | Không |',
        '| Bảo đảm đến nơi | ✅ | ❌ |',
        '| Đúng thứ tự | ✅ | ❌ |',
        '| Tốc độ | Chậm hơn | **Nhanh hơn** |',
        '| Kích thước header | 20 byte | **8 byte** |',
        '| Gửi cho nhiều máy | Không | ✅ broadcast/multicast |',
        '',
        '**Khi nào dùng gì:**',
        '',
        '| Ứng dụng | Chọn | Vì sao |',
        '|---|---|---|',
        '| Tải tệp, web, email | **TCP** | Thiếu một byte là hỏng cả tệp |',
        '| Chat | **TCP** | Tin nhắn không được mất hay đảo thứ tự |',
        '| Gọi video, phát nhạc trực tuyến | **UDP** | Mất một khung hình tốt hơn là bị giật để chờ |',
        '| **Game online** | **UDP** | Vị trí cũ đến muộn thì vô dụng — thà bỏ qua |',
        '| DNS | **UDP** | Truy vấn ngắn, hỏi lại rẻ hơn duy trì kết nối |',
        '',
        '🎮 **Liên hệ với khoá Pygame:** trong game bắn súng, nếu vị trí nhân vật ở khung hình 100 ' +
          'bị mất, TCP sẽ **dừng mọi thứ lại** để gửi lại nó — trong khi khung 101, 102 đã tới nơi ' +
          'và mới hơn nhiều. UDP bỏ qua gói cũ và dùng luôn dữ liệu mới nhất. Đó là lý do game ' +
          'online gần như luôn chọn UDP.',
      ], [
        'UDP không kết nối, không bảo đảm, nhưng nhanh',
        'TCP cho dữ liệu không được sai; UDP cho dữ liệu cần đúng thời điểm',
        'Game online dùng UDP vì dữ liệu cũ đến muộn là vô dụng',
      ]),
      example('Mô phỏng khác biệt TCP và UDP', 'Không dùng mạng thật — chỉ mô phỏng để thấy hệ quả.', [
        'import random',
        '',
        'random.seed(42)      # de ket qua lap lai duoc',
        '',
        'TY_LE_MAT_GOI = 0.25',
        'TY_LE_DAO_THU_TU = 0.3',
        '',
        '',
        'def mo_phong_udp(cac_goi):',
        '    """UDP: co the mat goi va dao thu tu."""',
        '    nhan_duoc = [g for g in cac_goi if random.random() > TY_LE_MAT_GOI]',
        '    if random.random() < TY_LE_DAO_THU_TU and len(nhan_duoc) > 1:',
        '        i = random.randrange(len(nhan_duoc) - 1)',
        '        nhan_duoc[i], nhan_duoc[i + 1] = nhan_duoc[i + 1], nhan_duoc[i]',
        '    return nhan_duoc',
        '',
        '',
        'def mo_phong_tcp(cac_goi):',
        '    """TCP: gui lai goi bi mat, sap xep lai thu tu."""',
        '    so_lan_gui = 0',
        '    da_nhan = {}',
        '',
        '    for goi in cac_goi:',
        '        while True:',
        '            so_lan_gui += 1',
        '            if random.random() > TY_LE_MAT_GOI:',
        '                da_nhan[goi["stt"]] = goi',
        '                break',
        '            # mat goi -> gui lai',
        '',
        '    ket_qua = [da_nhan[stt] for stt in sorted(da_nhan)]',
        '    return ket_qua, so_lan_gui',
        '',
        '',
        'goi_tin = [{"stt": i, "noi_dung": f"khung-{i}"} for i in range(1, 9)]',
        '',
        'print("=== UDP (nhanh, khong bao dam) ===")',
        'kq_udp = mo_phong_udp(goi_tin)',
        'print(f"  Gui   : {len(goi_tin)} goi")',
        'print(f"  Nhan  : {len(kq_udp)} goi")',
        'print(f"  Thu tu: {[g[\'stt\'] for g in kq_udp]}")',
        '',
        'print()',
        'print("=== TCP (cham hon, bao dam day du) ===")',
        'kq_tcp, lan_gui = mo_phong_tcp(goi_tin)',
        'print(f"  Gui   : {lan_gui} lan (cho {len(goi_tin)} goi)")',
        'print(f"  Nhan  : {len(kq_tcp)} goi")',
        'print(f"  Thu tu: {[g[\'stt\'] for g in kq_tcp]}")',
        '',
        'print()',
        'print("=> UDP mat du lieu nhung khong ton lan gui lai.")',
        'print("=> TCP day du va dung thu tu, doi lai phai gui lai nhieu lan.")',
      ], {
        output: [
          '=== UDP (nhanh, khong bao dam) ===',
          '  Gui   : 8 goi',
          '  Nhan  : 6 goi',
          '  Thu tu: [1, 2, 4, 6, 7, 8]',
          '',
          '=== TCP (cham hon, bao dam day du) ===',
          '  Gui   : 11 lan (cho 8 goi)',
          '  Nhan  : 8 goi',
          '  Thu tu: [1, 2, 3, 4, 5, 6, 7, 8]',
          '',
          '=> UDP mat du lieu nhung khong ton lan gui lai.',
          '=> TCP day du va dung thu tu, doi lai phai gui lai nhieu lan.',
        ].join('\n'),
        notes: [
          'Kết quả cụ thể phụ thuộc `random.seed(42)`; đổi seed sẽ cho con số khác.',
          'TCP phải gửi 11 lần cho 8 gói — đó chính là cái giá của độ tin cậy.',
          'Với game bắn súng, thiếu khung 3 và 5 như UDP hoàn toàn chấp nhận được; ' +
            'còn phải chờ gửi lại như TCP thì người chơi sẽ thấy giật.',
        ],
      }),
      playground('Sân chơi: chọn giao thức', [
        'Với mỗi tình huống dưới đây, chọn TCP hay UDP và **giải thích lý do**:',
        '',
        '1. Tải một tệp PDF bài tập về máy',
        '2. Gọi video với bạn',
        '3. Trò chơi đua xe nhiều người',
        '4. Gửi email',
        '5. Đồng hồ đồng bộ thời gian (NTP)',
        '6. Chuyển khoản ngân hàng',
        '7. Xem trực tiếp trận bóng đá',
        '8. Bảng xếp hạng điểm cao trong game',
      ], [
        'lua_chon = {',
        '    "Tai tep PDF": ("TCP", "Thieu mot byte la tep hong"),',
        '    "Goi video": ("UDP", "Mat mot khung hinh tot hon bi giat"),',
        '    # Dien tiep 6 truong hop con lai',
        '}',
        '',
        'for tinh_huong, (giao_thuc, ly_do) in lua_chon.items():',
        '    print(f"{tinh_huong:<24} -> {giao_thuc:<4} ({ly_do})")',
      ], 'Chọn đúng cả 8 tình huống và giải thích được lý do cho mỗi lựa chọn.'),
      quizBlock({
        slug: 'q-nc-b13-tcp-udp',
        title: 'Kiểm tra nhanh: TCP & UDP',
        questions: [
          {
            type: 'MULTIPLE_CHOICE',
            prompt: 'Vì sao game online nhiều người thường dùng UDP thay vì TCP?',
            explanation:
              'Dữ liệu vị trí cũ đến muộn là vô dụng. TCP sẽ dừng lại để gửi lại gói cũ, gây giật.',
            choices: [
              { text: 'Vì dữ liệu cũ đến muộn là vô dụng, thà bỏ qua để dùng dữ liệu mới nhất', isCorrect: true },
              { text: 'Vì UDP mã hoá dữ liệu tốt hơn' },
              { text: 'Vì TCP không gửi được nhiều gói tin' },
              { text: 'Vì UDP bảo đảm gói tin đến đúng thứ tự' },
            ],
          },
          {
            type: 'MULTIPLE_CHOICE',
            prompt: 'Bắt tay ba bước của TCP diễn ra theo thứ tự nào?',
            explanation: 'Client gửi SYN, server đáp SYN-ACK, client xác nhận ACK.',
            choices: [
              { text: 'SYN → SYN-ACK → ACK', isCorrect: true },
              { text: 'ACK → SYN → SYN-ACK' },
              { text: 'SYN → ACK → SYN-ACK' },
              { text: 'UDP không có bắt tay nên TCP cũng không' },
            ],
          },
          {
            type: 'TRUE_FALSE',
            prompt: 'UDP bảo đảm các gói tin đến đúng thứ tự đã gửi.',
            explanation: 'Sai. UDP không bảo đảm thứ tự, không bảo đảm đến nơi, và không phát hiện trùng lặp.',
            choices: [{ text: 'Đúng' }, { text: 'Sai', isCorrect: true }],
          },
          {
            type: 'MULTIPLE_CHOICE',
            prompt: 'Ứng dụng chat nên dùng giao thức nào?',
            explanation:
              'TCP — tin nhắn không được mất và không được đảo thứ tự, còn độ trễ vài chục mili giây thì không ai để ý.',
            choices: [
              { text: 'TCP, vì tin nhắn không được mất hay đảo thứ tự', isCorrect: true },
              { text: 'UDP, vì chat cần nhanh nhất có thể' },
              { text: 'Cả hai đều tương đương' },
              { text: 'Không dùng giao thức nào cả' },
            ],
          },
        ],
      }),
    ],
  },

  {
    order: 14,
    slug: 'nc-b14-socket-tcp-server-client',
    title: 'Lập trình Socket TCP: Server & Client đầu tiên',
    summary:
      'Tự tay viết cả hai đầu của một cuộc hội thoại mạng. Server và client cùng chạy trên ' +
      '`127.0.0.1`, không cần Internet.',
    objectives: [
      'Tạo socket TCP và hiểu vai trò từng bước',
      'Viết server lắng nghe và trả lời',
      'Viết client kết nối và gửi dữ liệu',
      'Mã hoá/giải mã dữ liệu giữa chuỗi và byte',
    ],
    difficulty: 5,
    estimatedMinutes: 120,
    status: 'REQUIRED',
    teacherNotes:
      'CHÍNH SÁCH BẢO MẬT: mọi bài tập chạy trên 127.0.0.1 trong sandbox đã TẮT mạng ra ngoài. ' +
      'Loopback vẫn hoạt động nên học sinh viết socket thật. Nhấn mạnh: socket luôn làm việc với BYTE.',
    blocks: [
      theory('Sáu bước của một server TCP', [
        '```python',
        'import socket',
        '',
        'HOST = "127.0.0.1"      # loopback: chinh may nay',
        'PORT = 50007            # cong > 1024',
        '',
        '# 1. TAO socket',
        's = socket.socket(socket.AF_INET, socket.SOCK_STREAM)',
        '#                 └─ IPv4        └─ TCP (SOCK_DGRAM la UDP)',
        '',
        '# 2. Cho phep dung lai cong ngay sau khi dong',
        's.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)',
        '',
        '# 3. GAN vao dia chi va cong',
        's.bind((HOST, PORT))',
        '',
        '# 4. LANG NGHE',
        's.listen(5)             # toi da 5 ket noi cho trong hang doi',
        '',
        '# 5. CHAP NHAN mot ket noi (dung o day cho toi khi co client)',
        'ket_noi, dia_chi = s.accept()',
        '',
        '# 6. NHAN va GUI',
        'du_lieu = ket_noi.recv(1024)          # nhan toi da 1024 byte',
        'ket_noi.sendall(du_lieu.upper())',
        '',
        'ket_noi.close()',
        's.close()',
        '```',
        '',
        '⚠️ **`bind` và `listen` chỉ server làm.** Client không cần hai bước này.',
        '',
        '💡 `SO_REUSEADDR` giải quyết lỗi *"Address already in use"* rất hay gặp khi chạy lại ' +
          'server ngay sau khi tắt. Gần như lúc nào cũng nên bật.',
      ], [
        'Server: tạo → bind → listen → accept → recv/send → close',
        '`AF_INET` = IPv4, `SOCK_STREAM` = TCP',
        '`SO_REUSEADDR` tránh lỗi cổng đang bận',
      ]),
      theory('Client và chuyện byte', [
        'Client đơn giản hơn nhiều — chỉ ba bước:',
        '',
        '```python',
        's = socket.socket(socket.AF_INET, socket.SOCK_STREAM)',
        's.connect((HOST, PORT))            # KET NOI (thay cho bind/listen/accept)',
        's.sendall("xin chao".encode("utf-8"))',
        'phan_hoi = s.recv(1024).decode("utf-8")',
        's.close()',
        '```',
        '',
        '**Điều quan trọng nhất buổi này: socket chỉ làm việc với BYTE, không phải chuỗi.**',
        '',
        '```python',
        '"xin chao".encode("utf-8")     # str -> bytes:  b\'xin chao\'',
        'b"xin chao".decode("utf-8")    # bytes -> str:  \'xin chao\'',
        '```',
        '',
        'Quên `.encode()` sẽ gặp `TypeError: a bytes-like object is required`. ' +
          'Luôn dùng `"utf-8"` để tiếng Việt có dấu không bị hỏng.',
        '',
        '**Ba cạm bẫy khác:**',
        '',
        '| Bẫy | Hiện tượng | Cách xử lý |',
        '|---|---|---|',
        '| `recv()` không bảo đảm nhận đủ | Nhận thiếu dữ liệu | Lặp `recv` tới khi đủ, hoặc dùng dấu kết thúc |',
        '| Quên `close()` | Cổng bị giữ, rò rỉ tài nguyên | Dùng `with socket.socket(...) as s:` |',
        '| `accept()` chặn luồng | Chương trình treo | Dùng luồng riêng, học ở buổi 15 |',
        '',
        '```python',
        '# Cach an toan nhat: dung with (nhu buoi 4 da hoc)',
        'with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:',
        '    s.connect((HOST, PORT))',
        '    s.sendall(b"xin chao")',
        '# tu dong close, ke ca khi co loi',
        '```',
      ], [
        'Client: tạo → connect → sendall/recv → close',
        'Socket chỉ nhận BYTE — luôn `.encode()` và `.decode()`',
        'Dùng `with socket.socket(...) as s:` để tự đóng',
      ]),
      example('Server và client hoàn chỉnh trong một tệp', 'Server chạy ở luồng riêng nên cả hai cùng chạy được.', [
        'import socket',
        'import threading',
        'import time',
        '',
        'HOST = "127.0.0.1"',
        'PORT = 50007',
        '',
        '',
        'def chay_server(so_lan_phuc_vu=3):',
        '    """Server: nhan chuoi, tra ve chuoi viet hoa kem so thu tu."""',
        '    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:',
        '        s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)',
        '        s.bind((HOST, PORT))',
        '        s.listen(5)',
        '        print(f"[SERVER] Dang lang nghe tai {HOST}:{PORT}")',
        '',
        '        for lan in range(1, so_lan_phuc_vu + 1):',
        '            ket_noi, dia_chi = s.accept()',
        '            with ket_noi:',
        '                du_lieu = ket_noi.recv(1024)',
        '                tin = du_lieu.decode("utf-8")',
        '                print(f"[SERVER] Nhan tu {dia_chi}: {tin!r}")',
        '',
        '                phan_hoi = f"#{lan} {tin.upper()}"',
        '                ket_noi.sendall(phan_hoi.encode("utf-8"))',
        '',
        '        print("[SERVER] Da phuc vu xong, dong lai")',
        '',
        '',
        'def gui(tin_nhan):',
        '    """Client: gui mot chuoi, tra ve phan hoi cua server."""',
        '    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:',
        '        s.settimeout(3)',
        '        s.connect((HOST, PORT))',
        '        s.sendall(tin_nhan.encode("utf-8"))',
        '        return s.recv(1024).decode("utf-8")',
        '',
        '',
        '# Chay server o LUONG RIENG de khong chan chuong trinh chinh',
        'luong = threading.Thread(target=chay_server, args=(3,), daemon=True)',
        'luong.start()',
        'time.sleep(0.3)          # cho server kip lang nghe',
        '',
        'for tin in ["xin chao", "lap trinh mang", "da lat"]:',
        '    print(f"[CLIENT] Gui : {tin!r}")',
        '    print(f"[CLIENT] Nhan: {gui(tin)!r}")',
        '',
        'luong.join(timeout=2)',
        'print("Hoan tat.")',
      ], {
        output: [
          '[SERVER] Dang lang nghe tai 127.0.0.1:50007',
          "[CLIENT] Gui : 'xin chao'",
          "[SERVER] Nhan tu ('127.0.0.1', 51234): 'xin chao'",
          "[CLIENT] Nhan: '#1 XIN CHAO'",
          "[CLIENT] Gui : 'lap trinh mang'",
          "[CLIENT] Nhan: '#2 LAP TRINH MANG'",
          "[CLIENT] Gui : 'da lat'",
          "[CLIENT] Nhan: '#3 DA LAT'",
          '[SERVER] Da phuc vu xong, dong lai',
          'Hoan tat.',
        ].join('\n'),
        notes: [
          '`daemon=True` bảo đảm luồng server không giữ chương trình lại khi phần chính đã xong.',
          '`time.sleep(0.3)` cho server kịp `listen()` trước khi client `connect()`. Thiếu dòng này ' +
            'client có thể bị `ConnectionRefusedError`.',
          '`s.settimeout(3)` ngăn client treo vô hạn nếu server không phản hồi — luôn nên đặt.',
          'Toàn bộ chạy trên `127.0.0.1`, nên hoạt động bình thường trong sandbox đã tắt mạng ra ngoài.',
        ],
      }),
      playground('Sân chơi: server tính toán', [
        'Sửa server ở trên thành một máy tính: client gửi `"5 + 3"`, server trả về `"8"`.',
        '',
        'Hỗ trợ bốn phép `+`, `-`, `*`, `/`. Chia cho 0 thì trả về `"Loi: chia cho 0"`.',
        '',
        '⚠️ **Tuyệt đối không dùng `eval()`** để tính biểu thức nhận từ mạng — đó là lỗ hổng bảo mật ' +
          'nghiêm trọng. Hãy tự tách chuỗi và xử lý.',
      ], [
        'import socket',
        'import threading',
        'import time',
        '',
        'HOST, PORT = "127.0.0.1", 50008',
        '',
        '',
        'def tinh(bieu_thuc):',
        '    """Tinh bieu thuc dang \'a op b\'. KHONG dung eval()."""',
        '    phan = bieu_thuc.split()',
        '    if len(phan) != 3:',
        '        return "Loi: sai dinh dang"',
        '    try:',
        '        a, op, b = float(phan[0]), phan[1], float(phan[2])',
        '    except ValueError:',
        '        return "Loi: khong phai so"',
        '',
        '    if op == "+":',
        '        return str(a + b)',
        '    # Bo sung -, *, / o day',
        '    return "Loi: phep toan khong ho tro"',
        '',
        '',
        'print(tinh("5 + 3"))',
        'print(tinh("10 / 0"))',
      ], 'Server tính đúng bốn phép toán và xử lý được chia cho 0, không dùng `eval()`.'),
      challenge({
        slug: 'p-nc-b14-socket-echo-server',
        title: 'Server vọng lại trên loopback',
        statement: [
          'Viết hai hàm giao tiếp qua TCP trên `127.0.0.1`:',
          '',
          '**`xu_ly(tin_nhan)`** — hàm thuần logic, nhận chuỗi và trả về chuỗi đã **viết hoa** ' +
            'và **đảo ngược**. Ví dụ `"abc"` → `"CBA"`.',
          '',
          '**`chay_server(port, so_lan=1)`** — mở socket TCP tại `127.0.0.1:port`, ' +
            'bật `SO_REUSEADDR`, lắng nghe, và phục vụ đúng `so_lan` kết nối. Với mỗi kết nối: ' +
            'nhận dữ liệu, áp dụng `xu_ly`, gửi kết quả về, rồi đóng kết nối. Xong hết thì đóng socket.',
          '',
          '**`gui(port, tin_nhan)`** — kết nối tới `127.0.0.1:port`, gửi `tin_nhan`, ' +
            'nhận phản hồi và **trả về** phản hồi đó dưới dạng chuỗi.',
          '',
          'Mã hoá bằng `utf-8`. Bộ test sẽ chạy `chay_server` ở một luồng riêng rồi gọi `gui`.',
          '',
          '🔒 Chỉ dùng địa chỉ `127.0.0.1`. Môi trường chấm bài đã **tắt mạng ra ngoài**; ' +
            'loopback vẫn hoạt động nên bài này chạy bình thường.',
        ].join('\n'),
        hints: [
          '`xu_ly` chỉ cần `return tin_nhan.upper()[::-1]`.',
          'Nhớ `s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)` trước `bind`.',
          'Dùng `with socket.socket(...) as s:` để socket tự đóng.',
          'Trong `gui`, nhớ `.encode("utf-8")` khi gửi và `.decode("utf-8")` khi nhận.',
        ],
        starterCode: [
          'import socket',
          '',
          'HOST = "127.0.0.1"',
          '',
          '',
          'def xu_ly(tin_nhan):',
          '    """Viet hoa va dao nguoc chuoi."""',
          '    pass',
          '',
          '',
          'def chay_server(port, so_lan=1):',
          '    """Phuc vu dung so_lan ket noi roi dong."""',
          '    pass',
          '',
          '',
          'def gui(port, tin_nhan):',
          '    """Ket noi, gui, nhan phan hoi, tra ve chuoi."""',
          '    pass',
        ].join('\n'),
        solutionCode: [
          'import socket',
          '',
          'HOST = "127.0.0.1"',
          '',
          '',
          'def xu_ly(tin_nhan):',
          '    return tin_nhan.upper()[::-1]',
          '',
          '',
          'def chay_server(port, so_lan=1):',
          '    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:',
          '        s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)',
          '        s.bind((HOST, port))',
          '        s.listen(5)',
          '        for _ in range(so_lan):',
          '            ket_noi, _dia_chi = s.accept()',
          '            with ket_noi:',
          '                du_lieu = ket_noi.recv(4096)',
          '                if not du_lieu:',
          '                    continue',
          '                tra_loi = xu_ly(du_lieu.decode("utf-8"))',
          '                ket_noi.sendall(tra_loi.encode("utf-8"))',
          '',
          '',
          'def gui(port, tin_nhan):',
          '    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:',
          '        s.settimeout(5)',
          '        s.connect((HOST, port))',
          '        s.sendall(tin_nhan.encode("utf-8"))',
          '        return s.recv(4096).decode("utf-8")',
        ].join('\n'),
        tier: 'THU_THACH',
        judgeMode: 'UNIT_TEST',
        runtimeImage: 'PY_TEST',
        networkPolicy: 'NONE',
        timeLimitMs: 10000,
        unitTestCode: [
          'import socket',
          'import threading',
          'import time',
          '',
          'from solution import chay_server, gui, xu_ly',
          '',
          '',
          'def cong_trong():',
          '    """Xin he dieu hanh mot cong con trong tren loopback."""',
          '    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:',
          '        s.bind(("127.0.0.1", 0))',
          '        return s.getsockname()[1]',
          '',
          '',
          'def khoi_dong(port, so_lan):',
          '    luong = threading.Thread(target=chay_server, args=(port, so_lan), daemon=True)',
          '    luong.start()',
          '    time.sleep(0.4)',
          '    return luong',
          '',
          '',
          'def test_xu_ly_thuan_logic():',
          '    assert xu_ly("abc") == "CBA"',
          '    assert xu_ly("Da Lat") == "TAL AD"',
          '    assert xu_ly("") == ""',
          '',
          '',
          'def test_mot_vong_gui_nhan():',
          '    port = cong_trong()',
          '    khoi_dong(port, 1)',
          '    assert gui(port, "xin chao") == "OAHC NIX"',
          '',
          '',
          'def test_nhieu_ket_noi_lien_tiep():',
          '    port = cong_trong()',
          '    khoi_dong(port, 3)',
          '    assert gui(port, "abc") == "CBA"',
          '    assert gui(port, "python") == "NOHTYP"',
          '    assert gui(port, "12345") == "54321"',
          '',
          '',
          'def test_giu_duoc_tieng_viet():',
          '    port = cong_trong()',
          '    khoi_dong(port, 1)',
          '    assert gui(port, "khong dau") == "UAD GNOHK"',
          '',
          '',
          'def test_server_dong_sau_khi_xong():',
          '    """Sau khi phuc vu du so_lan, server phai nha cong ra."""',
          '    port = cong_trong()',
          '    luong = khoi_dong(port, 1)',
          '    gui(port, "abc")',
          '    luong.join(timeout=3)',
          '    assert not luong.is_alive()',
        ].join('\n'),
        totalPoints: 100,
      }),
    ],
  },

  {
    order: 15,
    slug: 'nc-b15-du-an-chat-server-client',
    title: 'Dự án: Chat Server / Client',
    summary:
      'Dự án lớn của chương: một phòng chat nhiều người, server dùng luồng để phục vụ đồng thời ' +
      'và phát lại tin nhắn cho mọi người.',
    objectives: [
      'Dùng `threading` để phục vụ nhiều kết nối cùng lúc',
      'Phát lại (broadcast) tin nhắn tới mọi client',
      'Xử lý client ngắt kết nối đột ngột',
      'Thiết kế giao thức tin nhắn đơn giản',
    ],
    difficulty: 5,
    estimatedMinutes: 120,
    status: 'REQUIRED',
    teacherNotes:
      'Dự án chính của Chương 2. Toàn bộ chạy trên 127.0.0.1. Nhấn mạnh phần xử lý ngắt kết nối — ' +
      'học sinh hay quên và server sẽ sập.',
    blocks: [
      theory('Vì sao cần luồng', [
        'Server ở buổi 14 chỉ phục vụ **một client tại một thời điểm**, vì `accept()` và `recv()` ' +
          'đều **chặn** luồng đang chạy.',
        '',
        '```',
        'Khong co luong:                  Co luong:',
        '  accept() ─► phuc vu A            accept() ─► [Luong A] phuc vu A',
        '  (B phai cho A xong)              accept() ─► [Luong B] phuc vu B',
        '  accept() ─► phuc vu B            accept() ─► [Luong C] phuc vu C',
        '```',
        '',
        '```python',
        'import threading',
        '',
        'while dang_chay:',
        '    ket_noi, dia_chi = s.accept()',
        '    luong = threading.Thread(',
        '        target=phuc_vu_client,',
        '        args=(ket_noi, dia_chi),',
        '        daemon=True,',
        '    )',
        '    luong.start()          # phuc vu client nay o luong rieng',
        '    # vong lap quay lai accept() ngay -> san sang cho client tiep theo',
        '```',
        '',
        '⚠️ **Nhiều luồng cùng sửa một danh sách là nguy hiểm.** Dùng `threading.Lock()` để bảo vệ:',
        '',
        '```python',
        'khoa = threading.Lock()',
        'danh_sach_client = []',
        '',
        'with khoa:',
        '    danh_sach_client.append(ket_noi)     # chi mot luong vao duoc tai mot thoi diem',
        '```',
      ], [
        'Mỗi client một luồng riêng để phục vụ đồng thời',
        '`daemon=True` để luồng không giữ chương trình lại',
        '`Lock()` bảo vệ dữ liệu dùng chung giữa các luồng',
      ]),
      theory('Broadcast và xử lý ngắt kết nối', [
        '**Phát lại tin nhắn cho mọi người:**',
        '',
        '```python',
        'def phat_lai(tin_nhan, tru_ai=None):',
        '    """Gui tin nhan toi moi client, tru mot nguoi."""',
        '    hong = []',
        '    with khoa:',
        '        for kn in danh_sach_client:',
        '            if kn is tru_ai:',
        '                continue',
        '            try:',
        '                kn.sendall(tin_nhan.encode("utf-8"))',
        '            except OSError:',
        '                hong.append(kn)      # client nay da mat ket noi',
        '',
        '        for kn in hong:',
        '            danh_sach_client.remove(kn)',
        '```',
        '',
        '**Ba tình huống ngắt kết nối phải xử lý:**',
        '',
        '| Tình huống | Dấu hiệu | Cách xử lý |',
        '|---|---|---|',
        '| Thoát lịch sự | `recv()` trả về `b""` | Xoá khỏi danh sách |',
        '| Đóng đột ngột | `ConnectionResetError` | Bắt bằng `try/except` |',
        '| Mạng hỏng | `OSError` khi gửi | Đánh dấu hỏng, dọn sau |',
        '',
        '⚠️ **`recv()` trả về `b""` nghĩa là client đã đóng.** Không kiểm tra điều này thì server ' +
          'sẽ lặp vô hạn với chuỗi rỗng và ngốn 100% CPU.',
        '',
        '```python',
        'def phuc_vu_client(ket_noi, dia_chi):',
        '    try:',
        '        while True:',
        '            du_lieu = ket_noi.recv(1024)',
        '            if not du_lieu:               # <-- BAT BUOC kiem tra',
        '                break',
        '            phat_lai(du_lieu.decode("utf-8"), tru_ai=ket_noi)',
        '    except (ConnectionResetError, OSError):',
        '        pass',
        '    finally:',
        '        with khoa:',
        '            if ket_noi in danh_sach_client:',
        '                danh_sach_client.remove(ket_noi)',
        '        ket_noi.close()',
        '```',
        '',
        'Khối `finally` bảo đảm client luôn được dọn khỏi danh sách, dù thoát kiểu gì.',
      ], [
        '`recv()` trả `b""` = client đã đóng, phải `break`',
        'Bọc mọi thao tác socket trong `try/except`',
        '`finally` để luôn dọn dẹp danh sách client',
      ]),
      example('Phòng chat hoàn chỉnh', 'Server đa luồng và ba client, tất cả trên loopback.', [
        'import socket',
        'import threading',
        'import time',
        '',
        'HOST, PORT = "127.0.0.1", 50010',
        '',
        'danh_sach_client = []',
        'khoa = threading.Lock()',
        'nhat_ky = []',
        '',
        '',
        'def phat_lai(tin_nhan, tru_ai=None):',
        '    """Gui tin nhan toi moi client dang ket noi."""',
        '    hong = []',
        '    with khoa:',
        '        for kn in danh_sach_client:',
        '            if kn is tru_ai:',
        '                continue',
        '            try:',
        '                kn.sendall(tin_nhan.encode("utf-8"))',
        '            except OSError:',
        '                hong.append(kn)',
        '        for kn in hong:',
        '            danh_sach_client.remove(kn)',
        '',
        '',
        'def phuc_vu_client(ket_noi, dia_chi):',
        '    """Vong doi cua mot client tren server."""',
        '    ten = f"Nguoi-{dia_chi[1]}"',
        '    with khoa:',
        '        danh_sach_client.append(ket_noi)',
        '    nhat_ky.append(f"{ten} vao phong")',
        '    phat_lai(f"* {ten} da vao phong\\n", tru_ai=ket_noi)',
        '',
        '    try:',
        '        while True:',
        '            du_lieu = ket_noi.recv(1024)',
        '            if not du_lieu:',
        '                break',
        '            tin = du_lieu.decode("utf-8").strip()',
        '            nhat_ky.append(f"{ten}: {tin}")',
        '            phat_lai(f"[{ten}] {tin}\\n", tru_ai=ket_noi)',
        '    except (ConnectionResetError, OSError):',
        '        pass',
        '    finally:',
        '        with khoa:',
        '            if ket_noi in danh_sach_client:',
        '                danh_sach_client.remove(ket_noi)',
        '        ket_noi.close()',
        '        nhat_ky.append(f"{ten} roi phong")',
        '        phat_lai(f"* {ten} da roi phong\\n")',
        '',
        '',
        'def chay_server(thoi_gian_song=2.5):',
        '    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:',
        '        s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)',
        '        s.bind((HOST, PORT))',
        '        s.listen(10)',
        '        s.settimeout(0.5)',
        '        het_han = time.time() + thoi_gian_song',
        '',
        '        while time.time() < het_han:',
        '            try:',
        '                ket_noi, dia_chi = s.accept()',
        '            except socket.timeout:',
        '                continue',
        '            threading.Thread(target=phuc_vu_client,',
        '                             args=(ket_noi, dia_chi), daemon=True).start()',
        '',
        '',
        'def client_gia(ten, cac_tin):',
        '    """Mot client tu dong: gui vai tin roi thoat."""',
        '    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:',
        '        s.settimeout(2)',
        '        s.connect((HOST, PORT))',
        '        for tin in cac_tin:',
        '            time.sleep(0.15)',
        '            s.sendall(f"{tin}".encode("utf-8"))',
        '        time.sleep(0.3)',
        '',
        '',
        'threading.Thread(target=chay_server, daemon=True).start()',
        'time.sleep(0.3)',
        '',
        'cac_luong = [',
        '    threading.Thread(target=client_gia, args=("A", ["xin chao", "co ai khong?"])),',
        '    threading.Thread(target=client_gia, args=("B", ["chao ban"])),',
        '    threading.Thread(target=client_gia, args=("C", ["minh moi vao"])),',
        ']',
        'for lg in cac_luong:',
        '    lg.start()',
        '    time.sleep(0.1)',
        'for lg in cac_luong:',
        '    lg.join()',
        '',
        'time.sleep(0.4)',
        'print("=== NHAT KY PHONG CHAT ===")',
        'for dong in nhat_ky:',
        '    print(" ", dong)',
      ], {
        output: [
          '=== NHAT KY PHONG CHAT ===',
          '  Nguoi-51201 vao phong',
          '  Nguoi-51202 vao phong',
          '  Nguoi-51203 vao phong',
          '  Nguoi-51201: xin chao',
          '  Nguoi-51202: chao ban',
          '  Nguoi-51203: minh moi vao',
          '  Nguoi-51201: co ai khong?',
          '  Nguoi-51202 roi phong',
          '  Nguoi-51203 roi phong',
          '  Nguoi-51201 roi phong',
        ].join('\n'),
        notes: [
          'Số cổng trong tên là ngẫu nhiên nên mỗi lần chạy sẽ khác; thứ tự dòng cũng có thể đổi vì đa luồng.',
          '`s.settimeout(0.5)` trên socket lắng nghe cho phép vòng lặp `accept()` thoát ra được — ' +
            'nếu không, server treo mãi.',
          'Khối `finally` bảo đảm mọi client đều được ghi "roi phong", kể cả khi ngắt đột ngột.',
          'Toàn bộ dùng `127.0.0.1`, chạy được trong sandbox đã tắt mạng ra ngoài.',
        ],
      }),
      playground('Sân chơi: nâng cấp phòng chat', [
        'Thêm lần lượt vào phòng chat:',
        '',
        '1. **Đặt tên** — client gửi tên ở tin nhắn đầu tiên, server dùng tên đó thay cho số cổng',
        '2. **Lệnh `/danh-sach`** — server trả về danh sách người đang online',
        '3. **Tin nhắn riêng** — `/rieng <ten> <noi dung>` chỉ gửi cho một người',
        '4. **Lịch sử** — người mới vào nhận 10 tin nhắn gần nhất',
      ], [
        'import threading',
        '',
        'khoa = threading.Lock()',
        'nguoi_dung = {}      # {ket_noi: ten}',
        'lich_su = []         # 10 tin gan nhat',
        '',
        '',
        'def them_lich_su(tin):',
        '    """Giu toi da 10 tin gan nhat."""',
        '    with khoa:',
        '        lich_su.append(tin)',
        '        if len(lich_su) > 10:',
        '            lich_su.pop(0)',
        '',
        '',
        'def xu_ly_lenh(ket_noi, tin):',
        '    """Xu ly cac lenh bat dau bang /."""',
        '    if tin == "/danh-sach":',
        '        with khoa:',
        '            ds = ", ".join(nguoi_dung.values())',
        '        return f"* Dang online: {ds}\\n"',
        '    # Bo sung /rieng o day',
        '    return None',
        '',
        '',
        'print("Bo khung - hay ghep vao server chat o phan vi du")',
      ], 'Thêm được ít nhất hai tính năng và phòng chat vẫn ổn định khi client thoát đột ngột.'),
      challenge({
        slug: 'p-nc-b15-chat-broadcast',
        title: 'Server chat có broadcast',
        statement: [
          'Viết một server chat tối giản trên `127.0.0.1`:',
          '',
          '**`dinh_dang(ten, tin_nhan)`** — hàm thuần logic, trả về `f"[{ten}] {tin_nhan}"`.',
          '',
          '**`ChatServer`** — một lớp với:',
          '',
          '- `__init__(self, port)` → lưu `self.port`, tạo `self.clients = []` (danh sách rỗng **mới**), ' +
            '`self.nhat_ky = []`, và `self.khoa = threading.Lock()`',
          '- `them_client(self, kn)` → thêm `kn` vào `self.clients`, có dùng khoá',
          '- `xoa_client(self, kn)` → xoá `kn` khỏi `self.clients` nếu có, có dùng khoá',
          '- `phat_lai(self, noi_dung, tru_ai=None)` → gửi `noi_dung` (đã `.encode("utf-8")`) tới ' +
            'mọi client trừ `tru_ai`; client nào gây `OSError` thì bị xoá khỏi danh sách. ' +
            'Trả về **số client đã gửi thành công**',
          '',
          'Bộ test dùng đối tượng giả lập thay cho socket thật, nên em **không cần** viết phần ' +
            '`accept()` — chỉ cần phần quản lý danh sách và phát lại cho đúng.',
        ].join('\n'),
        hints: [
          '`self.clients = []` phải nằm trong `__init__`, không phải ở thân lớp.',
          '`phat_lai` nên gom các client hỏng vào một danh sách riêng rồi xoá sau vòng lặp — ' +
            'xoá trong lúc duyệt sẽ bỏ sót phần tử.',
          'Đếm số gửi thành công bằng một biến cộng dồn, chỉ tăng khi `sendall` không ném lỗi.',
        ],
        starterCode: [
          'import threading',
          '',
          '',
          'def dinh_dang(ten, tin_nhan):',
          '    pass',
          '',
          '',
          'class ChatServer:',
          '    def __init__(self, port):',
          '        pass',
          '',
          '    def them_client(self, kn):',
          '        pass',
          '',
          '    def xoa_client(self, kn):',
          '        pass',
          '',
          '    def phat_lai(self, noi_dung, tru_ai=None):',
          '        pass',
        ].join('\n'),
        solutionCode: [
          'import threading',
          '',
          '',
          'def dinh_dang(ten, tin_nhan):',
          '    return f"[{ten}] {tin_nhan}"',
          '',
          '',
          'class ChatServer:',
          '    def __init__(self, port):',
          '        self.port = port',
          '        self.clients = []',
          '        self.nhat_ky = []',
          '        self.khoa = threading.Lock()',
          '',
          '    def them_client(self, kn):',
          '        with self.khoa:',
          '            self.clients.append(kn)',
          '',
          '    def xoa_client(self, kn):',
          '        with self.khoa:',
          '            if kn in self.clients:',
          '                self.clients.remove(kn)',
          '',
          '    def phat_lai(self, noi_dung, tru_ai=None):',
          '        da_gui = 0',
          '        hong = []',
          '        with self.khoa:',
          '            for kn in self.clients:',
          '                if kn is tru_ai:',
          '                    continue',
          '                try:',
          '                    kn.sendall(noi_dung.encode("utf-8"))',
          '                    da_gui += 1',
          '                except OSError:',
          '                    hong.append(kn)',
          '            for kn in hong:',
          '                self.clients.remove(kn)',
          '        return da_gui',
        ].join('\n'),
        tier: 'NANG_CAO',
        judgeMode: 'UNIT_TEST',
        runtimeImage: 'PY_TEST',
        networkPolicy: 'NONE',
        unitTestCode: [
          'import threading',
          '',
          'from solution import ChatServer, dinh_dang',
          '',
          '',
          'class ClientGia:',
          '    """Gia lap mot socket client."""',
          '',
          '    def __init__(self, hong=False):',
          '        self.hong = hong',
          '        self.da_nhan = []',
          '',
          '    def sendall(self, du_lieu):',
          '        if self.hong:',
          '            raise OSError("ket noi dut")',
          '        self.da_nhan.append(du_lieu)',
          '',
          '',
          'def test_dinh_dang():',
          '    assert dinh_dang("Lan", "xin chao") == "[Lan] xin chao"',
          '',
          '',
          'def test_khoi_tao():',
          '    s = ChatServer(50011)',
          '    assert s.port == 50011',
          '    assert s.clients == []',
          '    assert s.nhat_ky == []',
          '    assert isinstance(s.khoa, type(threading.Lock()))',
          '',
          '',
          'def test_danh_sach_khong_dung_chung():',
          '    a, b = ChatServer(1), ChatServer(2)',
          '    a.them_client(ClientGia())',
          '    assert len(b.clients) == 0',
          '',
          '',
          'def test_them_va_xoa():',
          '    s = ChatServer(1)',
          '    c = ClientGia()',
          '    s.them_client(c)',
          '    assert c in s.clients',
          '    s.xoa_client(c)',
          '    assert c not in s.clients',
          '',
          '',
          'def test_xoa_client_khong_ton_tai():',
          '    s = ChatServer(1)',
          '    s.xoa_client(ClientGia())      # khong duoc bao loi',
          '    assert s.clients == []',
          '',
          '',
          'def test_phat_lai_cho_moi_nguoi():',
          '    s = ChatServer(1)',
          '    a, b, c = ClientGia(), ClientGia(), ClientGia()',
          '    for x in (a, b, c):',
          '        s.them_client(x)',
          '',
          '    assert s.phat_lai("xin chao") == 3',
          '    for x in (a, b, c):',
          '        assert x.da_nhan == [b"xin chao"]',
          '',
          '',
          'def test_phat_lai_tru_mot_nguoi():',
          '    s = ChatServer(1)',
          '    a, b = ClientGia(), ClientGia()',
          '    s.them_client(a)',
          '    s.them_client(b)',
          '',
          '    assert s.phat_lai("tin", tru_ai=a) == 1',
          '    assert a.da_nhan == []',
          '    assert b.da_nhan == [b"tin"]',
          '',
          '',
          'def test_client_hong_bi_xoa():',
          '    s = ChatServer(1)',
          '    tot, hong = ClientGia(), ClientGia(hong=True)',
          '    s.them_client(tot)',
          '    s.them_client(hong)',
          '',
          '    assert s.phat_lai("tin") == 1',
          '    assert hong not in s.clients',
          '    assert tot in s.clients',
          '',
          '',
          'def test_ma_hoa_utf8():',
          '    s = ChatServer(1)',
          '    c = ClientGia()',
          '    s.them_client(c)',
          '    s.phat_lai("abc")',
          '    assert isinstance(c.da_nhan[0], bytes)',
        ].join('\n'),
        totalPoints: 100,
      }),
      projectBlock(
        'Dự án Chương 2: Phòng chat của em',
        [
          'Hoàn thiện ứng dụng chat chạy trên `127.0.0.1`.',
          '',
          '**Yêu cầu bắt buộc:**',
          '',
          '- Server phục vụ được **ít nhất 3 client cùng lúc** bằng `threading`',
          '- Tin nhắn của một người được phát lại cho mọi người còn lại',
          '- Xử lý đúng khi client thoát (lịch sự và đột ngột) — server **không được sập**',
          '- Client có giao diện dòng lệnh nhập và hiện tin nhắn',
          '',
          '**Điểm cộng:** đặt tên người dùng, lệnh `/danh-sach`, tin nhắn riêng, lịch sử tin nhắn, ' +
            'ghi nhật ký ra tệp.',
          '',
          '🔒 **Bắt buộc dùng `127.0.0.1`.** Không mở server ra mạng ngoài.',
          '',
          '**Nộp kèm:** một đoạn mô tả ngắn giao thức tin nhắn em thiết kế (định dạng tin nhắn, ' +
            'các lệnh, cách server phản hồi).',
        ],
        'CUSTOM',
        [
          'Server một client hoạt động (dựa trên buổi 14)',
          'Thêm threading để phục vụ nhiều client',
          'Thêm broadcast và xử lý ngắt kết nối',
          'Hoàn thiện client, thử với 3 cửa sổ cùng lúc, nộp bài',
        ],
        { minutes: 70 },
      ),
    ],
  },

  {
    order: 16,
    slug: 'nc-b16-socket-udp-va-tong-ket',
    title: 'Socket UDP & tổng kết chương',
    summary:
      'Đổi một dòng code là chuyển từ TCP sang UDP. Buổi cuối chương so sánh trực tiếp hai cách ' +
      'và hệ thống lại kiến thức mạng.',
    objectives: [
      'Viết server và client UDP',
      'So sánh trực tiếp code TCP và UDP',
      'Nhận ra hệ quả của việc UDP không bảo đảm',
      'Hệ thống lại toàn bộ Chương 2',
    ],
    difficulty: 4,
    status: 'RECOMMENDED',
    isDerived: true,
    teacherNotes:
      'Buổi tổng kết (⟨derived⟩). Học sinh dừng ở buổi 15 vẫn nắm đủ phần cốt lõi của chương.',
    blocks: [
      theory('UDP — ít bước hơn hẳn', [
        'UDP không có kết nối, nên không cần `listen()`, `accept()` hay `connect()`.',
        '',
        '```python',
        'import socket',
        '',
        '# ===== SERVER UDP =====',
        's = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)   # DGRAM thay vi STREAM',
        's.bind(("127.0.0.1", 50020))',
        '',
        'du_lieu, dia_chi = s.recvfrom(1024)    # nhan KEM dia chi nguoi gui',
        's.sendto(du_lieu.upper(), dia_chi)     # gui THANG toi dia chi do',
        '',
        '# ===== CLIENT UDP =====',
        'c = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)',
        'c.sendto(b"xin chao", ("127.0.0.1", 50020))    # khong can connect',
        'phan_hoi, _ = c.recvfrom(1024)',
        '```',
        '',
        '| | TCP | UDP |',
        '|---|---|---|',
        '| Loại socket | `SOCK_STREAM` | `SOCK_DGRAM` |',
        '| Server | bind, listen, accept | **chỉ bind** |',
        '| Client | connect | **không cần gì** |',
        '| Nhận | `recv()` | `recvfrom()` → kèm địa chỉ |',
        '| Gửi | `sendall()` | `sendto()` → kèm địa chỉ |',
        '',
        '**Vì sao UDP cần địa chỉ mỗi lần?** Vì không có kết nối, socket không "nhớ" đang nói ' +
          'chuyện với ai. Mỗi gói tin phải tự mang theo địa chỉ đích.',
        '',
        '💡 Đó cũng là lý do một socket UDP phục vụ được nhiều client mà **không cần luồng nào** — ' +
          'hoàn toàn khác với server TCP ở buổi 15.',
      ], [
        '`SOCK_DGRAM` thay cho `SOCK_STREAM`',
        'UDP: chỉ bind ở server, client không cần connect',
        '`recvfrom`/`sendto` luôn kèm địa chỉ',
        'Một socket UDP phục vụ nhiều client không cần luồng',
      ]),
      example('TCP và UDP cạnh nhau', 'Cùng một chức năng, hai cách cài đặt.', [
        'import socket',
        'import threading',
        'import time',
        '',
        'HOST = "127.0.0.1"',
        'PORT_TCP, PORT_UDP = 50021, 50022',
        '',
        '',
        '# ================= TCP =================',
        'def server_tcp(so_lan=2):',
        '    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:',
        '        s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)',
        '        s.bind((HOST, PORT_TCP))',
        '        s.listen(5)',
        '        for _ in range(so_lan):',
        '            kn, _dc = s.accept()',
        '            with kn:',
        '                data = kn.recv(1024)',
        '                kn.sendall(b"TCP:" + data.upper())',
        '',
        '',
        'def client_tcp(tin):',
        '    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:',
        '        s.settimeout(2)',
        '        s.connect((HOST, PORT_TCP))',
        '        s.sendall(tin.encode())',
        '        return s.recv(1024).decode()',
        '',
        '',
        '# ================= UDP =================',
        'def server_udp(so_lan=2):',
        '    with socket.socket(socket.AF_INET, socket.SOCK_DGRAM) as s:',
        '        s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)',
        '        s.bind((HOST, PORT_UDP))',
        '        s.settimeout(3)',
        '        for _ in range(so_lan):',
        '            data, dia_chi = s.recvfrom(1024)',
        '            s.sendto(b"UDP:" + data.upper(), dia_chi)',
        '',
        '',
        'def client_udp(tin):',
        '    with socket.socket(socket.AF_INET, socket.SOCK_DGRAM) as s:',
        '        s.settimeout(2)',
        '        s.sendto(tin.encode(), (HOST, PORT_UDP))',
        '        data, _dc = s.recvfrom(1024)',
        '        return data.decode()',
        '',
        '',
        'threading.Thread(target=server_tcp, daemon=True).start()',
        'threading.Thread(target=server_udp, daemon=True).start()',
        'time.sleep(0.3)',
        '',
        'print("=== So sanh ===")',
        'for tin in ["xin chao", "da lat"]:',
        '    print(f"  Gui  : {tin!r}")',
        'print()',
        'print(f"  TCP  -> {client_tcp(\'xin chao\')!r}")',
        'print(f"  UDP  -> {client_udp(\'xin chao\')!r}")',
        'print(f"  TCP  -> {client_tcp(\'da lat\')!r}")',
        'print(f"  UDP  -> {client_udp(\'da lat\')!r}")',
        '',
        'print()',
        'print("So dong code phia client:")',
        'print("  TCP: tao -> connect -> sendall -> recv        (4 buoc)")',
        'print("  UDP: tao -> sendto -> recvfrom                (3 buoc)")',
      ], {
        output: [
          '=== So sanh ===',
          "  Gui  : 'xin chao'",
          "  Gui  : 'da lat'",
          '',
          "  TCP  -> 'TCP:XIN CHAO'",
          "  UDP  -> 'UDP:XIN CHAO'",
          "  TCP  -> 'TCP:DA LAT'",
          "  UDP  -> 'UDP:DA LAT'",
          '',
          'So dong code phia client:',
          '  TCP: tao -> connect -> sendall -> recv        (4 buoc)',
          '  UDP: tao -> sendto -> recvfrom                (3 buoc)',
        ].join('\n'),
        notes: [
          'Hai server chỉ khác nhau ở `SOCK_DGRAM` và cặp `recvfrom`/`sendto` — phần còn lại gần như giống hệt.',
          'Server UDP không cần `listen()` và `accept()`, nên ngắn hơn đáng kể.',
          '`settimeout` ở server UDP rất quan trọng: không có nó, `recvfrom` sẽ chờ mãi nếu không ai gửi.',
        ],
      }),
      playground('Sân chơi: đo mất gói của UDP', [
        'Gửi 100 gói UDP thật nhanh rồi đếm xem server nhận được bao nhiêu.',
        '',
        'Trên loopback tỉ lệ mất gói thường rất thấp, nhưng nếu gửi đủ nhanh vẫn có thể thấy hiện tượng.',
        '',
        'Sau đó thử làm điều tương tự với TCP và so sánh.',
      ], [
        'import socket',
        'import threading',
        'import time',
        '',
        'HOST, PORT = "127.0.0.1", 50023',
        'SO_GOI = 100',
        'da_nhan = []',
        '',
        '',
        'def server():',
        '    with socket.socket(socket.AF_INET, socket.SOCK_DGRAM) as s:',
        '        s.bind((HOST, PORT))',
        '        s.settimeout(2)',
        '        while True:',
        '            try:',
        '                data, _ = s.recvfrom(1024)',
        '                da_nhan.append(int(data.decode()))',
        '            except socket.timeout:',
        '                break',
        '',
        '',
        'threading.Thread(target=server, daemon=True).start()',
        'time.sleep(0.3)',
        '',
        'with socket.socket(socket.AF_INET, socket.SOCK_DGRAM) as c:',
        '    for i in range(SO_GOI):',
        '        c.sendto(str(i).encode(), (HOST, PORT))',
        '',
        'time.sleep(2.5)',
        'print(f"Gui  : {SO_GOI} goi")',
        'print(f"Nhan : {len(da_nhan)} goi")',
        'print(f"Mat  : {SO_GOI - len(da_nhan)} goi")',
        'thieu = sorted(set(range(SO_GOI)) - set(da_nhan))',
        'print(f"Goi thieu: {thieu[:10]}{\'...\' if len(thieu) > 10 else \'\'}")',
      ], 'Đo được số gói mất và giải thích được vì sao TCP không gặp hiện tượng này.'),
      challenge({
        slug: 'p-nc-b16-udp-echo',
        title: 'Server UDP vọng lại',
        statement: [
          'Viết server và client UDP trên `127.0.0.1`:',
          '',
          '**`bien_doi(tin_nhan)`** — hàm thuần logic: trả về `tin_nhan` với **mỗi từ được viết hoa ' +
            'chữ cái đầu**, các từ nối bằng một dấu cách. Ví dụ `"da lat xinh"` → `"Da Lat Xinh"`.',
          '',
          '**`chay_server_udp(port, so_goi=1)`** — tạo socket UDP, bật `SO_REUSEADDR`, ' +
            'bind vào `127.0.0.1:port`, đặt timeout 5 giây, rồi nhận đúng `so_goi` gói. ' +
            'Với mỗi gói: áp dụng `bien_doi` và gửi kết quả **về đúng địa chỉ người gửi**.',
          '',
          '**`gui_udp(port, tin_nhan)`** — tạo socket UDP, đặt timeout 5 giây, gửi `tin_nhan` tới ' +
            '`127.0.0.1:port`, nhận phản hồi và **trả về** chuỗi phản hồi.',
          '',
          'Mã hoá `utf-8`. Bộ test chạy server ở luồng riêng rồi gọi client.',
          '',
          '🔒 Chỉ dùng `127.0.0.1`.',
        ].join('\n'),
        hints: [
          '`bien_doi` gọn nhất là `" ".join(t.capitalize() for t in tin_nhan.split())`.',
          '`socket.SOCK_DGRAM` cho UDP.',
          '`data, dia_chi = s.recvfrom(1024)` rồi `s.sendto(ket_qua, dia_chi)`.',
          'Client UDP **không** gọi `connect()` — dùng thẳng `sendto` với địa chỉ đích.',
        ],
        starterCode: [
          'import socket',
          '',
          'HOST = "127.0.0.1"',
          '',
          '',
          'def bien_doi(tin_nhan):',
          '    """Viet hoa chu cai dau moi tu."""',
          '    pass',
          '',
          '',
          'def chay_server_udp(port, so_goi=1):',
          '    pass',
          '',
          '',
          'def gui_udp(port, tin_nhan):',
          '    pass',
        ].join('\n'),
        solutionCode: [
          'import socket',
          '',
          'HOST = "127.0.0.1"',
          '',
          '',
          'def bien_doi(tin_nhan):',
          '    return " ".join(tu.capitalize() for tu in tin_nhan.split())',
          '',
          '',
          'def chay_server_udp(port, so_goi=1):',
          '    with socket.socket(socket.AF_INET, socket.SOCK_DGRAM) as s:',
          '        s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)',
          '        s.bind((HOST, port))',
          '        s.settimeout(5)',
          '        for _ in range(so_goi):',
          '            data, dia_chi = s.recvfrom(4096)',
          '            ket_qua = bien_doi(data.decode("utf-8"))',
          '            s.sendto(ket_qua.encode("utf-8"), dia_chi)',
          '',
          '',
          'def gui_udp(port, tin_nhan):',
          '    with socket.socket(socket.AF_INET, socket.SOCK_DGRAM) as s:',
          '        s.settimeout(5)',
          '        s.sendto(tin_nhan.encode("utf-8"), (HOST, port))',
          '        data, _dia_chi = s.recvfrom(4096)',
          '        return data.decode("utf-8")',
        ].join('\n'),
        tier: 'NANG_CAO',
        judgeMode: 'UNIT_TEST',
        runtimeImage: 'PY_TEST',
        networkPolicy: 'NONE',
        timeLimitMs: 10000,
        unitTestCode: [
          'import socket',
          'import threading',
          'import time',
          '',
          'from solution import bien_doi, chay_server_udp, gui_udp',
          '',
          '',
          'def cong_trong():',
          '    with socket.socket(socket.AF_INET, socket.SOCK_DGRAM) as s:',
          '        s.bind(("127.0.0.1", 0))',
          '        return s.getsockname()[1]',
          '',
          '',
          'def khoi_dong(port, so_goi):',
          '    luong = threading.Thread(target=chay_server_udp, args=(port, so_goi), daemon=True)',
          '    luong.start()',
          '    time.sleep(0.4)',
          '    return luong',
          '',
          '',
          'def test_bien_doi():',
          '    assert bien_doi("da lat xinh") == "Da Lat Xinh"',
          '    assert bien_doi("PYTHON") == "Python"',
          '    assert bien_doi("") == ""',
          '    assert bien_doi("  nhieu   khoang   trang  ") == "Nhieu Khoang Trang"',
          '',
          '',
          'def test_mot_goi():',
          '    port = cong_trong()',
          '    khoi_dong(port, 1)',
          '    assert gui_udp(port, "da lat xinh") == "Da Lat Xinh"',
          '',
          '',
          'def test_nhieu_goi_lien_tiep():',
          '    port = cong_trong()',
          '    khoi_dong(port, 3)',
          '    assert gui_udp(port, "xin chao") == "Xin Chao"',
          '    assert gui_udp(port, "lap trinh mang") == "Lap Trinh Mang"',
          '    assert gui_udp(port, "python") == "Python"',
          '',
          '',
          'def test_dung_socket_udp():',
          '    """Server phai la UDP: client TCP khong ket noi duoc."""',
          '    port = cong_trong()',
          '    khoi_dong(port, 1)',
          '    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:',
          '        s.settimeout(1)',
          '        try:',
          '            s.connect(("127.0.0.1", port))',
          '            ket_noi_duoc = True',
          '        except OSError:',
          '            ket_noi_duoc = False',
          '    assert not ket_noi_duoc',
          '    gui_udp(port, "dong server")',
        ].join('\n'),
        totalPoints: 100,
      }),
      quizBlock({
        slug: 'q-nc-b16-tong-ket-chuong-2',
        title: 'Tổng kết Chương 2: Lập trình mạng',
        passingScore: 70,
        questions: [
          {
            type: 'MULTIPLE_CHOICE',
            prompt: 'Bước nào chỉ có ở server TCP mà client TCP không cần?',
            explanation: '`bind` và `listen` là việc của server. Client chỉ `connect`.',
            choices: [
              { text: 'bind và listen', isCorrect: true },
              { text: 'socket()' },
              { text: 'recv()' },
              { text: 'close()' },
            ],
          },
          {
            type: 'MULTIPLE_CHOICE',
            prompt: '`recv()` trả về `b""` nghĩa là gì?',
            explanation:
              'Client đã đóng kết nối. Không kiểm tra điều này thì server lặp vô hạn và ngốn CPU.',
            choices: [
              { text: 'Client đã đóng kết nối', isCorrect: true },
              { text: 'Dữ liệu đang trên đường tới' },
              { text: 'Có lỗi mạng tạm thời' },
              { text: 'Client gửi một chuỗi rỗng' },
            ],
          },
          {
            type: 'MULTIPLE_CHOICE',
            prompt: 'Vì sao socket cần `.encode()` và `.decode()`?',
            explanation: 'Socket chỉ truyền byte, không truyền chuỗi Python.',
            choices: [
              { text: 'Vì socket chỉ làm việc với byte, không phải chuỗi', isCorrect: true },
              { text: 'Để nén dữ liệu cho nhẹ hơn' },
              { text: 'Để mã hoá bảo mật' },
              { text: 'Không cần thiết, chỉ là thói quen' },
            ],
          },
          {
            type: 'MULTIPLE_CHOICE',
            prompt: 'Vì sao server UDP phục vụ được nhiều client mà không cần luồng?',
            explanation:
              'UDP không có kết nối; mỗi gói tự mang địa chỉ người gửi, nên một socket xử lý được mọi người.',
            choices: [
              { text: 'Vì UDP không có kết nối, mỗi gói tự mang địa chỉ người gửi', isCorrect: true },
              { text: 'Vì UDP nhanh hơn nên kịp phục vụ tuần tự' },
              { text: 'Vì UDP tự tạo luồng bên trong' },
              { text: 'Thật ra UDP cũng cần luồng' },
            ],
          },
          {
            type: 'FILL_BLANK',
            prompt: 'Địa chỉ IP nào luôn trỏ về chính máy đang chạy?',
            explanation: '`127.0.0.1`, còn gọi là localhost hay loopback.',
            acceptedAnswers: ['127.0.0.1', 'localhost', 'loopback', '127001'],
            matchMode: 'normalised',
          },
          {
            type: 'SHORT_ANSWER',
            prompt:
              'Trong dự án chat của em, điều gì xảy ra nếu một client tắt máy đột ngột? ' +
              'Em đã xử lý thế nào để server không sập?',
            explanation:
              'Server sẽ gặp `ConnectionResetError` hoặc `OSError` khi gửi. Cách xử lý: bọc trong ' +
              '`try/except`, đánh dấu client hỏng và xoá khỏi danh sách trong khối `finally`.',
            points: 25,
          },
        ],
      }),
    ],
  },
];

export const advancedChuong2: ModuleSpec = {
  slug: 'lap-trinh-mang',
  title: 'Chương 2 · Lập trình mạng',
  description:
    'Từ khái niệm IP và cổng đến một phòng chat nhiều người tự viết. Toàn bộ chạy trên ' +
    'địa chỉ loopback 127.0.0.1, nên em học được socket thật mà môi trường vẫn an toàn tuyệt đối.',
  lessons: advancedLessons11to16,
};
