/**
 * Python Nâng Cao — Chương 1 (OOP), Buổi 6–10.
 *
 * Teacher note 14 — the lesson plan asks for real-world modelling and PEP8 to be
 * emphasised. B10 carries both: PEP8 conventions plus a Library/Shop modelling
 * project that closes the chapter.
 */
import type { LessonSpec } from '../types.ts';
import {
  challenge,
  example,
  playground,
  projectBlock,
  quizBlock,
  reflection,
  theory,
} from '../builders.ts';

export const advancedLessons6to10: LessonSpec[] = [
  {
    order: 6,
    slug: 'nc-b06-ke-thua-inheritance',
    title: 'Kế thừa (Inheritance) & `super()`',
    summary:
      'Đừng viết lại những gì đã có. Kế thừa cho phép một lớp mới nhận toàn bộ thuộc tính và ' +
      'phương thức của lớp cũ, rồi bổ sung phần riêng.',
    objectives: [
      'Tạo lớp con kế thừa từ lớp cha',
      'Dùng `super().__init__()` để gọi constructor lớp cha',
      'Bổ sung thuộc tính và phương thức riêng cho lớp con',
      'Dùng `isinstance()` và `issubclass()` để kiểm tra quan hệ',
    ],
    difficulty: 4,
    status: 'REQUIRED',
    teacherNotes: 'Nhấn mạnh quan hệ "là một" (is-a). Nếu không đọc được "X là một Y" thì đừng kế thừa.',
    blocks: [
      theory('Kế thừa — quan hệ "là một"', [
        '```python',
        'class Nguoi:                      # LOP CHA',
        '    def __init__(self, ho_ten, tuoi):',
        '        self.ho_ten = ho_ten',
        '        self.tuoi = tuoi',
        '',
        '    def gioi_thieu(self):',
        '        return f"Toi la {self.ho_ten}, {self.tuoi} tuoi"',
        '',
        '',
        'class HocSinh(Nguoi):             # LOP CON - ke thua Nguoi',
        '    def __init__(self, ho_ten, tuoi, lop):',
        '        super().__init__(ho_ten, tuoi)   # goi constructor lop cha',
        '        self.lop = lop                    # them thuoc tinh rieng',
        '',
        '    def hoc_bai(self):                    # them phuong thuc rieng',
        '        return f"{self.ho_ten} dang hoc bai"',
        '',
        '',
        'hs = HocSinh("Lan", 14, "7A1")',
        'print(hs.gioi_thieu())      # ke thua tu Nguoi',
        'print(hs.hoc_bai())         # cua rieng HocSinh',
        '```',
        '',
        '**Quy tắc vàng — phép thử "là một":** chỉ kế thừa khi câu *"X **là một** Y"* nghe hợp lý.',
        '',
        '| Câu | Hợp lý? | Kết luận |',
        '|---|---|---|',
        '| Học sinh **là một** Người | ✅ | Nên kế thừa |',
        '| Chó **là một** Động vật | ✅ | Nên kế thừa |',
        '| Xe hơi **là một** Động cơ | ❌ | Xe **có** động cơ → dùng thuộc tính |',
        '| Lớp học **là một** Học sinh | ❌ | Lớp **chứa** học sinh → dùng danh sách |',
        '',
        'Nhầm giữa **"là một"** (kế thừa) và **"có một"** (thuộc tính) là sai lầm thiết kế phổ biến nhất.',
      ], [
        '`class Con(Cha):` để kế thừa',
        'Phép thử: "X là một Y" nghe có hợp lý không?',
        '"Có một" thì dùng thuộc tính, không dùng kế thừa',
      ]),
      theory('`super()` và ghi đè phương thức', [
        '`super()` trỏ tới **lớp cha**. Dùng nhiều nhất trong `__init__`:',
        '',
        '```python',
        'def __init__(self, ho_ten, tuoi, lop):',
        '    super().__init__(ho_ten, tuoi)    # cha lo phan cua cha',
        '    self.lop = lop                     # con lo phan cua con',
        '```',
        '',
        '⚠️ **Quên gọi `super().__init__()`** là lỗi rất hay gặp. Khi đó `self.ho_ten` không tồn tại, ' +
          'và lỗi chỉ nổ ra khi dùng tới nó — rất khó truy.',
        '',
        '**Ghi đè (override)** — lớp con định nghĩa lại phương thức của cha:',
        '',
        '```python',
        'class GiaoVien(Nguoi):',
        '    def __init__(self, ho_ten, tuoi, mon):',
        '        super().__init__(ho_ten, tuoi)',
        '        self.mon = mon',
        '',
        '    def gioi_thieu(self):             # GHI DE',
        '        goc = super().gioi_thieu()    # van dung duoc ban cua cha',
        '        return f"{goc}, day mon {self.mon}"',
        '```',
        '',
        'Gọi `super().gioi_thieu()` bên trong bản ghi đè cho phép em **mở rộng** thay vì **thay thế hoàn toàn**.',
        '',
        '**Kiểm tra quan hệ:**',
        '',
        '```python',
        'isinstance(hs, HocSinh)     # True',
        'isinstance(hs, Nguoi)       # True  - hoc sinh CUNG LA nguoi',
        'issubclass(HocSinh, Nguoi)  # True',
        'type(hs) is Nguoi           # False - kiem tra chinh xac, it dung',
        '```',
        '',
        'Luôn ưu tiên `isinstance()` hơn `type() is`, vì `isinstance` tôn trọng quan hệ kế thừa.',
      ], [
        '`super().__init__(...)` bắt buộc gọi trong `__init__` của lớp con',
        'Ghi đè = định nghĩa lại phương thức cùng tên',
        '`super().phuong_thuc()` để mở rộng thay vì thay thế',
        'Dùng `isinstance()` chứ đừng dùng `type() is`',
      ]),
      example('Cây kế thừa hoàn chỉnh', 'Một lớp cha, ba lớp con, mỗi lớp thêm phần riêng.', [
        'class Nguoi:',
        '    """Lop cha - phan chung cua moi nguoi trong truong."""',
        '',
        '    def __init__(self, ho_ten, tuoi):',
        '        self.ho_ten = ho_ten',
        '        self.tuoi = tuoi',
        '',
        '    def gioi_thieu(self):',
        '        return f"Toi la {self.ho_ten}, {self.tuoi} tuoi"',
        '',
        '    def vai_tro(self):',
        '        return "Nguoi"',
        '',
        '',
        'class HocSinh(Nguoi):',
        '    def __init__(self, ho_ten, tuoi, lop):',
        '        super().__init__(ho_ten, tuoi)',
        '        self.lop = lop',
        '        self.diem = []',
        '',
        '    def gioi_thieu(self):',
        '        return f"{super().gioi_thieu()}, hoc lop {self.lop}"',
        '',
        '    def vai_tro(self):',
        '        return "Hoc sinh"',
        '',
        '    def them_diem(self, d):',
        '        self.diem.append(d)',
        '',
        '    def trung_binh(self):',
        '        return sum(self.diem) / len(self.diem) if self.diem else 0.0',
        '',
        '',
        'class GiaoVien(Nguoi):',
        '    def __init__(self, ho_ten, tuoi, mon, so_nam=0):',
        '        super().__init__(ho_ten, tuoi)',
        '        self.mon = mon',
        '        self.so_nam = so_nam',
        '',
        '    def gioi_thieu(self):',
        '        return f"{super().gioi_thieu()}, day {self.mon} duoc {self.so_nam} nam"',
        '',
        '    def vai_tro(self):',
        '        return "Giao vien"',
        '',
        '',
        'class HieuTruong(GiaoVien):        # ke thua NHIEU TANG',
        '    def __init__(self, ho_ten, tuoi, mon, so_nam, truong):',
        '        super().__init__(ho_ten, tuoi, mon, so_nam)',
        '        self.truong = truong',
        '',
        '    def vai_tro(self):',
        '        return "Hieu truong"',
        '',
        '    def gioi_thieu(self):',
        '        return f"{super().gioi_thieu()}, quan ly {self.truong}"',
        '',
        '',
        'moi_nguoi = [',
        '    HocSinh("Lan", 14, "7A1"),',
        '    GiaoVien("Thay Nam", 35, "Toan", 10),',
        '    HieuTruong("Co Hoa", 48, "Van", 22, "THCS Da Lat"),',
        ']',
        '',
        'for ng in moi_nguoi:',
        '    print(f"[{ng.vai_tro():<12}] {ng.gioi_thieu()}")',
        '',
        'print()',
        'ht = moi_nguoi[2]',
        'print(f"HieuTruong la GiaoVien? {isinstance(ht, GiaoVien)}")',
        'print(f"HieuTruong la Nguoi?    {isinstance(ht, Nguoi)}")',
        'print(f"HieuTruong la HocSinh?  {isinstance(ht, HocSinh)}")',
      ], {
        output: [
          '[Hoc sinh   ] Toi la Lan, 14 tuoi, hoc lop 7A1',
          '[Giao vien  ] Toi la Thay Nam, 35 tuoi, day Toan duoc 10 nam',
          '[Hieu truong] Toi la Co Hoa, 48 tuoi, day Van duoc 22 nam, quan ly THCS Da Lat',
          '',
          'HieuTruong la GiaoVien? True',
          'HieuTruong la Nguoi?    True',
          'HieuTruong la HocSinh?  False',
        ].join('\n'),
        notes: [
          '`HieuTruong` kế thừa qua ba tầng. Câu giới thiệu của nó ghép cả ba tầng lại nhờ chuỗi `super()`.',
          'Vòng lặp cuối gọi `ng.vai_tro()` mà không cần biết đối tượng thuộc lớp nào — đó là đa hình, học ở buổi 8.',
          '`isinstance(ht, Nguoi)` là True dù `HieuTruong` cách `Nguoi` hai tầng.',
        ],
      }),
      playground('Sân chơi: cây kế thừa của em', [
        'Xây một cây kế thừa 3 tầng cho chủ đề em thích:',
        '',
        '- `DongVat` → `Cho`, `Meo`, `Chim`',
        '- `PhuongTien` → `XeMay`, `OTo` → `XeTai`',
        '- `NhanVat` → `ChienBinh`, `PhapSu`',
        '',
        'Mỗi lớp con phải: gọi `super().__init__()`, thêm ít nhất một thuộc tính riêng, ' +
          'và ghi đè ít nhất một phương thức.',
      ], [
        'class DongVat:',
        '    def __init__(self, ten, tuoi):',
        '        self.ten = ten',
        '        self.tuoi = tuoi',
        '',
        '    def keu(self):',
        '        return "..."',
        '',
        '    def mo_ta(self):',
        '        return f"{self.ten} ({self.tuoi} tuoi) keu: {self.keu()}"',
        '',
        '',
        'class Cho(DongVat):',
        '    def __init__(self, ten, tuoi, giong):',
        '        super().__init__(ten, tuoi)',
        '        self.giong = giong',
        '',
        '    def keu(self):',
        '        return "Gau gau!"',
        '',
        '',
        '# Them lop Meo va Chim',
        '',
        'thu = [Cho("Milu", 3, "Corgi")]',
        'for t in thu:',
        '    print(t.mo_ta())',
      ], 'Cây kế thừa có ít nhất ba lớp, mỗi lớp con ghi đè phương thức và gọi `super()`.'),
      challenge({
        slug: 'p-nc-b06-ke-thua-hinh-hoc',
        title: 'Kế thừa hình học',
        statement: [
          'Viết ba lớp:',
          '',
          '**`Hinh`** (lớp cha)',
          '- `__init__(self, ten)` → gán `self.ten`',
          '- `dien_tich(self)` → trả về `0`',
          '- `mo_ta(self)` → trả về `f"{ten} co dien tich {dien_tich():.2f}"`',
          '',
          '**`HinhTron(Hinh)`**',
          '- `__init__(self, ban_kinh)` → gọi `super().__init__("Hinh tron")`, gán `self.ban_kinh`',
          '- `dien_tich(self)` → `3.14159 * ban_kinh ** 2`',
          '',
          '**`HinhChuNhat(Hinh)`**',
          '- `__init__(self, dai, rong)` → gọi `super().__init__("Hinh chu nhat")`, gán `dai`, `rong`',
          '- `dien_tich(self)` → `dai * rong`',
          '- `la_hinh_vuong(self)` → `True` nếu `dai == rong`',
          '',
          'Dùng đúng hằng số `3.14159` (không dùng `math.pi`) để kết quả khớp với bộ test.',
        ].join('\n'),
        hints: [
          '`mo_ta` chỉ viết **một lần** ở lớp cha — nó tự gọi `self.dien_tich()` của lớp con.',
          'Lớp con truyền tên cố định vào `super().__init__()`, không nhận tên từ ngoài.',
          'Định dạng hai chữ số thập phân bằng `{...:.2f}`.',
        ],
        starterCode: [
          'class Hinh:',
          '    def __init__(self, ten):',
          '        pass',
          '',
          '    def dien_tich(self):',
          '        return 0',
          '',
          '    def mo_ta(self):',
          '        pass',
          '',
          '',
          'class HinhTron(Hinh):',
          '    pass',
          '',
          '',
          'class HinhChuNhat(Hinh):',
          '    pass',
        ].join('\n'),
        solutionCode: [
          'class Hinh:',
          '    def __init__(self, ten):',
          '        self.ten = ten',
          '',
          '    def dien_tich(self):',
          '        return 0',
          '',
          '    def mo_ta(self):',
          '        return f"{self.ten} co dien tich {self.dien_tich():.2f}"',
          '',
          '',
          'class HinhTron(Hinh):',
          '    def __init__(self, ban_kinh):',
          '        super().__init__("Hinh tron")',
          '        self.ban_kinh = ban_kinh',
          '',
          '    def dien_tich(self):',
          '        return 3.14159 * self.ban_kinh ** 2',
          '',
          '',
          'class HinhChuNhat(Hinh):',
          '    def __init__(self, dai, rong):',
          '        super().__init__("Hinh chu nhat")',
          '        self.dai = dai',
          '        self.rong = rong',
          '',
          '    def dien_tich(self):',
          '        return self.dai * self.rong',
          '',
          '    def la_hinh_vuong(self):',
          '        return self.dai == self.rong',
        ].join('\n'),
        tier: 'CO_BAN',
        judgeMode: 'UNIT_TEST',
        runtimeImage: 'PY_TEST',
        unitTestCode: [
          'from solution import Hinh, HinhChuNhat, HinhTron',
          '',
          '',
          'def test_quan_he_ke_thua():',
          '    assert issubclass(HinhTron, Hinh)',
          '    assert issubclass(HinhChuNhat, Hinh)',
          '',
          '',
          'def test_hinh_co_ban():',
          '    h = Hinh("Hinh")',
          '    assert h.ten == "Hinh"',
          '    assert h.dien_tich() == 0',
          '',
          '',
          'def test_hinh_tron():',
          '    t = HinhTron(2)',
          '    assert t.ten == "Hinh tron"',
          '    assert t.ban_kinh == 2',
          '    assert abs(t.dien_tich() - 12.56636) < 1e-6',
          '',
          '',
          'def test_hinh_chu_nhat():',
          '    r = HinhChuNhat(5, 3)',
          '    assert r.ten == "Hinh chu nhat"',
          '    assert r.dien_tich() == 15',
          '',
          '',
          'def test_la_hinh_vuong():',
          '    assert HinhChuNhat(4, 4).la_hinh_vuong() is True',
          '    assert HinhChuNhat(4, 5).la_hinh_vuong() is False',
          '',
          '',
          'def test_mo_ta_dung_dien_tich_cua_lop_con():',
          '    """mo_ta chi viet o lop cha nhung phai goi dien_tich cua lop con."""',
          '    assert HinhChuNhat(5, 3).mo_ta() == "Hinh chu nhat co dien tich 15.00"',
          '    assert HinhTron(1).mo_ta() == "Hinh tron co dien tich 3.14"',
          '',
          '',
          'def test_isinstance():',
          '    assert isinstance(HinhTron(1), Hinh)',
          '    assert isinstance(HinhChuNhat(1, 1), Hinh)',
        ].join('\n'),
        totalPoints: 100,
      }),
    ],
  },

  {
    order: 7,
    slug: 'nc-b07-da-ke-thua-va-mro',
    title: 'Đa kế thừa & thứ tự phân giải MRO',
    summary:
      'Một lớp có thể kế thừa nhiều lớp cha. Mạnh, nhưng dễ rối — buổi này học cả cách dùng ' +
      'lẫn cách tránh lạm dụng.',
    objectives: [
      'Viết lớp kế thừa từ nhiều lớp cha',
      'Đọc được thứ tự phân giải phương thức (MRO)',
      'Nhận diện vấn đề kim cương trong đa kế thừa',
      'Dùng mixin như một cách đa kế thừa an toàn',
    ],
    difficulty: 5,
    status: 'ADVANCED',
    isDerived: true,
    teacherNotes:
      'Buổi mở rộng (⟨derived⟩) cho học sinh học nhanh. Học sinh bỏ qua buổi này vẫn theo được ' +
      'phần còn lại của chương.',
    blocks: [
      theory('Đa kế thừa và MRO', [
        '```python',
        'class BietBoi:',
        '    def boi(self):',
        '        return "Dang boi"',
        '',
        '',
        'class BietBay:',
        '    def bay(self):',
        '        return "Dang bay"',
        '',
        '',
        'class Vit(BietBoi, BietBay):      # ke thua CA HAI',
        '    def keu(self):',
        '        return "Quac quac"',
        '',
        '',
        'v = Vit()',
        'print(v.boi(), v.bay(), v.keu())',
        '```',
        '',
        '**MRO (Method Resolution Order)** là thứ tự Python đi tìm phương thức. Xem bằng:',
        '',
        '```python',
        'print(Vit.__mro__)',
        '# (Vit, BietBoi, BietBay, object)',
        '```',
        '',
        'Python tìm từ trái sang phải: `Vit` trước, rồi `BietBoi`, rồi `BietBay`, cuối cùng `object`. ' +
          'Tìm thấy ở đâu thì dừng ở đó.',
        '',
        '**Vấn đề kim cương** — khi hai lớp cha cùng có một phương thức:',
        '',
        '```',
        '        A',
        '       / \\',
        '      B   C        B va C deu co phuong thuc chao()',
        '       \\ /',
        '        D          D goi chao() -> cua ai?',
        '```',
        '',
        '```python',
        'class D(B, C): pass',
        'd = D()',
        'd.chao()      # goi cua B, vi B dung TRUOC C trong danh sach',
        '```',
        '',
        'Thứ tự khai báo quyết định. Đổi thành `class D(C, B)` là kết quả đổi theo — ' +
          'đó chính là lý do đa kế thừa dễ gây bất ngờ.',
      ], [
        '`class Con(Cha1, Cha2)` cho đa kế thừa',
        'MRO: tìm từ trái sang phải, thấy đầu tiên thì dùng',
        'Thứ tự khai báo lớp cha quyết định phương thức nào được gọi',
      ]),
      theory('Mixin — cách đa kế thừa an toàn', [
        '**Mixin** là một lớp nhỏ chỉ cung cấp **một** khả năng, không dùng độc lập, và không có ' +
          'trạng thái riêng.',
        '',
        '```python',
        'class MixinSoSanh:',
        '    """Chi cung cap kha nang so sanh. Khong dung mot minh."""',
        '',
        '    def __lt__(self, khac):',
        '        return self.gia_tri_so_sanh() < khac.gia_tri_so_sanh()',
        '',
        '    def __eq__(self, khac):',
        '        return self.gia_tri_so_sanh() == khac.gia_tri_so_sanh()',
        '',
        '',
        'class MixinJson:',
        '    """Chi cung cap kha nang xuat JSON."""',
        '',
        '    def to_json(self):',
        '        import json',
        '        return json.dumps(vars(self), ensure_ascii=False)',
        '',
        '',
        'class SanPham(MixinSoSanh, MixinJson):',
        '    def __init__(self, ten, gia):',
        '        self.ten = ten',
        '        self.gia = gia',
        '',
        '    def gia_tri_so_sanh(self):',
        '        return self.gia',
        '```',
        '',
        'Giờ `SanPham` **sắp xếp được** và **xuất JSON được**, mà mỗi khả năng vẫn nằm gọn trong ' +
          'một lớp riêng, dễ đọc và dễ tái sử dụng.',
        '',
        '**Ba quy tắc dùng đa kế thừa an toàn:**',
        '',
        '1. Ưu tiên **mixin** hơn đa kế thừa hai lớp "đầy đủ"',
        '2. Đặt tên mixin có tiền tố rõ ràng: `MixinSoSanh`, `MixinJson`',
        '3. Mixin **không nên có `__init__`** — tránh xung đột constructor',
        '',
        '📌 Trong đa số trường hợp, **kế thừa đơn cộng với thuộc tính** đủ dùng và dễ hiểu hơn. ' +
          'Đa kế thừa là công cụ dành cho tình huống đặc thù.',
      ], [
        'Mixin = lớp nhỏ cung cấp một khả năng, không dùng độc lập',
        'Đặt tên mixin rõ ràng, không cho mixin có `__init__`',
        'Ưu tiên kế thừa đơn — đa kế thừa chỉ dùng khi thật cần',
      ]),
      example('MRO và mixin trong thực tế', 'Chạy để thấy MRO quyết định mọi thứ như thế nào.', [
        'class A:',
        '    def chao(self):',
        '        return "Chao tu A"',
        '',
        '',
        'class B(A):',
        '    def chao(self):',
        '        return "Chao tu B"',
        '',
        '',
        'class C(A):',
        '    def chao(self):',
        '        return "Chao tu C"',
        '',
        '',
        'class D(B, C):',
        '    pass',
        '',
        '',
        'class E(C, B):',
        '    pass',
        '',
        '',
        'print("=== Van de kim cuong ===")',
        'print(f"D(B, C).chao() -> {D().chao()}")',
        'print(f"E(C, B).chao() -> {E().chao()}")',
        'print()',
        'print("MRO cua D:", " -> ".join(c.__name__ for c in D.__mro__))',
        'print("MRO cua E:", " -> ".join(c.__name__ for c in E.__mro__))',
        '',
        'print()',
        'print("=== Mixin ===")',
        '',
        '',
        'class MixinSoSanh:',
        '    def __lt__(self, khac):',
        '        return self.gia_tri_so_sanh() < khac.gia_tri_so_sanh()',
        '',
        '    def __eq__(self, khac):',
        '        return self.gia_tri_so_sanh() == khac.gia_tri_so_sanh()',
        '',
        '',
        'class MixinMoTa:',
        '    def mo_ta(self):',
        '        cap = ", ".join(f"{k}={v}" for k, v in vars(self).items())',
        '        return f"{type(self).__name__}({cap})"',
        '',
        '',
        'class SanPham(MixinSoSanh, MixinMoTa):',
        '    def __init__(self, ten, gia):',
        '        self.ten = ten',
        '        self.gia = gia',
        '',
        '    def gia_tri_so_sanh(self):',
        '        return self.gia',
        '',
        '',
        'kho = [SanPham("But", 5000), SanPham("Vo", 12000), SanPham("Thuoc", 3000)]',
        '',
        'for sp in sorted(kho):',
        '    print(" ", sp.mo_ta())',
        '',
        'print()',
        'print("But == But khac gia? ", SanPham("But", 5000) == SanPham("But bi", 5000))',
      ], {
        output: [
          '=== Van de kim cuong ===',
          'D(B, C).chao() -> Chao tu B',
          'E(C, B).chao() -> Chao tu C',
          '',
          'MRO cua D: D -> B -> C -> A -> object',
          'MRO cua E: E -> C -> B -> A -> object',
          '',
          '=== Mixin ===',
          '  SanPham(ten=Thuoc, gia=3000)',
          '  SanPham(ten=But, gia=5000)',
          '  SanPham(ten=Vo, gia=12000)',
          '',
          'But == But khac gia?  True',
        ].join('\n'),
        notes: [
          '`D` và `E` chỉ khác thứ tự khai báo lớp cha, mà kết quả `chao()` đã khác nhau.',
          '`sorted(kho)` hoạt động được chỉ nhờ mixin cung cấp `__lt__` — `SanPham` không viết dòng nào về sắp xếp.',
          'Dòng cuối cho thấy `__eq__` của mixin so sánh theo giá, nên hai sản phẩm khác tên nhưng cùng giá là "bằng nhau". ' +
            'Đó là hệ quả của thiết kế, cần cân nhắc kỹ.',
        ],
      }),
      playground('Sân chơi: mixin của em', [
        'Viết hai mixin rồi ghép vào một lớp:',
        '',
        '- `MixinDemSo` — đếm số đối tượng đã tạo (dùng thuộc tính của lớp)',
        '- `MixinInDep` — phương thức `in_dep()` in thuộc tính theo bảng',
        '',
        'Sau đó in `__mro__` của lớp kết quả và giải thích thứ tự.',
      ], [
        'class MixinInDep:',
        '    def in_dep(self):',
        '        print(f"--- {type(self).__name__} ---")',
        '        for k, v in vars(self).items():',
        '            print(f"  {k:<12}: {v}")',
        '',
        '',
        '# Them MixinDemSo o day',
        '',
        '',
        'class NhanVien(MixinInDep):',
        '    def __init__(self, ten, luong):',
        '        self.ten = ten',
        '        self.luong = luong',
        '',
        '',
        'nv = NhanVien("Lan", 12000000)',
        'nv.in_dep()',
        'print(" -> ".join(c.__name__ for c in NhanVien.__mro__))',
      ], 'Hai mixin hoạt động và giải thích được thứ tự MRO in ra.'),
      quizBlock({
        slug: 'q-nc-b07-mro',
        title: 'Kiểm tra nhanh: đa kế thừa & MRO',
        questions: [
          {
            type: 'MULTIPLE_CHOICE',
            prompt:
              'Với `class D(B, C)` mà cả `B` và `C` đều có phương thức `chao()`, Python gọi bản nào?',
            explanation: 'MRO đi từ trái sang phải, nên `B` được tìm thấy trước.',
            choices: [
              { text: 'Bản của B', isCorrect: true },
              { text: 'Bản của C' },
              { text: 'Gọi cả hai' },
              { text: 'Báo lỗi vì không rõ ràng' },
            ],
          },
          {
            type: 'MULTIPLE_CHOICE',
            prompt: 'Đặc điểm nào KHÔNG phải của một mixin tốt?',
            explanation:
              'Mixin không nên có `__init__` riêng để tránh xung đột constructor khi ghép nhiều mixin.',
            choices: [
              { text: 'Có `__init__` riêng với nhiều tham số', isCorrect: true },
              { text: 'Chỉ cung cấp một khả năng' },
              { text: 'Không dùng độc lập' },
              { text: 'Tên có tiền tố rõ ràng' },
            ],
          },
          {
            type: 'FILL_BLANK',
            prompt: 'Thuộc tính nào của lớp cho biết thứ tự phân giải phương thức?',
            explanation: '`__mro__`, hoặc gọi phương thức `mro()`.',
            acceptedAnswers: ['__mro__', 'mro', 'mro()', '__mro__ '],
            matchMode: 'normalised',
          },
        ],
      }),
    ],
  },

  {
    order: 8,
    slug: 'nc-b08-da-hinh-polymorphism',
    title: 'Đa hình (Polymorphism) & method overriding',
    summary:
      'Cùng một lời gọi, nhiều cách phản ứng. Đa hình là thứ khiến code OOP gọn và dễ mở rộng ' +
      'hơn hẳn chuỗi `if/elif` dài dằng dặc.',
    objectives: [
      'Giải thích được đa hình qua ví dụ cụ thể',
      'Ghi đè phương thức để mỗi lớp con phản ứng theo cách riêng',
      'Dùng duck typing của Python',
      'Thay chuỗi `if/elif` kiểm tra kiểu bằng đa hình',
    ],
    difficulty: 4,
    status: 'REQUIRED',
    teacherNotes:
      'Bài học lớn nhất: đa hình giúp XOÁ BỎ chuỗi if/elif kiểm tra kiểu. Cho học sinh thấy ' +
      'cả hai cách cạnh nhau.',
    blocks: [
      theory('Đa hình — một lời gọi, nhiều phản ứng', [
        '**Không có đa hình** — code đầy `if/elif` và phải sửa mỗi khi thêm loại mới:',
        '',
        '```python',
        'def tinh_dien_tich(hinh):',
        '    if hinh["loai"] == "tron":',
        '        return 3.14159 * hinh["r"] ** 2',
        '    elif hinh["loai"] == "chu_nhat":',
        '        return hinh["dai"] * hinh["rong"]',
        '    elif hinh["loai"] == "tam_giac":',
        '        return hinh["day"] * hinh["cao"] / 2',
        '    # Them hinh moi -> phai SUA ham nay',
        '```',
        '',
        '**Có đa hình** — mỗi lớp tự biết cách tính của mình:',
        '',
        '```python',
        'for h in danh_sach_hinh:',
        '    print(h.dien_tich())     # moi hinh tu lo phan cua no',
        '```',
        '',
        'Thêm `HinhThang` mới? Chỉ cần viết lớp mới. **Không sửa một dòng nào** ở đoạn code trên.',
        '',
        'Đây là **nguyên tắc Mở–Đóng**: mở cho việc mở rộng, đóng với việc sửa đổi.',
        '',
        '| Tiêu chí | if/elif | Đa hình |',
        '|---|---|---|',
        '| Thêm loại mới | Sửa hàm cũ | Viết lớp mới |',
        '| Rủi ro làm hỏng code cũ | Cao | Gần như không |',
        '| Độ dài code khi có 10 loại | Rất dài | Không đổi |',
      ], [
        'Đa hình thay thế chuỗi if/elif kiểm tra kiểu',
        'Thêm loại mới = viết lớp mới, không sửa code cũ',
        'Nguyên tắc Mở–Đóng: mở để mở rộng, đóng với sửa đổi',
      ]),
      theory('Duck typing — kiểu Python', [
        '*"Nếu nó đi như vịt và kêu như vịt, thì nó là vịt."*',
        '',
        'Python **không bắt buộc** các lớp phải có chung lớp cha để dùng đa hình. Chỉ cần chúng có ' +
          'cùng **tên phương thức**:',
        '',
        '```python',
        'class Cho:',
        '    def keu(self):',
        '        return "Gau gau"',
        '',
        '',
        'class Meo:',
        '    def keu(self):',
        '        return "Meo meo"',
        '',
        '',
        'class DienThoai:      # khong lien quan gi den dong vat!',
        '    def keu(self):',
        '        return "Reng reng"',
        '',
        '',
        'for thu in [Cho(), Meo(), DienThoai()]:',
        '    print(thu.keu())     # deu chay duoc',
        '```',
        '',
        'Ba lớp này không kế thừa từ đâu cả, nhưng vẫn dùng chung được. Đó là **duck typing**.',
        '',
        '**Ưu và nhược:**',
        '',
        '| Ưu | Nhược |',
        '|---|---|',
        '| Linh hoạt, không cần cây kế thừa | Chỉ phát hiện lỗi lúc chạy |',
        '| Code ngắn gọn | Không có gì bảo đảm lớp thật sự có phương thức đó |',
        '',
        'Muốn có bảo đảm, dùng lớp trừu tượng — nội dung của buổi 9.',
        '',
        '💡 Cách kiểm tra an toàn khi cần: `if hasattr(thu, "keu"):`',
      ], [
        'Duck typing: chỉ cần cùng tên phương thức, không cần cùng lớp cha',
        'Linh hoạt nhưng lỗi chỉ lộ ra lúc chạy',
        '`hasattr()` để kiểm tra trước khi gọi',
      ]),
      example('Hai cách viết cùng một bài toán', 'Đọc cả hai rồi tự đánh giá cách nào dễ mở rộng hơn.', [
        '# ============ CACH 1: if/elif (khong nen) ============',
        'def dien_tich_cu(hinh):',
        '    if hinh["loai"] == "tron":',
        '        return 3.14159 * hinh["r"] ** 2',
        '    elif hinh["loai"] == "chu_nhat":',
        '        return hinh["dai"] * hinh["rong"]',
        '    elif hinh["loai"] == "tam_giac":',
        '        return hinh["day"] * hinh["cao"] / 2',
        '    return 0',
        '',
        '',
        'hinh_cu = [',
        '    {"loai": "tron", "r": 2},',
        '    {"loai": "chu_nhat", "dai": 5, "rong": 3},',
        '    {"loai": "tam_giac", "day": 6, "cao": 4},',
        ']',
        'print("Cach 1:", [round(dien_tich_cu(h), 2) for h in hinh_cu])',
        '',
        '',
        '# ============ CACH 2: da hinh (nen dung) ============',
        'class Hinh:',
        '    def dien_tich(self):',
        '        return 0',
        '',
        '    def ten(self):',
        '        return type(self).__name__',
        '',
        '    def mo_ta(self):',
        '        return f"{self.ten():<14} S = {self.dien_tich():8.2f}"',
        '',
        '',
        'class HinhTron(Hinh):',
        '    def __init__(self, r):',
        '        self.r = r',
        '',
        '    def dien_tich(self):',
        '        return 3.14159 * self.r ** 2',
        '',
        '',
        'class HinhChuNhat(Hinh):',
        '    def __init__(self, dai, rong):',
        '        self.dai = dai',
        '        self.rong = rong',
        '',
        '    def dien_tich(self):',
        '        return self.dai * self.rong',
        '',
        '',
        'class TamGiac(Hinh):',
        '    def __init__(self, day, cao):',
        '        self.day = day',
        '        self.cao = cao',
        '',
        '    def dien_tich(self):',
        '        return self.day * self.cao / 2',
        '',
        '',
        '# ==> THEM HINH MOI: khong sua mot dong nao o duoi',
        'class HinhThang(Hinh):',
        '    def __init__(self, day_lon, day_nho, cao):',
        '        self.day_lon = day_lon',
        '        self.day_nho = day_nho',
        '        self.cao = cao',
        '',
        '    def dien_tich(self):',
        '        return (self.day_lon + self.day_nho) * self.cao / 2',
        '',
        '',
        'danh_sach = [HinhTron(2), HinhChuNhat(5, 3), TamGiac(6, 4), HinhThang(8, 4, 5)]',
        '',
        'print()',
        'print("Cach 2:")',
        'for h in danh_sach:',
        '    print(" ", h.mo_ta())',
        '',
        'print()',
        'print(f"  Tong dien tich: {sum(h.dien_tich() for h in danh_sach):.2f}")',
        'print(f"  Lon nhat      : {max(danh_sach, key=lambda h: h.dien_tich()).ten()}")',
      ], {
        output: [
          'Cach 1: [12.57, 15, 12.0]',
          '',
          'Cach 2:',
          '  HinhTron       S =    12.57',
          '  HinhChuNhat    S =    15.00',
          '  TamGiac        S =    12.00',
          '  HinhThang      S =    30.00',
          '',
          '  Tong dien tich: 69.57',
          '  Lon nhat      : HinhThang',
        ].join('\n'),
        notes: [
          '`HinhThang` được thêm vào mà `mo_ta()`, `sum()` và `max()` đều hoạt động ngay — không sửa gì cả.',
          'Với cách 1, thêm hình thang phải sửa hàm `dien_tich_cu` — nguy cơ làm hỏng phần đang chạy tốt.',
          '`type(self).__name__` lấy tên lớp thật của đối tượng, nên `ten()` chỉ cần viết một lần ở lớp cha.',
        ],
      }),
      playground('Sân chơi: xoá bỏ if/elif', [
        'Đoạn code dưới đây dùng `if/elif` để tính lương theo loại nhân viên.',
        '',
        'Hãy viết lại bằng đa hình: một lớp cha `NhanVien` và ba lớp con.',
        '',
        'Sau đó thêm loại thứ tư (`ThucTapSinh`) và kiểm chứng rằng em **không phải sửa** phần in kết quả.',
      ], [
        '# ==== CACH CU: sua lai bang da hinh ====',
        'def tinh_luong(nv):',
        '    if nv["loai"] == "toan_thoi_gian":',
        '        return nv["luong_thang"]',
        '    elif nv["loai"] == "theo_gio":',
        '        return nv["so_gio"] * nv["gia_gio"]',
        '    elif nv["loai"] == "kinh_doanh":',
        '        return nv["luong_co_ban"] + nv["doanh_so"] * 0.05',
        '    return 0',
        '',
        '',
        'nhan_vien = [',
        '    {"loai": "toan_thoi_gian", "ten": "A", "luong_thang": 15000000},',
        '    {"loai": "theo_gio", "ten": "B", "so_gio": 120, "gia_gio": 80000},',
        '    {"loai": "kinh_doanh", "ten": "C", "luong_co_ban": 8000000, "doanh_so": 200000000},',
        ']',
        '',
        'for nv in nhan_vien:',
        '    print(f"{nv[\'ten\']}: {tinh_luong(nv):,.0f} d")',
        '',
        '',
        '# ==== VIET LAI BANG DA HINH O DAY ====',
      ], 'Viết lại bằng đa hình và thêm được loại nhân viên thứ tư mà không sửa vòng lặp in.'),
      challenge({
        slug: 'p-nc-b08-da-hinh-dong-vat',
        title: 'Đa hình với động vật',
        statement: [
          'Viết một lớp cha và ba lớp con:',
          '',
          '**`DongVat`**',
          '- `__init__(self, ten)` → gán `self.ten`',
          '- `keu(self)` → trả về `"..."`',
          '- `di_chuyen(self)` → trả về `"di chuyen"`',
          '- `gioi_thieu(self)` → trả về `f"{ten} keu {keu()} va {di_chuyen()}"`',
          '',
          '**`Cho(DongVat)`** — `keu()` → `"Gau gau"`, `di_chuyen()` → `"chay"`',
          '',
          '**`Chim(DongVat)`** — `keu()` → `"Chiep chiep"`, `di_chuyen()` → `"bay"`',
          '',
          '**`Ca(DongVat)`** — `keu()` → `"..."` (không ghi đè), `di_chuyen()` → `"boi"`',
          '',
          'Ngoài ra viết **hàm** `tat_ca_gioi_thieu(danh_sach)` nhận một danh sách động vật và ' +
            'trả về **danh sách các chuỗi** giới thiệu của từng con.',
          '',
          '`gioi_thieu` chỉ được viết **một lần** ở lớp cha.',
        ].join('\n'),
        hints: [
          '`Ca` không cần viết lại `keu()` — nó dùng bản kế thừa từ `DongVat`.',
          '`gioi_thieu` gọi `self.keu()` và `self.di_chuyen()`, nên tự lấy đúng bản của lớp con.',
          '`tat_ca_gioi_thieu` viết gọn bằng list comprehension.',
        ],
        starterCode: [
          'class DongVat:',
          '    def __init__(self, ten):',
          '        self.ten = ten',
          '',
          '    def keu(self):',
          '        return "..."',
          '',
          '    def di_chuyen(self):',
          '        return "di chuyen"',
          '',
          '    def gioi_thieu(self):',
          '        pass',
          '',
          '',
          'class Cho(DongVat):',
          '    pass',
          '',
          '',
          'class Chim(DongVat):',
          '    pass',
          '',
          '',
          'class Ca(DongVat):',
          '    pass',
          '',
          '',
          'def tat_ca_gioi_thieu(danh_sach):',
          '    pass',
        ].join('\n'),
        solutionCode: [
          'class DongVat:',
          '    def __init__(self, ten):',
          '        self.ten = ten',
          '',
          '    def keu(self):',
          '        return "..."',
          '',
          '    def di_chuyen(self):',
          '        return "di chuyen"',
          '',
          '    def gioi_thieu(self):',
          '        return f"{self.ten} keu {self.keu()} va {self.di_chuyen()}"',
          '',
          '',
          'class Cho(DongVat):',
          '    def keu(self):',
          '        return "Gau gau"',
          '',
          '    def di_chuyen(self):',
          '        return "chay"',
          '',
          '',
          'class Chim(DongVat):',
          '    def keu(self):',
          '        return "Chiep chiep"',
          '',
          '    def di_chuyen(self):',
          '        return "bay"',
          '',
          '',
          'class Ca(DongVat):',
          '    def di_chuyen(self):',
          '        return "boi"',
          '',
          '',
          'def tat_ca_gioi_thieu(danh_sach):',
          '    return [dv.gioi_thieu() for dv in danh_sach]',
        ].join('\n'),
        tier: 'CO_BAN',
        judgeMode: 'UNIT_TEST',
        runtimeImage: 'PY_TEST',
        unitTestCode: [
          'from solution import Ca, Chim, Cho, DongVat, tat_ca_gioi_thieu',
          '',
          '',
          'def test_ke_thua():',
          '    for lop in (Cho, Chim, Ca):',
          '        assert issubclass(lop, DongVat)',
          '',
          '',
          'def test_lop_cha():',
          '    dv = DongVat("X")',
          '    assert dv.keu() == "..."',
          '    assert dv.di_chuyen() == "di chuyen"',
          '',
          '',
          'def test_cho():',
          '    c = Cho("Milu")',
          '    assert c.keu() == "Gau gau"',
          '    assert c.di_chuyen() == "chay"',
          '',
          '',
          'def test_chim():',
          '    c = Chim("Vet")',
          '    assert c.keu() == "Chiep chiep"',
          '    assert c.di_chuyen() == "bay"',
          '',
          '',
          'def test_ca_ke_thua_keu():',
          '    """Ca khong ghi de keu() nen phai dung ban cua lop cha."""',
          '    c = Ca("Vang")',
          '    assert c.keu() == "..."',
          '    assert c.di_chuyen() == "boi"',
          '',
          '',
          'def test_gioi_thieu_da_hinh():',
          '    assert Cho("Milu").gioi_thieu() == "Milu keu Gau gau va chay"',
          '    assert Chim("Vet").gioi_thieu() == "Vet keu Chiep chiep va bay"',
          '    assert Ca("Vang").gioi_thieu() == "Vang keu ... va boi"',
          '',
          '',
          'def test_gioi_thieu_chi_viet_o_lop_cha():',
          '    """Lop con khong duoc dinh nghia lai gioi_thieu."""',
          '    for lop in (Cho, Chim, Ca):',
          '        assert "gioi_thieu" not in lop.__dict__',
          '',
          '',
          'def test_tat_ca_gioi_thieu():',
          '    ds = [Cho("A"), Chim("B"), Ca("C")]',
          '    ket_qua = tat_ca_gioi_thieu(ds)',
          '    assert isinstance(ket_qua, list)',
          '    assert len(ket_qua) == 3',
          '    assert ket_qua[0] == "A keu Gau gau va chay"',
          '    assert ket_qua[2] == "C keu ... va boi"',
          '',
          '',
          'def test_danh_sach_rong():',
          '    assert tat_ca_gioi_thieu([]) == []',
        ].join('\n'),
        totalPoints: 100,
      }),
    ],
  },

  {
    order: 9,
    slug: 'nc-b09-truu-tuong-abstraction-abc',
    title: 'Trừu tượng (Abstraction) với `ABC`',
    summary:
      'Lớp trừu tượng là một bản hợp đồng: nó nói rõ lớp con **bắt buộc** phải làm gì, và Python ' +
      'sẽ cưỡng chế điều đó.',
    objectives: [
      'Giải thích được vai trò của lớp trừu tượng',
      'Dùng `ABC` và `@abstractmethod`',
      'Hiểu vì sao không thể tạo đối tượng từ lớp trừu tượng',
      'Kết hợp phương thức trừu tượng với phương thức có sẵn',
    ],
    difficulty: 5,
    status: 'REQUIRED',
    teacherNotes:
      'Ý chính: lớp trừu tượng biến lỗi lúc chạy thành lỗi lúc tạo đối tượng. Đó là tiến bộ lớn.',
    blocks: [
      theory('Vấn đề mà lớp trừu tượng giải quyết', [
        'Ở buổi 8, `Hinh.dien_tich()` trả về `0`. Nếu ai đó viết lớp con mà **quên** ghi đè:',
        '',
        '```python',
        'class NguHocGiac(Hinh):',
        '    def __init__(self, canh):',
        '        self.canh = canh',
        '    # QUEN viet dien_tich()',
        '',
        '',
        'h = NguHocGiac(5)',
        'print(h.dien_tich())     # 0 - KHONG bao loi, chi tra ve ket qua SAI',
        '```',
        '',
        'Đây là loại lỗi tệ nhất: **sai âm thầm**. Chương trình vẫn chạy, chỉ là kết quả sai.',
        '',
        '**Lớp trừu tượng** biến lỗi đó thành lỗi ngay lúc tạo đối tượng:',
        '',
        '```python',
        'from abc import ABC, abstractmethod',
        '',
        '',
        'class Hinh(ABC):',
        '    @abstractmethod',
        '    def dien_tich(self):',
        '        """Moi lop con BAT BUOC phai viet phuong thuc nay."""',
        '',
        '    def mo_ta(self):          # phuong thuc thuong, dung chung',
        '        return f"{type(self).__name__}: S = {self.dien_tich():.2f}"',
        '',
        '',
        'class NguHocGiac(Hinh):',
        '    pass',
        '',
        '',
        'h = NguHocGiac()',
        '# TypeError: Can\'t instantiate abstract class NguHocGiac',
        '#            with abstract method dien_tich',
        '```',
        '',
        'Lỗi nổ ra **ngay dòng tạo đối tượng**, kèm thông báo nói rõ thiếu phương thức nào. ' +
          'Đó là khác biệt giữa một bug tìm cả ngày và một bug sửa trong 10 giây.',
      ], [
        '`from abc import ABC, abstractmethod`',
        'Lớp kế thừa `ABC` không tạo được đối tượng trực tiếp',
        '`@abstractmethod` buộc lớp con phải ghi đè',
        'Biến lỗi âm thầm thành lỗi ngay lúc tạo đối tượng',
      ]),
      theory('Trộn phương thức trừu tượng và phương thức thường', [
        'Lớp trừu tượng không nhất thiết chỉ chứa phương thức rỗng. Nó có thể vừa **bắt buộc** ' +
          'vừa **cung cấp sẵn**:',
        '',
        '```python',
        'class PhuongTien(ABC):',
        '    def __init__(self, ten, so_banh):',
        '        self.ten = ten',
        '        self.so_banh = so_banh',
        '',
        '    # ===== BAT BUOC lop con viet =====',
        '    @abstractmethod',
        '    def khoi_dong(self):',
        '        ...',
        '',
        '    @abstractmethod',
        '    def toc_do_toi_da(self):',
        '        ...',
        '',
        '    # ===== CO SAN, dung chung =====',
        '    def mo_ta(self):',
        '        return f"{self.ten} ({self.so_banh} banh), toi da {self.toc_do_toi_da()} km/h"',
        '',
        '    def la_xe_may(self):',
        '        return self.so_banh == 2',
        '```',
        '',
        'Đây là mô hình rất hay dùng: **phần chung viết một lần ở lớp cha, phần khác biệt bắt buộc ' +
          'lớp con tự lo.**',
        '',
        '| Khi nào dùng gì |',
        '|---|',
        '| Mọi lớp con làm **giống nhau** → phương thức thường ở lớp cha |',
        '| Mọi lớp con **phải có** nhưng làm **khác nhau** → `@abstractmethod` |',
        '| Chỉ **một số** lớp con cần → để lớp con tự thêm |',
        '',
        '💡 **`@property` cũng trừu tượng được:**',
        '',
        '```python',
        '@property',
        '@abstractmethod',
        'def gia_tri(self):',
        '    ...',
        '```',
      ], [
        'Lớp trừu tượng trộn được cả phương thức bắt buộc lẫn phương thức có sẵn',
        'Phần chung ở cha, phần khác biệt bắt buộc ở con',
        '`@property` kết hợp `@abstractmethod` được',
      ]),
      example('Hệ thống thanh toán trừu tượng', 'Một bản hợp đồng rõ ràng cho mọi phương thức thanh toán.', [
        'from abc import ABC, abstractmethod',
        '',
        '',
        'class PhuongThucThanhToan(ABC):',
        '    """Hop dong: moi phuong thuc thanh toan phai lam duoc 3 viec nay."""',
        '',
        '    def __init__(self, chu_the):',
        '        self.chu_the = chu_the',
        '        self.lich_su = []',
        '',
        '    @abstractmethod',
        '    def ten_phuong_thuc(self):',
        '        """Ten hien thi cho nguoi dung."""',
        '',
        '    @abstractmethod',
        '    def phi_giao_dich(self, so_tien):',
        '        """Phi tinh theo so tien."""',
        '',
        '    @abstractmethod',
        '    def kiem_tra_hop_le(self, so_tien):',
        '        """True neu giao dich thuc hien duoc."""',
        '',
        '    # ===== Phan CHUNG, viet mot lan =====',
        '    def thanh_toan(self, so_tien):',
        '        if so_tien <= 0:',
        '            return f"Loi: so tien phai duong"',
        '        if not self.kiem_tra_hop_le(so_tien):',
        '            return f"Loi: {self.ten_phuong_thuc()} khong thuc hien duoc {so_tien:,} d"',
        '',
        '        phi = self.phi_giao_dich(so_tien)',
        '        tong = so_tien + phi',
        '        self.lich_su.append(tong)',
        '        return (f"{self.ten_phuong_thuc():<14} {so_tien:>12,} d"',
        '                f" + phi {phi:>8,.0f} d = {tong:>12,.0f} d")',
        '',
        '',
        'class TienMat(PhuongThucThanhToan):',
        '    def ten_phuong_thuc(self):',
        '        return "Tien mat"',
        '',
        '    def phi_giao_dich(self, so_tien):',
        '        return 0',
        '',
        '    def kiem_tra_hop_le(self, so_tien):',
        '        return so_tien <= 20_000_000',
        '',
        '',
        'class TheNganHang(PhuongThucThanhToan):',
        '    def __init__(self, chu_the, han_muc):',
        '        super().__init__(chu_the)',
        '        self.han_muc = han_muc',
        '',
        '    def ten_phuong_thuc(self):',
        '        return "The ngan hang"',
        '',
        '    def phi_giao_dich(self, so_tien):',
        '        return so_tien * 0.011',
        '',
        '    def kiem_tra_hop_le(self, so_tien):',
        '        return so_tien <= self.han_muc',
        '',
        '',
        'class ViDienTu(PhuongThucThanhToan):',
        '    def __init__(self, chu_the, so_du):',
        '        super().__init__(chu_the)',
        '        self.so_du = so_du',
        '',
        '    def ten_phuong_thuc(self):',
        '        return "Vi dien tu"',
        '',
        '    def phi_giao_dich(self, so_tien):',
        '        return 2200',
        '',
        '    def kiem_tra_hop_le(self, so_tien):',
        '        return so_tien + 2200 <= self.so_du',
        '',
        '',
        'cac_cach = [',
        '    TienMat("Lan"),',
        '    TheNganHang("Minh", han_muc=50_000_000),',
        '    ViDienTu("Hoa", so_du=1_000_000),',
        ']',
        '',
        'for cach in cac_cach:',
        '    print(cach.thanh_toan(500_000))',
        '',
        'print()',
        'print(cac_cach[2].thanh_toan(2_000_000))    # vuot so du',
        '',
        'print()',
        'print("--- Thu tao lop thieu phuong thuc ---")',
        '',
        '',
        'class ThieuSot(PhuongThucThanhToan):',
        '    def ten_phuong_thuc(self):',
        '        return "Thieu sot"',
        '    # QUEN phi_giao_dich va kiem_tra_hop_le',
        '',
        '',
        'try:',
        '    ThieuSot("X")',
        'except TypeError as loi:',
        '    print(f"Bi chan ngay: {loi}")',
      ], {
        output: [
          'Tien mat            500,000 d + phi        0 d =      500,000 d',
          'The ngan hang       500,000 d + phi    5,500 d =      505,500 d',
          'Vi dien tu          500,000 d + phi    2,200 d =      502,200 d',
          '',
          'Loi: Vi dien tu khong thuc hien duoc 2,000,000 d',
          '',
          '--- Thu tao lop thieu phuong thuc ---',
          "Bi chan ngay: Can't instantiate abstract class ThieuSot without an implementation for abstract methods 'kiem_tra_hop_le', 'phi_giao_dich'",
        ].join('\n'),
        notes: [
          '`thanh_toan()` viết **một lần** ở lớp cha nhưng gọi ba phương thức trừu tượng — mỗi lớp con tự lo phần của mình.',
          'Thông báo lỗi cuối cùng liệt kê **chính xác** hai phương thức còn thiếu. Rất dễ sửa.',
          'Thêm phương thức thanh toán mới (ví dụ QR) chỉ cần viết một lớp con — `thanh_toan()` không đổi.',
        ],
      }),
      playground('Sân chơi: hợp đồng của em', [
        'Thiết kế một lớp trừu tượng cho chủ đề em chọn:',
        '',
        '- `NhanVien` → `tinh_luong()`, `chuc_danh()` (trừu tượng); `mo_ta()` (có sẵn)',
        '- `Mon` → `nau()`, `thoi_gian_nau()` (trừu tượng); `thuc_don()` (có sẵn)',
        '- `VuKhi` → `sat_thuong()`, `tam_ban()` (trừu tượng); `so_sanh()` (có sẵn)',
        '',
        'Nhớ thử tạo một lớp con **thiếu** phương thức để thấy Python chặn lại.',
      ], [
        'from abc import ABC, abstractmethod',
        '',
        '',
        'class NhanVien(ABC):',
        '    def __init__(self, ho_ten):',
        '        self.ho_ten = ho_ten',
        '',
        '    @abstractmethod',
        '    def tinh_luong(self):',
        '        ...',
        '',
        '    @abstractmethod',
        '    def chuc_danh(self):',
        '        ...',
        '',
        '    def mo_ta(self):',
        '        return f"{self.ho_ten} - {self.chuc_danh()}: {self.tinh_luong():,.0f} d"',
        '',
        '',
        '# Viet cac lop con o day',
        '',
        '# Sau do thu tao mot lop con THIEU phuong thuc va xem loi',
      ], 'Lớp trừu tượng có cả phương thức bắt buộc lẫn phương thức chung, và chặn được lớp con thiếu sót.'),
      challenge({
        slug: 'p-nc-b09-lop-truu-tuong-tai-khoan',
        title: 'Lớp trừu tượng TaiKhoan',
        statement: [
          'Dùng `abc.ABC` viết:',
          '',
          '**`TaiKhoan(ABC)`**',
          '- `__init__(self, chu_the, so_du=0)` → gán `self.chu_the`, `self.so_du`',
          '- `@abstractmethod loai_tai_khoan(self)` → tên loại',
          '- `@abstractmethod lai_suat(self)` → lãi suất năm, dạng số thực',
          '- `nap(self, tien)` → nếu `tien <= 0` trả về `False`; ngược lại cộng vào `so_du` ' +
            'và trả về `True`',
          '- `tien_lai_nam(self)` → `so_du * lai_suat()`',
          '- `mo_ta(self)` → `f"{loai_tai_khoan()} cua {chu_the}: {so_du:,.0f} d"`',
          '',
          '**`TaiKhoanThanhToan(TaiKhoan)`** — loại `"Thanh toan"`, lãi suất `0.001`',
          '',
          '**`TaiKhoanTietKiem(TaiKhoan)`** — `__init__(self, chu_the, so_du=0, ky_han=6)`, ' +
            'loại `"Tiet kiem"`, lãi suất `0.055` nếu `ky_han >= 12`, ngược lại `0.042`',
          '',
          'Lớp `TaiKhoan` phải **không tạo được đối tượng trực tiếp**.',
        ].join('\n'),
        hints: [
          '`class TaiKhoan(ABC):` và nhớ `from abc import ABC, abstractmethod`.',
          '`TaiKhoanTietKiem.__init__` phải gọi `super().__init__(chu_the, so_du)` rồi mới gán `ky_han`.',
          '`lai_suat()` của tiết kiệm trả về giá trị khác nhau tuỳ `self.ky_han`.',
        ],
        starterCode: [
          'from abc import ABC, abstractmethod',
          '',
          '',
          'class TaiKhoan(ABC):',
          '    def __init__(self, chu_the, so_du=0):',
          '        pass',
          '',
          '    @abstractmethod',
          '    def loai_tai_khoan(self):',
          '        ...',
          '',
          '    @abstractmethod',
          '    def lai_suat(self):',
          '        ...',
          '',
          '    def nap(self, tien):',
          '        pass',
          '',
          '    def tien_lai_nam(self):',
          '        pass',
          '',
          '    def mo_ta(self):',
          '        pass',
          '',
          '',
          'class TaiKhoanThanhToan(TaiKhoan):',
          '    pass',
          '',
          '',
          'class TaiKhoanTietKiem(TaiKhoan):',
          '    pass',
        ].join('\n'),
        solutionCode: [
          'from abc import ABC, abstractmethod',
          '',
          '',
          'class TaiKhoan(ABC):',
          '    def __init__(self, chu_the, so_du=0):',
          '        self.chu_the = chu_the',
          '        self.so_du = so_du',
          '',
          '    @abstractmethod',
          '    def loai_tai_khoan(self):',
          '        ...',
          '',
          '    @abstractmethod',
          '    def lai_suat(self):',
          '        ...',
          '',
          '    def nap(self, tien):',
          '        if tien <= 0:',
          '            return False',
          '        self.so_du += tien',
          '        return True',
          '',
          '    def tien_lai_nam(self):',
          '        return self.so_du * self.lai_suat()',
          '',
          '    def mo_ta(self):',
          '        return f"{self.loai_tai_khoan()} cua {self.chu_the}: {self.so_du:,.0f} d"',
          '',
          '',
          'class TaiKhoanThanhToan(TaiKhoan):',
          '    def loai_tai_khoan(self):',
          '        return "Thanh toan"',
          '',
          '    def lai_suat(self):',
          '        return 0.001',
          '',
          '',
          'class TaiKhoanTietKiem(TaiKhoan):',
          '    def __init__(self, chu_the, so_du=0, ky_han=6):',
          '        super().__init__(chu_the, so_du)',
          '        self.ky_han = ky_han',
          '',
          '    def loai_tai_khoan(self):',
          '        return "Tiet kiem"',
          '',
          '    def lai_suat(self):',
          '        return 0.055 if self.ky_han >= 12 else 0.042',
        ].join('\n'),
        tier: 'THU_THACH',
        judgeMode: 'UNIT_TEST',
        runtimeImage: 'PY_TEST',
        unitTestCode: [
          'from abc import ABC',
          '',
          'import pytest',
          '',
          'from solution import TaiKhoan, TaiKhoanThanhToan, TaiKhoanTietKiem',
          '',
          '',
          'def test_la_lop_truu_tuong():',
          '    assert issubclass(TaiKhoan, ABC)',
          '    with pytest.raises(TypeError):',
          '        TaiKhoan("Lan")',
          '',
          '',
          'def test_ke_thua():',
          '    assert issubclass(TaiKhoanThanhToan, TaiKhoan)',
          '    assert issubclass(TaiKhoanTietKiem, TaiKhoan)',
          '',
          '',
          'def test_thanh_toan():',
          '    tk = TaiKhoanThanhToan("Lan", 1_000_000)',
          '    assert tk.loai_tai_khoan() == "Thanh toan"',
          '    assert tk.lai_suat() == 0.001',
          '    assert abs(tk.tien_lai_nam() - 1000) < 1e-6',
          '',
          '',
          'def test_tiet_kiem_ngan_han():',
          '    tk = TaiKhoanTietKiem("Minh", 10_000_000, ky_han=6)',
          '    assert tk.loai_tai_khoan() == "Tiet kiem"',
          '    assert tk.lai_suat() == 0.042',
          '',
          '',
          'def test_tiet_kiem_dai_han():',
          '    tk = TaiKhoanTietKiem("Minh", 10_000_000, ky_han=12)',
          '    assert tk.lai_suat() == 0.055',
          '    assert abs(tk.tien_lai_nam() - 550_000) < 1e-6',
          '',
          '',
          'def test_ky_han_mac_dinh():',
          '    assert TaiKhoanTietKiem("A").ky_han == 6',
          '',
          '',
          'def test_nap_hop_le():',
          '    tk = TaiKhoanThanhToan("Lan", 100)',
          '    assert tk.nap(50) is True',
          '    assert tk.so_du == 150',
          '',
          '',
          'def test_nap_khong_hop_le():',
          '    tk = TaiKhoanThanhToan("Lan", 100)',
          '    assert tk.nap(0) is False',
          '    assert tk.nap(-10) is False',
          '    assert tk.so_du == 100',
          '',
          '',
          'def test_mo_ta():',
          '    assert TaiKhoanThanhToan("Lan", 1_500_000).mo_ta() == (',
          '        "Thanh toan cua Lan: 1,500,000 d"',
          '    )',
          '',
          '',
          'def test_lop_con_thieu_phuong_thuc_bi_chan():',
          '    class ThieuSot(TaiKhoan):',
          '        def loai_tai_khoan(self):',
          '            return "Thieu"',
          '',
          '    with pytest.raises(TypeError):',
          '        ThieuSot("X")',
        ].join('\n'),
        totalPoints: 100,
      }),
    ],
  },

  {
    order: 10,
    slug: 'nc-b10-pep8-va-du-an-oop',
    title: 'Chuẩn PEP8 & dự án OOP: mô hình hoá Thư viện / Cửa hàng',
    summary:
      'Buổi khép chương: viết code theo chuẩn cộng đồng, rồi mô hình hoá một hệ thống thật ' +
      'bằng toàn bộ bốn tính chất OOP đã học.',
    objectives: [
      'Áp dụng các quy tắc PEP8 quan trọng nhất',
      'Viết docstring cho lớp và phương thức',
      'Mô hình hoá một hệ thống thực tế thành nhiều lớp',
      'Kết hợp đóng gói, kế thừa, đa hình và trừu tượng trong một dự án',
    ],
    difficulty: 5,
    estimatedMinutes: 120,
    status: 'REQUIRED',
    teacherNotes:
      'Chương 1 GHI CHÚ: nhấn mạnh PEP8 và mô hình hoá thế giới thực, đúng yêu cầu kế hoạch bài giảng. ' +
      'Dự án cuối chương nên cho học sinh chọn giữa Thư viện và Cửa hàng.',
    blocks: [
      theory('PEP8 — quy ước viết code Python', [
        '**PEP8** là tài liệu quy định cách viết code Python mà cả cộng đồng dùng chung. ' +
          'Code theo PEP8 thì bất kỳ lập trình viên Python nào cũng đọc được ngay.',
        '',
        '| Đối tượng | Quy tắc | Ví dụ đúng | Ví dụ sai |',
        '|---|---|---|---|',
        '| Lớp | `PascalCase` | `TaiKhoanNganHang` | `tai_khoan_ngan_hang` |',
        '| Hàm, phương thức | `snake_case` | `tinh_trung_binh` | `TinhTrungBinh` |',
        '| Biến | `snake_case` | `so_hoc_sinh` | `soHocSinh` |',
        '| Hằng số | `UPPER_CASE` | `THUE_SUAT` | `thueSuat` |',
        '| Nội bộ | `_snake_case` | `_bo_dem` | `bodem` |',
        '',
        '**Khoảng trắng và độ dài:**',
        '',
        '```python',
        '# DUNG',
        'x = 1',
        'ket_qua = tinh_tong(a, b)',
        'if x > 0 and y < 10:',
        'danh_sach = [1, 2, 3]',
        '',
        '# SAI',
        'x=1',
        'ket_qua = tinh_tong( a,b )',
        'if x>0 and y<10:',
        'danh_sach = [1,2,3]',
        '```',
        '',
        '- Tối đa **79 ký tự** một dòng',
        '- **Hai dòng trống** giữa các lớp và hàm ở cấp cao nhất',
        '- **Một dòng trống** giữa các phương thức trong lớp',
        '- Thụt lề **4 dấu cách**, không dùng tab',
        '',
        '💡 Công cụ tự kiểm tra: `pip install flake8` rồi chạy `flake8 tep.py`. ' +
          'Công cụ tự sửa: `pip install black` rồi `black tep.py`.',
      ], [
        'Lớp PascalCase, hàm/biến snake_case, hằng UPPER_CASE',
        'Có khoảng trắng quanh toán tử, sau dấu phẩy',
        'Tối đa 79 ký tự/dòng, thụt lề 4 dấu cách',
        '`flake8` để kiểm tra, `black` để tự sửa',
      ]),
      theory('Docstring — tài liệu ngay trong code', [
        '```python',
        'class TaiKhoan:',
        '    """Mo hinh mot tai khoan ngan hang.',
        '',
        '    Thuoc tinh:',
        '        chu_the (str): Ten chu tai khoan.',
        '        so_du (float): So du hien tai, luon khong am.',
        '    """',
        '',
        '    def rut(self, so_tien):',
        '        """Rut tien khoi tai khoan.',
        '',
        '        Tham so:',
        '            so_tien (float): So tien can rut, phai duong.',
        '',
        '        Tra ve:',
        '            bool: True neu rut thanh cong, False neu khong du so du.',
        '',
        '        Ngoai le:',
        '            ValueError: Neu so_tien khong duong.',
        '        """',
        '```',
        '',
        'Docstring khác ghi chú `#` ở ba điểm:',
        '',
        '1. Đặt **ngay dưới** dòng `def` hoặc `class`, dùng ba dấu nháy',
        '2. Truy cập được lúc chạy: `help(TaiKhoan)` hoặc `TaiKhoan.rut.__doc__`',
        '3. Mô tả **cái gì và tại sao**, không mô tả **như thế nào** (code đã nói điều đó rồi)',
        '',
        '**Quy tắc thực hành:** viết docstring cho mọi lớp và mọi phương thức công khai. ' +
          'Phương thức nội bộ (`_ten`) thì tuỳ.',
        '',
        '⚠️ Docstring sai còn tệ hơn không có docstring. Sửa code thì nhớ sửa cả docstring.',
      ], [
        'Docstring dùng ba dấu nháy, đặt ngay dưới `def`/`class`',
        'Mô tả cái gì và tại sao, không mô tả như thế nào',
        'Docstring lỗi thời còn tệ hơn không có',
      ]),
      example('Dự án mẫu: hệ thống thư viện', 'Đủ bốn tính chất OOP, viết theo PEP8, có docstring.', [
        '"""He thong quan ly thu vien - du an ket Chuong 1."""',
        '',
        'from abc import ABC, abstractmethod',
        'from datetime import date, timedelta',
        '',
        'PHI_QUA_HAN_MOI_NGAY = 5_000',
        '',
        '',
        'class TaiLieu(ABC):',
        '    """Lop truu tuong cho moi tai lieu trong thu vien."""',
        '',
        '    def __init__(self, ma, tieu_de, tac_gia):',
        '        self._ma = ma',
        '        self.tieu_de = tieu_de',
        '        self.tac_gia = tac_gia',
        '        self._nguoi_muon = None',
        '        self._ngay_muon = None',
        '',
        '    @property',
        '    def ma(self):',
        '        """str: Ma tai lieu, chi doc."""',
        '        return self._ma',
        '',
        '    @property',
        '    def dang_duoc_muon(self):',
        '        """bool: True neu tai lieu dang o tay doc gia."""',
        '        return self._nguoi_muon is not None',
        '',
        '    @abstractmethod',
        '    def loai(self):',
        '        """str: Ten loai tai lieu."""',
        '',
        '    @abstractmethod',
        '    def so_ngay_muon_toi_da(self):',
        '        """int: So ngay duoc muon toi da."""',
        '',
        '    def cho_muon(self, doc_gia, hom_nay=None):',
        '        """Cho doc gia muon tai lieu nay.',
        '',
        '        Tra ve:',
        '            bool: True neu cho muon thanh cong.',
        '        """',
        '        if self.dang_duoc_muon:',
        '            return False',
        '        self._nguoi_muon = doc_gia',
        '        self._ngay_muon = hom_nay or date.today()',
        '        return True',
        '',
        '    def han_tra(self):',
        '        """date | None: Han tra, hoac None neu chua ai muon."""',
        '        if not self.dang_duoc_muon:',
        '            return None',
        '        return self._ngay_muon + timedelta(days=self.so_ngay_muon_toi_da())',
        '',
        '    def phi_qua_han(self, hom_nay=None):',
        '        """int: Tien phat neu qua han, 0 neu con han."""',
        '        han = self.han_tra()',
        '        if han is None:',
        '            return 0',
        '        so_ngay_tre = ((hom_nay or date.today()) - han).days',
        '        return max(0, so_ngay_tre) * PHI_QUA_HAN_MOI_NGAY',
        '',
        '    def mo_ta(self):',
        '        """str: Mot dong mo ta tai lieu."""',
        '        trang_thai = "dang muon" if self.dang_duoc_muon else "co san"',
        '        return f"[{self.loai():<8}] {self.tieu_de:<28} - {self.tac_gia:<18} ({trang_thai})"',
        '',
        '',
        'class Sach(TaiLieu):',
        '    """Sach giay, cho muon 14 ngay."""',
        '',
        '    def __init__(self, ma, tieu_de, tac_gia, so_trang):',
        '        super().__init__(ma, tieu_de, tac_gia)',
        '        self.so_trang = so_trang',
        '',
        '    def loai(self):',
        '        return "Sach"',
        '',
        '    def so_ngay_muon_toi_da(self):',
        '        return 14',
        '',
        '',
        'class TapChi(TaiLieu):',
        '    """Tap chi, chi cho muon 3 ngay vi nhieu nguoi can."""',
        '',
        '    def __init__(self, ma, tieu_de, tac_gia, so_phat_hanh):',
        '        super().__init__(ma, tieu_de, tac_gia)',
        '        self.so_phat_hanh = so_phat_hanh',
        '',
        '    def loai(self):',
        '        return "Tap chi"',
        '',
        '    def so_ngay_muon_toi_da(self):',
        '        return 3',
        '',
        '',
        'class DiaDVD(TaiLieu):',
        '    """Dia DVD, cho muon 7 ngay."""',
        '',
        '    def loai(self):',
        '        return "DVD"',
        '',
        '    def so_ngay_muon_toi_da(self):',
        '        return 7',
        '',
        '',
        'class ThuVien:',
        '    """Quan ly kho tai lieu cua thu vien."""',
        '',
        '    def __init__(self, ten):',
        '        self.ten = ten',
        '        self._kho = {}',
        '',
        '    def them(self, tai_lieu):',
        '        """Them tai lieu vao kho."""',
        '        self._kho[tai_lieu.ma] = tai_lieu',
        '',
        '    def tim(self, ma):',
        '        """TaiLieu | None: Tim tai lieu theo ma."""',
        '        return self._kho.get(ma)',
        '',
        '    def danh_sach_co_san(self):',
        '        """list: Cac tai lieu chua ai muon."""',
        '        return [t for t in self._kho.values() if not t.dang_duoc_muon]',
        '',
        '    def bao_cao(self):',
        '        """str: Bao cao toan bo kho."""',
        '        dong = [f"=== {self.ten} ({len(self._kho)} tai lieu) ==="]',
        '        for tl in self._kho.values():',
        '            dong.append("  " + tl.mo_ta())',
        '        return "\\n".join(dong)',
        '',
        '',
        'hom_nay = date(2026, 8, 16)',
        'tv = ThuVien("Thu vien THCS Da Lat")',
        'tv.them(Sach("S01", "De Men phieu luu ky", "To Hoai", 180))',
        'tv.them(TapChi("T01", "Khoa hoc tuoi tre", "Ban bien tap", 512))',
        'tv.them(DiaDVD("D01", "Hanh tinh xanh", "BBC"))',
        '',
        'tv.tim("S01").cho_muon("Lan", hom_nay=date(2026, 7, 20))',
        'tv.tim("T01").cho_muon("Minh", hom_nay=hom_nay)',
        '',
        'print(tv.bao_cao())',
        'print()',
        'print(f"Co san: {len(tv.danh_sach_co_san())} tai lieu")',
        '',
        'sach = tv.tim("S01")',
        'print(f"Han tra S01 : {sach.han_tra()}")',
        'print(f"Phi qua han : {sach.phi_qua_han(hom_nay):,} d")',
      ], {
        output: [
          '=== Thu vien THCS Da Lat (3 tai lieu) ===',
          '  [Sach    ] De Men phieu luu ky          - To Hoai            (dang muon)',
          '  [Tap chi ] Khoa hoc tuoi tre            - Ban bien tap       (dang muon)',
          '  [DVD     ] Hanh tinh xanh               - BBC                (co san)',
          '',
          'Co san: 1 tai lieu',
          'Han tra S01 : 2026-08-03',
          'Phi qua han : 65,000 d',
        ].join('\n'),
        notes: [
          '**Trừu tượng**: `TaiLieu(ABC)` buộc mọi loại tài liệu phải khai báo `loai()` và `so_ngay_muon_toi_da()`.',
          '**Kế thừa**: `Sach`, `TapChi`, `DiaDVD` dùng chung toàn bộ logic mượn/trả.',
          '**Đa hình**: `mo_ta()` và `han_tra()` viết một lần nhưng cho kết quả khác nhau tuỳ loại.',
          '**Đóng gói**: `_ma` được bọc bởi property chỉ đọc; `_nguoi_muon` chỉ đổi qua `cho_muon()`.',
          'Tham số `hom_nay=None` giúp bộ test truyền ngày cố định — code phụ thuộc `date.today()` rất khó kiểm thử.',
        ],
      }),
      playground('Sân chơi: soi lỗi PEP8', [
        'Đoạn code dưới đây chạy được nhưng vi phạm **ít nhất 8 quy tắc PEP8**.',
        '',
        'Tìm và sửa hết. Sau đó tự chấm bằng cách so với bảng quy tắc ở phần lý thuyết.',
      ], [
        'class tai_khoan:',
        '    Lai_Suat=0.05',
        '    def __init__(self,ChuThe,SoDu):',
        '        self.ChuThe=ChuThe',
        '        self.SoDu=SoDu',
        '    def Nap(self,tien):',
        '        if tien>0:self.SoDu+=tien',
        '        return self.SoDu',
        '    def tinhLai( self ):',
        '        return self.SoDu*self.Lai_Suat',
        'a=tai_khoan("Lan",1000000)',
        'a.Nap( 500000 )',
        'print(a.tinhLai())',
      ], 'Sửa hết lỗi PEP8 và code vẫn chạy đúng như cũ.'),
      projectBlock(
        'Dự án kết Chương 1: mô hình hoá một hệ thống thật',
        [
          'Chọn **một** hệ thống và mô hình hoá bằng OOP:',
          '',
          '**A — Thư viện:** tài liệu (sách, tạp chí, DVD), độc giả, phiếu mượn, tính phí quá hạn.',
          '',
          '**B — Cửa hàng:** sản phẩm (hàng thường, hàng có hạn dùng, hàng điện tử), khách hàng, ' +
            'giỏ hàng, đơn hàng, khuyến mãi.',
          '',
          '**Yêu cầu bắt buộc — phải có đủ bốn tính chất OOP:**',
          '',
          '| Tính chất | Thể hiện ở đâu |',
          '|---|---|',
          '| **Trừu tượng** | Ít nhất một lớp `ABC` với `@abstractmethod` |',
          '| **Kế thừa** | Ít nhất 3 lớp con từ lớp trừu tượng đó |',
          '| **Đa hình** | Một phương thức ở lớp cha cho kết quả khác nhau theo lớp con |',
          '| **Đóng gói** | Ít nhất 2 `@property`, trong đó có 1 property chỉ đọc |',
          '',
          '**Yêu cầu về chất lượng code:**',
          '',
          '- Tuân thủ PEP8 (kiểm tra bằng `flake8` nếu có)',
          '- Docstring cho mọi lớp và phương thức công khai',
          '- Constructor kiểm tra dữ liệu đầu vào',
          '- Có phần `if __name__ == "__main__":` để chạy thử',
          '',
          '**Nộp kèm:** một sơ đồ (vẽ tay hoặc gõ) thể hiện quan hệ giữa các lớp.',
        ],
        'CUSTOM',
        [
          'Mô hình hoá bằng lời: liệt kê lớp, thuộc tính, phương thức',
          'Viết lớp trừu tượng và các lớp con',
          'Thêm đóng gói bằng property và kiểm tra dữ liệu',
          'Chuẩn hoá PEP8, viết docstring, nộp kèm sơ đồ',
        ],
        { minutes: 70 },
      ),
      quizBlock({
        slug: 'q-nc-b10-pep8-va-oop',
        title: 'Kiểm tra tổng kết Chương 1',
        passingScore: 70,
        questions: [
          {
            type: 'MULTIPLE_CHOICE',
            prompt: 'Theo PEP8, tên lớp nào viết đúng chuẩn?',
            explanation: 'Tên lớp dùng PascalCase — viết hoa chữ cái đầu mỗi từ, không có gạch dưới.',
            choices: [
              { text: 'TaiKhoanNganHang', isCorrect: true },
              { text: 'tai_khoan_ngan_hang' },
              { text: 'taiKhoanNganHang' },
              { text: 'TAI_KHOAN_NGAN_HANG' },
            ],
          },
          {
            type: 'MULTIPLE_CHOICE',
            prompt: 'Vì sao không tạo được đối tượng từ một lớp có `@abstractmethod` chưa được ghi đè?',
            explanation:
              'Python chặn ngay lúc tạo, kèm thông báo nói rõ thiếu phương thức nào — biến lỗi âm thầm thành lỗi rõ ràng.',
            choices: [
              { text: 'Vì lớp đó chưa đầy đủ, Python chặn để tránh lỗi âm thầm về sau', isCorrect: true },
              { text: 'Vì lớp trừu tượng tốn nhiều bộ nhớ' },
              { text: 'Vì `ABC` khoá luôn constructor' },
              { text: 'Thật ra vẫn tạo được bình thường' },
            ],
          },
          {
            type: 'MULTIPLE_CHOICE',
            prompt: 'Lợi ích lớn nhất của đa hình so với chuỗi `if/elif` kiểm tra kiểu là gì?',
            explanation:
              'Thêm loại mới chỉ cần viết lớp mới, không phải sửa code đang chạy tốt — nguyên tắc Mở–Đóng.',
            choices: [
              { text: 'Thêm loại mới không phải sửa code cũ', isCorrect: true },
              { text: 'Chạy nhanh hơn đáng kể' },
              { text: 'Tốn ít bộ nhớ hơn' },
              { text: 'Không cần viết test' },
            ],
          },
          {
            type: 'TRUE_FALSE',
            prompt: 'Thuộc tính chỉ có getter (`@property` mà không có setter) thì không gán được từ bên ngoài.',
            explanation: 'Đúng. Gán vào sẽ gây `AttributeError`. Đây là cách tạo thuộc tính chỉ đọc.',
            choices: [{ text: 'Đúng', isCorrect: true }, { text: 'Sai' }],
          },
          {
            type: 'FILL_BLANK',
            prompt: 'Từ khoá nào dùng để gọi phương thức của lớp cha từ trong lớp con?',
            explanation: '`super()`, ví dụ `super().__init__(...)`.',
            acceptedAnswers: ['super', 'super()', 'super().__init__', 'ham super'],
            matchMode: 'normalised',
          },
          {
            type: 'SHORT_ANSWER',
            prompt:
              'Hãy giải thích bằng lời của em bốn tính chất OOP (đóng gói, kế thừa, đa hình, trừu tượng), ' +
              'mỗi tính chất kèm một ví dụ từ dự án của em.',
            explanation:
              'Đóng gói: giấu dữ liệu, chỉ cho truy cập qua property có kiểm tra. Kế thừa: lớp con dùng lại ' +
              'lớp cha. Đa hình: cùng lời gọi, mỗi lớp phản ứng theo cách riêng. Trừu tượng: lớp cha đặt ' +
              'ra hợp đồng mà lớp con bắt buộc thực hiện.',
            points: 30,
          },
        ],
      }),
      reflection(
        'Nhìn lại Chương 1',
        'Mười buổi trước, em quản lý dữ liệu bằng biến và từ điển. Giờ em mô hình hoá được cả một ' +
          'hệ thống. Hãy viết: (1) tính chất OOP nào em thấy hữu ích nhất và vì sao, ' +
          '(2) một chỗ trong dự án cũ của em mà giờ em sẽ viết lại bằng OOP.',
      ),
    ],
  },
];
