/**
 * Python Nâng Cao — Chương 1 (OOP), Buổi 1–5.
 *
 * Judge contract for this chapter: the student's submission is saved as
 * `solution.py` inside the sandbox, and the hidden pytest suite in
 * `unitTestCode` imports from it. I/O matching cannot verify a constructor,
 * an inherited method or a private attribute — unit testing can.
 */
import type { LessonSpec } from '../types.ts';
import { challenge, example, playground, quizBlock, theory } from '../builders.ts';

export const advancedLessons1to5: LessonSpec[] = [
  {
    order: 1,
    slug: 'nc-b01-gioi-thieu-oop-mo-hinh-hoa',
    title: 'Giới thiệu OOP & tư duy mô hình hoá thế giới thực',
    summary:
      'Trước khi học cú pháp, hãy học cách nhìn. OOP là cách mô tả thế giới thật bằng code — ' +
      'buổi này tập trung vào tư duy, không phải từ khoá.',
    objectives: [
      'Giải thích được vì sao lập trình hướng đối tượng ra đời',
      'Phân biệt lập trình thủ tục và lập trình hướng đối tượng',
      'Nhận diện đối tượng, thuộc tính và hành vi trong một bài toán thực tế',
      'Vẽ được sơ đồ mô hình hoá đơn giản cho một hệ thống',
    ],
    difficulty: 2,
    estimatedMinutes: 90,
    status: 'REQUIRED',
    teacherNotes:
      'Chương 1 GHI CHÚ: nhấn mạnh mô hình hoá thế giới thực. Buổi này cố ý CHƯA dạy cú pháp class — ' +
      'học sinh cần thấy vấn đề trước khi thấy giải pháp.',
    prerequisites: [],
    blocks: [
      theory('Vấn đề mà OOP sinh ra để giải quyết', [
        'Ở khoá Cơ Bản, em quản lý một học sinh bằng vài biến rời rạc:',
        '',
        '```python',
        'ten_1 = "Lan"',
        'tuoi_1 = 14',
        'diem_1 = [8, 9, 7]',
        '',
        'ten_2 = "Minh"',
        'tuoi_2 = 15',
        'diem_2 = [7, 8, 9]',
        '```',
        '',
        'Với 3 học sinh đã rối. Với 300 thì không thể.',
        '',
        'Dùng từ điển thì khá hơn:',
        '',
        '```python',
        'hoc_sinh = [',
        '    {"ten": "Lan", "tuoi": 14, "diem": [8, 9, 7]},',
        '    {"ten": "Minh", "tuoi": 15, "diem": [7, 8, 9]},',
        ']',
        '',
        'def tinh_trung_binh(hs):',
        '    return sum(hs["diem"]) / len(hs["diem"])',
        '```',
        '',
        'Nhưng vẫn còn ba vấn đề:',
        '',
        '1. **Dữ liệu và hành vi tách rời.** `tinh_trung_binh` là một hàm trôi nổi ở đâu đó, ' +
          'không gắn với học sinh.',
        '2. **Không ai bảo vệ dữ liệu.** Ai cũng có thể viết `hs["diem"] = "abc"` mà không bị chặn.',
        '3. **Gõ sai khoá không báo lỗi ngay.** `hs["tên"]` thay vì `hs["ten"]` chỉ đổ vỡ lúc chạy.',
        '',
        '**OOP gộp dữ liệu và hành vi vào cùng một chỗ**, và cho phép em kiểm soát ai được làm gì ' +
          'với dữ liệu đó.',
      ], [
        'Biến rời rạc không quản lý nổi nhiều đối tượng',
        'Từ điển tốt hơn nhưng dữ liệu vẫn tách rời hành vi',
        'OOP gộp dữ liệu và hành vi, và bảo vệ dữ liệu',
      ]),
      theory('Mô hình hoá: nhìn thế giới như những đối tượng', [
        'Trước khi viết dòng code nào, hãy trả lời ba câu hỏi về bài toán:',
        '',
        '| Câu hỏi | Trong OOP gọi là | Ví dụ: thư viện |',
        '|---|---|---|',
        '| Có những **thứ** gì? | Lớp (class) | Sách, Độc giả, Phiếu mượn |',
        '| Mỗi thứ **biết** gì về mình? | Thuộc tính (attribute) | Sách: tên, tác giả, ISBN, còn hay đã mượn |',
        '| Mỗi thứ **làm** được gì? | Phương thức (method) | Sách: cho mượn, trả về, kiểm tra tình trạng |',
        '',
        '**Quy tắc thực hành:** đọc đề bài rồi gạch chân.',
        '',
        '- **Danh từ** → thường là lớp hoặc thuộc tính',
        '- **Động từ** → thường là phương thức',
        '',
        '*"Hệ thống quản lý **thư viện** cho phép **độc giả** **mượn sách**. Mỗi **cuốn sách** có ' +
          '**tên**, **tác giả**. Khi **mượn**, hệ thống **ghi lại** ngày mượn và **tính** hạn trả."*',
        '',
        'Từ một câu như trên, em đã có ngay:',
        '',
        '```',
        'Lop Sach          : ten, tac_gia, da_muon',
        'Lop DocGia        : ho_ten, ma_the, danh_sach_dang_muon',
        'Lop PhieuMuon     : sach, doc_gia, ngay_muon, han_tra',
        '                    -> tinh_han_tra(), da_qua_han()',
        '```',
        '',
        '⚠️ **Sai lầm phổ biến của người mới:** tạo một lớp khổng lồ tên `QuanLyTatCa` chứa mọi thứ. ' +
          'Hãy chia thành nhiều lớp nhỏ, mỗi lớp mô tả **một** loại đồ vật hoặc khái niệm.',
      ], [
        'Danh từ → lớp và thuộc tính; động từ → phương thức',
        'Mỗi lớp mô tả MỘT khái niệm',
        'Tránh lớp khổng lồ chứa tất cả mọi thứ',
      ]),
      example('Cùng một bài toán, ba cách viết', 'Đọc từ trên xuống để thấy code gọn dần và an toàn dần.', [
        '# ============ CACH 1: Bien roi rac ============',
        'ten_1, tuoi_1, diem_1 = "Lan", 14, [8, 9, 7]',
        'ten_2, tuoi_2, diem_2 = "Minh", 15, [7, 8, 9]',
        '',
        'tb_1 = sum(diem_1) / len(diem_1)',
        'tb_2 = sum(diem_2) / len(diem_2)',
        'print(f"{ten_1}: {tb_1:.2f}")',
        'print(f"{ten_2}: {tb_2:.2f}")',
        '',
        '',
        '# ============ CACH 2: Tu dien + ham ============',
        'hoc_sinh = [',
        '    {"ten": "Lan", "tuoi": 14, "diem": [8, 9, 7]},',
        '    {"ten": "Minh", "tuoi": 15, "diem": [7, 8, 9]},',
        ']',
        '',
        '',
        'def trung_binh(hs):',
        '    return sum(hs["diem"]) / len(hs["diem"])',
        '',
        '',
        'for hs in hoc_sinh:',
        '    print(f"{hs[\'ten\']}: {trung_binh(hs):.2f}")',
        '',
        '',
        '# ============ CACH 3: OOP (xem truoc buoi 2) ============',
        'class HocSinh:',
        '    def __init__(self, ten, tuoi, diem):',
        '        self.ten = ten',
        '        self.tuoi = tuoi',
        '        self.diem = diem',
        '',
        '    def trung_binh(self):',
        '        return sum(self.diem) / len(self.diem)',
        '',
        '    def xep_loai(self):',
        '        tb = self.trung_binh()',
        '        if tb >= 8:',
        '            return "Gioi"',
        '        if tb >= 6.5:',
        '            return "Kha"',
        '        return "Trung binh"',
        '',
        '',
        'ds = [HocSinh("Lan", 14, [8, 9, 7]), HocSinh("Minh", 15, [7, 8, 9])]',
        'for hs in ds:',
        '    print(f"{hs.ten}: {hs.trung_binh():.2f} - {hs.xep_loai()}")',
      ], {
        output: [
          'Lan: 8.00',
          'Minh: 8.00',
          'Lan: 8.00',
          'Minh: 8.00',
          'Lan: 8.00 - Gioi',
          'Minh: 8.00 - Gioi',
        ].join('\n'),
        notes: [
          'Ở cách 3, `hs.trung_binh()` đọc như tiếng Anh: "học sinh, tính trung bình của cậu đi".',
          'Thêm `xep_loai()` chỉ cần sửa một chỗ trong lớp — mọi học sinh có ngay hành vi mới.',
          'Cú pháp `class` và `self` sẽ được giải thích kỹ ở buổi 2 và 3. Buổi này chỉ cần thấy sự khác biệt.',
        ],
      }),
      playground('Sân chơi: mô hình hoá bằng lời', [
        'Chưa viết code. Chọn **một** hệ thống dưới đây và mô hình hoá bằng lời:',
        '',
        '- Quán cà phê (đồ uống, đơn hàng, khách)',
        '- Trò chơi RPG (nhân vật, vật phẩm, quái)',
        '- Cửa hàng trực tuyến (sản phẩm, giỏ hàng, đơn)',
        '- Trường học (học sinh, lớp, môn, điểm)',
        '',
        'Với mỗi lớp, liệt kê ít nhất 3 thuộc tính và 2 phương thức.',
      ], [
        '# Mo hinh hoa bang GHI CHU, chua can viet code',
        '',
        '# He thong: ...',
        '',
        '# Lop 1: ...',
        '#   Thuoc tinh: ...',
        '#   Phuong thuc: ...',
        '',
        '# Lop 2: ...',
        '#   Thuoc tinh: ...',
        '#   Phuong thuc: ...',
        '',
        '# Lop 3: ...',
        '#   Thuoc tinh: ...',
        '#   Phuong thuc: ...',
        '',
        'print("Da mo hinh hoa xong!")',
      ], 'Mô hình hoá được một hệ thống thành 3 lớp, mỗi lớp có thuộc tính và phương thức rõ ràng.'),
      quizBlock({
        slug: 'q-nc-b01-tu-duy-oop',
        title: 'Kiểm tra nhanh: tư duy OOP',
        questions: [
          {
            type: 'MULTIPLE_CHOICE',
            prompt: 'Trong câu "Độc giả mượn sách", đâu là ứng viên cho **phương thức**?',
            explanation: 'Động từ thường trở thành phương thức. "Mượn" là hành vi.',
            choices: [
              { text: 'mượn', isCorrect: true },
              { text: 'độc giả' },
              { text: 'sách' },
              { text: 'cả ba đều là phương thức' },
            ],
          },
          {
            type: 'MULTIPLE_CHOICE',
            prompt: 'Điểm khác biệt cốt lõi giữa OOP và cách dùng từ điển + hàm là gì?',
            explanation:
              'OOP gắn dữ liệu với hành vi trong cùng một đơn vị, và cho phép kiểm soát truy cập.',
            choices: [
              { text: 'OOP gộp dữ liệu và hành vi vào một chỗ và bảo vệ được dữ liệu', isCorrect: true },
              { text: 'OOP chạy nhanh hơn từ điển' },
              { text: 'OOP tốn ít bộ nhớ hơn' },
              { text: 'Không có khác biệt thật sự' },
            ],
          },
          {
            type: 'TRUE_FALSE',
            prompt:
              'Với hệ thống quản lý thư viện, nên tạo một lớp `QuanLyThuVien` chứa toàn bộ dữ liệu ' +
              'sách, độc giả và phiếu mượn.',
            explanation:
              'Sai. Nên chia thành nhiều lớp nhỏ, mỗi lớp mô tả một khái niệm. Lớp khổng lồ rất khó sửa và khó thử.',
            choices: [{ text: 'Đúng' }, { text: 'Sai', isCorrect: true }],
          },
          {
            type: 'SHORT_ANSWER',
            prompt:
              'Mô hình hoá một trò chơi RPG đơn giản: liệt kê 2 lớp, mỗi lớp 3 thuộc tính và 2 phương thức.',
            explanation:
              'Ví dụ: lớp NhanVat (ten, mau, cap_do — tan_cong(), nhan_sat_thuong()) và ' +
              'lớp VatPham (ten, gia_tri, loai — su_dung(), mo_ta()).',
            points: 20,
          },
        ],
      }),
    ],
  },

  {
    order: 2,
    slug: 'nc-b02-class-object-thuoc-tinh-phuong-thuc',
    title: 'Class & Object — thuộc tính và phương thức',
    summary:
      'Cú pháp đầu tiên của OOP. Lớp là bản thiết kế, đối tượng là sản phẩm tạo ra từ bản thiết kế đó.',
    objectives: [
      'Định nghĩa được lớp bằng từ khoá `class`',
      'Tạo đối tượng từ lớp và truy cập thuộc tính',
      'Viết phương thức và hiểu vai trò của `self`',
      'Phân biệt thuộc tính của lớp và thuộc tính của đối tượng',
    ],
    difficulty: 3,
    status: 'REQUIRED',
    teacherNotes: '`self` là chỗ khó nhất buổi này. Giải thích bằng ví dụ nhiều đối tượng cùng lớp.',
    blocks: [
      theory('Lớp là bản thiết kế, đối tượng là sản phẩm', [
        '```python',
        'class HocSinh:            # BAN THIET KE',
        '    truong = "THCS Da Lat"    # thuoc tinh cua LOP - moi doi tuong dung chung',
        '',
        '    def gioi_thieu(self):     # phuong thuc',
        '        return f"Toi la {self.ten}, hoc tai {self.truong}"',
        '',
        '',
        'lan = HocSinh()           # SAN PHAM 1',
        'lan.ten = "Lan"           # thuoc tinh cua DOI TUONG - rieng tung ban',
        '',
        'minh = HocSinh()          # SAN PHAM 2',
        'minh.ten = "Minh"',
        '',
        'print(lan.gioi_thieu())   # Toi la Lan, hoc tai THCS Da Lat',
        'print(minh.gioi_thieu())  # Toi la Minh, hoc tai THCS Da Lat',
        '```',
        '',
        '| Khái niệm | Ví dụ đời thường |',
        '|---|---|',
        '| **Lớp** (class) | Bản vẽ ngôi nhà |',
        '| **Đối tượng** (object) | Ngôi nhà thật xây từ bản vẽ đó |',
        '| **Thuộc tính** | Màu sơn, số phòng của một ngôi nhà cụ thể |',
        '| **Phương thức** | Mở cửa, bật đèn |',
        '',
        'Từ **một** bản vẽ xây được **nhiều** ngôi nhà, mỗi ngôi có màu sơn riêng. ' +
          'Đó chính là quan hệ giữa lớp và đối tượng.',
        '',
        '📌 **Quy ước đặt tên (PEP8):** tên lớp viết kiểu `PascalCase` — `HocSinh`, `TaiKhoanNganHang`. ' +
          'Tên biến và phương thức viết kiểu `snake_case` — `ho_ten`, `tinh_trung_binh`.',
      ], [
        'Lớp = bản thiết kế, đối tượng = sản phẩm cụ thể',
        'Thuộc tính của lớp dùng chung; thuộc tính của đối tượng riêng từng bản',
        'Tên lớp: PascalCase. Tên biến/phương thức: snake_case',
      ]),
      theory('`self` — từ khoá gây bối rối nhất', [
        '`self` nghĩa là **"chính đối tượng đang gọi phương thức này"**.',
        '',
        'Khi em viết `lan.gioi_thieu()`, Python thực chất gọi `HocSinh.gioi_thieu(lan)`. ' +
          'Đối tượng `lan` được truyền vào làm tham số đầu tiên, và tham số đó tên là `self`.',
        '',
        '```python',
        'class DemSo:',
        '    def dat(self, gia_tri):',
        '        self.so = gia_tri        # gan vao CHINH doi tuong nay',
        '',
        '    def tang(self):',
        '        self.so += 1',
        '        return self.so',
        '',
        '',
        'a = DemSo()',
        'b = DemSo()',
        'a.dat(10)',
        'b.dat(100)',
        '',
        'print(a.tang())    # 11  - chi a bi anh huong',
        'print(b.tang())    # 101 - b hoan toan doc lap',
        '```',
        '',
        '**Ba quy tắc về `self`:**',
        '',
        '1. `self` **luôn là tham số đầu tiên** của mọi phương thức thường',
        '2. Khi **gọi**, em **không truyền** `self` — Python tự làm',
        '3. Muốn truy cập thuộc tính bên trong phương thức, **bắt buộc** viết `self.ten`, ' +
          'không viết `ten` trơn',
        '',
        '⚠️ Quên `self` trong danh sách tham số là lỗi số một của người mới:',
        '',
        '```python',
        'def gioi_thieu():          # THIEU self',
        '    return f"Toi la {self.ten}"',
        '',
        '# TypeError: gioi_thieu() takes 0 positional arguments but 1 was given',
        '```',
      ], [
        '`self` = chính đối tượng đang gọi phương thức',
        'Luôn là tham số đầu tiên, nhưng không truyền khi gọi',
        'Bên trong phương thức phải viết `self.thuoc_tinh`',
      ]),
      example('Lớp đầu tiên hoàn chỉnh', 'Ba đối tượng độc lập từ cùng một lớp.', [
        'class TaiKhoan:',
        '    """Mo hinh mot tai khoan ngan hang don gian."""',
        '',
        '    ngan_hang = "DYE Bank"        # thuoc tinh cua LOP',
        '',
        '    def khoi_tao(self, chu_the, so_du):',
        '        self.chu_the = chu_the     # thuoc tinh cua DOI TUONG',
        '        self.so_du = so_du',
        '        self.lich_su = []',
        '',
        '    def nap(self, tien):',
        '        if tien <= 0:',
        '            return False',
        '        self.so_du += tien',
        '        self.lich_su.append(f"Nap {tien:,}")',
        '        return True',
        '',
        '    def rut(self, tien):',
        '        if tien <= 0 or tien > self.so_du:',
        '            return False',
        '        self.so_du -= tien',
        '        self.lich_su.append(f"Rut {tien:,}")',
        '        return True',
        '',
        '    def sao_ke(self):',
        '        dong = [f"=== {self.chu_the} tai {self.ngan_hang} ==="]',
        '        for muc in self.lich_su:',
        '            dong.append(f"  {muc}")',
        '        dong.append(f"  So du: {self.so_du:,} d")',
        '        return "\\n".join(dong)',
        '',
        '',
        'a = TaiKhoan()',
        'a.khoi_tao("Nguyen Van A", 1_000_000)',
        '',
        'b = TaiKhoan()',
        'b.khoi_tao("Tran Thi B", 500_000)',
        '',
        'a.nap(200_000)',
        'a.rut(50_000)',
        'b.rut(1_000_000)      # that bai: khong du so du',
        '',
        'print(a.sao_ke())',
        'print()',
        'print(b.sao_ke())',
      ], {
        output: [
          '=== Nguyen Van A tai DYE Bank ===',
          '  Nap 200,000',
          '  Rut 50,000',
          '  So du: 1,150,000 d',
          '',
          '=== Tran Thi B tai DYE Bank ===',
          '  So du: 500,000 d',
          ].join('\n'),
        notes: [
          '`b.rut(1_000_000)` trả về False và không ghi vào lịch sử — dữ liệu được bảo vệ khỏi thao tác sai.',
          'Hai đối tượng có `lich_su` riêng, hoàn toàn độc lập.',
          '`ngan_hang` là thuộc tính của lớp nên cả hai dùng chung, truy cập qua `self.ngan_hang`.',
          'Dấu gạch dưới trong `1_000_000` chỉ để dễ đọc — Python bỏ qua nó.',
        ],
      }),
      playground('Sân chơi: lớp của em', [
        'Viết một lớp mô tả thứ em thích: `NhanVatGame`, `MonAn`, `BaiHat`, `ChiecXe`...',
        '',
        'Yêu cầu: ít nhất 3 thuộc tính, 2 phương thức, và tạo 2 đối tượng khác nhau để kiểm chứng ' +
          'chúng độc lập với nhau.',
      ], [
        'class NhanVatGame:',
        '    the_gioi = "Dai luc Aurora"',
        '',
        '    def khoi_tao(self, ten, mau, suc_manh):',
        '        self.ten = ten',
        '        self.mau = mau',
        '        self.suc_manh = suc_manh',
        '',
        '    def tan_cong(self, muc_tieu):',
        '        muc_tieu.mau -= self.suc_manh',
        '        return f"{self.ten} danh {muc_tieu.ten} mat {self.suc_manh} mau"',
        '',
        '    def con_song(self):',
        '        return self.mau > 0',
        '',
        '',
        'hung = NhanVatGame()',
        'hung.khoi_tao("Hung", 100, 25)',
        '',
        'quai = NhanVatGame()',
        'quai.khoi_tao("Quai vat", 60, 10)',
        '',
        'print(hung.tan_cong(quai))',
        'print(f"{quai.ten} con song: {quai.con_song()}")',
      ], 'Lớp có đủ 3 thuộc tính, 2 phương thức, và hai đối tượng hoạt động độc lập.'),
      challenge({
        slug: 'p-nc-b02-lop-hinh-chu-nhat',
        title: 'Lớp HinhChuNhat',
        statement: [
          'Viết lớp `HinhChuNhat` với:',
          '',
          '**Phương thức `dat_kich_thuoc(self, dai, rong)`** — gán hai thuộc tính `self.dai` và `self.rong`.',
          '',
          '**Phương thức `chu_vi(self)`** — trả về `(dai + rong) * 2`.',
          '',
          '**Phương thức `dien_tich(self)`** — trả về `dai * rong`.',
          '',
          '**Phương thức `la_hinh_vuong(self)`** — trả về `True` nếu `dai == rong`.',
          '',
          'Lớp cũng phải có **thuộc tính của lớp** tên `don_vi` với giá trị `"cm"`.',
          '',
          'Lưu bài của em trong tệp; hệ thống sẽ tự kiểm tra bằng bộ test ẩn.',
        ].join('\n'),
        hints: [
          '`don_vi = "cm"` viết thẳng trong thân lớp, ngoài mọi phương thức.',
          'Mọi phương thức đều cần `self` làm tham số đầu tiên.',
          '`la_hinh_vuong` chỉ cần `return self.dai == self.rong` — không cần if/else.',
        ],
        starterCode: [
          'class HinhChuNhat:',
          '    # Thuoc tinh cua lop',
          '    don_vi = "cm"',
          '',
          '    def dat_kich_thuoc(self, dai, rong):',
          '        pass',
          '',
          '    def chu_vi(self):',
          '        pass',
          '',
          '    def dien_tich(self):',
          '        pass',
          '',
          '    def la_hinh_vuong(self):',
          '        pass',
        ].join('\n'),
        solutionCode: [
          'class HinhChuNhat:',
          '    don_vi = "cm"',
          '',
          '    def dat_kich_thuoc(self, dai, rong):',
          '        self.dai = dai',
          '        self.rong = rong',
          '',
          '    def chu_vi(self):',
          '        return (self.dai + self.rong) * 2',
          '',
          '    def dien_tich(self):',
          '        return self.dai * self.rong',
          '',
          '    def la_hinh_vuong(self):',
          '        return self.dai == self.rong',
        ].join('\n'),
        tier: 'CO_BAN',
        judgeMode: 'UNIT_TEST',
        runtimeImage: 'PY_TEST',
        unitTestCode: [
          'from solution import HinhChuNhat',
          '',
          '',
          'def test_thuoc_tinh_cua_lop():',
          '    assert HinhChuNhat.don_vi == "cm"',
          '',
          '',
          'def test_dat_kich_thuoc():',
          '    h = HinhChuNhat()',
          '    h.dat_kich_thuoc(5, 3)',
          '    assert h.dai == 5',
          '    assert h.rong == 3',
          '',
          '',
          'def test_chu_vi():',
          '    h = HinhChuNhat()',
          '    h.dat_kich_thuoc(5, 3)',
          '    assert h.chu_vi() == 16',
          '',
          '',
          'def test_dien_tich():',
          '    h = HinhChuNhat()',
          '    h.dat_kich_thuoc(5, 3)',
          '    assert h.dien_tich() == 15',
          '',
          '',
          'def test_la_hinh_vuong_dung():',
          '    h = HinhChuNhat()',
          '    h.dat_kich_thuoc(4, 4)',
          '    assert h.la_hinh_vuong() is True',
          '',
          '',
          'def test_la_hinh_vuong_sai():',
          '    h = HinhChuNhat()',
          '    h.dat_kich_thuoc(4, 5)',
          '    assert h.la_hinh_vuong() is False',
          '',
          '',
          'def test_hai_doi_tuong_doc_lap():',
          '    a = HinhChuNhat()',
          '    b = HinhChuNhat()',
          '    a.dat_kich_thuoc(2, 3)',
          '    b.dat_kich_thuoc(10, 20)',
          '    assert a.dien_tich() == 6',
          '    assert b.dien_tich() == 200',
        ].join('\n'),
        totalPoints: 100,
      }),
    ],
  },

  {
    order: 3,
    slug: 'nc-b03-constructor-init',
    title: 'Constructor `__init__` & khởi tạo đối tượng',
    summary:
      'Không ai muốn gọi `dat_kich_thuoc()` sau mỗi lần tạo đối tượng. `__init__` chạy tự động ' +
      'ngay lúc đối tượng ra đời.',
    objectives: [
      'Viết `__init__` để khởi tạo đối tượng',
      'Truyền tham số vào lúc tạo đối tượng',
      'Dùng tham số mặc định trong constructor',
      'Kiểm tra tính hợp lệ của dữ liệu ngay trong constructor',
    ],
    difficulty: 3,
    status: 'REQUIRED',
    teacherNotes: 'Nhấn mạnh: `__init__` KHÔNG tạo ra đối tượng, nó chỉ khởi tạo đối tượng vừa được tạo.',
    blocks: [
      theory('`__init__` — phương thức chạy tự động', [
        '```python',
        'class HocSinh:',
        '    def __init__(self, ten, tuoi):',
        '        self.ten = ten',
        '        self.tuoi = tuoi',
        '        self.diem = []          # moi hoc sinh bat dau voi danh sach RONG',
        '',
        '',
        'lan = HocSinh("Lan", 14)        # __init__ chay TU DONG ngay tai day',
        'print(lan.ten)                  # Lan',
        '```',
        '',
        'Hai dấu gạch dưới ở hai đầu (`__init__`) là quy ước của Python cho các phương thức đặc biệt, ' +
          'thường gọi là **dunder** (double underscore). Em không gọi chúng trực tiếp — Python gọi hộ.',
        '',
        '**Tham số mặc định** dùng được như với hàm thường:',
        '',
        '```python',
        'class TaiKhoan:',
        '    def __init__(self, chu_the, so_du=0):',
        '        self.chu_the = chu_the',
        '        self.so_du = so_du',
        '',
        '',
        'a = TaiKhoan("Lan")            # so_du = 0',
        'b = TaiKhoan("Minh", 500_000)  # so_du = 500000',
        '```',
        '',
        '⚠️ **Bẫy kinh điển — đừng dùng list làm giá trị mặc định:**',
        '',
        '```python',
        '# SAI: moi doi tuong DUNG CHUNG mot danh sach!',
        'def __init__(self, ten, diem=[]):',
        '    self.diem = diem',
        '',
        '# DUNG',
        'def __init__(self, ten, diem=None):',
        '    self.diem = diem if diem is not None else []',
        '```',
        '',
        'Đây chính là bẫy sao chép danh sách ở buổi 21 khoá Cơ Bản, xuất hiện lại dưới dạng khác.',
      ], [
        '`__init__` chạy tự động khi tạo đối tượng',
        'Tham số mặc định dùng được bình thường',
        'KHÔNG BAO GIỜ dùng `[]` hay `{}` làm giá trị mặc định',
      ]),
      theory('Kiểm tra dữ liệu ngay từ đầu', [
        'Constructor là **cửa ngõ** duy nhất để tạo đối tượng, nên đây là chỗ lý tưởng để chặn ' +
          'dữ liệu sai:',
        '',
        '```python',
        'class HocSinh:',
        '    def __init__(self, ten, tuoi):',
        '        if not ten or not ten.strip():',
        '            raise ValueError("Ten khong duoc de trong")',
        '        if not isinstance(tuoi, int):',
        '            raise TypeError("Tuoi phai la so nguyen")',
        '        if tuoi < 0 or tuoi > 120:',
        '            raise ValueError("Tuoi phai tu 0 den 120")',
        '',
        '        self.ten = ten.strip()',
        '        self.tuoi = tuoi',
        '```',
        '',
        '`raise` **ném ra** một lỗi, dừng ngay việc tạo đối tượng. Nhờ vậy trong chương trình ' +
          'sẽ **không bao giờ tồn tại** một `HocSinh` có tuổi âm.',
        '',
        '| Loại lỗi nên ném | Khi nào |',
        '|---|---|',
        '| `ValueError` | Đúng kiểu nhưng giá trị vô lý (tuổi = -5) |',
        '| `TypeError` | Sai kiểu dữ liệu (tuổi là chuỗi) |',
        '',
        '💡 Nguyên tắc: **thà lỗi sớm còn hơn sai âm thầm**. Một `ValueError` ngay lúc tạo dễ sửa hơn ' +
          'nhiều so với một con số kỳ lạ xuất hiện sau 200 dòng code.',
        '',
        'Ở buổi 27 khoá Cơ Bản em đã học **bắt** lỗi bằng `try`/`except`. Giờ em học **ném** lỗi. ' +
          'Hai việc bổ sung cho nhau.',
      ], [
        '`raise ValueError(...)` để chặn dữ liệu vô lý',
        '`ValueError` cho giá trị sai, `TypeError` cho kiểu sai',
        'Thà lỗi sớm còn hơn sai âm thầm',
      ]),
      example('Constructor có kiểm tra đầy đủ', 'Đối tượng tạo ra luôn ở trạng thái hợp lệ.', [
        'class SanPham:',
        '    """San pham trong cua hang. Bao dam luon hop le sau khi tao."""',
        '',
        '    thue_suat = 0.08',
        '',
        '    def __init__(self, ten, gia, so_luong=0, giam_gia=0.0):',
        '        if not ten or not ten.strip():',
        '            raise ValueError("Ten san pham khong duoc de trong")',
        '        if gia < 0:',
        '            raise ValueError(f"Gia khong duoc am, nhan duoc {gia}")',
        '        if so_luong < 0:',
        '            raise ValueError(f"So luong khong duoc am, nhan duoc {so_luong}")',
        '        if not 0 <= giam_gia <= 1:',
        '            raise ValueError("Giam gia phai tu 0 den 1")',
        '',
        '        self.ten = ten.strip()',
        '        self.gia = gia',
        '        self.so_luong = so_luong',
        '        self.giam_gia = giam_gia',
        '',
        '    def gia_sau_giam(self):',
        '        return self.gia * (1 - self.giam_gia)',
        '',
        '    def gia_cuoi(self):',
        '        return self.gia_sau_giam() * (1 + SanPham.thue_suat)',
        '',
        '    def tong_gia_tri_kho(self):',
        '        return self.gia_cuoi() * self.so_luong',
        '',
        '',
        '# --- Tao san pham hop le ---',
        'but = SanPham("  But bi  ", 5000, so_luong=100, giam_gia=0.1)',
        'print(f"Ten           : \'{but.ten}\'")',
        'print(f"Gia goc       : {but.gia:,.0f} d")',
        'print(f"Sau giam 10%  : {but.gia_sau_giam():,.0f} d")',
        'print(f"Gia cuoi (VAT): {but.gia_cuoi():,.0f} d")',
        'print(f"Gia tri kho   : {but.tong_gia_tri_kho():,.0f} d")',
        '',
        'print()',
        '',
        '# --- Thu tao san pham khong hop le ---',
        'for ten, gia in [("", 1000), ("Vo", -5000)]:',
        '    try:',
        '        SanPham(ten, gia)',
        '    except ValueError as loi:',
        '        print(f"Bi chan: {loi}")',
      ], {
        output: [
          "Ten           : 'But bi'",
          'Gia goc       : 5,000 d',
          'Sau giam 10%  : 4,500 d',
          'Gia cuoi (VAT): 4,860 d',
          'Gia tri kho   : 486,000 d',
          '',
          'Bi chan: Ten san pham khong duoc de trong',
          'Bi chan: Gia khong duoc am, nhan duoc -5000',
        ].join('\n'),
        notes: [
          '`ten.strip()` dọn khoảng trắng thừa ngay trong constructor — dữ liệu vào là đã sạch.',
          '`except ValueError as loi` bắt lỗi và lấy thông điệp — kết hợp giữa buổi 27 khoá Cơ Bản và buổi này.',
          'Thông điệp lỗi có kèm giá trị nhận được (`nhan duoc -5000`) giúp gỡ lỗi nhanh hơn nhiều.',
        ],
      }),
      playground('Sân chơi: constructor an toàn', [
        'Viết lớp `TaiKhoanNganHang` với `__init__` kiểm tra:',
        '',
        '- Tên chủ tài khoản không rỗng',
        '- Số dư ban đầu không âm (mặc định 0)',
        '- Mã PIN đúng 4 chữ số',
        '',
        'Thử tạo cả tài khoản hợp lệ lẫn không hợp lệ để kiểm chứng.',
      ], [
        'class TaiKhoanNganHang:',
        '    def __init__(self, chu_the, so_du=0, pin="0000"):',
        '        # Them cac phep kiem tra o day',
        '        self.chu_the = chu_the',
        '        self.so_du = so_du',
        '        self.pin = pin',
        '',
        '',
        '# Thu nghiem',
        'a = TaiKhoanNganHang("Lan", 100000, "1234")',
        'print(a.chu_the, a.so_du)',
        '',
        'for du_lieu in [("", 0, "1234"), ("Minh", -100, "1234"), ("Hoa", 0, "12")]:',
        '    try:',
        '        TaiKhoanNganHang(*du_lieu)',
        '        print(f"{du_lieu} -> tao duoc (co the thieu kiem tra)")',
        '    except (ValueError, TypeError) as loi:',
        '        print(f"{du_lieu} -> bi chan: {loi}")',
      ], 'Cả ba trường hợp không hợp lệ đều bị constructor chặn lại.'),
      challenge({
        slug: 'p-nc-b03-lop-hoc-sinh-init',
        title: 'Lớp HocSinh với constructor',
        statement: [
          'Viết lớp `HocSinh` với `__init__(self, ho_ten, tuoi, diem=None)`:',
          '',
          '**Kiểm tra trong constructor:**',
          '',
          '- `ho_ten` rỗng hoặc chỉ có khoảng trắng → `raise ValueError`',
          '- `tuoi` nhỏ hơn 5 hoặc lớn hơn 100 → `raise ValueError`',
          '',
          '**Gán thuộc tính:**',
          '',
          '- `self.ho_ten` — đã cắt khoảng trắng thừa bằng `.strip()`',
          '- `self.tuoi`',
          '- `self.diem` — nếu `diem` là `None` thì gán danh sách **rỗng mới**, ngược lại gán chính nó',
          '',
          '**Phương thức:**',
          '',
          '- `them_diem(self, d)` — thêm `d` vào `self.diem`',
          '- `trung_binh(self)` — trung bình các điểm; trả về `0.0` nếu chưa có điểm nào',
          '- `xep_loai(self)` — `"Gioi"` từ 8.0, `"Kha"` từ 6.5, `"Trung binh"` từ 5.0, ' +
            'còn lại `"Can co gang"`',
        ].join('\n'),
        hints: [
          'Dùng `if not ho_ten or not ho_ten.strip():` để bắt cả chuỗi rỗng lẫn chuỗi toàn khoảng trắng.',
          'Với `diem`: `self.diem = diem if diem is not None else []` — tuyệt đối không dùng `diem=[]`.',
          '`trung_binh` phải kiểm tra danh sách rỗng trước khi chia, tránh ZeroDivisionError.',
        ],
        starterCode: [
          'class HocSinh:',
          '    def __init__(self, ho_ten, tuoi, diem=None):',
          '        # Kiem tra du lieu',
          '        pass',
          '',
          '    def them_diem(self, d):',
          '        pass',
          '',
          '    def trung_binh(self):',
          '        pass',
          '',
          '    def xep_loai(self):',
          '        pass',
        ].join('\n'),
        solutionCode: [
          'class HocSinh:',
          '    def __init__(self, ho_ten, tuoi, diem=None):',
          '        if not ho_ten or not ho_ten.strip():',
          '            raise ValueError("Ho ten khong duoc de trong")',
          '        if tuoi < 5 or tuoi > 100:',
          '            raise ValueError("Tuoi phai tu 5 den 100")',
          '',
          '        self.ho_ten = ho_ten.strip()',
          '        self.tuoi = tuoi',
          '        self.diem = diem if diem is not None else []',
          '',
          '    def them_diem(self, d):',
          '        self.diem.append(d)',
          '',
          '    def trung_binh(self):',
          '        if not self.diem:',
          '            return 0.0',
          '        return sum(self.diem) / len(self.diem)',
          '',
          '    def xep_loai(self):',
          '        tb = self.trung_binh()',
          '        if tb >= 8:',
          '            return "Gioi"',
          '        if tb >= 6.5:',
          '            return "Kha"',
          '        if tb >= 5:',
          '            return "Trung binh"',
          '        return "Can co gang"',
        ].join('\n'),
        tier: 'CO_BAN',
        judgeMode: 'UNIT_TEST',
        runtimeImage: 'PY_TEST',
        unitTestCode: [
          'import pytest',
          '',
          'from solution import HocSinh',
          '',
          '',
          'def test_khoi_tao_co_ban():',
          '    hs = HocSinh("Lan", 14)',
          '    assert hs.ho_ten == "Lan"',
          '    assert hs.tuoi == 14',
          '    assert hs.diem == []',
          '',
          '',
          'def test_cat_khoang_trang():',
          '    hs = HocSinh("   Minh   ", 15)',
          '    assert hs.ho_ten == "Minh"',
          '',
          '',
          'def test_ten_rong_bi_chan():',
          '    with pytest.raises(ValueError):',
          '        HocSinh("", 14)',
          '    with pytest.raises(ValueError):',
          '        HocSinh("   ", 14)',
          '',
          '',
          'def test_tuoi_khong_hop_le_bi_chan():',
          '    with pytest.raises(ValueError):',
          '        HocSinh("Lan", 4)',
          '    with pytest.raises(ValueError):',
          '        HocSinh("Lan", 101)',
          '',
          '',
          'def test_danh_sach_diem_khong_dung_chung():',
          '    """Bay kinh dien: diem=[] lam moi doi tuong dung chung mot danh sach."""',
          '    a = HocSinh("A", 14)',
          '    b = HocSinh("B", 15)',
          '    a.them_diem(10)',
          '    assert a.diem == [10]',
          '    assert b.diem == []',
          '',
          '',
          'def test_diem_truyen_vao():',
          '    hs = HocSinh("Lan", 14, [8, 9, 7])',
          '    assert hs.diem == [8, 9, 7]',
          '',
          '',
          'def test_trung_binh_rong():',
          '    assert HocSinh("Lan", 14).trung_binh() == 0.0',
          '',
          '',
          'def test_trung_binh():',
          '    hs = HocSinh("Lan", 14, [8, 9, 7])',
          '    assert abs(hs.trung_binh() - 8.0) < 1e-9',
          '',
          '',
          '@pytest.mark.parametrize(',
          '    "diem, mong_doi",',
          '    [',
          '        ([10, 10], "Gioi"),',
          '        ([8], "Gioi"),',
          '        ([7], "Kha"),',
          '        ([6.5], "Kha"),',
          '        ([5], "Trung binh"),',
          '        ([4.9], "Can co gang"),',
          '        ([0], "Can co gang"),',
          '    ],',
          ')',
          'def test_xep_loai(diem, mong_doi):',
          '    assert HocSinh("X", 14, list(diem)).xep_loai() == mong_doi',
        ].join('\n'),
        totalPoints: 100,
      }),
    ],
  },

  {
    order: 4,
    slug: 'nc-b04-destructor-vong-doi',
    title: 'Destructor `__del__` & vòng đời đối tượng',
    summary:
      'Đối tượng sinh ra, sống, rồi biến mất. Hiểu vòng đời giúp em quản lý tài nguyên đúng cách — ' +
      'và biết vì sao `__del__` ít được dùng trong thực tế.',
    objectives: [
      'Mô tả được vòng đời của một đối tượng Python',
      'Viết `__del__` và biết khi nào nó được gọi',
      'Giải thích cơ chế đếm tham chiếu',
      'Dùng context manager (`with`) thay cho `__del__` khi quản lý tài nguyên',
    ],
    difficulty: 4,
    status: 'REQUIRED',
    teacherNotes:
      'Dạy `__del__` theo yêu cầu chương trình, nhưng phải nói rõ nó không đáng tin cậy và ' +
      'thực tế nên dùng `with`. Đây là bài học về "biết công cụ VÀ biết giới hạn của nó".',
    blocks: [
      theory('Vòng đời của một đối tượng', [
        '```',
        '  hs = HocSinh("Lan", 14)',
        '        │',
        '        ├─► 1. __new__   Python cap phat bo nho  (em hiem khi dung)',
        '        ├─► 2. __init__  Khoi tao thuoc tinh     (em viet cai nay)',
        '        │',
        '        ├─── 3. SONG: doi tuong duoc su dung',
        '        │',
        '        └─► 4. __del__   Truoc khi bi huy        (tu dong, khong doan duoc luc nao)',
        '```',
        '',
        'Python huỷ đối tượng bằng cơ chế **đếm tham chiếu**: mỗi đối tượng đếm xem có bao nhiêu ' +
          'cái tên đang trỏ tới nó. Khi con số đó về 0, đối tượng bị huỷ.',
        '',
        '```python',
        'a = HocSinh("Lan", 14)   # so tham chieu = 1',
        'b = a                     # so tham chieu = 2  (khong sao chep!)',
        'del a                     # so tham chieu = 1  (van song)',
        'del b                     # so tham chieu = 0  -> __del__ chay',
        '```',
        '',
        'Chú ý `b = a` **không sao chép** đối tượng — đúng như bẫy danh sách ở buổi 21 khoá Cơ Bản.',
        '',
        '`del a` chỉ **xoá cái tên** `a`, không xoá đối tượng. Đối tượng chỉ chết khi không còn ' +
          'cái tên nào trỏ tới nó.',
      ], [
        '`__init__` khi sinh, `__del__` trước khi chết',
        'Python đếm tham chiếu: về 0 thì huỷ',
        '`del a` xoá cái tên, không xoá đối tượng',
      ]),
      theory('Vì sao thực tế ít dùng `__del__`', [
        '`__del__` có trong chương trình học, nhưng lập trình viên thật rất hiếm khi dùng. Ba lý do:',
        '',
        '**1. Không biết chạy lúc nào.** Nếu đối tượng còn được tham chiếu ở đâu đó, `__del__` ' +
          'có thể chạy rất muộn, hoặc không chạy khi chương trình kết thúc đột ngột.',
        '',
        '**2. Tham chiếu vòng.** Hai đối tượng trỏ vào nhau thì số tham chiếu không bao giờ về 0:',
        '',
        '```python',
        'a.ban = b',
        'b.ban = a       # ca hai deu khong bao gio ve 0',
        '```',
        '',
        '**3. Lỗi bên trong `__del__` bị nuốt.** Python chỉ in cảnh báo rồi bỏ qua, rất khó gỡ lỗi.',
        '',
        '**Giải pháp thay thế: context manager.** Dùng `with` để bảo đảm dọn dẹp đúng lúc:',
        '',
        '```python',
        'class KetNoi:',
        '    def __init__(self, ten):',
        '        self.ten = ten',
        '',
        '    def __enter__(self):',
        '        print(f"Mo ket noi {self.ten}")',
        '        return self',
        '',
        '    def __exit__(self, loai_loi, gia_tri_loi, vet):',
        '        print(f"Dong ket noi {self.ten}")',
        '        return False        # False = khong nuot loi',
        '',
        '',
        'with KetNoi("CSDL") as kn:',
        '    print("Dang lam viec...")',
        '# __exit__ chay o day, CHAC CHAN, ke ca khi co loi',
        '```',
        '',
        'Đây chính là `with open(...)` mà em đã dùng ở buổi 28 khoá Cơ Bản — giờ em biết nó hoạt động ' +
          'thế nào bên trong.',
        '',
        '📌 **Quy tắc thực hành:** cần dọn dẹp tài nguyên (tệp, kết nối mạng, khoá) thì dùng `with`. ' +
          'Chỉ dùng `__del__` để ghi log hoặc đếm, không bao giờ cho việc quan trọng.',
      ], [
        '`__del__` không đoán được thời điểm chạy',
        'Tham chiếu vòng khiến `__del__` không bao giờ chạy',
        'Dùng `with` (`__enter__`/`__exit__`) cho mọi việc dọn dẹp quan trọng',
      ]),
      example('Vòng đời và context manager cạnh nhau', 'Chạy thử và đọc kỹ thứ tự các dòng in ra.', [
        'class TaiNguyen:',
        '    """Minh hoa __del__ - KHONG dung cho viec quan trong."""',
        '',
        '    so_dang_song = 0',
        '',
        '    def __init__(self, ten):',
        '        self.ten = ten',
        '        TaiNguyen.so_dang_song += 1',
        '        print(f"  [+] Tao {self.ten} (dang song: {TaiNguyen.so_dang_song})")',
        '',
        '    def __del__(self):',
        '        TaiNguyen.so_dang_song -= 1',
        '        print(f"  [-] Huy {self.ten} (dang song: {TaiNguyen.so_dang_song})")',
        '',
        '',
        'class KetNoiAnToan:',
        '    """Cach DUNG de quan ly tai nguyen."""',
        '',
        '    def __init__(self, ten):',
        '        self.ten = ten',
        '',
        '    def __enter__(self):',
        '        print(f"  >>> MO {self.ten}")',
        '        return self',
        '',
        '    def __exit__(self, loai_loi, gia_tri_loi, vet):',
        '        print(f"  <<< DONG {self.ten}")',
        '        return False',
        '',
        '    def lam_viec(self):',
        '        print(f"      dang lam viec voi {self.ten}")',
        '',
        '',
        'print("=== 1. Vong doi co ban ===")',
        'a = TaiNguyen("A")',
        'b = a                       # KHONG sao chep, chi them mot cai ten',
        'print("  del a (van con b tro toi)")',
        'del a',
        'print("  del b")',
        'del b',
        '',
        'print()',
        'print("=== 2. Doi tuong trong pham vi ham ===")',
        '',
        '',
        'def tao_tam():',
        '    t = TaiNguyen("Tam")',
        '    print("      trong ham")',
        '    # het ham -> t het pham vi -> tu dong huy',
        '',
        '',
        'tao_tam()',
        'print("  da ra khoi ham")',
        '',
        'print()',
        'print("=== 3. Context manager: dong CHAC CHAN ===")',
        'try:',
        '    with KetNoiAnToan("CSDL") as kn:',
        '        kn.lam_viec()',
        '        raise RuntimeError("Co su co!")',
        'except RuntimeError as loi:',
        '    print(f"  Bat duoc loi: {loi}")',
        'print("  -> Ket noi VAN duoc dong du co loi")',
      ], {
        output: [
          '=== 1. Vong doi co ban ===',
          '  [+] Tao A (dang song: 1)',
          '  del a (van con b tro toi)',
          '  del b',
          '  [-] Huy A (dang song: 0)',
          '',
          '=== 2. Doi tuong trong pham vi ham ===',
          '  [+] Tao Tam (dang song: 1)',
          '      trong ham',
          '  [-] Huy Tam (dang song: 0)',
          '  da ra khoi ham',
          '',
          '=== 3. Context manager: dong CHAC CHAN ===',
          '  >>> MO CSDL',
          '      dang lam viec voi CSDL',
          '  <<< DONG CSDL',
          '  Bat duoc loi: Co su co!',
          '  -> Ket noi VAN duoc dong du co loi',
        ].join('\n'),
        notes: [
          'Phần 1: `del a` KHÔNG gọi `__del__` vì `b` vẫn trỏ tới đối tượng. Chỉ `del b` mới huỷ.',
          'Phần 2: biến cục bộ tự huỷ khi hàm kết thúc — không cần `del`.',
          'Phần 3: `__exit__` chạy TRƯỚC cả khối `except`. Đó là lý do `with` đáng tin cậy hơn `__del__`.',
        ],
      }),
      playground('Sân chơi: đếm đối tượng đang sống', [
        'Viết lớp `NguoiChoi` đếm số người chơi đang online:',
        '',
        '- `__init__` tăng bộ đếm',
        '- `__del__` giảm bộ đếm',
        '- Phương thức lớp `so_online()` trả về bộ đếm',
        '',
        'Sau đó thử tạo tham chiếu vòng (`a.ban = b; b.ban = a`) rồi `del` cả hai — ' +
          'quan sát `__del__` **không** chạy. Đó chính là hạn chế đã nói.',
      ], [
        'class NguoiChoi:',
        '    dang_online = 0',
        '',
        '    def __init__(self, ten):',
        '        self.ten = ten',
        '        NguoiChoi.dang_online += 1',
        '        print(f"{ten} vao game. Online: {NguoiChoi.dang_online}")',
        '',
        '    def __del__(self):',
        '        NguoiChoi.dang_online -= 1',
        '        print(f"{self.ten} thoat. Online: {NguoiChoi.dang_online}")',
        '',
        '',
        'a = NguoiChoi("Lan")',
        'b = NguoiChoi("Minh")',
        'del a',
        '',
        'print("--- Thu tham chieu vong ---")',
        'x = NguoiChoi("X")',
        'y = NguoiChoi("Y")',
        'x.ban = y',
        'y.ban = x',
        'del x',
        'del y',
        'print("Da del ca hai - __del__ co chay khong?")',
      ], 'Quan sát được `__del__` không chạy với tham chiếu vòng và giải thích được vì sao.'),
      challenge({
        slug: 'p-nc-b04-quan-ly-tai-nguyen',
        title: 'Lớp quản lý tài nguyên có context manager',
        statement: [
          'Viết lớp `QuanLyTep` mô phỏng việc mở/đóng tệp (không cần đụng tới tệp thật):',
          '',
          '**`__init__(self, ten_tep)`** — gán `self.ten_tep`, đặt `self.dang_mo = False`, ' +
            'và `self.nhat_ky = []` (danh sách rỗng **mới** cho mỗi đối tượng).',
          '',
          '**`__enter__(self)`** — đặt `self.dang_mo = True`, thêm `"MO"` vào `nhat_ky`, ' +
            'và **trả về `self`**.',
          '',
          '**`__exit__(self, loai_loi, gia_tri_loi, vet)`** — đặt `self.dang_mo = False`, ' +
            'thêm `"DONG"` vào `nhat_ky`, và trả về `False`.',
          '',
          '**`ghi(self, noi_dung)`** — nếu chưa mở thì `raise RuntimeError`; nếu đã mở thì thêm ' +
            '`f"GHI:{noi_dung}"` vào `nhat_ky`.',
          '',
          '**Thuộc tính của lớp `so_lan_mo`** — bắt đầu từ `0`, tăng thêm 1 mỗi lần `__enter__` chạy.',
        ].join('\n'),
        hints: [
          '`__enter__` **bắt buộc** phải `return self`, nếu không thì `with ... as x` sẽ cho `x = None`.',
          '`__exit__` nhận đúng ba tham số ngoài `self`, dù em không dùng tới chúng.',
          'Tăng biến của lớp bằng `QuanLyTep.so_lan_mo += 1`, không phải `self.so_lan_mo += 1`.',
        ],
        starterCode: [
          'class QuanLyTep:',
          '    so_lan_mo = 0',
          '',
          '    def __init__(self, ten_tep):',
          '        pass',
          '',
          '    def __enter__(self):',
          '        pass',
          '',
          '    def __exit__(self, loai_loi, gia_tri_loi, vet):',
          '        pass',
          '',
          '    def ghi(self, noi_dung):',
          '        pass',
        ].join('\n'),
        solutionCode: [
          'class QuanLyTep:',
          '    so_lan_mo = 0',
          '',
          '    def __init__(self, ten_tep):',
          '        self.ten_tep = ten_tep',
          '        self.dang_mo = False',
          '        self.nhat_ky = []',
          '',
          '    def __enter__(self):',
          '        self.dang_mo = True',
          '        self.nhat_ky.append("MO")',
          '        QuanLyTep.so_lan_mo += 1',
          '        return self',
          '',
          '    def __exit__(self, loai_loi, gia_tri_loi, vet):',
          '        self.dang_mo = False',
          '        self.nhat_ky.append("DONG")',
          '        return False',
          '',
          '    def ghi(self, noi_dung):',
          '        if not self.dang_mo:',
          '            raise RuntimeError("Tep chua duoc mo")',
          '        self.nhat_ky.append(f"GHI:{noi_dung}")',
        ].join('\n'),
        tier: 'THU_THACH',
        judgeMode: 'UNIT_TEST',
        runtimeImage: 'PY_TEST',
        unitTestCode: [
          'import pytest',
          '',
          'from solution import QuanLyTep',
          '',
          '',
          'def test_khoi_tao():',
          '    q = QuanLyTep("a.txt")',
          '    assert q.ten_tep == "a.txt"',
          '    assert q.dang_mo is False',
          '    assert q.nhat_ky == []',
          '',
          '',
          'def test_nhat_ky_khong_dung_chung():',
          '    a = QuanLyTep("a.txt")',
          '    b = QuanLyTep("b.txt")',
          '    with a:',
          '        a.ghi("x")',
          '    assert b.nhat_ky == []',
          '',
          '',
          'def test_enter_tra_ve_self():',
          '    q = QuanLyTep("a.txt")',
          '    with q as ket_qua:',
          '        assert ket_qua is q',
          '',
          '',
          'def test_luong_mo_ghi_dong():',
          '    q = QuanLyTep("a.txt")',
          '    with q:',
          '        q.ghi("xin chao")',
          '        q.ghi("tam biet")',
          '    assert q.nhat_ky == ["MO", "GHI:xin chao", "GHI:tam biet", "DONG"]',
          '    assert q.dang_mo is False',
          '',
          '',
          'def test_ghi_khi_chua_mo():',
          '    q = QuanLyTep("a.txt")',
          '    with pytest.raises(RuntimeError):',
          '        q.ghi("khong duoc phep")',
          '',
          '',
          'def test_van_dong_khi_co_loi():',
          '    q = QuanLyTep("a.txt")',
          '    with pytest.raises(ValueError):',
          '        with q:',
          '            q.ghi("truoc loi")',
          '            raise ValueError("su co")',
          '    assert q.dang_mo is False',
          '    assert q.nhat_ky[-1] == "DONG"',
          '',
          '',
          'def test_dem_so_lan_mo():',
          '    truoc = QuanLyTep.so_lan_mo',
          '    with QuanLyTep("1.txt"):',
          '        pass',
          '    with QuanLyTep("2.txt"):',
          '        pass',
          '    assert QuanLyTep.so_lan_mo == truoc + 2',
        ].join('\n'),
        totalPoints: 100,
      }),
    ],
  },

  {
    order: 5,
    slug: 'nc-b05-dong-goi-encapsulation',
    title: 'Đóng gói (Encapsulation): private, getter/setter, `@property`',
    objectives: [
      'Giải thích được ý nghĩa của đóng gói',
      'Dùng quy ước `_` và `__` để đánh dấu thuộc tính nội bộ',
      'Viết getter và setter có kiểm tra dữ liệu',
      'Dùng `@property` để viết code vừa an toàn vừa gọn',
    ],
    summary:
      'Không phải thứ gì bên trong đối tượng cũng nên cho bên ngoài sờ vào. Đóng gói là cách ' +
      'bảo vệ dữ liệu khỏi bị thay đổi sai.',
    difficulty: 4,
    status: 'REQUIRED',
    teacherNotes:
      'Nhấn mạnh Python dùng QUY ƯỚC chứ không cưỡng chế như Java. `@property` là công cụ ' +
      'quan trọng nhất buổi này.',
    blocks: [
      theory('Vì sao cần đóng gói', [
        'Với lớp `TaiKhoan` ở buổi 2, không gì ngăn được việc này:',
        '',
        '```python',
        'a = TaiKhoan("Lan", 1000)',
        'a.so_du = -999999999      # ??? So du am!',
        'a.so_du = "rat nhieu"     # ??? So du la chuoi!',
        '```',
        '',
        'Mọi phép kiểm tra em viết trong `nap()` và `rut()` đều vô nghĩa nếu ai cũng gán thẳng ' +
          'vào thuộc tính.',
        '',
        '**Đóng gói** giải quyết bằng cách: giấu dữ liệu bên trong, chỉ cho phép truy cập qua ' +
          'những cửa có kiểm soát.',
        '',
        '| Quy ước | Ý nghĩa | Python có cưỡng chế không? |',
        '|---|---|---|',
        '| `so_du` | Công khai, ai cũng dùng được | — |',
        '| `_so_du` | *"Nội bộ, đừng đụng vào"* | **Không** — chỉ là quy ước |',
        '| `__so_du` | Riêng tư, bị đổi tên khi biên dịch | Gần như có |',
        '',
        '```python',
        'class TaiKhoan:',
        '    def __init__(self, so_du):',
        '        self.__so_du = so_du      # hai gach duoi',
        '',
        '',
        'a = TaiKhoan(1000)',
        'print(a.__so_du)      # AttributeError!',
        'print(a._TaiKhoan__so_du)   # 1000 - van truy cap duoc neu co y',
        '```',
        '',
        'Hai gạch dưới kích hoạt cơ chế **đổi tên** (name mangling): `__so_du` trở thành ' +
          '`_TaiKhoan__so_du`. Không phải bảo mật tuyệt đối, nhưng đủ để không ai vô tình chạm vào.',
        '',
        '📌 **Triết lý Python:** *"Chúng ta đều là người lớn ở đây."* Python tin lập trình viên ' +
          'tôn trọng quy ước, thay vì dựng rào cản cứng như một số ngôn ngữ khác.',
      ], [
        '`_ten` = quy ước "nội bộ", Python không cưỡng chế',
        '`__ten` = đổi tên thành `_TenLop__ten`, khó chạm nhầm',
        'Python dùng quy ước, không dùng rào cản cứng',
      ]),
      theory('`@property` — getter/setter kiểu Python', [
        'Cách truyền thống (kiểu Java) rất dài dòng:',
        '',
        '```python',
        'class TaiKhoan:',
        '    def get_so_du(self):',
        '        return self.__so_du',
        '',
        '    def set_so_du(self, gia_tri):',
        '        if gia_tri < 0:',
        '            raise ValueError("So du khong duoc am")',
        '        self.__so_du = gia_tri',
        '',
        '',
        'a.set_so_du(a.get_so_du() + 100)     # rat dai dong',
        '```',
        '',
        'Python có cách gọn hơn nhiều — **`@property`**:',
        '',
        '```python',
        'class TaiKhoan:',
        '    def __init__(self, so_du=0):',
        '        self.so_du = so_du        # goi luon setter ben duoi!',
        '',
        '    @property',
        '    def so_du(self):              # GETTER',
        '        return self.__so_du',
        '',
        '    @so_du.setter',
        '    def so_du(self, gia_tri):     # SETTER',
        '        if not isinstance(gia_tri, (int, float)):',
        '            raise TypeError("So du phai la so")',
        '        if gia_tri < 0:',
        '            raise ValueError("So du khong duoc am")',
        '        self.__so_du = gia_tri',
        '',
        '',
        'a = TaiKhoan(1000)',
        'print(a.so_du)        # 1000  - trong nhu thuoc tinh thuong',
        'a.so_du = 2000        # nhung THUC RA goi setter co kiem tra',
        'a.so_du = -5          # ValueError!',
        '```',
        '',
        '**Điểm mạnh nhất của `@property`:** code bên ngoài viết y hệt như với thuộc tính thường, ' +
          'nên em có thể **thêm kiểm tra vào sau** mà không phải sửa một dòng nào ở nơi sử dụng.',
        '',
        '**Thuộc tính chỉ đọc** — chỉ viết getter, không viết setter:',
        '',
        '```python',
        '@property',
        'def tuoi(self):',
        '    return date.today().year - self.nam_sinh',
        '',
        '# a.tuoi = 20  ->  AttributeError: can\'t set attribute',
        '```',
        '',
        'Thuộc tính tính toán như `tuoi` không nên gán được — nó phải luôn suy ra từ `nam_sinh`.',
      ], [
        '`@property` cho getter, `@ten.setter` cho setter',
        'Bên ngoài dùng như thuộc tính thường, bên trong vẫn kiểm tra',
        'Chỉ có getter = thuộc tính chỉ đọc',
      ]),
      example('Tài khoản được bảo vệ đầy đủ', 'So sánh trước và sau khi đóng gói.', [
        'class TaiKhoan:',
        '    """Tai khoan co dong goi day du."""',
        '',
        '    def __init__(self, chu_the, so_du=0):',
        '        self.__chu_the = chu_the',
        '        self.__lich_su = []',
        '        self.so_du = so_du            # di qua setter -> duoc kiem tra',
        '',
        '    # ===== chu_the: CHI DOC =====',
        '    @property',
        '    def chu_the(self):',
        '        return self.__chu_the',
        '',
        '    # ===== so_du: doc + ghi CO KIEM TRA =====',
        '    @property',
        '    def so_du(self):',
        '        return self.__so_du',
        '',
        '    @so_du.setter',
        '    def so_du(self, gia_tri):',
        '        if not isinstance(gia_tri, (int, float)):',
        '            raise TypeError(f"So du phai la so, nhan duoc {type(gia_tri).__name__}")',
        '        if gia_tri < 0:',
        '            raise ValueError(f"So du khong duoc am, nhan duoc {gia_tri}")',
        '        self.__so_du = gia_tri',
        '',
        '    # ===== lich_su: CHI DOC, tra ve BAN SAO =====',
        '    @property',
        '    def lich_su(self):',
        '        return self.__lich_su.copy()',
        '',
        '    # ===== Thuoc tinh TINH TOAN =====',
        '    @property',
        '    def hang(self):',
        '        if self.__so_du >= 10_000_000:',
        '            return "Kim cuong"',
        '        if self.__so_du >= 1_000_000:',
        '            return "Vang"',
        '        return "Thuong"',
        '',
        '    def nap(self, tien):',
        '        self.so_du = self.so_du + tien      # di qua setter',
        '        self.__lich_su.append(f"Nap {tien:,}")',
        '',
        '',
        'a = TaiKhoan("Lan", 500_000)',
        'print(f"Chu the: {a.chu_the}   Hang: {a.hang}")',
        '',
        'a.nap(2_000_000)',
        'print(f"Sau khi nap: {a.so_du:,} - Hang: {a.hang}")',
        '',
        'print()',
        'print("--- Thu pha hoai ---")',
        '',
        'for mo_ta, ham in [',
        '    ("a.so_du = -100", lambda: setattr(a, "so_du", -100)),',
        '    ("a.so_du = \'nhieu\'", lambda: setattr(a, "so_du", "nhieu")),',
        '    ("a.chu_the = \'Hacker\'", lambda: setattr(a, "chu_the", "Hacker")),',
        '    ("a.hang = \'Kim cuong\'", lambda: setattr(a, "hang", "Kim cuong")),',
        ']:',
        '    try:',
        '        ham()',
        '        print(f"  {mo_ta:<26} -> THANH CONG (co lo hong!)")',
        '    except (ValueError, TypeError, AttributeError) as loi:',
        '        print(f"  {mo_ta:<26} -> bi chan: {type(loi).__name__}")',
        '',
        'print()',
        '# Lich su tra ve ban sao nen sua ban sao khong anh huong ban goc',
        'ban_sao = a.lich_su',
        'ban_sao.append("GIAO DICH GIA")',
        'print(f"Lich su that: {a.lich_su}")',
      ], {
        output: [
          'Chu the: Lan   Hang: Thuong',
          'Sau khi nap: 2,500,000 - Hang: Vang',
          '',
          '--- Thu pha hoai ---',
          '  a.so_du = -100             -> bi chan: ValueError',
          "  a.so_du = 'nhieu'          -> bi chan: TypeError",
          "  a.chu_the = 'Hacker'       -> bi chan: AttributeError",
          "  a.hang = 'Kim cuong'       -> bi chan: AttributeError",
          '',
          "Lich su that: ['Nap 2,000,000']",
        ].join('\n'),
        notes: [
          '`hang` là thuộc tính tính toán — luôn đúng vì nó suy ra từ số dư, không lưu riêng.',
          '`lich_su` trả về `.copy()` nên bên ngoài không sửa được lịch sử thật. Rất quan trọng với dữ liệu nhạy cảm.',
          '`self.so_du = so_du` trong `__init__` cố ý đi qua setter, nên dữ liệu ban đầu cũng được kiểm tra.',
        ],
      }),
      playground('Sân chơi: nhiệt độ hai đơn vị', [
        'Viết lớp `NhietDo` lưu **duy nhất** giá trị Celsius nhưng cho phép đọc/ghi cả Fahrenheit:',
        '',
        '- `celsius` — property có setter, chặn giá trị dưới −273.15 (độ không tuyệt đối)',
        '- `fahrenheit` — property tính từ celsius, setter đổi ngược lại',
        '',
        'Công thức: `F = C × 9/5 + 32` và `C = (F − 32) × 5/9`.',
        '',
        'Kiểm chứng: đặt `t.fahrenheit = 212` thì `t.celsius` phải bằng 100.',
      ], [
        'class NhietDo:',
        '    def __init__(self, celsius=0):',
        '        self.celsius = celsius',
        '',
        '    @property',
        '    def celsius(self):',
        '        return self.__celsius',
        '',
        '    @celsius.setter',
        '    def celsius(self, gia_tri):',
        '        if gia_tri < -273.15:',
        '            raise ValueError("Duoi do khong tuyet doi")',
        '        self.__celsius = gia_tri',
        '',
        '    @property',
        '    def fahrenheit(self):',
        '        # Viet cong thuc o day',
        '        pass',
        '',
        '    # Them @fahrenheit.setter o day',
        '',
        '',
        't = NhietDo(100)',
        'print(t.fahrenheit)      # mong doi 212.0',
      ], 'Đổi được cả hai chiều và chặn được nhiệt độ dưới độ không tuyệt đối.'),
      challenge({
        slug: 'p-nc-b05-dong-goi-san-pham',
        title: 'Đóng gói lớp SanPham',
        statement: [
          'Viết lớp `SanPham` với đóng gói đầy đủ:',
          '',
          '**`__init__(self, ma, ten, gia, so_luong=0)`** — gán `ma` vào thuộc tính nội bộ ' +
            '`self.__ma`; `ten`, `gia`, `so_luong` phải đi **qua setter**.',
          '',
          '**`ma`** — property **chỉ đọc**.',
          '',
          '**`ten`** — property đọc/ghi; setter `raise ValueError` nếu chuỗi rỗng hoặc chỉ có ' +
            'khoảng trắng, và lưu bản đã `.strip()`.',
          '',
          '**`gia`** — property đọc/ghi; setter `raise TypeError` nếu không phải `int`/`float`, ' +
            '`raise ValueError` nếu âm.',
          '',
          '**`so_luong`** — property đọc/ghi; setter `raise ValueError` nếu âm.',
          '',
          '**`tong_gia_tri`** — property **chỉ đọc**, trả về `gia * so_luong`.',
          '',
          '**`con_hang`** — property **chỉ đọc**, trả về `True` khi `so_luong > 0`.',
          '',
          'Lưu ý: `isinstance(True, int)` là `True` trong Python, nhưng bài này không kiểm tra ' +
            'trường hợp đó — cứ dùng `isinstance(gia_tri, (int, float))`.',
        ].join('\n'),
        hints: [
          'Trong `__init__`, gán `self.ten = ten` (không phải `self.__ten = ten`) để đi qua setter.',
          'Property chỉ đọc = chỉ viết `@property`, tuyệt đối không viết `@ten.setter`.',
          '`tong_gia_tri` và `con_hang` không lưu gì cả, chúng tính lại mỗi lần được đọc.',
        ],
        starterCode: [
          'class SanPham:',
          '    def __init__(self, ma, ten, gia, so_luong=0):',
          '        self.__ma = ma',
          '        self.ten = ten',
          '        self.gia = gia',
          '        self.so_luong = so_luong',
          '',
          '    @property',
          '    def ma(self):',
          '        pass',
          '',
          '    @property',
          '    def ten(self):',
          '        pass',
          '',
          '    @ten.setter',
          '    def ten(self, gia_tri):',
          '        pass',
          '',
          '    # Them gia, so_luong, tong_gia_tri, con_hang',
        ].join('\n'),
        solutionCode: [
          'class SanPham:',
          '    def __init__(self, ma, ten, gia, so_luong=0):',
          '        self.__ma = ma',
          '        self.ten = ten',
          '        self.gia = gia',
          '        self.so_luong = so_luong',
          '',
          '    @property',
          '    def ma(self):',
          '        return self.__ma',
          '',
          '    @property',
          '    def ten(self):',
          '        return self.__ten',
          '',
          '    @ten.setter',
          '    def ten(self, gia_tri):',
          '        if not gia_tri or not gia_tri.strip():',
          '            raise ValueError("Ten khong duoc de trong")',
          '        self.__ten = gia_tri.strip()',
          '',
          '    @property',
          '    def gia(self):',
          '        return self.__gia',
          '',
          '    @gia.setter',
          '    def gia(self, gia_tri):',
          '        if not isinstance(gia_tri, (int, float)):',
          '            raise TypeError("Gia phai la so")',
          '        if gia_tri < 0:',
          '            raise ValueError("Gia khong duoc am")',
          '        self.__gia = gia_tri',
          '',
          '    @property',
          '    def so_luong(self):',
          '        return self.__so_luong',
          '',
          '    @so_luong.setter',
          '    def so_luong(self, gia_tri):',
          '        if gia_tri < 0:',
          '            raise ValueError("So luong khong duoc am")',
          '        self.__so_luong = gia_tri',
          '',
          '    @property',
          '    def tong_gia_tri(self):',
          '        return self.__gia * self.__so_luong',
          '',
          '    @property',
          '    def con_hang(self):',
          '        return self.__so_luong > 0',
        ].join('\n'),
        tier: 'THU_THACH',
        judgeMode: 'UNIT_TEST',
        runtimeImage: 'PY_TEST',
        unitTestCode: [
          'import pytest',
          '',
          'from solution import SanPham',
          '',
          '',
          'def tao():',
          '    return SanPham("SP01", "But bi", 5000, 10)',
          '',
          '',
          'def test_doc_thuoc_tinh():',
          '    sp = tao()',
          '    assert sp.ma == "SP01"',
          '    assert sp.ten == "But bi"',
          '    assert sp.gia == 5000',
          '    assert sp.so_luong == 10',
          '',
          '',
          'def test_ma_chi_doc():',
          '    sp = tao()',
          '    with pytest.raises(AttributeError):',
          '        sp.ma = "SP99"',
          '',
          '',
          'def test_ten_cat_khoang_trang():',
          '    sp = SanPham("X", "   Vo o ly   ", 100)',
          '    assert sp.ten == "Vo o ly"',
          '',
          '',
          'def test_ten_rong_bi_chan():',
          '    sp = tao()',
          '    with pytest.raises(ValueError):',
          '        sp.ten = ""',
          '    with pytest.raises(ValueError):',
          '        sp.ten = "    "',
          '',
          '',
          'def test_gia_sai_kieu():',
          '    sp = tao()',
          '    with pytest.raises(TypeError):',
          '        sp.gia = "nhieu tien"',
          '',
          '',
          'def test_gia_am():',
          '    sp = tao()',
          '    with pytest.raises(ValueError):',
          '        sp.gia = -1',
          '',
          '',
          'def test_so_luong_am():',
          '    sp = tao()',
          '    with pytest.raises(ValueError):',
          '        sp.so_luong = -5',
          '',
          '',
          'def test_kiem_tra_ngay_trong_init():',
          '    with pytest.raises(ValueError):',
          '        SanPham("X", "Ten", -100)',
          '    with pytest.raises(ValueError):',
          '        SanPham("X", "", 100)',
          '',
          '',
          'def test_tong_gia_tri():',
          '    sp = tao()',
          '    assert sp.tong_gia_tri == 50000',
          '    sp.so_luong = 3',
          '    assert sp.tong_gia_tri == 15000',
          '',
          '',
          'def test_tong_gia_tri_chi_doc():',
          '    sp = tao()',
          '    with pytest.raises(AttributeError):',
          '        sp.tong_gia_tri = 999',
          '',
          '',
          'def test_con_hang():',
          '    sp = tao()',
          '    assert sp.con_hang is True',
          '    sp.so_luong = 0',
          '    assert sp.con_hang is False',
          '',
          '',
          'def test_thuoc_tinh_that_su_duoc_giau():',
          '    sp = tao()',
          '    assert not hasattr(sp, "gia_tri_cong_khai")',
          '    assert "__gia" not in [t for t in vars(sp) if not t.startswith("_SanPham")]',
        ].join('\n'),
        totalPoints: 100,
      }),
    ],
  },
];
