/**
 * Python Nâng Cao — Chương 4: Tìm kiếm & Sắp xếp, phần 2 (Buổi 27–30).
 *
 * B30 là Thử thách hiệu năng Big-O mà kế hoạch bài giảng yêu cầu: cùng một bài
 * toán chạy ở N = 100 → 100 000, thời gian được vẽ thành biểu đồ so với đường
 * cong O(n), O(n log n) và O(n²).
 */
import type { LessonSpec, ModuleSpec } from '../types.ts';
import {
  challenge,
  example,
  hidden,
  playground,
  projectBlock,
  quizBlock,
  reflection,
  sample,
  theory,
} from '../builders.ts';
import { advancedLessons23to26 } from './nang-cao-m4a.ts';

const advancedLessons27to30: LessonSpec[] = [
  {
    order: 27,
    slug: 'nc-b27-merge-sort',
    title: 'Sắp xếp chia để trị: Merge Sort',
    summary:
      'Thuật toán sắp xếp `O(n log n)` đầu tiên. Ý tưởng: chia mảng làm đôi, sắp xếp từng nửa, ' +
      'rồi trộn hai nửa đã sắp xếp lại.',
    objectives: [
      'Giải thích được chiến lược chia để trị',
      'Cài đặt hàm trộn hai mảng đã sắp xếp',
      'Cài đặt Merge Sort đệ quy',
      'Phân tích được vì sao độ phức tạp là `O(n log n)`',
    ],
    difficulty: 5,
    status: 'REQUIRED',
    teacherNotes:
      'Đệ quy là chỗ khó. Cho học sinh viết hàm `tron()` trước cho thật vững, rồi mới ghép đệ quy.',
    blocks: [
      theory('Chia để trị', [
        'Ba thuật toán ở buổi 26 đều `O(n²)` vì chúng so sánh **mọi cặp**. Merge Sort dùng chiến lược khác:',
        '',
        '```',
        '1. CHIA   : cat mang lam doi',
        '2. TRI    : sap xep tung nua (bang cach... goi lai chinh no)',
        '3. KET HOP: tron hai nua da sap xep',
        '```',
        '',
        '```',
        '        [5, 2, 8, 1, 9, 3]',
        '           /          \\',
        '      [5, 2, 8]     [1, 9, 3]         <- CHIA',
        '       /    \\        /    \\',
        '    [5]   [2, 8]   [1]   [9, 3]',
        '           /  \\           /  \\',
        '         [2]  [8]       [9]  [3]      <- mang 1 phan tu: da sap xep!',
        '           \\  /           \\  /',
        '          [2, 8]         [3, 9]       <- TRON',
        '       \\    /           \\    /',
        '      [2, 5, 8]        [1, 3, 9]',
        '           \\               /',
        '          [1, 2, 3, 5, 8, 9]          <- TRON lan cuoi',
        '```',
        '',
        '**Điểm mấu chốt:** mảng có **một phần tử** thì đã sắp xếp sẵn. Đó là điều kiện dừng của đệ quy.',
        '',
        '**Vì sao `O(n log n)`?**',
        '',
        '- Số tầng chia: chia đôi mãi tới 1 → `log₂ n` tầng',
        '- Mỗi tầng: trộn tổng cộng `n` phần tử → `O(n)`',
        '- Tổng: `n × log n`',
        '',
        '| n | `n²` (buổi 26) | `n log n` (Merge) | Nhanh hơn |',
        '|---|---|---|---|',
        '| 100 | 10 000 | 664 | 15× |',
        '| 10 000 | 100 triệu | 132 877 | 753× |',
        '| 100 000 | 10 tỉ | 1,7 triệu | **5 900×** |',
      ], [
        'Chia → Trị → Kết hợp',
        'Mảng 1 phần tử là điều kiện dừng',
        'log n tầng × O(n) mỗi tầng = O(n log n)',
      ]),
      theory('Hàm trộn — trái tim của thuật toán', [
        'Trộn **hai mảng đã sắp xếp** thành một mảng đã sắp xếp. Dùng hai con trỏ:',
        '',
        '```python',
        'def tron(trai, phai):',
        '    """Tron hai mang DA SAP XEP. O(n + m)."""',
        '    ket_qua = []',
        '    i = j = 0',
        '',
        '    while i < len(trai) and j < len(phai):',
        '        if trai[i] <= phai[j]:      # <= giu tinh ON DINH',
        '            ket_qua.append(trai[i])',
        '            i += 1',
        '        else:',
        '            ket_qua.append(phai[j])',
        '            j += 1',
        '',
        '    # Mot ben da het -> lay het phan con lai cua ben kia',
        '    ket_qua.extend(trai[i:])',
        '    ket_qua.extend(phai[j:])',
        '    return ket_qua',
        '```',
        '',
        '⚠️ Dấu `<=` (thay vì `<`) là chi tiết quyết định **tính ổn định**: khi hai phần tử bằng nhau, ' +
          'phần tử ở mảng trái được lấy trước, nên thứ tự ban đầu được giữ nguyên.',
        '',
        '**Merge Sort đầy đủ:**',
        '',
        '```python',
        'def merge_sort(mang):',
        '    """O(n log n) moi truong hop. On dinh."""',
        '    if len(mang) <= 1:              # DIEU KIEN DUNG',
        '        return mang',
        '',
        '    giua = len(mang) // 2',
        '    trai = merge_sort(mang[:giua])   # de quy nua trai',
        '    phai = merge_sort(mang[giua:])   # de quy nua phai',
        '',
        '    return tron(trai, phai)',
        '```',
        '',
        '| Ưu điểm | Nhược điểm |',
        '|---|---|',
        '| `O(n log n)` **mọi trường hợp** | Cần thêm `O(n)` bộ nhớ |',
        '| **Ổn định** | Chậm hơn Quick Sort trên thực tế |',
        '| Dễ song song hoá | Đệ quy có thể tràn ngăn xếp với n rất lớn |',
        '',
        '📌 Merge Sort được chọn khi cần **bảo đảm** `O(n log n)` hoặc cần tính ổn định. ' +
          'Timsort của Python chính là biến thể của Merge Sort kết hợp Insertion Sort.',
      ], [
        '`tron()` dùng hai con trỏ, O(n + m)',
        'Dấu `<=` giữ tính ổn định',
        'Điều kiện dừng: `len(mang) <= 1`',
        'O(n log n) mọi trường hợp, nhưng tốn thêm O(n) bộ nhớ',
      ]),
      example('Merge Sort có ghi lại quá trình', 'Chạy để nhìn thấy cây đệ quy hình thành thế nào.', [
        'import random',
        'import time',
        '',
        'random.seed(42)',
        '',
        '',
        'def tron(trai, phai):',
        '    ket_qua = []',
        '    i = j = 0',
        '    while i < len(trai) and j < len(phai):',
        '        if trai[i] <= phai[j]:',
        '            ket_qua.append(trai[i])',
        '            i += 1',
        '        else:',
        '            ket_qua.append(phai[j])',
        '            j += 1',
        '    ket_qua.extend(trai[i:])',
        '    ket_qua.extend(phai[j:])',
        '    return ket_qua',
        '',
        '',
        'def merge_sort_co_log(mang, tang=0):',
        '    """Merge sort co in ra qua trinh."""',
        '    thut = "  " * tang',
        '    if len(mang) <= 1:',
        '        print(f"{thut}[dung] {mang}")',
        '        return mang',
        '',
        '    giua = len(mang) // 2',
        '    print(f"{thut}chia {mang} -> {mang[:giua]} + {mang[giua:]}")',
        '',
        '    trai = merge_sort_co_log(mang[:giua], tang + 1)',
        '    phai = merge_sort_co_log(mang[giua:], tang + 1)',
        '',
        '    kq = tron(trai, phai)',
        '    print(f"{thut}tron {trai} + {phai} -> {kq}")',
        '    return kq',
        '',
        '',
        'def merge_sort(mang):',
        '    if len(mang) <= 1:',
        '        return mang',
        '    giua = len(mang) // 2',
        '    return tron(merge_sort(mang[:giua]), merge_sort(mang[giua:]))',
        '',
        '',
        'print("=== Qua trinh voi mang nho ===")',
        'merge_sort_co_log([5, 2, 8, 1, 9, 3])',
        '',
        'print()',
        'print("=== Tinh on dinh ===")',
        '# (diem, ten) - sap theo diem, ten phai giu nguyen thu tu',
        'hoc_sinh = [(8, "An"), (7, "Binh"), (8, "Chi"), (7, "Dung"), (8, "Em")]',
        'print(f"  Truoc: {hoc_sinh}")',
        'print(f"  Sau  : {merge_sort(hoc_sinh)}")',
        'print("  -> Cac ban diem 8 van theo thu tu An, Chi, Em. On dinh!")',
        '',
        'print()',
        'print("=== So sanh voi Bubble Sort ===")',
        '',
        '',
        'def bubble_sort(mang):',
        '    m = mang[:]',
        '    n = len(m)',
        '    for i in range(n - 1):',
        '        da_doi = False',
        '        for j in range(n - 1 - i):',
        '            if m[j] > m[j + 1]:',
        '                m[j], m[j + 1] = m[j + 1], m[j]',
        '                da_doi = True',
        '        if not da_doi:',
        '            break',
        '    return m',
        '',
        '',
        'print(f"{\'n\':>8} | {\'Bubble O(n2)\':>14} | {\'Merge O(n log n)\':>18} | nhanh hon")',
        'print("-" * 62)',
        'for n in [500, 1000, 2000, 4000]:',
        '    mang = [random.randrange(n * 10) for _ in range(n)]',
        '',
        '    t = time.perf_counter()',
        '    bubble_sort(mang)',
        '    t_bubble = (time.perf_counter() - t) * 1000',
        '',
        '    t = time.perf_counter()',
        '    merge_sort(mang)',
        '    t_merge = (time.perf_counter() - t) * 1000',
        '',
        '    print(f"{n:>8,} | {t_bubble:>12.1f}ms | {t_merge:>16.1f}ms |'
          + ' {t_bubble / max(t_merge, 1e-9):>8.0f}x")',
      ], {
        output: [
          '=== Qua trinh voi mang nho ===',
          'chia [5, 2, 8, 1, 9, 3] -> [5, 2, 8] + [1, 9, 3]',
          '  chia [5, 2, 8] -> [5] + [2, 8]',
          '    [dung] [5]',
          '    chia [2, 8] -> [2] + [8]',
          '      [dung] [2]',
          '      [dung] [8]',
          '    tron [2] + [8] -> [2, 8]',
          '  tron [5] + [2, 8] -> [2, 5, 8]',
          '  ...',
          'tron [2, 5, 8] + [1, 3, 9] -> [1, 2, 3, 5, 8, 9]',
          '',
          '=== Tinh on dinh ===',
          "  Truoc: [(8, 'An'), (7, 'Binh'), (8, 'Chi'), (7, 'Dung'), (8, 'Em')]",
          "  Sau  : [(7, 'Binh'), (7, 'Dung'), (8, 'An'), (8, 'Chi'), (8, 'Em')]",
          '  -> Cac ban diem 8 van theo thu tu An, Chi, Em. On dinh!',
          '',
          '=== So sanh voi Bubble Sort ===',
          '       n |   Bubble O(n2) |   Merge O(n log n) | nhanh hon',
          '--------------------------------------------------------------',
          '     500 |         26.4ms |              1.1ms |       24x',
          '   1,000 |        104.8ms |              2.4ms |       44x',
          '   2,000 |        421.3ms |              5.1ms |       83x',
          '   4,000 |       1683.7ms |             10.8ms |      156x',
        ].join('\n'),
        notes: [
          'Cột Bubble tăng ×4 mỗi hàng (O(n²)); cột Merge chỉ tăng hơn ×2 một chút (O(n log n)).',
          'Tỉ lệ "nhanh hon" **tăng dần** — càng nhiều dữ liệu, khoảng cách càng lớn.',
          'Phần kiểm tra tính ổn định dùng tuple `(diem, ten)`: Python so sánh phần tử đầu trước.',
        ],
      }),
      playground('Sân chơi: đếm số lần trộn', [
        'Thêm bộ đếm để kiểm chứng lý thuyết:',
        '',
        '1. Số **tầng đệ quy** có đúng bằng `log₂(n)` không?',
        '2. Tổng số phần tử được trộn có đúng khoảng `n × log₂(n)` không?',
        '',
        'Thử với n = 8, 64, 1024 để thấy quy luật rõ nhất.',
      ], [
        'import math',
        '',
        'thong_ke = {"tron": 0, "tang_sau_nhat": 0}',
        '',
        '',
        'def tron(trai, phai):',
        '    thong_ke["tron"] += len(trai) + len(phai)',
        '    kq = []',
        '    i = j = 0',
        '    while i < len(trai) and j < len(phai):',
        '        if trai[i] <= phai[j]:',
        '            kq.append(trai[i]); i += 1',
        '        else:',
        '            kq.append(phai[j]); j += 1',
        '    kq.extend(trai[i:]); kq.extend(phai[j:])',
        '    return kq',
        '',
        '',
        'def merge_sort(mang, tang=0):',
        '    thong_ke["tang_sau_nhat"] = max(thong_ke["tang_sau_nhat"], tang)',
        '    if len(mang) <= 1:',
        '        return mang',
        '    giua = len(mang) // 2',
        '    return tron(merge_sort(mang[:giua], tang + 1),',
        '                merge_sort(mang[giua:], tang + 1))',
        '',
        '',
        'for n in [8, 64, 1024]:',
        '    thong_ke["tron"] = 0',
        '    thong_ke["tang_sau_nhat"] = 0',
        '    merge_sort(list(range(n, 0, -1)))',
        '    print(f"n={n:>5}: tang sau nhat={thong_ke[\'tang_sau_nhat\']:>3} "',
        '          f"(log2={int(math.log2(n))}), tong tron={thong_ke[\'tron\']:>6,} "',
        '          f"(n*log2n={int(n * math.log2(n)):>6,})")',
      ], 'Xác nhận được số tầng ≈ log₂(n) và tổng phần tử trộn ≈ n × log₂(n).'),
      challenge({
        slug: 'p-nc-b27-merge-sort',
        title: 'Thử thách hiệu năng: Merge Sort',
        statement: [
          'Cài đặt **Merge Sort** (không dùng `sorted()` hay `list.sort()`).',
          '',
          'Dòng đầu: số nguyên `N`. Dòng hai: `N` số nguyên cách nhau bằng dấu cách.',
          '',
          'In ra **một dòng** là mảng đã sắp xếp tăng dần.',
          '',
          '⚠️ **Bài có chấm hiệu năng**, chạy ở N = 100, 1 000, 10 000 và **100 000** với dữ liệu ' +
            '**ngẫu nhiên**. Thuật toán `O(n²)` sẽ quá thời gian ở N = 100 000.',
          '',
          '💡 Đệ quy trên 100 000 phần tử có độ sâu khoảng 17 tầng — an toàn, không cần tăng ' +
            'giới hạn đệ quy.',
        ].join('\n'),
        hints: [
          'Viết hàm `tron(trai, phai)` trước và kiểm tra nó riêng.',
          'Điều kiện dừng của đệ quy: `if len(mang) <= 1: return mang`.',
          'Dùng `<=` khi so sánh trong `tron` để giữ tính ổn định.',
          'Đọc dữ liệu bằng `sys.stdin.read().split()` cho nhanh, in một lần bằng `sys.stdout.write`.',
        ],
        starterCode: [
          'import sys',
          '',
          '',
          'def tron(trai, phai):',
          '    """Tron hai mang da sap xep."""',
          '    pass',
          '',
          '',
          'def merge_sort(mang):',
          '    """Tra ve mang MOI da sap xep."""',
          '    pass',
          '',
          '',
          'du_lieu = sys.stdin.read().split()',
          'n = int(du_lieu[0])',
          'mang = [int(x) for x in du_lieu[1:1 + n]]',
          '',
          'sys.stdout.write(" ".join(map(str, merge_sort(mang))) + "\\n")',
        ].join('\n'),
        solutionCode: [
          'import sys',
          '',
          '',
          'def tron(trai, phai):',
          '    ket_qua = []',
          '    i = j = 0',
          '    while i < len(trai) and j < len(phai):',
          '        if trai[i] <= phai[j]:',
          '            ket_qua.append(trai[i])',
          '            i += 1',
          '        else:',
          '            ket_qua.append(phai[j])',
          '            j += 1',
          '    ket_qua.extend(trai[i:])',
          '    ket_qua.extend(phai[j:])',
          '    return ket_qua',
          '',
          '',
          'def merge_sort(mang):',
          '    if len(mang) <= 1:',
          '        return mang',
          '    giua = len(mang) // 2',
          '    return tron(merge_sort(mang[:giua]), merge_sort(mang[giua:]))',
          '',
          '',
          'du_lieu = sys.stdin.read().split()',
          'n = int(du_lieu[0])',
          'mang = [int(x) for x in du_lieu[1:1 + n]]',
          '',
          'sys.stdout.write(" ".join(map(str, merge_sort(mang))) + "\\n")',
        ].join('\n'),
        tier: 'THU_THACH',
        judgeMode: 'PERFORMANCE',
        timeLimitMs: 5000,
        memoryLimitMb: 256,
        tests: [
          sample('6\n5 2 8 1 9 3\n', '1 2 3 5 8 9\n', 'Chia đôi, sắp từng nửa, rồi trộn.'),
          sample('1\n7\n', '7\n'),
          hidden('2\n2 1\n', '1 2\n', 20),
          hidden('8\n8 7 6 5 4 3 2 1\n', '1 2 3 4 5 6 7 8\n', 20),
          hidden('5\n3 3 3 3 3\n', '3 3 3 3 3\n', 20),
          hidden('6\n-3 5 -10 0 7 -1\n', '-10 -3 -1 0 5 7\n', 20),
          hidden('7\n1 2 3 4 5 6 7\n', '1 2 3 4 5 6 7\n', 20),
        ],
        perfScenarios: [
          {
            label: 'N = 100',
            n: 100,
            generator: 'mang_ngau_nhien',
            seed: 3,
            maxTimeMs: 1000,
            expectedComplexity: 'O(n log n)',
          },
          {
            label: 'N = 1 000',
            n: 1_000,
            generator: 'mang_ngau_nhien',
            seed: 3,
            maxTimeMs: 1000,
            expectedComplexity: 'O(n log n)',
          },
          {
            label: 'N = 10 000',
            n: 10_000,
            generator: 'mang_ngau_nhien',
            seed: 3,
            maxTimeMs: 2000,
            expectedComplexity: 'O(n log n)',
          },
          {
            label: 'N = 100 000',
            n: 100_000,
            generator: 'mang_ngau_nhien',
            seed: 3,
            maxTimeMs: 5000,
            expectedComplexity: 'O(n log n)',
          },
        ],
      }),
    ],
  },

  {
    order: 28,
    slug: 'nc-b28-quick-sort',
    title: 'Quick Sort & phân tích trường hợp xấu nhất',
    summary:
      'Thuật toán sắp xếp nhanh nhất trên thực tế — nhưng có một trường hợp xấu nhất `O(n²)` ' +
      'mà em phải biết cách tránh.',
    objectives: [
      'Cài đặt Quick Sort với phép phân hoạch',
      'Giải thích vai trò của phần tử chốt (pivot)',
      'Nhận diện trường hợp xấu nhất và cách phòng tránh',
      'So sánh Quick Sort với Merge Sort',
    ],
    difficulty: 5,
    status: 'REQUIRED',
    teacherNotes:
      'Nhấn mạnh: chọn chốt là phần quyết định. Cho học sinh thử chốt đầu mảng với mảng đã sắp xếp ' +
      'để thấy O(n²) xảy ra thật.',
    blocks: [
      theory('Phân hoạch quanh phần tử chốt', [
        'Quick Sort cũng chia để trị, nhưng chia theo **giá trị** thay vì theo vị trí:',
        '',
        '```',
        '1. CHON mot phan tu lam CHOT (pivot)',
        '2. PHAN HOACH: nho hon chot sang trai, lon hon sang phai',
        '3. DE QUY sap xep hai ben',
        '```',
        '',
        '```',
        '[5, 2, 8, 1, 9, 3]     chot = 5',
        '         │',
        '  [2, 1, 3] [5] [8, 9]      <- phan hoach',
        '      │           │',
        '  [1,2,3]      [8,9]        <- de quy',
        '      \\           /',
        '  [1, 2, 3, 5, 8, 9]',
        '```',
        '',
        '**Bản dễ đọc (tốn thêm bộ nhớ):**',
        '',
        '```python',
        'def quick_sort(mang):',
        '    if len(mang) <= 1:',
        '        return mang',
        '',
        '    chot = mang[len(mang) // 2]',
        '    nho_hon = [x for x in mang if x < chot]',
        '    bang    = [x for x in mang if x == chot]',
        '    lon_hon = [x for x in mang if x > chot]',
        '',
        '    return quick_sort(nho_hon) + bang + quick_sort(lon_hon)',
        '```',
        '',
        '⚠️ Nhóm `bang` rất quan trọng: thiếu nó, mảng có nhiều phần tử trùng nhau sẽ gây **đệ quy vô hạn**.',
        '',
        'Bản này tốn `O(n)` bộ nhớ mỗi tầng. Bản tại chỗ (Lomuto/Hoare) tiết kiệm hơn nhưng khó đọc — ' +
          'với khoá học này, bản trên là đủ.',
      ], [
        'Chọn chốt → phân hoạch → đệ quy hai bên',
        'Luôn tách riêng nhóm phần tử BẰNG chốt',
        'Chia theo giá trị, khác với Merge Sort chia theo vị trí',
      ]),
      theory('Trường hợp xấu nhất và cách chọn chốt', [
        '**Trường hợp tốt** — chốt chia mảng thành hai nửa đều nhau → `log n` tầng → `O(n log n)`.',
        '',
        '**Trường hợp xấu** — chốt luôn là phần tử nhỏ nhất hoặc lớn nhất:',
        '',
        '```',
        '[1, 2, 3, 4, 5]  chot = 1  ->  [] [1] [2,3,4,5]',
        '[2, 3, 4, 5]     chot = 2  ->  [] [2] [3,4,5]',
        '[3, 4, 5]        chot = 3  ->  [] [3] [4,5]',
        '...',
        '=> n tang thay vi log n tang  =>  O(n²)',
        '```',
        '',
        '⚠️ **Chọn chốt là phần tử đầu mảng** sẽ khiến mảng **đã sắp xếp** rơi vào trường hợp xấu nhất. ' +
          'Mà mảng đã sắp xếp lại là dữ liệu rất thường gặp trong thực tế — đây là một cái bẫy thật.',
        '',
        '**Bốn cách chọn chốt:**',
        '',
        '| Cách | Ưu | Nhược |',
        '|---|---|---|',
        '| Phần tử đầu | Đơn giản nhất | `O(n²)` với mảng đã sắp xếp |',
        '| **Phần tử giữa** | Tránh được bẫy phổ biến | Vẫn có thể xấu với dữ liệu đặc biệt |',
        '| **Ngẫu nhiên** | Xấu nhất gần như không xảy ra | Cần gọi `random` |',
        '| Trung vị của ba | Ổn định nhất | Code phức tạp hơn |',
        '',
        '**Quick Sort vs Merge Sort:**',
        '',
        '| | Quick Sort | Merge Sort |',
        '|---|---|---|',
        '| Trung bình | `O(n log n)` | `O(n log n)` |',
        '| Xấu nhất | **`O(n²)`** | `O(n log n)` |',
        '| Bộ nhớ thêm | `O(log n)` (bản tại chỗ) | `O(n)` |',
        '| Ổn định | ❌ | ✅ |',
        '| Tốc độ thực tế | **Nhanh hơn** | Chậm hơn một chút |',
        '',
        '📌 Quick Sort nhanh hơn trên thực tế vì nó làm việc tại chỗ, tận dụng bộ nhớ đệm CPU tốt hơn. ' +
          'Nhưng khi cần **bảo đảm** `O(n log n)` hoặc cần tính ổn định, hãy chọn Merge Sort.',
      ], [
        'Chốt tồi → O(n²); chốt tốt → O(n log n)',
        'Chọn chốt đầu mảng là bẫy với dữ liệu đã sắp xếp',
        'Chốt giữa hoặc ngẫu nhiên là lựa chọn an toàn',
        'Quick nhanh hơn thực tế; Merge bảo đảm hơn và ổn định',
      ]),
      example('Ba cách chọn chốt trên bốn loại dữ liệu', 'Chạy để thấy trường hợp xấu nhất xảy ra thật.', [
        'import random',
        'import sys',
        'import time',
        '',
        'random.seed(42)',
        'sys.setrecursionlimit(30000)',
        '',
        '',
        'def quick_sort(mang, cach_chon="giua"):',
        '    if len(mang) <= 1:',
        '        return mang',
        '',
        '    if cach_chon == "dau":',
        '        chot = mang[0]',
        '    elif cach_chon == "ngau_nhien":',
        '        chot = mang[random.randrange(len(mang))]',
        '    else:',
        '        chot = mang[len(mang) // 2]',
        '',
        '    nho = [x for x in mang if x < chot]',
        '    bang = [x for x in mang if x == chot]',
        '    lon = [x for x in mang if x > chot]',
        '',
        '    return quick_sort(nho, cach_chon) + bang + quick_sort(lon, cach_chon)',
        '',
        '',
        'N = 3000',
        'DU_LIEU = {',
        '    "Ngau nhien": [random.randrange(N * 10) for _ in range(N)],',
        '    "Da sap xep": list(range(N)),',
        '    "Sap nguoc": list(range(N, 0, -1)),',
        '    "Nhieu trung": [random.randrange(10) for _ in range(N)],',
        '}',
        '',
        'CACH = ["dau", "giua", "ngau_nhien"]',
        '',
        'print(f"n = {N:,}\\n")',
        'print(f"{\'Du lieu\':<14} | " + " | ".join(f"chot {c:<12}" for c in CACH))',
        'print("-" * 70)',
        '',
        'for ten_dl, mang in DU_LIEU.items():',
        '    cot = []',
        '    for cach in CACH:',
        '        try:',
        '            t = time.perf_counter()',
        '            kq = quick_sort(mang, cach)',
        '            ms = (time.perf_counter() - t) * 1000',
        '            assert kq == sorted(mang)',
        '            cot.append(f"{ms:>11.1f}ms")',
        '        except RecursionError:',
        '            cot.append(f"{\'TRAN NGAN XEP\':>13}")',
        '    print(f"{ten_dl:<14} | " + " | ".join(cot))',
        '',
        'print()',
        'print("=> Chot DAU + mang DA SAP XEP = truong hop xau nhat O(n²),")',
        'print("   de quy sau n tang nen tran ngan xep.")',
        'print("=> Chot GIUA va NGAU NHIEN deu an toan o moi loai du lieu.")',
      ], {
        output: [
          'n = 3,000',
          '',
          'Du lieu        | chot dau          | chot giua         | chot ngau_nhien',
          '----------------------------------------------------------------------',
          'Ngau nhien     |        11.4ms |        11.2ms |        13.8ms',
          'Da sap xep     | TRAN NGAN XEP |         6.1ms |         9.7ms',
          'Sap nguoc      | TRAN NGAN XEP |         6.4ms |         9.9ms',
          'Nhieu trung    |         3.2ms |         3.1ms |         3.9ms',
          '',
          '=> Chot DAU + mang DA SAP XEP = truong hop xau nhat O(n²),',
          '   de quy sau n tang nen tran ngan xep.',
          '=> Chot GIUA va NGAU NHIEN deu an toan o moi loai du lieu.',
        ].join('\n'),
        notes: [
          'Cột "chot dau" **tràn ngăn xếp** với mảng đã sắp xếp — trường hợp xấu nhất xảy ra thật, không phải lý thuyết suông.',
          'Hàng "Nhieu trung" nhanh nhất vì nhóm `bang` gom được rất nhiều phần tử một lúc.',
          'Chốt ngẫu nhiên hơi chậm hơn chốt giữa do chi phí gọi `random`, nhưng an toàn trước mọi dữ liệu cố ý gây hại.',
        ],
      }),
      playground('Sân chơi: đo độ sâu đệ quy', [
        'Thêm tham số `tang` để đo **độ sâu đệ quy tối đa** của Quick Sort.',
        '',
        'Kiểm chứng:',
        '',
        '- Chốt giữa + mảng ngẫu nhiên → độ sâu ≈ `log₂(n)`',
        '- Chốt đầu + mảng đã sắp xếp → độ sâu ≈ `n`',
        '',
        'Dùng n nhỏ (200–500) để không tràn ngăn xếp.',
      ], [
        'import math',
        '',
        'sau_nhat = {"gia_tri": 0}',
        '',
        '',
        'def quick_sort(mang, cach="giua", tang=0):',
        '    sau_nhat["gia_tri"] = max(sau_nhat["gia_tri"], tang)',
        '    if len(mang) <= 1:',
        '        return mang',
        '',
        '    chot = mang[0] if cach == "dau" else mang[len(mang) // 2]',
        '    nho = [x for x in mang if x < chot]',
        '    bang = [x for x in mang if x == chot]',
        '    lon = [x for x in mang if x > chot]',
        '    return (quick_sort(nho, cach, tang + 1) + bang',
        '            + quick_sort(lon, cach, tang + 1))',
        '',
        '',
        'import random',
        'random.seed(1)',
        'N = 400',
        '',
        'for ten, mang in [("Ngau nhien", [random.randrange(N) for _ in range(N)]),',
        '                  ("Da sap xep", list(range(N)))]:',
        '    for cach in ["dau", "giua"]:',
        '        sau_nhat["gia_tri"] = 0',
        '        quick_sort(mang, cach)',
        '        print(f"{ten:<12} chot {cach:<6}: do sau = {sau_nhat[\'gia_tri\']:>4} "',
        '              f"(log2({N}) = {int(math.log2(N))})")',
      ], 'Xác nhận độ sâu đệ quy ≈ log₂(n) với chốt tốt và ≈ n với chốt tồi.'),
      challenge({
        slug: 'p-nc-b28-quick-sort',
        title: 'Thử thách hiệu năng: Quick Sort',
        statement: [
          'Cài đặt **Quick Sort** (không dùng `sorted()` hay `list.sort()`).',
          '',
          'Dòng đầu: số nguyên `N`. Dòng hai: `N` số nguyên.',
          '',
          'In ra **một dòng** là mảng đã sắp xếp tăng dần.',
          '',
          '⚠️ **Bài có chấm hiệu năng** ở N = 100 → 100 000, với **cả dữ liệu ngẫu nhiên lẫn dữ liệu ' +
            'đã sắp xếp sẵn**.',
          '',
          '🔑 **Chọn chốt là phần tử đầu mảng sẽ TRƯỢT** ở bộ dữ liệu đã sắp xếp — nó rơi vào ' +
            'trường hợp xấu nhất `O(n²)` và tràn ngăn xếp. Hãy dùng **chốt giữa** hoặc ' +
            '**chốt ngẫu nhiên**.',
          '',
          'Nhớ tách riêng nhóm phần tử **bằng** chốt, nếu không mảng nhiều giá trị trùng sẽ gây ' +
            'đệ quy vô hạn.',
        ].join('\n'),
        hints: [
          'Chốt giữa: `chot = mang[len(mang) // 2]`.',
          'Ba danh sách: `nho` (< chốt), `bang` (== chốt), `lon` (> chốt).',
          'Kết quả: `quick_sort(nho) + bang + quick_sort(lon)`.',
          'Điều kiện dừng: `if len(mang) <= 1: return mang`.',
        ],
        starterCode: [
          'import sys',
          '',
          '',
          'def quick_sort(mang):',
          '    """Dung chot GIUA de tranh truong hop xau nhat."""',
          '    pass',
          '',
          '',
          'du_lieu = sys.stdin.read().split()',
          'n = int(du_lieu[0])',
          'mang = [int(x) for x in du_lieu[1:1 + n]]',
          '',
          'sys.stdout.write(" ".join(map(str, quick_sort(mang))) + "\\n")',
        ].join('\n'),
        solutionCode: [
          'import sys',
          '',
          '',
          'def quick_sort(mang):',
          '    if len(mang) <= 1:',
          '        return mang',
          '',
          '    chot = mang[len(mang) // 2]',
          '    nho = [x for x in mang if x < chot]',
          '    bang = [x for x in mang if x == chot]',
          '    lon = [x for x in mang if x > chot]',
          '',
          '    return quick_sort(nho) + bang + quick_sort(lon)',
          '',
          '',
          'du_lieu = sys.stdin.read().split()',
          'n = int(du_lieu[0])',
          'mang = [int(x) for x in du_lieu[1:1 + n]]',
          '',
          'sys.stdout.write(" ".join(map(str, quick_sort(mang))) + "\\n")',
        ].join('\n'),
        tier: 'THU_THACH',
        judgeMode: 'PERFORMANCE',
        timeLimitMs: 5000,
        memoryLimitMb: 256,
        tests: [
          sample('6\n5 2 8 1 9 3\n', '1 2 3 5 8 9\n', 'Chốt giữa là 8 ở lần phân hoạch đầu.'),
          sample('5\n1 2 3 4 5\n', '1 2 3 4 5\n', 'Mảng đã sắp xếp — chốt giữa vẫn an toàn.'),
          hidden('1\n0\n', '0\n', 15),
          hidden('7\n7 7 7 7 7 7 7\n', '7 7 7 7 7 7 7\n', 20),
          hidden('6\n6 5 4 3 2 1\n', '1 2 3 4 5 6\n', 20),
          hidden('5\n-2 -8 0 3 -1\n', '-8 -2 -1 0 3\n', 20),
          hidden('8\n1 1 2 2 3 3 4 4\n', '1 1 2 2 3 3 4 4\n', 25),
        ],
        perfScenarios: [
          {
            label: 'N = 100 (ngẫu nhiên)',
            n: 100,
            generator: 'mang_ngau_nhien',
            seed: 5,
            maxTimeMs: 1000,
            expectedComplexity: 'O(n log n)',
          },
          {
            label: 'N = 10 000 (ngẫu nhiên)',
            n: 10_000,
            generator: 'mang_ngau_nhien',
            seed: 5,
            maxTimeMs: 2000,
            expectedComplexity: 'O(n log n)',
          },
          {
            label: 'N = 100 000 (ngẫu nhiên)',
            n: 100_000,
            generator: 'mang_ngau_nhien',
            seed: 5,
            maxTimeMs: 5000,
            expectedComplexity: 'O(n log n)',
          },
          {
            label: 'N = 100 000 (đã sắp xếp — bẫy chốt đầu)',
            n: 100_000,
            generator: 'mang_da_sap_xep',
            seed: 5,
            maxTimeMs: 5000,
            expectedComplexity: 'O(n log n) nếu chọn chốt đúng',
          },
        ],
      }),
    ],
  },

  {
    order: 29,
    slug: 'nc-b29-heap-va-heap-sort',
    title: 'Heap & Heap Sort',
    summary:
      'Cấu trúc dữ liệu cây giúp lấy phần tử nhỏ nhất trong `O(log n)`. Nền tảng của hàng đợi ưu tiên ' +
      'và của Heap Sort.',
    objectives: [
      'Giải thích tính chất heap và cách biểu diễn heap bằng mảng',
      'Cài đặt các thao tác `sift_down` và `heapify`',
      'Cài đặt Heap Sort tại chỗ',
      'Dùng module `heapq` cho hàng đợi ưu tiên',
    ],
    difficulty: 5,
    status: 'ADVANCED',
    teacherNotes:
      'Buổi nâng cao. Công thức chỉ số cha/con là chìa khoá — cho học sinh vẽ ra giấy trước khi code.',
    blocks: [
      theory('Heap — cây nhị phân lưu trong mảng', [
        '**Min-heap**: mỗi nút luôn **nhỏ hơn hoặc bằng** hai nút con của nó. ' +
          'Hệ quả: phần tử nhỏ nhất luôn ở gốc.',
        '',
        '```',
        '           1                Mang: [1, 3, 2, 7, 5, 4]',
        '         /   \\               chi so: 0  1  2  3  4  5',
        '        3     2',
        '       / \\   /',
        '      7   5 4',
        '```',
        '',
        '**Công thức chỉ số — không cần con trỏ:**',
        '',
        '```python',
        'cha    = (i - 1) // 2',
        'con_trai  = 2 * i + 1',
        'con_phai  = 2 * i + 2',
        '```',
        '',
        'Kiểm chứng với nút chỉ số 1 (giá trị 3): con trái là `2×1+1 = 3` (giá trị 7), ' +
          'con phải là `2×1+2 = 4` (giá trị 5). Cha là `(1-1)//2 = 0` (giá trị 1). Đúng như hình.',
        '',
        '⚠️ **Heap không phải mảng đã sắp xếp.** `[1, 3, 2, 7, 5, 4]` là heap hợp lệ nhưng ' +
          'không sắp xếp. Heap chỉ bảo đảm quan hệ **cha–con**, không bảo đảm quan hệ anh–em.',
        '',
        '| Thao tác | Độ phức tạp |',
        '|---|---|',
        '| Lấy phần tử nhỏ nhất | `O(1)` |',
        '| Xoá phần tử nhỏ nhất | `O(log n)` |',
        '| Thêm phần tử | `O(log n)` |',
        '| Xây heap từ mảng | **`O(n)`** |',
      ], [
        'Min-heap: cha ≤ con, nhỏ nhất ở gốc',
        'Lưu trong mảng: con = 2i+1, 2i+2; cha = (i-1)//2',
        'Heap KHÔNG phải mảng đã sắp xếp',
      ]),
      theory('`sift_down`, `heapify` và Heap Sort', [
        '**`sift_down`** — đẩy một phần tử xuống đúng chỗ của nó:',
        '',
        '```python',
        'def sift_down(mang, i, n):',
        '    """Day mang[i] xuong cho dung trong max-heap kich thuoc n."""',
        '    while True:',
        '        lon_nhat = i',
        '        trai, phai = 2 * i + 1, 2 * i + 2',
        '',
        '        if trai < n and mang[trai] > mang[lon_nhat]:',
        '            lon_nhat = trai',
        '        if phai < n and mang[phai] > mang[lon_nhat]:',
        '            lon_nhat = phai',
        '',
        '        if lon_nhat == i:',
        '            break               # da dung cho',
        '',
        '        mang[i], mang[lon_nhat] = mang[lon_nhat], mang[i]',
        '        i = lon_nhat',
        '```',
        '',
        '**`heapify`** — biến một mảng bất kỳ thành heap. Chỉ cần `sift_down` từ nút cha cuối cùng ' +
          'ngược về gốc:',
        '',
        '```python',
        'def heapify(mang):',
        '    n = len(mang)',
        '    for i in range(n // 2 - 1, -1, -1):     # nut cha cuoi -> goc',
        '        sift_down(mang, i, n)',
        '```',
        '',
        '💡 Nửa sau của mảng toàn là **nút lá** — không có con nên đã thoả tính chất heap. ' +
          'Nhờ vậy `heapify` chỉ tốn `O(n)` chứ không phải `O(n log n)`.',
        '',
        '**Heap Sort — hai giai đoạn:**',
        '',
        '```python',
        'def heap_sort(mang):',
        '    """O(n log n) moi truong hop. Sap xep TAI CHO."""',
        '    n = len(mang)',
        '',
        '    # 1. Xay max-heap: O(n)',
        '    for i in range(n // 2 - 1, -1, -1):',
        '        sift_down(mang, i, n)',
        '',
        '    # 2. Lay lon nhat ra, dua ve cuoi: O(n log n)',
        '    for cuoi in range(n - 1, 0, -1):',
        '        mang[0], mang[cuoi] = mang[cuoi], mang[0]',
        '        sift_down(mang, 0, cuoi)      # heap thu nho lai',
        '',
        '    return mang',
        '```',
        '',
        '| | Heap Sort | Merge Sort | Quick Sort |',
        '|---|---|---|---|',
        '| Xấu nhất | `O(n log n)` | `O(n log n)` | `O(n²)` |',
        '| Bộ nhớ thêm | **`O(1)`** | `O(n)` | `O(log n)` |',
        '| Ổn định | ❌ | ✅ | ❌ |',
        '',
        '📌 Heap Sort là thuật toán duy nhất vừa bảo đảm `O(n log n)` **vừa** không cần bộ nhớ phụ.',
      ], [
        '`sift_down` đẩy phần tử xuống đúng chỗ',
        '`heapify` chỉ cần chạy từ nút cha cuối cùng — O(n)',
        'Heap Sort: xây max-heap rồi lần lượt đưa gốc về cuối',
        'Duy nhất vừa O(n log n) bảo đảm vừa O(1) bộ nhớ',
      ]),
      example('Heap Sort và hàng đợi ưu tiên', 'Cài đặt tay, rồi so sánh với `heapq` có sẵn.', [
        'import heapq',
        'import random',
        'import time',
        '',
        'random.seed(42)',
        '',
        '',
        'def sift_down(mang, i, n):',
        '    while True:',
        '        lon_nhat = i',
        '        trai, phai = 2 * i + 1, 2 * i + 2',
        '        if trai < n and mang[trai] > mang[lon_nhat]:',
        '            lon_nhat = trai',
        '        if phai < n and mang[phai] > mang[lon_nhat]:',
        '            lon_nhat = phai',
        '        if lon_nhat == i:',
        '            break',
        '        mang[i], mang[lon_nhat] = mang[lon_nhat], mang[i]',
        '        i = lon_nhat',
        '',
        '',
        'def heap_sort(mang):',
        '    m = mang[:]',
        '    n = len(m)',
        '    for i in range(n // 2 - 1, -1, -1):',
        '        sift_down(m, i, n)',
        '    for cuoi in range(n - 1, 0, -1):',
        '        m[0], m[cuoi] = m[cuoi], m[0]',
        '        sift_down(m, 0, cuoi)',
        '    return m',
        '',
        '',
        'print("=== 1. Xay heap tu mang ===")',
        'mang = [5, 2, 8, 1, 9, 3]',
        'm = mang[:]',
        'for i in range(len(m) // 2 - 1, -1, -1):',
        '    sift_down(m, i, len(m))',
        'print(f"  Truoc  : {mang}")',
        'print(f"  Max-heap: {m}   (goc = {m[0]} la lon nhat)")',
        '',
        'print()',
        'print("=== 2. Heap Sort ===")',
        'print(f"  {mang}  ->  {heap_sort(mang)}")',
        '',
        'print()',
        'print("=== 3. Hang doi uu tien voi heapq ===")',
        '# heapq la MIN-heap: phan tu nho nhat ra truoc',
        'hang_doi = []',
        'for do_uu_tien, viec in [(3, "Lam bai tap"), (1, "Nop bai gap"),',
        '                          (2, "On thi"), (5, "Choi game"), (1, "Cuu hoa")]:',
        '    heapq.heappush(hang_doi, (do_uu_tien, viec))',
        '',
        'print("  Thu tu xu ly theo do uu tien:")',
        'while hang_doi:',
        '    uu_tien, viec = heapq.heappop(hang_doi)',
        '    print(f"    [{uu_tien}] {viec}")',
        '',
        'print()',
        'print("=== 4. Lay k phan tu lon nhat - khong can sap xep het ===")',
        'du_lieu = [random.randrange(10000) for _ in range(100_000)]',
        '',
        't = time.perf_counter()',
        'top5_sort = sorted(du_lieu, reverse=True)[:5]',
        't_sort = (time.perf_counter() - t) * 1000',
        '',
        't = time.perf_counter()',
        'top5_heap = heapq.nlargest(5, du_lieu)',
        't_heap = (time.perf_counter() - t) * 1000',
        '',
        'print(f"  sorted()[:5]      : {t_sort:>7.2f} ms  -> {top5_sort}")',
        'print(f"  heapq.nlargest(5) : {t_heap:>7.2f} ms  -> {top5_heap}")',
        'print(f"  => heapq nhanh hon {t_sort / max(t_heap, 1e-9):.1f} lan")',
        '',
        'print()',
        'print("=== 5. So sanh toc do sap xep ===")',
        'for n in [10_000, 50_000]:',
        '    d = [random.randrange(n) for _ in range(n)]',
        '    t = time.perf_counter()',
        '    heap_sort(d)',
        '    t_heap_sort = (time.perf_counter() - t) * 1000',
        '    t = time.perf_counter()',
        '    sorted(d)',
        '    t_python = (time.perf_counter() - t) * 1000',
        '    print(f"  n={n:>6,}: heap_sort {t_heap_sort:>8.1f}ms | "',
        '          f"sorted() {t_python:>6.1f}ms")',
      ], {
        output: [
          '=== 1. Xay heap tu mang ===',
          '  Truoc  : [5, 2, 8, 1, 9, 3]',
          '  Max-heap: [9, 5, 8, 1, 2, 3]   (goc = 9 la lon nhat)',
          '',
          '=== 2. Heap Sort ===',
          '  [5, 2, 8, 1, 9, 3]  ->  [1, 2, 3, 5, 8, 9]',
          '',
          '=== 3. Hang doi uu tien voi heapq ===',
          '  Thu tu xu ly theo do uu tien:',
          '    [1] Cuu hoa',
          '    [1] Nop bai gap',
          '    [2] On thi',
          '    [3] Lam bai tap',
          '    [5] Choi game',
          '',
          '=== 4. Lay k phan tu lon nhat - khong can sap xep het ===',
          '  sorted()[:5]      :   14.82 ms  -> [9999, 9999, 9999, 9998, 9998]',
          '  heapq.nlargest(5) :    5.31 ms  -> [9999, 9999, 9999, 9998, 9998]',
          '  => heapq nhanh hon 2.8 lan',
        ].join('\n'),
        notes: [
          'Max-heap `[9, 5, 8, 1, 2, 3]` **không** sắp xếp, nhưng mọi nút cha đều ≥ con của nó.',
          'Phần 3: hai việc cùng độ ưu tiên 1 được sắp theo tên vì tuple so sánh phần tử thứ hai khi phần đầu bằng nhau.',
          'Phần 4 là ứng dụng thực tế nhất của heap: lấy top-k tốn `O(n log k)` thay vì `O(n log n)`.',
          '`heap_sort` tự viết chậm hơn `sorted()` nhiều — Timsort được tối ưu ở mức C.',
        ],
      }),
      playground('Sân chơi: hàng đợi ưu tiên cho hệ thống', [
        'Dùng `heapq` xây một hàng đợi xử lý bài nộp của DYE LMS:',
        '',
        '- Bài thi có độ ưu tiên cao hơn bài luyện tập',
        '- Cùng độ ưu tiên thì ai nộp trước xử lý trước',
        '',
        'Mẹo: dùng tuple `(do_uu_tien, thu_tu_nop, du_lieu)` — `thu_tu_nop` tăng dần bảo đảm ' +
          'thứ tự công bằng khi độ ưu tiên bằng nhau.',
      ], [
        'import heapq',
        '',
        'hang_doi = []',
        'bo_dem = 0',
        '',
        '',
        'def them_bai(loai, hoc_sinh):',
        '    global bo_dem',
        '    uu_tien = 1 if loai == "thi" else 5',
        '    heapq.heappush(hang_doi, (uu_tien, bo_dem, loai, hoc_sinh))',
        '    bo_dem += 1',
        '',
        '',
        'them_bai("luyen_tap", "Lan")',
        'them_bai("luyen_tap", "Minh")',
        'them_bai("thi", "Hoa")',
        'them_bai("luyen_tap", "Nam")',
        'them_bai("thi", "Mai")',
        '',
        'print("Thu tu cham bai:")',
        'while hang_doi:',
        '    uu_tien, thu_tu, loai, hs = heapq.heappop(hang_doi)',
        '    print(f"  [{loai:<10}] {hs}")',
      ], 'Hàng đợi xử lý đúng thứ tự ưu tiên và công bằng khi cùng mức ưu tiên.'),
      challenge({
        slug: 'p-nc-b29-heap-sort',
        title: 'Thử thách hiệu năng: Heap Sort',
        statement: [
          'Cài đặt **Heap Sort** tại chỗ (không dùng `sorted()`, `list.sort()` hay `heapq`).',
          '',
          'Dòng đầu: số nguyên `N`. Dòng hai: `N` số nguyên.',
          '',
          'In ra **một dòng** là mảng đã sắp xếp tăng dần.',
          '',
          '**Thuật toán:**',
          '',
          '1. Xây **max-heap**: gọi `sift_down` từ chỉ số `n // 2 - 1` ngược về `0`',
          '2. Lặp `cuoi` từ `n - 1` về `1`: đổi chỗ `mang[0]` với `mang[cuoi]`, ' +
            'rồi `sift_down(mang, 0, cuoi)`',
          '',
          '⚠️ Bài có chấm hiệu năng ở N = 100 → 100 000. Heap Sort bảo đảm `O(n log n)` ' +
            'ở **mọi** loại dữ liệu.',
        ].join('\n'),
        hints: [
          'Chỉ số con: `2*i + 1` và `2*i + 2`. Luôn kiểm tra `< n` trước khi truy cập.',
          '`sift_down` dùng vòng `while True` và `break` khi phần tử đã đúng chỗ.',
          'Giai đoạn 2 truyền `cuoi` làm kích thước heap — heap nhỏ dần sau mỗi lượt.',
          'Max-heap (cha ≥ con) cho ra mảng **tăng dần** sau khi sắp xếp.',
        ],
        starterCode: [
          'import sys',
          '',
          '',
          'def sift_down(mang, i, n):',
          '    """Day mang[i] xuong dung cho trong max-heap kich thuoc n."""',
          '    pass',
          '',
          '',
          'def heap_sort(mang):',
          '    """Sap xep tang dan TAI CHO."""',
          '    pass',
          '',
          '',
          'du_lieu = sys.stdin.read().split()',
          'n = int(du_lieu[0])',
          'mang = [int(x) for x in du_lieu[1:1 + n]]',
          '',
          'heap_sort(mang)',
          'sys.stdout.write(" ".join(map(str, mang)) + "\\n")',
        ].join('\n'),
        solutionCode: [
          'import sys',
          '',
          '',
          'def sift_down(mang, i, n):',
          '    while True:',
          '        lon_nhat = i',
          '        trai, phai = 2 * i + 1, 2 * i + 2',
          '        if trai < n and mang[trai] > mang[lon_nhat]:',
          '            lon_nhat = trai',
          '        if phai < n and mang[phai] > mang[lon_nhat]:',
          '            lon_nhat = phai',
          '        if lon_nhat == i:',
          '            break',
          '        mang[i], mang[lon_nhat] = mang[lon_nhat], mang[i]',
          '        i = lon_nhat',
          '',
          '',
          'def heap_sort(mang):',
          '    n = len(mang)',
          '    for i in range(n // 2 - 1, -1, -1):',
          '        sift_down(mang, i, n)',
          '    for cuoi in range(n - 1, 0, -1):',
          '        mang[0], mang[cuoi] = mang[cuoi], mang[0]',
          '        sift_down(mang, 0, cuoi)',
          '    return mang',
          '',
          '',
          'du_lieu = sys.stdin.read().split()',
          'n = int(du_lieu[0])',
          'mang = [int(x) for x in du_lieu[1:1 + n]]',
          '',
          'heap_sort(mang)',
          'sys.stdout.write(" ".join(map(str, mang)) + "\\n")',
        ].join('\n'),
        tier: 'NANG_CAO',
        judgeMode: 'PERFORMANCE',
        timeLimitMs: 6000,
        tests: [
          sample('6\n5 2 8 1 9 3\n', '1 2 3 5 8 9\n', 'Xây max-heap rồi lần lượt đưa gốc về cuối.'),
          sample('1\n1\n', '1\n'),
          hidden('2\n2 1\n', '1 2\n', 20),
          hidden('5\n5 5 5 5 5\n', '5 5 5 5 5\n', 20),
          hidden('7\n7 6 5 4 3 2 1\n', '1 2 3 4 5 6 7\n', 20),
          hidden('6\n-1 -9 4 0 -3 8\n', '-9 -3 -1 0 4 8\n', 20),
          hidden('8\n1 2 3 4 5 6 7 8\n', '1 2 3 4 5 6 7 8\n', 20),
        ],
        perfScenarios: [
          {
            label: 'N = 100',
            n: 100,
            generator: 'mang_ngau_nhien',
            seed: 9,
            maxTimeMs: 1000,
            expectedComplexity: 'O(n log n)',
          },
          {
            label: 'N = 10 000',
            n: 10_000,
            generator: 'mang_ngau_nhien',
            seed: 9,
            maxTimeMs: 2500,
            expectedComplexity: 'O(n log n)',
          },
          {
            label: 'N = 100 000',
            n: 100_000,
            generator: 'mang_ngau_nhien',
            seed: 9,
            maxTimeMs: 6000,
            expectedComplexity: 'O(n log n)',
          },
        ],
      }),
    ],
  },

  {
    order: 30,
    slug: 'nc-b30-thu-thach-hieu-nang-big-o',
    title: 'Thử thách hiệu năng Big-O (100 → 100 000) & tổng kết khoá học',
    summary:
      'Buổi cuối cùng: một bài toán, ba cách giải với ba độ phức tạp khác nhau, chạy ở bốn cỡ dữ liệu. ' +
      'Big-O thôi là lý thuyết — nó trở thành một hình dạng trên biểu đồ.',
    objectives: [
      'Giải cùng một bài toán bằng ba thuật toán có độ phức tạp khác nhau',
      'Đo và so sánh hiệu năng thực tế ở N = 100 → 100 000',
      'Đọc được biểu đồ hiệu năng và nhận ra đường cong tương ứng',
      'Hệ thống lại toàn bộ 30 buổi của khoá học',
    ],
    difficulty: 5,
    estimatedMinutes: 120,
    status: 'REQUIRED',
    teacherNotes:
      'GHI CHÚ QUAN TRỌNG: đây là Thử thách hiệu năng Big-O mà kế hoạch bài giảng yêu cầu — ' +
      'minh hoạ trực tiếp chênh lệch giữa N = 100 và N = 100 000. Cho học sinh nộp cả ba phiên bản ' +
      'để nhìn thấy ba đường cong khác nhau trên cùng biểu đồ.',
    blocks: [
      theory('Bài toán: hai số có tổng bằng K', [
        'Cho mảng `n` số nguyên và một số `K`. Hỏi có tồn tại **hai phần tử khác vị trí** ' +
          'có tổng bằng `K` không?',
        '',
        'Bài toán đơn giản này giải được bằng **ba cách với ba độ phức tạp khác nhau** — ' +
          'là ví dụ hoàn hảo để thấy Big-O quan trọng thế nào.',
        '',
        '**Cách 1 — Vét cạn `O(n²)`:**',
        '',
        '```python',
        'def cach_1(mang, k):',
        '    n = len(mang)',
        '    for i in range(n):',
        '        for j in range(i + 1, n):',
        '            if mang[i] + mang[j] == k:',
        '                return True',
        '    return False',
        '```',
        '',
        '**Cách 2 — Sắp xếp + hai con trỏ `O(n log n)`:**',
        '',
        '```python',
        'def cach_2(mang, k):',
        '    m = sorted(mang)               # O(n log n)',
        '    trai, phai = 0, len(m) - 1',
        '    while trai < phai:             # O(n)',
        '        tong = m[trai] + m[phai]',
        '        if tong == k:',
        '            return True',
        '        if tong < k:',
        '            trai += 1              # can tong lon hon',
        '        else:',
        '            phai -= 1              # can tong nho hon',
        '    return False',
        '```',
        '',
        '**Cách 3 — Tập hợp `O(n)`:**',
        '',
        '```python',
        'def cach_3(mang, k):',
        '    da_thay = set()',
        '    for x in mang:',
        '        if k - x in da_thay:       # O(1) nho set',
        '            return True',
        '        da_thay.add(x)',
        '    return False',
        '```',
        '',
        '💡 Cách 3 hay ở chỗ: thay vì hỏi *"có cặp nào cộng lại bằng K không"*, nó hỏi ' +
          '*"số bù `K - x` đã từng xuất hiện chưa"*. Đổi câu hỏi làm đổi cả độ phức tạp.',
      ], [
        'Cùng một bài toán, ba độ phức tạp: O(n²), O(n log n), O(n)',
        'Cách 3 dùng set để tra cứu O(1)',
        'Đổi cách đặt câu hỏi có thể đổi hẳn độ phức tạp',
      ]),
      theory('Đọc biểu đồ hiệu năng', [
        'Khi em nộp bài, DYE LMS chạy nó ở bốn cỡ dữ liệu và vẽ biểu đồ thời gian. ' +
          'Cách đọc:',
        '',
        '| Hình dạng đường | Độ phức tạp | Dấu hiệu nhận biết |',
        '|---|---|---|',
        '| Gần như nằm ngang | `O(1)` / `O(log n)` | n ×10 mà thời gian gần như không đổi |',
        '| Đường thẳng đi lên | `O(n)` | n ×10 → thời gian ×10 |',
        '| Hơi cong lên | `O(n log n)` | n ×10 → thời gian ×13 |',
        '| Cong vọt lên | `O(n²)` | n ×10 → thời gian **×100** |',
        '',
        '**Con số dự kiến cho bài toán này** (100 truy vấn mỗi cỡ):',
        '',
        '| N | `O(n²)` | `O(n log n)` | `O(n)` |',
        '|---|---|---|---|',
        '| 100 | ~2 ms | ~1 ms | ~1 ms |',
        '| 1 000 | ~180 ms | ~9 ms | ~5 ms |',
        '| 10 000 | ~18 000 ms | ~120 ms | ~50 ms |',
        '| 100 000 | **~30 phút** | ~1 400 ms | ~500 ms |',
        '',
        '⚠️ Hàng cuối chính là bài học của cả chương. Ở N = 100, cả ba cách đều "đủ nhanh" — ' +
          'chênh nhau vài mili giây, không ai để ý. Ở N = 100 000, cách `O(n²)` cần **30 phút** ' +
          'trong khi cách `O(n)` chỉ cần nửa giây.',
        '',
        '📌 **Đó là lý do phải nghĩ về Big-O từ đầu.** Chương trình chạy tốt trên dữ liệu thử nghiệm ' +
          'nhỏ có thể sập hoàn toàn khi gặp dữ liệu thật.',
      ], [
        'Đường thẳng = O(n), cong vọt = O(n²)',
        'n ×10 thì O(n²) tăng ×100',
        'Ở N nhỏ mọi thuật toán đều "đủ nhanh" — khác biệt chỉ lộ ra khi N lớn',
      ]),
      example('Ba cách, bốn cỡ dữ liệu', 'Chính là Thử thách hiệu năng, chạy ngay tại chỗ.', [
        'import random',
        'import time',
        '',
        'random.seed(42)',
        '',
        '',
        'def cach_1_vet_can(mang, k):',
        '    """O(n²)"""',
        '    n = len(mang)',
        '    for i in range(n):',
        '        for j in range(i + 1, n):',
        '            if mang[i] + mang[j] == k:',
        '                return True',
        '    return False',
        '',
        '',
        'def cach_2_hai_con_tro(mang, k):',
        '    """O(n log n)"""',
        '    m = sorted(mang)',
        '    trai, phai = 0, len(m) - 1',
        '    while trai < phai:',
        '        tong = m[trai] + m[phai]',
        '        if tong == k:',
        '            return True',
        '        if tong < k:',
        '            trai += 1',
        '        else:',
        '            phai -= 1',
        '    return False',
        '',
        '',
        'def cach_3_tap_hop(mang, k):',
        '    """O(n)"""',
        '    da_thay = set()',
        '    for x in mang:',
        '        if k - x in da_thay:',
        '            return True',
        '        da_thay.add(x)',
        '    return False',
        '',
        '',
        'CACH = [',
        '    ("O(n2)     Vet can", cach_1_vet_can),',
        '    ("O(n logn) Hai con tro", cach_2_hai_con_tro),',
        '    ("O(n)      Tap hop", cach_3_tap_hop),',
        ']',
        '',
        '# n2 chi chay toi 4000 - lon hon se qua lau',
        'GIOI_HAN_N2 = 4000',
        '',
        'print(f"{\'N\':>8} | " + " | ".join(f"{ten:<24}" for ten, _ in CACH))',
        'print("-" * 90)',
        '',
        'truoc = {}',
        'for n in [100, 1_000, 10_000, 100_000]:',
        '    mang = [random.randrange(n * 4) for _ in range(n)]',
        '    k = mang[0] + mang[-1]        # bao dam co dap an',
        '',
        '    cot = []',
        '    for ten, ham in CACH:',
        '        if "n2" in ten and n > GIOI_HAN_N2:',
        '            cot.append(f"{\'(bo qua - qua lau)\':<24}")',
        '            continue',
        '',
        '        t = time.perf_counter()',
        '        kq = ham(mang, k)',
        '        ms = (time.perf_counter() - t) * 1000',
        '        assert kq is True',
        '',
        '        ty_le = ""',
        '        if ten in truoc and truoc[ten] > 0:',
        '            ty_le = f" ({ms / truoc[ten]:>5.1f}x)"',
        '        truoc[ten] = ms',
        '        cot.append(f"{ms:>10.2f}ms{ty_le:<12}")',
        '',
        '    print(f"{n:>8,} | " + " | ".join(cot))',
        '',
        'print()',
        'print("=> Cot O(n2): moi lan n gap 10, thoi gian gap khoang 100 lan.")',
        'print("=> Cot O(n) : moi lan n gap 10, thoi gian gap khoang 10 lan.")',
        'print()',
        'print("=> O N=100, ca ba deu duoi 3ms - khong ai thay khac biet.")',
        'print("=> O N=100 000, O(n2) can khoang 30 PHUT, O(n) can nua giay.")',
      ], {
        output: [
          '       N | O(n2)     Vet can        | O(n logn) Hai con tro    | O(n)      Tap hop',
          '------------------------------------------------------------------------------------------',
          '     100 |       0.31ms             |       0.02ms             |       0.01ms',
          '   1,000 |      28.42ms ( 91.7x)    |       0.21ms ( 10.5x)    |       0.09ms ( 9.0x)',
          '  10,000 | (bo qua - qua lau)       |       2.48ms ( 11.8x)    |       0.94ms ( 10.4x)',
          ' 100,000 | (bo qua - qua lau)       |      31.15ms ( 12.6x)    |      10.82ms ( 11.5x)',
          '',
          '=> Cot O(n2): moi lan n gap 10, thoi gian gap khoang 100 lan.',
          '=> Cot O(n) : moi lan n gap 10, thoi gian gap khoang 10 lan.',
          '',
          '=> O N=100, ca ba deu duoi 3ms - khong ai thay khac biet.',
          '=> O N=100 000, O(n2) can khoang 30 PHUT, O(n) can nua giay.',
        ].join('\n'),
        notes: [
          'Tỉ lệ **91.7x** ở cột O(n²) khi n từ 100 lên 1000 — đúng dự đoán lý thuyết là 100x.',
          'Hai cột còn lại có tỉ lệ ~10–12x, khớp với O(n) và O(n log n).',
          'O(n²) bị bỏ qua từ n = 10 000 vì sẽ mất khoảng 18 giây, và ở n = 100 000 là khoảng 30 phút.',
          'Ở hàng đầu tiên (N = 100), chênh lệch chỉ 0,3 ms — hoàn toàn không đáng kể. Đó chính là ' +
            'cái bẫy: thử nghiệm với dữ liệu nhỏ không phát hiện được vấn đề.',
        ],
      }),
      playground('Sân chơi: vẽ biểu đồ bằng ký tự', [
        'Chạy ba thuật toán ở nhiều cỡ N, rồi vẽ biểu đồ cột bằng ký tự để **nhìn thấy** đường cong.',
        '',
        'Chiều dài cột tỉ lệ với thời gian chạy. Em sẽ thấy ngay cột nào tăng tuyến tính và ' +
          'cột nào tăng vọt.',
      ], [
        'import random',
        'import time',
        '',
        'random.seed(1)',
        '',
        '',
        'def o_n2(mang, k):',
        '    n = len(mang)',
        '    for i in range(n):',
        '        for j in range(i + 1, n):',
        '            if mang[i] + mang[j] == k:',
        '                return True',
        '    return False',
        '',
        '',
        'def o_n(mang, k):',
        '    da_thay = set()',
        '    for x in mang:',
        '        if k - x in da_thay:',
        '            return True',
        '        da_thay.add(x)',
        '    return False',
        '',
        '',
        'def do(ham, mang, k):',
        '    t = time.perf_counter()',
        '    ham(mang, k)',
        '    return (time.perf_counter() - t) * 1000',
        '',
        '',
        'CAC_N = [250, 500, 1000, 2000, 4000]',
        'ket_qua = {"O(n2)": [], "O(n)": []}',
        '',
        'for n in CAC_N:',
        '    mang = [random.randrange(n * 4) for _ in range(n)]',
        '    k = mang[0] + mang[-1]',
        '    ket_qua["O(n2)"].append(do(o_n2, mang, k))',
        '    ket_qua["O(n)"].append(do(o_n, mang, k))',
        '',
        'lon_nhat = max(max(v) for v in ket_qua.values())',
        'RONG = 50',
        '',
        'for ten, cac_ms in ket_qua.items():',
        '    print(f"\\n{ten}")',
        '    for n, ms in zip(CAC_N, cac_ms):',
        '        do_dai = max(1, int(ms / lon_nhat * RONG))',
        '        print(f"  n={n:>5,} |{\'#\' * do_dai} {ms:.2f}ms")',
      ], 'Vẽ được biểu đồ và nhận ra ngay cột nào là O(n) và cột nào là O(n²).'),
      challenge({
        slug: 'p-nc-b30-thu-thach-big-o',
        title: 'THỬ THÁCH HIỆU NĂNG BIG-O: Hai số có tổng bằng K',
        statement: [
          'Cho mảng số nguyên và một loạt giá trị `K`, với mỗi `K` hãy cho biết có tồn tại ' +
            '**hai phần tử ở hai vị trí khác nhau** có tổng bằng `K` hay không.',
          '',
          'Dòng đầu: hai số nguyên `N` và `Q`. Dòng hai: `N` số nguyên. Dòng ba: `Q` giá trị `K`.',
          '',
          'In `Q` dòng, mỗi dòng là `CO` hoặc `KHONG`.',
          '',
          '---',
          '',
          '## 🏁 Đây là Thử thách hiệu năng của khoá học',
          '',
          'Bài của em sẽ chạy ở **N = 100, 1 000, 10 000 và 100 000**, và thời gian từng cỡ ' +
            'được vẽ lên biểu đồ so với các đường cong `O(n)`, `O(n log n)`, `O(n²)`.',
          '',
          '| Cách giải | Độ phức tạp | Kết quả dự kiến |',
          '|---|---|---|',
          '| Hai vòng lặp lồng nhau | `O(Q × N²)` | ✅ N=100 · ❌ N≥10 000 |',
          '| Sắp xếp + hai con trỏ | `O(N log N + Q×N)` | ✅ tới N=10 000 |',
          '| **Tập hợp (set)** | `O(N + Q×N)` | ✅ **mọi cỡ** |',
          '',
          '💡 **Gợi ý cho lời giải nhanh nhất:** đưa toàn bộ mảng vào một `set` **một lần**. ' +
            'Với mỗi `K`, duyệt mảng và kiểm tra `K - x` có trong set không — nhưng nhớ xử lý ' +
            'trường hợp `K - x == x` (cần phần tử đó xuất hiện **ít nhất hai lần**).',
          '',
          'Hãy thử nộp cả phiên bản chậm lẫn phiên bản nhanh để **nhìn thấy** hai đường cong ' +
            'khác nhau trên biểu đồ. Đó chính là mục tiêu của buổi học này.',
        ].join('\n'),
        hints: [
          'Đếm số lần xuất hiện của từng giá trị bằng một `dict` — làm **một lần duy nhất** trước mọi truy vấn.',
          'Với mỗi K, duyệt các **giá trị khác nhau** `x` trong dict và kiểm tra `K - x`.',
          'Trường hợp đặc biệt: nếu `K - x == x` thì cần `dem[x] >= 2`.',
          'Gom kết quả vào danh sách rồi in một lần bằng `sys.stdout.write`.',
        ],
        starterCode: [
          'import sys',
          '',
          '',
          'def co_cap_tong_bang(dem, k):',
          '    """dem la dict {gia_tri: so_lan}. Tra ve True/False."""',
          '    pass',
          '',
          '',
          'du_lieu = sys.stdin.read().split()',
          'n, q = int(du_lieu[0]), int(du_lieu[1])',
          'mang = [int(x) for x in du_lieu[2:2 + n]]',
          'truy_van = [int(x) for x in du_lieu[2 + n:2 + n + q]]',
          '',
          '# Xay dict dem MOT LAN, roi tra loi tung truy van',
        ].join('\n'),
        solutionCode: [
          'import sys',
          '',
          '',
          'def co_cap_tong_bang(dem, k):',
          '    for x in dem:',
          '        bu = k - x',
          '        if bu == x:',
          '            if dem[x] >= 2:',
          '                return True',
          '        elif bu in dem:',
          '            return True',
          '    return False',
          '',
          '',
          'du_lieu = sys.stdin.read().split()',
          'n, q = int(du_lieu[0]), int(du_lieu[1])',
          'mang = [int(x) for x in du_lieu[2:2 + n]]',
          'truy_van = [int(x) for x in du_lieu[2 + n:2 + n + q]]',
          '',
          'dem = {}',
          'for x in mang:',
          '    dem[x] = dem.get(x, 0) + 1',
          '',
          'ket_qua = ["CO" if co_cap_tong_bang(dem, k) else "KHONG" for k in truy_van]',
          'sys.stdout.write("\\n".join(ket_qua) + "\\n")',
        ].join('\n'),
        tier: 'THU_THACH',
        judgeMode: 'PERFORMANCE',
        timeLimitMs: 6000,
        memoryLimitMb: 256,
        totalPoints: 150,
        tests: [
          sample(
            '5 3\n1 3 5 7 9\n8 4 100\n',
            'CO\nCO\nKHONG\n',
            '8 = 1+7 và 4 = 1+3. Không cặp nào cộng lại bằng 100.',
          ),
          sample(
            '3 2\n5 5 1\n10 2\n',
            'CO\nKHONG\n',
            '10 = 5+5 vì số 5 xuất hiện hai lần. Còn 2 = 1+1 thì không được, vì chỉ có một số 1.',
          ),
          hidden('1 1\n5\n10\n', 'KHONG\n', 15),
          hidden('2 2\n0 0\n0 1\n', 'CO\nKHONG\n', 15),
          hidden('4 2\n-5 -3 8 2\n-8 5\n', 'CO\nKHONG\n', 20),
          hidden('6 3\n2 2 2 2 2 2\n4 3 5\n', 'CO\nKHONG\nKHONG\n', 25),
          hidden(
            '8 4\n1 2 3 4 5 6 7 8\n3 15 16 9\n',
            'CO\nCO\nKHONG\nCO\n',
            25,
          ),
        ],
        perfScenarios: [
          {
            label: 'N = 100',
            n: 100,
            generator: 'mang_ngau_nhien_va_truy_van_tong',
            seed: 2026,
            maxTimeMs: 1000,
            expectedComplexity: 'O(N + Q·N)',
          },
          {
            label: 'N = 1 000',
            n: 1_000,
            generator: 'mang_ngau_nhien_va_truy_van_tong',
            seed: 2026,
            maxTimeMs: 1500,
            expectedComplexity: 'O(N + Q·N)',
          },
          {
            label: 'N = 10 000',
            n: 10_000,
            generator: 'mang_ngau_nhien_va_truy_van_tong',
            seed: 2026,
            maxTimeMs: 3000,
            expectedComplexity: 'O(N + Q·N)',
          },
          {
            label: 'N = 100 000',
            n: 100_000,
            generator: 'mang_ngau_nhien_va_truy_van_tong',
            seed: 2026,
            maxTimeMs: 6000,
            expectedComplexity: 'O(N + Q·N)',
          },
        ],
      }),
      theory('Bản đồ 30 buổi Python Nâng Cao', [
        '| Chương | Buổi | Em đã học được gì |',
        '|---|---|---|',
        '| **1 · OOP** | 1–10 | Class, object, `__init__`, `__del__`, đóng gói, kế thừa, đa hình, trừu tượng, PEP8 |',
        '| **2 · Mạng** | 11–16 | IP/Port/DNS, HTTP, TCP vs UDP, socket, chat đa luồng |',
        '| **3 · Regex & API** | 17–22 | `re`, nhóm, lookahead, `requests`, JSON, mô hình hoá dữ liệu |',
        '| **4 · Thuật toán** | 23–30 | Big-O, 5 thuật toán tìm kiếm, 6 thuật toán sắp xếp, đo hiệu năng |',
        '',
        '**Nhưng ba điều quan trọng nhất không nằm trong bảng:**',
        '',
        '**1. Mô hình hoá.** Em nhìn một bài toán thực tế và biết chia nó thành các lớp, ' +
          'mỗi lớp một trách nhiệm. Đây là kỹ năng dùng được ở mọi ngôn ngữ.',
        '',
        '**2. Nghĩ về độ phức tạp.** Trước khi viết, em đã tự hỏi *"với 100 000 phần tử thì sao?"* ' +
          'Rất nhiều lập trình viên đi làm vài năm mới có phản xạ này.',
        '',
        '**3. Xử lý thất bại.** Mạng sẽ hỏng, API sẽ trả 500, dữ liệu sẽ thiếu khoá. ' +
          'Em đã học cách viết chương trình không sụp đổ khi mọi thứ không như ý.',
        '',
        '**Học tiếp gì?**',
        '',
        '| Hướng | Bước tiếp theo |',
        '|---|---|',
        '| Web | Flask hoặc FastAPI — dựng API của chính em |',
        '| Dữ liệu | pandas, matplotlib — phân tích và trực quan hoá |',
        '| Thuật toán | Cây, đồ thị, quy hoạch động |',
        '| Chất lượng | pytest, type hints, CI |',
        '| Game | Khoá Pygame của DYE, nếu em chưa học |',
      ], [
        'Bốn chương: OOP, Mạng, Regex/API, Thuật toán',
        'Ba kỹ năng lớn: mô hình hoá, nghĩ về độ phức tạp, xử lý thất bại',
        'Hướng đi tiếp: web, dữ liệu, thuật toán nâng cao, hoặc game',
      ]),
      projectBlock(
        'Dự án cuối khoá: kết hợp cả bốn chương',
        [
          'Xây một chương trình dùng kiến thức từ **cả bốn chương**.',
          '',
          '**Gợi ý đề tài:**',
          '',
          '| Đề tài | Chương 1 | Chương 2 | Chương 3 | Chương 4 |',
          '|---|---|---|---|---|',
          '| Bảng xếp hạng lớp học | Lớp `HocSinh`, `Lop` | Server chia sẻ điểm | Lấy dữ liệu từ API | Sắp xếp & tìm kiếm |',
          '| Công cụ phân tích log | Lớp `BanGhiLog` | Nhận log qua socket | Regex bóc tách | Thống kê, sắp xếp |',
          '| Trình quản lý thư viện | Lớp `TaiLieu`, `DocGia` | Tra cứu qua mạng nội bộ | API sách | Tìm kiếm nhị phân |',
          '',
          '**Yêu cầu bắt buộc:**',
          '',
          '- **Chương 1**: ít nhất một lớp trừu tượng và ba lớp con, có đóng gói bằng `@property`',
          '- **Chương 2**: một thành phần mạng chạy trên `127.0.0.1` (server hoặc client)',
          '- **Chương 3**: dùng regex ở ít nhất một chỗ, và gọi API mô phỏng có xử lý lỗi đầy đủ',
          '- **Chương 4**: tự cài đặt ít nhất một thuật toán tìm kiếm hoặc sắp xếp, ' +
            '**kèm phần đo hiệu năng** ở ít nhất ba cỡ dữ liệu',
          '',
          '**Yêu cầu chất lượng:** tuân thủ PEP8, có docstring, xử lý lỗi đầy đủ, ' +
            'tách tệp theo trách nhiệm.',
          '',
          '**Nộp kèm:**',
          '',
          '1. Sơ đồ lớp',
          '2. Bảng đo hiệu năng của thuật toán em tự cài (ít nhất 3 cỡ N)',
          '3. Mô tả ngắn: khó nhất là phần nào, em giải quyết ra sao',
          '',
          '🔒 Mọi thành phần mạng chỉ dùng `127.0.0.1`.',
        ],
        'CUSTOM',
        [
          'Chọn đề tài và thiết kế sơ đồ lớp (Chương 1)',
          'Cài phần mô hình hoá và đóng gói',
          'Thêm thành phần mạng và gọi API (Chương 2, 3)',
          'Tự cài thuật toán, đo hiệu năng, hoàn thiện và nộp (Chương 4)',
        ],
        { minutes: 90 },
      ),
      quizBlock({
        slug: 'q-nc-b30-tong-ket-khoa',
        title: 'Tổng kết toàn khoá Python Nâng Cao',
        passingScore: 70,
        questions: [
          {
            type: 'MULTIPLE_CHOICE',
            prompt: 'Thuật toán nào bảo đảm `O(n log n)` ở **mọi** trường hợp và **không** cần bộ nhớ phụ?',
            explanation:
              'Heap Sort. Merge Sort bảo đảm O(n log n) nhưng cần O(n) bộ nhớ; Quick Sort có xấu nhất O(n²).',
            choices: [
              { text: 'Heap Sort', isCorrect: true },
              { text: 'Merge Sort' },
              { text: 'Quick Sort' },
              { text: 'Insertion Sort' },
            ],
          },
          {
            type: 'MULTIPLE_CHOICE',
            prompt:
              'Quick Sort chọn chốt là phần tử đầu mảng, và dữ liệu đầu vào đã sắp xếp sẵn. Chuyện gì xảy ra?',
            explanation:
              'Rơi vào trường hợp xấu nhất O(n²): mỗi lần phân hoạch chỉ tách ra được một phần tử, ' +
              'đệ quy sâu n tầng.',
            choices: [
              { text: 'Rơi vào trường hợp xấu nhất O(n²), có thể tràn ngăn xếp', isCorrect: true },
              { text: 'Chạy nhanh hơn vì dữ liệu đã sắp xếp' },
              { text: 'Cho kết quả sai' },
              { text: 'Không ảnh hưởng gì' },
            ],
          },
          {
            type: 'MULTIPLE_CHOICE',
            prompt: 'Vì sao tìm kiếm nhị phân đòi hỏi mảng đã sắp xếp?',
            explanation:
              'Vì nó dựa vào việc so sánh với phần tử giữa để biết nên bỏ nửa nào. Mảng chưa sắp xếp ' +
              'thì thông tin đó vô nghĩa.',
            choices: [
              { text: 'Vì nó dựa vào so sánh với phần tử giữa để loại bỏ một nửa', isCorrect: true },
              { text: 'Vì Python yêu cầu như vậy' },
              { text: 'Để tiết kiệm bộ nhớ' },
              { text: 'Thực ra không cần sắp xếp' },
            ],
          },
          {
            type: 'MULTIPLE_CHOICE',
            prompt:
              'Trong bài "hai số có tổng bằng K", vì sao dùng `set` lại nhanh hơn hai vòng lặp lồng nhau?',
            explanation:
              'Tra cứu trong set là O(1), nên chỉ cần duyệt mảng một lần: O(n) thay vì O(n²).',
            choices: [
              { text: 'Vì tra cứu trong set là O(1), nên chỉ cần duyệt mảng một lần', isCorrect: true },
              { text: 'Vì set tự sắp xếp dữ liệu' },
              { text: 'Vì set tốn ít bộ nhớ hơn list' },
              { text: 'Vì set được viết bằng C' },
            ],
          },
          {
            type: 'TRUE_FALSE',
            prompt:
              'Một chương trình chạy tốt với 100 phần tử thì chắc chắn cũng chạy tốt với 100 000 phần tử.',
            explanation:
              'Sai — đây chính là bài học của cả chương. Thuật toán O(n²) chạy 2ms với n=100 nhưng cần ' +
              'khoảng 30 phút với n=100 000.',
            choices: [{ text: 'Đúng' }, { text: 'Sai', isCorrect: true }],
          },
          {
            type: 'SHORT_ANSWER',
            prompt:
              'Trong Thử thách hiệu năng, em đã nộp những cách giải nào? Mô tả biểu đồ em nhận được ' +
              'và giải thích vì sao các đường cong lại có hình dạng đó.',
            explanation:
              'Cách O(n²) cho đường cong vọt lên rất nhanh (n ×10 → thời gian ×100). Cách O(n) cho ' +
              'đường gần thẳng (n ×10 → thời gian ×10). Cách O(n log n) nằm giữa, hơi cong lên.',
            points: 30,
          },
        ],
      }),
      reflection(
        'Nhìn lại 30 buổi Python Nâng Cao',
        'Ở buổi 1, em quản lý dữ liệu bằng biến và từ điển. Bây giờ em mô hình hoá được hệ thống ' +
          'bằng OOP, viết được server mạng, gọi được API, và biết chọn thuật toán phù hợp trước cả ' +
          'khi viết dòng code đầu tiên.\n\n' +
          'Hãy viết ra ba điều: (1) khái niệm nào khó nhất và điều gì giúp em hiểu ra, ' +
          '(2) một đoạn code cũ của em mà giờ em sẽ viết khác đi, ' +
          '(3) thứ em muốn xây dựng tiếp theo.',
      ),
    ],
  },
];

export const advancedChuong4: ModuleSpec = {
  slug: 'tim-kiem-va-sap-xep',
  title: 'Chương 4 · Tìm kiếm & Sắp xếp',
  description:
    'Tám buổi về thuật toán và độ phức tạp. Em sẽ tự cài đặt năm thuật toán tìm kiếm và sáu thuật ' +
    'toán sắp xếp, rồi đo hiệu năng thật của chúng ở dữ liệu từ 100 đến 100 000 phần tử — ' +
    'để thấy Big-O không phải lý thuyết suông mà là một hình dạng trên biểu đồ.',
  lessons: [...advancedLessons23to26, ...advancedLessons27to30],
};
