/**
 * Pygame — Module 4 (assembly) và Module 5 (Buổi 27–30).
 */
import type { ModuleSpec } from '../types.ts';
import {
  challenge,
  example,
  hidden,
  playground,
  projectBlock,
  quizBlock,
  reflection,
  resources,
  sample,
  theory,
} from '../builders.ts';
import { pygameLessons17to19 } from './pygame-m4a.ts';
import { pygameLessons20to23 } from './pygame-m4b.ts';
import { pygameLessons24to26 } from './pygame-m4c.ts';

export const pygameModule4: ModuleSpec = {
  slug: 'platformer-ai-power-up-tong-hop',
  title: 'Module 4 · Platformer, AI, Power-up & Tổng hợp',
  description:
    'Mười buổi dài nhất khoá học. Bảy buổi đầu xây từng hệ thống lớn của một trò chơi hoàn chỉnh, ' +
    'ba buổi cuối là các buổi tổng hợp ghép mọi thứ lại thành ba trò chơi khác nhau.',
  lessons: [...pygameLessons17to19, ...pygameLessons20to23, ...pygameLessons24to26],
};

export const pygameModule5: ModuleSpec = {
  slug: 'go-loi-hoan-thien-trinh-bay',
  title: 'Module 5 · Gỡ lỗi, Hoàn thiện, Trình bày',
  description:
    'Bốn buổi cuối biến một trò chơi "chạy được" thành một sản phẩm em tự hào đưa cho người khác chơi.',
  lessons: [
    {
      order: 27,
      slug: 'pg-b27-go-loi-va-toi-uu',
      title: 'Gỡ lỗi & tối ưu hiệu năng game',
      summary:
        'Kỹ năng quan trọng nhất mà ít được dạy nhất: tìm ra vì sao game hỏng, và làm nó chạy mượt trở lại.',
      objectives: [
        'Đọc và hiểu thông báo lỗi Python trong bối cảnh game',
        'Dùng kỹ thuật in trạng thái ra màn hình để gỡ lỗi',
        'Nhận diện các nguyên nhân làm game tụt FPS',
        'Áp dụng ba cách tối ưu hiệu năng phổ biến',
      ],
      difficulty: 4,
      status: 'REQUIRED',
      teacherNotes:
        'Cho học sinh gỡ lỗi trên chính dự án của mình. Nhấn mạnh quy trình: Phát hiện → Tái hiện → ' +
        'Tìm nguyên nhân → Sửa → Kiểm tra lại.',
      blocks: [
        theory('Quy trình gỡ lỗi năm bước', [
          'Khi game hỏng, đừng sửa lung tung. Làm đúng năm bước này sẽ nhanh hơn nhiều:',
          '',
          '| Bước | Việc làm | Câu hỏi tự đặt |',
          '|---|---|---|',
          '| 1. Phát hiện | Mô tả lỗi bằng một câu | "Nhân vật lọt qua sàn khi nhảy từ trên cao" |',
          '| 2. Tái hiện | Tìm cách làm lỗi xuất hiện **mỗi lần** | "Nhảy từ bệ cao nhất là lọt" |',
          '| 3. Tìm nguyên nhân | In trạng thái ra để xem gì đang sai | "vy lên tới 45, lớn hơn TILE = 40" |',
          '| 4. Sửa | Sửa **nguyên nhân**, không sửa triệu chứng | Giới hạn `vy` tối đa 18 |',
          '| 5. Kiểm tra lại | Thử lại bước 2, và thử cả các phần khác | "Không lọt nữa, nhảy vẫn bình thường" |',
          '',
          '**Bước 2 là bước hay bị bỏ qua nhất, mà lại quan trọng nhất.** Lỗi không tái hiện được là ' +
            'lỗi không sửa được — và cũng không biết đã sửa xong hay chưa.',
          '',
          '⚠️ Bước 4 nhấn mạnh: sửa **nguyên nhân**. Nếu nhân vật lọt sàn mà em xử lý bằng cách ' +
            '"nếu lọt thì đưa lại lên trên", lỗi sẽ quay lại dưới hình dạng khác. ' +
            'Nguyên nhân thật là tốc độ rơi quá lớn.',
        ], [
          'Phát hiện → Tái hiện → Tìm nguyên nhân → Sửa → Kiểm tra lại',
          'Không tái hiện được thì không sửa được',
          'Sửa nguyên nhân, không sửa triệu chứng',
        ]),
        theory('Ba công cụ gỡ lỗi game', [
          '**1. Bảng gỡ lỗi trên màn hình** — hiệu quả nhất cho game, vì `print()` cuộn quá nhanh ' +
            'ở 60 khung hình mỗi giây:',
          '',
          '```python',
          'def ve_bang_go_loi(mh, font, thong_tin):',
          '    y = 8',
          '    for dong in thong_tin:',
          '        mh.blit(font.render(dong, True, (0, 255, 120)), (8, y))',
          '        y += 20',
          '',
          '# Trong game loop',
          'if CHE_DO_GO_LOI:',
          '    ve_bang_go_loi(man_hinh, font_nho, [',
          '        f"FPS: {dong_ho.get_fps():.0f}",',
          '        f"vy: {vy:.2f}   tren_nen: {tren_nen}",',
          '        f"So sprite: {len(tat_ca)}",',
          '        f"Trang thai: {trang_thai}",',
          '    ])',
          '```',
          '',
          'Đặt `CHE_DO_GO_LOI = True` ở đầu tệp, bấm phím F1 để bật/tắt. Nộp bài thì để `False`.',
          '',
          '**2. Vẽ vùng va chạm** — thấy tận mắt vì sao va chạm sai:',
          '',
          '```python',
          'if CHE_DO_GO_LOI:',
          '    pygame.draw.rect(man_hinh, (255, 0, 0), nv, 1)',
          '    for o in nen:',
          '        pygame.draw.rect(man_hinh, (0, 255, 255), o, 1)',
          '```',
          '',
          '**3. Chạy chậm lại** — đổi `tick(60)` thành `tick(5)` để xem từng khung hình một. ' +
            'Rất hiệu quả với lỗi va chạm.',
        ], [
          'Bảng gỡ lỗi trên màn hình thay cho `print()`',
          'Vẽ viền vùng va chạm để thấy vấn đề',
          '`tick(5)` để xem chuyển động chậm lại',
        ]),
        theory('Ba nguyên nhân làm game chậm', [
          '| Nguyên nhân | Dấu hiệu | Cách sửa |',
          '|---|---|---|',
          '| Tải ảnh trong game loop | Chậm ngay từ đầu, đều đều | Tải một lần, ngoài vòng lặp |',
          '| Vẽ mọi thứ kể cả ngoài màn hình | Càng nhiều đối tượng càng chậm | Chỉ vẽ phần đang nhìn thấy |',
          '| Không xoá đối tượng đã chết | Chậm dần theo thời gian chơi | Gọi `sprite.kill()` |',
          '',
          '```python',
          '# SAI: doc tep 60 lan moi giay',
          'while dang_chay:',
          '    anh = pygame.image.load("tau.png")     # ← tham hoa',
          '',
          '# DUNG: doc mot lan',
          'anh = pygame.image.load("tau.png").convert_alpha()',
          'while dang_chay:',
          '    man_hinh.blit(anh, (x, y))',
          '```',
          '',
          '```python',
          '# Chi ve phan dang nhin thay (culling)',
          'khung_nhin = pygame.Rect(camera_x, camera_y, RONG, CAO)',
          'for o in nen:',
          '    if khung_nhin.colliderect(o):',
          '        pygame.draw.rect(man_hinh, MAU, (o.x - camera_x, o.y - camera_y, TILE, TILE))',
          '```',
          '',
          '```python',
          '# Xoa dan da ra khoi man hinh',
          'class Dan(pygame.sprite.Sprite):',
          '    def update(self):',
          '        self.rect.y -= 10',
          '        if self.rect.bottom < 0:',
          '            self.kill()          # ← thieu dong nay = ro ri bo nho',
          '```',
          '',
          '💡 Cách đo nhanh: hiện `len(tat_ca)` lên bảng gỡ lỗi. Nếu con số cứ tăng mãi và không bao giờ ' +
            'giảm, em đang quên `kill()` ở đâu đó.',
        ], [
          'Tải ảnh một lần, ngoài game loop',
          'Chỉ vẽ những gì đang nhìn thấy',
          'Luôn `kill()` đối tượng đã ra khỏi màn hình',
          'Số sprite tăng mãi = quên `kill()`',
        ]),
        example('Bảng gỡ lỗi bật/tắt bằng F1', 'Thêm đoạn này vào dự án của em ngay hôm nay.', [
          'import pygame',
          '',
          'pygame.init()',
          'RONG, CAO = 700, 460',
          'man_hinh = pygame.display.set_mode((RONG, CAO))',
          'pygame.display.set_caption("Cong cu go loi")',
          'dong_ho = pygame.time.Clock()',
          'font_go_loi = pygame.font.SysFont("consolas", 16)',
          '',
          'CHE_DO_GO_LOI = True',
          'fps_muc_tieu = 60',
          '',
          'nen = [pygame.Rect(0, 400, RONG, 60), pygame.Rect(240, 300, 160, 24)]',
          'nv = pygame.Rect(80, 200, 30, 40)',
          'vy = 0.0',
          'tren_nen = False',
          'dan = []',
          '',
          '',
          'def ve_bang_go_loi(mh, font, thong_tin):',
          '    nen_bang = pygame.Surface((260, len(thong_tin) * 20 + 10), pygame.SRCALPHA)',
          '    nen_bang.fill((0, 0, 0, 160))',
          '    mh.blit(nen_bang, (6, 6))',
          '    y = 11',
          '    for dong in thong_tin:',
          '        mh.blit(font.render(dong, True, (0, 255, 130)), (12, y))',
          '        y += 20',
          '',
          '',
          'dang_chay = True',
          'while dang_chay:',
          '    for su_kien in pygame.event.get():',
          '        if su_kien.type == pygame.QUIT:',
          '            dang_chay = False',
          '        elif su_kien.type == pygame.KEYDOWN:',
          '            if su_kien.key == pygame.K_F1:',
          '                CHE_DO_GO_LOI = not CHE_DO_GO_LOI',
          '            elif su_kien.key == pygame.K_F2:',
          '                fps_muc_tieu = 5 if fps_muc_tieu == 60 else 60',
          '            elif su_kien.key == pygame.K_SPACE and tren_nen:',
          '                vy = -14',
          '            elif su_kien.key == pygame.K_f:',
          '                dan.append(pygame.Rect(nv.centerx, nv.top, 5, 14))',
          '',
          '    phim = pygame.key.get_pressed()',
          '    vx = 0',
          '    if phim[pygame.K_LEFT]:',
          '        vx = -5',
          '    if phim[pygame.K_RIGHT]:',
          '        vx = 5',
          '',
          '    vy = min(vy + 0.8, 16)',
          '',
          '    nv.x += vx',
          '    for o in nen:',
          '        if nv.colliderect(o):',
          '            if vx > 0:',
          '                nv.right = o.left',
          '            elif vx < 0:',
          '                nv.left = o.right',
          '',
          '    tren_nen = False',
          '    nv.y += int(vy)',
          '    for o in nen:',
          '        if nv.colliderect(o):',
          '            if vy > 0:',
          '                nv.bottom = o.top',
          '                tren_nen = True',
          '            elif vy < 0:',
          '                nv.top = o.bottom',
          '            vy = 0.0',
          '',
          '    # Dan bay len va TU XOA khi ra khoi man hinh',
          '    con_lai = []',
          '    for d in dan:',
          '        d.y -= 9',
          '        if d.bottom > 0:',
          '            con_lai.append(d)',
          '    dan = con_lai',
          '',
          '    man_hinh.fill((26, 26, 46))',
          '    for o in nen:',
          '        pygame.draw.rect(man_hinh, (85, 95, 125), o)',
          '    for d in dan:',
          '        pygame.draw.rect(man_hinh, (241, 196, 15), d)',
          '    pygame.draw.rect(man_hinh, (46, 204, 113), nv, 0, border_radius=5)',
          '',
          '    if CHE_DO_GO_LOI:',
          '        pygame.draw.rect(man_hinh, (255, 60, 60), nv, 1)',
          '        for o in nen:',
          '            pygame.draw.rect(man_hinh, (0, 220, 255), o, 1)',
          '        ve_bang_go_loi(man_hinh, font_go_loi, [',
          '            f"FPS      : {dong_ho.get_fps():5.1f} / {fps_muc_tieu}",',
          '            f"nv       : ({nv.x}, {nv.y})",',
          '            f"vy       : {vy:6.2f}",',
          '            f"tren_nen : {tren_nen}",',
          '            f"So dan   : {len(dan)}",',
          '            "F1 tat bang · F2 chay cham · F ban",',
          '        ])',
          '',
          '    pygame.display.flip()',
          '    dong_ho.tick(fps_muc_tieu)',
          '',
          'pygame.quit()',
        ], {
          output:
            'Game nhỏ có bảng gỡ lỗi nền mờ ở góc trái, viền va chạm màu đỏ/xanh, F1 tắt bảng, F2 chạy chậm để soi từng khung hình.',
          notes: [
            'Bấm F rồi giữ — quan sát "So dan" tăng lên rồi **giảm lại** khi đạn bay khỏi màn hình. ' +
              'Nếu con số chỉ tăng, đó là dấu hiệu rò rỉ.',
            'Bấm F2 để chạy 5 FPS rồi nhảy — em sẽ thấy rõ từng bước va chạm diễn ra thế nào.',
            'Viền va chạm cho thấy vùng thật sự dùng để tính, thường khác với hình vẽ.',
          ],
        }),
        playground('Sân chơi: tìm lỗi trong đoạn code này', [
          'Đoạn dưới đây có **ba lỗi hiệu năng**. Tìm và sửa cả ba.',
          '',
          'Gợi ý: một lỗi về tải tài nguyên, một lỗi về rò rỉ đối tượng, một lỗi về vẽ thừa.',
          '',
          'Dùng đúng quy trình năm bước — đừng đoán mò.',
        ], [
          'import pygame',
          '',
          'pygame.init()',
          'man_hinh = pygame.display.set_mode((800, 600))',
          'dong_ho = pygame.time.Clock()',
          'font = pygame.font.SysFont("arial", 16)',
          '',
          'dan = []',
          'nen = [pygame.Rect(i * 40, 500, 40, 40) for i in range(200)]   # ban do rat rong',
          'camera_x = 0',
          '',
          'dang_chay = True',
          'while dang_chay:',
          '    for su_kien in pygame.event.get():',
          '        if su_kien.type == pygame.QUIT:',
          '            dang_chay = False',
          '',
          '    # LOI 1: tao font moi moi khung hinh',
          '    font = pygame.font.SysFont("arial", 16)',
          '',
          '    dan.append(pygame.Rect(400, 300, 5, 10))',
          '    for d in dan:',
          '        d.y -= 8',
          '    # LOI 2: dan bay ra ngoai nhung khong bao gio bi xoa',
          '',
          '    man_hinh.fill((25, 25, 45))',
          '    # LOI 3: ve ca 200 o nen du chi nhin thay khoang 20 o',
          '    for o in nen:',
          '        pygame.draw.rect(man_hinh, (90, 100, 125), (o.x - camera_x, o.y, 40, 40))',
          '',
          '    for d in dan:',
          '        pygame.draw.rect(man_hinh, (241, 196, 15), d)',
          '',
          '    man_hinh.blit(font.render(f"So dan: {len(dan)}  FPS: {dong_ho.get_fps():.0f}",',
          '                              True, (255, 255, 255)), (10, 10))',
          '    pygame.display.flip()',
          '    dong_ho.tick(60)',
          '',
          'pygame.quit()',
        ], 'Tìm và sửa được cả ba lỗi, FPS ổn định ở 60 sau khi sửa.'),
        challenge({
          slug: 'p-pg-b27-dem-doi-tuong-song',
          title: 'Phát hiện rò rỉ đối tượng',
          statement: [
            'Mỗi khung hình, game tạo thêm `a` viên đạn và xoá những viên đã ra khỏi màn hình.',
            '',
            'Viên đạn sống đúng `t` khung hình rồi bị xoá. Ở khung hình đầu tiên (khung 1), ' +
              '`a` viên được tạo; chúng bị xoá **sau khi** khung `t` kết thúc.',
            '',
            'Nói cách khác, sau `N` khung hình, số đạn còn sống là số đạn được tạo trong ' +
              '`min(N, t)` khung hình gần nhất.',
            '',
            'Đọc **ba số nguyên** trên ba dòng: `a`, `t`, `N`.',
            '',
            'In ra **một dòng**: số viên đạn còn sống sau `N` khung hình.',
            '',
            'Nếu `t` bằng `0`, đạn bị xoá ngay nên kết quả luôn là `0`.',
          ].join('\n'),
          hints: [
            'Không cần mô phỏng từng viên — chỉ cần một phép nhân.',
            'Số khung hình còn giữ đạn là `min(N, t)`.',
            'Kết quả là `a * min(N, t)`.',
          ],
          starterCode: [
            'a = int(input())',
            't = int(input())',
            'n = int(input())',
            '',
            '# Tính số đạn còn sống',
          ].join('\n'),
          solutionCode: [
            'a = int(input())',
            't = int(input())',
            'n = int(input())',
            '',
            'print(a * min(n, t))',
          ].join('\n'),
          tier: 'CO_BAN',
          judgeMode: 'IO_MATCH',
          tests: [
            sample('2\n30\n100\n', '60\n', 'Chỉ 30 khung gần nhất còn giữ đạn: 2 × 30 = 60.'),
            sample('5\n10\n3\n', '15\n', 'Mới chạy 3 khung nên chưa viên nào bị xoá: 5 × 3 = 15.'),
            hidden('1\n0\n1000\n', '0\n', 20),
            hidden('3\n1\n1\n', '3\n', 20),
            hidden('10\n60\n60\n', '600\n', 30),
            hidden('7\n5\n1000000\n', '35\n', 30),
          ],
        }),
      ],
    },

    {
      order: 28,
      slug: 'pg-b28-hoan-thien-do-hoa-am-thanh',
      title: 'Hoàn thiện đồ hoạ, âm thanh & trải nghiệm người chơi',
      summary:
        'Khoảng cách giữa "bài tập" và "trò chơi" nằm ở những chi tiết nhỏ: hiệu ứng, phản hồi, ' +
        'và sự tử tế với người chơi.',
      objectives: [
        'Thêm hiệu ứng hình ảnh: hạt, rung màn hình, chữ bay',
        'Cân bằng bảng màu và độ tương phản',
        'Thêm phản hồi tức thì cho mọi hành động của người chơi',
        'Thiết kế trò chơi dễ tiếp cận với mọi người',
      ],
      difficulty: 3,
      status: 'REQUIRED',
      teacherNotes:
        'Nhấn mạnh phần dễ tiếp cận: chữ đủ lớn, không chỉ dựa vào màu để truyền tin, ' +
        'có thể tắt hiệu ứng mạnh.',
      blocks: [
        theory('Phản hồi tức thì — nguyên tắc số một', [
          '**Mọi hành động của người chơi phải có phản hồi trong vòng một khung hình.** ' +
            'Đây là nguyên tắc quan trọng nhất của cảm giác game.',
          '',
          '| Hành động | Phản hồi tối thiểu |',
          '|---|---|',
          '| Bấm nút | Nút đổi màu hoặc thụt xuống |',
          '| Bắn | Chớp sáng ở nòng + tiếng |',
          '| Trúng đòn | Màn hình chớp đỏ + nhân vật nhấp nháy |',
          '| Ăn vật phẩm | Chữ "+10" bay lên + tiếng |',
          '| Thắng màn | Hiệu ứng + nhạc + dừng một nhịp |',
          '',
          'Không có phản hồi, người chơi sẽ nghĩ game bị lỗi — kể cả khi nó chạy hoàn hảo.',
          '',
          '**Chữ bay lên rồi mờ dần** — hiệu ứng dễ làm mà hiệu quả cao:',
          '',
          '```python',
          'chu_bay = []      # moi phan tu: [x, y, noi_dung, thoi_gian_con_lai]',
          '',
          '# Khi an xu',
          'chu_bay.append([nv.centerx, nv.top, "+10", 45])',
          '',
          '# Moi khung hinh',
          'con_lai = []',
          'for c in chu_bay:',
          '    c[1] -= 1.5           # bay len',
          '    c[3] -= 1',
          '    if c[3] > 0:',
          '        con_lai.append(c)',
          'chu_bay = con_lai',
          '',
          '# Ve',
          'for x, y, noi_dung, tg in chu_bay:',
          '    do_dam = int(255 * tg / 45)          # mo dan',
          '    anh_chu = font.render(noi_dung, True, (241, 196, 15))',
          '    anh_chu.set_alpha(do_dam)',
          '    man_hinh.blit(anh_chu, (x, y))',
          '```',
        ], [
          'Mọi hành động phải có phản hồi ngay lập tức',
          'Không phản hồi = người chơi tưởng game lỗi',
          '`set_alpha()` để làm mờ dần',
        ]),
        theory('Hạt, rung màn hình và bảng màu', [
          '**Hệ hạt** — dùng cho vụ nổ, bụi, tia lửa:',
          '',
          '```python',
          'import random',
          '',
          'def tao_no(x, y, so_hat=20):',
          '    hat = []',
          '    for i in range(so_hat):',
          '        hat.append({',
          '            "x": float(x), "y": float(y),',
          '            "vx": random.uniform(-4, 4),',
          '            "vy": random.uniform(-4, 4),',
          '            "doi": random.randint(20, 40),',
          '        })',
          '    return hat',
          '',
          '# Cap nhat: hat bay ra, roi xuong, roi bien mat',
          'for h in danh_sach_hat:',
          '    h["x"] += h["vx"]',
          '    h["y"] += h["vy"]',
          '    h["vy"] += 0.15          # trong luc cho hat',
          '    h["doi"] -= 1',
          '```',
          '',
          '**Rung màn hình** — thêm sức nặng cho va chạm mạnh:',
          '',
          '```python',
          'rung = 0',
          '',
          '# Khi trung don',
          'rung = 12',
          '',
          '# Khi ve: lech toan bo theo mot luong ngau nhien',
          'lech_x = lech_y = 0',
          'if rung > 0:',
          '    lech_x = random.randint(-rung, rung)',
          '    lech_y = random.randint(-rung, rung)',
          '    rung -= 1',
          '```',
          '',
          '⚠️ **Rung nhẹ thôi.** Rung quá mạnh gây khó chịu và có thể ảnh hưởng tới bạn nhạy cảm ' +
            'với chuyển động. Nên có tuỳ chọn tắt.',
          '',
          '**Bảng màu:** chọn 4–6 màu và dùng nhất quán cả game. Bảng màu lộn xộn làm game trông ' +
            'nghiệp dư hơn cả đồ hoạ xấu.',
        ], [
          'Hạt = danh sách từ điển có vx, vy, đời sống',
          'Rung màn hình = lệch toàn bộ khi vẽ, và phải nhẹ',
          'Chọn 4–6 màu, dùng nhất quán',
        ]),
        theory('Trò chơi dành cho mọi người', [
          'Game của em sẽ có bạn cùng lớp chơi. Vài nguyên tắc để không ai bị bỏ lại:',
          '',
          '**1. Không truyền tin chỉ bằng màu.** Khoảng 1 trong 12 bạn nam khó phân biệt đỏ–xanh lá. ' +
            'Nếu kẻ địch đỏ và đồng minh xanh lá **chỉ khác nhau ở màu**, một số bạn sẽ không chơi được.',
          '',
          '```python',
          '# TOT: khac ca mau LAN hinh dang',
          'pygame.draw.rect(mh, DO, dich)                    # ke dich: vuong',
          'pygame.draw.circle(mh, XANH, ban.center, 15)      # dong minh: tron',
          '```',
          '',
          '**2. Chữ đủ lớn.** Tối thiểu 18px cho chữ thường, 24px cho thông tin quan trọng. ' +
            'Và luôn tương phản cao với nền.',
          '',
          '**3. Có thể chơi bằng một tay.** Cho phép cả mũi tên và WASD.',
          '',
          '**4. Không phạt nặng.** Người mới cần được thử lại nhanh. Tránh "chết là mất hết tiến độ".',
          '',
          '**5. Có màn hướng dẫn.** Một dòng chữ ở màn menu: "Mui ten de di chuyen, CACH de nhay" ' +
            'là đủ.',
          '',
          '**6. Cho tắt hiệu ứng mạnh.** Rung màn hình và chớp sáng nên có tuỳ chọn tắt.',
        ], [
          'Đừng chỉ dùng màu để phân biệt — thêm hình dạng',
          'Chữ tối thiểu 18px, tương phản cao',
          'Hỗ trợ nhiều bộ phím, cho thử lại nhanh',
          'Có hướng dẫn và cho tắt hiệu ứng mạnh',
        ]),
        example('Gói hiệu ứng hoàn chỉnh', 'Bấm chuột để nổ. Ba hiệu ứng cùng lúc: hạt, chữ bay, rung màn hình.', [
          'import pygame',
          'import random',
          '',
          'pygame.init()',
          'RONG, CAO = 760, 520',
          'man_hinh = pygame.display.set_mode((RONG, CAO))',
          'pygame.display.set_caption("Goi hieu ung")',
          'dong_ho = pygame.time.Clock()',
          'font = pygame.font.SysFont("arial", 22, bold=True)',
          'font_nho = pygame.font.SysFont("arial", 18)',
          '',
          'BANG_MAU = [(241, 196, 15), (230, 126, 34), (231, 76, 60), (155, 89, 182)]',
          '',
          'hat = []',
          'chu_bay = []',
          'rung = 0',
          'diem = 0',
          'bat_hieu_ung = True',
          '',
          '',
          'def tao_no(x, y):',
          '    ra = []',
          '    for i in range(26):',
          '        ra.append({',
          '            "x": float(x), "y": float(y),',
          '            "vx": random.uniform(-5, 5),',
          '            "vy": random.uniform(-5, 2),',
          '            "doi": random.randint(24, 46),',
          '            "doi_goc": 46,',
          '            "mau": random.choice(BANG_MAU),',
          '            "r": random.randint(3, 6),',
          '        })',
          '    return ra',
          '',
          '',
          'dang_chay = True',
          'while dang_chay:',
          '    for su_kien in pygame.event.get():',
          '        if su_kien.type == pygame.QUIT:',
          '            dang_chay = False',
          '        elif su_kien.type == pygame.KEYDOWN:',
          '            if su_kien.key == pygame.K_e:',
          '                bat_hieu_ung = not bat_hieu_ung',
          '        elif su_kien.type == pygame.MOUSEBUTTONDOWN:',
          '            x, y = su_kien.pos',
          '            diem += 10',
          '            chu_bay.append([x, float(y), "+10", 45])',
          '            if bat_hieu_ung:',
          '                hat.extend(tao_no(x, y))',
          '                rung = 9',
          '',
          '    # --- Cap nhat hat ---',
          '    con_lai = []',
          '    for h in hat:',
          '        h["x"] += h["vx"]',
          '        h["y"] += h["vy"]',
          '        h["vy"] += 0.16',
          '        h["doi"] -= 1',
          '        if h["doi"] > 0:',
          '            con_lai.append(h)',
          '    hat = con_lai',
          '',
          '    # --- Cap nhat chu bay ---',
          '    con_lai = []',
          '    for c in chu_bay:',
          '        c[1] -= 1.4',
          '        c[3] -= 1',
          '        if c[3] > 0:',
          '            con_lai.append(c)',
          '    chu_bay = con_lai',
          '',
          '    # --- Rung man hinh ---',
          '    lech_x = lech_y = 0',
          '    if rung > 0:',
          '        lech_x = random.randint(-rung, rung)',
          '        lech_y = random.randint(-rung, rung)',
          '        rung -= 1',
          '',
          '    # ===== VE =====',
          '    man_hinh.fill((24, 24, 44))',
          '',
          '    for h in hat:',
          '        do_dam = max(0, min(255, int(255 * h["doi"] / h["doi_goc"])))',
          '        be_mat = pygame.Surface((h["r"] * 2, h["r"] * 2), pygame.SRCALPHA)',
          '        pygame.draw.circle(be_mat, (*h["mau"], do_dam), (h["r"], h["r"]), h["r"])',
          '        man_hinh.blit(be_mat, (h["x"] - h["r"] + lech_x, h["y"] - h["r"] + lech_y))',
          '',
          '    for x, y, noi_dung, tg in chu_bay:',
          '        anh_chu = font.render(noi_dung, True, (241, 196, 15))',
          '        anh_chu.set_alpha(int(255 * tg / 45))',
          '        man_hinh.blit(anh_chu, (x - 16 + lech_x, y + lech_y))',
          '',
          '    man_hinh.blit(font.render(f"Diem: {diem}", True, (255, 255, 255)), (14, 12))',
          '    man_hinh.blit(font_nho.render(',
          '        f"Bam chuot de no  ·  E de {\'tat\' if bat_hieu_ung else \'bat\'} hieu ung",',
          '        True, (170, 170, 200)), (14, 44))',
          '    man_hinh.blit(font_nho.render(f"So hat dang song: {len(hat)}", True, (120, 120, 150)),',
          '                  (14, CAO - 30))',
          '',
          '    pygame.display.flip()',
          '    dong_ho.tick(60)',
          '',
          'pygame.quit()',
        ], {
          output:
            'Bấm chuột tạo vụ nổ nhiều màu, chữ "+10" bay lên mờ dần, màn hình rung nhẹ. Phím E tắt/bật hiệu ứng.',
          notes: [
            'Hạt có `vy += 0.16` nên rơi xuống như thật — chính là trọng lực của buổi 11 áp dụng cho hiệu ứng.',
            '`(*h["mau"], do_dam)` ghép tuple màu 3 số với độ đục thành tuple 4 số.',
            'Phím E cho phép tắt hiệu ứng — một chi tiết dễ tiếp cận mà rất ít bài tập học sinh có.',
            '"So hat dang song" giảm về 0 sau mỗi vụ nổ, chứng tỏ không rò rỉ.',
          ],
        }),
        playground('Sân chơi: hoàn thiện game của em', [
          'Mở dự án của em và thêm ít nhất **ba** thứ sau:',
          '',
          '- Hiệu ứng hạt khi có va chạm quan trọng',
          '- Chữ bay lên khi được điểm',
          '- Rung màn hình nhẹ khi trúng đòn (kèm tuỳ chọn tắt)',
          '- Bảng màu thống nhất 4–6 màu',
          '- Dòng hướng dẫn điều khiển ở màn menu',
          '- Phân biệt đối tượng bằng **cả** màu lẫn hình dạng',
        ], [
          '# Chep gia tri BANG_MAU nay vao du an cua em',
          'BANG_MAU = {',
          '    "nen":      (24, 24, 44),',
          '    "nhan_vat": (46, 204, 113),',
          '    "dich":     (231, 76, 60),',
          '    "vat_pham": (241, 196, 15),',
          '    "chu":      (236, 240, 241),',
          '    "phu":      (149, 165, 166),',
          '}',
          '',
          '# Kiem tra danh sach:',
          '# [ ] Moi hanh dong deu co phan hoi',
          '# [ ] Chu it nhat 18px',
          '# [ ] Phan biet bang ca mau lan hinh dang',
          '# [ ] Co dong huong dan dieu khien',
          '# [ ] Co the tat hieu ung manh',
        ], 'Dự án có ít nhất ba cải tiến về trải nghiệm và vẫn chạy ổn định.'),
        quizBlock({
          slug: 'q-pg-b28-trai-nghiem',
          title: 'Kiểm tra nhanh: trải nghiệm người chơi',
          questions: [
            {
              type: 'MULTIPLE_CHOICE',
              prompt:
                'Vì sao không nên phân biệt kẻ địch và đồng minh **chỉ** bằng màu đỏ và xanh lá?',
              explanation:
                'Nhiều người khó phân biệt hai màu này. Thêm khác biệt về hình dạng để ai cũng chơi được.',
              choices: [
                { text: 'Vì nhiều người khó phân biệt đỏ với xanh lá', isCorrect: true },
                { text: 'Vì hai màu đó làm game chạy chậm' },
                { text: 'Vì Pygame không vẽ được màu đỏ chuẩn' },
                { text: 'Vì hai màu đó khó phối với nhau' },
              ],
            },
            {
              type: 'MULTIPLE_CHOICE',
              prompt: 'Người chơi bấm nút bắn nhưng không thấy gì xảy ra ngay. Hậu quả gì?',
              explanation:
                'Không có phản hồi tức thì, người chơi sẽ nghĩ game bị lỗi hoặc nút không hoạt động.',
              choices: [
                { text: 'Người chơi tưởng game bị lỗi', isCorrect: true },
                { text: 'Game chạy nhanh hơn vì đỡ phải vẽ' },
                { text: 'Không sao cả, miễn là đạn có bay ra' },
                { text: 'Điểm số sẽ bị tính sai' },
              ],
            },
            {
              type: 'TRUE_FALSE',
              prompt: 'Rung màn hình càng mạnh thì game càng hay.',
              explanation:
                'Sai. Rung quá mạnh gây khó chịu, khó nhìn, và ảnh hưởng tới người nhạy cảm với chuyển động. ' +
                'Nên rung nhẹ và cho phép tắt.',
              choices: [{ text: 'Đúng' }, { text: 'Sai', isCorrect: true }],
            },
          ],
        }),
      ],
    },

    {
      order: 29,
      slug: 'pg-b29-dong-goi-va-nop-du-an',
      title: 'Đóng gói & nộp dự án cá nhân',
      summary:
        'Game chạy trên máy em chưa đủ — nó phải chạy được trên máy người khác. Buổi này lo phần đó.',
      objectives: [
        'Tổ chức thư mục dự án gọn gàng',
        'Dùng đường dẫn tương đối để game chạy được ở mọi máy',
        'Viết tệp README mô tả dự án',
        'Kiểm tra dự án trước khi nộp',
      ],
      difficulty: 3,
      status: 'REQUIRED',
      teacherNotes:
        'Lỗi số một khi nộp bài là đường dẫn tuyệt đối tới thư mục trên máy học sinh. ' +
        'Nhấn mạnh phần này.',
      blocks: [
        theory('Cấu trúc thư mục dự án', [
          '```',
          'game_cua_em/',
          '├── main.py              ← tep chay chinh',
          '├── cai_dat.py           ← hang so, bang mau',
          '├── nhan_vat.py          ← cac lop Sprite',
          '├── README.md            ← mo ta du an',
          '├── tai_nguyen/',
          '│   ├── anh/',
          '│   │   ├── nhan_vat.png',
          '│   │   └── ke_dich.png',
          '│   └── am_thanh/',
          '│       ├── nhay.wav',
          '│       └── nhac_nen.ogg',
          '└── du_lieu/',
          '    └── diem_cao.json',
          '```',
          '',
          '**Ba quy tắc:**',
          '',
          '1. Tệp chạy chính luôn tên `main.py` — người khác biết ngay phải chạy tệp nào',
          '2. Tài nguyên (ảnh, âm thanh) nằm trong thư mục riêng, không vứt lẫn với code',
          '3. Tên tệp không dấu, không khoảng trắng — dùng `nhan_vat.png`, đừng dùng `nhân vật.png`',
        ], [
          'Tệp chạy chính đặt tên `main.py`',
          'Tài nguyên để trong thư mục riêng',
          'Tên tệp không dấu, không khoảng trắng',
        ]),
        theory('Đường dẫn tương đối — lỗi số một khi nộp bài', [
          'Đây là lỗi khiến game chạy hoàn hảo trên máy em nhưng hỏng ngay trên máy thầy cô:',
          '',
          '```python',
          '# SAI: duong dan tuyet doi - chi ton tai tren may cua em',
          'anh = pygame.image.load("D:/BaiTap/game_cua_em/tai_nguyen/anh/nhan_vat.png")',
          '',
          '# TAM DUOC: duong dan tuong doi - phu thuoc thu muc dang chay',
          'anh = pygame.image.load("tai_nguyen/anh/nhan_vat.png")',
          '',
          '# TOT NHAT: tinh tu vi tri cua chinh tep .py',
          'import os',
          '',
          'THU_MUC = os.path.dirname(os.path.abspath(__file__))',
          'DUONG_DAN_ANH = os.path.join(THU_MUC, "tai_nguyen", "anh")',
          '',
          'anh = pygame.image.load(os.path.join(DUONG_DAN_ANH, "nhan_vat.png"))',
          '```',
          '',
          'Cách thứ ba luôn đúng dù người chơi chạy game từ thư mục nào. `os.path.join()` cũng tự ' +
            'xử lý khác biệt giữa `/` và `\\` trên các hệ điều hành.',
          '',
          '**Luôn bọc phần tải tài nguyên trong `try`/`except`** để thiếu một tệp không làm chết cả game:',
          '',
          '```python',
          'def tai_anh(ten):',
          '    duong_dan = os.path.join(DUONG_DAN_ANH, ten)',
          '    try:',
          '        return pygame.image.load(duong_dan).convert_alpha()',
          '    except (pygame.error, FileNotFoundError):',
          '        print(f"Canh bao: khong tim thay {duong_dan}")',
          '        thay_the = pygame.Surface((40, 40), pygame.SRCALPHA)',
          '        thay_the.fill((255, 0, 255))       # mau hong de de thay',
          '        return thay_the',
          '```',
          '',
          'Màu hồng chói là quy ước phổ biến trong ngành game để đánh dấu "thiếu tài nguyên".',
        ], [
          'KHÔNG BAO GIỜ dùng đường dẫn tuyệt đối',
          '`os.path.dirname(os.path.abspath(__file__))` cho thư mục của tệp',
          '`os.path.join()` để ghép đường dẫn đúng trên mọi hệ điều hành',
          'Bọc tải tài nguyên trong try/except, có ảnh thay thế',
        ]),
        example('Bộ tải tài nguyên an toàn', 'Chép nguyên đoạn này vào dự án của em.', [
          'import os',
          'import pygame',
          '',
          'pygame.init()',
          'pygame.mixer.init()',
          '',
          '# ===== DUONG DAN =====',
          'THU_MUC = os.path.dirname(os.path.abspath(__file__))',
          'DUONG_DAN_ANH = os.path.join(THU_MUC, "tai_nguyen", "anh")',
          'DUONG_DAN_AM = os.path.join(THU_MUC, "tai_nguyen", "am_thanh")',
          'DUONG_DAN_DU_LIEU = os.path.join(THU_MUC, "du_lieu")',
          '',
          '',
          'def tai_anh(ten, kich_thuoc=None):',
          '    """Tai anh, tra ve hinh thay the mau hong neu thieu tep."""',
          '    duong_dan = os.path.join(DUONG_DAN_ANH, ten)',
          '    try:',
          '        anh = pygame.image.load(duong_dan).convert_alpha()',
          '    except (pygame.error, FileNotFoundError):',
          '        print(f"[Canh bao] Thieu anh: {duong_dan}")',
          '        anh = pygame.Surface(kich_thuoc or (40, 40), pygame.SRCALPHA)',
          '        anh.fill((255, 0, 255))',
          '        return anh',
          '',
          '    if kich_thuoc:',
          '        anh = pygame.transform.scale(anh, kich_thuoc)',
          '    return anh',
          '',
          '',
          'class AmThanhRong:',
          '    """Dung thay Sound khi thieu tep - goi play() khong bi loi."""',
          '',
          '    def play(self):',
          '        pass',
          '',
          '    def set_volume(self, v):',
          '        pass',
          '',
          '',
          'def tai_am_thanh(ten, am_luong=0.4):',
          '    duong_dan = os.path.join(DUONG_DAN_AM, ten)',
          '    try:',
          '        am = pygame.mixer.Sound(duong_dan)',
          '        am.set_volume(am_luong)',
          '        return am',
          '    except (pygame.error, FileNotFoundError):',
          '        print(f"[Canh bao] Thieu am thanh: {duong_dan}")',
          '        return AmThanhRong()',
          '',
          '',
          '# ===== SU DUNG =====',
          'man_hinh = pygame.display.set_mode((640, 400))',
          'pygame.display.set_caption("Bo tai tai nguyen")',
          'dong_ho = pygame.time.Clock()',
          '',
          'anh_nv = tai_anh("nhan_vat.png", (48, 48))',
          'tieng_nhay = tai_am_thanh("nhay.wav")',
          '',
          'x = 100',
          'dang_chay = True',
          'while dang_chay:',
          '    for su_kien in pygame.event.get():',
          '        if su_kien.type == pygame.QUIT:',
          '            dang_chay = False',
          '        elif su_kien.type == pygame.KEYDOWN:',
          '            if su_kien.key == pygame.K_SPACE:',
          '                tieng_nhay.play()      # khong loi du thieu tep',
          '',
          '    phim = pygame.key.get_pressed()',
          '    if phim[pygame.K_LEFT]:',
          '        x -= 5',
          '    if phim[pygame.K_RIGHT]:',
          '        x += 5',
          '',
          '    man_hinh.fill((28, 28, 50))',
          '    man_hinh.blit(anh_nv, (x, 180))',
          '    pygame.display.flip()',
          '    dong_ho.tick(60)',
          '',
          'pygame.quit()',
        ], {
          output:
            'Game chạy bình thường ngay cả khi chưa có tệp ảnh hay âm thanh — hiện ô hồng thay thế và in cảnh báo ra terminal.',
          notes: [
            'Lớp `AmThanhRong` có sẵn `play()` rỗng, nên phần code gọi `tieng_nhay.play()` không cần ' +
              'kiểm tra `if` ở mọi chỗ.',
            'Đây là kỹ thuật "đối tượng rỗng" — thay vì trả về `None` rồi phải kiểm tra khắp nơi, ' +
              'trả về một đối tượng làm-không-gì.',
            'Màu hồng chói giúp em phát hiện ngay ảnh nào bị thiếu khi chạy thử.',
          ],
        }),
        playground('Sân chơi: danh sách kiểm tra trước khi nộp', [
          'Chạy qua danh sách này với dự án của em. **Mỗi mục phải tự tay kiểm tra**, đừng chỉ đọc lướt.',
          '',
          'Cách kiểm tra tốt nhất: **sao chép cả thư mục dự án sang một chỗ khác** (ví dụ Desktop) ' +
            'rồi chạy lại từ đó. Nếu vẫn chạy được, đường dẫn của em ổn.',
        ], [
          '# ===== DANH SACH KIEM TRA TRUOC KHI NOP =====',
          '',
          '# [ ] Tep chay chinh ten main.py',
          '# [ ] KHONG con duong dan tuyet doi nao (tim chuoi "C:/" hoac "D:/")',
          '# [ ] Da chep thu muc sang cho khac va chay thu -> van chay duoc',
          '# [ ] Tat CHE_DO_GO_LOI',
          '# [ ] Xoa cac dong print() go loi khong can thiet',
          '# [ ] Game dong duoc bang nut X ma khong bao loi',
          '# [ ] Choi thu tu dau den cuoi mot lan, khong crash',
          '# [ ] Thu bam lung tung (bam nhieu phim cung luc) -> khong crash',
          '# [ ] Co README.md mo ta cach choi',
          '# [ ] Ten tep khong dau, khong khoang trang',
          '# [ ] Thu xoa mot tep anh -> game van chay (co hinh thay the)',
        ], 'Tất cả các mục đều được tự tay kiểm tra và đánh dấu xong.'),
        resources('Mẫu README cho dự án', [
          {
            label: 'Markdown cơ bản (cú pháp viết README)',
            url: 'https://www.markdownguide.org/basic-syntax/',
          },
          { label: 'Tài liệu chính thức Pygame', url: 'https://www.pygame.org/docs/' },
          { label: 'Tài nguyên đồ hoạ, âm thanh miễn phí', url: 'https://opengameart.org/' },
        ]),
        projectBlock(
          'Nộp dự án cá nhân',
          [
            'Nộp toàn bộ thư mục dự án (nén thành `.zip`) kèm tệp `README.md`.',
            '',
            '**README.md cần có:**',
            '',
            '```markdown',
            '# Ten game cua em',
            '',
            '## Gioi thieu',
            'Mot doan ngan ve game: the loai, muc tieu cua nguoi choi.',
            '',
            '## Cach choi',
            '- Mui ten trai/phai: di chuyen',
            '- CACH: nhay',
            '- ESC: tam dung',
            '',
            '## Cach chay',
            '1. Cai dat: `pip install pygame-ce`',
            '2. Chay: `python main.py`',
            '',
            '## Nhung gi em da lam duoc',
            '- ...',
            '',
            '## Phan kho nhat va cach em giai quyet',
            '- ...',
            '```',
            '',
            '**Thầy cô sẽ xem theo bốn tiêu chí:**',
            '',
            '| Tiêu chí | Nội dung |',
            '|---|---|',
            '| Chạy được | Game khởi động và chơi được từ đầu đến cuối, không crash |',
            '| Kỹ thuật | Áp dụng đúng sprite, va chạm, trạng thái, tổ chức code |',
            '| Trải nghiệm | Có phản hồi, HUD rõ ràng, hướng dẫn điều khiển |',
            '| Hoàn thiện | Đường dẫn tương đối, README đầy đủ, không còn code gỡ lỗi |',
          ],
          'CUSTOM',
          [
            'Tổ chức lại thư mục theo cấu trúc chuẩn',
            'Chuyển hết sang đường dẫn tương đối và kiểm tra bằng cách chép sang chỗ khác',
            'Viết README.md',
            'Chạy hết danh sách kiểm tra rồi nén và nộp',
          ],
          { minutes: 60 },
        ),
      ],
    },

    {
      order: 30,
      slug: 'pg-b30-trinh-bay-va-tong-ket',
      title: 'Trình bày dự án & tổng kết khoá học',
      summary:
        'Buổi cuối cùng: chơi game của nhau, trình bày sản phẩm của mình, và nhìn lại 30 buổi đã qua.',
      objectives: [
        'Trình bày được dự án của mình một cách rõ ràng',
        'Nhận xét dự án của bạn theo hướng xây dựng',
        'Hệ thống lại toàn bộ kiến thức 30 buổi',
        'Xác định hướng học tiếp',
      ],
      difficulty: 2,
      status: 'REQUIRED',
      teacherNotes:
        'Dành ít nhất nửa buổi cho học sinh chơi game của nhau — đây là phần các em nhớ nhất. ' +
        'Nhấn mạnh cách góp ý xây dựng.',
      blocks: [
        theory('Trình bày dự án trong ba phút', [
          'Ba phút là đủ nếu em đi theo bốn bước này:',
          '',
          '| Thời lượng | Nội dung | Ví dụ |',
          '|---|---|---|',
          '| 30 giây | **Giới thiệu** — game là gì, người chơi làm gì | "Em làm game platformer, người chơi thu thập chìa khoá để mở cửa" |',
          '| 60 giây | **Trình diễn** — chơi thử, chỉ ra điểm hay | Chơi thật, vừa chơi vừa nói |',
          '| 60 giây | **Kỹ thuật** — phần em tự hào nhất | "Kẻ địch tự quay đầu ở mép bệ nhờ điểm thăm dò" |',
          '| 30 giây | **Bài học** — phần khó nhất và cách em vượt qua | "Nhân vật lọt sàn, em phát hiện tốc độ rơi lớn hơn kích thước ô" |',
          '',
          '💡 **Chuẩn bị trước một tình huống dự phòng.** Nếu game bị lỗi ngay lúc trình bày, ' +
            'hãy có sẵn ảnh chụp màn hình. Đó cũng là một bài học nghề nghiệp.',
          '',
          '**Cách góp ý cho bạn — quy tắc "hai khen một hỏi":**',
          '',
          '1. Một điều em thích: *"Hiệu ứng nổ đẹp quá"*',
          '2. Một điều em thấy ấn tượng về kỹ thuật: *"Camera cuộn rất mượt"*',
          '3. Một câu hỏi mở: *"Bạn định thêm gì tiếp theo?"*',
          '',
          'Hỏi thay vì chê. *"Bạn nghĩ sao nếu nhân vật đi nhanh hơn một chút?"* dễ nghe và ' +
            'hữu ích hơn *"nhân vật đi chậm quá"* rất nhiều.',
        ], [
          'Bốn bước: giới thiệu → trình diễn → kỹ thuật → bài học',
          'Chuẩn bị ảnh chụp màn hình phòng khi game lỗi',
          'Góp ý theo quy tắc hai khen một hỏi',
        ]),
        theory('Bản đồ 30 buổi', [
          '| Module | Buổi | Em đã học được gì |',
          '|---|---|---|',
          '| 1 | 1–4 | Game loop, hệ toạ độ, biến điều khiển hình vẽ, điều khiển bàn phím |',
          '| 2 | 5–8 | FPS, vẽ hình và ảnh, sự kiện, Sprite và Group |',
          '| 3 | 9–16 | Chuyển động, gia tốc, trọng lực, va chạm, HUD, menu, dự án Pong |',
          '| 4 | 17–26 | Tile map, platformer, camera, AI, power-up, ba buổi tổng hợp |',
          '| 5 | 27–30 | Gỡ lỗi, tối ưu, hoàn thiện, đóng gói, trình bày |',
          '',
          '**Nhưng thứ quan trọng nhất không nằm trong bảng trên.** Điều em thật sự học được là:',
          '',
          '- **Chia nhỏ vấn đề lớn.** Một trò chơi hoàn chỉnh trông bất khả thi, nhưng tám bước nhỏ thì làm được.',
          '- **Chạy thử sau mỗi bước.** Kỹ năng này áp dụng cho mọi việc, không riêng lập trình.',
          '- **Đọc lỗi thay vì sợ lỗi.** Thông báo lỗi là bạn, không phải kẻ thù.',
          '- **Làm cho người khác dùng.** Game của em có người khác chơi — đó là khác biệt lớn nhất ' +
            'so với bài tập chỉ để nộp.',
        ], [
          'Năm module, 30 buổi, từ cửa sổ trống tới trò chơi hoàn chỉnh',
          'Kỹ năng lớn nhất: chia nhỏ vấn đề và chạy thử liên tục',
          'Game của em có người thật chơi — đó là điều đáng nhớ nhất',
        ]),
        example('Danh sách kỹ thuật em đã dùng', 'Đọc qua và tự đánh dấu — em sẽ bất ngờ vì mình biết nhiều thế nào.', [
          '# ===== EM DA LAM DUOC TAT CA NHUNG THU NAY =====',
          '',
          'ky_thuat = {',
          '    "Nen tang": [',
          '        "Game loop 60 FPS",',
          '        "He toa do man hinh",',
          '        "Xu ly su kien QUIT, KEYDOWN, MOUSEBUTTONDOWN",',
          '        "Ve hinh: rect, circle, polygon, line",',
          '        "Tai va bien doi anh",',
          '    ],',
          '    "Sprite": [',
          '        "Lop ke thua pygame.sprite.Sprite",',
          '        "Group.update() va Group.draw()",',
          '        "sprite.kill() de don dep",',
          '    ],',
          '    "Chuyen dong": [',
          '        "Van toc theo hai truc",',
          '        "Gia toc va ma sat",',
          '        "Trong luc va co che nhay",',
          '        "Coyote time",',
          '    ],',
          '    "Va cham": [',
          '        "colliderect va collidepoint",',
          '        "spritecollide va groupcollide",',
          '        "Tach hai truc de day ra dung huong",',
          '        "Bat tu tam thoi",',
          '    ],',
          '    "The gioi game": [',
          '        "Tile map tu danh sach chuoi",',
          '        "Camera bam muot va kep o mep",',
          '        "AI di tuan va duoi theo",',
          '        "May trang thai cho ke dich",',
          '        "Power-up co thoi han",',
          '        "Nhieu man choi va luu tien do JSON",',
          '    ],',
          '    "Hoan thien": [',
          '        "HUD: diem, mang, thanh mau",',
          '        "Am thanh va nhac nen",',
          '        "Menu va man tam dung",',
          '        "Hieu ung hat, chu bay, rung man hinh",',
          '        "Bang go loi tren man hinh",',
          '        "Duong dan tuong doi va tai nguyen an toan",',
          '    ],',
          '}',
          '',
          'tong = 0',
          'for nhom, danh_sach in ky_thuat.items():',
          '    print(f"\\n{nhom} ({len(danh_sach)} ky thuat)")',
          '    for kt in danh_sach:',
          '        print(f"  [x] {kt}")',
          '    tong += len(danh_sach)',
          '',
          'print(f"\\n=> Tong cong: {tong} ky thuat trong 30 buoi.")',
        ], {
          output: [
            'Nen tang (5 ky thuat)',
            '  [x] Game loop 60 FPS',
            '  ...',
            '',
            '=> Tong cong: 26 ky thuat trong 30 buoi.',
          ].join('\n'),
          notes: [
            'Đoạn code này cũng là một bài ôn tập nhỏ: từ điển chứa danh sách, `.items()`, vòng lặp lồng nhau.',
            'Hãy chạy thử và tự đánh dấu những kỹ thuật em thấy mình đã thật sự nắm.',
          ],
        }),
        playground('Sân chơi: hồ sơ dự án của em', [
          'Viết một đoạn code nhỏ in ra "danh thiếp" cho dự án của em.',
          '',
          'Đây vừa là ôn tập từ điển và f-string, vừa là tư liệu cho phần trình bày.',
        ], [
          'du_an = {',
          '    "ten": "...",',
          '    "the_loai": "...",',
          '    "so_dong_code": 0,',
          '    "thoi_gian_lam": "... buoi",',
          '    "ky_thuat_tu_hao_nhat": "...",',
          '    "phan_kho_nhat": "...",',
          '    "neu_co_them_thoi_gian": "...",',
          '}',
          '',
          'print("=" * 46)',
          'print(f"  {du_an[\'ten\'].upper()}")',
          'print("=" * 46)',
          'for khoa, gia_tri in du_an.items():',
          '    if khoa != "ten":',
          '        nhan = khoa.replace("_", " ").capitalize()',
          '        print(f"  {nhan:<26}: {gia_tri}")',
          'print("=" * 46)',
        ], 'In được danh thiếp dự án đầy đủ và dùng nó cho phần trình bày.'),
        challenge({
          slug: 'p-pg-b30-tong-ket-diem-du-an',
          title: 'Tổng kết điểm dự án',
          statement: [
            'Dự án được chấm theo bốn tiêu chí, mỗi tiêu chí có trọng số riêng:',
            '',
            '| Tiêu chí | Trọng số |',
            '|---|---|',
            '| Chạy được | 40% |',
            '| Kỹ thuật | 30% |',
            '| Trải nghiệm | 20% |',
            '| Hoàn thiện | 10% |',
            '',
            'Đọc **bốn số thực** trên bốn dòng (mỗi tiêu chí trên thang 10), theo đúng thứ tự bảng trên.',
            '',
            'In ra **hai dòng**:',
            '',
            '```',
            'Diem tong: <diem>',
            'Xep loai: <loai>',
            '```',
            '',
            '`<diem>` hiển thị **2 chữ số thập phân**. Xếp loại: từ 9.0 là `Xuat sac`, ' +
              'từ 7.5 là `Tot`, từ 6.0 là `Kha`, còn lại là `Dang hoan thien`.',
          ].join('\n'),
          hints: [
            'Điểm tổng = 0.4×a + 0.3×b + 0.2×c + 0.1×d.',
            'Xếp loại bằng chuỗi if/elif/else, sắp từ mốc cao xuống thấp.',
            'Nhớ định dạng `{diem:.2f}`.',
          ],
          starterCode: [
            'chay_duoc = float(input())',
            'ky_thuat = float(input())',
            'trai_nghiem = float(input())',
            'hoan_thien = float(input())',
            '',
            '# Tính điểm tổng có trọng số rồi xếp loại',
          ].join('\n'),
          solutionCode: [
            'chay_duoc = float(input())',
            'ky_thuat = float(input())',
            'trai_nghiem = float(input())',
            'hoan_thien = float(input())',
            '',
            'diem = (chay_duoc * 0.4 + ky_thuat * 0.3',
            '        + trai_nghiem * 0.2 + hoan_thien * 0.1)',
            '',
            'print(f"Diem tong: {diem:.2f}")',
            '',
            'if diem >= 9:',
            '    print("Xep loai: Xuat sac")',
            'elif diem >= 7.5:',
            '    print("Xep loai: Tot")',
            'elif diem >= 6:',
            '    print("Xep loai: Kha")',
            'else:',
            '    print("Xep loai: Dang hoan thien")',
          ].join('\n'),
          tier: 'CO_BAN',
          judgeMode: 'IO_MATCH',
          tests: [
            sample(
              '10\n9\n8\n7\n',
              'Diem tong: 9.10\nXep loai: Xuat sac\n',
              '4.0 + 2.7 + 1.6 + 0.7 = 9.10.',
            ),
            sample('8\n7\n6\n5\n', 'Diem tong: 7.00\nXep loai: Kha\n'),
            hidden('10\n10\n10\n10\n', 'Diem tong: 10.00\nXep loai: Xuat sac\n', 20),
            hidden('0\n0\n0\n0\n', 'Diem tong: 0.00\nXep loai: Dang hoan thien\n', 20),
            hidden('7.5\n7.5\n7.5\n7.5\n', 'Diem tong: 7.50\nXep loai: Tot\n', 30),
            hidden('6\n6\n6\n6\n', 'Diem tong: 6.00\nXep loai: Kha\n', 30),
          ],
        }),
        projectBlock(
          'Trình bày dự án cuối khoá',
          [
            'Trình bày dự án của em trước lớp trong **ba phút**, theo bốn bước đã học.',
            '',
            '**Chuẩn bị trước:**',
            '',
            '- Game đã chạy sẵn, mở sẵn ở màn menu',
            '- Ảnh chụp màn hình dự phòng',
            '- Ba câu trả lời cho: game là gì, kỹ thuật em tự hào nhất, phần khó nhất',
            '',
            '**Trong lúc bạn khác trình bày:** ghi lại một điều em thích và một câu hỏi cho mỗi bạn. ' +
              'Nộp phần ghi chú này cùng dự án.',
          ],
          'CUSTOM',
          [
            'Chuẩn bị game và ảnh dự phòng',
            'Tập trình bày ba phút theo bốn bước',
            'Trình bày trước lớp',
            'Ghi nhận xét cho ít nhất ba bạn',
          ],
          { minutes: 50 },
        ),
        reflection(
          'Nhìn lại 30 buổi Pygame',
          'Ở buổi 1, em chỉ có một cửa sổ trống. Bây giờ em có một trò chơi mà người khác chơi được. ' +
            'Hãy viết ra: (1) điều em tự hào nhất đã tự làm được, (2) một lỗi khiến em mất nhiều thời gian ' +
            'nhất và em đã hiểu ra điều gì từ nó, (3) thứ em muốn làm tiếp — game lớn hơn, hay ' +
            'khoá Python Nâng Cao?',
        ),
      ],
    },
  ],
};
