/**
 * Pygame — Module 4, phần 2 (Buổi 20–23): AI kẻ địch, power-up, nhiều màn chơi.
 */
import type { LessonSpec } from '../types.ts';
import { challenge, example, hidden, playground, quizBlock, sample, theory } from '../builders.ts';

export const pygameLessons20to23: LessonSpec[] = [
  {
    order: 20,
    slug: 'pg-b20-ai-ke-dich-co-ban',
    title: 'AI kẻ địch cơ bản: tuần tra & đuổi theo',
    summary:
      'Kẻ địch đứng yên thì không thành trò chơi. Hai hành vi đơn giản nhất — đi tuần và đuổi theo — ' +
      'đã đủ làm màn chơi sống động.',
    objectives: [
      'Cài đặt kẻ địch đi tuần giữa hai mốc',
      'Cho kẻ địch quay đầu khi tới mép bệ',
      'Cài đặt hành vi đuổi theo người chơi trong tầm phát hiện',
      'Tính khoảng cách giữa hai đối tượng',
    ],
    difficulty: 4,
    status: 'REQUIRED',
    teacherNotes: 'AI ở đây chỉ là if/else — nhấn mạnh để học sinh không thấy "AI" là thứ đáng sợ.',
    blocks: [
      theory('AI trong game chỉ là if/else', [
        'Đừng để chữ "AI" làm em sợ. Kẻ địch trong game 2D thường chỉ là vài câu `if`.',
        '',
        '**Hành vi 1 — đi tuần giữa hai mốc:**',
        '',
        '```python',
        'dich.x += huong * TOC_DO',
        '',
        'if dich.x < moc_trai:',
        '    dich.x = moc_trai',
        '    huong = 1              # quay sang phai',
        'elif dich.x > moc_phai:',
        '    dich.x = moc_phai',
        '    huong = -1             # quay sang trai',
        '```',
        '',
        '**Hành vi 2 — quay đầu khi hết bệ** (thông minh hơn, không cần đặt mốc tay):',
        '',
        '```python',
        '# Diem tham do ngay truoc mat va thap hon mot chut',
        'tham_do_x = dich.right + 5 if huong > 0 else dich.left - 5',
        'diem_tham_do = (tham_do_x, dich.bottom + 5)',
        '',
        'co_nen_phia_truoc = False',
        'for o in nen:',
        '    if o.collidepoint(diem_tham_do):',
        '        co_nen_phia_truoc = True',
        '        break',
        '',
        'if not co_nen_phia_truoc:',
        '    huong = -huong        # sap roi khoi be -> quay dau',
        '```',
        '',
        'Mẹo "điểm thăm dò" này được dùng trong rất nhiều game platformer thật.',
      ], [
        'AI cơ bản = vài câu if/else, không có gì huyền bí',
        'Đi tuần: đổi hướng khi chạm mốc',
        'Thăm dò nền phía trước để tự quay đầu ở mép bệ',
      ]),
      theory('Đuổi theo và tầm phát hiện', [
        '**Khoảng cách giữa hai đối tượng** — dùng định lý Pytago:',
        '',
        '```python',
        'import math',
        '',
        'dx = nv.centerx - dich.centerx',
        'dy = nv.centery - dich.centery',
        'khoang_cach = math.hypot(dx, dy)     # bang math.sqrt(dx*dx + dy*dy)',
        '```',
        '',
        '`math.hypot()` gọn hơn và chính xác hơn việc tự viết căn bậc hai.',
        '',
        '**Đuổi theo khi trong tầm:**',
        '',
        '```python',
        'TAM_PHAT_HIEN = 220',
        '',
        'if khoang_cach < TAM_PHAT_HIEN:',
        '    # Duoi theo: di chuyen ve phia nguoi choi',
        '    if dx > 0:',
        '        dich.x += TOC_DO_DUOI',
        '    elif dx < 0:',
        '        dich.x -= TOC_DO_DUOI',
        'else:',
        '    # Ngoai tam -> quay ve di tuan',
        '    dich.x += huong * TOC_DO_TUAN',
        '```',
        '',
        '💡 **Mẹo so sánh nhanh:** nếu chỉ cần biết "có trong tầm không", so sánh **bình phương** ' +
          'khoảng cách để khỏi phải tính căn:',
        '',
        '```python',
        'if dx * dx + dy * dy < TAM_PHAT_HIEN ** 2:',
        '```',
        '',
        'Với vài chục kẻ địch thì không khác biệt, nhưng với hàng nghìn thì đáng kể.',
      ], [
        '`math.hypot(dx, dy)` cho khoảng cách',
        'So sánh bình phương khoảng cách để khỏi tính căn',
        'Trong tầm thì đuổi, ngoài tầm thì quay về tuần tra',
      ]),
      example('Hai kẻ địch, hai hành vi', 'Kẻ địch đỏ đi tuần, kẻ địch tím đuổi theo khi em lại gần.', [
        'import pygame',
        'import math',
        '',
        'pygame.init()',
        'RONG, CAO = 800, 500',
        'man_hinh = pygame.display.set_mode((RONG, CAO))',
        'pygame.display.set_caption("AI ke dich")',
        'dong_ho = pygame.time.Clock()',
        'font = pygame.font.SysFont("arial", 16)',
        '',
        'MAT_DAT = 420',
        'nv = pygame.Rect(60, MAT_DAT - 40, 30, 40)',
        '',
        '# Ke dich 1: di tuan',
        'tuan = pygame.Rect(300, MAT_DAT - 34, 34, 34)',
        'tuan_huong = 1',
        'MOC_TRAI, MOC_PHAI = 250, 520',
        '',
        '# Ke dich 2: duoi theo',
        'san = pygame.Rect(650, MAT_DAT - 34, 34, 34)',
        'san_huong = -1',
        'TAM_PHAT_HIEN = 220',
        '',
        'dang_chay = True',
        'while dang_chay:',
        '    for su_kien in pygame.event.get():',
        '        if su_kien.type == pygame.QUIT:',
        '            dang_chay = False',
        '',
        '    phim = pygame.key.get_pressed()',
        '    if phim[pygame.K_LEFT]:',
        '        nv.x -= 6',
        '    if phim[pygame.K_RIGHT]:',
        '        nv.x += 6',
        '    nv.clamp_ip(man_hinh.get_rect())',
        '',
        '    # --- AI 1: di tuan ---',
        '    tuan.x += tuan_huong * 3',
        '    if tuan.left < MOC_TRAI:',
        '        tuan.left = MOC_TRAI',
        '        tuan_huong = 1',
        '    elif tuan.right > MOC_PHAI:',
        '        tuan.right = MOC_PHAI',
        '        tuan_huong = -1',
        '',
        '    # --- AI 2: duoi theo khi trong tam ---',
        '    dx = nv.centerx - san.centerx',
        '    dy = nv.centery - san.centery',
        '    khoang_cach = math.hypot(dx, dy)',
        '    dang_duoi = khoang_cach < TAM_PHAT_HIEN',
        '',
        '    if dang_duoi:',
        '        if dx > 2:',
        '            san.x += 4',
        '        elif dx < -2:',
        '            san.x -= 4',
        '    else:',
        '        san.x += san_huong * 2',
        '        if san.left < 560 or san.right > 780:',
        '            san_huong = -san_huong',
        '            san.clamp_ip(pygame.Rect(560, 0, 220, CAO))',
        '',
        '    # ===== VE =====',
        '    man_hinh.fill((30, 30, 55))',
        '    pygame.draw.rect(man_hinh, (60, 70, 90), (0, MAT_DAT, RONG, CAO - MAT_DAT))',
        '',
        '    # Ve tam phat hien cua ke dich san',
        '    pygame.draw.circle(man_hinh, (120, 60, 140) if dang_duoi else (60, 60, 90),',
        '                       san.center, TAM_PHAT_HIEN, 2)',
        '',
        '    pygame.draw.line(man_hinh, (80, 80, 110), (MOC_TRAI, MAT_DAT), (MOC_PHAI, MAT_DAT), 4)',
        '    pygame.draw.rect(man_hinh, (231, 76, 60), tuan, 0, border_radius=5)',
        '    pygame.draw.rect(man_hinh, (155, 89, 182), san, 0, border_radius=5)',
        '    pygame.draw.rect(man_hinh, (46, 204, 113), nv, 0, border_radius=5)',
        '',
        '    man_hinh.blit(font.render(',
        '        f"Khoang cach toi ke san: {khoang_cach:.0f}   Dang duoi: {dang_duoi}",',
        '        True, (200, 200, 225)), (10, 10))',
        '',
        '    pygame.display.flip()',
        '    dong_ho.tick(60)',
        '',
        'pygame.quit()',
      ], {
        output:
          'Ô đỏ đi tới đi lui trong đoạn cố định; ô tím có vòng tròn tầm phát hiện, sáng lên và đuổi theo khi em lại gần.',
        notes: [
          'Vẽ vòng tròn tầm phát hiện ra màn hình giúp gỡ lỗi AI cực nhanh — thấy ngay vì sao nó đuổi hay không.',
          'Điều kiện `dx > 2` thay vì `dx > 0` tránh kẻ địch rung lắc qua lại khi đứng gần đúng vị trí.',
          'Khi ra khỏi tầm, kẻ địch tím quay lại tuần tra chứ không đứng chết — chi tiết nhỏ làm nó "sống" hơn.',
        ],
      }),
      playground('Sân chơi: kẻ địch của em', [
        'Thử ba biến thể:',
        '',
        '1. **Kẻ địch nhát gan** — chạy *ra xa* người chơi thay vì lại gần (đổi dấu)',
        '2. **Kẻ địch có giới hạn** — chỉ đuổi trong khu vực của nó, ra khỏi thì quay về',
        '3. **Kẻ địch tăng tốc** — càng gần càng chạy nhanh',
        '',
        'Nhớ vẽ vòng tròn tầm phát hiện để thấy AI đang "nghĩ" gì.',
      ], [
        'import pygame',
        'import math',
        '',
        'pygame.init()',
        'man_hinh = pygame.display.set_mode((800, 500))',
        'dong_ho = pygame.time.Clock()',
        '',
        'nv = pygame.Rect(100, 380, 30, 40)',
        'dich = pygame.Rect(600, 386, 34, 34)',
        'TAM = 250',
        '',
        'dang_chay = True',
        'while dang_chay:',
        '    for su_kien in pygame.event.get():',
        '        if su_kien.type == pygame.QUIT:',
        '            dang_chay = False',
        '',
        '    phim = pygame.key.get_pressed()',
        '    if phim[pygame.K_LEFT]:',
        '        nv.x -= 6',
        '    if phim[pygame.K_RIGHT]:',
        '        nv.x += 6',
        '',
        '    dx = nv.centerx - dich.centerx',
        '    kc = abs(dx)',
        '',
        '    if kc < TAM:',
        '        # Doi dau o day de co ke dich nhat gan',
        '        if dx > 2:',
        '            dich.x += 4',
        '        elif dx < -2:',
        '            dich.x -= 4',
        '',
        '    man_hinh.fill((30, 30, 55))',
        '    pygame.draw.circle(man_hinh, (70, 70, 100), dich.center, TAM, 2)',
        '    pygame.draw.rect(man_hinh, (231, 76, 60), dich)',
        '    pygame.draw.rect(man_hinh, (46, 204, 113), nv)',
        '    pygame.display.flip()',
        '    dong_ho.tick(60)',
        '',
        'pygame.quit()',
      ], 'Làm được ít nhất hai kiểu hành vi kẻ địch khác nhau.'),
      challenge({
        slug: 'p-pg-b20-ai-tuan-tra',
        title: 'Mô phỏng kẻ địch đi tuần',
        statement: [
          'Kẻ địch bắt đầu ở vị trí `x`, đi theo hướng `h` (`1` là phải, `-1` là trái) với tốc độ `s`.',
          '',
          'Mỗi khung hình: `x += h * s`. Sau đó, nếu `x < L` thì đặt `x = L` và `h = 1`; ' +
            'nếu `x > R` thì đặt `x = R` và `h = -1`.',
          '',
          'Dòng đầu: bốn số nguyên `x h s N`. Dòng hai: hai số nguyên `L R`.',
          '',
          'In ra **một dòng**: `<x> <h>` sau đúng `N` khung hình.',
        ].join('\n'),
        hints: [
          'Cộng trước, kiểm tra mốc sau.',
          'Nhớ đặt lại `x` về đúng mốc chứ không chỉ đổi hướng.',
          'Dùng `elif` cho mốc thứ hai để hai điều kiện không cùng chạy.',
        ],
        starterCode: [
          'x, h, s, n = map(int, input().split())',
          'l, r = map(int, input().split())',
          '',
          '# Mô phỏng n khung hình',
        ].join('\n'),
        solutionCode: [
          'x, h, s, n = map(int, input().split())',
          'l, r = map(int, input().split())',
          '',
          'for i in range(n):',
          '    x += h * s',
          '    if x < l:',
          '        x = l',
          '        h = 1',
          '    elif x > r:',
          '        x = r',
          '        h = -1',
          '',
          'print(f"{x} {h}")',
        ].join('\n'),
        tier: 'CO_BAN',
        judgeMode: 'IO_MATCH',
        tests: [
          sample('100 1 5 10\n50 200\n', '150 1\n', 'Sau 10 khung đi được 50 điểm, chưa tới mốc phải.'),
          sample('195 1 10 1\n50 200\n', '200 -1\n', '205 vượt mốc 200 nên bị kéo về 200 và quay đầu.'),
          hidden('50 -1 5 1\n50 200\n', '50 1\n', 20),
          hidden('100 1 200 3\n0 300\n', '300 -1\n', 20),
          hidden('0 1 1 10\n0 5\n', '4 -1\n', 30),
          hidden('120 -1 4 40\n100 140\n', '120 1\n', 30),
        ],
      }),
    ],
  },

  {
    order: 21,
    slug: 'pg-b21-ai-nang-cao-may-trang-thai',
    title: 'AI nâng cao: máy trạng thái & mẫu di chuyển',
    summary:
      'Kẻ địch có nhiều tính cách: đứng canh, đuổi, tấn công, rút lui. Máy trạng thái của buổi 15 ' +
      'quay lại — lần này áp dụng cho từng kẻ địch.',
    objectives: [
      'Áp dụng máy trạng thái cho hành vi kẻ địch',
      'Thiết kế điều kiện chuyển trạng thái hợp lý',
      'Tạo mẫu di chuyển theo đường sin và đường tròn',
      'Thêm độ trễ phản ứng để AI trông tự nhiên hơn',
    ],
    difficulty: 5,
    status: 'RECOMMENDED',
    teacherNotes:
      'Buổi mở rộng. Học sinh nào thấy khó có thể dừng ở AI cơ bản của buổi 20 mà vẫn làm được dự án.',
    blocks: [
      theory('Mỗi kẻ địch là một máy trạng thái', [
        'Ở buổi 15, cả trò chơi có một `trang_thai`. Giờ **mỗi kẻ địch** có `trang_thai` riêng:',
        '',
        '```',
        '  ┌──────────┐  thay nguoi choi   ┌────────┐',
        '  │  CANH    │───────────────────►│  DUOI  │',
        '  └──────────┘◄───────────────────└───┬────┘',
        '        ▲       mat dau vet          │ den rat gan',
        '        │                            ▼',
        '        │                      ┌───────────┐',
        '        └──────────────────────┤  TAN CONG │',
        '           danh xong, hoi suc  └───────────┘',
        '```',
        '',
        '```python',
        'class KeDich:',
        '    def __init__(self, x, y):',
        '        self.rect = pygame.Rect(x, y, 34, 34)',
        '        self.trang_thai = "CANH"',
        '        self.bo_dem = 0',
        '',
        '    def cap_nhat(self, nv):',
        '        kc = abs(nv.centerx - self.rect.centerx)',
        '',
        '        if self.trang_thai == "CANH":',
        '            if kc < 200:',
        '                self.trang_thai = "DUOI"',
        '',
        '        elif self.trang_thai == "DUOI":',
        '            if kc > 280:',
        '                self.trang_thai = "CANH"',
        '            elif kc < 50:',
        '                self.trang_thai = "TAN_CONG"',
        '                self.bo_dem = 40',
        '            else:',
        '                self.rect.x += 3 if nv.centerx > self.rect.centerx else -3',
        '',
        '        elif self.trang_thai == "TAN_CONG":',
        '            self.bo_dem -= 1',
        '            if self.bo_dem <= 0:',
        '                self.trang_thai = "CANH"',
        '```',
        '',
        '⚠️ Chú ý hai ngưỡng **khác nhau**: vào trạng thái DUOI ở khoảng cách 200, thoát ra ở 280. ' +
          'Nếu dùng cùng một ngưỡng, kẻ địch sẽ nhấp nháy qua lại giữa hai trạng thái khi người chơi ' +
          'đứng ngay ranh giới. Kỹ thuật này gọi là **ngưỡng trễ**.',
      ], [
        'Mỗi kẻ địch giữ `trang_thai` riêng',
        'Dùng hai ngưỡng khác nhau cho vào và ra để tránh nhấp nháy',
        'Bộ đếm `bo_dem` để trạng thái kéo dài một khoảng thời gian',
      ]),
      theory('Mẫu di chuyển đẹp mắt', [
        'Kẻ địch đi thẳng thì đơn điệu. Vài công thức toán học biến chúng thành thứ đáng nhớ:',
        '',
        '```python',
        'import math',
        '',
        '# 1. Bay theo song sin - kieu Space Invaders',
        'thoi_gian += 1',
        'dich.y = y_goc + math.sin(thoi_gian * 0.05) * 60',
        '',
        '# 2. Bay theo duong tron',
        'dich.centerx = tam_x + math.cos(thoi_gian * 0.03) * ban_kinh',
        'dich.centery = tam_y + math.sin(thoi_gian * 0.03) * ban_kinh',
        '',
        '# 3. Bay hinh so 8',
        'dich.centerx = tam_x + math.sin(thoi_gian * 0.03) * 150',
        'dich.centery = tam_y + math.sin(thoi_gian * 0.06) * 80',
        '```',
        '',
        'Đây chính là `sin` và `cos` từ buổi 17 khoá Cơ Bản — nhưng lần này em thấy được kết quả ' +
          'chuyển động trên màn hình thay vì một con số.',
        '',
        '**Ba tham số điều khiển hình dạng:**',
        '',
        '| Tham số | Vị trí trong công thức | Ảnh hưởng |',
        '|---|---|---|',
        '| Hệ số nhân thời gian | `thoi_gian * 0.05` | Nhanh chậm |',
        '| Biên độ | `* 60` | Dao động rộng hẹp |',
        '| Độ lệch pha | `sin(t + lech)` | Các kẻ địch lệch nhau |',
        '',
        'Cho mỗi kẻ địch một độ lệch pha khác nhau (`i * 0.5`) là có ngay một đàn bay uốn lượn ' +
          'so le rất đẹp.',
      ], [
        '`sin` cho dao động lên xuống, `sin` + `cos` cho đường tròn',
        'Độ lệch pha khác nhau tạo đàn bay so le',
        'Đây là lượng giác của buổi 17 khoá Cơ Bản, áp dụng thật',
      ], { tier: 'NANG_CAO' }),
      example('Đàn kẻ địch có trạng thái và mẫu bay', 'Ba kẻ địch, ba hành vi khác nhau.', [
        'import pygame',
        'import math',
        '',
        'pygame.init()',
        'RONG, CAO = 800, 500',
        'man_hinh = pygame.display.set_mode((RONG, CAO))',
        'pygame.display.set_caption("AI nang cao")',
        'dong_ho = pygame.time.Clock()',
        'font = pygame.font.SysFont("arial", 15)',
        '',
        'MAU_TRANG_THAI = {',
        '    "CANH": (149, 165, 166),',
        '    "DUOI": (230, 126, 34),',
        '    "TAN_CONG": (231, 76, 60),',
        '}',
        '',
        '',
        'class KeDich:',
        '    def __init__(self, x, y, lech_pha):',
        '        self.rect = pygame.Rect(x, y, 32, 32)',
        '        self.y_goc = y',
        '        self.lech_pha = lech_pha',
        '        self.trang_thai = "CANH"',
        '        self.bo_dem = 0',
        '        self.t = 0',
        '',
        '    def cap_nhat(self, nv):',
        '        self.t += 1',
        '        kc = abs(nv.centerx - self.rect.centerx)',
        '',
        '        if self.trang_thai == "CANH":',
        '            # Bay song sin tai cho',
        '            self.rect.y = int(self.y_goc + math.sin(self.t * 0.05 + self.lech_pha) * 45)',
        '            if kc < 200:',
        '                self.trang_thai = "DUOI"',
        '',
        '        elif self.trang_thai == "DUOI":',
        '            if kc > 280:',
        '                self.trang_thai = "CANH"',
        '            elif kc < 55:',
        '                self.trang_thai = "TAN_CONG"',
        '                self.bo_dem = 45',
        '            else:',
        '                self.rect.x += 3 if nv.centerx > self.rect.centerx else -3',
        '                self.rect.y += 1 if nv.centery > self.rect.centery else -1',
        '',
        '        elif self.trang_thai == "TAN_CONG":',
        '            self.bo_dem -= 1',
        '            self.rect.y += int(math.sin(self.bo_dem * 0.4) * 4)',
        '            if self.bo_dem <= 0:',
        '                self.trang_thai = "CANH"',
        '                self.y_goc = self.rect.y',
        '',
        '',
        'nv = pygame.Rect(400, 400, 30, 40)',
        'dich = [KeDich(120 + i * 240, 140, i * 1.2) for i in range(3)]',
        '',
        'dang_chay = True',
        'while dang_chay:',
        '    for su_kien in pygame.event.get():',
        '        if su_kien.type == pygame.QUIT:',
        '            dang_chay = False',
        '',
        '    phim = pygame.key.get_pressed()',
        '    if phim[pygame.K_LEFT]:',
        '        nv.x -= 6',
        '    if phim[pygame.K_RIGHT]:',
        '        nv.x += 6',
        '    if phim[pygame.K_UP]:',
        '        nv.y -= 5',
        '    if phim[pygame.K_DOWN]:',
        '        nv.y += 5',
        '    nv.clamp_ip(man_hinh.get_rect())',
        '',
        '    for d in dich:',
        '        d.cap_nhat(nv)',
        '',
        '    man_hinh.fill((28, 28, 50))',
        '    for d in dich:',
        '        pygame.draw.rect(man_hinh, MAU_TRANG_THAI[d.trang_thai], d.rect, 0, border_radius=6)',
        '        nhan = font.render(d.trang_thai, True, (210, 210, 230))',
        '        man_hinh.blit(nhan, nhan.get_rect(center=(d.rect.centerx, d.rect.top - 12)))',
        '',
        '    pygame.draw.rect(man_hinh, (46, 204, 113), nv, 0, border_radius=5)',
        '    pygame.display.flip()',
        '    dong_ho.tick(60)',
        '',
        'pygame.quit()',
      ], {
        output:
          'Ba kẻ địch bay uốn lượn so le, đổi màu và đổi nhãn trạng thái khi em lại gần rồi lùi ra xa.',
        notes: [
          'Nhãn trạng thái vẽ ngay trên đầu mỗi kẻ địch — cách gỡ lỗi máy trạng thái hiệu quả nhất.',
          'Ba kẻ địch có `lech_pha` khác nhau (`i * 1.2`) nên bay so le chứ không đồng loạt.',
          'Khi thoát TAN_CONG, `y_goc` được cập nhật lại để kẻ địch không nhảy vọt về chỗ cũ.',
        ],
      }),
      playground('Sân chơi: mẫu bay của em', [
        'Thay công thức `sin` trong trạng thái CANH bằng mẫu bay khác:',
        '',
        '- **Đường tròn:** cập nhật cả `x` và `y` bằng `cos` và `sin`',
        '- **Hình số 8:** dùng hai tần số khác nhau cho `x` và `y`',
        '- **Zigzag:** dùng phép `%` thay cho `sin`',
        '',
        'Đổi ba tham số (tốc độ, biên độ, lệch pha) và quan sát.',
      ], [
        'import pygame',
        'import math',
        '',
        'pygame.init()',
        'man_hinh = pygame.display.set_mode((800, 500))',
        'dong_ho = pygame.time.Clock()',
        '',
        't = 0',
        'TAM_X, TAM_Y = 400, 250',
        '',
        'dang_chay = True',
        'while dang_chay:',
        '    for su_kien in pygame.event.get():',
        '        if su_kien.type == pygame.QUIT:',
        '            dang_chay = False',
        '',
        '    t += 1',
        '',
        '    # Thu doi cong thuc o hai dong nay',
        '    x = TAM_X + math.cos(t * 0.03) * 200',
        '    y = TAM_Y + math.sin(t * 0.03) * 120',
        '',
        '    man_hinh.fill((28, 28, 50))',
        '    pygame.draw.circle(man_hinh, (155, 89, 182), (int(x), int(y)), 18)',
        '    pygame.display.flip()',
        '    dong_ho.tick(60)',
        '',
        'pygame.quit()',
      ], 'Tạo được ít nhất hai mẫu bay khác nhau bằng lượng giác.'),
      challenge({
        slug: 'p-pg-b21-chuyen-trang-thai-ai',
        title: 'Chuyển trạng thái kẻ địch',
        statement: [
          'Kẻ địch có ba trạng thái với **ngưỡng trễ**:',
          '',
          '- `CANH` → `DUOI` khi khoảng cách `< 200`',
          '- `DUOI` → `CANH` khi khoảng cách `> 280`',
          '- `DUOI` → `TAN_CONG` khi khoảng cách `< 55`',
          '- `TAN_CONG` → `CANH` khi khoảng cách `> 120`',
          '',
          'Thứ tự kiểm tra trong trạng thái `DUOI`: xét điều kiện về `CANH` **trước**, rồi mới xét ' +
            '`TAN_CONG`.',
          '',
          'Dòng đầu: số nguyên `N`. Dòng hai: `N` số nguyên là khoảng cách ở từng khung hình.',
          '',
          'Trạng thái ban đầu là `CANH`. In ra **một dòng** là trạng thái sau `N` khung hình.',
        ].join('\n'),
        hints: [
          'Giữ một biến chuỗi `trang_thai`.',
          'Mỗi khoảng cách: xét đúng nhánh của trạng thái hiện tại, và chỉ chuyển tối đa một lần.',
          'Dùng `elif` để không chuyển hai lần trong cùng một khung hình.',
        ],
        starterCode: [
          'n = int(input())',
          'kc = list(map(int, input().split()))',
          '',
          'trang_thai = "CANH"',
          'for d in kc:',
          '    # Chuyển trạng thái theo d',
          '    pass',
          '',
          'print(trang_thai)',
        ].join('\n'),
        solutionCode: [
          'n = int(input())',
          'kc = list(map(int, input().split()))',
          '',
          'trang_thai = "CANH"',
          'for d in kc:',
          '    if trang_thai == "CANH":',
          '        if d < 200:',
          '            trang_thai = "DUOI"',
          '    elif trang_thai == "DUOI":',
          '        if d > 280:',
          '            trang_thai = "CANH"',
          '        elif d < 55:',
          '            trang_thai = "TAN_CONG"',
          '    else:',
          '        if d > 120:',
          '            trang_thai = "CANH"',
          '',
          'print(trang_thai)',
        ].join('\n'),
        tier: 'NANG_CAO',
        judgeMode: 'IO_MATCH',
        tests: [
          sample('3\n300 150 40\n', 'TAN_CONG\n', 'CANH → DUOI ở 150 → TAN_CONG ở 40.'),
          sample('2\n250 260\n', 'CANH\n', '250 không nhỏ hơn 200 nên chưa rời trạng thái CANH.'),
          hidden('1\n199\n', 'DUOI\n', 20),
          hidden('4\n100 300 100 30\n', 'TAN_CONG\n', 20),
          hidden('3\n50 60 130\n', 'CANH\n', 30),
          hidden('5\n199 281 199 54 121\n', 'CANH\n', 30),
        ],
      }),
      quizBlock({
        slug: 'q-pg-b21-ai-trang-thai',
        title: 'Kiểm tra nhanh: AI có trạng thái',
        questions: [
          {
            type: 'MULTIPLE_CHOICE',
            prompt: 'Vì sao ngưỡng vào `DUOI` (200) lại khác ngưỡng ra `CANH` (280)?',
            explanation:
              'Nếu dùng chung một ngưỡng, kẻ địch sẽ nhấp nháy liên tục giữa hai trạng thái khi ' +
              'người chơi đứng ngay ranh giới. Hai ngưỡng khác nhau gọi là ngưỡng trễ.',
            choices: [
              { text: 'Để kẻ địch không nhấp nháy qua lại khi ở ngay ranh giới', isCorrect: true },
              { text: 'Để tiết kiệm bộ nhớ' },
              { text: 'Vì Pygame yêu cầu như vậy' },
              { text: 'Không có lý do, chỉ là con số tuỳ ý' },
            ],
          },
          {
            type: 'MULTIPLE_CHOICE',
            prompt: 'Muốn ba kẻ địch bay sóng sin so le nhau, ta thay đổi tham số nào?',
            explanation: 'Độ lệch pha — cộng thêm một giá trị khác nhau vào bên trong hàm sin.',
            choices: [
              { text: 'Độ lệch pha bên trong `sin()`', isCorrect: true },
              { text: 'Biên độ (số nhân bên ngoài)' },
              { text: 'Màu sắc của kẻ địch' },
              { text: 'FPS của game' },
            ],
          },
        ],
      }),
    ],
  },

  {
    order: 22,
    slug: 'pg-b22-power-up-vat-pham-kho-do',
    title: 'Power-up, vật phẩm & kho đồ đơn giản',
    summary:
      'Vật phẩm ăn được, hiệu ứng có thời hạn, và một kho đồ nhỏ. Đây là thứ làm người chơi ' +
      'muốn khám phá màn chơi.',
    objectives: [
      'Tạo vật phẩm nhặt được và xử lý va chạm nhặt',
      'Cài đặt hiệu ứng power-up có thời hạn bằng bộ đếm',
      'Quản lý kho đồ bằng từ điển',
      'Hiển thị hiệu ứng đang hoạt động lên HUD',
    ],
    difficulty: 4,
    status: 'REQUIRED',
    teacherNotes: 'Kho đồ dùng từ điển — nhắc lại buổi 22 khoá Cơ Bản.',
    blocks: [
      theory('Vật phẩm và hiệu ứng có thời hạn', [
        'Nhặt vật phẩm chỉ là va chạm cộng với xoá — em đã làm ở buổi 12:',
        '',
        '```python',
        'nhat_duoc = pygame.sprite.spritecollide(nv, nhom_vat_pham, True)',
        'for vp in nhat_duoc:',
        '    if vp.loai == "TOC_DO":',
        '        hieu_ung["TOC_DO"] = 300      # keo dai 300 khung = 5 giay',
        '    elif vp.loai == "MAU":',
        '        mau = min(mau + 25, MAU_TOI_DA)',
        '```',
        '',
        '**Hiệu ứng có thời hạn** dùng một từ điển đếm ngược:',
        '',
        '```python',
        'hieu_ung = {}       # {"TOC_DO": 300, "BAT_TU": 120}',
        '',
        '# Moi khung hinh: giam bo dem, xoa cai het han',
        'for ten in list(hieu_ung.keys()):',
        '    hieu_ung[ten] -= 1',
        '    if hieu_ung[ten] <= 0:',
        '        del hieu_ung[ten]',
        '',
        '# Ap dung hieu ung',
        'toc_do = 10 if "TOC_DO" in hieu_ung else 5',
        '```',
        '',
        '⚠️ Chú ý `list(hieu_ung.keys())`. Không thể xoá phần tử của từ điển **trong khi** đang duyệt ' +
          'chính nó — Python sẽ báo `RuntimeError`. Bọc `list()` để tạo một bản sao danh sách khoá trước.',
        '',
        'Đây chính là kiểu lỗi mà bài học về sao chép ở buổi 21 khoá Cơ Bản đã chuẩn bị cho em.',
      ], [
        'Hiệu ứng = từ điển `{ten: so_khung_con_lai}`',
        'Giảm bộ đếm mỗi khung, xoá khi về 0',
        'Luôn `list(d.keys())` khi cần xoá trong lúc duyệt',
      ]),
      theory('Kho đồ đơn giản', [
        'Kho đồ chỉ là một từ điển đếm số lượng — đúng mẫu đếm tần suất ở buổi 22 khoá Cơ Bản:',
        '',
        '```python',
        'kho = {}',
        '',
        'def them_vat_pham(kho, ten, so_luong=1):',
        '    kho[ten] = kho.get(ten, 0) + so_luong',
        '',
        'def dung_vat_pham(kho, ten):',
        '    if kho.get(ten, 0) <= 0:',
        '        return False           # khong co de dung',
        '    kho[ten] -= 1',
        '    if kho[ten] == 0:',
        '        del kho[ten]           # don sach cho HUD gon',
        '    return True',
        '```',
        '',
        'Hàm `dung_vat_pham` trả về `True`/`False` để nơi gọi biết có dùng được hay không — ' +
          'nhờ vậy không bao giờ trừ nhầm về số âm.',
        '',
        '**Hiển thị kho lên HUD:**',
        '',
        '```python',
        'y = 100',
        'for ten, sl in kho.items():',
        '    chu = font.render(f"{ten} x{sl}", True, (255, 255, 255))',
        '    man_hinh.blit(chu, (20, y))',
        '    y += 26',
        '```',
      ], [
        'Kho đồ = `{ten_vat_pham: so_luong}`',
        '`kho.get(ten, 0) + 1` để thêm an toàn',
        'Hàm dùng đồ trả về True/False để tránh số lượng âm',
      ]),
      example('Power-up hoàn chỉnh', 'Ba loại vật phẩm, hiệu ứng có thời hạn, kho đồ và HUD.', [
        'import pygame',
        'import random',
        '',
        'pygame.init()',
        'RONG, CAO = 800, 500',
        'man_hinh = pygame.display.set_mode((RONG, CAO))',
        'pygame.display.set_caption("Power-up")',
        'dong_ho = pygame.time.Clock()',
        'font = pygame.font.SysFont("arial", 18)',
        '',
        'LOAI = {',
        '    "TOC_DO": (52, 152, 219),',
        '    "BAT_TU": (241, 196, 15),',
        '    "MAU": (231, 76, 60),',
        '}',
        '',
        'nv = pygame.Rect(400, 250, 30, 30)',
        'vat_pham = []',
        'hieu_ung = {}',
        'kho = {}',
        'mau = 60',
        'MAU_TOI_DA = 100',
        'bo_dem_sinh = 0',
        '',
        'dang_chay = True',
        'while dang_chay:',
        '    for su_kien in pygame.event.get():',
        '        if su_kien.type == pygame.QUIT:',
        '            dang_chay = False',
        '        elif su_kien.type == pygame.KEYDOWN:',
        '            if su_kien.key == pygame.K_1 and kho.get("MAU", 0) > 0:',
        '                kho["MAU"] -= 1',
        '                if kho["MAU"] == 0:',
        '                    del kho["MAU"]',
        '                mau = min(mau + 25, MAU_TOI_DA)',
        '',
        '    # --- Sinh vat pham moi ---',
        '    bo_dem_sinh += 1',
        '    if bo_dem_sinh >= 70:',
        '        bo_dem_sinh = 0',
        '        ten = random.choice(list(LOAI.keys()))',
        '        vat_pham.append({',
        '            "rect": pygame.Rect(random.randint(20, RONG - 40),',
        '                                random.randint(20, CAO - 40), 22, 22),',
        '            "loai": ten,',
        '        })',
        '',
        '    # --- Dieu khien ---',
        '    toc_do = 11 if "TOC_DO" in hieu_ung else 5',
        '    phim = pygame.key.get_pressed()',
        '    if phim[pygame.K_LEFT]:',
        '        nv.x -= toc_do',
        '    if phim[pygame.K_RIGHT]:',
        '        nv.x += toc_do',
        '    if phim[pygame.K_UP]:',
        '        nv.y -= toc_do',
        '    if phim[pygame.K_DOWN]:',
        '        nv.y += toc_do',
        '    nv.clamp_ip(man_hinh.get_rect())',
        '',
        '    # --- Nhat vat pham ---',
        '    con_lai = []',
        '    for vp in vat_pham:',
        '        if nv.colliderect(vp["rect"]):',
        '            if vp["loai"] == "MAU":',
        '                kho["MAU"] = kho.get("MAU", 0) + 1',
        '            else:',
        '                hieu_ung[vp["loai"]] = 300',
        '        else:',
        '            con_lai.append(vp)',
        '    vat_pham = con_lai',
        '',
        '    # --- Giam bo dem hieu ung ---',
        '    for ten in list(hieu_ung.keys()):',
        '        hieu_ung[ten] -= 1',
        '        if hieu_ung[ten] <= 0:',
        '            del hieu_ung[ten]',
        '',
        '    # ===== VE =====',
        '    man_hinh.fill((28, 28, 50))',
        '    for vp in vat_pham:',
        '        pygame.draw.rect(man_hinh, LOAI[vp["loai"]], vp["rect"], 0, border_radius=5)',
        '',
        '    mau_nv = (241, 196, 15) if "BAT_TU" in hieu_ung else (46, 204, 113)',
        '    pygame.draw.rect(man_hinh, mau_nv, nv, 0, border_radius=6)',
        '',
        '    # HUD',
        '    pygame.draw.rect(man_hinh, (60, 60, 70), (20, 20, 200, 20))',
        '    pygame.draw.rect(man_hinh, (46, 204, 113), (20, 20, int(200 * mau / MAU_TOI_DA), 20))',
        '    pygame.draw.rect(man_hinh, (255, 255, 255), (20, 20, 200, 20), 2)',
        '',
        '    y = 50',
        '    for ten, con in hieu_ung.items():',
        '        man_hinh.blit(font.render(f"{ten}: {con // 60 + 1}s", True, LOAI[ten]), (20, y))',
        '        y += 24',
        '',
        '    y += 10',
        '    for ten, sl in kho.items():',
        '        man_hinh.blit(font.render(f"Kho: {ten} x{sl}  (bam 1 de dung)",',
        '                                  True, (220, 220, 235)), (20, y))',
        '        y += 24',
        '',
        '    pygame.display.flip()',
        '    dong_ho.tick(60)',
        '',
        'pygame.quit()',
      ], {
        output:
          'Vật phẩm xuất hiện đều đặn; ăn xanh thì chạy nhanh, ăn vàng thì đổi màu bất tử, ăn đỏ thì vào kho và bấm 1 để hồi máu.',
        notes: [
          'Danh sách `con_lai` được xây mới thay vì xoá phần tử khi đang duyệt — cùng nguyên tắc với `list(keys())`.',
          '`con // 60 + 1` đổi số khung hình còn lại thành số giây, cho HUD dễ đọc.',
          'Máu và kho đồ tách biệt: vật phẩm MAU vào kho để dùng khi cần, chứ không hồi ngay.',
        ],
      }),
      playground('Sân chơi: power-up của em', [
        'Thêm loại power-up mới vào ví dụ trên. Vài ý tưởng:',
        '',
        '- **NHO_LAI** — nhân vật nhỏ đi, chui được qua khe hẹp',
        '- **NAM_CHAM** — vật phẩm tự bay về phía nhân vật',
        '- **DONG_BANG** — kẻ địch đứng yên một lúc',
        '',
        'Nhớ thêm màu vào từ điển `LOAI` và xử lý hiệu ứng ở phần cập nhật.',
      ], [
        'LOAI = {',
        '    "TOC_DO": (52, 152, 219),',
        '    "BAT_TU": (241, 196, 15),',
        '    "MAU": (231, 76, 60),',
        '    # Them loai moi o day',
        '}',
        '',
        'hieu_ung = {}',
        '',
        '# Mau ap dung hieu ung:',
        '# kich_thuoc = 15 if "NHO_LAI" in hieu_ung else 30',
      ], 'Thêm được ít nhất một power-up mới hoạt động đúng và hiện trên HUD.'),
      challenge({
        slug: 'p-pg-b22-quan-ly-kho-do',
        title: 'Quản lý kho đồ',
        statement: [
          'Kho đồ bắt đầu rỗng. Xử lý một dãy lệnh:',
          '',
          '- `THEM <ten> <so_luong>` — thêm vật phẩm vào kho',
          '- `DUNG <ten>` — dùng **một** vật phẩm; nếu kho không có thì bỏ qua lệnh này',
          '',
          'Dòng đầu: số nguyên `N`. `N` dòng tiếp theo là các lệnh.',
          '',
          'In ra danh sách kho đồ còn lại, **mỗi vật phẩm một dòng**, sắp xếp theo **bảng chữ cái**:',
          '',
          '```',
          '<ten> x<so_luong>',
          '```',
          '',
          'Vật phẩm có số lượng bằng 0 **không** được in. Nếu kho rỗng, in `Kho rong`.',
        ].join('\n'),
        hints: [
          'Dùng từ điển với mẫu `kho[ten] = kho.get(ten, 0) + sl`.',
          'Lệnh DUNG chỉ trừ khi `kho.get(ten, 0) > 0`.',
          'Khi in, bỏ qua các mục có số lượng bằng 0; dùng `sorted(kho)` để sắp theo bảng chữ cái.',
        ],
        starterCode: [
          'n = int(input())',
          'kho = {}',
          '',
          'for i in range(n):',
          '    phan = input().split()',
          '    # Xử lý lệnh THEM hoặc DUNG',
          '',
          '# In kho theo thứ tự bảng chữ cái',
        ].join('\n'),
        solutionCode: [
          'n = int(input())',
          'kho = {}',
          '',
          'for i in range(n):',
          '    phan = input().split()',
          '    if phan[0] == "THEM":',
          '        kho[phan[1]] = kho.get(phan[1], 0) + int(phan[2])',
          '    else:',
          '        if kho.get(phan[1], 0) > 0:',
          '            kho[phan[1]] -= 1',
          '',
          'co_gi = False',
          'for ten in sorted(kho):',
          '    if kho[ten] > 0:',
          '        print(f"{ten} x{kho[ten]}")',
          '        co_gi = True',
          '',
          'if not co_gi:',
          '    print("Kho rong")',
        ].join('\n'),
        tier: 'THU_THACH',
        judgeMode: 'IO_MATCH',
        tests: [
          sample(
            '4\nTHEM MAU 3\nTHEM BOM 1\nDUNG MAU\nDUNG BOM\n',
            'MAU x2\n',
            'BOM về 0 nên không in. MAU còn 2. Sắp xếp theo bảng chữ cái.',
          ),
          sample('2\nDUNG MAU\nDUNG BOM\n', 'Kho rong\n', 'Dùng đồ không có thì bị bỏ qua.'),
          hidden('1\nTHEM KIEM 1\n', 'KIEM x1\n', 20),
          hidden('3\nTHEM A 2\nTHEM B 2\nDUNG A\n', 'A x1\nB x2\n', 20),
          hidden('4\nTHEM Z 1\nTHEM A 1\nTHEM M 1\nDUNG Z\n', 'A x1\nM x1\n', 30),
          hidden('5\nTHEM X 5\nDUNG X\nDUNG X\nDUNG X\nDUNG X\n', 'X x1\n', 30),
        ],
      }),
    ],
  },

  {
    order: 23,
    slug: 'pg-b23-nhieu-man-choi-va-luu-tien-do',
    title: 'Nhiều màn chơi, tăng độ khó & lưu tiến độ',
    summary:
      'Một màn chơi thì nhanh chán. Buổi này em xây hệ thống nhiều màn, độ khó tăng dần, ' +
      'và lưu tiến độ để lần sau chơi tiếp.',
    objectives: [
      'Lưu nhiều màn chơi trong một danh sách và chuyển màn',
      'Điều chỉnh độ khó theo số thứ tự màn',
      'Lưu và đọc tiến độ bằng JSON',
      'Thiết kế đường cong độ khó hợp lý',
    ],
    difficulty: 4,
    status: 'RECOMMENDED',
    teacherNotes:
      'Buổi mở rộng. Phần JSON dùng lại buổi 29 khoá Cơ Bản — nhắc học sinh liên hệ để thấy kiến thức nối tiếp.',
    blocks: [
      theory('Danh sách các màn chơi', [
        'Gói các màn chơi vào một danh sách, rồi dùng một chỉ số để biết đang ở màn nào:',
        '',
        '```python',
        'CAC_MAN = [',
        '    [  # Man 1',
        '        "..........",',
        '        "....XX....",',
        '        "XXXXXXXXXX",',
        '    ],',
        '    [  # Man 2',
        '        "..........",',
        '        "..XX..XX..",',
        '        "XXXXXXXXXX",',
        '    ],',
        ']',
        '',
        'man_hien_tai = 0',
        '',
        'def nap_man(chi_so):',
        '    ban_do = CAC_MAN[chi_so]',
        '    nen = []',
        '    for hang, dong in enumerate(ban_do):',
        '        for cot, ky_tu in enumerate(dong):',
        '            if ky_tu == "X":',
        '                nen.append(pygame.Rect(cot * TILE, hang * TILE, TILE, TILE))',
        '    return nen',
        '```',
        '',
        '**Chuyển màn** khi người chơi tới đích:',
        '',
        '```python',
        'if nv.colliderect(cua_dich):',
        '    man_hien_tai += 1',
        '    if man_hien_tai >= len(CAC_MAN):',
        '        trang_thai = "THANG"      # het man -> thang ca game',
        '    else:',
        '        nen = nap_man(man_hien_tai)',
        '        nv.topleft = VI_TRI_XUAT_PHAT',
        '```',
        '',
        '⚠️ Luôn kiểm tra `man_hien_tai >= len(CAC_MAN)` **trước khi** nạp — nếu không sẽ gặp `IndexError` ' +
          'ở màn cuối.',
      ], [
        'Các màn chơi nằm trong một danh sách, dùng chỉ số để chuyển',
        'Viết hàm `nap_man()` để không lặp code',
        'Kiểm tra hết màn trước khi nạp, tránh IndexError',
      ]),
      theory('Đường cong độ khó và lưu tiến độ', [
        '**Độ khó tăng theo số màn** — tính từ chỉ số màn thay vì viết tay từng màn:',
        '',
        '```python',
        'so_ke_dich = 2 + man_hien_tai',
        'toc_do_dich = 2 + man_hien_tai * 0.5',
        'thoi_gian = max(60 - man_hien_tai * 5, 20)     # khong duoi 20 giay',
        '```',
        '',
        'Hàm `max()` ở dòng cuối rất quan trọng: nó đặt một **sàn** để màn 20 không trở thành ' +
          'bất khả thi.',
        '',
        '| Nguyên tắc | Vì sao |',
        '|---|---|',
        '| Tăng dần, không nhảy vọt | Người chơi cần cảm giác tiến bộ |',
        '| Luôn có giới hạn trên/dưới | Tránh màn sau không thể thắng |',
        '| Đổi **kiểu** thử thách, không chỉ đổi số | Chỉ tăng số kẻ địch sẽ nhàm |',
        '',
        '**Lưu tiến độ bằng JSON** — đúng kỹ thuật buổi 29 khoá Cơ Bản:',
        '',
        '```python',
        'import json',
        '',
        'def luu(man, diem):',
        '    with open("tien_do.json", "w", encoding="utf-8") as f:',
        '        json.dump({"man": man, "diem_cao": diem}, f)',
        '',
        'def doc():',
        '    try:',
        '        with open("tien_do.json", "r", encoding="utf-8") as f:',
        '            d = json.load(f)',
        '            return d.get("man", 0), d.get("diem_cao", 0)',
        '    except (FileNotFoundError, json.JSONDecodeError):',
        '        return 0, 0',
        '```',
        '',
        'Dùng `.get(khoa, mac_dinh)` thay vì `d["man"]` để tệp cũ thiếu khoá vẫn đọc được.',
      ], [
        'Tính độ khó từ chỉ số màn, đừng viết tay từng màn',
        'Luôn đặt sàn/trần bằng `max()` hoặc `min()`',
        'Lưu tiến độ bằng JSON, bọc try/except và dùng `.get()`',
      ]),
      example('Hệ thống nhiều màn có lưu tiến độ', 'Ba màn chơi, độ khó tăng dần, tiến độ lưu ra tệp.', [
        'import pygame',
        'import json',
        '',
        'pygame.init()',
        'TILE = 40',
        'RONG, CAO = 600, 360',
        'man_hinh = pygame.display.set_mode((RONG, CAO))',
        'pygame.display.set_caption("Nhieu man choi")',
        'dong_ho = pygame.time.Clock()',
        'font = pygame.font.SysFont("arial", 18)',
        'font_lon = pygame.font.SysFont("arial", 40, bold=True)',
        '',
        'CAC_MAN = [',
        '    ["...............",',
        '     "...............",',
        '     ".....XXX.......",',
        '     "...............",',
        '     "..XX........XX.",',
        '     "...............",',
        '     "...............",',
        '     "XXXXXXXXXXXXXXX"],',
        '    ["...............",',
        '     "....XX.....XX..",',
        '     "...............",',
        '     "..XX...XX......",',
        '     "...........XXX.",',
        '     "...............",',
        '     "...XX..........",',
        '     "XXXXXXXXXXXXXXX"],',
        '    ["...............",',
        '     "..XX..XX..XX...",',
        '     "...............",',
        '     "XX..XX..XX..XX.",',
        '     "...............",',
        '     "..XX..XX..XX...",',
        '     "...............",',
        '     "XXXXXXXXXXXXXXX"],',
        ']',
        '',
        '',
        'def doc_tien_do():',
        '    try:',
        '        with open("tien_do.json", "r", encoding="utf-8") as f:',
        '            d = json.load(f)',
        '            return d.get("man", 0)',
        '    except (FileNotFoundError, json.JSONDecodeError):',
        '        return 0',
        '',
        '',
        'def luu_tien_do(man):',
        '    with open("tien_do.json", "w", encoding="utf-8") as f:',
        '        json.dump({"man": man}, f)',
        '',
        '',
        'def nap_man(chi_so):',
        '    o = []',
        '    for hang, dong in enumerate(CAC_MAN[chi_so]):',
        '        for cot, ky_tu in enumerate(dong):',
        '            if ky_tu == "X":',
        '                o.append(pygame.Rect(cot * TILE, hang * TILE, TILE, TILE))',
        '    return o',
        '',
        '',
        'man_hien_tai = min(doc_tien_do(), len(CAC_MAN) - 1)',
        'nen = nap_man(man_hien_tai)',
        'nv = pygame.Rect(20, 20, 26, 34)',
        'vy = 0.0',
        'tren_nen = False',
        'cua_dich = pygame.Rect(RONG - 60, CAO - 120, 30, 40)',
        'trang_thai = "CHOI"',
        '',
        'dang_chay = True',
        'while dang_chay:',
        '    for su_kien in pygame.event.get():',
        '        if su_kien.type == pygame.QUIT:',
        '            dang_chay = False',
        '        elif su_kien.type == pygame.KEYDOWN:',
        '            if su_kien.key == pygame.K_SPACE and tren_nen and trang_thai == "CHOI":',
        '                vy = -14',
        '            elif su_kien.key == pygame.K_r:',
        '                man_hien_tai = 0',
        '                nen = nap_man(0)',
        '                nv.topleft = (20, 20)',
        '                vy = 0.0',
        '                trang_thai = "CHOI"',
        '                luu_tien_do(0)',
        '',
        '    if trang_thai == "CHOI":',
        '        toc_do = 4 + man_hien_tai        # do kho tang dan',
        '        phim = pygame.key.get_pressed()',
        '        vx = 0',
        '        if phim[pygame.K_LEFT]:',
        '            vx = -toc_do',
        '        if phim[pygame.K_RIGHT]:',
        '            vx = toc_do',
        '',
        '        vy = min(vy + 0.8, 16)',
        '',
        '        nv.x += vx',
        '        for o in nen:',
        '            if nv.colliderect(o):',
        '                if vx > 0:',
        '                    nv.right = o.left',
        '                elif vx < 0:',
        '                    nv.left = o.right',
        '',
        '        tren_nen = False',
        '        nv.y += int(vy)',
        '        for o in nen:',
        '            if nv.colliderect(o):',
        '                if vy > 0:',
        '                    nv.bottom = o.top',
        '                    tren_nen = True',
        '                elif vy < 0:',
        '                    nv.top = o.bottom',
        '                vy = 0.0',
        '',
        '        nv.clamp_ip(man_hinh.get_rect())',
        '',
        '        if nv.colliderect(cua_dich):',
        '            man_hien_tai += 1',
        '            if man_hien_tai >= len(CAC_MAN):',
        '                trang_thai = "THANG"',
        '                luu_tien_do(len(CAC_MAN) - 1)',
        '            else:',
        '                nen = nap_man(man_hien_tai)',
        '                nv.topleft = (20, 20)',
        '                vy = 0.0',
        '                luu_tien_do(man_hien_tai)',
        '',
        '    man_hinh.fill((28, 28, 50))',
        '    for o in nen:',
        '        pygame.draw.rect(man_hinh, (90, 100, 125), o)',
        '    pygame.draw.rect(man_hinh, (241, 196, 15), cua_dich, 0, border_radius=4)',
        '    pygame.draw.rect(man_hinh, (46, 204, 113), nv, 0, border_radius=4)',
        '',
        '    man_hinh.blit(font.render(',
        '        f"Man {man_hien_tai + 1}/{len(CAC_MAN)}   (R de choi lai tu dau)",',
        '        True, (215, 215, 235)), (10, 8))',
        '',
        '    if trang_thai == "THANG":',
        '        chu = font_lon.render("HOAN THANH!", True, (46, 204, 113))',
        '        man_hinh.blit(chu, chu.get_rect(center=(RONG // 2, CAO // 2)))',
        '',
        '    pygame.display.flip()',
        '    dong_ho.tick(60)',
        '',
        'pygame.quit()',
      ], {
        output:
          'Nhân vật đi qua ba màn chơi khó dần; tắt game rồi mở lại vẫn tiếp tục từ màn đang chơi dở.',
        notes: [
          '`min(doc_tien_do(), len(CAC_MAN) - 1)` chống trường hợp tệp tiến độ lưu số màn lớn hơn số màn thật.',
          'Tốc độ nhân vật tăng theo màn — cùng một màn chơi nhưng cảm giác khó hơn.',
          'Phím R vừa đặt lại game vừa ghi đè tiến độ, để người chơi thật sự bắt đầu lại được.',
        ],
      }),
      playground('Sân chơi: thiết kế đường cong độ khó', [
        'Viết một hàm tính độ khó cho màn thứ `n`, rồi in bảng cho 10 màn đầu.',
        '',
        'Thử ba kiểu tăng và so sánh:',
        '',
        '- **Tuyến tính:** `2 + n`',
        '- **Chậm dần:** `2 + n // 2`',
        '- **Có trần:** `min(2 + n, 8)`',
        '',
        'Kiểu nào cho cảm giác công bằng nhất ở màn 10?',
      ], [
        'def do_kho(n):',
        '    so_dich = 2 + n',
        '    toc_do = 2 + n * 0.5',
        '    thoi_gian = max(60 - n * 5, 20)',
        '    return so_dich, toc_do, thoi_gian',
        '',
        '',
        'print("Man | Dich | Toc do | Thoi gian")',
        'print("-" * 34)',
        'for n in range(10):',
        '    d, t, g = do_kho(n)',
        '    print(f"{n + 1:3d} | {d:4d} | {t:6.1f} | {g:9.0f}")',
      ], 'So sánh được ba đường cong độ khó và chọn được kiểu phù hợp cho game của em.'),
      challenge({
        slug: 'p-pg-b23-do-kho-theo-man',
        title: 'Tính độ khó theo màn',
        statement: [
          'Với màn thứ `n` (đánh số từ 1), độ khó được tính như sau:',
          '',
          '- Số kẻ địch: `2 + (n - 1)`, nhưng **tối đa 10**',
          '- Tốc độ kẻ địch: `2 + (n - 1)`, nhưng **tối đa 7**',
          '- Thời gian (giây): `60 - (n - 1) * 5`, nhưng **tối thiểu 20**',
          '',
          'Dòng đầu: số nguyên `Q`. `Q` dòng tiếp theo, mỗi dòng một số nguyên `n`.',
          '',
          'Với mỗi màn, in một dòng: `<so_dich> <toc_do> <thoi_gian>`.',
        ].join('\n'),
        hints: [
          'Dùng `min()` cho giới hạn trên, `max()` cho giới hạn dưới.',
          'Chú ý màn được đánh số từ 1 nên phải trừ 1 trước khi nhân.',
          'In ba số trên cùng một dòng, cách nhau một dấu cách.',
        ],
        starterCode: [
          'q = int(input())',
          '',
          'for i in range(q):',
          '    n = int(input())',
          '    # Tính ba giá trị rồi in',
        ].join('\n'),
        solutionCode: [
          'q = int(input())',
          '',
          'for i in range(q):',
          '    n = int(input())',
          '    so_dich = min(2 + (n - 1), 10)',
          '    toc_do = min(2 + (n - 1), 7)',
          '    thoi_gian = max(60 - (n - 1) * 5, 20)',
          '    print(f"{so_dich} {toc_do} {thoi_gian}")',
        ].join('\n'),
        tier: 'CO_BAN',
        judgeMode: 'IO_MATCH',
        tests: [
          sample(
            '3\n1\n5\n20\n',
            '2 2 60\n6 6 40\n10 7 20\n',
            'Màn 20 chạm cả ba giới hạn: 10 kẻ địch, tốc độ 7, 20 giây.',
          ),
          sample('1\n9\n', '10 7 20\n', 'Màn 9 đã chạm trần số kẻ địch và sàn thời gian.'),
          hidden('1\n2\n', '3 3 55\n', 20),
          hidden('1\n1000\n', '10 7 20\n', 20),
          hidden('2\n6\n7\n', '7 7 35\n8 7 30\n', 30),
          hidden('1\n8\n', '9 7 25\n', 30),
        ],
      }),
    ],
  },
];
