/**
 * Lập Trình Game Python (Pygame) — Module 3 (Buổi 9–16).
 *
 * Teacher notes enforced here:
 *   • Note 11 — "Split advanced movement and physics into separate, focused
 *     sessions before applying them to projects." B9 basic movement, B10 advanced
 *     movement (acceleration/friction/bounce), B11 physics (gravity/jump) are
 *     three distinct sessions, and the module project (B16) comes only after all
 *     three plus collision handling.
 *   • Note 11 — "Reorder the Menu lesson." Menu moved to B15, immediately before
 *     the project, so game states exist before a menu needs to switch between them.
 */
import type { ModuleSpec } from '../types.ts';
import {
  challenge,
  example,
  hidden,
  playground,
  projectBlock,
  quizBlock,
  sample,
  theory,
} from '../builders.ts';

export const pygameModule3: ModuleSpec = {
  slug: 'chuyen-dong-vat-ly-va-cham',
  title: 'Module 3 · Chuyển động, Vật lý, Va chạm, Logic',
  description:
    'Trái tim kỹ thuật của khoá học. Mỗi kỹ thuật được học riêng một buổi cho thật vững, ' +
    'rồi mới ghép lại thành trò chơi Pong hoàn chỉnh ở buổi cuối module.',
  lessons: [
    {
      order: 9,
      slug: 'pg-b09-chuyen-dong-co-ban',
      title: 'Chuyển động cơ bản: vận tốc & giới hạn màn hình',
      summary:
        'Vận tốc theo hai trục, chuyển động chéo, và bốn cách xử lý khi vật chạm mép màn hình.',
      objectives: [
        'Biểu diễn chuyển động bằng cặp vận tốc `vx`, `vy`',
        'Tạo chuyển động chéo bằng cách kết hợp hai trục',
        'Xử lý bốn kiểu chạm mép: dừng, nảy, xuyên qua, kẹp lại',
        'Chuẩn hoá tốc độ khi đi chéo',
      ],
      difficulty: 3,
      status: 'REQUIRED',
      teacherNotes:
        'GHI CHÚ Module 3: tách riêng chuyển động cơ bản khỏi chuyển động nâng cao. Buổi này chỉ ' +
        'vận tốc đều, chưa có gia tốc.',
      blocks: [
        theory('Vận tốc theo hai trục', [
          'Chuyển động trong game được mô tả bằng hai con số:',
          '',
          '```python',
          'vx = 5     # dịch bao nhiêu điểm ảnh theo trục ngang mỗi khung hình',
          'vy = -3    # theo trục dọc (âm = đi LÊN, vì y tăng xuống dưới)',
          '',
          'rect.x += vx',
          'rect.y += vy',
          '```',
          '',
          '| `vx` | `vy` | Hướng đi |',
          '|---|---|---|',
          '| `5` | `0` | Sang phải |',
          '| `0` | `-5` | Lên trên |',
          '| `5` | `5` | Chéo xuống phải |',
          '| `-3` | `4` | Chéo xuống trái |',
          '',
          '⚠️ **Một chi tiết dễ bỏ sót:** đi chéo với `vx=5, vy=5` thực ra **nhanh hơn** đi thẳng ' +
            'với `vx=5`. Quãng đường thực tế là √(5² + 5²) ≈ 7.07 chứ không phải 5.',
          '',
          'Trong game có nhân vật đi bốn hướng, người chơi sẽ phát hiện ra là đi chéo nhanh hơn ' +
            'và lợi dụng điều đó. Cách sửa là chia tốc độ cho √2 khi đi chéo.',
        ], [
          '`vx` và `vy` mô tả đầy đủ chuyển động',
          '`vy` âm = đi lên',
          'Đi chéo nhanh hơn đi thẳng khoảng 41% nếu không chuẩn hoá',
        ]),
        theory('Bốn cách xử lý khi chạm mép', [
          '**1. Dừng lại (kẹp)** — dùng cho nhân vật người chơi:',
          '',
          '```python',
          'if rect.left < 0:',
          '    rect.left = 0',
          'if rect.right > RONG:',
          '    rect.right = RONG',
          '```',
          '',
          '**2. Nảy lại** — dùng cho bóng:',
          '',
          '```python',
          'if rect.left < 0 or rect.right > RONG:',
          '    vx = -vx',
          '```',
          '',
          '**3. Xuyên qua (wrap)** — dùng cho game kiểu Asteroids:',
          '',
          '```python',
          'if rect.left > RONG:',
          '    rect.right = 0',
          '```',
          '',
          '**4. Biến mất** — dùng cho đạn:',
          '',
          '```python',
          'if rect.bottom < 0:',
          '    self.kill()',
          '```',
          '',
          '💡 Pygame còn có `rect.clamp_ip(khung)` làm sẵn cách 1 cho cả hai trục chỉ trong một dòng.',
        ], [
          'Kẹp cho nhân vật, nảy cho bóng, xuyên qua cho Asteroids, biến mất cho đạn',
          '`rect.clamp_ip(khung)` kẹp gọn cả hai trục',
        ]),
        example('Bốn hành vi cạnh nhau', 'Bấm 1–4 để đổi cách xử lý mép và quan sát khác biệt.', [
          'import pygame',
          '',
          'pygame.init()',
          'RONG, CAO = 800, 600',
          'man_hinh = pygame.display.set_mode((RONG, CAO))',
          'pygame.display.set_caption("Bon cach xu ly mep")',
          'dong_ho = pygame.time.Clock()',
          'phong_chu = pygame.font.SysFont("arial", 20)',
          'khung_man_hinh = man_hinh.get_rect()',
          '',
          'vat = pygame.Rect(400, 300, 40, 40)',
          'vx, vy = 6, 4',
          'che_do = 2',
          'TEN_CHE_DO = {1: "1 - Kep lai", 2: "2 - Nay lai", 3: "3 - Xuyen qua", 4: "4 - Dung han"}',
          '',
          'dang_chay = True',
          'while dang_chay:',
          '    for su_kien in pygame.event.get():',
          '        if su_kien.type == pygame.QUIT:',
          '            dang_chay = False',
          '        elif su_kien.type == pygame.KEYDOWN:',
          '            if su_kien.key in (pygame.K_1, pygame.K_2, pygame.K_3, pygame.K_4):',
          '                che_do = int(pygame.key.name(su_kien.key))',
          '                vat.center = (400, 300)',
          '                vx, vy = 6, 4',
          '',
          '    vat.x += vx',
          '    vat.y += vy',
          '',
          '    if che_do == 1:',
          '        vat.clamp_ip(khung_man_hinh)',
          '    elif che_do == 2:',
          '        if vat.left < 0 or vat.right > RONG:',
          '            vx = -vx',
          '        if vat.top < 0 or vat.bottom > CAO:',
          '            vy = -vy',
          '        vat.clamp_ip(khung_man_hinh)',
          '    elif che_do == 3:',
          '        if vat.left > RONG:',
          '            vat.right = 0',
          '        if vat.right < 0:',
          '            vat.left = RONG',
          '        if vat.top > CAO:',
          '            vat.bottom = 0',
          '        if vat.bottom < 0:',
          '            vat.top = CAO',
          '    elif che_do == 4:',
          '        if not khung_man_hinh.contains(vat):',
          '            vx, vy = 0, 0',
          '            vat.clamp_ip(khung_man_hinh)',
          '',
          '    man_hinh.fill((25, 25, 45))',
          '    pygame.draw.rect(man_hinh, (231, 76, 60), vat, 0, border_radius=6)',
          '    chu = phong_chu.render(f"Che do: {TEN_CHE_DO[che_do]}  (bam 1-4)", True, (220, 220, 235))',
          '    man_hinh.blit(chu, (10, 10))',
          '    pygame.display.flip()',
          '    dong_ho.tick(60)',
          '',
          'pygame.quit()',
        ], {
          output: 'Một ô vuông đỏ chuyển động chéo; bấm 1–4 để đổi giữa kẹp lại, nảy, xuyên qua và dừng hẳn.',
          notes: [
            'Ở chế độ nảy, `clamp_ip` sau khi đổi dấu giúp vật không bị kẹt dính vào mép.',
            '`khung.contains(vat)` kiểm tra vật có nằm trọn trong khung không.',
            'Chế độ 3 (xuyên qua) chính là cơ chế của game Asteroids và Pac-Man.',
          ],
        }),
        playground('Sân chơi: chuẩn hoá tốc độ đi chéo', [
          'Điều khiển nhân vật bốn hướng, rồi thử đi chéo và so sánh với đi thẳng.',
          '',
          'Sau đó thêm phần chuẩn hoá: khi cả hai trục đều có vận tốc, chia cả hai cho √2 ' +
            '(khoảng 1.414) để tốc độ chéo bằng tốc độ thẳng.',
        ], [
          'import pygame',
          '',
          'pygame.init()',
          'man_hinh = pygame.display.set_mode((800, 600))',
          'dong_ho = pygame.time.Clock()',
          '',
          'x, y = 400.0, 300.0',
          'TOC_DO = 6',
          '',
          'dang_chay = True',
          'while dang_chay:',
          '    for su_kien in pygame.event.get():',
          '        if su_kien.type == pygame.QUIT:',
          '            dang_chay = False',
          '',
          '    phim = pygame.key.get_pressed()',
          '    vx = vy = 0',
          '    if phim[pygame.K_LEFT]:',
          '        vx -= TOC_DO',
          '    if phim[pygame.K_RIGHT]:',
          '        vx += TOC_DO',
          '    if phim[pygame.K_UP]:',
          '        vy -= TOC_DO',
          '    if phim[pygame.K_DOWN]:',
          '        vy += TOC_DO',
          '',
          '    # Them phan chuan hoa o day:',
          '    # neu ca vx va vy deu khac 0, chia ca hai cho 1.414',
          '',
          '    x += vx',
          '    y += vy',
          '',
          '    man_hinh.fill((25, 25, 45))',
          '    pygame.draw.circle(man_hinh, (46, 204, 113), (int(x), int(y)), 20)',
          '    pygame.display.flip()',
          '    dong_ho.tick(60)',
          '',
          'pygame.quit()',
        ], 'Tốc độ đi chéo bằng đúng tốc độ đi thẳng sau khi chuẩn hoá.'),
        challenge({
          slug: 'p-pg-b09-mo-phong-nay',
          title: 'Mô phỏng bóng nảy',
          statement: [
            'Một quả bóng (coi như một điểm) ở vị trí `x`, `y` với vận tốc `vx`, `vy`. ' +
              'Màn hình rộng `W`, cao `H`.',
            '',
            'Mỗi khung hình: cộng `vx` vào `x` và `vy` vào `y`. Sau đó, nếu `x < 0` hoặc `x > W` ' +
              'thì `vx` đổi dấu; nếu `y < 0` hoặc `y > H` thì `vy` đổi dấu.',
            '',
            'Dòng đầu: bốn số nguyên `x y vx vy`. Dòng hai: ba số nguyên `W H N`.',
            '',
            'In ra **một dòng**: `<x> <y>` sau đúng `N` khung hình.',
          ].join('\n'),
          hints: [
            'Thứ tự rất quan trọng: cộng vận tốc TRƯỚC, kiểm tra mép SAU.',
            'Bài này không kẹp vị trí lại — chỉ đổi dấu vận tốc.',
            'Dùng hai câu `if` riêng cho hai trục.',
          ],
          starterCode: [
            'x, y, vx, vy = map(int, input().split())',
            'w, h, n = map(int, input().split())',
            '',
            '# Mô phỏng n khung hình',
          ].join('\n'),
          solutionCode: [
            'x, y, vx, vy = map(int, input().split())',
            'w, h, n = map(int, input().split())',
            '',
            'for i in range(n):',
            '    x += vx',
            '    y += vy',
            '    if x < 0 or x > w:',
            '        vx = -vx',
            '    if y < 0 or y > h:',
            '        vy = -vy',
            '',
            'print(f"{x} {y}")',
          ].join('\n'),
          tier: 'THU_THACH',
          judgeMode: 'IO_MATCH',
          tests: [
            sample(
              '0 0 10 10\n100 100 5\n',
              '50 50\n',
              'Sau 5 khung, bóng ở (50, 50), chưa chạm mép nào.',
            ),
            sample(
              '95 50 10 0\n100 100 2\n',
              '95 50\n',
              'Khung 1: x=105 vượt mép nên vx đổi thành -10. Khung 2: x=95.',
            ),
            hidden('50 50 0 0\n100 100 1000\n', '50 50\n', 25),
            hidden('0 0 1 1\n10 10 20\n', '2 2\n', 25),
            hidden('5 5 -10 -10\n100 100 3\n', '15 15\n', 25),
            hidden('100 0 20 5\n100 100 4\n', '20 20\n', 25),
          ],
        }),
      ],
    },

    {
      order: 10,
      slug: 'pg-b10-chuyen-dong-nang-cao',
      title: 'Chuyển động nâng cao: gia tốc, ma sát, nảy',
      summary:
        'Buổi riêng cho chuyển động có cảm giác. Gia tốc làm nhân vật tăng tốc dần, ma sát làm nó ' +
        'dừng mượt, và hệ số nảy làm quả bóng nảy tự nhiên.',
      objectives: [
        'Phân biệt vị trí, vận tốc và gia tốc',
        'Áp dụng gia tốc để nhân vật tăng tốc và giảm tốc mượt mà',
        'Dùng ma sát để nhân vật dừng dần thay vì đứng khựng',
        'Dùng hệ số nảy để quả bóng nảy thấp dần',
      ],
      difficulty: 4,
      status: 'REQUIRED',
      teacherNotes:
        'GHI CHÚ Module 3: buổi RIÊNG cho chuyển động nâng cao, theo đúng yêu cầu tách nhỏ trong ' +
        'kế hoạch bài giảng. Chưa động tới trọng lực — đó là buổi 11.',
      blocks: [
        theory('Ba tầng của chuyển động', [
          '| Đại lượng | Ý nghĩa | Cập nhật |',
          '|---|---|---|',
          '| **Vị trí** `x` | Vật đang ở đâu | `x += vx` |',
          '| **Vận tốc** `vx` | Đi nhanh chậm thế nào | `vx += ax` |',
          '| **Gia tốc** `ax` | Vận tốc đang đổi ra sao | Do người chơi hoặc lực tác động |',
          '',
          'Ở buổi 9, em đặt thẳng `vx = 5` — nhân vật lập tức đạt tốc độ tối đa rồi lập tức dừng. ' +
            'Cảm giác rất cứng.',
          '',
          'Với gia tốc, nhân vật **tăng tốc dần**:',
          '',
          '```python',
          'phim = pygame.key.get_pressed()',
          'ax = 0',
          'if phim[pygame.K_LEFT]:',
          '    ax = -0.5',
          'if phim[pygame.K_RIGHT]:',
          '    ax = 0.5',
          '',
          'vx += ax          # vận tốc thay đổi dần',
          'x += vx           # vị trí thay đổi theo vận tốc',
          '```',
          '',
          '⚠️ Vị trí phải lưu bằng **số thực** (`float`), không phải `rect.x` (số nguyên). ' +
            'Với gia tốc 0.5, nếu ép về số nguyên mỗi khung hình thì phần lẻ bị mất và nhân vật ' +
            'sẽ không bao giờ chuyển động.',
        ], [
          'Vị trí ← vận tốc ← gia tốc',
          'Lưu vị trí bằng float, chỉ ép về int khi vẽ',
          'Gia tốc tạo cảm giác tăng tốc mượt mà',
        ]),
        theory('Ma sát và hệ số nảy', [
          '**Ma sát** — nhân rất nhẹ vào vận tốc mỗi khung hình:',
          '',
          '```python',
          'MA_SAT = 0.92',
          'vx *= MA_SAT      # mỗi khung hình mất 8% vận tốc',
          '',
          'if abs(vx) < 0.1: # tránh vận tốc lẻ vô hạn',
          '    vx = 0',
          '```',
          '',
          '| Hệ số ma sát | Cảm giác |',
          '|---|---|',
          '| `0.99` | Trơn như trên băng |',
          '| `0.92` | Vừa phải, tự nhiên |',
          '| `0.80` | Nặng nề, dừng nhanh |',
          '',
          '**Hệ số nảy** — nhân vào vận tốc khi va chạm, luôn nhỏ hơn 1:',
          '',
          '```python',
          'HE_SO_NAY = 0.75',
          'if rect.bottom > CAO:',
          '    rect.bottom = CAO',
          '    vy = -vy * HE_SO_NAY   # đổi hướng VÀ mất bớt năng lượng',
          '```',
          '',
          'Không có hệ số nảy, bóng nảy mãi ở cùng độ cao — trông giả. Với hệ số 0.75, mỗi lần nảy ' +
            'bóng chỉ lên được 75% vận tốc cũ, nên nó thấp dần và dừng lại, đúng như thật.',
        ], [
          'Ma sát: `vx *= 0.92` mỗi khung hình',
          'Hệ số nảy < 1 để bóng nảy thấp dần',
          'Đặt vận tốc về 0 khi quá nhỏ, tránh rung lắc vô hạn',
        ]),
        example('So sánh ba kiểu chuyển động', 'Bấm 1/2/3 để đổi kiểu và cảm nhận sự khác biệt.', [
          'import pygame',
          '',
          'pygame.init()',
          'RONG, CAO = 800, 600',
          'man_hinh = pygame.display.set_mode((RONG, CAO))',
          'pygame.display.set_caption("Chuyen dong nang cao")',
          'dong_ho = pygame.time.Clock()',
          'phong_chu = pygame.font.SysFont("arial", 20)',
          '',
          'x, vx = 400.0, 0.0',
          'kieu = 3',
          'TEN = {1: "1 - Van toc deu (cung)", 2: "2 - Co gia toc", 3: "3 - Gia toc + ma sat"}',
          '',
          'GIA_TOC = 0.6',
          'MA_SAT = 0.92',
          'TOC_DO_TOI_DA = 12',
          '',
          'dang_chay = True',
          'while dang_chay:',
          '    for su_kien in pygame.event.get():',
          '        if su_kien.type == pygame.QUIT:',
          '            dang_chay = False',
          '        elif su_kien.type == pygame.KEYDOWN:',
          '            if su_kien.key in (pygame.K_1, pygame.K_2, pygame.K_3):',
          '                kieu = int(pygame.key.name(su_kien.key))',
          '                x, vx = 400.0, 0.0',
          '',
          '    phim = pygame.key.get_pressed()',
          '    trai = phim[pygame.K_LEFT]',
          '    phai = phim[pygame.K_RIGHT]',
          '',
          '    if kieu == 1:',
          '        vx = 0',
          '        if trai:',
          '            vx = -8',
          '        if phai:',
          '            vx = 8',
          '    else:',
          '        if trai:',
          '            vx -= GIA_TOC',
          '        if phai:',
          '            vx += GIA_TOC',
          '        if kieu == 3:',
          '            vx *= MA_SAT',
          '            if abs(vx) < 0.1:',
          '                vx = 0.0',
          '        if vx > TOC_DO_TOI_DA:',
          '            vx = TOC_DO_TOI_DA',
          '        if vx < -TOC_DO_TOI_DA:',
          '            vx = -TOC_DO_TOI_DA',
          '',
          '    x += vx',
          '    if x < 20:',
          '        x, vx = 20.0, 0.0',
          '    if x > RONG - 20:',
          '        x, vx = RONG - 20.0, 0.0',
          '',
          '    man_hinh.fill((25, 25, 45))',
          '    pygame.draw.line(man_hinh, (60, 60, 85), (0, 300), (RONG, 300), 2)',
          '    pygame.draw.circle(man_hinh, (241, 196, 15), (int(x), 300), 20)',
          '    man_hinh.blit(phong_chu.render(TEN[kieu], True, (220, 220, 235)), (10, 10))',
          '    man_hinh.blit(phong_chu.render(f"Van toc: {vx:6.2f}", True, (150, 200, 255)), (10, 40))',
          '    pygame.display.flip()',
          '    dong_ho.tick(60)',
          '',
          'pygame.quit()',
        ], {
          output: 'Quả cầu vàng điều khiển bằng mũi tên, kèm chỉ số vận tốc thay đổi theo thời gian thực.',
          notes: [
            'Kiểu 1 rất "cứng": thả phím là đứng khựng ngay.',
            'Kiểu 2 tăng tốc mượt nhưng thả phím lại trượt mãi — không có gì làm nó chậm lại.',
            'Kiểu 3 là cách hầu hết game thật dùng: vừa tăng tốc mượt, vừa dừng dần tự nhiên.',
            'Quan sát chỉ số vận tốc để hiểu rõ chuyện gì đang diễn ra.',
          ],
        }),
        playground('Sân chơi: bóng nảy thật', [
          'Cho quả bóng rơi và nảy lên với hệ số nảy nhỏ hơn 1.',
          '',
          'Thử đổi `HE_SO_NAY` giữa 0.5, 0.75, 0.95 và 1.0 để thấy khác biệt.',
          '',
          'Ở 1.0, bóng nảy mãi không dừng — trông ngay lập tức giả tạo.',
        ], [
          'import pygame',
          '',
          'pygame.init()',
          'RONG, CAO = 800, 600',
          'man_hinh = pygame.display.set_mode((RONG, CAO))',
          'dong_ho = pygame.time.Clock()',
          '',
          'y, vy = 100.0, 0.0',
          'GIA_TOC_ROI = 0.6',
          'HE_SO_NAY = 0.75',
          'DAY = CAO - 50',
          '',
          'dang_chay = True',
          'while dang_chay:',
          '    for su_kien in pygame.event.get():',
          '        if su_kien.type == pygame.QUIT:',
          '            dang_chay = False',
          '        elif su_kien.type == pygame.KEYDOWN:',
          '            if su_kien.key == pygame.K_SPACE:',
          '                y, vy = 100.0, 0.0',
          '',
          '    vy += GIA_TOC_ROI',
          '    y += vy',
          '',
          '    if y > DAY:',
          '        y = DAY',
          '        vy = -vy * HE_SO_NAY',
          '',
          '    man_hinh.fill((25, 25, 45))',
          '    pygame.draw.line(man_hinh, (100, 100, 130), (0, DAY + 20), (RONG, DAY + 20), 3)',
          '    pygame.draw.circle(man_hinh, (231, 76, 60), (400, int(y)), 20)',
          '    pygame.display.flip()',
          '    dong_ho.tick(60)',
          '',
          'pygame.quit()',
        ], 'Bóng nảy thấp dần rồi dừng hẳn, và giải thích được vai trò của hệ số nảy.'),
        challenge({
          slug: 'p-pg-b10-ma-sat-va-gia-toc',
          title: 'Vận tốc sau N khung hình có ma sát',
          statement: [
            'Vận tốc ban đầu là `v` (số thực). Mỗi khung hình, vận tốc lần lượt được:',
            '',
            '1. Cộng thêm gia tốc `a`',
            '2. Nhân với hệ số ma sát `f`',
            '',
            'Đọc **bốn dòng**: `v`, `a`, `f` (số thực) và `N` (số nguyên).',
            '',
            'In ra **một dòng**: `Van toc: <v>` với `<v>` hiển thị **3 chữ số thập phân**.',
            '',
            'Chú ý đúng thứ tự: cộng gia tốc trước, nhân ma sát sau.',
          ].join('\n'),
          hints: [
            'Trong mỗi vòng lặp: `v = (v + a) * f`.',
            'Lặp đúng N lần.',
            'Định dạng ba chữ số thập phân là `{v:.3f}`.',
          ],
          starterCode: [
            'v = float(input())',
            'a = float(input())',
            'f = float(input())',
            'n = int(input())',
            '',
            '# Lặp n khung hình',
          ].join('\n'),
          solutionCode: [
            'v = float(input())',
            'a = float(input())',
            'f = float(input())',
            'n = int(input())',
            '',
            'for i in range(n):',
            '    v = (v + a) * f',
            '',
            'print(f"Van toc: {v:.3f}")',
          ].join('\n'),
          tier: 'NANG_CAO',
          judgeMode: 'IO_MATCH',
          tests: [
            sample(
              '0\n0.5\n0.9\n1\n',
              'Van toc: 0.450\n',
              '(0 + 0.5) × 0.9 = 0.45.',
            ),
            sample('10\n0\n0.5\n3\n', 'Van toc: 1.250\n', '10 → 5 → 2.5 → 1.25.'),
            hidden('0\n0\n0.9\n100\n', 'Van toc: 0.000\n', 25),
            hidden('5\n0\n1.0\n50\n', 'Van toc: 5.000\n', 25),
            hidden('0\n1\n0.5\n10\n', 'Van toc: 0.999\n', 25),
            hidden('-3\n0.2\n0.8\n5\n', 'Van toc: -0.454\n', 25),
          ],
        }),
      ],
    },

    {
      order: 11,
      slug: 'pg-b11-vat-ly-trong-luc-nhay',
      title: 'Vật lý game: trọng lực & cơ chế nhảy',
      summary:
        'Buổi riêng cho trọng lực. Đây là nền móng của mọi game platformer — và cũng là nơi ' +
        'quyết định game "cảm giác" tốt hay không.',
      objectives: [
        'Cài đặt trọng lực bằng gia tốc theo trục y',
        'Làm nhân vật nhảy bằng một xung vận tốc âm',
        'Chỉ cho nhảy khi đang đứng trên mặt đất',
        'Tinh chỉnh cảm giác nhảy: nhảy cao thấp, nhảy đôi, coyote time',
      ],
      difficulty: 4,
      status: 'REQUIRED',
      teacherNotes:
        'GHI CHÚ Module 3: buổi RIÊNG cho vật lý, tách khỏi chuyển động nâng cao. ' +
        'Cho học sinh tự chỉnh các hằng số để cảm nhận — đây là bài học quan trọng nhất về game feel.',
      blocks: [
        theory('Trọng lực chỉ là gia tốc hướng xuống', [
          'Trọng lực trong game đơn giản đến bất ngờ — chỉ một dòng:',
          '',
          '```python',
          'TRONG_LUC = 0.8',
          '',
          'vy += TRONG_LUC      # mỗi khung hình rơi nhanh thêm một chút',
          'y += vy',
          '```',
          '',
          'Vì `vy` cứ tăng mãi, vật rơi ngày càng nhanh — đúng như vật lý thật.',
          '',
          '**Nhảy** là một cú hích vận tốc lên trên (giá trị âm):',
          '',
          '```python',
          'LUC_NHAY = -15',
          '',
          'if su_kien.key == pygame.K_SPACE and tren_mat_dat:',
          '    vy = LUC_NHAY',
          '```',
          '',
          'Sau cú hích, trọng lực tự động kéo nhân vật chậm lại, dừng ở đỉnh, rồi rơi xuống. ' +
            'Em không cần viết thêm gì cho việc rơi cả.',
          '',
          '**Kiểm tra đứng trên mặt đất:**',
          '',
          '```python',
          'tren_mat_dat = False',
          'if rect.bottom >= MAT_DAT:',
          '    rect.bottom = MAT_DAT',
          '    vy = 0',
          '    tren_mat_dat = True',
          '```',
          '',
          'Thiếu kiểm tra này, người chơi sẽ bấm nhảy liên tục và bay lên trời.',
        ], [
          'Trọng lực = `vy += TRONG_LUC` mỗi khung hình',
          'Nhảy = đặt `vy` thành một số âm',
          'Chỉ cho nhảy khi `tren_mat_dat` là True',
          'Chạm đất thì đặt `vy = 0`',
        ]),
        theory('Ba mẹo làm cú nhảy "đã tay"', [
          'Trọng lực đúng công thức chưa chắc đã vui. Các game hay nhất đều "gian lận" một chút:',
          '',
          '**1. Nhảy cao thấp theo thời gian giữ phím** — thả phím sớm thì nhảy thấp:',
          '',
          '```python',
          'if su_kien.type == pygame.KEYUP:',
          '    if su_kien.key == pygame.K_SPACE and vy < 0:',
          '        vy *= 0.4          # cắt bớt lực nhảy khi thả sớm',
          '```',
          '',
          '**2. Coyote time** — cho phép nhảy trong vài khung hình sau khi vừa rời mép:',
          '',
          '```python',
          'if tren_mat_dat:',
          '    thoi_gian_coyote = 6',
          'elif thoi_gian_coyote > 0:',
          '    thoi_gian_coyote -= 1',
          '',
          '# Cho nhay khi tren_mat_dat HOAC thoi_gian_coyote > 0',
          '```',
          '',
          'Tên gọi đến từ phim hoạt hình Wile E. Coyote — chạy khỏi vách đá vẫn lơ lửng một lúc. ' +
            'Người chơi không nhận ra, nhưng game "cảm giác" công bằng hơn hẳn.',
          '',
          '**3. Rơi nhanh hơn lúc lên** — nhân trọng lực khi đang rơi:',
          '',
          '```python',
          'if vy > 0:',
          '    vy += TRONG_LUC * 1.6    # rơi nhanh hơn',
          'else:',
          '    vy += TRONG_LUC',
          '```',
          '',
          'Mario dùng chính mẹo này. Cú nhảy vì thế gọn gàng và dứt khoát.',
        ], [
          'Thả phím sớm → nhảy thấp hơn',
          'Coyote time: cho nhảy vài khung sau khi rời mép',
          'Rơi nhanh hơn lúc lên làm cú nhảy dứt khoát hơn',
        ], { tier: 'NANG_CAO' }),
        example('Nhảy hoàn chỉnh có coyote time', 'Bấm phím cách để nhảy. Giữ lâu nhảy cao, thả sớm nhảy thấp.', [
          'import pygame',
          '',
          'pygame.init()',
          'RONG, CAO = 800, 600',
          'man_hinh = pygame.display.set_mode((RONG, CAO))',
          'pygame.display.set_caption("Trong luc & Nhay")',
          'dong_ho = pygame.time.Clock()',
          'phong_chu = pygame.font.SysFont("arial", 18)',
          '',
          'MAT_DAT = 500',
          'TRONG_LUC = 0.8',
          'LUC_NHAY = -16',
          'HE_SO_ROI_NHANH = 1.6',
          'COYOTE_TOI_DA = 6',
          '',
          'nv = pygame.Rect(380, MAT_DAT - 50, 40, 50)',
          'vy = 0.0',
          'vx = 0.0',
          'tren_mat_dat = True',
          'coyote = COYOTE_TOI_DA',
          '',
          'dang_chay = True',
          'while dang_chay:',
          '    for su_kien in pygame.event.get():',
          '        if su_kien.type == pygame.QUIT:',
          '            dang_chay = False',
          '        elif su_kien.type == pygame.KEYDOWN:',
          '            if su_kien.key == pygame.K_SPACE and (tren_mat_dat or coyote > 0):',
          '                vy = LUC_NHAY',
          '                tren_mat_dat = False',
          '                coyote = 0',
          '        elif su_kien.type == pygame.KEYUP:',
          '            if su_kien.key == pygame.K_SPACE and vy < 0:',
          '                vy *= 0.4        # tha som -> nhay thap',
          '',
          '    phim = pygame.key.get_pressed()',
          '    vx = 0.0',
          '    if phim[pygame.K_LEFT]:',
          '        vx = -6',
          '    if phim[pygame.K_RIGHT]:',
          '        vx = 6',
          '',
          '    # Roi nhanh hon luc len',
          '    if vy > 0:',
          '        vy += TRONG_LUC * HE_SO_ROI_NHANH',
          '    else:',
          '        vy += TRONG_LUC',
          '',
          '    nv.x += int(vx)',
          '    nv.y += int(vy)',
          '',
          '    if nv.bottom >= MAT_DAT:',
          '        nv.bottom = MAT_DAT',
          '        vy = 0.0',
          '        tren_mat_dat = True',
          '        coyote = COYOTE_TOI_DA',
          '    else:',
          '        tren_mat_dat = False',
          '        if coyote > 0:',
          '            coyote -= 1',
          '',
          '    nv.clamp_ip(man_hinh.get_rect())',
          '',
          '    man_hinh.fill((30, 30, 55))',
          '    pygame.draw.rect(man_hinh, (39, 174, 96), (0, MAT_DAT, RONG, CAO - MAT_DAT))',
          '    pygame.draw.rect(man_hinh, (52, 152, 219), nv, 0, border_radius=6)',
          '',
          '    man_hinh.blit(phong_chu.render(',
          '        f"vy: {vy:6.2f}   tren_mat_dat: {tren_mat_dat}   coyote: {coyote}",',
          '        True, (220, 220, 240)), (10, 10))',
          '    man_hinh.blit(phong_chu.render(',
          '        "CACH de nhay (giu lau nhay cao hon)", True, (150, 150, 180)), (10, 34))',
          '',
          '    pygame.display.flip()',
          '    dong_ho.tick(60)',
          '',
          'pygame.quit()',
        ], {
          output: 'Nhân vật xanh nhảy trên nền cỏ, có chỉ số vy, trạng thái mặt đất và coyote hiển thị trực tiếp.',
          notes: [
            'Thử bấm nhanh và thả ngay — nhân vật chỉ nhảy thấp. Giữ lâu thì nhảy cao. Đó là mẹo số 1.',
            'Thử đổi `LUC_NHAY` thành -25 và `TRONG_LUC` thành 0.3 để có cảm giác nhảy trên Mặt Trăng.',
            'Việc hiển thị các chỉ số ngay trên màn hình là cách gỡ lỗi game hiệu quả nhất.',
          ],
        }),
        playground('Sân chơi: chỉnh cảm giác nhảy', [
          'Không viết thêm code — chỉ chỉnh bốn hằng số và cảm nhận.',
          '',
          '| Muốn gì | Chỉnh gì |',
          '|---|---|',
          '| Nhảy cao hơn | `LUC_NHAY` âm hơn |',
          '| Rơi nhanh hơn | `TRONG_LUC` lớn hơn |',
          '| Cảm giác Mặt Trăng | `TRONG_LUC` nhỏ, `LUC_NHAY` rất âm |',
          '| Nhảy dứt khoát | `HE_SO_ROI_NHANH` lớn hơn |',
          '',
          'Tìm ra bộ số mà em thấy "đã tay" nhất, rồi ghi lại để dùng cho dự án.',
        ], [
          'import pygame',
          '',
          'pygame.init()',
          'RONG, CAO = 800, 600',
          'man_hinh = pygame.display.set_mode((RONG, CAO))',
          'dong_ho = pygame.time.Clock()',
          '',
          '# ==== CHINH BON SO NAY ====',
          'TRONG_LUC = 0.8',
          'LUC_NHAY = -16',
          'HE_SO_ROI_NHANH = 1.6',
          'TOC_DO_NGANG = 6',
          '# ==========================',
          '',
          'MAT_DAT = 500',
          'nv = pygame.Rect(380, MAT_DAT - 50, 40, 50)',
          'vy = 0.0',
          'tren_mat_dat = True',
          '',
          'dang_chay = True',
          'while dang_chay:',
          '    for su_kien in pygame.event.get():',
          '        if su_kien.type == pygame.QUIT:',
          '            dang_chay = False',
          '        elif su_kien.type == pygame.KEYDOWN:',
          '            if su_kien.key == pygame.K_SPACE and tren_mat_dat:',
          '                vy = LUC_NHAY',
          '',
          '    phim = pygame.key.get_pressed()',
          '    if phim[pygame.K_LEFT]:',
          '        nv.x -= TOC_DO_NGANG',
          '    if phim[pygame.K_RIGHT]:',
          '        nv.x += TOC_DO_NGANG',
          '',
          '    vy += TRONG_LUC * (HE_SO_ROI_NHANH if vy > 0 else 1)',
          '    nv.y += int(vy)',
          '',
          '    if nv.bottom >= MAT_DAT:',
          '        nv.bottom = MAT_DAT',
          '        vy = 0.0',
          '        tren_mat_dat = True',
          '    else:',
          '        tren_mat_dat = False',
          '',
          '    man_hinh.fill((30, 30, 55))',
          '    pygame.draw.rect(man_hinh, (39, 174, 96), (0, MAT_DAT, RONG, 100))',
          '    pygame.draw.rect(man_hinh, (52, 152, 219), nv)',
          '    pygame.display.flip()',
          '    dong_ho.tick(60)',
          '',
          'pygame.quit()',
        ], 'Tìm được bộ hằng số cho cảm giác nhảy em thích và giải thích được vì sao.'),
        challenge({
          slug: 'p-pg-b11-do-cao-cu-nhay',
          title: 'Độ cao tối đa của cú nhảy',
          statement: [
            'Nhân vật đứng ở độ cao `y = 0` (càng lớn càng thấp, đúng như toạ độ màn hình) và nhảy ' +
              'với vận tốc ban đầu `v0` (số âm).',
            '',
            'Mỗi khung hình: `v += g` rồi `y += v`.',
            '',
            'Đọc **hai dòng**: `v0` và `g` (số thực, `g` dương).',
            '',
            'In ra **một dòng**: `Do cao: <h>` trong đó `<h>` là **độ cao lớn nhất** đạt được so với ' +
              'điểm xuất phát, hiển thị **2 chữ số thập phân** và là số **dương**.',
            '',
            'Gợi ý: mô phỏng cho tới khi `v >= 0` (nhân vật bắt đầu rơi), theo dõi giá trị `y` nhỏ nhất.',
          ].join('\n'),
          hints: [
            'Vì y càng nhỏ càng cao, hãy theo dõi giá trị y NHỎ NHẤT.',
            'Dừng vòng lặp khi v >= 0 — lúc đó nhân vật đã tới đỉnh.',
            'Độ cao là `-y_nho_nhat` vì y xuất phát từ 0 và giảm dần khi lên cao.',
          ],
          starterCode: [
            'v = float(input())',
            'g = float(input())',
            '',
            'y = 0.0',
            'cao_nhat = 0.0',
            '',
            '# Mô phỏng tới khi nhân vật bắt đầu rơi',
          ].join('\n'),
          solutionCode: [
            'v = float(input())',
            'g = float(input())',
            '',
            'y = 0.0',
            'cao_nhat = 0.0',
            '',
            'while v < 0:',
            '    v += g',
            '    y += v',
            '    if y < cao_nhat:',
            '        cao_nhat = y',
            '',
            'print(f"Do cao: {-cao_nhat:.2f}")',
          ].join('\n'),
          tier: 'NANG_CAO',
          judgeMode: 'IO_MATCH',
          timeLimitMs: 3000,
          tests: [
            sample(
              '-10\n1\n',
              'Do cao: 45.00\n',
              'Vận tốc giảm dần 10→9→...→1, tổng quãng đường lên là 9+8+...+1+0 = 45.',
            ),
            sample('-4\n2\n', 'Do cao: 4.00\n', 'Chỉ hai khung hình: lên 2 rồi lên 2 nữa.'),
            hidden('-1\n1\n', 'Do cao: 0.00\n', 25),
            hidden('-16\n0.8\n', 'Do cao: 152.00\n', 25),
            hidden('-20\n2\n', 'Do cao: 90.00\n', 25),
            hidden('-5\n0.5\n', 'Do cao: 22.50\n', 25),
          ],
        }),
      ],
    },

    {
      order: 12,
      slug: 'pg-b12-phat-hien-va-cham',
      title: 'Phát hiện va chạm: `Rect` & `Mask`',
      summary:
        'Hai kỹ thuật kiểm tra va chạm: hình chữ nhật cho nhanh, và mặt nạ theo pixel cho chính xác.',
      objectives: [
        'Dùng `rect.colliderect()` cho va chạm hai vật',
        'Dùng các hàm va chạm của Sprite Group',
        'Hiểu khi nào va chạm hình chữ nhật là chưa đủ',
        'Dùng `pygame.mask` cho va chạm chính xác theo pixel',
      ],
      difficulty: 4,
      status: 'REQUIRED',
      teacherNotes: 'Va chạm Rect là đủ cho 95% trường hợp. Mask chỉ giới thiệu để học sinh biết khi cần.',
      blocks: [
        theory('Va chạm hình chữ nhật', [
          'Cách nhanh nhất và dùng nhiều nhất:',
          '',
          '```python',
          'if nhan_vat.rect.colliderect(ke_dich.rect):',
          '    print("Va cham!")',
          '```',
          '',
          '**Với Sprite Group**, Pygame có sẵn ba hàm rất tiện:',
          '',
          '```python',
          '# 1. Mot sprite voi ca nhom -> tra ve DANH SACH sprite bi cham',
          'trung = pygame.sprite.spritecollide(nhan_vat, nhom_vat_pham, True)',
          '#                                                            ^^^^',
          '#                                        True = xoa vat pham bi cham',
          '',
          '# 2. Hai nhom voi nhau -> tra ve TU DIEN',
          'va_cham = pygame.sprite.groupcollide(nhom_dan, nhom_dich, True, True)',
          '',
          '# 3. Chi kiem tra co hay khong (nhanh nhat)',
          'if pygame.sprite.spritecollideany(nhan_vat, nhom_bay):',
          '    mat_mang()',
          '```',
          '',
          'Hàm `spritecollide` với tham số `True` vừa phát hiện vừa xoá vật phẩm — đúng một dòng ' +
            'là xong logic "ăn xu".',
        ], [
          '`colliderect()` cho hai Rect',
          '`spritecollide(sprite, nhom, xoa)` cho một sprite với cả nhóm',
          '`groupcollide(nhom1, nhom2, xoa1, xoa2)` cho hai nhóm — dùng cho đạn và kẻ địch',
        ]),
        theory('Khi hình chữ nhật là chưa đủ', [
          'Rect luôn là hình chữ nhật thẳng. Với một con tàu hình tam giác hay một hành tinh tròn, ' +
            'phần góc của Rect là khoảng trống — mà máy vẫn báo va chạm.',
          '',
          '```',
          '   ┌─────────┐',
          '   │   ╱▲╲   │   ← góc này TRỐNG nhưng vẫn tính là va chạm',
          '   │  ╱███╲  │',
          '   │ ╱█████╲ │',
          '   └─────────┘',
          '```',
          '',
          'Người chơi sẽ thấy "chết oan" và rất bực.',
          '',
          '**Hai cách xử lý:**',
          '',
          '**1. Thu nhỏ Rect** — đơn giản, hiệu quả, dùng nhiều nhất:',
          '',
          '```python',
          'khung_va_cham = self.rect.inflate(-20, -20)   # nho hon 20 diem moi chieu',
          'if khung_va_cham.colliderect(ke_dich.rect):',
          '    ...',
          '```',
          '',
          '**2. Mask — va chạm theo pixel**, chính xác tuyệt đối nhưng chậm hơn:',
          '',
          '```python',
          'self.mask = pygame.mask.from_surface(self.image)',
          '',
          'if pygame.sprite.collide_mask(nhan_vat, ke_dich):',
          '    ...',
          '```',
          '',
          '💡 **Mẹo tối ưu:** kiểm tra Rect trước (rất nhanh), chỉ khi Rect chạm nhau mới kiểm tra ' +
            'Mask. Cách này cho độ chính xác của Mask với tốc độ gần bằng Rect.',
        ], [
          'Rect nhanh nhưng có góc trống',
          '`rect.inflate(-20, -20)` thu nhỏ vùng va chạm — cách đơn giản nhất',
          'Mask chính xác theo pixel nhưng chậm hơn',
          'Kiểm tra Rect trước, Mask sau để vừa nhanh vừa chính xác',
        ]),
        example('Ba loại va chạm trong một demo', 'Điều khiển bằng mũi tên. Ăn xu, tránh gai, và bắn mục tiêu.', [
          'import pygame',
          'import random',
          '',
          'pygame.init()',
          'RONG, CAO = 800, 600',
          'man_hinh = pygame.display.set_mode((RONG, CAO))',
          'pygame.display.set_caption("Va cham")',
          'dong_ho = pygame.time.Clock()',
          'phong_chu = pygame.font.SysFont("arial", 22)',
          '',
          '',
          'def tao_sprite(mau, kich_thuoc, x, y, tron=False):',
          '    s = pygame.sprite.Sprite()',
          '    s.image = pygame.Surface(kich_thuoc, pygame.SRCALPHA)',
          '    if tron:',
          '        r = kich_thuoc[0] // 2',
          '        pygame.draw.circle(s.image, mau, (r, r), r)',
          '    else:',
          '        s.image.fill(mau)',
          '    s.rect = s.image.get_rect(center=(x, y))',
          '    return s',
          '',
          '',
          'nhan_vat = tao_sprite((52, 152, 219), (44, 44), 400, 500)',
          'nhom_nhan_vat = pygame.sprite.Group(nhan_vat)',
          '',
          'nhom_xu = pygame.sprite.Group()',
          'for i in range(10):',
          '    nhom_xu.add(tao_sprite((241, 196, 15), (24, 24),',
          '                           random.randint(30, RONG - 30),',
          '                           random.randint(30, 400), tron=True))',
          '',
          'nhom_gai = pygame.sprite.Group()',
          'for i in range(4):',
          '    nhom_gai.add(tao_sprite((231, 76, 60), (36, 36),',
          '                            random.randint(30, RONG - 30),',
          '                            random.randint(150, 400)))',
          '',
          'diem = 0',
          'mau_nen = (25, 25, 45)',
          '',
          'dang_chay = True',
          'while dang_chay:',
          '    for su_kien in pygame.event.get():',
          '        if su_kien.type == pygame.QUIT:',
          '            dang_chay = False',
          '',
          '    phim = pygame.key.get_pressed()',
          '    if phim[pygame.K_LEFT]:',
          '        nhan_vat.rect.x -= 7',
          '    if phim[pygame.K_RIGHT]:',
          '        nhan_vat.rect.x += 7',
          '    if phim[pygame.K_UP]:',
          '        nhan_vat.rect.y -= 7',
          '    if phim[pygame.K_DOWN]:',
          '        nhan_vat.rect.y += 7',
          '    nhan_vat.rect.clamp_ip(man_hinh.get_rect())',
          '',
          '    # 1. An xu: phat hien VA xoa trong mot dong',
          '    an_duoc = pygame.sprite.spritecollide(nhan_vat, nhom_xu, True)',
          '    diem += len(an_duoc) * 10',
          '',
          '    # 2. Cham gai: chi kiem tra co hay khong',
          '    if pygame.sprite.spritecollideany(nhan_vat, nhom_gai):',
          '        mau_nen = (80, 25, 30)',
          '    else:',
          '        mau_nen = (25, 25, 45)',
          '',
          '    man_hinh.fill(mau_nen)',
          '    nhom_xu.draw(man_hinh)',
          '    nhom_gai.draw(man_hinh)',
          '    nhom_nhan_vat.draw(man_hinh)',
          '',
          '    man_hinh.blit(phong_chu.render(',
          '        f"Diem: {diem}   Con lai: {len(nhom_xu)} xu", True, (255, 255, 255)), (10, 10))',
          '',
          '    pygame.display.flip()',
          '    dong_ho.tick(60)',
          '',
          'pygame.quit()',
        ], {
          output: 'Ô vuông xanh ăn các đồng xu vàng và làm nền chuyển đỏ khi chạm gai.',
          notes: [
            '`spritecollide(..., True)` vừa phát hiện vừa xoá — logic ăn xu chỉ mất một dòng.',
            '`len(an_duoc)` cho biết ăn được mấy xu trong khung hình đó, phòng khi ăn hai xu cùng lúc.',
            '`spritecollideany` nhanh hơn vì nó dừng ngay khi tìm thấy va chạm đầu tiên.',
          ],
        }),
        playground('Sân chơi: thu nhỏ vùng va chạm', [
          'Chạy demo và chú ý: nhân vật đôi khi "chết oan" khi chỉ mới gần chạm gai.',
          '',
          'Hãy thu nhỏ vùng va chạm của nhân vật bằng `inflate(-12, -12)` và cảm nhận sự khác biệt.',
          '',
          'Thử vẽ cả vùng va chạm bằng một hình chữ nhật viền để nhìn thấy nó.',
        ], [
          'import pygame',
          '',
          'pygame.init()',
          'man_hinh = pygame.display.set_mode((800, 600))',
          'dong_ho = pygame.time.Clock()',
          '',
          'nv = pygame.Rect(0, 0, 60, 60)',
          'nv.center = (400, 300)',
          'chuong_ngai = pygame.Rect(500, 250, 80, 80)',
          '',
          'dang_chay = True',
          'while dang_chay:',
          '    for su_kien in pygame.event.get():',
          '        if su_kien.type == pygame.QUIT:',
          '            dang_chay = False',
          '',
          '    nv.center = pygame.mouse.get_pos()',
          '',
          '    # Thu doi dong duoi thanh: khung_va_cham = nv.inflate(-24, -24)',
          '    khung_va_cham = nv',
          '    cham = khung_va_cham.colliderect(chuong_ngai)',
          '',
          '    man_hinh.fill((25, 25, 45))',
          '    pygame.draw.rect(man_hinh, (231, 76, 60) if cham else (52, 152, 219), nv)',
          '    pygame.draw.rect(man_hinh, (255, 255, 0), khung_va_cham, 2)',
          '    pygame.draw.rect(man_hinh, (149, 165, 166), chuong_ngai)',
          '    pygame.display.flip()',
          '    dong_ho.tick(60)',
          '',
          'pygame.quit()',
        ], 'Thấy rõ vùng va chạm nhỏ hơn hình vẽ và giải thích được vì sao game thật hay làm vậy.'),
        challenge({
          slug: 'p-pg-b12-kiem-tra-va-cham-rect',
          title: 'Kiểm tra va chạm hai hình chữ nhật',
          statement: [
            'Hai hình chữ nhật được cho bằng góc trên bên trái, chiều rộng và chiều cao.',
            '',
            'Hai hình **chồng lấn** khi chúng có phần diện tích chung. Chỉ chạm mép (không có diện tích ' +
              'chung) thì **không** tính là va chạm — đúng như `pygame.Rect.colliderect()`.',
            '',
            'Dòng đầu: số nguyên `Q`. `Q` dòng tiếp theo, mỗi dòng tám số nguyên: ' +
              '`x1 y1 w1 h1 x2 y2 w2 h2`.',
            '',
            'Với mỗi dòng, in `CHAM` hoặc `KHONG` trên một dòng riêng.',
          ].join('\n'),
          hints: [
            'Hai hình KHÔNG chạm khi một hình nằm hoàn toàn về một phía của hình kia.',
            'Không chạm nếu: `x1 + w1 <= x2` hoặc `x2 + w2 <= x1` hoặc `y1 + h1 <= y2` hoặc `y2 + h2 <= y1`.',
            'Chạm chính là phủ định của bốn điều kiện trên.',
          ],
          starterCode: [
            'q = int(input())',
            '',
            'for i in range(q):',
            '    x1, y1, w1, h1, x2, y2, w2, h2 = map(int, input().split())',
            '    # Kiểm tra chồng lấn',
          ].join('\n'),
          solutionCode: [
            'q = int(input())',
            '',
            'for i in range(q):',
            '    x1, y1, w1, h1, x2, y2, w2, h2 = map(int, input().split())',
            '    tach_roi = (x1 + w1 <= x2 or x2 + w2 <= x1 or',
            '                y1 + h1 <= y2 or y2 + h2 <= y1)',
            '    if tach_roi:',
            '        print("KHONG")',
            '    else:',
            '        print("CHAM")',
          ].join('\n'),
          tier: 'CO_BAN',
          judgeMode: 'IO_MATCH',
          tests: [
            sample(
              '2\n0 0 50 50 25 25 50 50\n0 0 50 50 50 0 50 50\n',
              'CHAM\nKHONG\n',
              'Trường hợp hai chỉ chạm mép tại x = 50 nên không có diện tích chung.',
            ),
            sample('1\n0 0 10 10 5 5 2 2\n', 'CHAM\n', 'Hình nhỏ nằm hoàn toàn bên trong hình lớn.'),
            hidden('1\n0 0 10 10 20 20 5 5\n', 'KHONG\n', 20),
            hidden('1\n0 0 100 100 0 0 100 100\n', 'CHAM\n', 20),
            hidden('1\n0 0 10 10 9 9 10 10\n', 'CHAM\n', 20),
            hidden('1\n0 0 10 10 0 10 10 10\n', 'KHONG\n', 20),
            hidden('1\n-5 -5 10 10 0 0 10 10\n', 'CHAM\n', 20),
          ],
        }),
      ],
    },

    {
      order: 13,
      slug: 'pg-b13-phan-hoi-va-cham-va-logic',
      title: 'Phản hồi va chạm & logic trò chơi',
      summary:
        'Phát hiện va chạm mới là một nửa. Buổi này học cách **phản ứng**: nảy đúng hướng, ' +
        'đẩy ra khỏi tường, huỷ đối tượng.',
      objectives: [
        'Xác định hướng va chạm để phản ứng đúng',
        'Đẩy nhân vật ra khỏi tường mà không bị kẹt',
        'Xử lý va chạm theo từng trục riêng biệt',
        'Cài đặt cơ chế bất tử tạm thời sau khi trúng đòn',
      ],
      difficulty: 4,
      status: 'REQUIRED',
      teacherNotes:
        'Kỹ thuật tách hai trục là chìa khoá của mọi platformer. Học sinh phải làm được ở buổi này ' +
        'trước khi vào Module 4.',
      blocks: [
        theory('Kỹ thuật quan trọng nhất: tách hai trục', [
          'Khi nhân vật đâm vào tường, ta cần biết nó đâm từ **hướng nào** để đẩy ra đúng chiều. ' +
            'Nếu di chuyển cả hai trục cùng lúc rồi mới kiểm tra, gần như không thể biết được.',
          '',
          '**Giải pháp:** di chuyển và xử lý **từng trục một**.',
          '',
          '```python',
          '# --- TRUC X ---',
          'rect.x += vx',
          'for tuong in danh_sach_tuong:',
          '    if rect.colliderect(tuong):',
          '        if vx > 0:                # dang di sang PHAI',
          '            rect.right = tuong.left',
          '        elif vx < 0:              # dang di sang TRAI',
          '            rect.left = tuong.right',
          '        vx = 0',
          '',
          '# --- TRUC Y ---',
          'rect.y += vy',
          'for tuong in danh_sach_tuong:',
          '    if rect.colliderect(tuong):',
          '        if vy > 0:                # dang ROI xuong',
          '            rect.bottom = tuong.top',
          '            tren_mat_dat = True',
          '        elif vy < 0:              # dang BAY len',
          '            rect.top = tuong.bottom',
          '        vy = 0',
          '```',
          '',
          '**Vì sao cách này đúng?** Vì trong mỗi khối, ta biết chắc nhân vật chỉ vừa di chuyển ' +
            'theo một trục. Dấu của `vx` (hoặc `vy`) cho biết ngay nó đến từ hướng nào.',
          '',
          'Đây là kỹ thuật nền tảng của mọi game platformer. Hãy đọc lại đoạn trên vài lần.',
        ], [
          'Di chuyển trục X → xử lý va chạm X → di chuyển trục Y → xử lý va chạm Y',
          'Dấu của vận tốc cho biết hướng va chạm',
          'Đặt mép sát vào tường thay vì lùi lại một khoảng cố định',
        ]),
        theory('Nảy đúng hướng và bất tử tạm thời', [
          '**Nảy theo hướng va chạm** — với bóng Pong, nảy dọc hay ngang tuỳ mặt bị chạm:',
          '',
          '```python',
          '# Cham hai ben trai/phai -> doi huong ngang',
          'if bong.rect.left <= 0 or bong.rect.right >= RONG:',
          '    vx = -vx',
          '',
          '# Cham tren/duoi -> doi huong doc',
          'if bong.rect.top <= 0 or bong.rect.bottom >= CAO:',
          '    vy = -vy',
          '```',
          '',
          '**Nảy theo điểm chạm trên paddle** — mẹo làm Pong hay hơn hẳn:',
          '',
          '```python',
          '# Cham gan mep paddle -> nay xien nhieu hon',
          'lech = (bong.rect.centerx - paddle.rect.centerx) / (paddle.rect.width / 2)',
          'vx = lech * 8      # lech tu -1 den 1',
          'vy = -abs(vy)      # luon nay len',
          '```',
          '',
          'Nhờ vậy người chơi điều khiển được hướng bóng — trò chơi từ may rủi thành có kỹ năng.',
          '',
          '**Bất tử tạm thời** — tránh mất hết máu trong một lần chạm:',
          '',
          '```python',
          'if bat_tu > 0:',
          '    bat_tu -= 1',
          'elif pygame.sprite.spritecollideany(nhan_vat, nhom_dich):',
          '    mang -= 1',
          '    bat_tu = 90            # 1.5 giay o 60 FPS',
          '',
          '# Nhap nhay de bao hieu dang bat tu',
          'if bat_tu == 0 or (bat_tu // 5) % 2 == 0:',
          '    man_hinh.blit(nhan_vat.image, nhan_vat.rect)',
          '```',
        ], [
          'Nảy theo điểm chạm làm Pong có chiều sâu hơn hẳn',
          'Bất tử tạm thời tránh mất hết máu trong một lần chạm',
          'Nhấp nháy để người chơi biết đang bất tử',
        ]),
        example('Nhân vật đi trong mê cung tường', 'Kỹ thuật tách hai trục, áp dụng đầy đủ.', [
          'import pygame',
          '',
          'pygame.init()',
          'RONG, CAO = 800, 600',
          'man_hinh = pygame.display.set_mode((RONG, CAO))',
          'pygame.display.set_caption("Va cham voi tuong")',
          'dong_ho = pygame.time.Clock()',
          '',
          'tuong = [',
          '    pygame.Rect(150, 150, 300, 30),',
          '    pygame.Rect(150, 150, 30, 250),',
          '    pygame.Rect(500, 250, 30, 300),',
          '    pygame.Rect(200, 420, 350, 30),',
          '    pygame.Rect(0, 0, RONG, 20),',
          '    pygame.Rect(0, CAO - 20, RONG, 20),',
          '    pygame.Rect(0, 0, 20, CAO),',
          '    pygame.Rect(RONG - 20, 0, 20, CAO),',
          ']',
          '',
          'nv = pygame.Rect(60, 60, 34, 34)',
          'TOC_DO = 5',
          '',
          'dang_chay = True',
          'while dang_chay:',
          '    for su_kien in pygame.event.get():',
          '        if su_kien.type == pygame.QUIT:',
          '            dang_chay = False',
          '',
          '    phim = pygame.key.get_pressed()',
          '    vx = vy = 0',
          '    if phim[pygame.K_LEFT]:',
          '        vx = -TOC_DO',
          '    if phim[pygame.K_RIGHT]:',
          '        vx = TOC_DO',
          '    if phim[pygame.K_UP]:',
          '        vy = -TOC_DO',
          '    if phim[pygame.K_DOWN]:',
          '        vy = TOC_DO',
          '',
          '    # ===== TRUC X =====',
          '    nv.x += vx',
          '    for t in tuong:',
          '        if nv.colliderect(t):',
          '            if vx > 0:',
          '                nv.right = t.left',
          '            elif vx < 0:',
          '                nv.left = t.right',
          '',
          '    # ===== TRUC Y =====',
          '    nv.y += vy',
          '    for t in tuong:',
          '        if nv.colliderect(t):',
          '            if vy > 0:',
          '                nv.bottom = t.top',
          '            elif vy < 0:',
          '                nv.top = t.bottom',
          '',
          '    man_hinh.fill((25, 25, 45))',
          '    for t in tuong:',
          '        pygame.draw.rect(man_hinh, (110, 120, 140), t)',
          '    pygame.draw.rect(man_hinh, (46, 204, 113), nv, 0, border_radius=5)',
          '    pygame.display.flip()',
          '    dong_ho.tick(60)',
          '',
          'pygame.quit()',
        ], {
          output: 'Nhân vật xanh đi trong mê cung, trượt dọc theo tường thay vì bị kẹt cứng.',
          notes: [
            'Thử gộp hai khối X và Y thành một — nhân vật sẽ bị kẹt ở góc. Đó là lý do phải tách trục.',
            'Nhờ tách trục, nhân vật "trượt" dọc tường khi đi chéo — cảm giác rất tự nhiên.',
            'Bốn tường cuối trong danh sách chính là viền màn hình.',
          ],
        }),
        playground('Sân chơi: bóng nảy theo điểm chạm', [
          'Làm một paddle và một quả bóng. Khi bóng chạm paddle, hướng nảy phụ thuộc vào **điểm chạm**:',
          '',
          '- Chạm giữa paddle → nảy thẳng lên',
          '- Chạm mép trái → nảy chéo sang trái',
          '- Chạm mép phải → nảy chéo sang phải',
          '',
          'Đây chính là cơ chế làm Pong trở nên thú vị.',
        ], [
          'import pygame',
          '',
          'pygame.init()',
          'RONG, CAO = 800, 600',
          'man_hinh = pygame.display.set_mode((RONG, CAO))',
          'dong_ho = pygame.time.Clock()',
          '',
          'paddle = pygame.Rect(0, 0, 140, 18)',
          'paddle.center = (400, 540)',
          'bong = pygame.Rect(0, 0, 18, 18)',
          'bong.center = (400, 300)',
          'vx, vy = 5.0, 5.0',
          '',
          'dang_chay = True',
          'while dang_chay:',
          '    for su_kien in pygame.event.get():',
          '        if su_kien.type == pygame.QUIT:',
          '            dang_chay = False',
          '',
          '    paddle.centerx = pygame.mouse.get_pos()[0]',
          '    paddle.clamp_ip(man_hinh.get_rect())',
          '',
          '    bong.x += int(vx)',
          '    bong.y += int(vy)',
          '',
          '    if bong.left <= 0 or bong.right >= RONG:',
          '        vx = -vx',
          '    if bong.top <= 0:',
          '        vy = -vy',
          '    if bong.top > CAO:',
          '        bong.center = (400, 300)',
          '        vx, vy = 5.0, 5.0',
          '',
          '    if bong.colliderect(paddle) and vy > 0:',
          '        # Them phan tinh huong nay theo diem cham o day',
          '        vy = -vy',
          '',
          '    man_hinh.fill((25, 25, 45))',
          '    pygame.draw.rect(man_hinh, (52, 152, 219), paddle, 0, border_radius=9)',
          '    pygame.draw.ellipse(man_hinh, (241, 196, 15), bong)',
          '    pygame.display.flip()',
          '    dong_ho.tick(60)',
          '',
          'pygame.quit()',
        ], 'Bóng nảy theo hướng phụ thuộc vào điểm chạm trên paddle.'),
        challenge({
          slug: 'p-pg-b13-huong-va-cham',
          title: 'Xác định hướng va chạm',
          statement: [
            'Một nhân vật di chuyển với vận tốc `vx`, `vy` và vừa va vào một bức tường.',
            '',
            'Xác định nhân vật đâm vào tường từ hướng nào, dựa trên trục được xét và dấu vận tốc:',
            '',
            '| Trục | Vận tốc | Kết quả |',
            '|---|---|---|',
            '| `X` | `vx > 0` | `PHAI` |',
            '| `X` | `vx < 0` | `TRAI` |',
            '| `Y` | `vy > 0` | `DUOI` |',
            '| `Y` | `vy < 0` | `TREN` |',
            '| bất kỳ | vận tốc bằng 0 | `KHONG` |',
            '',
            'Dòng đầu: số nguyên `Q`. `Q` dòng tiếp theo, mỗi dòng có dạng `<truc> <vx> <vy>` ' +
              'với `<truc>` là `X` hoặc `Y`.',
            '',
            'In kết quả của mỗi lần kiểm tra trên một dòng riêng.',
          ].join('\n'),
          hints: [
            'Tách dòng bằng `.split()`; phần đầu là chữ, hai phần sau là số.',
            'Xét trục trước, rồi mới xét dấu vận tốc tương ứng.',
            'Vận tốc bằng 0 luôn cho KHONG, dù ở trục nào.',
          ],
          starterCode: [
            'q = int(input())',
            '',
            'for i in range(q):',
            '    phan = input().split()',
            '    truc = phan[0]',
            '    vx = int(phan[1])',
            '    vy = int(phan[2])',
            '    # Xác định hướng',
          ].join('\n'),
          solutionCode: [
            'q = int(input())',
            '',
            'for i in range(q):',
            '    phan = input().split()',
            '    truc = phan[0]',
            '    vx = int(phan[1])',
            '    vy = int(phan[2])',
            '',
            '    if truc == "X":',
            '        if vx > 0:',
            '            print("PHAI")',
            '        elif vx < 0:',
            '            print("TRAI")',
            '        else:',
            '            print("KHONG")',
            '    else:',
            '        if vy > 0:',
            '            print("DUOI")',
            '        elif vy < 0:',
            '            print("TREN")',
            '        else:',
            '            print("KHONG")',
          ].join('\n'),
          tier: 'CO_BAN',
          judgeMode: 'IO_MATCH',
          tests: [
            sample(
              '4\nX 5 0\nX -5 0\nY 0 8\nY 0 -8\n',
              'PHAI\nTRAI\nDUOI\nTREN\n',
              'Mỗi dòng minh hoạ một hướng va chạm.',
            ),
            sample('2\nX 0 5\nY 5 0\n', 'KHONG\nKHONG\n', 'Trục được xét có vận tốc bằng 0.'),
            hidden('1\nX 1 -100\n', 'PHAI\n', 25),
            hidden('1\nY -100 1\n', 'DUOI\n', 25),
            hidden('3\nX -1 -1\nY -1 -1\nX 0 0\n', 'TRAI\nTREN\nKHONG\n', 25),
            hidden('2\nY 0 0\nX 999 999\n', 'KHONG\nPHAI\n', 25),
          ],
        }),
      ],
    },

    {
      order: 14,
      slug: 'pg-b14-diem-so-mang-hud-am-thanh',
      title: 'Điểm số, mạng sống, HUD & âm thanh',
      summary:
        'Biến một demo kỹ thuật thành một trò chơi thật: có điểm để phấn đấu, có mạng để mất, ' +
        'có giao diện để theo dõi và có âm thanh để phản hồi.',
      objectives: [
        'Hiển thị chữ lên màn hình bằng `pygame.font`',
        'Thiết kế HUD gọn gàng: điểm, mạng, thanh máu',
        'Phát hiệu ứng âm thanh và nhạc nền',
        'Lưu và đọc điểm cao nhất bằng JSON',
      ],
      difficulty: 3,
      status: 'REQUIRED',
      teacherNotes:
        'Phần lưu điểm cao dùng lại JSON đã học ở buổi 29 khoá Cơ Bản. Nhắc học sinh liên hệ.',
      blocks: [
        theory('Hiển thị chữ và HUD', [
          '```python',
          '# Tao font MOT LAN, ngoai game loop',
          'phong_chu = pygame.font.SysFont("arial", 28, bold=True)',
          '',
          '# Trong game loop',
          'chu = phong_chu.render(f"Diem: {diem}", True, (255, 255, 255))',
          'man_hinh.blit(chu, (20, 20))',
          '```',
          '',
          'Tham số `True` là **khử răng cưa** — chữ mượt hơn nhiều, hầu như luôn nên bật.',
          '',
          '**Thanh máu** chỉ là hai hình chữ nhật lồng nhau:',
          '',
          '```python',
          'ty_le = mau_hien_tai / mau_toi_da',
          'pygame.draw.rect(mh, (60, 60, 60), (20, 60, 200, 22))              # nen',
          'pygame.draw.rect(mh, (46, 204, 113), (20, 60, int(200 * ty_le), 22))  # mau',
          'pygame.draw.rect(mh, (255, 255, 255), (20, 60, 200, 22), 2)        # vien',
          '```',
          '',
          '**Nguyên tắc thiết kế HUD cho game của em:**',
          '',
          '- Đặt ở góc màn hình, không che vùng chơi',
          '- Chỉ hiện thông tin người chơi thật sự cần',
          '- Chữ đủ lớn để đọc lướt qua là thấy',
          '- Dùng màu nhất quán: xanh lá là máu, vàng là điểm',
        ], [
          'Tạo font MỘT LẦN ngoài game loop',
          '`render(chu, True, mau)` — True để khử răng cưa',
          'Thanh máu = hình nền + hình máu + viền',
          'HUD đặt ở góc, không che vùng chơi',
        ]),
        theory('Âm thanh', [
          '```python',
          'pygame.mixer.init()',
          '',
          '# Hieu ung ngan (.wav hoac .ogg)',
          'tieng_ban = pygame.mixer.Sound("ban.wav")',
          'tieng_ban.set_volume(0.4)',
          'tieng_ban.play()',
          '',
          '# Nhac nen (phat lien tuc)',
          'pygame.mixer.music.load("nhac_nen.ogg")',
          'pygame.mixer.music.set_volume(0.3)',
          'pygame.mixer.music.play(-1)      # -1 = lap vo han',
          '```',
          '',
          '| Loại | Dùng cho | Định dạng |',
          '|---|---|---|',
          '| `Sound` | Hiệu ứng ngắn: bắn, nổ, ăn xu | `.wav`, `.ogg` |',
          '| `music` | Nhạc nền dài | `.ogg`, `.mp3` |',
          '',
          '⚠️ **Hai lưu ý quan trọng:**',
          '',
          '1. Luôn giảm âm lượng xuống khoảng `0.3`–`0.5`. Âm thanh game mặc định thường rất to.',
          '2. Bọc phần tải âm thanh trong `try`/`except` — thiếu tệp âm thanh không nên làm game chết.',
          '',
          '```python',
          'try:',
          '    tieng_ban = pygame.mixer.Sound("ban.wav")',
          '    co_am_thanh = True',
          'except (pygame.error, FileNotFoundError):',
          '    co_am_thanh = False',
          '```',
        ], [
          '`Sound` cho hiệu ứng ngắn, `mixer.music` cho nhạc nền',
          '`play(-1)` để lặp vô hạn',
          'Luôn giảm âm lượng và bọc trong try/except',
        ]),
        example('Trò chơi hoàn chỉnh có HUD và điểm cao', 'Ghép mọi thứ của Module 3 lại.', [
          'import pygame',
          'import random',
          'import json',
          '',
          'pygame.init()',
          'RONG, CAO = 800, 600',
          'man_hinh = pygame.display.set_mode((RONG, CAO))',
          'pygame.display.set_caption("Hung xu")',
          'dong_ho = pygame.time.Clock()',
          '',
          'font_lon = pygame.font.SysFont("arial", 32, bold=True)',
          'font_nho = pygame.font.SysFont("arial", 20)',
          '',
          '',
          'def doc_diem_cao():',
          '    try:',
          '        with open("diem_cao.json", "r", encoding="utf-8") as f:',
          '            return json.load(f).get("diem_cao", 0)',
          '    except (FileNotFoundError, json.JSONDecodeError):',
          '        return 0',
          '',
          '',
          'def ghi_diem_cao(diem):',
          '    with open("diem_cao.json", "w", encoding="utf-8") as f:',
          '        json.dump({"diem_cao": diem}, f)',
          '',
          '',
          'gio = pygame.Rect(0, 0, 90, 20)',
          'gio.center = (RONG // 2, CAO - 40)',
          'xu = []',
          'for i in range(6):',
          '    xu.append([random.randint(20, RONG - 20), random.randint(-600, 0),',
          '               random.randint(3, 7)])',
          '',
          'diem = 0',
          'mang = 3',
          'diem_cao = doc_diem_cao()',
          '',
          'dang_chay = True',
          'while dang_chay:',
          '    for su_kien in pygame.event.get():',
          '        if su_kien.type == pygame.QUIT:',
          '            dang_chay = False',
          '',
          '    gio.centerx = pygame.mouse.get_pos()[0]',
          '    gio.clamp_ip(man_hinh.get_rect())',
          '',
          '    for v in xu:',
          '        v[1] += v[2]',
          '        khung_xu = pygame.Rect(v[0] - 10, v[1] - 10, 20, 20)',
          '',
          '        if khung_xu.colliderect(gio):',
          '            diem += 10',
          '            v[0] = random.randint(20, RONG - 20)',
          '            v[1] = random.randint(-300, -20)',
          '        elif v[1] > CAO:',
          '            mang -= 1',
          '            v[0] = random.randint(20, RONG - 20)',
          '            v[1] = random.randint(-300, -20)',
          '',
          '    if mang <= 0:',
          '        if diem > diem_cao:',
          '            diem_cao = diem',
          '            ghi_diem_cao(diem_cao)',
          '        diem, mang = 0, 3',
          '',
          '    # ===== VE =====',
          '    man_hinh.fill((25, 25, 45))',
          '',
          '    for v in xu:',
          '        pygame.draw.circle(man_hinh, (241, 196, 15), (v[0], v[1]), 10)',
          '    pygame.draw.rect(man_hinh, (52, 152, 219), gio, 0, border_radius=10)',
          '',
          '    # ===== HUD =====',
          '    man_hinh.blit(font_lon.render(f"{diem}", True, (241, 196, 15)), (20, 15))',
          '    man_hinh.blit(font_nho.render(f"Ky luc: {diem_cao}", True, (150, 150, 180)), (20, 55))',
          '',
          '    for i in range(mang):',
          '        pygame.draw.circle(man_hinh, (231, 76, 60), (RONG - 30 - i * 30, 30), 11)',
          '',
          '    pygame.display.flip()',
          '    dong_ho.tick(60)',
          '',
          'pygame.quit()',
        ], {
          output: 'Trò chơi hứng xu hoàn chỉnh: điểm ở góc trái, kỷ lục bên dưới, ba mạng hình tim ở góc phải.',
          notes: [
            'Kỷ lục được lưu ra JSON nên vẫn còn sau khi tắt game — đúng kỹ thuật buổi 29 khoá Cơ Bản.',
            '`json.JSONDecodeError` được bắt riêng phòng khi tệp bị hỏng.',
            'Mạng hiển thị bằng hình tròn đỏ thay vì con số — trực quan hơn nhiều.',
          ],
        }),
        playground('Sân chơi: HUD của em', [
          'Thiết kế lại HUD theo ý em. Thử thêm:',
          '',
          '- Thanh máu có màu đổi theo mức: xanh → vàng → đỏ',
          '- Bộ đếm thời gian còn lại',
          '- Chữ "Diem +10" bay lên rồi mờ dần khi ăn xu',
        ], [
          'import pygame',
          '',
          'pygame.init()',
          'man_hinh = pygame.display.set_mode((800, 600))',
          'dong_ho = pygame.time.Clock()',
          'font = pygame.font.SysFont("arial", 24, bold=True)',
          '',
          'mau = 100',
          'mau_toi_da = 100',
          '',
          'dang_chay = True',
          'while dang_chay:',
          '    for su_kien in pygame.event.get():',
          '        if su_kien.type == pygame.QUIT:',
          '            dang_chay = False',
          '        elif su_kien.type == pygame.KEYDOWN:',
          '            if su_kien.key == pygame.K_DOWN:',
          '                mau = max(0, mau - 10)',
          '            if su_kien.key == pygame.K_UP:',
          '                mau = min(mau_toi_da, mau + 10)',
          '',
          '    man_hinh.fill((25, 25, 45))',
          '',
          '    ty_le = mau / mau_toi_da',
          '    # Doi mau thanh mau theo ty_le o day',
          '    pygame.draw.rect(man_hinh, (60, 60, 60), (20, 20, 240, 26))',
          '    pygame.draw.rect(man_hinh, (46, 204, 113), (20, 20, int(240 * ty_le), 26))',
          '    pygame.draw.rect(man_hinh, (255, 255, 255), (20, 20, 240, 26), 2)',
          '',
          '    man_hinh.blit(font.render("Len/Xuong de doi mau", True, (200, 200, 220)), (20, 60))',
          '    pygame.display.flip()',
          '    dong_ho.tick(60)',
          '',
          'pygame.quit()',
        ], 'HUD hiển thị đúng và thanh máu đổi màu theo mức còn lại.'),
        challenge({
          slug: 'p-pg-b14-tinh-diem-combo',
          title: 'Tính điểm có combo',
          statement: [
            'Người chơi ăn một chuỗi vật phẩm. Mỗi vật phẩm có điểm cơ bản `p`.',
            '',
            'Hệ số combo bắt đầu từ 1. Mỗi lần ăn **liên tiếp** (không bỏ lỡ), hệ số tăng thêm 1, ' +
              'nhưng **tối đa là 5**. Bỏ lỡ một vật phẩm thì hệ số quay về 1.',
            '',
            'Điểm nhận được mỗi lần ăn = `p × hệ số hiện tại` (tính **sau** khi đã tăng hệ số).',
            '',
            'Dòng đầu: hai số nguyên `N` và `p`. Dòng hai: `N` ký tự `A` (ăn được) hoặc `M` (bỏ lỡ), ' +
              'cách nhau bằng dấu cách.',
            '',
            'In ra **một dòng** là tổng điểm.',
            '',
            'Ví dụ với `p = 10` và chuỗi `A A A`: hệ số lần lượt là 2, 3, 4 → điểm 20 + 30 + 40 = 90.',
          ].join('\n'),
          hints: [
            'Giữ một biến `he_so`, bắt đầu bằng 1.',
            'Gặp `A`: tăng hệ số (không quá 5), rồi cộng `p × he_so` vào tổng.',
            'Gặp `M`: đặt lại `he_so = 1`, không cộng điểm.',
          ],
          starterCode: [
            'n, p = map(int, input().split())',
            'chuoi = input().split()',
            '',
            'tong = 0',
            'he_so = 1',
            '',
            '# Duyệt từng ký tự',
          ].join('\n'),
          solutionCode: [
            'n, p = map(int, input().split())',
            'chuoi = input().split()',
            '',
            'tong = 0',
            'he_so = 1',
            '',
            'for c in chuoi:',
            '    if c == "A":',
            '        if he_so < 5:',
            '            he_so += 1',
            '        tong += p * he_so',
            '    else:',
            '        he_so = 1',
            '',
            'print(tong)',
          ].join('\n'),
          tier: 'THU_THACH',
          judgeMode: 'IO_MATCH',
          tests: [
            sample('3 10\nA A A\n', '90\n', 'Hệ số 2, 3, 4 → 20 + 30 + 40 = 90.'),
            sample('3 10\nA M A\n', '40\n', 'Bỏ lỡ làm hệ số về 1, nên lần ăn cuối chỉ được hệ số 2.'),
            hidden('1 5\nM\n', '0\n', 20),
            hidden('6 10\nA A A A A A\n', '240\n', 20),
            hidden('4 100\nM M M M\n', '0\n', 20),
            hidden('5 1\nA A M A A\n', '10\n', 20),
            hidden('8 10\nA A A A A A A A\n', '440\n', 20),
          ],
        }),
      ],
    },

    {
      order: 15,
      slug: 'pg-b15-menu-quan-ly-trang-thai',
      title: 'Menu & quản lý trạng thái game',
      summary:
        'Một game thật không chỉ có màn chơi. Buổi này em xây menu chính, màn tạm dừng và ' +
        'màn kết thúc, nối với nhau bằng máy trạng thái.',
      objectives: [
        'Hiểu khái niệm trạng thái game (game state)',
        'Chuyển đổi giữa MENU, CHOI, TAM_DUNG và KET_THUC',
        'Xây menu có nút bấm điều khiển bằng chuột',
        'Tạm dừng và tiếp tục game đúng cách',
      ],
      difficulty: 4,
      status: 'REQUIRED',
      teacherNotes:
        'GHI CHÚ Module 3: bài Menu được ĐẢO VỊ TRÍ về đây, ngay trước buổi dự án, theo yêu cầu ' +
        'trong kế hoạch bài giảng. Lý do: học sinh cần có sẵn logic game rồi mới thấy menu để làm gì.',
      blocks: [
        theory('Máy trạng thái', [
          'Cho đến giờ, game của em chỉ có một trạng thái duy nhất: đang chơi. Game thật có nhiều hơn:',
          '',
          '```',
          '   ┌─────────┐  Bam Choi   ┌──────────┐',
          '   │  MENU   │────────────►│   CHOI   │',
          '   └─────────┘             └──┬────┬──┘',
          '        ▲                     │    │',
          '        │              ESC    │    │  Het mang',
          '        │                     ▼    ▼',
          '        │            ┌───────────┐ ┌────────────┐',
          '        └────────────┤ TAM_DUNG  │ │ KET_THUC   │',
          '                     └───────────┘ └─────┬──────┘',
          '                                         │',
          '        └────────────────────────────────┘',
          '```',
          '',
          'Cách cài đặt đơn giản nhất là **một biến chuỗi**:',
          '',
          '```python',
          'trang_thai = "MENU"',
          '',
          'while dang_chay:',
          '    if trang_thai == "MENU":',
          '        cap_nhat_menu()',
          '        ve_menu()',
          '    elif trang_thai == "CHOI":',
          '        cap_nhat_game()',
          '        ve_game()',
          '    elif trang_thai == "TAM_DUNG":',
          '        ve_game()          # ve nen game dang dung',
          '        ve_lop_phu_tam_dung()',
          '    elif trang_thai == "KET_THUC":',
          '        ve_man_ket_thuc()',
          '```',
          '',
          '💡 Điểm hay của TAM_DUNG: vẫn **vẽ** game nhưng không **cập nhật** nó. Nhờ vậy người chơi ' +
            'thấy màn hình game đứng yên phía sau lớp phủ mờ.',
        ], [
          'Một biến `trang_thai` là đủ để quản lý toàn bộ luồng game',
          'Mỗi trạng thái có phần cập nhật và phần vẽ riêng',
          'TAM_DUNG: vẽ nhưng không cập nhật',
        ]),
        theory('Nút bấm dùng lại được', [
          'Ở buổi 7 em đã làm một nút. Giờ ta gói nó thành hàm để dùng nhiều lần:',
          '',
          '```python',
          'def ve_nut(mh, khung, nhan, font, chuot):',
          '    dang_di_qua = khung.collidepoint(chuot)',
          '    mau = (93, 173, 226) if dang_di_qua else (52, 152, 219)',
          '',
          '    pygame.draw.rect(mh, mau, khung, 0, border_radius=12)',
          '    pygame.draw.rect(mh, (255, 255, 255), khung, 2, border_radius=12)',
          '',
          '    chu = font.render(nhan, True, (255, 255, 255))',
          '    mh.blit(chu, chu.get_rect(center=khung.center))',
          '',
          '    return dang_di_qua',
          '```',
          '',
          'Hàm trả về `True` khi chuột đang ở trên nút, nên lúc xử lý sự kiện chỉ cần:',
          '',
          '```python',
          'if su_kien.type == pygame.MOUSEBUTTONDOWN:',
          '    if nut_choi.collidepoint(su_kien.pos):',
          '        trang_thai = "CHOI"',
          '```',
          '',
          '**Lớp phủ mờ** cho màn tạm dừng — một mẹo nhỏ nhưng trông rất chuyên nghiệp:',
          '',
          '```python',
          'lop_phu = pygame.Surface((RONG, CAO), pygame.SRCALPHA)',
          'lop_phu.fill((0, 0, 0, 160))     # so thu tu la do trong suot',
          'man_hinh.blit(lop_phu, (0, 0))',
          '```',
        ], [
          'Gói nút bấm thành hàm để dùng lại',
          'Surface với SRCALPHA và màu 4 số cho lớp phủ mờ',
          'Số thứ tư của màu là độ đục: 0 trong suốt, 255 đặc',
        ]),
        example('Game có menu đầy đủ', 'Bộ khung này dùng được cho mọi dự án về sau.', [
          'import pygame',
          '',
          'pygame.init()',
          'RONG, CAO = 800, 600',
          'man_hinh = pygame.display.set_mode((RONG, CAO))',
          'pygame.display.set_caption("Game co Menu")',
          'dong_ho = pygame.time.Clock()',
          '',
          'font_tieu_de = pygame.font.SysFont("arial", 56, bold=True)',
          'font_nut = pygame.font.SysFont("arial", 26, bold=True)',
          'font_nho = pygame.font.SysFont("arial", 18)',
          '',
          'nut_choi = pygame.Rect(0, 0, 240, 64)',
          'nut_choi.center = (RONG // 2, 320)',
          'nut_thoat = pygame.Rect(0, 0, 240, 64)',
          'nut_thoat.center = (RONG // 2, 400)',
          '',
          'trang_thai = "MENU"',
          'nv = pygame.Rect(0, 0, 40, 40)',
          'nv.center = (RONG // 2, CAO // 2)',
          'diem = 0',
          '',
          '',
          'def ve_nut(khung, nhan, chuot):',
          '    di_qua = khung.collidepoint(chuot)',
          '    mau = (93, 173, 226) if di_qua else (52, 152, 219)',
          '    pygame.draw.rect(man_hinh, mau, khung, 0, border_radius=12)',
          '    pygame.draw.rect(man_hinh, (255, 255, 255), khung, 2, border_radius=12)',
          '    chu = font_nut.render(nhan, True, (255, 255, 255))',
          '    man_hinh.blit(chu, chu.get_rect(center=khung.center))',
          '',
          '',
          'def ve_giua(font, text, y, mau=(255, 255, 255)):',
          '    chu = font.render(text, True, mau)',
          '    man_hinh.blit(chu, chu.get_rect(center=(RONG // 2, y)))',
          '',
          '',
          'dang_chay = True',
          'while dang_chay:',
          '    chuot = pygame.mouse.get_pos()',
          '',
          '    for su_kien in pygame.event.get():',
          '        if su_kien.type == pygame.QUIT:',
          '            dang_chay = False',
          '',
          '        elif su_kien.type == pygame.KEYDOWN:',
          '            if su_kien.key == pygame.K_ESCAPE:',
          '                if trang_thai == "CHOI":',
          '                    trang_thai = "TAM_DUNG"',
          '                elif trang_thai == "TAM_DUNG":',
          '                    trang_thai = "CHOI"',
          '            elif su_kien.key == pygame.K_m and trang_thai in ("TAM_DUNG", "KET_THUC"):',
          '                trang_thai = "MENU"',
          '',
          '        elif su_kien.type == pygame.MOUSEBUTTONDOWN and trang_thai == "MENU":',
          '            if nut_choi.collidepoint(su_kien.pos):',
          '                trang_thai = "CHOI"',
          '                diem = 0',
          '                nv.center = (RONG // 2, CAO // 2)',
          '            elif nut_thoat.collidepoint(su_kien.pos):',
          '                dang_chay = False',
          '',
          '    # ===== CAP NHAT =====',
          '    if trang_thai == "CHOI":',
          '        phim = pygame.key.get_pressed()',
          '        if phim[pygame.K_LEFT]:',
          '            nv.x -= 6',
          '        if phim[pygame.K_RIGHT]:',
          '            nv.x += 6',
          '        if phim[pygame.K_UP]:',
          '            nv.y -= 6',
          '        if phim[pygame.K_DOWN]:',
          '            nv.y += 6',
          '        nv.clamp_ip(man_hinh.get_rect())',
          '        diem += 1',
          '',
          '    # ===== VE =====',
          '    man_hinh.fill((25, 25, 45))',
          '',
          '    if trang_thai == "MENU":',
          '        ve_giua(font_tieu_de, "GAME CUA EM", 200, (241, 196, 15))',
          '        ve_nut(nut_choi, "CHOI", chuot)',
          '        ve_nut(nut_thoat, "THOAT", chuot)',
          '',
          '    else:',
          '        pygame.draw.rect(man_hinh, (46, 204, 113), nv, 0, border_radius=6)',
          '        man_hinh.blit(font_nut.render(f"Diem: {diem}", True, (255, 255, 255)), (20, 20))',
          '        man_hinh.blit(font_nho.render("ESC de tam dung", True, (150, 150, 180)), (20, 56))',
          '',
          '        if trang_thai == "TAM_DUNG":',
          '            lop_phu = pygame.Surface((RONG, CAO), pygame.SRCALPHA)',
          '            lop_phu.fill((0, 0, 0, 170))',
          '            man_hinh.blit(lop_phu, (0, 0))',
          '            ve_giua(font_tieu_de, "TAM DUNG", 260)',
          '            ve_giua(font_nho, "ESC de tiep tuc  ·  M de ve Menu", 330, (200, 200, 220))',
          '',
          '    pygame.display.flip()',
          '    dong_ho.tick(60)',
          '',
          'pygame.quit()',
        ], {
          output:
            'Menu có hai nút sáng lên khi rê chuột; vào game điều khiển ô vuông; ESC tạm dừng với lớp phủ mờ.',
          notes: [
            'Ở trạng thái TAM_DUNG, phần cập nhật bị bỏ qua nhưng phần vẽ game vẫn chạy — nên nhìn thấy game đứng yên phía sau.',
            'Phím ESC làm hai việc ngược nhau tuỳ trạng thái hiện tại — đó chính là sức mạnh của máy trạng thái.',
            'Bộ khung menu này em dùng lại được cho mọi dự án về sau.',
          ],
        }),
        playground('Sân chơi: thêm màn kết thúc', [
          'Bổ sung trạng thái `KET_THUC` vào bộ khung ở trên:',
          '',
          '1. Khi điểm vượt một mốc nào đó (ví dụ 300), chuyển sang `KET_THUC`',
          '2. Màn kết thúc hiện điểm cuối cùng và dòng chữ "Bam M de ve Menu"',
          '3. Thêm nút "CHOI LAI" bấm được bằng chuột',
        ], [
          'import pygame',
          '',
          'pygame.init()',
          'RONG, CAO = 800, 600',
          'man_hinh = pygame.display.set_mode((RONG, CAO))',
          'dong_ho = pygame.time.Clock()',
          'font = pygame.font.SysFont("arial", 36, bold=True)',
          '',
          'trang_thai = "CHOI"',
          'diem = 0',
          '',
          'dang_chay = True',
          'while dang_chay:',
          '    for su_kien in pygame.event.get():',
          '        if su_kien.type == pygame.QUIT:',
          '            dang_chay = False',
          '        elif su_kien.type == pygame.KEYDOWN:',
          '            if su_kien.key == pygame.K_r:',
          '                trang_thai, diem = "CHOI", 0',
          '',
          '    if trang_thai == "CHOI":',
          '        diem += 1',
          '        if diem > 300:',
          '            trang_thai = "KET_THUC"',
          '',
          '    man_hinh.fill((25, 25, 45))',
          '    if trang_thai == "CHOI":',
          '        chu = font.render(f"Diem: {diem}", True, (255, 255, 255))',
          '    else:',
          '        chu = font.render(f"Ket thuc! Diem: {diem}  (R de choi lai)", True, (241, 196, 15))',
          '    man_hinh.blit(chu, chu.get_rect(center=(RONG // 2, CAO // 2)))',
          '',
          '    pygame.display.flip()',
          '    dong_ho.tick(60)',
          '',
          'pygame.quit()',
        ], 'Game chuyển đúng qua bốn trạng thái và quay lại menu được.'),
        quizBlock({
          slug: 'q-pg-b15-trang-thai-game',
          title: 'Kiểm tra nhanh: trạng thái game',
          questions: [
            {
              type: 'MULTIPLE_CHOICE',
              prompt: 'Ở trạng thái TAM_DUNG, ta nên làm gì với phần vẽ và phần cập nhật?',
              explanation:
                'Vẫn vẽ để người chơi thấy game đứng yên phía sau, nhưng không cập nhật để game thật sự dừng.',
              choices: [
                { text: 'Vẫn vẽ nhưng không cập nhật', isCorrect: true },
                { text: 'Không vẽ cũng không cập nhật' },
                { text: 'Vẫn cập nhật nhưng không vẽ' },
                { text: 'Vẫn làm cả hai như bình thường' },
              ],
            },
            {
              type: 'MULTIPLE_CHOICE',
              prompt: 'Màu `(0, 0, 0, 170)` khác gì với `(0, 0, 0)`?',
              explanation: 'Số thứ tư là độ đục. 170 nghĩa là đen mờ, cho thấy được phần phía sau.',
              choices: [
                { text: 'Có thêm độ đục — đen mờ chứ không đen đặc', isCorrect: true },
                { text: 'Không khác gì, số thừa bị bỏ qua' },
                { text: 'Số thứ tư là độ sáng' },
                { text: 'Số thứ tư là độ dày viền' },
              ],
            },
            {
              type: 'TRUE_FALSE',
              prompt: 'Cần một biến riêng cho mỗi trạng thái game, ví dụ `dang_o_menu`, `dang_choi`, `dang_tam_dung`.',
              explanation:
                'Sai. Một biến `trang_thai` duy nhất là đủ và an toàn hơn — nhiều biến cờ dễ rơi vào ' +
                'trạng thái mâu thuẫn, ví dụ vừa ở menu vừa đang chơi.',
              choices: [{ text: 'Đúng' }, { text: 'Sai', isCorrect: true }],
            },
          ],
        }),
      ],
    },

    {
      order: 16,
      slug: 'pg-b16-du-an-pong-hoan-chinh',
      title: 'Dự án Module 3: Pong hoàn chỉnh',
      summary:
        'Ghép toàn bộ Module 3 thành một trò chơi Pong đầy đủ: hai paddle, bóng nảy có kỹ năng, ' +
        'điểm số, menu và màn kết thúc.',
      objectives: [
        'Xây dựng một trò chơi hoàn chỉnh từ đầu đến cuối',
        'Áp dụng chuyển động, vật lý, va chạm và trạng thái vào cùng một sản phẩm',
        'Cân bằng độ khó để trò chơi vừa sức nhưng vẫn thú vị',
      ],
      difficulty: 4,
      estimatedMinutes: 120,
      status: 'REQUIRED',
      teacherNotes:
        'Dự án kết Module 3. Đây là trò chơi hoàn chỉnh đầu tiên của học sinh — dành thời gian ' +
        'để các em chơi thử game của nhau.',
      blocks: [
        theory('Kế hoạch xây dựng Pong', [
          'Đừng viết một mạch. Hãy làm theo sáu bước, **chạy thử sau mỗi bước**:',
          '',
          '| Bước | Việc làm | Kiểm tra |',
          '|---|---|---|',
          '| 1 | Cửa sổ + game loop | Cửa sổ mở, đóng được |',
          '| 2 | Hai paddle điều khiển được | W/S và mũi tên di chuyển được |',
          '| 3 | Bóng chuyển động và nảy tường | Bóng nảy trên/dưới, không thoát ra |',
          '| 4 | Va chạm bóng–paddle | Bóng nảy lại khi chạm paddle |',
          '| 5 | Điểm số + reset bóng | Bóng ra ngoài thì bên kia được điểm |',
          '| 6 | Menu + màn kết thúc | Chuyển trạng thái đúng |',
          '',
          '**Ba mẹo làm Pong hay hơn:**',
          '',
          '1. **Nảy theo điểm chạm** (buổi 13) — chạm mép paddle thì bóng đi xiên hơn. ' +
            'Đây là thứ biến Pong từ trò may rủi thành trò có kỹ năng.',
          '2. **Tăng tốc dần** — mỗi lần chạm paddle, nhân tốc độ bóng với 1.03. Ván đấu càng về sau càng căng.',
          '3. **Giới hạn tốc độ tối đa** — nếu không, bóng sẽ nhanh tới mức xuyên qua paddle.',
          '',
          '⚠️ Lỗi kinh điển: bóng đi quá nhanh sẽ **nhảy qua** paddle giữa hai khung hình mà không ' +
            'bị phát hiện va chạm. Cách xử lý đơn giản là giới hạn tốc độ bóng dưới bề rộng paddle.',
        ], [
          'Làm sáu bước, chạy thử sau mỗi bước',
          'Nảy theo điểm chạm là thứ làm Pong thú vị',
          'Giới hạn tốc độ bóng để nó không xuyên qua paddle',
        ]),
        example('Pong hoàn chỉnh', 'Đọc kỹ, chạy thử, rồi sửa thành phiên bản của riêng em.', [
          'import pygame',
          '',
          'pygame.init()',
          'RONG, CAO = 800, 600',
          'man_hinh = pygame.display.set_mode((RONG, CAO))',
          'pygame.display.set_caption("PONG")',
          'dong_ho = pygame.time.Clock()',
          '',
          'font_lon = pygame.font.SysFont("consolas", 64, bold=True)',
          'font_nho = pygame.font.SysFont("arial", 20)',
          '',
          'TRANG = (240, 240, 245)',
          'NEN = (18, 18, 32)',
          'DIEM_THANG = 5',
          'TOC_DO_TOI_DA = 14',
          '',
          'trai = pygame.Rect(30, CAO // 2 - 55, 14, 110)',
          'phai = pygame.Rect(RONG - 44, CAO // 2 - 55, 14, 110)',
          'bong = pygame.Rect(0, 0, 16, 16)',
          '',
          'diem_trai = diem_phai = 0',
          'vx = vy = 0.0',
          'trang_thai = "MENU"',
          '',
          '',
          'def reset_bong(huong):',
          '    global vx, vy',
          '    bong.center = (RONG // 2, CAO // 2)',
          '    vx = 6.0 * huong',
          '    vy = 4.0',
          '',
          '',
          'def ve_giua(font, text, y, mau=TRANG):',
          '    chu = font.render(text, True, mau)',
          '    man_hinh.blit(chu, chu.get_rect(center=(RONG // 2, y)))',
          '',
          '',
          'reset_bong(1)',
          '',
          'dang_chay = True',
          'while dang_chay:',
          '    for su_kien in pygame.event.get():',
          '        if su_kien.type == pygame.QUIT:',
          '            dang_chay = False',
          '        elif su_kien.type == pygame.KEYDOWN:',
          '            if su_kien.key == pygame.K_SPACE:',
          '                if trang_thai in ("MENU", "KET_THUC"):',
          '                    diem_trai = diem_phai = 0',
          '                    reset_bong(1)',
          '                    trang_thai = "CHOI"',
          '            elif su_kien.key == pygame.K_ESCAPE:',
          '                if trang_thai == "CHOI":',
          '                    trang_thai = "TAM_DUNG"',
          '                elif trang_thai == "TAM_DUNG":',
          '                    trang_thai = "CHOI"',
          '',
          '    if trang_thai == "CHOI":',
          '        phim = pygame.key.get_pressed()',
          '        if phim[pygame.K_w]:',
          '            trai.y -= 8',
          '        if phim[pygame.K_s]:',
          '            trai.y += 8',
          '        if phim[pygame.K_UP]:',
          '            phai.y -= 8',
          '        if phim[pygame.K_DOWN]:',
          '            phai.y += 8',
          '        trai.clamp_ip(man_hinh.get_rect())',
          '        phai.clamp_ip(man_hinh.get_rect())',
          '',
          '        bong.x += int(vx)',
          '        bong.y += int(vy)',
          '',
          '        if bong.top <= 0 or bong.bottom >= CAO:',
          '            vy = -vy',
          '            bong.clamp_ip(man_hinh.get_rect())',
          '',
          '        for paddle, huong in ((trai, 1), (phai, -1)):',
          '            if bong.colliderect(paddle) and vx * huong < 0:',
          '                lech = (bong.centery - paddle.centery) / (paddle.height / 2)',
          '                vx = abs(vx) * huong * 1.05',
          '                vy = lech * 7',
          '                if abs(vx) > TOC_DO_TOI_DA:',
          '                    vx = TOC_DO_TOI_DA * huong',
          '                bong.centerx = (paddle.right + 9) if huong > 0 else (paddle.left - 9)',
          '',
          '        if bong.right < 0:',
          '            diem_phai += 1',
          '            reset_bong(1)',
          '        elif bong.left > RONG:',
          '            diem_trai += 1',
          '            reset_bong(-1)',
          '',
          '        if diem_trai >= DIEM_THANG or diem_phai >= DIEM_THANG:',
          '            trang_thai = "KET_THUC"',
          '',
          '    # ===== VE =====',
          '    man_hinh.fill(NEN)',
          '',
          '    for y in range(0, CAO, 34):',
          '        pygame.draw.rect(man_hinh, (50, 50, 75), (RONG // 2 - 2, y, 4, 18))',
          '    pygame.draw.rect(man_hinh, TRANG, trai, 0, border_radius=7)',
          '    pygame.draw.rect(man_hinh, TRANG, phai, 0, border_radius=7)',
          '    pygame.draw.ellipse(man_hinh, (241, 196, 15), bong)',
          '',
          '    man_hinh.blit(font_lon.render(str(diem_trai), True, TRANG), (RONG // 2 - 110, 30))',
          '    man_hinh.blit(font_lon.render(str(diem_phai), True, TRANG), (RONG // 2 + 60, 30))',
          '',
          '    if trang_thai == "MENU":',
          '        ve_giua(font_lon, "PONG", 230, (241, 196, 15))',
          '        ve_giua(font_nho, "W/S  va  Mui ten len/xuong", 320)',
          '        ve_giua(font_nho, "CACH de bat dau", 360, (150, 200, 255))',
          '    elif trang_thai == "TAM_DUNG":',
          '        ve_giua(font_lon, "TAM DUNG", 280)',
          '        ve_giua(font_nho, "ESC de tiep tuc", 340, (150, 150, 180))',
          '    elif trang_thai == "KET_THUC":',
          '        ai_thang = "BEN TRAI" if diem_trai > diem_phai else "BEN PHAI"',
          '        ve_giua(font_lon, f"{ai_thang} THANG!", 260, (46, 204, 113))',
          '        ve_giua(font_nho, "CACH de choi lai", 330, (150, 200, 255))',
          '',
          '    pygame.display.flip()',
          '    dong_ho.tick(60)',
          '',
          'pygame.quit()',
        ], {
          output:
            'Pong hai người chơi hoàn chỉnh: lưới giữa sân, điểm số lớn, bóng tăng tốc dần, có menu và màn thắng.',
          notes: [
            'Vòng `for paddle, huong in ((trai, 1), (phai, -1))` xử lý cả hai paddle bằng cùng một đoạn code.',
            'Điều kiện `vx * huong < 0` bảo đảm chỉ nảy khi bóng đang bay **về phía** paddle, ' +
              'tránh lỗi bóng dính vào paddle.',
            'Dòng đặt lại `bong.centerx` sau va chạm đẩy bóng ra khỏi paddle ngay lập tức — ' +
              'không có nó bóng sẽ rung lắc.',
            '`vx = abs(vx) * huong * 1.05` vừa đảo hướng vừa tăng tốc 5% mỗi lần chạm.',
          ],
        }),
        playground('Sân chơi: thêm chế độ một người chơi', [
          'Thêm AI đơn giản cho paddle bên phải để chơi một mình được.',
          '',
          'AI cơ bản nhất: paddle di chuyển về phía bóng, nhưng **chậm hơn** người chơi để còn thắng được.',
          '',
          '```python',
          'if phai.centery < bong.centery:',
          '    phai.y += 5      # cham hon 8 cua nguoi choi',
          'elif phai.centery > bong.centery:',
          '    phai.y -= 5',
          '```',
          '',
          'Thử đổi tốc độ AI giữa 3, 5, 7 để tìm mức khó vừa phải.',
        ], [
          '# Chep code Pong o tren vao day,',
          '# roi thay phan dieu khien paddle phai bang AI.',
          '',
          '# Goi y AI:',
          '# if phai.centery < bong.centery:',
          '#     phai.y += TOC_DO_AI',
          '# elif phai.centery > bong.centery:',
          '#     phai.y -= TOC_DO_AI',
          '',
        ], 'Chơi được một mình với AI có độ khó vừa phải.'),
        challenge({
          slug: 'p-pg-b16-ai-paddle',
          title: 'AI paddle đuổi theo bóng',
          statement: [
            'Paddle AI có tâm ở `p` và tốc độ tối đa `s` mỗi khung hình. Bóng có tâm ở `b`.',
            '',
            'Mỗi khung hình, AI di chuyển về phía bóng nhưng **không quá `s` điểm ảnh**:',
            '',
            '- Nếu `p < b`: `p` tăng, nhưng không vượt quá `b`',
            '- Nếu `p > b`: `p` giảm, nhưng không xuống dưới `b`',
            '',
            'Dòng đầu: ba số nguyên `p`, `s`, `N` (số khung hình). ' +
              'Dòng hai: `N` số nguyên là vị trí `b` của bóng ở từng khung hình.',
            '',
            'In ra **một dòng** là vị trí `p` sau `N` khung hình.',
          ].join('\n'),
          hints: [
            'Khoảng cách cần đi là `b - p`.',
            'Nếu khoảng cách đó nhỏ hơn `s`, đi thẳng tới `b` luôn.',
            'Ngược lại chỉ đi `s` điểm ảnh về đúng hướng.',
          ],
          starterCode: [
            'p, s, n = map(int, input().split())',
            'bong = list(map(int, input().split()))',
            '',
            'for b in bong:',
            '    # Di chuyển p về phía b, tối đa s điểm ảnh',
            '    pass',
            '',
            'print(p)',
          ].join('\n'),
          solutionCode: [
            'p, s, n = map(int, input().split())',
            'bong = list(map(int, input().split()))',
            '',
            'for b in bong:',
            '    if p < b:',
            '        p = min(p + s, b)',
            '    elif p > b:',
            '        p = max(p - s, b)',
            '',
            'print(p)',
          ].join('\n'),
          tier: 'THU_THACH',
          judgeMode: 'IO_MATCH',
          tests: [
            sample(
              '300 5 3\n400 400 400\n',
              '315\n',
              'Mỗi khung AI chỉ đi được 5 điểm, sau 3 khung là 315.',
            ),
            sample('300 5 2\n302 302\n', '302\n', 'Khoảng cách 2 nhỏ hơn tốc độ 5 nên tới thẳng nơi.'),
            hidden('100 10 5\n100 100 100 100 100\n', '100\n', 25),
            hidden('500 20 3\n100 100 100\n', '440\n', 25),
            hidden('0 1 10\n5 5 5 5 5 5 5 5 5 5\n', '5\n', 25),
            hidden('250 8 4\n300 200 300 200\n', '250\n', 25),
          ],
        }),
        projectBlock(
          'Nộp dự án Pong',
          [
            'Nộp trò chơi Pong của em kèm mô tả ngắn.',
            '',
            '**Yêu cầu bắt buộc:**',
            '',
            '- Hai paddle điều khiển được (hoặc một paddle và một AI)',
            '- Bóng nảy đúng ở cả bốn cạnh và trên paddle',
            '- Điểm số hiển thị rõ ràng, có điều kiện thắng',
            '- Ít nhất ba trạng thái: MENU, CHOI, KET_THUC',
            '',
            '**Điểm cộng nếu em làm thêm:**',
            '',
            '- Nảy theo điểm chạm trên paddle',
            '- Bóng tăng tốc dần theo ván đấu',
            '- Âm thanh khi chạm paddle và khi ghi điểm',
            '- Hiệu ứng hình ảnh của riêng em',
          ],
          'PONG',
          [
            'Bước 1–2: cửa sổ và hai paddle điều khiển được',
            'Bước 3–4: bóng chuyển động và va chạm đúng',
            'Bước 5: điểm số và điều kiện thắng',
            'Bước 6: menu và màn kết thúc, rồi nộp bài',
          ],
          { minutes: 60 },
        ),
      ],
    },
  ],
};
