/**
 * Pygame — Module 4, phần 1 (Buổi 17–19): Tile map, nhân vật Platformer, camera.
 *
 * Auto-graded exercises stay logic-only (tile index maths, ground snapping,
 * camera clamping) so they run in the PY_BASE sandbox. The game itself is
 * assessed by project upload.
 */
import type { LessonSpec } from '../types.ts';
import { challenge, example, hidden, playground, sample, theory } from '../builders.ts';

export const pygameLessons17to19: LessonSpec[] = [
  {
    order: 17,
    slug: 'pg-b17-tile-map-va-man-choi',
    title: 'Tile map & xây dựng màn chơi Platformer',
    summary:
      'Vẽ màn chơi bằng một lưới ô vuông thay vì đặt tay từng bức tường. Một danh sách chuỗi ' +
      'là đủ để mô tả cả một màn chơi.',
    objectives: [
      'Mô tả màn chơi bằng lưới tile (danh sách các chuỗi)',
      'Chuyển đổi qua lại giữa toạ độ ô và toạ độ điểm ảnh',
      'Sinh danh sách Rect nền từ tile map',
      'Thiết kế một màn chơi của riêng em',
    ],
    difficulty: 4,
    status: 'REQUIRED',
    teacherNotes: 'Mở đầu Module 4. Tile map giúp học sinh thiết kế màn chơi mà không cần đặt tay từng Rect.',
    blocks: [
      theory('Màn chơi là một lưới ô', [
        'Đặt tay 50 bức tường bằng `pygame.Rect(...)` thì rất mệt và không sửa nổi. ' +
          'Cách chuyên nghiệp là mô tả màn chơi bằng **lưới ô vuông**:',
        '',
        '```python',
        'TILE = 40    # moi o vuong 40x40 diem anh',
        '',
        'MAN_CHOI = [',
        '    "........................",',
        '    "........................",',
        '    "......XXXX..............",',
        '    "........................",',
        '    "..XXX...........XXXX....",',
        '    "................._......",',
        '    "XXXXXXXXXXXXXXXXXXXXXXXX",',
        ']',
        '```',
        '',
        '`X` là nền cứng, `.` là khoảng trống, `_` là vật phẩm. Nhìn vào là thấy ngay hình dạng màn chơi.',
        '',
        '**Công thức chuyển đổi — nhớ kỹ hai dòng này:**',
        '',
        '```python',
        '# Tu o -> diem anh',
        'x = cot * TILE',
        'y = hang * TILE',
        '',
        '# Tu diem anh -> o',
        'cot = x // TILE',
        'hang = y // TILE',
        '```',
        '',
        '⚠️ Chú ý thứ tự: `MAN_CHOI[hang][cot]`. **Hàng trước, cột sau** — ngược với `(x, y)` quen thuộc.',
      ], [
        'Màn chơi = danh sách chuỗi, mỗi ký tự là một ô',
        '`x = cot * TILE`, `cot = x // TILE`',
        '`MAN_CHOI[hang][cot]` — hàng trước, cột sau',
      ]),
      example('Sinh nền từ tile map', 'Một vòng lặp lồng nhau biến chuỗi thành danh sách Rect.', [
        'import pygame',
        '',
        'pygame.init()',
        'TILE = 40',
        '',
        'MAN_CHOI = [',
        '    "....................",',
        '    "....................",',
        '    "......XXXX..........",',
        '    "....................",',
        '    "..XXX..........XXXX.",',
        '    "....................",',
        '    ".........XXX........",',
        '    "XXXXXXXXXXXXXXXXXXXX",',
        ']',
        '',
        'RONG = len(MAN_CHOI[0]) * TILE',
        'CAO = len(MAN_CHOI) * TILE',
        'man_hinh = pygame.display.set_mode((RONG, CAO))',
        'pygame.display.set_caption("Tile map")',
        'dong_ho = pygame.time.Clock()',
        '',
        '# Sinh danh sach nen tu tile map',
        'nen = []',
        'for hang, dong in enumerate(MAN_CHOI):',
        '    for cot, ky_tu in enumerate(dong):',
        '        if ky_tu == "X":',
        '            nen.append(pygame.Rect(cot * TILE, hang * TILE, TILE, TILE))',
        '',
        'print(f"Da sinh {len(nen)} o nen")',
        '',
        'dang_chay = True',
        'while dang_chay:',
        '    for su_kien in pygame.event.get():',
        '        if su_kien.type == pygame.QUIT:',
        '            dang_chay = False',
        '',
        '    man_hinh.fill((30, 30, 55))',
        '    for o in nen:',
        '        pygame.draw.rect(man_hinh, (90, 100, 125), o)',
        '        pygame.draw.rect(man_hinh, (130, 145, 175), o, 2)',
        '    pygame.display.flip()',
        '    dong_ho.tick(60)',
        '',
        'pygame.quit()',
      ], {
        output: 'Màn chơi hiện ra đúng như hình vẽ trong danh sách chuỗi, gồm các bệ đứng và một nền dài phía dưới.',
        notes: [
          '`enumerate()` cho cả chỉ số lẫn giá trị — gọn hơn hẳn `range(len(...))`.',
          'Kích thước cửa sổ được tính TỪ tile map, nên đổi màn chơi là cửa sổ tự khớp theo.',
          'Sửa một ký tự trong chuỗi là đổi được cả màn chơi — đó là lý do dùng tile map.',
        ],
      }),
      playground('Sân chơi: thiết kế màn chơi của em', [
        'Sửa `MAN_CHOI` để tạo màn chơi của riêng em. Vài ý tưởng:',
        '',
        '- Một cầu thang bậc thang đi lên',
        '- Một hang động có trần',
        '- Các bệ nổi rải rác cần nhảy chuyền',
        '',
        'Nhớ: mọi dòng phải **dài bằng nhau**, nếu không sẽ lỗi khi truy cập ô.',
      ], [
        'import pygame',
        '',
        'pygame.init()',
        'TILE = 40',
        '',
        '# Thiet ke man choi cua em o day',
        'MAN_CHOI = [',
        '    "....................",',
        '    "....................",',
        '    "....................",',
        '    "....................",',
        '    "....................",',
        '    "....................",',
        '    "....................",',
        '    "XXXXXXXXXXXXXXXXXXXX",',
        ']',
        '',
        'RONG = len(MAN_CHOI[0]) * TILE',
        'CAO = len(MAN_CHOI) * TILE',
        'man_hinh = pygame.display.set_mode((RONG, CAO))',
        'dong_ho = pygame.time.Clock()',
        '',
        'nen = []',
        'for hang, dong in enumerate(MAN_CHOI):',
        '    for cot, ky_tu in enumerate(dong):',
        '        if ky_tu == "X":',
        '            nen.append(pygame.Rect(cot * TILE, hang * TILE, TILE, TILE))',
        '',
        'dang_chay = True',
        'while dang_chay:',
        '    for su_kien in pygame.event.get():',
        '        if su_kien.type == pygame.QUIT:',
        '            dang_chay = False',
        '    man_hinh.fill((30, 30, 55))',
        '    for o in nen:',
        '        pygame.draw.rect(man_hinh, (90, 100, 125), o)',
        '    pygame.display.flip()',
        '    dong_ho.tick(60)',
        '',
        'pygame.quit()',
      ], 'Thiết kế được một màn chơi có ít nhất ba bệ đứng ở độ cao khác nhau.'),
      challenge({
        slug: 'p-pg-b17-dem-o-nen',
        title: 'Đếm ô nền và tìm điểm xuất phát',
        statement: [
          'Dòng đầu: hai số nguyên `H` và `T` — số hàng của tile map và kích thước một ô.',
          '',
          '`H` dòng tiếp theo là các dòng của tile map, gồm ký tự `X` (nền), `.` (trống) và `P` (điểm xuất phát).',
          '',
          'In ra **hai dòng**:',
          '',
          '```',
          'So o nen: <n>',
          'Xuat phat: <x> <y>',
          '```',
          '',
          'Trong đó `<x> <y>` là toạ độ **điểm ảnh** của góc trên bên trái ô chứa `P` ' +
            '(tức `cot * T` và `hang * T`). Đề bảo đảm có đúng một ký tự `P`.',
        ].join('\n'),
        hints: [
          'Duyệt bằng hai vòng lặp lồng nhau, hoặc dùng `enumerate` cho gọn.',
          'Đếm `X` bằng một biến cộng dồn.',
          'Khi gặp `P`, ghi lại `cot * T` và `hang * T`.',
        ],
        starterCode: [
          'h, t = map(int, input().split())',
          'ban_do = []',
          'for i in range(h):',
          '    ban_do.append(input())',
          '',
          '# Đếm X và tìm P',
        ].join('\n'),
        solutionCode: [
          'h, t = map(int, input().split())',
          'ban_do = []',
          'for i in range(h):',
          '    ban_do.append(input())',
          '',
          'so_nen = 0',
          'px = py = 0',
          'for hang, dong in enumerate(ban_do):',
          '    for cot, ky_tu in enumerate(dong):',
          '        if ky_tu == "X":',
          '            so_nen += 1',
          '        elif ky_tu == "P":',
          '            px = cot * t',
          '            py = hang * t',
          '',
          'print(f"So o nen: {so_nen}")',
          'print(f"Xuat phat: {px} {py}")',
        ].join('\n'),
        tier: 'CO_BAN',
        judgeMode: 'IO_MATCH',
        tests: [
          sample(
            '3 40\n..P.\n.XX.\nXXXX\n',
            'So o nen: 6\nXuat phat: 80 0\n',
            'P ở hàng 0 cột 2, nên toạ độ điểm ảnh là (2×40, 0×40) = (80, 0).',
          ),
          sample('1 10\nP..\n', 'So o nen: 0\nXuat phat: 0 0\n', 'Không có ô nền nào.'),
          hidden('2 32\n.P\nXX\n', 'So o nen: 2\nXuat phat: 32 0\n', 20),
          hidden('4 40\n....\n....\n....\nXXXP\n', 'So o nen: 3\nXuat phat: 120 120\n', 20),
          hidden('2 1\nXXXXX\nXXXXP\n', 'So o nen: 9\nXuat phat: 4 1\n', 30),
          hidden('3 50\nP....\n.....\nXXXXX\n', 'So o nen: 5\nXuat phat: 0 0\n', 30),
        ],
      }),
    ],
  },

  {
    order: 18,
    slug: 'pg-b18-nhan-vat-platformer',
    title: 'Nhân vật Platformer: nhảy, rơi, va chạm nền',
    summary:
      'Ghép trọng lực của buổi 11 với kỹ thuật tách hai trục của buổi 13 lên tile map của buổi 17. ' +
      'Kết quả là một nhân vật platformer đúng nghĩa.',
    objectives: [
      'Áp dụng tách hai trục cho va chạm với nhiều bệ nền',
      'Phát hiện đúng lúc nhân vật đứng trên nền',
      'Xử lý nhân vật đâm đầu vào trần',
      'Ngăn nhân vật lọt qua nền khi rơi quá nhanh',
    ],
    difficulty: 5,
    status: 'REQUIRED',
    teacherNotes:
      'Buổi khó nhất Module 4. Nhắc học sinh xem lại buổi 11 (trọng lực) và buổi 13 (tách trục) trước.',
    blocks: [
      theory('Ghép ba kỹ thuật đã học', [
        'Nhân vật platformer không có kỹ thuật mới nào — chỉ là ba thứ em đã biết ghép lại:',
        '',
        '| Từ buổi | Kỹ thuật | Vai trò ở đây |',
        '|---|---|---|',
        '| 11 | Trọng lực & nhảy | Làm nhân vật rơi và nhảy |',
        '| 13 | Tách hai trục | Biết nhân vật đâm vào nền từ hướng nào |',
        '| 17 | Tile map | Cung cấp danh sách các bệ nền |',
        '',
        'Vòng lặp cập nhật đầy đủ:',
        '',
        '```python',
        '# 1. Nguoi choi dieu khien -> vx',
        'phim = pygame.key.get_pressed()',
        'vx = 0',
        'if phim[pygame.K_LEFT]:',
        '    vx = -TOC_DO',
        'if phim[pygame.K_RIGHT]:',
        '    vx = TOC_DO',
        '',
        '# 2. Trong luc -> vy',
        'vy += TRONG_LUC',
        'if vy > TOC_DO_ROI_TOI_DA:',
        '    vy = TOC_DO_ROI_TOI_DA',
        '',
        '# 3. TRUC X: di chuyen roi day ra',
        'nv.x += int(vx)',
        'for o in nen:',
        '    if nv.colliderect(o):',
        '        if vx > 0:',
        '            nv.right = o.left',
        '        elif vx < 0:',
        '            nv.left = o.right',
        '',
        '# 4. TRUC Y: di chuyen roi day ra',
        'tren_nen = False',
        'nv.y += int(vy)',
        'for o in nen:',
        '    if nv.colliderect(o):',
        '        if vy > 0:              # dang roi -> dap dat',
        '            nv.bottom = o.top',
        '            tren_nen = True',
        '        elif vy < 0:            # dang bay len -> dam tran',
        '            nv.top = o.bottom',
        '        vy = 0',
        '```',
      ], [
        'Trọng lực → trục X → trục Y, đúng thứ tự đó',
        '`vy > 0` là đang rơi, `vy < 0` là đang bay lên',
        '`tren_nen` được đặt lại mỗi khung hình, chỉ True khi thật sự đáp đất',
      ]),
      theory('Lỗi lọt qua nền và cách chặn', [
        'Nếu `vy` lớn hơn chiều cao một ô nền, nhân vật sẽ **nhảy qua** ô đó giữa hai khung hình ' +
          'mà không hề chạm — rồi rơi xuyên xuống vực.',
        '',
        '```',
        'Khung 1:  nhan vat o day        Khung 2:',
        '          ▓',
        '          │  vy = 60',
        '  ════════▓════════  ← o nen (cao 40)',
        '          │',
        '          ▼                      ▓  <- da lot qua!',
        '```',
        '',
        '**Cách chặn đơn giản và hiệu quả nhất:** giới hạn tốc độ rơi dưới chiều cao ô nền.',
        '',
        '```python',
        'TOC_DO_ROI_TOI_DA = 18      # nho hon TILE = 40',
        'if vy > TOC_DO_ROI_TOI_DA:',
        '    vy = TOC_DO_ROI_TOI_DA',
        '```',
        '',
        'Đây cũng là lý do các game platformer thật đều có tốc độ rơi tối đa — vừa để tránh lỗi, ' +
          'vừa để người chơi kịp phản ứng.',
        '',
        '💡 Cách xử lý triệt để hơn là chia nhỏ bước di chuyển thành nhiều bước con, nhưng ' +
          'giới hạn tốc độ là đủ tốt cho mọi dự án của khoá học này.',
      ], [
        'Rơi quá nhanh sẽ lọt qua nền',
        'Giới hạn tốc độ rơi < kích thước một ô là cách chặn đơn giản nhất',
      ]),
      example('Platformer chạy được', 'Ghép tile map, trọng lực và tách trục.', [
        'import pygame',
        '',
        'pygame.init()',
        'TILE = 40',
        'MAN_CHOI = [',
        '    "....................",',
        '    "....................",',
        '    "......XXXX..........",',
        '    "....................",',
        '    "..XXX..........XXXX.",',
        '    "....................",',
        '    ".........XXX........",',
        '    "XXXXXXXXXXXXXXXXXXXX",',
        ']',
        '',
        'RONG = len(MAN_CHOI[0]) * TILE',
        'CAO = len(MAN_CHOI) * TILE',
        'man_hinh = pygame.display.set_mode((RONG, CAO))',
        'pygame.display.set_caption("Platformer")',
        'dong_ho = pygame.time.Clock()',
        'font = pygame.font.SysFont("arial", 16)',
        '',
        'nen = []',
        'for hang, dong in enumerate(MAN_CHOI):',
        '    for cot, ky_tu in enumerate(dong):',
        '        if ky_tu == "X":',
        '            nen.append(pygame.Rect(cot * TILE, hang * TILE, TILE, TILE))',
        '',
        'TRONG_LUC = 0.9',
        'LUC_NHAY = -15',
        'TOC_DO = 5',
        'TOC_DO_ROI_TOI_DA = 18',
        '',
        'nv = pygame.Rect(80, 40, 28, 38)',
        'vy = 0.0',
        'tren_nen = False',
        '',
        'dang_chay = True',
        'while dang_chay:',
        '    for su_kien in pygame.event.get():',
        '        if su_kien.type == pygame.QUIT:',
        '            dang_chay = False',
        '        elif su_kien.type == pygame.KEYDOWN:',
        '            if su_kien.key in (pygame.K_SPACE, pygame.K_UP) and tren_nen:',
        '                vy = LUC_NHAY',
        '            elif su_kien.key == pygame.K_r:',
        '                nv.topleft = (80, 40)',
        '                vy = 0.0',
        '',
        '    phim = pygame.key.get_pressed()',
        '    vx = 0',
        '    if phim[pygame.K_LEFT] or phim[pygame.K_a]:',
        '        vx = -TOC_DO',
        '    if phim[pygame.K_RIGHT] or phim[pygame.K_d]:',
        '        vx = TOC_DO',
        '',
        '    vy += TRONG_LUC',
        '    if vy > TOC_DO_ROI_TOI_DA:',
        '        vy = TOC_DO_ROI_TOI_DA',
        '',
        '    # ===== TRUC X =====',
        '    nv.x += vx',
        '    for o in nen:',
        '        if nv.colliderect(o):',
        '            if vx > 0:',
        '                nv.right = o.left',
        '            elif vx < 0:',
        '                nv.left = o.right',
        '',
        '    # ===== TRUC Y =====',
        '    tren_nen = False',
        '    nv.y += int(vy)',
        '    for o in nen:',
        '        if nv.colliderect(o):',
        '            if vy > 0:',
        '                nv.bottom = o.top',
        '                tren_nen = True',
        '            elif vy < 0:',
        '                nv.top = o.bottom',
        '            vy = 0.0',
        '',
        '    if nv.top > CAO:',
        '        nv.topleft = (80, 40)',
        '        vy = 0.0',
        '',
        '    # ===== VE =====',
        '    man_hinh.fill((30, 30, 55))',
        '    for o in nen:',
        '        pygame.draw.rect(man_hinh, (90, 100, 125), o)',
        '        pygame.draw.rect(man_hinh, (130, 145, 175), o, 2)',
        '    pygame.draw.rect(man_hinh, (46, 204, 113), nv, 0, border_radius=5)',
        '',
        '    man_hinh.blit(font.render(',
        '        f"tren_nen: {tren_nen}   vy: {vy:5.1f}   (R de dat lai)",',
        '        True, (200, 200, 225)), (8, 8))',
        '',
        '    pygame.display.flip()',
        '    dong_ho.tick(60)',
        '',
        'pygame.quit()',
      ], {
        output: 'Nhân vật xanh chạy và nhảy giữa các bệ, dừng đúng trên mặt bệ, đâm trần thì rơi lại.',
        notes: [
          '`tren_nen = False` đặt TRƯỚC vòng kiểm tra trục Y — nếu đặt sau, nhân vật sẽ nhảy được giữa không trung.',
          'Thử đổi `TOC_DO_ROI_TOI_DA` thành 60 rồi nhảy từ trên cao — nhân vật sẽ lọt qua bệ.',
          'Hiển thị `tren_nen` và `vy` ngay trên màn hình là cách gỡ lỗi platformer nhanh nhất.',
        ],
      }),
      playground('Sân chơi: chỉnh cảm giác platformer', [
        'Không viết thêm code, chỉ chỉnh bốn hằng số của ví dụ trên và cảm nhận:',
        '',
        '| Muốn gì | Chỉnh |',
        '|---|---|',
        '| Nhân vật nhanh nhẹn | `TOC_DO` lớn hơn |',
        '| Nhảy cao hơn | `LUC_NHAY` âm hơn |',
        '| Rơi nặng nề | `TRONG_LUC` lớn hơn |',
        '| Cảm giác trôi nổi | `TRONG_LUC` nhỏ, `LUC_NHAY` rất âm |',
        '',
        'Tìm bộ số em thích rồi ghi lại cho dự án ở buổi 24.',
      ], [
        '# Chinh bon hang so nay trong vi du o tren:',
        'TRONG_LUC = 0.9',
        'LUC_NHAY = -15',
        'TOC_DO = 5',
        'TOC_DO_ROI_TOI_DA = 18',
        '',
        '# Ghi lai bo so em thich nhat:',
        '# TRONG_LUC = ?',
        '# LUC_NHAY = ?',
      ], 'Tìm được bộ hằng số cho cảm giác điều khiển em thích và giải thích được vì sao.'),
      challenge({
        slug: 'p-pg-b18-dap-dat',
        title: 'Nhân vật đáp xuống nền',
        statement: [
          'Mép dưới của nhân vật đang ở toạ độ `y` và rơi với vận tốc `v` mỗi khung hình.',
          '',
          'Có một bệ nền với mép trên ở `nen`. Mỗi khung hình `y` tăng thêm `v`. ' +
            'Ngay khi `y >= nen`, nhân vật **đáp xuống**: `y` được đặt bằng `nen` và mô phỏng dừng lại.',
          '',
          'Đọc **bốn số nguyên** trên bốn dòng theo thứ tự: `y`, `v`, `nen`, `N` ' +
            '(`N` là số khung hình tối đa được mô phỏng).',
          '',
          'In ra **hai dòng**:',
          '',
          '```',
          'Vi tri: <y>',
          'Da dap dat: <CO hoac KHONG>',
          '```',
          '',
          'In `CO` nếu nhân vật đã chạm nền trong `N` khung hình, ngược lại in `KHONG`.',
        ].join('\n'),
        hints: [
          'Lặp tối đa N lần, mỗi lần cộng v vào y.',
          'Kiểm tra `y >= nen` ngay sau khi cộng, và dùng `break` để dừng.',
          'Dùng một biến cờ để ghi nhớ đã đáp đất hay chưa.',
        ],
        starterCode: [
          'y = int(input())',
          'v = int(input())',
          'nen = int(input())',
          'n = int(input())',
          '',
          'da_dap = False',
          '# Mô phỏng tối đa n khung hình',
        ].join('\n'),
        solutionCode: [
          'y = int(input())',
          'v = int(input())',
          'nen = int(input())',
          'n = int(input())',
          '',
          'da_dap = False',
          'for i in range(n):',
          '    y += v',
          '    if y >= nen:',
          '        y = nen',
          '        da_dap = True',
          '        break',
          '',
          'print(f"Vi tri: {y}")',
          'if da_dap:',
          '    print("Da dap dat: CO")',
          'else:',
          '    print("Da dap dat: KHONG")',
        ].join('\n'),
        tier: 'THU_THACH',
        judgeMode: 'IO_MATCH',
        tests: [
          sample(
            '100\n20\n200\n10\n',
            'Vi tri: 200\nDa dap dat: CO\n',
            'Sau 5 khung y = 200, đúng bằng mép nền nên đáp xuống.',
          ),
          sample('0\n5\n1000\n10\n', 'Vi tri: 50\nDa dap dat: KHONG\n', 'Hết 10 khung mà vẫn chưa tới nền.'),
          hidden('0\n18\n40\n5\n', 'Vi tri: 40\nDa dap dat: CO\n', 20),
          hidden('195\n10\n200\n1\n', 'Vi tri: 200\nDa dap dat: CO\n', 20),
          hidden('0\n0\n100\n50\n', 'Vi tri: 0\nDa dap dat: KHONG\n', 30),
          hidden('300\n7\n280\n1\n', 'Vi tri: 280\nDa dap dat: CO\n', 30),
        ],
      }),
    ],
  },

  {
    order: 19,
    slug: 'pg-b19-camera-va-cuon-man-hinh',
    title: 'Camera & cuộn màn hình',
    summary:
      'Màn chơi rộng hơn cửa sổ. Camera là thứ quyết định người chơi nhìn thấy phần nào — ' +
      'và nó đơn giản hơn em tưởng nhiều.',
    objectives: [
      'Hiểu camera chỉ là một độ lệch trừ vào toạ độ khi vẽ',
      'Cho camera bám theo nhân vật',
      'Kẹp camera lại ở mép màn chơi',
      'Tạo hiệu ứng nền nhiều lớp (parallax)',
    ],
    difficulty: 4,
    status: 'REQUIRED',
    teacherNotes: 'Ý chính: camera KHÔNG di chuyển thế giới, nó chỉ đổi cách vẽ. Nhấn mạnh điều này.',
    blocks: [
      theory('Camera chỉ là một phép trừ', [
        'Nghe "camera" thì tưởng phức tạp, nhưng thực chất chỉ là **hai con số** trừ vào toạ độ ' +
          'lúc vẽ:',
        '',
        '```python',
        'camera_x = 0',
        'camera_y = 0',
        '',
        '# Khi ve, tru di camera',
        'pygame.draw.rect(man_hinh, MAU,',
        '                 (o.x - camera_x, o.y - camera_y, o.width, o.height))',
        '```',
        '',
        '⚠️ **Điểm quan trọng nhất:** toạ độ thật của mọi vật **không hề thay đổi**. ' +
          'Va chạm, vật lý, AI vẫn tính trên toạ độ thật. Camera chỉ ảnh hưởng đến **việc vẽ**.',
        '',
        'Trộn lẫn hai hệ toạ độ này là lỗi phổ biến nhất khi làm camera. Quy tắc để nhớ:',
        '',
        '| Việc | Dùng toạ độ nào |',
        '|---|---|',
        '| Va chạm, vật lý, AI | Toạ độ **thế giới** (thật) |',
        '| Vẽ lên màn hình | Toạ độ **thế giới − camera** |',
        '| HUD (điểm, máu) | Toạ độ **màn hình** (không trừ camera) |',
      ], [
        'Camera = độ lệch trừ vào toạ độ khi VẼ',
        'Toạ độ thật không đổi — va chạm vẫn tính như cũ',
        'HUD không trừ camera',
      ]),
      theory('Bám theo nhân vật và kẹp ở mép', [
        '**Camera bám cứng** — nhân vật luôn ở chính giữa:',
        '',
        '```python',
        'camera_x = nv.centerx - RONG // 2',
        'camera_y = nv.centery - CAO // 2',
        '```',
        '',
        '**Camera bám mượt** — trôi dần tới vị trí đích, dễ chịu hơn nhiều cho mắt:',
        '',
        '```python',
        'dich_x = nv.centerx - RONG // 2',
        'camera_x += (dich_x - camera_x) * 0.1     # 0.1 = do muot',
        '```',
        '',
        '**Kẹp camera ở mép màn chơi** — để không nhìn thấy khoảng trống ngoài bản đồ:',
        '',
        '```python',
        'if camera_x < 0:',
        '    camera_x = 0',
        'if camera_x > RONG_MAN_CHOI - RONG:',
        '    camera_x = RONG_MAN_CHOI - RONG',
        '```',
        '',
        '💡 **Parallax** — nền xa cuộn chậm hơn nền gần, tạo cảm giác chiều sâu:',
        '',
        '```python',
        'man_hinh.blit(nen_xa, (-camera_x * 0.3, 0))     # cuon cham',
        'man_hinh.blit(nen_gan, (-camera_x * 0.7, 0))    # cuon nhanh hon',
        '# Vat the trong game: -camera_x * 1.0',
        '```',
      ], [
        'Bám cứng: `camera_x = nv.centerx - RONG // 2`',
        'Bám mượt: cộng dần một phần của khoảng cách còn lại',
        'Luôn kẹp camera ở mép màn chơi',
        'Parallax: nhân camera với hệ số nhỏ hơn 1 cho lớp nền xa',
      ]),
      example('Platformer có camera cuộn', 'Màn chơi rộng gấp ba cửa sổ.', [
        'import pygame',
        '',
        'pygame.init()',
        'TILE = 40',
        'RONG, CAO = 640, 480',
        'man_hinh = pygame.display.set_mode((RONG, CAO))',
        'pygame.display.set_caption("Camera cuon")',
        'dong_ho = pygame.time.Clock()',
        'font = pygame.font.SysFont("arial", 16)',
        '',
        'MAN_CHOI = [',
        '    "................................................",',
        '    "................................................",',
        '    "......XXXX.............XXX......................",',
        '    "................................................",',
        '    "..XXX.........XXXX...........XXXX....XXX........",',
        '    "................................................",',
        '    ".........XXX.........XXX..............XXXXX.....",',
        '    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",',
        ']',
        '',
        'RONG_MAN_CHOI = len(MAN_CHOI[0]) * TILE',
        'CAO_MAN_CHOI = len(MAN_CHOI) * TILE',
        '',
        'nen = []',
        'for hang, dong in enumerate(MAN_CHOI):',
        '    for cot, ky_tu in enumerate(dong):',
        '        if ky_tu == "X":',
        '            nen.append(pygame.Rect(cot * TILE, hang * TILE, TILE, TILE))',
        '',
        'nv = pygame.Rect(80, 40, 28, 38)',
        'vy = 0.0',
        'tren_nen = False',
        'camera_x = 0.0',
        '',
        'dang_chay = True',
        'while dang_chay:',
        '    for su_kien in pygame.event.get():',
        '        if su_kien.type == pygame.QUIT:',
        '            dang_chay = False',
        '        elif su_kien.type == pygame.KEYDOWN:',
        '            if su_kien.key in (pygame.K_SPACE, pygame.K_UP) and tren_nen:',
        '                vy = -15',
        '',
        '    phim = pygame.key.get_pressed()',
        '    vx = 0',
        '    if phim[pygame.K_LEFT]:',
        '        vx = -5',
        '    if phim[pygame.K_RIGHT]:',
        '        vx = 5',
        '',
        '    vy = min(vy + 0.9, 18)',
        '',
        '    nv.x += vx',
        '    for o in nen:',
        '        if nv.colliderect(o):',
        '            if vx > 0:',
        '                nv.right = o.left',
        '            elif vx < 0:',
        '                nv.left = o.right',
        '',
        '    tren_nen = False',
        '    nv.y += int(vy)',
        '    for o in nen:',
        '        if nv.colliderect(o):',
        '            if vy > 0:',
        '                nv.bottom = o.top',
        '                tren_nen = True',
        '            elif vy < 0:',
        '                nv.top = o.bottom',
        '            vy = 0.0',
        '',
        '    if nv.top > CAO_MAN_CHOI:',
        '        nv.topleft = (80, 40)',
        '        vy = 0.0',
        '',
        '    # ===== CAMERA: bam muot roi kep lai =====',
        '    dich_x = nv.centerx - RONG // 2',
        '    camera_x += (dich_x - camera_x) * 0.12',
        '    if camera_x < 0:',
        '        camera_x = 0.0',
        '    if camera_x > RONG_MAN_CHOI - RONG:',
        '        camera_x = float(RONG_MAN_CHOI - RONG)',
        '',
        '    cx = int(camera_x)',
        '',
        '    # ===== VE =====',
        '    man_hinh.fill((30, 30, 55))',
        '',
        '    # Nen xa - parallax, cuon cham hon',
        '    for i in range(0, RONG_MAN_CHOI, 160):',
        '        pygame.draw.circle(man_hinh, (45, 45, 80),',
        '                           (i - int(camera_x * 0.3), 120), 50)',
        '',
        '    for o in nen:',
        '        khung = pygame.Rect(o.x - cx, o.y, TILE, TILE)',
        '        if khung.right > 0 and khung.left < RONG:      # chi ve o dang nhin thay',
        '            pygame.draw.rect(man_hinh, (90, 100, 125), khung)',
        '            pygame.draw.rect(man_hinh, (130, 145, 175), khung, 2)',
        '',
        '    pygame.draw.rect(man_hinh, (46, 204, 113),',
        '                     (nv.x - cx, nv.y, nv.width, nv.height), 0, border_radius=5)',
        '',
        '    # HUD: KHONG tru camera',
        '    man_hinh.blit(font.render(',
        '        f"camera_x: {cx}   nv.x thuc te: {nv.x}", True, (200, 200, 225)), (8, 8))',
        '',
        '    pygame.display.flip()',
        '    dong_ho.tick(60)',
        '',
        'pygame.quit()',
      ], {
        output:
          'Nhân vật chạy trong màn chơi rộng 1920 điểm ảnh; camera bám mượt và dừng lại ở hai đầu bản đồ.',
        notes: [
          'Hai chỉ số trên HUD cho thấy rõ: `nv.x` thật vẫn tăng đều, camera chỉ bám theo.',
          'Điều kiện `khung.right > 0 and khung.left < RONG` bỏ qua các ô ngoài tầm nhìn — ' +
            'tối ưu quan trọng khi bản đồ lớn.',
          'Các vòng tròn nền cuộn với hệ số 0.3 nên trông như ở rất xa.',
        ],
      }),
      playground('Sân chơi: so sánh bám cứng và bám mượt', [
        'Trong ví dụ trên, đổi dòng camera:',
        '',
        '```python',
        '# Bam cung',
        'camera_x = nv.centerx - RONG // 2',
        '',
        '# Bam muot (doi 0.12 thanh 0.05 hoac 0.3)',
        'camera_x += (dich_x - camera_x) * 0.12',
        '```',
        '',
        'Chạy thử cả ba và cảm nhận. Bám cứng chính xác nhưng hơi "dính mắt"; bám mượt dễ chịu hơn ' +
          'nhưng nếu quá chậm sẽ thấy trễ.',
      ], [
        '# Thu ba gia tri do muot trong vi du o tren:',
        '# 1. Bam cung:   camera_x = nv.centerx - RONG // 2',
        '# 2. Rat muot:   camera_x += (dich_x - camera_x) * 0.05',
        '# 3. Muot vua:   camera_x += (dich_x - camera_x) * 0.12',
        '# 4. Gan nhu cung: camera_x += (dich_x - camera_x) * 0.4',
        '',
        '# Ghi lai gia tri em thay de chiu nhat:',
      ], 'Chọn được độ mượt camera phù hợp và giải thích được đánh đổi giữa hai cách.'),
      challenge({
        slug: 'p-pg-b19-kep-camera',
        title: 'Kẹp camera ở mép màn chơi',
        statement: [
          'Camera cần đặt sao cho nhân vật ở giữa màn hình, nhưng không được nhìn ra ngoài màn chơi.',
          '',
          'Công thức: `camera = nhan_vat - man_hinh // 2`, sau đó kẹp vào khoảng ' +
            '`[0, man_choi - man_hinh]`.',
          '',
          'Nếu màn chơi **hẹp hơn** màn hình (`man_choi < man_hinh`), camera luôn bằng `0`.',
          '',
          'Dòng đầu: số nguyên `Q`. `Q` dòng tiếp theo, mỗi dòng ba số nguyên ' +
            '`<nhan_vat> <man_hinh> <man_choi>`.',
          '',
          'Với mỗi dòng, in giá trị camera trên một dòng riêng.',
        ].join('\n'),
        hints: [
          'Tính `cam = nhan_vat - man_hinh // 2` trước.',
          'Giới hạn trên là `man_choi - man_hinh`.',
          'Nếu giới hạn trên nhỏ hơn 0, kết quả luôn là 0.',
        ],
        starterCode: [
          'q = int(input())',
          '',
          'for i in range(q):',
          '    nv, mh, mc = map(int, input().split())',
          '    # Tính camera rồi kẹp lại',
        ].join('\n'),
        solutionCode: [
          'q = int(input())',
          '',
          'for i in range(q):',
          '    nv, mh, mc = map(int, input().split())',
          '    cam = nv - mh // 2',
          '    toi_da = mc - mh',
          '    if toi_da < 0:',
          '        cam = 0',
          '    else:',
          '        if cam < 0:',
          '            cam = 0',
          '        if cam > toi_da:',
          '            cam = toi_da',
          '    print(cam)',
        ].join('\n'),
        tier: 'THU_THACH',
        judgeMode: 'IO_MATCH',
        tests: [
          sample(
            '3\n960 640 1920\n100 640 1920\n1900 640 1920\n',
            '640\n0\n1280\n',
            'Ở giữa bản đồ camera tự do; sát hai mép thì bị kẹp lại.',
          ),
          sample('1\n200 800 400\n', '0\n', 'Màn chơi hẹp hơn màn hình nên camera luôn bằng 0.'),
          hidden('1\n320 640 640\n', '0\n', 20),
          hidden('1\n0 100 1000\n', '0\n', 20),
          hidden('2\n500 200 1000\n999 200 1000\n', '400\n800\n', 30),
          hidden('1\n50 640 1920\n', '0\n', 30),
        ],
      }),
    ],
  },
];
