/**
 * Lập Trình Game Python (Pygame) — Module 1 & 2 (Buổi 1–8).
 *
 * Teacher notes enforced here:
 *   • Note 9  — "Do NOT enforce dry theory continuously." Every session in
 *     Module 1 ends with something moving on screen: a window in session 1,
 *     falling objects in session 3, a sprite moving left/right in session 4.
 *   • Note 10 — drawing and image loading are COMBINED into one early session
 *     (B6), and the module closes with a controllable paddle/tank (B8).
 *
 * Auto-graded exercises in this course are logic-only (vectors, collision maths,
 * score rules) so they run in the standard sandbox. The game itself is assessed
 * by project upload with teacher review — see docs/01-ARCHITECTURE.md §5.4.
 */
import type { ModuleSpec } from '../types.ts';
import {
  challenge,
  example,
  hidden,
  playground,
  projectBlock,
  quizBlock,
  sample,
  theory,
} from '../builders.ts';

export const pygameModule1: ModuleSpec = {
  slug: 'nen-tang-hoc-qua-tuong-tac',
  title: 'Module 1 · Nền tảng — học qua tương tác',
  description:
    'Bốn buổi đầu ôn lại Python nhưng luôn gắn với hình ảnh chuyển động. Không có buổi nào chỉ ' +
    'ngồi nghe lý thuyết: kết thúc mỗi buổi em đều có một thứ chạy được trên màn hình.',
  lessons: [
    {
      order: 1,
      slug: 'pg-b01-gioi-thieu-va-cua-so-dau-tien',
      title: 'Giới thiệu lập trình game · Cài đặt Pygame · Cửa sổ game đầu tiên',
      summary:
        'Ngay buổi đầu tiên em đã có một cửa sổ game của riêng mình, đổi được màu nền và đóng được bằng nút X.',
      objectives: [
        'Hiểu vòng lặp game (game loop) là trái tim của mọi trò chơi',
        'Cài đặt và kiểm tra Pygame',
        'Tạo được cửa sổ game, đặt tiêu đề và màu nền',
        'Xử lý sự kiện đóng cửa sổ',
      ],
      difficulty: 2,
      estimatedMinutes: 90,
      status: 'REQUIRED',
      teacherNotes:
        'Module 1 GHI CHÚ: KHÔNG dạy lý thuyết khô liên tục. Ngay buổi 1 học sinh phải thấy cửa sổ ' +
        'game của mình hiện ra. Phần lý thuyết chỉ đủ để hiểu game loop.',
      prerequisites: [],
      blocks: [
        theory('Một trò chơi thực chất là gì?', [
          'Mọi trò chơi, từ Pong năm 1972 đến game 3D hôm nay, đều chạy trên cùng một vòng lặp:',
          '',
          '```',
          'Lặp mãi cho tới khi người chơi thoát:',
          '    1. NGHE   — người chơi bấm phím gì, chuột ở đâu?',
          '    2. CẬP NHẬT — di chuyển nhân vật, kiểm tra va chạm, tính điểm',
          '    3. VẼ     — xoá màn hình cũ, vẽ lại toàn bộ khung hình mới',
          '    4. CHỜ    — nghỉ một chút để đạt đúng 60 khung hình mỗi giây',
          '```',
          '',
          'Vòng lặp này gọi là **game loop**. Nó chạy khoảng **60 lần mỗi giây** — mắt người ' +
            'ghép các khung hình liên tiếp lại thành chuyển động mượt.',
          '',
          'Nghe quen chứ? Đó chính là `while` và `for` em đã học ở khoá Cơ Bản. ' +
            'Game chỉ là vòng lặp chạy rất nhanh và vẽ ra màn hình.',
        ], [
          'Game loop: Nghe → Cập nhật → Vẽ → Chờ',
          'Chạy khoảng 60 lần mỗi giây',
          'Mỗi vòng lặp vẽ lại TOÀN BỘ khung hình',
        ]),
        theory('Cài đặt Pygame và hệ toạ độ', [
          '**Cài đặt** (chạy một lần trong terminal):',
          '',
          '```',
          'pip install pygame-ce',
          '```',
          '',
          'Khoá học dùng `pygame-ce` — bản cộng đồng, được cập nhật thường xuyên hơn và tương thích ' +
            'hoàn toàn với `import pygame`.',
          '',
          '**Hệ toạ độ màn hình khác với Toán học:**',
          '',
          '```',
          '(0,0) ────────────► x tăng sang phải',
          '  │',
          '  │      ● (400, 300)',
          '  │',
          '  ▼',
          '  y tăng xuống dưới',
          '```',
          '',
          '⚠️ Gốc toạ độ ở **góc trên bên trái**, và **y tăng khi đi xuống**. ' +
            'Muốn vật rơi xuống, em phải **cộng** vào y chứ không phải trừ. ' +
            'Đây là điều dễ nhầm nhất trong buổi đầu.',
        ], [
          '`pip install pygame-ce`, dùng bằng `import pygame`',
          'Gốc toạ độ (0,0) ở góc TRÊN BÊN TRÁI',
          'y TĂNG khi đi xuống — cộng y để rơi xuống',
        ]),
        example('Cửa sổ game đầu tiên của em', 'Chép đoạn này, chạy thử, rồi đổi màu và kích thước theo ý em.', [
          'import pygame',
          '',
          'pygame.init()',
          '',
          '# Tao cua so 800x600',
          'man_hinh = pygame.display.set_mode((800, 600))',
          'pygame.display.set_caption("Game dau tien cua em")',
          'dong_ho = pygame.time.Clock()',
          '',
          '# Mau duoi dang (Red, Green, Blue), moi so tu 0 den 255',
          'XANH_DEM = (25, 25, 60)',
          '',
          'dang_chay = True',
          'while dang_chay:',
          '    # --- 1. NGHE ---',
          '    for su_kien in pygame.event.get():',
          '        if su_kien.type == pygame.QUIT:',
          '            dang_chay = False',
          '',
          '    # --- 2. CAP NHAT --- (chua co gi)',
          '',
          '    # --- 3. VE ---',
          '    man_hinh.fill(XANH_DEM)',
          '    pygame.display.flip()',
          '',
          '    # --- 4. CHO ---',
          '    dong_ho.tick(60)',
          '',
          'pygame.quit()',
        ], {
          output: 'Một cửa sổ 800×600 màu xanh đêm, tiêu đề "Game dau tien cua em", đóng được bằng nút X.',
          notes: [
            '`pygame.display.flip()` là lệnh "đưa những gì vừa vẽ lên màn hình". Thiếu nó thì màn hình đen.',
            '`dong_ho.tick(60)` giới hạn 60 khung hình/giây. Thiếu nó, máy sẽ chạy hết công suất một cách vô ích.',
            '`pygame.QUIT` là sự kiện khi người chơi bấm nút X.',
          ],
        }),
        playground('Sân chơi: cửa sổ của riêng em', [
          'Đổi ba thứ trong đoạn code và chạy lại sau mỗi lần đổi:',
          '',
          '1. Kích thước cửa sổ — thử `(640, 480)` hoặc `(1024, 768)`',
          '2. Màu nền — thử `(255, 200, 100)` hoặc màu em thích',
          '3. Tiêu đề cửa sổ',
          '',
          'Sau đó thử **xoá dòng `pygame.display.flip()`** và chạy lại. Màn hình sẽ đen — ' +
            'đó là cách để em nhớ dòng này quan trọng thế nào.',
        ], [
          'import pygame',
          '',
          'pygame.init()',
          'man_hinh = pygame.display.set_mode((800, 600))',
          'pygame.display.set_caption("Doi tieu de o day")',
          'dong_ho = pygame.time.Clock()',
          '',
          'MAU_NEN = (25, 25, 60)   # doi mau o day',
          '',
          'dang_chay = True',
          'while dang_chay:',
          '    for su_kien in pygame.event.get():',
          '        if su_kien.type == pygame.QUIT:',
          '            dang_chay = False',
          '',
          '    man_hinh.fill(MAU_NEN)',
          '    pygame.display.flip()',
          '    dong_ho.tick(60)',
          '',
          'pygame.quit()',
        ], 'Cửa sổ chạy được, đổi được màu, kích thước, tiêu đề, và đóng được bằng nút X.'),
        quizBlock({
          slug: 'q-pg-b01-game-loop',
          title: 'Kiểm tra nhanh: game loop',
          questions: [
            {
              type: 'MULTIPLE_CHOICE',
              prompt: 'Trong hệ toạ độ của Pygame, tăng giá trị `y` sẽ làm vật di chuyển về hướng nào?',
              explanation: 'Khác với Toán học, trục y của màn hình hướng xuống dưới.',
              choices: [
                { text: 'Đi xuống dưới', isCorrect: true },
                { text: 'Đi lên trên' },
                { text: 'Sang phải' },
                { text: 'Sang trái' },
              ],
            },
            {
              type: 'MULTIPLE_CHOICE',
              prompt: 'Lệnh nào đưa những gì vừa vẽ lên màn hình cho người chơi thấy?',
              explanation: 'Không có `pygame.display.flip()`, mọi thứ chỉ được vẽ trong bộ nhớ.',
              choices: [
                { text: 'pygame.display.flip()', isCorrect: true },
                { text: 'pygame.init()' },
                { text: 'man_hinh.fill()' },
                { text: 'dong_ho.tick(60)' },
              ],
            },
            {
              type: 'MULTIPLE_CHOICE',
              prompt: 'Bốn bước của một vòng lặp game theo đúng thứ tự là gì?',
              explanation: 'Nghe sự kiện → cập nhật trạng thái → vẽ khung hình → chờ để giữ FPS.',
              choices: [
                { text: 'Nghe sự kiện → Cập nhật → Vẽ → Chờ', isCorrect: true },
                { text: 'Vẽ → Nghe sự kiện → Chờ → Cập nhật' },
                { text: 'Cập nhật → Vẽ → Nghe sự kiện → Chờ' },
                { text: 'Chờ → Vẽ → Cập nhật → Nghe sự kiện' },
              ],
            },
            {
              type: 'TRUE_FALSE',
              prompt: 'Có thể bỏ `dong_ho.tick(60)` mà game vẫn chạy đúng tốc độ trên mọi máy.',
              explanation:
                'Sai. Không giới hạn FPS thì game chạy nhanh chậm khác nhau tuỳ cấu hình máy.',
              choices: [{ text: 'Đúng' }, { text: 'Sai', isCorrect: true }],
            },
          ],
        }),
      ],
    },

    {
      order: 2,
      slug: 'pg-b02-on-python-qua-hinh-ve',
      title: 'Ôn Python qua game: biến & kiểu dữ liệu điều khiển hình vẽ',
      summary:
        'Biến không còn là con số trừu tượng — mỗi biến bây giờ điều khiển vị trí, kích thước hoặc màu ' +
        'của một hình trên màn hình.',
      objectives: [
        'Dùng biến để điều khiển vị trí và kích thước hình vẽ',
        'Biểu diễn màu sắc bằng bộ ba RGB',
        'Vẽ hình chữ nhật, hình tròn và đường thẳng',
        'Thay đổi giá trị biến qua từng khung hình để tạo chuyển động',
      ],
      difficulty: 2,
      status: 'REQUIRED',
      teacherNotes:
        'Ôn lại biến và kiểu dữ liệu, nhưng gắn ngay với hình ảnh. Kết thúc buổi phải có hình di chuyển được.',
      blocks: [
        theory('Biến điều khiển hình vẽ', [
          'Ở khoá Cơ Bản, `x = 100` chỉ là một con số. Ở đây, `x` là **vị trí ngang của nhân vật**.',
          '',
          'Ba lệnh vẽ cơ bản:',
          '',
          '```python',
          '# Hình chữ nhật: (mặt vẽ, màu, (x, y, rộng, cao))',
          'pygame.draw.rect(man_hinh, DO, (x, y, 50, 50))',
          '',
          '# Hình tròn: (mặt vẽ, màu, (tâm_x, tâm_y), bán kính)',
          'pygame.draw.circle(man_hinh, XANH, (x, y), 25)',
          '',
          '# Đường thẳng: (mặt vẽ, màu, điểm đầu, điểm cuối, độ dày)',
          'pygame.draw.line(man_hinh, TRANG, (0, 300), (800, 300), 3)',
          '```',
          '',
          '**Màu sắc là một tuple ba số** (em đã gặp tuple ở buổi 23 khoá Cơ Bản):',
          '',
          '| Màu | RGB |',
          '|---|---|',
          '| Đỏ | `(255, 0, 0)` |',
          '| Xanh lá | `(0, 255, 0)` |',
          '| Xanh dương | `(0, 0, 255)` |',
          '| Trắng | `(255, 255, 255)` |',
          '| Đen | `(0, 0, 0)` |',
          '',
          'Mỗi số từ 0 đến 255. Trộn ba số lại được hơn 16 triệu màu.',
        ], [
          'Biến trong game điều khiển vị trí, kích thước, màu',
          'Màu là tuple `(R, G, B)`, mỗi số 0–255',
          '`draw.rect`, `draw.circle`, `draw.line` là ba lệnh vẽ hay dùng nhất',
        ]),
        theory('Bí mật của chuyển động', [
          'Chuyển động trong game không có gì huyền bí. Chỉ là:',
          '',
          '```python',
          'x = x + 5      # mỗi khung hình dịch sang phải 5 điểm ảnh',
          '```',
          '',
          'Game loop chạy 60 lần/giây, nên vật dịch 5 × 60 = **300 điểm ảnh mỗi giây**.',
          '',
          '⚠️ **Cực kỳ quan trọng:** phải **xoá màn hình** ở đầu mỗi lần vẽ bằng `man_hinh.fill(...)`. ' +
            'Nếu quên, hình cũ vẫn còn nguyên và em sẽ thấy một vệt dài thay vì một vật đang di chuyển.',
          '',
          '(Thật ra hiệu ứng "vệt dài" đó khá đẹp — nhiều game dùng nó cố ý. Nhưng phải là chủ ý, ' +
            'không phải do quên.)',
        ], [
          'Chuyển động = thay đổi biến vị trí mỗi khung hình',
          'Luôn `fill()` để xoá khung hình cũ trước khi vẽ khung mới',
          'Dịch 5 điểm/khung × 60 khung/giây = 300 điểm/giây',
        ]),
        example('Ba hình và một hình biết chạy', 'Chú ý biến `x` thay đổi trong vòng lặp.', [
          'import pygame',
          '',
          'pygame.init()',
          'man_hinh = pygame.display.set_mode((800, 600))',
          'pygame.display.set_caption("Bien dieu khien hinh ve")',
          'dong_ho = pygame.time.Clock()',
          '',
          'DEN = (20, 20, 30)',
          'DO = (231, 76, 60)',
          'XANH_LA = (46, 204, 113)',
          'VANG = (241, 196, 15)',
          '',
          '# Bien dieu khien hinh chay',
          'x = 50',
          'y = 300',
          'toc_do = 4',
          '',
          'dang_chay = True',
          'while dang_chay:',
          '    for su_kien in pygame.event.get():',
          '        if su_kien.type == pygame.QUIT:',
          '            dang_chay = False',
          '',
          '    # --- CAP NHAT ---',
          '    x = x + toc_do',
          '    if x > 800:',
          '        x = 0            # ra khoi man hinh thi quay lai dau',
          '',
          '    # --- VE ---',
          '    man_hinh.fill(DEN)                                   # xoa khung cu',
          '    pygame.draw.line(man_hinh, VANG, (0, 400), (800, 400), 3)',
          '    pygame.draw.rect(man_hinh, DO, (100, 450, 120, 60))',
          '    pygame.draw.circle(man_hinh, XANH_LA, (x, y), 30)    # hinh biet chay',
          '',
          '    pygame.display.flip()',
          '    dong_ho.tick(60)',
          '',
          'pygame.quit()',
        ], {
          output:
            'Một đường vàng ngang, một chữ nhật đỏ đứng yên, và một hình tròn xanh chạy từ trái sang phải rồi lặp lại.',
          notes: [
            'Chỉ hình tròn chuyển động vì chỉ toạ độ của nó được cập nhật trong vòng lặp.',
            'Thứ tự vẽ quan trọng: vẽ sau thì nằm đè lên vẽ trước.',
            'Thử tăng `toc_do` lên 20 để thấy khác biệt.',
          ],
        }),
        playground('Sân chơi: hình vuông nảy qua nảy lại', [
          'Sửa đoạn code để hình vuông **nảy ngược lại** khi chạm mép thay vì quay về đầu.',
          '',
          'Gợi ý: khi `x` vượt quá mép phải hoặc nhỏ hơn 0, hãy đổi dấu tốc độ — `toc_do = -toc_do`.',
        ], [
          'import pygame',
          '',
          'pygame.init()',
          'man_hinh = pygame.display.set_mode((800, 600))',
          'dong_ho = pygame.time.Clock()',
          '',
          'x = 400',
          'toc_do = 5',
          '',
          'dang_chay = True',
          'while dang_chay:',
          '    for su_kien in pygame.event.get():',
          '        if su_kien.type == pygame.QUIT:',
          '            dang_chay = False',
          '',
          '    x += toc_do',
          '    # Them dieu kien nay nguoc lai o day',
          '',
          '    man_hinh.fill((20, 20, 30))',
          '    pygame.draw.rect(man_hinh, (52, 152, 219), (x, 280, 40, 40))',
          '    pygame.display.flip()',
          '    dong_ho.tick(60)',
          '',
          'pygame.quit()',
        ], 'Hình vuông nảy qua nảy lại giữa hai mép màn hình mà không bị kẹt.'),
        challenge({
          slug: 'p-pg-b02-vi-tri-sau-n-khung',
          title: 'Vị trí sau N khung hình',
          statement: [
            'Một vật bắt đầu ở toạ độ `x` và mỗi khung hình dịch thêm `v` điểm ảnh.',
            '',
            'Màn hình rộng `W`. Khi vật vượt quá mép phải (`x > W`) nó quay về `x = 0`; ' +
              'khi vượt quá mép trái (`x < 0`) nó nhảy về `x = W`.',
            '',
            'Đọc **bốn số nguyên** trên bốn dòng: `x`, `v`, `W`, `N`.',
            '',
            'In ra **một dòng** là toạ độ `x` sau đúng `N` khung hình.',
          ].join('\n'),
          hints: [
            'Lặp đúng N lần, mỗi lần cộng v vào x.',
            'Sau mỗi lần cộng, kiểm tra ngay điều kiện vượt mép.',
            'Chú ý thứ tự: cộng trước, kiểm tra sau.',
          ],
          starterCode: [
            'x = int(input())',
            'v = int(input())',
            'w = int(input())',
            'n = int(input())',
            '',
            '# Mô phỏng n khung hình',
          ].join('\n'),
          solutionCode: [
            'x = int(input())',
            'v = int(input())',
            'w = int(input())',
            'n = int(input())',
            '',
            'for i in range(n):',
            '    x += v',
            '    if x > w:',
            '        x = 0',
            '    elif x < 0:',
            '        x = w',
            '',
            'print(x)',
          ].join('\n'),
          tier: 'CO_BAN',
          judgeMode: 'IO_MATCH',
          tests: [
            sample('0\n5\n800\n10\n', '50\n', 'Sau 10 khung, x = 0 + 5×10 = 50, chưa vượt mép.'),
            sample('795\n10\n800\n1\n', '0\n', '795 + 10 = 805 > 800 nên quay về 0.'),
            hidden('100\n-10\n800\n5\n', '50\n', 20),
            hidden('5\n-10\n800\n1\n', '800\n', 20),
            hidden('0\n1\n10\n25\n', '3\n', 30),
            hidden('400\n0\n800\n100\n', '400\n', 30),
          ],
        }),
      ],
    },

    {
      order: 3,
      slug: 'pg-b03-dieu-kien-vong-lap-qua-vat-roi',
      title: 'Điều kiện & vòng lặp qua tương tác: vật thể rơi',
      summary:
        'Ôn `if` và `for` bằng một màn mưa vật thể: nhiều vật rơi xuống, chạm đáy thì quay lên từ đầu.',
      objectives: [
        'Dùng danh sách để quản lý nhiều vật cùng lúc',
        'Duyệt danh sách bằng `for` trong game loop',
        'Dùng `if` để xử lý vật chạm đáy màn hình',
        'Sinh vị trí và tốc độ ngẫu nhiên bằng `random`',
      ],
      difficulty: 3,
      status: 'REQUIRED',
      teacherNotes:
        'GHI CHÚ Module 1: buổi này chính là ví dụ "vật thể rơi" trong kế hoạch bài giảng. ' +
        'Học sinh thấy ngay vòng lặp và điều kiện có tác dụng gì.',
      blocks: [
        theory('Quản lý nhiều vật bằng danh sách', [
          'Một vật rơi thì dễ. Nhưng 20 vật thì không thể tạo 20 biến `x1, y1, x2, y2...`.',
          '',
          'Giải pháp là **danh sách các danh sách** — mỗi phần tử là một vật:',
          '',
          '```python',
          'import random',
          '',
          'vat_the = []',
          'for i in range(20):',
          '    x = random.randint(0, 780)',
          '    y = random.randint(-600, 0)      # bắt đầu ở phía trên màn hình',
          '    toc_do = random.randint(2, 6)',
          '    vat_the.append([x, y, toc_do])',
          '```',
          '',
          'Rồi trong game loop, duyệt qua toàn bộ danh sách:',
          '',
          '```python',
          'for vat in vat_the:',
          '    vat[1] += vat[2]            # y += toc_do  -> rơi xuống',
          '    if vat[1] > 600:            # chạm đáy',
          '        vat[1] = -20            # đưa lên trên lại',
          '        vat[0] = random.randint(0, 780)',
          '```',
          '',
          'Nhớ lại buổi 20 khoá Cơ Bản: `vat[0]` là x, `vat[1]` là y, `vat[2]` là tốc độ.',
        ], [
          'Danh sách các danh sách để quản lý nhiều vật',
          '`for` trong game loop cập nhật mọi vật mỗi khung hình',
          'Chạm đáy thì đưa lên đầu — vật được tái sử dụng thay vì tạo mới',
        ]),
        example('Mưa vật thể', 'Chỉ khoảng 30 dòng, nhưng đã là một hiệu ứng game thật.', [
          'import pygame',
          'import random',
          '',
          'pygame.init()',
          'RONG, CAO = 800, 600',
          'man_hinh = pygame.display.set_mode((RONG, CAO))',
          'pygame.display.set_caption("Mua vat the")',
          'dong_ho = pygame.time.Clock()',
          '',
          '# Tao 30 vat the o vi tri ngau nhien phia tren man hinh',
          'vat_the = []',
          'for i in range(30):',
          '    vat_the.append([',
          '        random.randint(0, RONG - 20),      # x',
          '        random.randint(-CAO, 0),           # y',
          '        random.randint(2, 7),              # toc do roi',
          '        random.randint(8, 20),             # kich thuoc',
          '    ])',
          '',
          'dang_chay = True',
          'while dang_chay:',
          '    for su_kien in pygame.event.get():',
          '        if su_kien.type == pygame.QUIT:',
          '            dang_chay = False',
          '',
          '    # --- CAP NHAT: moi vat roi xuong ---',
          '    for vat in vat_the:',
          '        vat[1] += vat[2]',
          '        if vat[1] > CAO:',
          '            vat[1] = random.randint(-100, -20)',
          '            vat[0] = random.randint(0, RONG - 20)',
          '',
          '    # --- VE ---',
          '    man_hinh.fill((15, 15, 35))',
          '    for vat in vat_the:',
          '        pygame.draw.circle(man_hinh, (100, 200, 255), (vat[0], vat[1]), vat[3])',
          '',
          '    pygame.display.flip()',
          '    dong_ho.tick(60)',
          '',
          'pygame.quit()',
        ], {
          output: '30 quả cầu xanh rơi từ trên xuống với tốc độ và kích thước khác nhau, rơi hết lại quay lên.',
          notes: [
            'Mỗi vật có tốc độ riêng nên trông tự nhiên hơn hẳn so với việc cho tất cả rơi cùng tốc độ.',
            'Vật bắt đầu ở y âm để chúng "trôi vào" màn hình chứ không xuất hiện đột ngột.',
            'Không hề tạo thêm vật mới — chỉ tái sử dụng 30 vật ban đầu.',
          ],
        }),
        playground('Sân chơi: mưa của em', [
          'Nâng cấp màn mưa:',
          '',
          '1. Cho mỗi vật một **màu ngẫu nhiên** (thêm phần tử thứ 5 vào danh sách)',
          '2. Cho vật rơi theo đường **chéo** thay vì thẳng đứng',
          '3. Thử đổi `draw.circle` thành `draw.rect` để có mưa hình vuông',
        ], [
          'import pygame',
          'import random',
          '',
          'pygame.init()',
          'RONG, CAO = 800, 600',
          'man_hinh = pygame.display.set_mode((RONG, CAO))',
          'dong_ho = pygame.time.Clock()',
          '',
          'vat_the = []',
          'for i in range(30):',
          '    vat_the.append([',
          '        random.randint(0, RONG),',
          '        random.randint(-CAO, 0),',
          '        random.randint(2, 7),',
          '        random.randint(8, 20),',
          '        # Them mau ngau nhien o day',
          '    ])',
          '',
          'dang_chay = True',
          'while dang_chay:',
          '    for su_kien in pygame.event.get():',
          '        if su_kien.type == pygame.QUIT:',
          '            dang_chay = False',
          '',
          '    for vat in vat_the:',
          '        vat[1] += vat[2]',
          '        if vat[1] > CAO:',
          '            vat[1] = -20',
          '            vat[0] = random.randint(0, RONG)',
          '',
          '    man_hinh.fill((15, 15, 35))',
          '    for vat in vat_the:',
          '        pygame.draw.circle(man_hinh, (100, 200, 255), (vat[0], vat[1]), vat[3])',
          '    pygame.display.flip()',
          '    dong_ho.tick(60)',
          '',
          'pygame.quit()',
        ], 'Màn mưa có màu ngẫu nhiên và chuyển động theo ý em.'),
        challenge({
          slug: 'p-pg-b03-dem-vat-cham-day',
          title: 'Đếm số vật chạm đáy',
          statement: [
            'Có `M` vật rơi. Màn hình cao `H`.',
            '',
            'Dòng đầu: ba số nguyên `M`, `H`, `N` (số khung hình cần mô phỏng).',
            '',
            '`M` dòng tiếp theo, mỗi dòng hai số nguyên `y` và `v` — vị trí ban đầu và tốc độ rơi.',
            '',
            'Mỗi khung hình, mọi vật đều cộng `v` vào `y`. Khi `y > H`, vật được đưa về `y = 0` ' +
              'và tính là **một lần chạm đáy**.',
            '',
            'In ra **một dòng** là tổng số lần chạm đáy của tất cả các vật sau `N` khung hình.',
          ].join('\n'),
          hints: [
            'Dùng một danh sách để lưu y của từng vật và một danh sách khác cho tốc độ.',
            'Vòng lặp ngoài chạy N khung hình, vòng lặp trong duyệt M vật.',
            'Mỗi lần đặt lại y = 0, cộng 1 vào biến đếm.',
          ],
          starterCode: [
            'm, h, n = map(int, input().split())',
            'y = []',
            'v = []',
            'for i in range(m):',
            '    a, b = map(int, input().split())',
            '    y.append(a)',
            '    v.append(b)',
            '',
            'dem = 0',
            '# Mô phỏng n khung hình',
          ].join('\n'),
          solutionCode: [
            'm, h, n = map(int, input().split())',
            'y = []',
            'v = []',
            'for i in range(m):',
            '    a, b = map(int, input().split())',
            '    y.append(a)',
            '    v.append(b)',
            '',
            'dem = 0',
            'for khung in range(n):',
            '    for i in range(m):',
            '        y[i] += v[i]',
            '        if y[i] > h:',
            '            y[i] = 0',
            '            dem += 1',
            '',
            'print(dem)',
          ].join('\n'),
          tier: 'THU_THACH',
          judgeMode: 'IO_MATCH',
          tests: [
            sample(
              '2 100 30\n0 10\n50 20\n',
              '5\n',
              'Vật 1 chạm đáy 2 lần, vật 2 chạm 3 lần trong 30 khung hình.',
            ),
            sample('1 10 1\n0 5\n', '0\n', '5 chưa vượt quá 10 nên chưa chạm đáy.'),
            hidden('1 10 3\n0 5\n', '1\n', 25),
            hidden('3 100 10\n0 50\n0 50\n0 50\n', '15\n', 25),
            hidden('1 1000 5\n0 1\n', '0\n', 25),
            hidden('2 50 100\n0 25\n0 10\n', '69\n', 25),
          ],
        }),
      ],
    },

    {
      order: 4,
      slug: 'pg-b04-ham-danh-sach-qua-sprite-di-chuyen',
      title: 'Hàm & danh sách qua game: sprite di chuyển trái/phải',
      summary:
        'Buổi khép Module 1: em điều khiển được một nhân vật bằng phím mũi tên, và code đã được ' +
        'tổ chức gọn gàng bằng hàm.',
      objectives: [
        'Đọc trạng thái bàn phím bằng `pygame.key.get_pressed()`',
        'Điều khiển nhân vật di chuyển trái/phải',
        'Tách chương trình thành các hàm `cap_nhat()` và `ve()`',
        'Giới hạn nhân vật không đi ra khỏi màn hình',
      ],
      difficulty: 3,
      status: 'REQUIRED',
      teacherNotes:
        'GHI CHÚ Module 1: đây là ví dụ "di chuyển sprite trái/phải" của kế hoạch bài giảng. ' +
        'Kết thúc Module 1 học sinh đã điều khiển được nhân vật.',
      blocks: [
        theory('Hai cách đọc bàn phím', [
          'Pygame có hai cách nghe bàn phím, dùng cho hai mục đích khác nhau:',
          '',
          '**Cách 1 — sự kiện `KEYDOWN`:** kích hoạt **đúng một lần** lúc phím vừa được bấm xuống. ' +
            'Dùng cho hành động rời rạc: nhảy, bắn, mở menu.',
          '',
          '```python',
          'for su_kien in pygame.event.get():',
          '    if su_kien.type == pygame.KEYDOWN:',
          '        if su_kien.key == pygame.K_SPACE:',
          '            ban_dan()',
          '```',
          '',
          '**Cách 2 — `get_pressed()`:** cho biết phím nào đang **được giữ** ngay lúc này. ' +
            'Dùng cho chuyển động liên tục.',
          '',
          '```python',
          'phim = pygame.key.get_pressed()',
          'if phim[pygame.K_LEFT]:',
          '    x -= toc_do',
          'if phim[pygame.K_RIGHT]:',
          '    x += toc_do',
          '```',
          '',
          '💡 Dùng nhầm cách 1 cho di chuyển sẽ khiến nhân vật giật cục — phải bấm liên tục mới đi được.',
        ], [
          '`KEYDOWN` cho hành động một lần: nhảy, bắn',
          '`get_pressed()` cho chuyển động liên tục',
          'Dùng hai `if` riêng (không `elif`) để đi chéo được',
        ]),
        theory('Tách code thành hàm', [
          'Game loop dài dần sẽ rối. Cách tổ chức chuẩn là tách thành hàm — đúng như bài học ' +
            'ở buổi 24 khoá Cơ Bản:',
          '',
          '```python',
          'def xu_ly_su_kien():',
          '    for su_kien in pygame.event.get():',
          '        if su_kien.type == pygame.QUIT:',
          '            return False',
          '    return True',
          '',
          'def cap_nhat(nhan_vat):',
          '    phim = pygame.key.get_pressed()',
          '    if phim[pygame.K_LEFT]:',
          '        nhan_vat["x"] -= nhan_vat["toc_do"]',
          '',
          'def ve(man_hinh, nhan_vat):',
          '    man_hinh.fill(DEN)',
          '    pygame.draw.rect(man_hinh, XANH, (...))',
          '    pygame.display.flip()',
          '```',
          '',
          'Game loop khi đó chỉ còn ba dòng — đọc là hiểu ngay:',
          '',
          '```python',
          'while dang_chay:',
          '    dang_chay = xu_ly_su_kien()',
          '    cap_nhat(nhan_vat)',
          '    ve(man_hinh, nhan_vat)',
          '    dong_ho.tick(60)',
          '```',
          '',
          'Dùng **từ điển** để gom thông tin nhân vật cũng giúp code gọn hơn nhiều so với ' +
            'các biến rời rạc.',
        ], [
          'Tách thành `xu_ly_su_kien()`, `cap_nhat()`, `ve()`',
          'Game loop chính chỉ nên dài vài dòng',
          'Từ điển gom thông tin nhân vật lại một chỗ',
        ]),
        example('Nhân vật điều khiển được', 'Code đã tổ chức đúng chuẩn — đây là bộ khung em dùng cả khoá học.', [
          'import pygame',
          '',
          'pygame.init()',
          'RONG, CAO = 800, 600',
          'man_hinh = pygame.display.set_mode((RONG, CAO))',
          'pygame.display.set_caption("Dieu khien nhan vat")',
          'dong_ho = pygame.time.Clock()',
          '',
          'DEN = (20, 20, 35)',
          'XANH = (52, 152, 219)',
          'XAM = (60, 60, 80)',
          '',
          'nhan_vat = {"x": 400, "y": 500, "rong": 60, "cao": 20, "toc_do": 7}',
          '',
          '',
          'def xu_ly_su_kien():',
          '    for su_kien in pygame.event.get():',
          '        if su_kien.type == pygame.QUIT:',
          '            return False',
          '    return True',
          '',
          '',
          'def cap_nhat(nv):',
          '    phim = pygame.key.get_pressed()',
          '    if phim[pygame.K_LEFT] or phim[pygame.K_a]:',
          '        nv["x"] -= nv["toc_do"]',
          '    if phim[pygame.K_RIGHT] or phim[pygame.K_d]:',
          '        nv["x"] += nv["toc_do"]',
          '',
          '    # Gioi han trong man hinh',
          '    if nv["x"] < 0:',
          '        nv["x"] = 0',
          '    if nv["x"] > RONG - nv["rong"]:',
          '        nv["x"] = RONG - nv["rong"]',
          '',
          '',
          'def ve(mh, nv):',
          '    mh.fill(DEN)',
          '    pygame.draw.rect(mh, XAM, (0, 560, RONG, 40))',
          '    pygame.draw.rect(mh, XANH, (nv["x"], nv["y"], nv["rong"], nv["cao"]))',
          '    pygame.display.flip()',
          '',
          '',
          'dang_chay = True',
          'while dang_chay:',
          '    dang_chay = xu_ly_su_kien()',
          '    cap_nhat(nhan_vat)',
          '    ve(man_hinh, nhan_vat)',
          '    dong_ho.tick(60)',
          '',
          'pygame.quit()',
        ], {
          output: 'Một thanh xanh di chuyển trái/phải theo phím mũi tên hoặc A/D, không đi ra khỏi màn hình.',
          notes: [
            'Hỗ trợ cả phím mũi tên lẫn A/D — chi tiết nhỏ nhưng người chơi rất thích.',
            'Phần giới hạn màn hình dùng `RONG - nv["rong"]` chứ không phải `RONG`, ' +
              'vì toạ độ x là mép TRÁI của hình.',
            'Bộ khung ba hàm này sẽ được dùng lại suốt khoá học.',
          ],
        }),
        playground('Sân chơi: di chuyển bốn hướng', [
          'Mở rộng nhân vật để đi được cả bốn hướng bằng phím mũi tên.',
          '',
          'Nhớ dùng bốn câu `if` riêng biệt (không dùng `elif`) — như vậy bấm hai phím cùng lúc ' +
            'sẽ đi được theo đường chéo.',
        ], [
          'import pygame',
          '',
          'pygame.init()',
          'RONG, CAO = 800, 600',
          'man_hinh = pygame.display.set_mode((RONG, CAO))',
          'dong_ho = pygame.time.Clock()',
          '',
          'nv = {"x": 400, "y": 300, "kich_thuoc": 40, "toc_do": 6}',
          '',
          'dang_chay = True',
          'while dang_chay:',
          '    for su_kien in pygame.event.get():',
          '        if su_kien.type == pygame.QUIT:',
          '            dang_chay = False',
          '',
          '    phim = pygame.key.get_pressed()',
          '    if phim[pygame.K_LEFT]:',
          '        nv["x"] -= nv["toc_do"]',
          '    if phim[pygame.K_RIGHT]:',
          '        nv["x"] += nv["toc_do"]',
          '    # Them phim len va xuong o day',
          '',
          '    man_hinh.fill((20, 20, 35))',
          '    pygame.draw.rect(man_hinh, (46, 204, 113),',
          '                     (nv["x"], nv["y"], nv["kich_thuoc"], nv["kich_thuoc"]))',
          '    pygame.display.flip()',
          '    dong_ho.tick(60)',
          '',
          'pygame.quit()',
        ], 'Nhân vật đi được bốn hướng, đi chéo được, và không ra khỏi màn hình.'),
        challenge({
          slug: 'p-pg-b04-gioi-han-man-hinh',
          title: 'Giới hạn nhân vật trong màn hình',
          statement: [
            'Nhân vật rộng `w` đứng ở toạ độ `x` trên màn hình rộng `W`. Toạ độ `x` là **mép trái** ' +
              'của nhân vật, nên nhân vật hợp lệ khi `0 <= x <= W - w`.',
            '',
            'Đọc **một dòng** chứa ba số nguyên `x`, `w`, `W`, rồi đọc dòng thứ hai chứa số nguyên `dx` ' +
              '— khoảng dịch chuyển.',
            '',
            'In ra **một dòng** là toạ độ `x` sau khi dịch chuyển và đã được kẹp lại trong màn hình.',
            '',
            'Ví dụ: `x=790, w=60, W=800, dx=20` → sau dịch là 810, kẹp lại còn `740`.',
          ].join('\n'),
          hints: [
            'Cộng dx vào x trước.',
            'Nếu x < 0 thì đặt x = 0.',
            'Nếu x > W - w thì đặt x = W - w.',
          ],
          starterCode: [
            'x, w, W = map(int, input().split())',
            'dx = int(input())',
            '',
            '# Dịch chuyển rồi kẹp lại trong màn hình',
          ].join('\n'),
          solutionCode: [
            'x, w, W = map(int, input().split())',
            'dx = int(input())',
            '',
            'x += dx',
            'if x < 0:',
            '    x = 0',
            'if x > W - w:',
            '    x = W - w',
            '',
            'print(x)',
          ].join('\n'),
          tier: 'CO_BAN',
          judgeMode: 'IO_MATCH',
          tests: [
            sample('790 60 800\n20\n', '740\n', '790 + 20 = 810, vượt quá 800 - 60 = 740 nên kẹp về 740.'),
            sample('400 60 800\n-50\n', '350\n', 'Nằm trong khoảng hợp lệ nên giữ nguyên kết quả.'),
            hidden('10 60 800\n-50\n', '0\n', 20),
            hidden('0 40 800\n0\n', '0\n', 20),
            hidden('760 40 800\n100\n', '760\n', 30),
            hidden('300 800 800\n50\n', '0\n', 30),
          ],
        }),
        projectBlock(
          'Kết Module 1: nhân vật của em',
          [
            'Ghép mọi thứ của bốn buổi đầu thành một chương trình nhỏ:',
            '',
            '- Một nhân vật điều khiển được bằng bàn phím',
            '- Một vài vật thể rơi từ trên xuống',
            '- Nhân vật không đi ra khỏi màn hình',
            '- Code tổ chức bằng hàm `xu_ly_su_kien()`, `cap_nhat()`, `ve()`',
            '',
            'Chưa cần va chạm — đó là nội dung Module 3.',
            '',
            'Nộp tệp `.py` để thầy cô xem và góp ý.',
          ],
          'CUSTOM',
          [
            'Cửa sổ game chạy được và đóng được',
            'Nhân vật di chuyển theo bàn phím, có giới hạn màn hình',
            'Có ít nhất 5 vật thể rơi',
            'Code được tách thành hàm rõ ràng',
          ],
        ),
      ],
    },
  ],
};

export const pygameModule2: ModuleSpec = {
  slug: 'cua-so-ve-su-kien-sprite',
  title: 'Module 2 · Cửa sổ, Vẽ, Sự kiện, Sprite',
  description:
    'Đi sâu vào bốn trụ cột kỹ thuật của Pygame. Kết thúc module, em điều khiển được một paddle ' +
    'hoặc xe tăng bằng lớp Sprite chuẩn.',
  lessons: [
    {
      order: 5,
      slug: 'pg-b05-cua-so-game-loop-fps',
      title: 'Cửa sổ game, Game loop, FPS & hệ toạ độ',
      summary:
        'Hiểu sâu về khung hình mỗi giây, độ trễ giữa các khung, và cách làm game chạy đều trên mọi máy.',
      objectives: [
        'Giải thích được FPS và ảnh hưởng của nó tới trải nghiệm chơi',
        'Dùng `Clock.tick()` để giới hạn tốc độ khung hình',
        'Hiểu khái niệm delta time và vì sao nó cần thiết',
        'Đặt chế độ toàn màn hình và đổi kích thước cửa sổ',
      ],
      difficulty: 3,
      status: 'REQUIRED',
      teacherNotes: 'Delta time là khái niệm khó — chỉ giới thiệu ở mức nhận biết, chưa bắt buộc áp dụng.',
      blocks: [
        theory('FPS — khung hình mỗi giây', [
          '**FPS** (frames per second) là số lần game vẽ lại màn hình trong một giây.',
          '',
          '| FPS | Cảm giác |',
          '|---|---|',
          '| 15 | Giật, khó chơi |',
          '| 30 | Chấp nhận được |',
          '| **60** | Mượt — tiêu chuẩn của hầu hết game |',
          '| 120+ | Rất mượt, cần màn hình hỗ trợ |',
          '',
          '`dong_ho.tick(60)` bảo Pygame: *"nếu vòng lặp này chạy xong sớm, hãy nghỉ cho đủ 1/60 giây rồi mới đi tiếp"*.',
          '',
          'Không có nó, game sẽ chạy nhanh hết mức máy cho phép — trên máy mạnh nhân vật bay vèo vèo, ' +
            'trên máy yếu thì bò. Cùng một đoạn code, hai trải nghiệm hoàn toàn khác nhau.',
          '',
          '`dong_ho.get_fps()` cho biết FPS thực tế đang đạt được — rất hữu ích khi gỡ lỗi hiệu năng.',
        ], [
          '60 FPS là tiêu chuẩn',
          '`tick(60)` giữ tốc độ đồng đều trên mọi máy',
          '`get_fps()` để đo FPS thực tế',
        ]),
        theory('Delta time — chuyển động độc lập với FPS', [
          'Ngay cả khi đặt `tick(60)`, đôi lúc máy vẫn không kịp và FPS tụt xuống. Khi đó nhân vật ' +
            'sẽ đi chậm lại — không công bằng cho người chơi.',
          '',
          'Cách xử lý chuyên nghiệp là **delta time**: đo xem khung hình vừa rồi mất bao nhiêu giây, ' +
            'rồi nhân vào quãng đường:',
          '',
          '```python',
          'dt = dong_ho.tick(60) / 1000    # thời gian khung vừa rồi, đơn vị giây',
          '',
          '# Thay vì: x += 5           (5 điểm ảnh mỗi KHUNG HÌNH)',
          'x += 300 * dt              # 300 điểm ảnh mỗi GIÂY',
          '```',
          '',
          'Với cách này, dù FPS là 60 hay 30, nhân vật vẫn đi đúng 300 điểm ảnh mỗi giây.',
          '',
          '💡 Trong khoá học này em vẫn dùng cách đơn giản (cộng thẳng vào toạ độ) vì dễ hiểu hơn. ' +
            'Nhưng hãy nhớ khái niệm này — khi làm dự án lớn hơn em sẽ cần đến nó.',
        ], [
          'Delta time = thời gian của khung hình vừa rồi',
          'Nhân tốc độ với dt để chuyển động không phụ thuộc FPS',
          'Khoá học dùng cách đơn giản; delta time là kiến thức mở rộng',
        ], { tier: 'NANG_CAO' }),
        example('Đo và hiển thị FPS', 'Một công cụ gỡ lỗi em sẽ dùng suốt khoá học.', [
          'import pygame',
          '',
          'pygame.init()',
          'RONG, CAO = 800, 600',
          'man_hinh = pygame.display.set_mode((RONG, CAO))',
          'pygame.display.set_caption("Do FPS")',
          'dong_ho = pygame.time.Clock()',
          'phong_chu = pygame.font.SysFont("consolas", 22)',
          '',
          'gioi_han_fps = 60',
          'x = 0',
          '',
          'dang_chay = True',
          'while dang_chay:',
          '    for su_kien in pygame.event.get():',
          '        if su_kien.type == pygame.QUIT:',
          '            dang_chay = False',
          '        elif su_kien.type == pygame.KEYDOWN:',
          '            if su_kien.key == pygame.K_1:',
          '                gioi_han_fps = 15',
          '            elif su_kien.key == pygame.K_2:',
          '                gioi_han_fps = 30',
          '            elif su_kien.key == pygame.K_3:',
          '                gioi_han_fps = 60',
          '',
          '    x = (x + 5) % RONG',
          '',
          '    man_hinh.fill((20, 20, 35))',
          '    pygame.draw.circle(man_hinh, (241, 196, 15), (x, 300), 20)',
          '',
          '    chu = phong_chu.render(',
          '        f"FPS thuc te: {dong_ho.get_fps():.1f}  |  Gioi han: {gioi_han_fps}  |  Bam 1/2/3",',
          '        True, (255, 255, 255))',
          '    man_hinh.blit(chu, (10, 10))',
          '',
          '    pygame.display.flip()',
          '    dong_ho.tick(gioi_han_fps)',
          '',
          'pygame.quit()',
        ], {
          output: 'Quả cầu vàng chạy ngang màn hình, kèm dòng chữ hiển thị FPS. Bấm 1/2/3 để đổi giới hạn FPS.',
          notes: [
            'Bấm phím 1 (15 FPS) và thấy ngay quả cầu vừa giật vừa chậm — vì mỗi giây chỉ dịch 15×5 = 75 điểm.',
            'Đó chính là lý do cần delta time trong game thật.',
            '`phong_chu.render()` tạo ảnh chữ, `man_hinh.blit()` dán ảnh đó lên màn hình.',
          ],
        }),
        playground('Sân chơi: cảm nhận FPS', [
          'Chạy đoạn code ở trên và bấm lần lượt 1, 2, 3.',
          '',
          'Sau đó thử **xoá hẳn dòng `dong_ho.tick(...)`** và chạy lại. Quan sát FPS thực tế nhảy lên bao nhiêu.',
          '',
          'Đây là bài học trực quan nhất về vì sao phải giới hạn FPS.',
        ], [
          'import pygame',
          '',
          'pygame.init()',
          'man_hinh = pygame.display.set_mode((800, 600))',
          'dong_ho = pygame.time.Clock()',
          'phong_chu = pygame.font.SysFont("consolas", 22)',
          '',
          'x = 0',
          'dang_chay = True',
          'while dang_chay:',
          '    for su_kien in pygame.event.get():',
          '        if su_kien.type == pygame.QUIT:',
          '            dang_chay = False',
          '',
          '    x = (x + 5) % 800',
          '',
          '    man_hinh.fill((20, 20, 35))',
          '    pygame.draw.circle(man_hinh, (241, 196, 15), (x, 300), 20)',
          '    chu = phong_chu.render(f"FPS: {dong_ho.get_fps():.0f}", True, (255, 255, 255))',
          '    man_hinh.blit(chu, (10, 10))',
          '    pygame.display.flip()',
          '',
          '    dong_ho.tick(60)   # thu xoa dong nay',
          '',
          'pygame.quit()',
        ], 'Giải thích được vì sao game không giới hạn FPS lại chạy khác nhau trên các máy khác nhau.'),
        challenge({
          slug: 'p-pg-b05-quang-duong-theo-fps',
          title: 'Quãng đường theo FPS',
          statement: [
            'Một vật di chuyển `v` điểm ảnh **mỗi khung hình**. Game chạy ở `F` khung hình mỗi giây ' +
              'trong `T` giây.',
            '',
            'Đọc **ba số nguyên** trên ba dòng: `v`, `F`, `T`.',
            '',
            'In ra **hai dòng**:',
            '',
            '```',
            'Quang duong: <s>',
            'Toc do moi giay: <vs>',
            '```',
            '',
            'Trong đó `<s>` là tổng quãng đường sau `T` giây, `<vs>` là số điểm ảnh đi được mỗi giây. ' +
              'Cả hai đều là số nguyên.',
          ].join('\n'),
          hints: [
            'Số khung hình trong T giây là F × T.',
            'Quãng đường = v × F × T.',
            'Tốc độ mỗi giây = v × F.',
          ],
          starterCode: ['v = int(input())', 'f = int(input())', 't = int(input())', '', '# Tính và in'].join('\n'),
          solutionCode: [
            'v = int(input())',
            'f = int(input())',
            't = int(input())',
            'print(f"Quang duong: {v * f * t}")',
            'print(f"Toc do moi giay: {v * f}")',
          ].join('\n'),
          tier: 'CO_BAN',
          judgeMode: 'IO_MATCH',
          tests: [
            sample('5\n60\n2\n', 'Quang duong: 600\nToc do moi giay: 300\n', '5 × 60 = 300 điểm/giây, trong 2 giây là 600.'),
            sample('5\n30\n2\n', 'Quang duong: 300\nToc do moi giay: 150\n', 'Cùng tốc độ mỗi khung nhưng FPS thấp hơn nên đi được ít hơn.'),
            hidden('1\n60\n1\n', 'Quang duong: 60\nToc do moi giay: 60\n', 25),
            hidden('10\n15\n4\n', 'Quang duong: 600\nToc do moi giay: 150\n', 25),
            hidden('0\n60\n10\n', 'Quang duong: 0\nToc do moi giay: 0\n', 25),
            hidden('3\n120\n5\n', 'Quang duong: 1800\nToc do moi giay: 360\n', 25),
          ],
        }),
      ],
    },

    {
      order: 6,
      slug: 'pg-b06-ve-hinh-ket-hop-tai-anh',
      title: 'Vẽ hình kết hợp tải hình ảnh',
      summary:
        'Hai kỹ năng gộp trong một buổi: vẽ hình bằng lệnh, và tải ảnh có sẵn từ tệp. ' +
        'Từ buổi này game của em có thể trông đẹp thật sự.',
      objectives: [
        'Vẽ đầy đủ các hình cơ bản: chữ nhật, tròn, elip, đa giác, đường',
        'Tải ảnh từ tệp bằng `pygame.image.load()`',
        'Dán ảnh lên màn hình bằng `blit()`',
        'Thay đổi kích thước và xoay ảnh',
      ],
      difficulty: 3,
      status: 'REQUIRED',
      teacherNotes:
        'GHI CHÚ Module 2: kế hoạch bài giảng yêu cầu KẾT HỢP tải hình ảnh với vẽ hình ngay từ sớm, ' +
        'thay vì tách thành hai buổi riêng. Học sinh cần thấy game có thể đẹp ngay.',
      blocks: [
        theory('Bộ lệnh vẽ đầy đủ', [
          '```python',
          '# Chữ nhật — do_day=0 nghĩa là tô đặc',
          'pygame.draw.rect(mh, MAU, (x, y, rong, cao), do_day)',
          '',
          '# Chữ nhật bo góc',
          'pygame.draw.rect(mh, MAU, (x, y, rong, cao), 0, border_radius=12)',
          '',
          '# Hình tròn',
          'pygame.draw.circle(mh, MAU, (tam_x, tam_y), ban_kinh, do_day)',
          '',
          '# Elip — vẽ vừa khít trong khung chữ nhật',
          'pygame.draw.ellipse(mh, MAU, (x, y, rong, cao))',
          '',
          '# Đa giác — danh sách các đỉnh',
          'pygame.draw.polygon(mh, MAU, [(100, 50), (150, 150), (50, 150)])',
          '',
          '# Đường thẳng',
          'pygame.draw.line(mh, MAU, (x1, y1), (x2, y2), do_day)',
          '```',
          '',
          '💡 Tham số `do_day`: để `0` (hoặc bỏ qua) thì hình được **tô đặc**; số dương thì chỉ vẽ **viền** ' +
            'với độ dày đó.',
        ], [
          '`do_day = 0` tô đặc, `do_day > 0` chỉ vẽ viền',
          '`border_radius` để bo góc chữ nhật',
          'Đa giác nhận một danh sách các đỉnh',
        ]),
        theory('Tải và dán ảnh', [
          '```python',
          '# Tai anh (dat gan lenh init, KHONG dat trong game loop)',
          'anh_tau = pygame.image.load("tau.png").convert_alpha()',
          '',
          '# Dan anh len man hinh',
          'man_hinh.blit(anh_tau, (x, y))',
          '```',
          '',
          '**Ba điều bắt buộc nhớ:**',
          '',
          '1. **`.convert_alpha()`** — cho ảnh PNG có nền trong suốt. Với ảnh không cần trong suốt ' +
            'thì dùng `.convert()`. Thiếu bước này, game chạy chậm hơn nhiều lần.',
          '',
          '2. **Tải ảnh MỘT LẦN, ngoài game loop.** Tải ảnh trong vòng lặp nghĩa là đọc tệp 60 lần mỗi ' +
            'giây — game sẽ giật ngay.',
          '',
          '3. **`blit(anh, (x, y))`** — `(x, y)` là góc **trên bên trái** của ảnh, không phải tâm.',
          '',
          '**Chỉnh sửa ảnh:**',
          '',
          '```python',
          'anh_nho = pygame.transform.scale(anh_tau, (64, 64))',
          'anh_xoay = pygame.transform.rotate(anh_tau, 45)      # 45 độ ngược chiều kim đồng hồ',
          'anh_lat = pygame.transform.flip(anh_tau, True, False) # lật ngang',
          '```',
        ], [
          'Luôn dùng `.convert_alpha()` cho PNG trong suốt',
          'Tải ảnh MỘT LẦN, ngoài game loop',
          '`blit` dán theo góc trên bên trái',
          '`transform.scale` / `rotate` / `flip` để chỉnh ảnh',
        ]),
        example('Vẽ hình và dùng ảnh trong cùng một game', 'Có xử lý trường hợp thiếu tệp ảnh — dùng hình vẽ thay thế.', [
          'import pygame',
          '',
          'pygame.init()',
          'RONG, CAO = 800, 600',
          'man_hinh = pygame.display.set_mode((RONG, CAO))',
          'pygame.display.set_caption("Ve hinh + Anh")',
          'dong_ho = pygame.time.Clock()',
          '',
          'TRANG = (255, 255, 255)',
          'XANH_TROI = (52, 152, 219)',
          'VANG = (241, 196, 15)',
          'XANH_LA = (39, 174, 96)',
          '',
          '# Tai anh MOT LAN. Neu khong co tep, dung hinh ve thay the.',
          'try:',
          '    anh_tau = pygame.image.load("tau.png").convert_alpha()',
          '    anh_tau = pygame.transform.scale(anh_tau, (64, 64))',
          '    co_anh = True',
          'except (pygame.error, FileNotFoundError):',
          '    co_anh = False',
          '    print("Khong tim thay tau.png - dung hinh ve thay the")',
          '',
          'goc = 0',
          '',
          'dang_chay = True',
          'while dang_chay:',
          '    for su_kien in pygame.event.get():',
          '        if su_kien.type == pygame.QUIT:',
          '            dang_chay = False',
          '',
          '    goc = (goc + 2) % 360',
          '',
          '    man_hinh.fill((25, 25, 45))',
          '',
          '    # --- Ve khung canh bang lenh ve ---',
          '    pygame.draw.rect(man_hinh, XANH_LA, (0, 520, RONG, 80))          # mat dat',
          '    pygame.draw.circle(man_hinh, VANG, (700, 100), 50)               # mat troi',
          '    pygame.draw.polygon(man_hinh, (127, 140, 141),',
          '                        [(150, 520), (250, 300), (350, 520)])        # ngon nui',
          '    pygame.draw.rect(man_hinh, XANH_TROI, (400, 420, 120, 100), 0, border_radius=10)',
          '    pygame.draw.line(man_hinh, TRANG, (0, 520), (RONG, 520), 2)',
          '',
          '    # --- Dan anh (hoac hinh ve thay the) ---',
          '    if co_anh:',
          '        anh_xoay = pygame.transform.rotate(anh_tau, goc)',
          '        khung = anh_xoay.get_rect(center=(400, 200))',
          '        man_hinh.blit(anh_xoay, khung)',
          '    else:',
          '        pygame.draw.circle(man_hinh, (231, 76, 60), (400, 200), 32)',
          '        pygame.draw.circle(man_hinh, TRANG, (400, 200), 32, 3)',
          '',
          '    pygame.display.flip()',
          '    dong_ho.tick(60)',
          '',
          'pygame.quit()',
        ], {
          output: 'Một khung cảnh gồm mặt đất, mặt trời, ngọn núi và ngôi nhà, với một vật thể xoay tròn ở giữa.',
          notes: [
            'Khối `try/except` (buổi 27 khoá Cơ Bản) giúp game vẫn chạy khi thiếu tệp ảnh — rất quan trọng khi nộp bài.',
            '`anh_xoay.get_rect(center=(400, 200))` giúp ảnh xoay quanh TÂM thay vì quanh góc trên trái.',
            'Ảnh xoay thay đổi kích thước khung, nên phải lấy lại `get_rect` sau mỗi lần xoay.',
          ],
        }),
        playground('Sân chơi: bức tranh của em', [
          'Vẽ một khung cảnh bằng ít nhất bốn loại hình khác nhau: chữ nhật, tròn, đa giác và đường thẳng.',
          '',
          'Gợi ý đề tài: ngôi nhà, con robot, phong cảnh Đà Lạt, khuôn mặt cười.',
          '',
          'Nhớ: hình vẽ sau sẽ đè lên hình vẽ trước.',
        ], [
          'import pygame',
          '',
          'pygame.init()',
          'man_hinh = pygame.display.set_mode((800, 600))',
          'dong_ho = pygame.time.Clock()',
          '',
          'dang_chay = True',
          'while dang_chay:',
          '    for su_kien in pygame.event.get():',
          '        if su_kien.type == pygame.QUIT:',
          '            dang_chay = False',
          '',
          '    man_hinh.fill((135, 206, 235))   # nen troi',
          '',
          '    # Ve buc tranh cua em o day',
          '    pygame.draw.rect(man_hinh, (39, 174, 96), (0, 450, 800, 150))',
          '',
          '    pygame.display.flip()',
          '    dong_ho.tick(60)',
          '',
          'pygame.quit()',
        ], 'Bức tranh dùng ít nhất bốn loại hình vẽ khác nhau.'),
        challenge({
          slug: 'p-pg-b06-vi-tri-can-giua-anh',
          title: 'Căn giữa ảnh trên màn hình',
          statement: [
            '`blit()` dán ảnh theo **góc trên bên trái**, nhưng ta thường muốn ảnh nằm **giữa** một vị trí.',
            '',
            'Đọc **bốn số nguyên** trên bốn dòng: `cx`, `cy` (toạ độ tâm mong muốn), ' +
              '`w`, `h` (chiều rộng và cao của ảnh).',
            '',
            'In ra **một dòng**: `<x> <y>` là toạ độ góc trên bên trái cần truyền cho `blit()`.',
            '',
            'Kết quả là **số nguyên** — dùng phép chia lấy nguyên `//`.',
          ].join('\n'),
          hints: [
            'x = cx - w // 2.',
            'y = cy - h // 2.',
            'In hai số trên cùng một dòng, cách nhau một dấu cách.',
          ],
          starterCode: [
            'cx = int(input())',
            'cy = int(input())',
            'w = int(input())',
            'h = int(input())',
            '',
            '# Tính góc trên bên trái',
          ].join('\n'),
          solutionCode: [
            'cx = int(input())',
            'cy = int(input())',
            'w = int(input())',
            'h = int(input())',
            'print(f"{cx - w // 2} {cy - h // 2}")',
          ].join('\n'),
          tier: 'CO_BAN',
          judgeMode: 'IO_MATCH',
          tests: [
            sample('400\n300\n64\n64\n', '368 268\n', '400 - 32 = 368, 300 - 32 = 268.'),
            sample('0\n0\n10\n20\n', '-5 -10\n', 'Toạ độ âm là hợp lệ — ảnh sẽ bị cắt ở mép.'),
            hidden('100\n100\n0\n0\n', '100 100\n', 25),
            hidden('800\n600\n100\n50\n', '750 575\n', 25),
            hidden('50\n50\n101\n101\n', '0 0\n', 25),
            hidden('400\n300\n1\n1\n', '400 300\n', 25),
          ],
        }),
      ],
    },

    {
      order: 7,
      slug: 'pg-b07-xu-ly-su-kien-ban-phim-chuot',
      title: 'Xử lý sự kiện: bàn phím & chuột',
      summary:
        'Nghe đầy đủ mọi thứ người chơi làm: bấm phím, thả phím, di chuột, bấm chuột. ' +
        'Đây là nền tảng của mọi tương tác.',
      objectives: [
        'Phân biệt `KEYDOWN`, `KEYUP` và `key.get_pressed()`',
        'Lấy vị trí chuột và xử lý sự kiện bấm chuột',
        'Kiểm tra chuột có nằm trong một vùng hình chữ nhật không',
        'Làm một nút bấm đơn giản',
      ],
      difficulty: 3,
      status: 'REQUIRED',
      teacherNotes: 'Phần nút bấm ở buổi này sẽ được dùng lại khi làm Menu ở buổi 15.',
      blocks: [
        theory('Các loại sự kiện', [
          '| Sự kiện | Xảy ra khi | Dữ liệu kèm theo |',
          '|---|---|---|',
          '| `QUIT` | Bấm nút X | — |',
          '| `KEYDOWN` | Phím vừa bấm xuống | `.key` |',
          '| `KEYUP` | Phím vừa thả ra | `.key` |',
          '| `MOUSEBUTTONDOWN` | Vừa bấm chuột | `.pos`, `.button` |',
          '| `MOUSEBUTTONUP` | Vừa thả chuột | `.pos`, `.button` |',
          '| `MOUSEMOTION` | Chuột di chuyển | `.pos`, `.rel` |',
          '',
          '```python',
          'for su_kien in pygame.event.get():',
          '    if su_kien.type == pygame.QUIT:',
          '        dang_chay = False',
          '',
          '    elif su_kien.type == pygame.KEYDOWN:',
          '        if su_kien.key == pygame.K_SPACE:',
          '            ban_dan()',
          '        elif su_kien.key == pygame.K_ESCAPE:',
          '            dang_chay = False',
          '',
          '    elif su_kien.type == pygame.MOUSEBUTTONDOWN:',
          '        if su_kien.button == 1:              # 1 = chuột trái',
          '            x, y = su_kien.pos',
          '            print(f"Bam chuot tai ({x}, {y})")',
          '```',
          '',
          'Nút chuột: `1` trái, `2` giữa, `3` phải.',
        ], [
          '`KEYDOWN` bắt lúc bấm, `KEYUP` bắt lúc thả',
          '`su_kien.pos` cho vị trí chuột lúc bấm',
          'Nút chuột: 1 = trái, 3 = phải',
        ]),
        theory('Rect — công cụ kiểm tra vùng', [
          '`pygame.Rect` là một hình chữ nhật có sẵn nhiều tiện ích. Nó là nền tảng của cả va chạm ' +
            '(buổi 12) lẫn nút bấm.',
          '',
          '```python',
          'nut = pygame.Rect(300, 250, 200, 60)     # x, y, rộng, cao',
          '',
          '# Kiểm tra một điểm có nằm trong Rect không',
          'vi_tri_chuot = pygame.mouse.get_pos()',
          'if nut.collidepoint(vi_tri_chuot):',
          '    print("Chuot dang o tren nut")',
          '```',
          '',
          'Rect có nhiều thuộc tính tiện dụng, đọc và **gán được**:',
          '',
          '```python',
          'nut.centerx, nut.centery    # tâm',
          'nut.left, nut.right         # mép trái, mép phải',
          'nut.top, nut.bottom         # mép trên, mép dưới',
          'nut.center = (400, 300)     # gán để DI CHUYỂN cả hình',
          '```',
          '',
          'Gán `nut.center = (400, 300)` sẽ tự tính lại `x` và `y` — rất tiện khi căn giữa.',
        ], [
          '`Rect(x, y, rong, cao)`',
          '`.collidepoint(vi_tri)` kiểm tra một điểm có nằm trong không',
          'Gán `.center`, `.left`... để di chuyển cả hình',
        ]),
        example('Nút bấm biết đổi màu', 'Kết hợp Rect, chuột và sự kiện — chính là một nút bấm thật.', [
          'import pygame',
          '',
          'pygame.init()',
          'man_hinh = pygame.display.set_mode((800, 600))',
          'pygame.display.set_caption("Nut bam")',
          'dong_ho = pygame.time.Clock()',
          'phong_chu = pygame.font.SysFont("arial", 28, bold=True)',
          '',
          'XANH = (52, 152, 219)',
          'XANH_SANG = (93, 173, 226)',
          'TRANG = (255, 255, 255)',
          '',
          'nut = pygame.Rect(0, 0, 240, 70)',
          'nut.center = (400, 300)',
          '',
          'so_lan_bam = 0',
          '',
          'dang_chay = True',
          'while dang_chay:',
          '    vi_tri_chuot = pygame.mouse.get_pos()',
          '    dang_di_qua = nut.collidepoint(vi_tri_chuot)',
          '',
          '    for su_kien in pygame.event.get():',
          '        if su_kien.type == pygame.QUIT:',
          '            dang_chay = False',
          '        elif su_kien.type == pygame.MOUSEBUTTONDOWN:',
          '            if su_kien.button == 1 and nut.collidepoint(su_kien.pos):',
          '                so_lan_bam += 1',
          '        elif su_kien.type == pygame.KEYDOWN:',
          '            if su_kien.key == pygame.K_ESCAPE:',
          '                dang_chay = False',
          '',
          '    man_hinh.fill((25, 25, 45))',
          '',
          '    mau_nut = XANH_SANG if dang_di_qua else XANH',
          '    pygame.draw.rect(man_hinh, mau_nut, nut, 0, border_radius=14)',
          '    pygame.draw.rect(man_hinh, TRANG, nut, 3, border_radius=14)',
          '',
          '    chu = phong_chu.render(f"Da bam: {so_lan_bam}", True, TRANG)',
          '    man_hinh.blit(chu, chu.get_rect(center=nut.center))',
          '',
          '    goi_y = phong_chu.render("ESC de thoat", True, (150, 150, 170))',
          '    man_hinh.blit(goi_y, (10, 10))',
          '',
          '    pygame.display.flip()',
          '    dong_ho.tick(60)',
          '',
          'pygame.quit()',
        ], {
          output: 'Một nút bo góc sáng lên khi rê chuột qua, và đếm số lần được bấm.',
          notes: [
            '`mau_nut = XANH_SANG if dang_di_qua else XANH` là cách viết gọn của if/else trong một dòng.',
            'Kiểm tra `nut.collidepoint(su_kien.pos)` chứ không phải vị trí chuột hiện tại — ' +
              'để bấm đúng chỗ lúc bấm mới tính.',
            '`chu.get_rect(center=nut.center)` căn chữ vào giữa nút một cách chính xác.',
          ],
        }),
        playground('Sân chơi: vẽ bằng chuột', [
          'Làm một ứng dụng vẽ đơn giản: giữ chuột trái và di chuyển để vẽ.',
          '',
          'Mẹo: không `fill()` màn hình mỗi khung hình thì nét vẽ sẽ ở lại.',
          '',
          'Thử thêm: bấm phím C để xoá màn hình, bấm 1/2/3 để đổi màu bút.',
        ], [
          'import pygame',
          '',
          'pygame.init()',
          'man_hinh = pygame.display.set_mode((800, 600))',
          'dong_ho = pygame.time.Clock()',
          'man_hinh.fill((255, 255, 255))',
          '',
          'mau_but = (0, 0, 0)',
          '',
          'dang_chay = True',
          'while dang_chay:',
          '    for su_kien in pygame.event.get():',
          '        if su_kien.type == pygame.QUIT:',
          '            dang_chay = False',
          '        elif su_kien.type == pygame.KEYDOWN:',
          '            if su_kien.key == pygame.K_c:',
          '                man_hinh.fill((255, 255, 255))',
          '',
          '    if pygame.mouse.get_pressed()[0]:',
          '        pygame.draw.circle(man_hinh, mau_but, pygame.mouse.get_pos(), 6)',
          '',
          '    pygame.display.flip()',
          '    dong_ho.tick(60)',
          '',
          'pygame.quit()',
        ], 'Vẽ được bằng chuột, xoá được bằng phím C.'),
        challenge({
          slug: 'p-pg-b07-chuot-trong-vung',
          title: 'Chuột có nằm trong nút không?',
          statement: [
            'Một nút hình chữ nhật có góc trên bên trái `(rx, ry)`, rộng `rw`, cao `rh`.',
            '',
            'Điểm nằm **trong** nút khi `rx <= mx < rx + rw` và `ry <= my < ry + rh` — ' +
              'đúng theo cách `pygame.Rect.collidepoint()` hoạt động.',
            '',
            'Dòng đầu: bốn số nguyên `rx ry rw rh`.',
            '',
            'Dòng hai: số nguyên `Q` — số lần kiểm tra. `Q` dòng tiếp theo, mỗi dòng hai số `mx my`.',
            '',
            'Với mỗi lần kiểm tra, in `TRONG` hoặc `NGOAI` trên một dòng riêng.',
          ].join('\n'),
          hints: [
            'Chú ý dấu: mép trái/trên dùng `<=`, mép phải/dưới dùng `<` (không lấy bằng).',
            'Có thể gộp cả bốn điều kiện bằng `and`.',
          ],
          starterCode: [
            'rx, ry, rw, rh = map(int, input().split())',
            'q = int(input())',
            '',
            'for i in range(q):',
            '    mx, my = map(int, input().split())',
            '    # Kiểm tra và in kết quả',
          ].join('\n'),
          solutionCode: [
            'rx, ry, rw, rh = map(int, input().split())',
            'q = int(input())',
            '',
            'for i in range(q):',
            '    mx, my = map(int, input().split())',
            '    if rx <= mx < rx + rw and ry <= my < ry + rh:',
            '        print("TRONG")',
            '    else:',
            '        print("NGOAI")',
          ].join('\n'),
          tier: 'CO_BAN',
          judgeMode: 'IO_MATCH',
          tests: [
            sample(
              '300 250 200 60\n3\n400 280\n299 280\n500 280\n',
              'TRONG\nNGOAI\nNGOAI\n',
              'x = 500 chính là mép phải (300 + 200) nên bị coi là NGOAI.',
            ),
            sample('0 0 10 10\n2\n0 0\n9 9\n', 'TRONG\nTRONG\n', 'Mép trái và trên được tính là bên trong.'),
            hidden('0 0 10 10\n2\n10 5\n5 10\n', 'NGOAI\nNGOAI\n', 25),
            hidden('100 100 1 1\n1\n100 100\n', 'TRONG\n', 25),
            hidden('50 50 100 100\n3\n149 149\n150 150\n49 49\n', 'TRONG\nNGOAI\nNGOAI\n', 25),
            hidden('0 0 800 600\n2\n400 300\n800 600\n', 'TRONG\nNGOAI\n', 25),
          ],
        }),
      ],
    },

    {
      order: 8,
      slug: 'pg-b08-sprite-group-va-paddle',
      title: 'Sprite & Sprite Group — kết mô-đun: điều khiển paddle / xe tăng',
      summary:
        'Chuyển từ từ điển sang lớp `Sprite` chuẩn của Pygame. Buổi khép Module 2 với một paddle ' +
        'hoặc xe tăng di chuyển hoàn chỉnh.',
      objectives: [
        'Tạo lớp Sprite riêng kế thừa `pygame.sprite.Sprite`',
        'Hiểu vai trò của hai thuộc tính bắt buộc `image` và `rect`',
        'Dùng `pygame.sprite.Group` để quản lý nhiều sprite cùng lúc',
        'Hoàn thiện paddle/xe tăng điều khiển được',
      ],
      difficulty: 4,
      status: 'REQUIRED',
      teacherNotes:
        'GHI CHÚ Module 2: kết mô-đun bằng một vật thể di chuyển (paddle hoặc xe tăng) theo đúng ' +
        'kế hoạch bài giảng. Đây cũng là lần đầu học sinh gặp lớp (class) — chỉ giới thiệu ở mức dùng được.',
      blocks: [
        theory('Sprite — cách Pygame quản lý nhân vật', [
          'Từ điển `{"x": 400, "y": 500}` dùng tạm được, nhưng khi game có 50 viên đạn và 20 kẻ địch ' +
            'thì rất rối. Pygame có sẵn giải pháp: lớp **Sprite**.',
          '',
          '```python',
          'class Paddle(pygame.sprite.Sprite):',
          '    def __init__(self, x, y):',
          '        super().__init__()',
          '        self.image = pygame.Surface((120, 20))',
          '        self.image.fill((52, 152, 219))',
          '        self.rect = self.image.get_rect(center=(x, y))',
          '        self.toc_do = 8',
          '',
          '    def update(self):',
          '        phim = pygame.key.get_pressed()',
          '        if phim[pygame.K_LEFT]:',
          '            self.rect.x -= self.toc_do',
          '        if phim[pygame.K_RIGHT]:',
          '            self.rect.x += self.toc_do',
          '```',
          '',
          '**Hai thuộc tính BẮT BUỘC** của mọi Sprite:',
          '',
          '- **`self.image`** — hình dạng (một Surface, hoặc ảnh tải từ tệp)',
          '- **`self.rect`** — vị trí và kích thước',
          '',
          'Thiếu một trong hai, Pygame sẽ không vẽ được sprite đó.',
          '',
          '💡 `class` và `self` là kiến thức của khoá **Python Nâng Cao**. Ở đây em chỉ cần dùng theo ' +
            'mẫu — hiểu sâu sẽ đến sau.',
        ], [
          '`self.image` và `self.rect` là hai thuộc tính bắt buộc',
          '`super().__init__()` phải gọi đầu tiên trong `__init__`',
          'Phương thức `update()` chứa logic cập nhật mỗi khung hình',
        ]),
        theory('Group — quản lý cả đàn sprite', [
          '`Group` là nơi chứa nhiều sprite và thao tác với tất cả cùng lúc:',
          '',
          '```python',
          'tat_ca = pygame.sprite.Group()',
          'paddle = Paddle(400, 550)',
          'tat_ca.add(paddle)',
          '',
          '# Trong game loop — chỉ hai dòng cho MỌI sprite',
          'tat_ca.update()            # gọi update() của từng sprite',
          'tat_ca.draw(man_hinh)      # vẽ image tại rect của từng sprite',
          '```',
          '',
          'Dù có 1 sprite hay 500 sprite, game loop vẫn chỉ hai dòng đó. Đây là lý do Sprite Group ' +
            'đáng để học.',
          '',
          '| Thao tác | Cách viết |',
          '|---|---|',
          '| Thêm | `group.add(sprite)` |',
          '| Xoá khỏi mọi group | `sprite.kill()` |',
          '| Đếm | `len(group)` |',
          '| Duyệt | `for s in group:` |',
          '',
          '`sprite.kill()` là cách xoá một viên đạn hay kẻ địch đã bị tiêu diệt — em sẽ dùng rất nhiều ' +
            'từ Module 3.',
        ], [
          '`group.update()` gọi `update()` của mọi sprite',
          '`group.draw(man_hinh)` vẽ mọi sprite',
          '`sprite.kill()` xoá sprite khỏi tất cả các group',
        ]),
        example('Paddle hoàn chỉnh — kết Module 2', 'Bộ khung Sprite chuẩn dùng cho cả các module sau.', [
          'import pygame',
          '',
          'pygame.init()',
          'RONG, CAO = 800, 600',
          'man_hinh = pygame.display.set_mode((RONG, CAO))',
          'pygame.display.set_caption("Paddle - ket Module 2")',
          'dong_ho = pygame.time.Clock()',
          'phong_chu = pygame.font.SysFont("arial", 20)',
          '',
          '',
          'class Paddle(pygame.sprite.Sprite):',
          '    def __init__(self, x, y):',
          '        super().__init__()',
          '        self.image = pygame.Surface((130, 22), pygame.SRCALPHA)',
          '        pygame.draw.rect(self.image, (52, 152, 219),',
          '                         (0, 0, 130, 22), 0, border_radius=11)',
          '        self.rect = self.image.get_rect(center=(x, y))',
          '        self.toc_do = 9',
          '',
          '    def update(self):',
          '        phim = pygame.key.get_pressed()',
          '        if phim[pygame.K_LEFT] or phim[pygame.K_a]:',
          '            self.rect.x -= self.toc_do',
          '        if phim[pygame.K_RIGHT] or phim[pygame.K_d]:',
          '            self.rect.x += self.toc_do',
          '',
          '        # Gioi han trong man hinh - Rect lam viec nay rat gon',
          '        if self.rect.left < 0:',
          '            self.rect.left = 0',
          '        if self.rect.right > RONG:',
          '            self.rect.right = RONG',
          '',
          '',
          'class Muc_Tieu(pygame.sprite.Sprite):',
          '    def __init__(self, x, y):',
          '        super().__init__()',
          '        self.image = pygame.Surface((30, 30), pygame.SRCALPHA)',
          '        pygame.draw.circle(self.image, (241, 196, 15), (15, 15), 15)',
          '        self.rect = self.image.get_rect(center=(x, y))',
          '',
          '',
          'paddle = Paddle(RONG // 2, CAO - 50)',
          'tat_ca = pygame.sprite.Group(paddle)',
          '',
          'for i in range(6):',
          '    tat_ca.add(Muc_Tieu(80 + i * 130, 120))',
          '',
          'dang_chay = True',
          'while dang_chay:',
          '    for su_kien in pygame.event.get():',
          '        if su_kien.type == pygame.QUIT:',
          '            dang_chay = False',
          '',
          '    tat_ca.update()',
          '',
          '    man_hinh.fill((25, 25, 45))',
          '    tat_ca.draw(man_hinh)',
          '',
          '    chu = phong_chu.render(',
          '        f"Sprite: {len(tat_ca)}  |  Mui ten hoac A/D de di chuyen", True, (200, 200, 220))',
          '    man_hinh.blit(chu, (10, 10))',
          '',
          '    pygame.display.flip()',
          '    dong_ho.tick(60)',
          '',
          'pygame.quit()',
        ], {
          output: 'Một paddle xanh bo góc di chuyển trái/phải, sáu quả cầu vàng đứng yên phía trên.',
          notes: [
            '`pygame.SRCALPHA` cho phép Surface có vùng trong suốt — nếu thiếu, hình bo góc sẽ có nền đen.',
            'Chỉ Paddle có `update()`, nên chỉ nó chuyển động. `tat_ca.update()` vẫn gọi được cho mọi sprite ' +
              'vì lớp Sprite gốc đã có sẵn `update()` rỗng.',
            'Dùng `self.rect.left` và `self.rect.right` gọn hơn hẳn việc tự tính `x + rong`.',
          ],
        }),
        playground('Sân chơi: xe tăng bắn đạn', [
          'Đổi paddle thành xe tăng bắn được đạn:',
          '',
          '1. Thêm lớp `Dan` với `update()` làm viên đạn bay lên (`self.rect.y -= 10`)',
          '2. Khi đạn ra khỏi màn hình, gọi `self.kill()`',
          '3. Bấm phím cách để tạo một viên đạn mới ở vị trí xe tăng',
        ], [
          'import pygame',
          '',
          'pygame.init()',
          'RONG, CAO = 800, 600',
          'man_hinh = pygame.display.set_mode((RONG, CAO))',
          'dong_ho = pygame.time.Clock()',
          '',
          '',
          'class XeTang(pygame.sprite.Sprite):',
          '    def __init__(self, x, y):',
          '        super().__init__()',
          '        self.image = pygame.Surface((70, 40))',
          '        self.image.fill((39, 174, 96))',
          '        self.rect = self.image.get_rect(center=(x, y))',
          '',
          '    def update(self):',
          '        phim = pygame.key.get_pressed()',
          '        if phim[pygame.K_LEFT]:',
          '            self.rect.x -= 7',
          '        if phim[pygame.K_RIGHT]:',
          '            self.rect.x += 7',
          '        self.rect.clamp_ip(man_hinh.get_rect())',
          '',
          '',
          '# Them lop Dan o day',
          '',
          'xe = XeTang(RONG // 2, CAO - 60)',
          'tat_ca = pygame.sprite.Group(xe)',
          'dan_group = pygame.sprite.Group()',
          '',
          'dang_chay = True',
          'while dang_chay:',
          '    for su_kien in pygame.event.get():',
          '        if su_kien.type == pygame.QUIT:',
          '            dang_chay = False',
          '        elif su_kien.type == pygame.KEYDOWN:',
          '            if su_kien.key == pygame.K_SPACE:',
          '                pass   # tao vien dan moi o day',
          '',
          '    tat_ca.update()',
          '    dan_group.update()',
          '',
          '    man_hinh.fill((25, 25, 45))',
          '    tat_ca.draw(man_hinh)',
          '    dan_group.draw(man_hinh)',
          '    pygame.display.flip()',
          '    dong_ho.tick(60)',
          '',
          'pygame.quit()',
        ], 'Xe tăng di chuyển và bắn được đạn, đạn tự biến mất khi ra khỏi màn hình.'),
        challenge({
          slug: 'p-pg-b08-quan-ly-nhom-dan',
          title: 'Quản lý nhóm đạn',
          statement: [
            'Mỗi khung hình, mọi viên đạn bay lên `v` điểm ảnh (tức `y` giảm đi `v`). ' +
              'Viên đạn nào có `y < 0` sẽ bị xoá khỏi nhóm.',
            '',
            'Dòng đầu: ba số nguyên `M` (số đạn ban đầu), `v`, `N` (số khung hình).',
            '',
            'Dòng hai: `M` số nguyên là toạ độ `y` ban đầu của từng viên đạn.',
            '',
            'In ra **một dòng** là số viên đạn còn lại sau `N` khung hình.',
          ].join('\n'),
          hints: [
            'Không cần thật sự xoá phần tử khỏi danh sách — chỉ cần đếm số viên còn `y >= 0`.',
            'Sau N khung hình, viên đạn có y ban đầu là `y0` sẽ ở `y0 - v*N`.',
            'Cẩn thận: bài yêu cầu xoá khi `y < 0`, nên `y = 0` vẫn còn.',
          ],
          starterCode: [
            'm, v, n = map(int, input().split())',
            'y = list(map(int, input().split()))',
            '',
            '# Đếm số viên đạn còn lại',
          ].join('\n'),
          solutionCode: [
            'm, v, n = map(int, input().split())',
            'y = list(map(int, input().split()))',
            '',
            'con_lai = 0',
            'for y0 in y:',
            '    if y0 - v * n >= 0:',
            '        con_lai += 1',
            '',
            'print(con_lai)',
          ].join('\n'),
          tier: 'THU_THACH',
          judgeMode: 'IO_MATCH',
          tests: [
            sample(
              '4 10 30\n500 300 100 50\n',
              '2\n',
              'Sau 30 khung, đạn bay 300 điểm. Chỉ hai viên ở 500 và 300 còn lại.',
            ),
            sample('1 5 1\n5\n', '1\n', '5 - 5 = 0, vẫn còn vì điều kiện xoá là y < 0.'),
            hidden('3 1 1000\n100 200 300\n', '0\n', 25),
            hidden('2 0 100\n0 50\n', '2\n', 25),
            hidden('5 20 10\n199 200 201 400 600\n', '4\n', 25),
            hidden('1 7 3\n21\n', '1\n', 25),
          ],
        }),
        projectBlock(
          'Kết Module 2: paddle hoặc xe tăng của em',
          [
            'Hoàn thiện vật thể điều khiển được của riêng em, dùng lớp Sprite.',
            '',
            '**Yêu cầu bắt buộc:**',
            '',
            '- Ít nhất một lớp kế thừa `pygame.sprite.Sprite` với đủ `image` và `rect`',
            '- Điều khiển được bằng bàn phím, không đi ra khỏi màn hình',
            '- Dùng `pygame.sprite.Group` để quản lý và vẽ',
            '- Có ít nhất một sprite thứ hai trên màn hình',
            '',
            '**Làm thêm nếu em muốn:** dùng ảnh thật thay cho hình vẽ, thêm hiệu ứng khi di chuyển.',
          ],
          'CUSTOM',
          [
            'Viết được lớp Sprite đầu tiên có image và rect',
            'Điều khiển bằng bàn phím và giới hạn trong màn hình',
            'Quản lý sprite bằng Group',
            'Nộp bài kèm mô tả ngắn',
          ],
        ),
      ],
    },
  ],
};
