/**
 * Pygame — Module 4, phần 3 (Buổi 24–26): ba buổi TỔNG HỢP.
 *
 * Teacher note 12 — the lesson plan replaces the multiplayer lesson with
 * comprehensive synthesis sessions that consolidate earlier knowledge. These
 * three sessions teach almost no new API: they re-assemble what B1–B23 already
 * covered into three complete, different games.
 */
import type { LessonSpec } from '../types.ts';
import {
  challenge,
  example,
  hidden,
  playground,
  projectBlock,
  sample,
  theory,
} from '../builders.ts';

export const pygameLessons24to26: LessonSpec[] = [
  {
    order: 24,
    slug: 'pg-b24-tong-hop-1-platformer',
    title: 'Buổi tổng hợp 1: ghép Platformer hoàn chỉnh',
    summary:
      'Không có kỹ thuật mới. Buổi này ghép tile map, trọng lực, va chạm, camera, AI và vật phẩm ' +
      'của tám buổi vừa rồi thành một trò chơi platformer trọn vẹn.',
    objectives: [
      'Lập bản đồ kiến thức từ buổi 17 đến 23',
      'Ghép nhiều hệ thống rời rạc thành một trò chơi chạy được',
      'Tổ chức code theo lớp và hàm cho dễ mở rộng',
      'Tự tìm và sửa lỗi khi ghép các phần lại',
    ],
    difficulty: 5,
    estimatedMinutes: 120,
    status: 'REQUIRED',
    teacherNotes:
      'GHI CHÚ Module 4: buổi TỔNG HỢP thay cho bài multiplayer trong kế hoạch cũ. Mục tiêu là củng cố ' +
      'kiến thức đã học, không dạy thêm API mới. Cho học sinh tự ghép, thầy cô chỉ hỗ trợ khi bí.',
    blocks: [
      theory('Bản đồ những gì em đã có', [
        'Tám buổi vừa qua đã cho em đủ mọi mảnh ghép. Buổi này chỉ là lắp chúng lại.',
        '',
        '| Buổi | Mảnh ghép | Vai trò trong platformer |',
        '|---|---|---|',
        '| 17 | Tile map | Màn chơi |',
        '| 18 | Trọng lực + tách trục | Nhân vật đi và nhảy |',
        '| 19 | Camera | Màn chơi rộng hơn cửa sổ |',
        '| 20–21 | AI kẻ địch | Thử thách |',
        '| 22 | Power-up & kho đồ | Phần thưởng |',
        '| 23 | Nhiều màn + lưu tiến độ | Chiều dài trò chơi |',
        '| 14 | HUD & âm thanh | Phản hồi cho người chơi |',
        '| 15 | Máy trạng thái | Menu, tạm dừng, kết thúc |',
        '',
        '**Thứ tự ghép — quan trọng hơn em nghĩ.** Ghép sai thứ tự sẽ rất khó tìm lỗi:',
        '',
        '```',
        '1. Tile map + ve man choi           -> chay thu: thay man choi',
        '2. Nhan vat + trong luc + va cham   -> chay thu: di va nhay duoc',
        '3. Camera                            -> chay thu: man hinh cuon theo',
        '4. Vat pham                          -> chay thu: nhat duoc',
        '5. Ke dich                           -> chay thu: dich di chuyen',
        '6. Va cham nhan vat - ke dich        -> chay thu: mat mang',
        '7. HUD                               -> chay thu: thay diem va mang',
        '8. Menu + man ket thuc               -> chay thu: luong day du',
        '```',
        '',
        '**Chạy thử sau mỗi bước.** Nếu bước 5 hỏng, em biết chắc lỗi nằm ở phần kẻ địch chứ không ' +
          'phải ở bảy phần trước.',
      ], [
        'Buổi này không có API mới — chỉ ghép lại',
        'Ghép theo 8 bước, chạy thử sau mỗi bước',
        'Chạy thử từng bước giúp khoanh vùng lỗi ngay lập tức',
      ]),
      theory('Tổ chức code cho dự án lớn', [
        'Khi code vượt 200 dòng, cách tổ chức quan trọng hơn cả thuật toán. Bố cục chuẩn:',
        '',
        '```python',
        '# 1. IMPORT',
        'import pygame, json, math, random',
        '',
        '# 2. HANG SO - tat ca o mot cho de chinh',
        'TILE = 40',
        'TRONG_LUC = 0.9',
        'LUC_NHAY = -15',
        'MAU = {"nen": (28, 28, 50), "nhan_vat": (46, 204, 113)}',
        '',
        '# 3. DU LIEU MAN CHOI',
        'CAC_MAN = [...]',
        '',
        '# 4. CAC LOP',
        'class NhanVat(pygame.sprite.Sprite): ...',
        'class KeDich(pygame.sprite.Sprite): ...',
        'class VatPham(pygame.sprite.Sprite): ...',
        '',
        '# 5. CAC HAM TIEN ICH',
        'def nap_man(chi_so): ...',
        'def ve_hud(man_hinh, diem, mang): ...',
        '',
        '# 6. KHOI TAO',
        'pygame.init()',
        '',
        '# 7. GAME LOOP',
        'while dang_chay: ...',
        '```',
        '',
        '**Ba quy tắc giúp em không lạc trong chính code của mình:**',
        '',
        '1. **Không có "số ma thuật".** Thấy `nv.x += 5` thì đặt thành `TOC_DO = 5` ở đầu tệp. ' +
          'Sau này chỉnh game chỉ cần sửa một chỗ.',
        '2. **Mỗi hàm làm một việc.** `ve_hud()` chỉ vẽ HUD, không cập nhật điểm.',
        '3. **Đặt tên tiếng Việt không dấu, rõ nghĩa.** `so_mang_con_lai` tốt hơn `m`.',
      ], [
        'Bố cục: import → hằng số → dữ liệu → lớp → hàm → khởi tạo → game loop',
        'Không để "số ma thuật" rải rác trong code',
        'Mỗi hàm làm đúng một việc',
      ]),
      example('Bộ khung platformer đầy đủ', 'Khung sườn để em điền tiếp — đã có sẵn cấu trúc và chỗ trống.', [
        'import pygame',
        '',
        '# ===== 2. HANG SO =====',
        'TILE = 40',
        'RONG, CAO = 640, 480',
        'TRONG_LUC = 0.9',
        'LUC_NHAY = -15',
        'TOC_DO = 5',
        'TOC_DO_ROI_TOI_DA = 18',
        '',
        'MAU_NEN = (28, 28, 50)',
        'MAU_DAT = (90, 100, 125)',
        'MAU_NV = (46, 204, 113)',
        'MAU_XU = (241, 196, 15)',
        'MAU_DICH = (231, 76, 60)',
        '',
        '# ===== 3. DU LIEU MAN CHOI =====',
        'MAN_CHOI = [',
        '    "................................",',
        '    "................................",',
        '    "......XXXX.........o............",',
        '    "..................XXXX..........",',
        '    "..XXX....o..............XXXX....",',
        '    ".........................D......",',
        '    "......o......XXX................",',
        '    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",',
        ']',
        '',
        'RONG_MAN = len(MAN_CHOI[0]) * TILE',
        'CAO_MAN = len(MAN_CHOI) * TILE',
        '',
        '',
        '# ===== 5. HAM TIEN ICH =====',
        'def nap_man(ban_do):',
        '    """Tra ve (danh sach nen, danh sach xu, danh sach dich)."""',
        '    nen, xu, dich = [], [], []',
        '    for hang, dong in enumerate(ban_do):',
        '        for cot, ky_tu in enumerate(dong):',
        '            x, y = cot * TILE, hang * TILE',
        '            if ky_tu == "X":',
        '                nen.append(pygame.Rect(x, y, TILE, TILE))',
        '            elif ky_tu == "o":',
        '                xu.append(pygame.Rect(x + 12, y + 12, 16, 16))',
        '            elif ky_tu == "D":',
        '                dich.append({"rect": pygame.Rect(x, y + 6, 30, 30), "huong": 1})',
        '    return nen, xu, dich',
        '',
        '',
        'def ve_hud(mh, font, diem, mang, tong_xu):',
        '    mh.blit(font.render(f"Diem: {diem}/{tong_xu}", True, MAU_XU), (12, 10))',
        '    for i in range(mang):',
        '        pygame.draw.circle(mh, MAU_DICH, (RONG - 24 - i * 28, 22), 9)',
        '',
        '',
        '# ===== 6. KHOI TAO =====',
        'pygame.init()',
        'man_hinh = pygame.display.set_mode((RONG, CAO))',
        'pygame.display.set_caption("Platformer tong hop")',
        'dong_ho = pygame.time.Clock()',
        'font = pygame.font.SysFont("arial", 18, bold=True)',
        '',
        'nen, xu, dich = nap_man(MAN_CHOI)',
        'tong_xu = len(xu)',
        'nv = pygame.Rect(60, 40, 26, 34)',
        'vy = 0.0',
        'tren_nen = False',
        'camera_x = 0.0',
        'diem = 0',
        'mang = 3',
        'bat_tu = 0',
        '',
        '# ===== 7. GAME LOOP =====',
        'dang_chay = True',
        'while dang_chay:',
        '    for su_kien in pygame.event.get():',
        '        if su_kien.type == pygame.QUIT:',
        '            dang_chay = False',
        '        elif su_kien.type == pygame.KEYDOWN:',
        '            if su_kien.key == pygame.K_SPACE and tren_nen:',
        '                vy = LUC_NHAY',
        '',
        '    # --- Dieu khien ---',
        '    phim = pygame.key.get_pressed()',
        '    vx = 0',
        '    if phim[pygame.K_LEFT]:',
        '        vx = -TOC_DO',
        '    if phim[pygame.K_RIGHT]:',
        '        vx = TOC_DO',
        '',
        '    vy = min(vy + TRONG_LUC, TOC_DO_ROI_TOI_DA)',
        '',
        '    # --- Va cham truc X ---',
        '    nv.x += vx',
        '    for o in nen:',
        '        if nv.colliderect(o):',
        '            if vx > 0:',
        '                nv.right = o.left',
        '            elif vx < 0:',
        '                nv.left = o.right',
        '',
        '    # --- Va cham truc Y ---',
        '    tren_nen = False',
        '    nv.y += int(vy)',
        '    for o in nen:',
        '        if nv.colliderect(o):',
        '            if vy > 0:',
        '                nv.bottom = o.top',
        '                tren_nen = True',
        '            elif vy < 0:',
        '                nv.top = o.bottom',
        '            vy = 0.0',
        '',
        '    if nv.top > CAO_MAN:',
        '        nv.topleft = (60, 40)',
        '        vy = 0.0',
        '        mang -= 1',
        '',
        '    # --- Nhat xu ---',
        '    con_lai = []',
        '    for x_rect in xu:',
        '        if nv.colliderect(x_rect):',
        '            diem += 1',
        '        else:',
        '            con_lai.append(x_rect)',
        '    xu = con_lai',
        '',
        '    # --- Ke dich di tuan ---',
        '    for d in dich:',
        '        d["rect"].x += d["huong"] * 2',
        '        tham_do = (d["rect"].right + 4 if d["huong"] > 0 else d["rect"].left - 4,',
        '                   d["rect"].bottom + 6)',
        '        co_nen = False',
        '        for o in nen:',
        '            if o.collidepoint(tham_do):',
        '                co_nen = True',
        '                break',
        '        if not co_nen:',
        '            d["huong"] = -d["huong"]',
        '',
        '    # --- Va cham voi ke dich ---',
        '    if bat_tu > 0:',
        '        bat_tu -= 1',
        '    else:',
        '        for d in dich:',
        '            if nv.colliderect(d["rect"]):',
        '                mang -= 1',
        '                bat_tu = 90',
        '                break',
        '',
        '    # --- Camera ---',
        '    camera_x += ((nv.centerx - RONG // 2) - camera_x) * 0.12',
        '    camera_x = max(0.0, min(camera_x, float(RONG_MAN - RONG)))',
        '    cx = int(camera_x)',
        '',
        '    # --- Ve ---',
        '    man_hinh.fill(MAU_NEN)',
        '    for o in nen:',
        '        pygame.draw.rect(man_hinh, MAU_DAT, (o.x - cx, o.y, TILE, TILE))',
        '    for x_rect in xu:',
        '        pygame.draw.circle(man_hinh, MAU_XU,',
        '                           (x_rect.centerx - cx, x_rect.centery), 8)',
        '    for d in dich:',
        '        pygame.draw.rect(man_hinh, MAU_DICH,',
        '                         (d["rect"].x - cx, d["rect"].y, 30, 30), 0, border_radius=5)',
        '',
        '    if bat_tu == 0 or (bat_tu // 5) % 2 == 0:',
        '        pygame.draw.rect(man_hinh, MAU_NV,',
        '                         (nv.x - cx, nv.y, nv.width, nv.height), 0, border_radius=5)',
        '',
        '    ve_hud(man_hinh, font, diem, mang, tong_xu)',
        '    pygame.display.flip()',
        '    dong_ho.tick(60)',
        '',
        'pygame.quit()',
      ], {
        output:
          'Platformer đầy đủ: chạy nhảy trên bệ, ăn xu vàng, tránh kẻ địch đỏ biết tự quay đầu ở mép bệ, camera cuộn theo, HUD hiện điểm và mạng.',
        notes: [
          'Cả màn chơi, xu và kẻ địch đều sinh ra từ một danh sách chuỗi duy nhất — thêm một chữ `o` là có thêm một đồng xu.',
          'Kẻ địch dùng mẹo "điểm thăm dò" của buổi 20 nên không bao giờ rơi khỏi bệ.',
          'Bất tử tạm thời cộng với nhấp nháy (buổi 13, 14) tránh mất hết ba mạng trong một lần chạm.',
          'Còn thiếu: menu, nhiều màn, âm thanh, power-up. Đó là phần việc của em.',
        ],
      }),
      playground('Sân chơi: điền nốt bốn phần còn thiếu', [
        'Bộ khung ở trên đã chạy được nhưng còn thiếu bốn thứ. Thêm lần lượt, **chạy thử sau mỗi phần**:',
        '',
        '1. **Menu và màn kết thúc** (buổi 15) — thêm biến `trang_thai`',
        '2. **Nhiều màn chơi** (buổi 23) — đưa `MAN_CHOI` vào một danh sách `CAC_MAN`',
        '3. **Power-up** (buổi 22) — thêm ký tự `P` vào bản đồ',
        '4. **Âm thanh** (buổi 14) — tiếng nhảy và tiếng ăn xu',
        '',
        'Làm xong thứ tự này là em có một trò chơi hoàn chỉnh.',
      ], [
        '# Chep bo khung o tren vao day roi them lan luot:',
        '',
        '# 1. Menu',
        '# trang_thai = "MENU"',
        '',
        '# 2. Nhieu man',
        '# CAC_MAN = [MAN_CHOI_1, MAN_CHOI_2, ...]',
        '# man_hien_tai = 0',
        '',
        '# 3. Power-up: them ky tu "P" vao nap_man()',
        '',
        '# 4. Am thanh: pygame.mixer.Sound(...)',
      ], 'Ghép được ít nhất hai trong bốn phần còn thiếu và game vẫn chạy ổn định.'),
      challenge({
        slug: 'p-pg-b24-dem-phan-tu-ban-do',
        title: 'Phân tích bản đồ platformer',
        statement: [
          'Một bản đồ dùng các ký tự: `X` nền, `o` đồng xu, `D` kẻ địch, `P` power-up, `.` trống.',
          '',
          'Dòng đầu: số nguyên `H` — số hàng. `H` dòng tiếp theo là bản đồ.',
          '',
          'In ra **bốn dòng** theo đúng thứ tự:',
          '',
          '```',
          'Nen: <so_o_nen>',
          'Xu: <so_xu>',
          'Dich: <so_dich>',
          'Power-up: <so_power_up>',
          '```',
          '',
          'Ký tự lạ (không nằm trong năm ký tự trên) được bỏ qua.',
        ].join('\n'),
        hints: [
          'Dùng một từ điển đếm, hoặc bốn biến cộng dồn.',
          'Duyệt từng ký tự của từng dòng bằng hai vòng lặp lồng nhau.',
          'In đúng thứ tự bốn dòng như đề bài.',
        ],
        starterCode: [
          'h = int(input())',
          'ban_do = []',
          'for i in range(h):',
          '    ban_do.append(input())',
          '',
          '# Đếm bốn loại ký tự',
        ].join('\n'),
        solutionCode: [
          'h = int(input())',
          'ban_do = []',
          'for i in range(h):',
          '    ban_do.append(input())',
          '',
          'dem = {"X": 0, "o": 0, "D": 0, "P": 0}',
          'for dong in ban_do:',
          '    for c in dong:',
          '        if c in dem:',
          '            dem[c] += 1',
          '',
          'print(f"Nen: {dem[\'X\']}")',
          'print(f"Xu: {dem[\'o\']}")',
          'print(f"Dich: {dem[\'D\']}")',
          'print(f"Power-up: {dem[\'P\']}")',
        ].join('\n'),
        tier: 'CO_BAN',
        judgeMode: 'IO_MATCH',
        tests: [
          sample(
            '3\n..o..P..\n..D.....\nXXXXXXXX\n',
            'Nen: 8\nXu: 1\nDich: 1\nPower-up: 1\n',
            'Đếm từng ký tự trên toàn bản đồ.',
          ),
          sample('1\n........\n', 'Nen: 0\nXu: 0\nDich: 0\nPower-up: 0\n', 'Bản đồ trống.'),
          hidden('2\noooo\nXXXX\n', 'Nen: 4\nXu: 4\nDich: 0\nPower-up: 0\n', 20),
          hidden('1\nDDDPPP\n', 'Nen: 0\nXu: 0\nDich: 3\nPower-up: 3\n', 20),
          hidden('2\nXoXoXo\nDPDPDP\n', 'Nen: 3\nXu: 3\nDich: 3\nPower-up: 3\n', 30),
          hidden('1\nabcXYZ\n', 'Nen: 1\nXu: 0\nDich: 0\nPower-up: 0\n', 30),
        ],
      }),
      projectBlock(
        'Dự án tổng hợp 1: Platformer của em',
        [
          'Hoàn thiện platformer của riêng em dựa trên bộ khung ở buổi này.',
          '',
          '**Yêu cầu bắt buộc:**',
          '',
          '- Màn chơi bằng tile map, rộng hơn cửa sổ và có camera cuộn',
          '- Nhân vật chạy, nhảy, va chạm nền đúng ở cả hai trục',
          '- Ít nhất một loại kẻ địch có hành vi (đi tuần hoặc đuổi theo)',
          '- Vật phẩm nhặt được và HUD hiện điểm, mạng',
          '- Ít nhất ba trạng thái: MENU, CHOI, KET_THUC',
          '',
          '**Điểm cộng:** nhiều màn chơi, power-up, lưu tiến độ, âm thanh, hiệu ứng hình ảnh riêng.',
        ],
        'PLATFORMER',
        [
          'Bước 1–3: tile map, nhân vật, camera',
          'Bước 4–6: vật phẩm, kẻ địch, va chạm',
          'Bước 7–8: HUD, menu và màn kết thúc',
          'Hoàn thiện và nộp bài kèm mô tả',
        ],
        { minutes: 60 },
      ),
    ],
  },

  {
    order: 25,
    slug: 'pg-b25-tong-hop-2-space-invaders',
    title: 'Buổi tổng hợp 2: Space Invaders — ôn sprite, va chạm, điểm số',
    summary:
      'Cùng bộ kiến thức, một thể loại hoàn toàn khác. Space Invaders củng cố Sprite Group, ' +
      'va chạm nhóm với nhóm, và quản lý nhiều đối tượng cùng lúc.',
    objectives: [
      'Quản lý ba nhóm sprite: người chơi, đạn, kẻ địch',
      'Dùng `groupcollide` cho va chạm nhóm với nhóm',
      'Điều khiển đàn kẻ địch di chuyển đồng bộ',
      'Giới hạn tốc độ bắn bằng bộ đếm hồi chiêu',
    ],
    difficulty: 4,
    estimatedMinutes: 120,
    status: 'REQUIRED',
    teacherNotes:
      'GHI CHÚ Module 4: buổi TỔNG HỢP thứ hai. Ôn lại Sprite Group (buổi 8) và va chạm (buổi 12) ' +
      'trong một thể loại game khác hẳn platformer.',
    blocks: [
      theory('Ba nhóm sprite và va chạm nhóm–nhóm', [
        'Space Invaders là bài tập hoàn hảo cho Sprite Group. Chỉ cần ba nhóm:',
        '',
        '```python',
        'nhom_tau = pygame.sprite.Group(tau)',
        'nhom_dan = pygame.sprite.Group()',
        'nhom_dich = pygame.sprite.Group()',
        '```',
        '',
        '**Va chạm nhóm với nhóm** — một dòng xử lý mọi cặp đạn/kẻ địch:',
        '',
        '```python',
        'trung = pygame.sprite.groupcollide(nhom_dan, nhom_dich, True, True)',
        '#                                                        ^^^^  ^^^^',
        '#                                          xoa dan   xoa ke dich',
        'diem += len(trung) * 10',
        '```',
        '',
        '`groupcollide` trả về một **từ điển**: khoá là viên đạn, giá trị là danh sách kẻ địch mà nó ' +
          'bắn trúng. Với đạn thường thì mỗi khoá chỉ có một kẻ địch, nên `len(trung)` chính là số ' +
          'kẻ địch bị hạ.',
        '',
        '💡 Muốn làm đạn xuyên (một viên hạ nhiều kẻ), đặt tham số thứ ba là `False` để đạn không bị xoá.',
        '',
        '**Hồi chiêu** — không cho bắn liên tục vô hạn:',
        '',
        '```python',
        'hoi_chieu = 0',
        '',
        '# Moi khung hinh',
        'if hoi_chieu > 0:',
        '    hoi_chieu -= 1',
        '',
        'if phim[pygame.K_SPACE] and hoi_chieu == 0:',
        '    nhom_dan.add(Dan(tau.rect.centerx, tau.rect.top))',
        '    hoi_chieu = 12       # 12 khung = 0.2 giay',
        '```',
      ], [
        '`groupcollide(nhom1, nhom2, xoa1, xoa2)` xử lý mọi cặp trong một dòng',
        'Nó trả về từ điển; `len()` cho số cặp va chạm',
        'Bộ đếm hồi chiêu giới hạn tốc độ bắn',
      ]),
      theory('Đàn kẻ địch di chuyển đồng bộ', [
        'Đàn quái trong Space Invaders di chuyển như **một khối**: sang ngang tới khi có con chạm mép, ' +
          'rồi cả đàn tụt xuống và đảo hướng.',
        '',
        '```python',
        'huong_dan = 1',
        'TOC_DO_NGANG = 2',
        'BUOC_TUT_XUONG = 24',
        '',
        '# 1. Kiem tra XEM CO CON NAO cham mep khong',
        'cham_mep = False',
        'for d in nhom_dich:',
        '    if d.rect.right >= RONG or d.rect.left <= 0:',
        '        cham_mep = True',
        '        break',
        '',
        '# 2. Neu co -> ca dan tut xuong va dao huong',
        'if cham_mep:',
        '    huong_dan = -huong_dan',
        '    for d in nhom_dich:',
        '        d.rect.y += BUOC_TUT_XUONG',
        'else:',
        '    for d in nhom_dich:',
        '        d.rect.x += huong_dan * TOC_DO_NGANG',
        '```',
        '',
        '⚠️ Chú ý thứ tự: **kiểm tra toàn đàn trước, rồi mới di chuyển**. Nếu vừa duyệt vừa di chuyển ' +
          'và đảo hướng, con đầu tiên chạm mép sẽ làm đảo hướng ngay giữa vòng lặp, còn các con sau lại ' +
          'đi theo hướng mới — cả đàn sẽ bị xé lẻ.',
        '',
        'Đây là một ví dụ rất hay về việc **tách giai đoạn kiểm tra khỏi giai đoạn cập nhật**.',
        '',
        '**Tăng độ khó tự nhiên:** đàn càng ít con thì đi càng nhanh.',
        '',
        '```python',
        'TOC_DO_NGANG = 2 + (tong_dich_ban_dau - len(nhom_dich)) // 4',
        '```',
      ], [
        'Kiểm tra cả đàn TRƯỚC, rồi mới di chuyển cả đàn',
        'Chạm mép thì đảo hướng và tụt xuống cùng lúc',
        'Đàn ít con đi nhanh hơn — độ khó tự tăng',
      ]),
      example('Space Invaders hoàn chỉnh', 'Ba nhóm sprite, đàn quái đồng bộ, hồi chiêu, điểm số.', [
        'import pygame',
        '',
        'pygame.init()',
        'RONG, CAO = 700, 600',
        'man_hinh = pygame.display.set_mode((RONG, CAO))',
        'pygame.display.set_caption("Space Invaders")',
        'dong_ho = pygame.time.Clock()',
        'font = pygame.font.SysFont("arial", 20, bold=True)',
        'font_lon = pygame.font.SysFont("arial", 44, bold=True)',
        '',
        '',
        'def tao_surface(mau, kich_thuoc):',
        '    s = pygame.Surface(kich_thuoc, pygame.SRCALPHA)',
        '    pygame.draw.rect(s, mau, (0, 0, kich_thuoc[0], kich_thuoc[1]), 0, border_radius=5)',
        '    return s',
        '',
        '',
        'class Tau(pygame.sprite.Sprite):',
        '    def __init__(self):',
        '        super().__init__()',
        '        self.image = tao_surface((46, 204, 113), (54, 22))',
        '        self.rect = self.image.get_rect(center=(RONG // 2, CAO - 50))',
        '',
        '    def update(self):',
        '        phim = pygame.key.get_pressed()',
        '        if phim[pygame.K_LEFT]:',
        '            self.rect.x -= 7',
        '        if phim[pygame.K_RIGHT]:',
        '            self.rect.x += 7',
        '        self.rect.clamp_ip(man_hinh.get_rect())',
        '',
        '',
        'class Dan(pygame.sprite.Sprite):',
        '    def __init__(self, x, y):',
        '        super().__init__()',
        '        self.image = tao_surface((241, 196, 15), (5, 16))',
        '        self.rect = self.image.get_rect(center=(x, y))',
        '',
        '    def update(self):',
        '        self.rect.y -= 11',
        '        if self.rect.bottom < 0:',
        '            self.kill()',
        '',
        '',
        'class Dich(pygame.sprite.Sprite):',
        '    def __init__(self, x, y):',
        '        super().__init__()',
        '        self.image = tao_surface((231, 76, 60), (38, 28))',
        '        self.rect = self.image.get_rect(topleft=(x, y))',
        '',
        '',
        'def tao_dan_dich():',
        '    nhom = pygame.sprite.Group()',
        '    for hang in range(4):',
        '        for cot in range(9):',
        '            nhom.add(Dich(70 + cot * 62, 70 + hang * 50))',
        '    return nhom',
        '',
        '',
        'tau = Tau()',
        'nhom_tau = pygame.sprite.Group(tau)',
        'nhom_dan = pygame.sprite.Group()',
        'nhom_dich = tao_dan_dich()',
        'TONG_DICH = len(nhom_dich)',
        '',
        'huong_dan = 1',
        'hoi_chieu = 0',
        'diem = 0',
        'trang_thai = "CHOI"',
        '',
        'dang_chay = True',
        'while dang_chay:',
        '    for su_kien in pygame.event.get():',
        '        if su_kien.type == pygame.QUIT:',
        '            dang_chay = False',
        '        elif su_kien.type == pygame.KEYDOWN:',
        '            if su_kien.key == pygame.K_r and trang_thai != "CHOI":',
        '                nhom_dich = tao_dan_dich()',
        '                nhom_dan.empty()',
        '                tau.rect.centerx = RONG // 2',
        '                diem, huong_dan, trang_thai = 0, 1, "CHOI"',
        '',
        '    if trang_thai == "CHOI":',
        '        nhom_tau.update()',
        '        nhom_dan.update()',
        '',
        '        if hoi_chieu > 0:',
        '            hoi_chieu -= 1',
        '        phim = pygame.key.get_pressed()',
        '        if phim[pygame.K_SPACE] and hoi_chieu == 0:',
        '            nhom_dan.add(Dan(tau.rect.centerx, tau.rect.top))',
        '            hoi_chieu = 12',
        '',
        '        # --- Dan dich di chuyen dong bo ---',
        '        toc_do = 2 + (TONG_DICH - len(nhom_dich)) // 5',
        '        cham_mep = False',
        '        for d in nhom_dich:',
        '            if d.rect.right >= RONG - 10 or d.rect.left <= 10:',
        '                cham_mep = True',
        '                break',
        '',
        '        if cham_mep:',
        '            huong_dan = -huong_dan',
        '            for d in nhom_dich:',
        '                d.rect.y += 24',
        '        else:',
        '            for d in nhom_dich:',
        '                d.rect.x += huong_dan * toc_do',
        '',
        '        # --- Va cham dan voi dich ---',
        '        trung = pygame.sprite.groupcollide(nhom_dan, nhom_dich, True, True)',
        '        diem += len(trung) * 10',
        '',
        '        # --- Dieu kien ket thuc ---',
        '        if len(nhom_dich) == 0:',
        '            trang_thai = "THANG"',
        '        for d in nhom_dich:',
        '            if d.rect.bottom >= tau.rect.top:',
        '                trang_thai = "THUA"',
        '                break',
        '',
        '    # ===== VE =====',
        '    man_hinh.fill((16, 16, 34))',
        '    nhom_dich.draw(man_hinh)',
        '    nhom_dan.draw(man_hinh)',
        '    nhom_tau.draw(man_hinh)',
        '',
        '    man_hinh.blit(font.render(f"Diem: {diem}", True, (241, 196, 15)), (14, 12))',
        '    man_hinh.blit(font.render(f"Con lai: {len(nhom_dich)}", True, (200, 200, 225)),',
        '                  (RONG - 150, 12))',
        '',
        '    if trang_thai != "CHOI":',
        '        lop_phu = pygame.Surface((RONG, CAO), pygame.SRCALPHA)',
        '        lop_phu.fill((0, 0, 0, 175))',
        '        man_hinh.blit(lop_phu, (0, 0))',
        '        loi = "CHIEN THANG!" if trang_thai == "THANG" else "THUA ROI"',
        '        mau_loi = (46, 204, 113) if trang_thai == "THANG" else (231, 76, 60)',
        '        chu = font_lon.render(loi, True, mau_loi)',
        '        man_hinh.blit(chu, chu.get_rect(center=(RONG // 2, CAO // 2 - 20)))',
        '        goi = font.render("Bam R de choi lai", True, (210, 210, 230))',
        '        man_hinh.blit(goi, goi.get_rect(center=(RONG // 2, CAO // 2 + 34)))',
        '',
        '    pygame.display.flip()',
        '    dong_ho.tick(60)',
        '',
        'pygame.quit()',
      ], {
        output:
          'Space Invaders đầy đủ: 36 kẻ địch xếp 4 hàng tiến dần xuống, tàu bắn đạn có hồi chiêu, đàn địch càng ít càng nhanh, có màn thắng và thua.',
        notes: [
          'Toàn bộ logic bắn trúng chỉ nằm ở một dòng `groupcollide` — đó là sức mạnh của Sprite Group.',
          '`toc_do` được tính lại mỗi khung hình từ số kẻ địch còn lại, nên độ khó tăng mượt mà không cần code riêng.',
          'Vòng kiểm tra `cham_mep` tách hẳn khỏi vòng di chuyển — nếu gộp lại, đàn quái sẽ bị xé lẻ.',
          '`nhom_dan.empty()` xoá sạch nhóm khi chơi lại, tránh đạn cũ còn sót.',
        ],
      }),
      playground('Sân chơi: nâng cấp Space Invaders', [
        'Thêm lần lượt, chạy thử sau mỗi phần:',
        '',
        '1. **Kẻ địch bắn trả** — thỉnh thoảng một con ngẫu nhiên thả đạn xuống',
        '2. **Lá chắn** — vài khối chắn đạn, bị bắn thì mòn dần',
        '3. **Tàu mẹ** — thỉnh thoảng bay ngang phía trên, bắn trúng được nhiều điểm',
        '4. **Nhiều mạng** — dùng lại HUD hình tim của buổi 14',
      ], [
        'import pygame',
        'import random',
        '',
        '# Goi y: ke dich ban tra',
        '# Moi khung hinh, co mot xac suat nho de mot con bat ky tha dan:',
        '',
        '# if len(nhom_dich) > 0 and random.random() < 0.01:',
        '#     con_ban = random.choice(nhom_dich.sprites())',
        '#     nhom_dan_dich.add(DanDich(con_ban.rect.centerx, con_ban.rect.bottom))',
        '',
        '# Lop DanDich giong lop Dan nhung self.rect.y += 6 (di xuong)',
      ], 'Thêm được ít nhất một nâng cấp hoạt động ổn định.'),
      challenge({
        slug: 'p-pg-b25-dan-dich-cham-mep',
        title: 'Đàn kẻ địch chạm mép',
        statement: [
          'Một đàn kẻ địch, mỗi con rộng `w`, có toạ độ mép trái cho trước. Cả đàn di chuyển theo ' +
            'hướng `h` (`1` phải, `-1` trái) với tốc độ `s` mỗi khung hình.',
          '',
          'Mỗi khung hình:',
          '',
          '1. Kiểm tra **cả đàn**: nếu có con nào có `x < 0` hoặc `x + w > W` thì cả đàn **đảo hướng** ' +
            'và mỗi con tụt xuống — nhưng bài này chỉ theo dõi hướng, không theo dõi `y`',
          '2. Nếu không chạm mép, cả đàn dịch `h * s`',
          '',
          'Dòng đầu: năm số nguyên `M w W h s`. Dòng hai: `M` số nguyên là toạ độ `x` ban đầu. ' +
            'Dòng ba: số nguyên `N` — số khung hình.',
          '',
          'In ra **một dòng**: `<h> <x_nho_nhat>` sau `N` khung hình.',
        ].join('\n'),
        hints: [
          'Kiểm tra toàn bộ danh sách TRƯỚC, rồi mới quyết định di chuyển hay đảo hướng.',
          'Khi chạm mép thì chỉ đảo hướng, KHÔNG dịch trong khung hình đó.',
          '`min(danh_sach)` cho toạ độ nhỏ nhất.',
        ],
        starterCode: [
          'm, w, W, h, s = map(int, input().split())',
          'x = list(map(int, input().split()))',
          'n = int(input())',
          '',
          'for khung in range(n):',
          '    # Kiểm tra cả đàn trước',
          '    pass',
          '',
          'print(f"{h} {min(x)}")',
        ].join('\n'),
        solutionCode: [
          'm, w, W, h, s = map(int, input().split())',
          'x = list(map(int, input().split()))',
          'n = int(input())',
          '',
          'for khung in range(n):',
          '    cham_mep = False',
          '    for v in x:',
          '        if v < 0 or v + w > W:',
          '            cham_mep = True',
          '            break',
          '',
          '    if cham_mep:',
          '        h = -h',
          '    else:',
          '        for i in range(m):',
          '            x[i] += h * s',
          '',
          'print(f"{h} {min(x)}")',
        ].join('\n'),
        tier: 'THU_THACH',
        judgeMode: 'IO_MATCH',
        tests: [
          sample(
            '2 40 200 1 10\n0 60\n3\n',
            '1 30\n',
            'Sau 3 khung chưa con nào chạm mép, cả đàn dịch 30 điểm sang phải.',
          ),
          sample(
            '1 40 100 1 30\n50\n3\n',
            '-1 80\n',
            'Khung 2 đưa con này tới x=80 (80+40=120 > 100), nên khung 3 đảo hướng mà không dịch.',
          ),
          hidden('1 10 100 -1 5\n0\n1\n', '1 0\n', 25),
          hidden('3 20 300 1 10\n0 40 80\n5\n', '1 50\n', 25),
          hidden('2 50 100 1 10\n0 50\n1\n', '-1 0\n', 25),
          hidden('1 10 1000 1 1\n500\n100\n', '1 600\n', 25),
        ],
      }),
      projectBlock(
        'Dự án tổng hợp 2: Space Invaders của em',
        [
          'Hoàn thiện Space Invaders của riêng em.',
          '',
          '**Yêu cầu bắt buộc:**',
          '',
          '- Dùng `pygame.sprite.Sprite` và `Group` cho tàu, đạn và kẻ địch',
          '- Đàn kẻ địch di chuyển đồng bộ, chạm mép thì tụt xuống và đảo hướng',
          '- Va chạm đạn–kẻ địch bằng `groupcollide`',
          '- Điểm số, điều kiện thắng và điều kiện thua',
          '',
          '**Điểm cộng:** kẻ địch bắn trả, lá chắn, tàu mẹ, nhiều đợt quái, âm thanh.',
        ],
        'SPACE_INVADERS',
        [
          'Ba lớp Sprite: Tàu, Đạn, Kẻ địch',
          'Đàn kẻ địch di chuyển đồng bộ',
          'Va chạm và điểm số',
          'Màn thắng/thua, hoàn thiện và nộp bài',
        ],
        { minutes: 60 },
      ),
    ],
  },

  {
    order: 26,
    slug: 'pg-b26-tong-hop-3-maze-quiz-gui',
    title: 'Buổi tổng hợp 3: Maze / Quiz GUI — ôn thuật toán & giao diện',
    summary:
      'Buổi tổng hợp cuối, với hai lựa chọn: mê cung (nghiêng về thuật toán) hoặc trò đố vui ' +
      'có giao diện (nghiêng về tương tác). Em chọn hướng mình thích.',
    objectives: [
      'Biểu diễn mê cung bằng lưới và di chuyển theo ô',
      'Thiết kế giao diện nút bấm cho trò đố vui',
      'Đọc dữ liệu câu hỏi từ tệp JSON',
      'Chọn được cấu trúc dữ liệu phù hợp với từng loại trò chơi',
    ],
    difficulty: 4,
    estimatedMinutes: 120,
    status: 'REQUIRED',
    teacherNotes:
      'GHI CHÚ Module 4: buổi TỔNG HỢP thứ ba. Cho học sinh CHỌN một trong hai hướng theo sở thích — ' +
      'đây cũng là cách phân hoá tự nhiên.',
    blocks: [
      theory('Hướng A — Mê cung: di chuyển theo ô', [
        'Trong mê cung, nhân vật đi theo **ô** chứ không trượt mượt như platformer. ' +
          'Cách này đơn giản hơn nhiều và không cần vật lý.',
        '',
        '```python',
        'ME_CUNG = [',
        '    "XXXXXXXXXXX",',
        '    "X.........X",',
        '    "X.XXX.XXX.X",',
        '    "X...X...X.X",',
        '    "XXX.XXX.X.X",',
        '    "X.......X.D",',
        '    "XXXXXXXXXXX",',
        ']',
        '',
        'nv_hang, nv_cot = 1, 1',
        '',
        'def co_the_di(hang, cot):',
        '    """Kiem tra o (hang, cot) co di duoc khong."""',
        '    if hang < 0 or hang >= len(ME_CUNG):',
        '        return False',
        '    if cot < 0 or cot >= len(ME_CUNG[0]):',
        '        return False',
        '    return ME_CUNG[hang][cot] != "X"',
        '',
        '# Xu ly phim: moi lan bam di DUNG MOT o',
        'if su_kien.key == pygame.K_LEFT and co_the_di(nv_hang, nv_cot - 1):',
        '    nv_cot -= 1',
        '```',
        '',
        '⚠️ Dùng `KEYDOWN` chứ không phải `get_pressed()` — nếu không, giữ phím một giây là nhân vật ' +
          'bay 60 ô.',
        '',
        'Kiểm tra biên **trước** khi truy cập `ME_CUNG[hang][cot]`, nếu không sẽ gặp `IndexError` ' +
          'ở mép mê cung.',
      ], [
        'Mê cung: di chuyển theo ô, dùng KEYDOWN',
        'Hàm `co_the_di()` kiểm tra biên trước rồi mới đọc ô',
        'Không cần vật lý — đơn giản hơn platformer nhiều',
      ]),
      theory('Hướng B — Quiz GUI: dữ liệu và nút bấm', [
        'Trò đố vui gần như không có "game", nhưng lại là bài tập rất tốt về **giao diện** và ' +
          '**dữ liệu**.',
        '',
        '**Câu hỏi lưu bằng JSON** — đúng kỹ thuật buổi 29 khoá Cơ Bản:',
        '',
        '```json',
        '[',
        '  {',
        '    "cau_hoi": "Thu do cua Viet Nam la gi?",',
        '    "lua_chon": ["Ha Noi", "Da Nang", "Hue", "Can Tho"],',
        '    "dap_an": 0',
        '  }',
        ']',
        '```',
        '',
        '```python',
        'import json',
        '',
        'with open("cau_hoi.json", "r", encoding="utf-8") as f:',
        '    cau_hoi = json.load(f)',
        '```',
        '',
        '**Sinh nút từ dữ liệu** — số nút tự khớp với số lựa chọn:',
        '',
        '```python',
        'nut = []',
        'for i, lc in enumerate(cau_hoi[chi_so]["lua_chon"]):',
        '    nut.append(pygame.Rect(150, 220 + i * 70, 500, 55))',
        '',
        '# Xu ly bam',
        'for i, khung in enumerate(nut):',
        '    if khung.collidepoint(su_kien.pos):',
        '        if i == cau_hoi[chi_so]["dap_an"]:',
        '            diem += 1',
        '        chi_so += 1',
        '```',
        '',
        'Ưu điểm lớn: thêm câu hỏi chỉ cần sửa tệp JSON, **không cần sửa code**. ' +
          'Đó là nguyên tắc "tách dữ liệu khỏi code" mà mọi phần mềm lớn đều theo.',
      ], [
        'Câu hỏi nằm trong JSON, tách khỏi code',
        'Sinh nút từ dữ liệu nên số lựa chọn linh hoạt',
        'Thêm câu hỏi không cần sửa một dòng code nào',
      ]),
      example('Mê cung chạy được', 'Bản đầy đủ của hướng A — đếm bước đi và có màn thắng.', [
        'import pygame',
        '',
        'pygame.init()',
        'O = 44',
        '',
        'ME_CUNG = [',
        '    "XXXXXXXXXXXXX",',
        '    "XP..........X",',
        '    "X.XXX.XXXXX.X",',
        '    "X...X.....X.X",',
        '    "XXX.XXXXX.X.X",',
        '    "X.........X.X",',
        '    "X.XXXXXXX.X.X",',
        '    "X.......X...D",',
        '    "XXXXXXXXXXXXX",',
        ']',
        '',
        'RONG = len(ME_CUNG[0]) * O',
        'CAO = len(ME_CUNG) * O + 44',
        'man_hinh = pygame.display.set_mode((RONG, CAO))',
        'pygame.display.set_caption("Me cung")',
        'dong_ho = pygame.time.Clock()',
        'font = pygame.font.SysFont("arial", 20, bold=True)',
        'font_lon = pygame.font.SysFont("arial", 40, bold=True)',
        '',
        '',
        'def tim_ky_tu(ky_tu):',
        '    for hang, dong in enumerate(ME_CUNG):',
        '        for cot, c in enumerate(dong):',
        '            if c == ky_tu:',
        '                return hang, cot',
        '    return 1, 1',
        '',
        '',
        'def co_the_di(hang, cot):',
        '    if hang < 0 or hang >= len(ME_CUNG):',
        '        return False',
        '    if cot < 0 or cot >= len(ME_CUNG[0]):',
        '        return False',
        '    return ME_CUNG[hang][cot] != "X"',
        '',
        '',
        'bat_dau = tim_ky_tu("P")',
        'nv_hang, nv_cot = bat_dau',
        'dich_hang, dich_cot = tim_ky_tu("D")',
        'so_buoc = 0',
        'da_thang = False',
        '',
        'HUONG = {',
        '    pygame.K_LEFT: (0, -1),',
        '    pygame.K_RIGHT: (0, 1),',
        '    pygame.K_UP: (-1, 0),',
        '    pygame.K_DOWN: (1, 0),',
        '}',
        '',
        'dang_chay = True',
        'while dang_chay:',
        '    for su_kien in pygame.event.get():',
        '        if su_kien.type == pygame.QUIT:',
        '            dang_chay = False',
        '        elif su_kien.type == pygame.KEYDOWN:',
        '            if su_kien.key == pygame.K_r:',
        '                nv_hang, nv_cot = bat_dau',
        '                so_buoc = 0',
        '                da_thang = False',
        '            elif su_kien.key in HUONG and not da_thang:',
        '                dh, dc = HUONG[su_kien.key]',
        '                if co_the_di(nv_hang + dh, nv_cot + dc):',
        '                    nv_hang += dh',
        '                    nv_cot += dc',
        '                    so_buoc += 1',
        '                    if (nv_hang, nv_cot) == (dich_hang, dich_cot):',
        '                        da_thang = True',
        '',
        '    man_hinh.fill((22, 22, 40))',
        '',
        '    for hang, dong in enumerate(ME_CUNG):',
        '        for cot, c in enumerate(dong):',
        '            khung = pygame.Rect(cot * O, hang * O + 44, O, O)',
        '            if c == "X":',
        '                pygame.draw.rect(man_hinh, (70, 80, 110), khung)',
        '                pygame.draw.rect(man_hinh, (100, 115, 150), khung, 2)',
        '            elif c == "D":',
        '                pygame.draw.rect(man_hinh, (241, 196, 15), khung.inflate(-12, -12),',
        '                                 0, border_radius=6)',
        '',
        '    nv_khung = pygame.Rect(nv_cot * O, nv_hang * O + 44, O, O)',
        '    pygame.draw.circle(man_hinh, (46, 204, 113), nv_khung.center, O // 2 - 7)',
        '',
        '    man_hinh.blit(font.render(f"So buoc: {so_buoc}   (R de choi lai)",',
        '                              True, (215, 215, 235)), (12, 12))',
        '',
        '    if da_thang:',
        '        lop_phu = pygame.Surface((RONG, CAO), pygame.SRCALPHA)',
        '        lop_phu.fill((0, 0, 0, 170))',
        '        man_hinh.blit(lop_phu, (0, 0))',
        '        chu = font_lon.render(f"THOAT RA ROI! {so_buoc} buoc", True, (46, 204, 113))',
        '        man_hinh.blit(chu, chu.get_rect(center=(RONG // 2, CAO // 2)))',
        '',
        '    pygame.display.flip()',
        '    dong_ho.tick(60)',
        '',
        'pygame.quit()',
      ], {
        output: 'Mê cung 13×9, chấm xanh đi theo ô bằng phím mũi tên, tới ô vàng thì hiện màn thắng kèm số bước.',
        notes: [
          'Từ điển `HUONG` thay cho bốn câu `if` — gọn hơn nhiều và dễ thêm hướng chéo.',
          '`tim_ky_tu()` tìm điểm xuất phát và đích ngay trong bản đồ, nên đổi mê cung là chạy được luôn.',
          'Phần `+ 44` trong toạ độ vẽ là để chừa chỗ cho thanh HUD phía trên.',
        ],
      }),
      playground('Sân chơi: chọn hướng của em', [
        '**Hướng A — Mê cung.** Nâng cấp bản ở trên:',
        '',
        '- Thêm vật phẩm phải nhặt hết mới mở được cửa',
        '- Thêm bộ đếm thời gian',
        '- Thêm kẻ địch đi tuần trong mê cung',
        '',
        '**Hướng B — Quiz GUI.** Bắt đầu từ khung dưới:',
        '',
        '- Đọc câu hỏi từ JSON',
        '- Sinh nút từ danh sách lựa chọn',
        '- Hiện đúng/sai rồi chuyển câu tiếp theo',
        '- Màn tổng kết điểm ở cuối',
        '',
        'Chọn hướng em thấy hứng thú hơn.',
      ], [
        'import pygame',
        'import json',
        '',
        '# ==== HUONG B: Quiz GUI - bo khung ====',
        'CAU_HOI = [',
        '    {"cau_hoi": "Python dung ky tu nao de ghi chu?",',
        '     "lua_chon": ["//", "#", "<!-- -->", "/* */"],',
        '     "dap_an": 1},',
        '    {"cau_hoi": "Lenh nao lap 5 lan?",',
        '     "lua_chon": ["for i in range(5):", "loop 5:", "repeat(5)", "while 5:"],',
        '     "dap_an": 0},',
        ']',
        '',
        'pygame.init()',
        'RONG, CAO = 800, 520',
        'man_hinh = pygame.display.set_mode((RONG, CAO))',
        'dong_ho = pygame.time.Clock()',
        'font = pygame.font.SysFont("arial", 22)',
        '',
        'chi_so = 0',
        'diem = 0',
        '',
        'dang_chay = True',
        'while dang_chay:',
        '    for su_kien in pygame.event.get():',
        '        if su_kien.type == pygame.QUIT:',
        '            dang_chay = False',
        '        elif su_kien.type == pygame.MOUSEBUTTONDOWN and chi_so < len(CAU_HOI):',
        '            for i in range(len(CAU_HOI[chi_so]["lua_chon"])):',
        '                khung = pygame.Rect(120, 180 + i * 72, 560, 56)',
        '                if khung.collidepoint(su_kien.pos):',
        '                    if i == CAU_HOI[chi_so]["dap_an"]:',
        '                        diem += 1',
        '                    chi_so += 1',
        '                    break',
        '',
        '    man_hinh.fill((28, 28, 50))',
        '    if chi_so < len(CAU_HOI):',
        '        c = CAU_HOI[chi_so]',
        '        man_hinh.blit(font.render(c["cau_hoi"], True, (255, 255, 255)), (120, 100))',
        '        for i, lc in enumerate(c["lua_chon"]):',
        '            khung = pygame.Rect(120, 180 + i * 72, 560, 56)',
        '            pygame.draw.rect(man_hinh, (52, 152, 219), khung, 0, border_radius=10)',
        '            chu = font.render(lc, True, (255, 255, 255))',
        '            man_hinh.blit(chu, chu.get_rect(center=khung.center))',
        '    else:',
        '        chu = font.render(f"Ket qua: {diem}/{len(CAU_HOI)}", True, (241, 196, 15))',
        '        man_hinh.blit(chu, chu.get_rect(center=(RONG // 2, CAO // 2)))',
        '',
        '    pygame.display.flip()',
        '    dong_ho.tick(60)',
        '',
        'pygame.quit()',
      ], 'Hoàn thành được một trong hai hướng ở mức chạy được từ đầu đến cuối.'),
      challenge({
        slug: 'p-pg-b26-duong-di-me-cung',
        title: 'Kiểm tra đường đi trong mê cung',
        statement: [
          'Cho một mê cung gồm `X` (tường) và `.` (đi được), cùng vị trí xuất phát `(hang, cot)`.',
          '',
          'Thực hiện một dãy lệnh di chuyển gồm các ký tự `L` (trái), `R` (phải), `U` (lên), `D` (xuống). ' +
            'Mỗi lệnh dịch **một ô**. Nếu ô đích là tường hoặc nằm ngoài mê cung, lệnh đó **bị bỏ qua**.',
          '',
          'Dòng đầu: hai số nguyên `H` và `W`. `H` dòng tiếp theo là mê cung. ' +
            'Dòng kế: hai số nguyên `hang cot` là vị trí xuất phát. Dòng cuối: chuỗi lệnh (không dấu cách).',
          '',
          'In ra **một dòng**: `<hang> <cot>` là vị trí cuối cùng.',
        ].join('\n'),
        hints: [
          'Dùng từ điển ánh xạ ký tự sang cặp (dh, dc).',
          'Luôn kiểm tra biên TRƯỚC khi đọc `me_cung[hang][cot]`.',
          'Lệnh không hợp lệ thì giữ nguyên vị trí, không dừng chương trình.',
        ],
        starterCode: [
          'h, w = map(int, input().split())',
          'me_cung = []',
          'for i in range(h):',
          '    me_cung.append(input())',
          'hang, cot = map(int, input().split())',
          'lenh = input().strip()',
          '',
          'HUONG = {"L": (0, -1), "R": (0, 1), "U": (-1, 0), "D": (1, 0)}',
          '',
          '# Thực hiện từng lệnh',
        ].join('\n'),
        solutionCode: [
          'h, w = map(int, input().split())',
          'me_cung = []',
          'for i in range(h):',
          '    me_cung.append(input())',
          'hang, cot = map(int, input().split())',
          'lenh = input().strip()',
          '',
          'HUONG = {"L": (0, -1), "R": (0, 1), "U": (-1, 0), "D": (1, 0)}',
          '',
          'for c in lenh:',
          '    if c not in HUONG:',
          '        continue',
          '    dh, dc = HUONG[c]',
          '    nh, nc = hang + dh, cot + dc',
          '    if 0 <= nh < h and 0 <= nc < w and me_cung[nh][nc] != "X":',
          '        hang, cot = nh, nc',
          '',
          'print(f"{hang} {cot}")',
        ].join('\n'),
        tier: 'THU_THACH',
        judgeMode: 'IO_MATCH',
        tests: [
          sample(
            '3 5\nXXXXX\nX...X\nXXXXX\n1 1\nRRR\n',
            '1 3\n',
            'Đi được ba ô sang phải rồi dừng vì ô tiếp theo là tường.',
          ),
          sample(
            '3 5\nXXXXX\nX...X\nXXXXX\n1 1\nUULLL\n',
            '1 1\n',
            'Mọi lệnh đều bị chặn bởi tường nên vị trí không đổi.',
          ),
          hidden('3 3\nXXX\nX.X\nXXX\n1 1\nRLUD\n', '1 1\n', 20),
          hidden('4 4\nXXXX\nX..X\nX..X\nXXXX\n1 1\nDR\n', '2 2\n', 20),
          hidden('3 5\nXXXXX\nX...X\nXXXXX\n1 3\nRRRR\n', '1 3\n', 30),
          hidden('5 5\nXXXXX\nX...X\nX.X.X\nX...X\nXXXXX\n1 1\nDDRRUU\n', '1 3\n', 30),
        ],
      }),
      projectBlock(
        'Dự án tổng hợp 3: Maze hoặc Quiz GUI',
        [
          'Chọn **một** trong hai hướng và hoàn thiện nó.',
          '',
          '**Hướng A — Mê cung.** Yêu cầu: mê cung bằng lưới, di chuyển theo ô, có đích và ' +
            'màn thắng, đếm số bước hoặc thời gian.',
          '',
          '**Hướng B — Quiz GUI.** Yêu cầu: câu hỏi đọc từ JSON, nút bấm sinh từ dữ liệu, ' +
            'phản hồi đúng/sai, màn tổng kết điểm.',
          '',
          '**Cả hai hướng đều cần:** ít nhất ba trạng thái (MENU, CHOI, KET_THUC) và giao diện ' +
            'chữ đủ lớn, dễ đọc.',
          '',
          'Trong phần mô tả, hãy nói vì sao em chọn hướng đó.',
        ],
        'MAZE',
        [
          'Chọn hướng và dựng bộ khung chạy được',
          'Hoàn thành phần logic chính',
          'Thêm menu và màn kết thúc',
          'Hoàn thiện giao diện và nộp bài',
        ],
        { minutes: 60 },
      ),
    ],
  },
];
