/**
 * Python Cơ Bản — Module 7–9 (Buổi 24–30).
 *
 * Teacher notes enforced here:
 *   • Note 6 — session 27 keeps exception handling PRACTICAL. No custom
 *     exception classes; those belong to the Advanced course.
 *   • Note 7 — sessions 28–29 cover Text and JSON only. The `csv` module is
 *     deliberately absent from the entire course.
 */
import type { ModuleSpec } from '../types.ts';
import {
  challenge,
  example,
  hidden,
  playground,
  projectBlock,
  quizBlock,
  reflection,
  sample,
  theory,
} from '../builders.ts';

export const module7: ModuleSpec = {
  slug: 'ham-module-package',
  title: 'Hàm, Module & Package',
  description:
    'Đóng gói công việc thành hàm để dùng lại, rồi gom hàm thành module. Đây là bước chuyển từ ' +
    '"viết được chương trình" sang "viết được chương trình có tổ chức".',
  lessons: [
    {
      order: 24,
      slug: 'b24-ham-do-nguoi-dung-dinh-nghia',
      title: 'Hàm do người dùng định nghĩa',
      summary:
        'Tự tạo lệnh riêng cho mình. Viết một lần, dùng lại bao nhiêu lần cũng được.',
      objectives: [
        'Định nghĩa hàm bằng từ khoá `def`',
        'Gọi hàm và truyền tham số cho hàm',
        'Trả về kết quả bằng `return`',
        'Giải thích được vì sao nên tách chương trình thành hàm',
      ],
      difficulty: 3,
      status: 'OPTIONAL',
      teacherNotes: 'Lesson 8. Nhấn mạnh sự khác nhau giữa `print` (hiện ra) và `return` (trả về).',
      blocks: [
        theory('Tự tạo lệnh của riêng em', [
          'Em đã dùng nhiều hàm có sẵn: `print()`, `len()`, `input()`, `math.sqrt()`. ' +
            'Bây giờ em sẽ tự viết hàm của mình.',
          '',
          '```python',
          'def chao(ten):',
          '    print(f"Xin chao {ten}!")',
          '',
          'chao("Lan")      # Xin chao Lan!',
          'chao("Minh")     # Xin chao Minh!',
          '```',
          '',
          'Cấu trúc một hàm:',
          '',
          '1. `def` — từ khoá báo "đây là một hàm"',
          '2. Tên hàm — đặt như tên biến, nên là **động từ**: `tinh_tong`, `kiem_tra`',
          '3. Cặp ngoặc chứa **tham số** — có thể để trống',
          '4. Dấu hai chấm `:` và **thụt lề** cho thân hàm — giống `if` và `for`',
          '',
          '⚠️ **Định nghĩa hàm không làm hàm chạy.** Hàm chỉ chạy khi được **gọi**, tức khi ' +
            'em viết tên hàm kèm cặp ngoặc.',
        ], [
          '`def ten_ham(tham_so):` rồi thụt lề thân hàm',
          'Định nghĩa ≠ chạy. Phải gọi thì hàm mới chạy',
          'Tên hàm nên là động từ, mô tả việc nó làm',
        ]),
        theory('`return` — trả kết quả về', [
          'Có hai loại hàm:',
          '',
          '**Loại 1 — làm việc gì đó** (in ra màn hình, ghi tệp):',
          '',
          '```python',
          'def in_bang_cuu_chuong(n):',
          '    for i in range(1, 11):',
          '        print(f"{n} x {i} = {n * i}")',
          '```',
          '',
          '**Loại 2 — tính ra một giá trị** rồi trả về:',
          '',
          '```python',
          'def tinh_tong(a, b):',
          '    return a + b',
          '',
          'ket_qua = tinh_tong(3, 5)     # ket_qua = 8',
          'print(tinh_tong(10, 20) * 2)  # 60',
          '```',
          '',
          '⚠️ **`print` và `return` khác nhau hoàn toàn:**',
          '',
          '- `print` **hiện** giá trị ra màn hình cho người xem, chương trình không giữ lại gì',
          '- `return` **đưa** giá trị về cho chỗ đã gọi hàm, để tính tiếp',
          '',
          '`return` cũng **kết thúc hàm ngay lập tức** — mọi dòng sau nó trong hàm sẽ không chạy.',
        ], [
          '`return` đưa giá trị về nơi gọi hàm',
          '`print` chỉ hiện ra màn hình, không trả về gì',
          '`return` kết thúc hàm ngay lập tức',
        ]),
        example('Cùng một bài, có hàm và không có hàm', 'So sánh để thấy hàm giúp gì.', [
          '# --- KHONG DUNG HAM: lap lai code ---',
          'diem_1 = [8, 9, 7]',
          'tb_1 = sum(diem_1) / len(diem_1)',
          'print(f"To 1: {tb_1:.2f}")',
          '',
          'diem_2 = [6, 7, 8]',
          'tb_2 = sum(diem_2) / len(diem_2)',
          'print(f"To 2: {tb_2:.2f}")',
          '',
          'print("---")',
          '',
          '# --- DUNG HAM: viet mot lan, dung nhieu lan ---',
          'def trung_binh(danh_sach):',
          '    return sum(danh_sach) / len(danh_sach)',
          '',
          'def in_ket_qua(ten_to, diem):',
          '    print(f"{ten_to}: {trung_binh(diem):.2f}")',
          '',
          'in_ket_qua("To 1", [8, 9, 7])',
          'in_ket_qua("To 2", [6, 7, 8])',
          'in_ket_qua("To 3", [10, 9, 9])',
        ], {
          output: ['To 1: 8.00', 'To 2: 7.00', '---', 'To 1: 8.00', 'To 2: 7.00', 'To 3: 9.33'].join('\n'),
          notes: [
            'Thêm tổ thứ ba chỉ tốn một dòng, thay vì ba dòng như cách đầu.',
            'Hàm `in_ket_qua` gọi hàm `trung_binh` — hàm gọi hàm khác là chuyện bình thường.',
            'Sửa công thức trung bình chỉ cần sửa một chỗ duy nhất.',
          ],
        }),
        playground('Sân chơi: bộ hàm tiện ích của em', [
          'Viết ba hàm nhỏ, rồi thử gọi chúng:',
          '',
          '- `la_so_chan(n)` — trả về `True` nếu `n` chẵn',
          '- `lon_nhat(a, b)` — trả về số lớn hơn',
          '- `giai_thua(n)` — trả về `n!` (tích các số từ 1 đến n)',
        ], [
          'def la_so_chan(n):',
          '    return n % 2 == 0',
          '',
          'def lon_nhat(a, b):',
          '    if a > b:',
          '        return a',
          '    return b',
          '',
          '# Viết hàm giai_thua ở đây',
          '',
          'print(la_so_chan(10))',
          'print(lon_nhat(3, 7))',
        ], 'Viết và gọi đúng cả ba hàm, hiểu vì sao `la_so_chan` không cần `if`.'),
        challenge({
          slug: 'p-b24-ham-kiem-tra-nguyen-to',
          title: 'Hàm kiểm tra số nguyên tố',
          statement: [
            'Viết hàm `la_nguyen_to(n)` trả về `True` nếu `n` là số nguyên tố, ngược lại trả về `False`.',
            '',
            'Chương trình đọc **một số nguyên** và in ra `True` hoặc `False`.',
            '',
            'Nhắc lại: số nguyên tố là số **lớn hơn 1** và chỉ chia hết cho 1 và chính nó. ' +
              'Vậy 0, 1 và số âm đều **không** phải số nguyên tố.',
          ].join('\n'),
          hints: [
            'Xử lý trường hợp `n < 2` trước — trả về `False` ngay.',
            'Duyệt các ước từ 2 tới `int(n ** 0.5) + 1` là đủ.',
            'Gặp ước chia hết thì `return False` ngay, khỏi cần xét tiếp.',
          ],
          starterCode: [
            'def la_nguyen_to(n):',
            '    # Viết thân hàm ở đây',
            '    pass',
            '',
            'so = int(input())',
            'print(la_nguyen_to(so))',
          ].join('\n'),
          solutionCode: [
            'def la_nguyen_to(n):',
            '    if n < 2:',
            '        return False',
            '    for uoc in range(2, int(n ** 0.5) + 1):',
            '        if n % uoc == 0:',
            '            return False',
            '    return True',
            '',
            'so = int(input())',
            'print(la_nguyen_to(so))',
          ].join('\n'),
          tier: 'CO_BAN',
          judgeMode: 'IO_MATCH',
          tests: [
            sample('7\n', 'True\n', '7 chỉ chia hết cho 1 và 7.'),
            sample('1\n', 'False\n', '1 không phải số nguyên tố theo định nghĩa.'),
            hidden('2\n', 'True\n', 20),
            hidden('0\n', 'False\n', 20),
            hidden('-5\n', 'False\n', 20),
            hidden('97\n', 'True\n', 20),
            hidden('100\n', 'False\n', 20),
          ],
        }),
      ],
    },

    {
      order: 25,
      slug: 'b25-tham-so-tra-ve-pham-vi-bien',
      title: 'Tham số, giá trị trả về & phạm vi biến',
      summary:
        'Tham số mặc định, trả về nhiều giá trị cùng lúc, và hiểu vì sao biến trong hàm không ' +
        'ảnh hưởng tới biến ngoài hàm.',
      objectives: [
        'Đặt giá trị mặc định cho tham số',
        'Gọi hàm bằng tham số có tên',
        'Trả về nhiều giá trị cùng lúc',
        'Phân biệt biến cục bộ và biến toàn cục',
      ],
      difficulty: 4,
      status: 'OPTIONAL',
      teacherNotes: 'Buổi mở rộng của Lesson 8 (⟨derived⟩). Phạm vi biến là khái niệm khó, cho ví dụ trực quan.',
      isDerived: true,
      blocks: [
        theory('Tham số mặc định và tham số có tên', [
          'Tham số có thể có **giá trị mặc định**, dùng khi người gọi không truyền gì:',
          '',
          '```python',
          'def chao(ten, loi_chao="Xin chao"):',
          '    print(f"{loi_chao} {ten}!")',
          '',
          'chao("Lan")                      # Xin chao Lan!',
          'chao("Minh", "Chao buoi sang")   # Chao buoi sang Minh!',
          '```',
          '',
          '⚠️ Tham số có mặc định phải đứng **sau** các tham số bắt buộc.',
          '',
          'Khi gọi hàm, em có thể ghi rõ **tên tham số** để code dễ đọc:',
          '',
          '```python',
          'chao(ten="Hoa", loi_chao="Hello")',
          'chao(loi_chao="Hi", ten="Nam")    # thứ tự không còn quan trọng',
          '```',
        ], [
          'Tham số mặc định đứng sau tham số bắt buộc',
          'Gọi bằng tên tham số giúp code dễ đọc và không phụ thuộc thứ tự',
        ]),
        theory('Trả về nhiều giá trị & phạm vi biến', [
          '**Trả nhiều giá trị** — chỉ cần ngăn cách bằng dấu phẩy:',
          '',
          '```python',
          'def thong_ke(ds):',
          '    return min(ds), max(ds), sum(ds) / len(ds)',
          '',
          'nho, lon, tb = thong_ke([3, 7, 5])',
          'print(nho, lon, tb)     # 3 7 5.0',
          '```',
          '',
          'Thực chất hàm trả về một tuple (buổi 23), và dòng gán "mở" tuple đó ra ba biến.',
          '',
          '**Phạm vi biến** — biến tạo bên trong hàm chỉ tồn tại bên trong hàm đó:',
          '',
          '```python',
          'def thu():',
          '    x = 100        # biến CỤC BỘ',
          '    print(x)',
          '',
          'x = 5              # biến TOÀN CỤC',
          'thu()              # 100',
          'print(x)           # 5  — không bị đổi!',
          '```',
          '',
          'Đây là tính năng chứ không phải hạn chế: nhờ nó, viết hàm mới không sợ vô tình phá ' +
            'biến của phần khác trong chương trình.',
        ], [
          '`return a, b, c` trả về nhiều giá trị cùng lúc',
          'Biến trong hàm là cục bộ, không ảnh hưởng ra ngoài',
          'Phạm vi biến giúp các phần chương trình không phá nhau',
        ]),
        example('Máy tính hình học đầy đủ', 'Kết hợp tham số mặc định và trả về nhiều giá trị.', [
          'import math',
          '',
          'def thong_tin_hinh_tron(r, lam_tron=2):',
          '    chu_vi = 2 * math.pi * r',
          '    dien_tich = math.pi * r ** 2',
          '    return round(chu_vi, lam_tron), round(dien_tich, lam_tron)',
          '',
          '# Dùng mặc định 2 chữ số',
          'cv, dt = thong_tin_hinh_tron(5)',
          'print(f"r=5  -> chu vi {cv}, dien tich {dt}")',
          '',
          '# Yêu cầu 4 chữ số',
          'cv, dt = thong_tin_hinh_tron(5, lam_tron=4)',
          'print(f"r=5  -> chu vi {cv}, dien tich {dt}")',
          '',
          '# Kiểm tra phạm vi biến',
          'r = 999',
          'cv, dt = thong_tin_hinh_tron(1)',
          'print(f"r ben ngoai van la {r}")',
        ], {
          output: [
            'r=5  -> chu vi 31.42, dien tich 78.54',
            'r=5  -> chu vi 31.4159, dien tich 78.5398',
            'r ben ngoai van la 999',
          ].join('\n'),
          notes: [
            'Tham số `r` bên trong hàm hoàn toàn tách biệt với biến `r` bên ngoài.',
            '`round(x, n)` làm tròn `x` tới `n` chữ số thập phân và trả về số, khác với `{x:.2f}` trả về chuỗi.',
          ],
        }),
        playground('Sân chơi: hàm đổi đơn vị linh hoạt', [
          'Viết hàm `doi_nhiet_do(gia_tri, tu="C", sang="F")` đổi giữa độ C và độ F.',
          '',
          'Công thức: F = C × 9/5 + 32, và C = (F − 32) × 5/9.',
        ], [
          'def doi_nhiet_do(gia_tri, tu="C", sang="F"):',
          '    if tu == "C" and sang == "F":',
          '        return gia_tri * 9 / 5 + 32',
          '    # Bổ sung chiều ngược lại',
          '    return gia_tri',
          '',
          'print(doi_nhiet_do(100))',
          'print(doi_nhiet_do(212, tu="F", sang="C"))',
        ], 'Hàm đổi đúng cả hai chiều và dùng được tham số mặc định.'),
        challenge({
          slug: 'p-b25-ham-thong-ke-tra-nhieu-gia-tri',
          title: 'Hàm thống kê trả về nhiều giá trị',
          statement: [
            'Viết hàm `thong_ke(ds)` nhận một danh sách số và trả về **ba giá trị**: ' +
              'nhỏ nhất, lớn nhất, trung bình.',
            '',
            'Chương trình đọc `N` rồi đọc `N` số trên một dòng, sau đó in **ba dòng**:',
            '',
            '```',
            'Nho nhat: <min>',
            'Lon nhat: <max>',
            'Trung binh: <tb>',
            '```',
            '',
            '`<min>` và `<max>` in nguyên dạng số nguyên, `<tb>` hiển thị **2 chữ số thập phân**.',
          ].join('\n'),
          hints: [
            '`return min(ds), max(ds), sum(ds) / len(ds)`.',
            'Nhận ba giá trị bằng `a, b, c = thong_ke(so)`.',
          ],
          starterCode: [
            'def thong_ke(ds):',
            '    # Trả về ba giá trị',
            '    pass',
            '',
            'n = int(input())',
            'so = list(map(int, input().split()))',
            '',
            '# Gọi hàm và in kết quả',
          ].join('\n'),
          solutionCode: [
            'def thong_ke(ds):',
            '    return min(ds), max(ds), sum(ds) / len(ds)',
            '',
            'n = int(input())',
            'so = list(map(int, input().split()))',
            'nho, lon, tb = thong_ke(so)',
            'print(f"Nho nhat: {nho}")',
            'print(f"Lon nhat: {lon}")',
            'print(f"Trung binh: {tb:.2f}")',
          ].join('\n'),
          tier: 'THU_THACH',
          judgeMode: 'IO_MATCH',
          tests: [
            sample(
              '5\n3 7 5 9 1\n',
              'Nho nhat: 1\nLon nhat: 9\nTrung binh: 5.00\n',
              'Tổng 25 chia 5 phần tử được 5.00.',
            ),
            sample('1\n42\n', 'Nho nhat: 42\nLon nhat: 42\nTrung binh: 42.00\n'),
            hidden('3\n-5 0 5\n', 'Nho nhat: -5\nLon nhat: 5\nTrung binh: 0.00\n', 25),
            hidden('4\n2 2 2 2\n', 'Nho nhat: 2\nLon nhat: 2\nTrung binh: 2.00\n', 25),
            hidden('3\n1 2 4\n', 'Nho nhat: 1\nLon nhat: 4\nTrung binh: 2.33\n', 25),
            hidden('6\n10 20 30 40 50 61\n', 'Nho nhat: 10\nLon nhat: 61\nTrung binh: 35.17\n', 25),
          ],
        }),
      ],
    },

    {
      order: 26,
      slug: 'b26-module-va-package',
      title: 'Module và Package',
      summary:
        'Tách chương trình thành nhiều tệp và dùng lại code của chính mình — bước cuối để chương trình ' +
        'lớn vẫn gọn gàng.',
      objectives: [
        'Tạo module riêng và nhập nó vào chương trình khác',
        'Dùng đủ các dạng `import`: `import m`, `from m import x`, `import m as tên_ngắn`',
        'Hiểu vai trò của `if __name__ == "__main__"`',
        'Nhận biết package là thư mục chứa nhiều module',
      ],
      difficulty: 4,
      status: 'OPTIONAL',
      teacherNotes: 'Lesson 9. Cho học sinh tự tách một chương trình cũ thành hai tệp để thấy lợi ích.',
      blocks: [
        theory('Module là một tệp `.py`', [
          'Mỗi tệp `.py` em viết **đã là một module**. Đặt tên `tien_ich.py`:',
          '',
          '```python',
          '# tien_ich.py',
          'def trung_binh(ds):',
          '    return sum(ds) / len(ds)',
          '',
          'def la_so_chan(n):',
          '    return n % 2 == 0',
          '',
          'PI = 3.14159',
          '```',
          '',
          'Rồi dùng ở tệp khác cùng thư mục:',
          '',
          '```python',
          '# main.py',
          'import tien_ich',
          '',
          'print(tien_ich.trung_binh([8, 9, 7]))',
          'print(tien_ich.PI)',
          '```',
          '',
          'Ba cách nhập, chọn cách nào tuỳ tình huống:',
          '',
          '| Cách viết | Cách dùng | Khi nào |',
          '|---|---|---|',
          '| `import tien_ich` | `tien_ich.trung_binh(...)` | Rõ ràng nhất, biết hàm từ đâu ra |',
          '| `from tien_ich import trung_binh` | `trung_binh(...)` | Chỉ cần vài hàm |',
          '| `import tien_ich as ti` | `ti.trung_binh(...)` | Tên module dài |',
        ], [
          'Mỗi tệp `.py` là một module',
          'Ba dạng import: `import m`, `from m import x`, `import m as ten`',
          'Module phải nằm cùng thư mục (hoặc trong đường dẫn Python biết)',
        ]),
        theory('`__name__` và package', [
          'Khi em `import` một module, **toàn bộ tệp đó được chạy một lượt**. Nếu tệp có dòng ' +
            '`print()` ở ngoài hàm, nó sẽ in ra ngay lúc import — thường là ngoài ý muốn.',
          '',
          'Cách xử lý chuẩn:',
          '',
          '```python',
          '# tien_ich.py',
          'def trung_binh(ds):',
          '    return sum(ds) / len(ds)',
          '',
          'if __name__ == "__main__":',
          '    # Chỉ chạy khi CHẠY TRỰC TIẾP tệp này,',
          '    # KHÔNG chạy khi tệp bị import',
          '    print("Thu ham:", trung_binh([1, 2, 3]))',
          '```',
          '',
          'Biến `__name__` bằng `"__main__"` khi tệp được chạy trực tiếp, và bằng tên module ' +
            'khi tệp bị import. Đây là chỗ lý tưởng để đặt code thử nghiệm.',
          '',
          '**Package** là một *thư mục* chứa nhiều module:',
          '',
          '```',
          'game/',
          '    __init__.py',
          '    nhan_vat.py',
          '    ban_do.py',
          '```',
          '',
          'Dùng: `from game import nhan_vat`. Em sẽ gặp lại cấu trúc này ở khoá Pygame.',
        ], [
          'Import một module sẽ chạy toàn bộ tệp đó',
          '`if __name__ == "__main__":` để tách code thử nghiệm',
          'Package = thư mục chứa nhiều module',
        ]),
        example('Tách chương trình thành module', 'Hai tệp làm việc cùng nhau.', [
          '# ===== tep 1: tien_ich.py =====',
          'def trung_binh(ds):',
          '    return sum(ds) / len(ds)',
          '',
          'def xep_loai(diem):',
          '    if diem >= 8:',
          '        return "Gioi"',
          '    elif diem >= 6.5:',
          '        return "Kha"',
          '    elif diem >= 5:',
          '        return "Trung binh"',
          '    return "Can co gang"',
          '',
          'if __name__ == "__main__":',
          '    print("Dang thu module tien_ich")',
          '    print(trung_binh([8, 9, 7]))',
          '',
          '',
          '# ===== tep 2: main.py =====',
          'from tien_ich import trung_binh, xep_loai',
          '',
          'diem = [8, 9, 7, 6, 10]',
          'tb = trung_binh(diem)',
          '',
          'print(f"Trung binh: {tb:.2f}")',
          'print(f"Xep loai  : {xep_loai(tb)}")',
        ], {
          output: ['Trung binh: 8.00', 'Xep loai  : Gioi'].join('\n'),
          notes: [
            'Dòng "Dang thu module tien_ich" KHÔNG in ra, vì tien_ich bị import chứ không chạy trực tiếp.',
            'Đó chính là tác dụng của `if __name__ == "__main__"`.',
          ],
        }),
        playground('Sân chơi: thư viện riêng của em', [
          'Trong Sân chơi này chỉ có một tệp, nên hãy tưởng tượng phần trên là module.',
          '',
          'Viết vài hàm tiện ích mà em thấy hay dùng, rồi thử gọi chúng ở phần dưới ' +
            'trong khối `if __name__ == "__main__":`.',
        ], [
          '# ==== phan "module" ====',
          'def dien_tich_hcn(dai, rong):',
          '    return dai * rong',
          '',
          'def chu_vi_hcn(dai, rong):',
          '    return (dai + rong) * 2',
          '',
          '# ==== phan "chuong trinh chinh" ====',
          'if __name__ == "__main__":',
          '    print(dien_tich_hcn(5, 3))',
          '    print(chu_vi_hcn(5, 3))',
        ], 'Viết được ít nhất hai hàm tiện ích và gọi chúng trong khối `__main__`.'),
        challenge({
          slug: 'p-b26-thu-vien-ham-toan',
          title: 'Bộ hàm toán học tự viết',
          statement: [
            'Viết ba hàm rồi dùng chúng:',
            '',
            '- `uoc_chung_lon_nhat(a, b)` — ƯCLN của hai số nguyên dương',
            '- `boi_chung_nho_nhat(a, b)` — BCNN của hai số nguyên dương',
            '- `tong_uoc(n)` — tổng tất cả các ước của `n` (kể cả 1 và `n`)',
            '',
            'Chương trình đọc **hai số nguyên dương** `a` và `b` trên hai dòng, in ra **ba dòng**:',
            '',
            '```',
            'UCLN: <ucln>',
            'BCNN: <bcnn>',
            'Tong uoc cua a: <tong>',
            '```',
          ].join('\n'),
          hints: [
            'ƯCLN bằng thuật toán Euclid: lặp `a, b = b, a % b` cho tới khi `b == 0`.',
            'BCNN = a × b // ƯCLN(a, b).',
            'Tổng ước: duyệt từ 1 tới n, cộng dồn những số chia hết.',
          ],
          starterCode: [
            'def uoc_chung_lon_nhat(a, b):',
            '    while b != 0:',
            '        a, b = b, a % b',
            '    return a',
            '',
            'def boi_chung_nho_nhat(a, b):',
            '    # Dùng lại hàm ƯCLN ở trên',
            '    pass',
            '',
            'def tong_uoc(n):',
            '    pass',
            '',
            'a = int(input())',
            'b = int(input())',
          ].join('\n'),
          solutionCode: [
            'def uoc_chung_lon_nhat(a, b):',
            '    while b != 0:',
            '        a, b = b, a % b',
            '    return a',
            '',
            'def boi_chung_nho_nhat(a, b):',
            '    return a * b // uoc_chung_lon_nhat(a, b)',
            '',
            'def tong_uoc(n):',
            '    tong = 0',
            '    for i in range(1, n + 1):',
            '        if n % i == 0:',
            '            tong += i',
            '    return tong',
            '',
            'a = int(input())',
            'b = int(input())',
            'print(f"UCLN: {uoc_chung_lon_nhat(a, b)}")',
            'print(f"BCNN: {boi_chung_nho_nhat(a, b)}")',
            'print(f"Tong uoc cua a: {tong_uoc(a)}")',
          ].join('\n'),
          tier: 'NANG_CAO',
          judgeMode: 'IO_MATCH',
          tests: [
            sample(
              '12\n18\n',
              'UCLN: 6\nBCNN: 36\nTong uoc cua a: 28\n',
              'Ước của 12: 1+2+3+4+6+12 = 28.',
            ),
            sample('7\n5\n', 'UCLN: 1\nBCNN: 35\nTong uoc cua a: 8\n'),
            hidden('100\n75\n', 'UCLN: 25\nBCNN: 300\nTong uoc cua a: 217\n', 25),
            hidden('1\n1\n', 'UCLN: 1\nBCNN: 1\nTong uoc cua a: 1\n', 25),
            hidden('6\n6\n', 'UCLN: 6\nBCNN: 6\nTong uoc cua a: 12\n', 25),
            hidden('17\n34\n', 'UCLN: 17\nBCNN: 34\nTong uoc cua a: 18\n', 25),
          ],
        }),
      ],
    },
  ],
};

export const module8: ModuleSpec = {
  slug: 'xu-ly-loi-va-tep-tin',
  title: 'Xử lý lỗi & Tệp tin',
  description:
    'Chương trình thật phải chịu được dữ liệu sai và phải lưu được kết quả. Hai buổi cuối của phần ' +
    'kiến thức, tập trung vào tệp văn bản và JSON.',
  lessons: [
    {
      order: 27,
      slug: 'b27-xu-ly-ngoai-le',
      title: 'Xử lý ngoại lệ `try` / `except`',
      summary:
        'Bắt lỗi để chương trình không dừng đột ngột. Buổi này đi thẳng vào thực hành, không lý thuyết sâu.',
      objectives: [
        'Dùng `try` / `except` để bắt lỗi',
        'Bắt đúng loại lỗi: `ValueError`, `ZeroDivisionError`, `IndexError`, `KeyError`',
        'Dùng `else` và `finally` khi cần',
        'Kết hợp `try`/`except` với vòng lặp để hỏi lại người dùng',
      ],
      difficulty: 3,
      status: 'OPTIONAL',
      teacherNotes:
        'Lesson 10. GHI CHÚ: giữ ở mức THỰC HÀNH (try/except). KHÔNG đi sâu vào việc tự định nghĩa ' +
        'lớp ngoại lệ riêng — phần đó dành cho khoá Nâng cao.',
      blocks: [
        theory('Bắt lỗi thay vì để chương trình chết', [
          'Khi gặp lỗi, Python dừng chương trình ngay và in một thông báo khó hiểu. Với người dùng ' +
            'bình thường, đó là trải nghiệm rất tệ.',
          '',
          '```python',
          'tuoi = int(input("Nhap tuoi: "))    # người dùng gõ "abc" -> chương trình chết',
          '```',
          '',
          '`try` / `except` cho phép em **dự phòng**:',
          '',
          '```python',
          'try:',
          '    tuoi = int(input("Nhap tuoi: "))',
          '    print(f"Nam sau ban {tuoi + 1} tuoi")',
          'except ValueError:',
          '    print("Vui long nhap mot so nguyen!")',
          '```',
          '',
          '**Cách chạy:** Python thử chạy khối `try`. Nếu mọi thứ ổn, khối `except` bị bỏ qua. ' +
            'Nếu có lỗi đúng loại đã ghi, Python nhảy ngay sang `except`.',
        ], [
          '`try:` chứa code có thể lỗi',
          '`except LoaiLoi:` chứa cách xử lý khi lỗi đó xảy ra',
          'Không lỗi thì khối except không chạy',
        ]),
        theory('Các loại lỗi thường gặp', [
          '| Loại lỗi | Xảy ra khi |',
          '|---|---|',
          '| `ValueError` | `int("abc")` — đổi kiểu không được |',
          '| `ZeroDivisionError` | Chia cho 0 |',
          '| `IndexError` | `ds[10]` khi danh sách chỉ có 3 phần tử |',
          '| `KeyError` | `d["x"]` khi từ điển không có khoá `"x"` |',
          '| `TypeError` | `"5" + 5` — cộng chuỗi với số |',
          '| `FileNotFoundError` | Mở tệp không tồn tại |',
          '',
          '**Bắt nhiều loại lỗi cùng lúc:**',
          '',
          '```python',
          'try:',
          '    a = int(input())',
          '    b = int(input())',
          '    print(a / b)',
          'except ValueError:',
          '    print("Phai nhap so!")',
          'except ZeroDivisionError:',
          '    print("Khong the chia cho 0!")',
          '```',
          '',
          '`else` chạy khi **không** có lỗi. `finally` chạy **luôn luôn**, dù lỗi hay không — ' +
            'thường dùng để dọn dẹp.',
          '',
          '⚠️ Nên bắt **đúng loại lỗi** cần bắt. Viết `except:` trơn sẽ nuốt cả những lỗi em không ' +
            'ngờ tới và làm việc tìm lỗi khó hơn nhiều.',
        ], [
          'Bắt đúng loại lỗi, đừng dùng `except:` trơn',
          '`else` chạy khi không lỗi, `finally` chạy trong mọi trường hợp',
        ]),
        example('Máy tính không bao giờ chết', 'Kết hợp try/except với vòng lặp để hỏi lại.', [
          'while True:',
          '    try:',
          '        a = float(input("So thu nhat: "))',
          '        b = float(input("So thu hai: "))',
          '        ket_qua = a / b',
          '    except ValueError:',
          '        print("Loi: phai nhap so. Thu lai nhe.")',
          '    except ZeroDivisionError:',
          '        print("Loi: khong the chia cho 0. Thu lai nhe.")',
          '    else:',
          '        print(f"{a} / {b} = {ket_qua:.2f}")',
          '        break',
          '    finally:',
          '        print("--- het mot luot ---")',
        ], {
          output: [
            'So thu nhat: 10',
            'So thu hai: 0',
            'Loi: khong the chia cho 0. Thu lai nhe.',
            '--- het mot luot ---',
            'So thu nhat: 10',
            'So thu hai: 4',
            '10.0 / 4.0 = 2.50',
            '--- het mot luot ---',
          ].join('\n'),
          notes: [
            '`break` nằm trong `else` nên chỉ thoát vòng lặp khi tính thành công.',
            '`finally` chạy cả khi có lỗi lẫn khi thành công — chú ý nó in ra ở cả hai lượt.',
          ],
        }),
        playground('Sân chơi: nhập điểm an toàn', [
          'Viết chương trình hỏi điểm cho tới khi người dùng nhập được một số hợp lệ trong khoảng 0–10.',
          '',
          'Cần bắt cả trường hợp nhập chữ lẫn trường hợp nhập số ngoài khoảng.',
        ], [
          'while True:',
          '    try:',
          '        diem = float(input("Nhap diem (0-10): "))',
          '    except ValueError:',
          '        print("Phai nhap so!")',
          '        continue',
          '',
          '    if 0 <= diem <= 10:',
          '        print(f"Da ghi nhan: {diem}")',
          '        break',
          '    print("Diem phai tu 0 den 10!")',
        ], 'Chương trình không bao giờ dừng đột ngột dù nhập gì đi nữa.'),
        challenge({
          slug: 'p-b27-chia-an-toan',
          title: 'Phép chia an toàn',
          statement: [
            'Đọc **hai dòng**, mỗi dòng là một giá trị bất kỳ (có thể không phải số).',
            '',
            'In ra **một dòng** kết quả:',
            '',
            '- Nếu chia được: `Ket qua: <thuong>` với thương hiển thị **2 chữ số thập phân**',
            '- Nếu một trong hai dòng không phải số: `Loi: du lieu khong phai so`',
            '- Nếu số thứ hai bằng 0: `Loi: khong the chia cho 0`',
            '',
            'Ưu tiên kiểm tra kiểu dữ liệu trước phép chia.',
          ].join('\n'),
          hints: [
            'Bọc cả hai lệnh `float(input())` và phép chia trong một khối `try`.',
            'Viết hai khối `except` riêng cho `ValueError` và `ZeroDivisionError`.',
            'Vì đọc dữ liệu trước rồi mới chia, ValueError sẽ được bắt trước.',
          ],
          starterCode: [
            'try:',
            '    a = float(input())',
            '    b = float(input())',
            '    # Thực hiện phép chia',
            'except ValueError:',
            '    print("Loi: du lieu khong phai so")',
          ].join('\n'),
          solutionCode: [
            'try:',
            '    a = float(input())',
            '    b = float(input())',
            '    ket_qua = a / b',
            'except ValueError:',
            '    print("Loi: du lieu khong phai so")',
            'except ZeroDivisionError:',
            '    print("Loi: khong the chia cho 0")',
            'else:',
            '    print(f"Ket qua: {ket_qua:.2f}")',
          ].join('\n'),
          tier: 'CO_BAN',
          judgeMode: 'IO_MATCH',
          tests: [
            sample('10\n4\n', 'Ket qua: 2.50\n', '10 chia 4 bằng 2.5.'),
            sample('10\n0\n', 'Loi: khong the chia cho 0\n'),
            sample('abc\n5\n', 'Loi: du lieu khong phai so\n', 'Dòng đầu không đổi được sang số.'),
            hidden('7\nhai\n', 'Loi: du lieu khong phai so\n', 25),
            hidden('-9\n3\n', 'Ket qua: -3.00\n', 25),
            hidden('0\n5\n', 'Ket qua: 0.00\n', 25),
            hidden('1\n3\n', 'Ket qua: 0.33\n', 25),
          ],
        }),
      ],
    },

    {
      order: 28,
      slug: 'b28-doc-ghi-tep-van-ban',
      title: 'Đọc & ghi tệp văn bản',
      summary:
        'Lưu dữ liệu ra tệp để lần chạy sau vẫn còn. Đây là bước biến chương trình thành công cụ dùng được thật.',
      objectives: [
        'Mở tệp bằng `with open(...)` và hiểu vì sao nên dùng `with`',
        'Đọc tệp bằng `read()`, `readlines()` và duyệt từng dòng',
        'Ghi tệp bằng chế độ `w` và `a`',
        'Bắt lỗi `FileNotFoundError`',
      ],
      difficulty: 4,
      status: 'OPTIONAL',
      teacherNotes:
        'Lesson 11. GHI CHÚ: tập trung Text và JSON. KHÔNG dạy CSV — học sinh phản hồi là ' +
        'giống Excel và nhàm chán.',
      blocks: [
        theory('Mở tệp đúng cách với `with`', [
          '```python',
          'with open("diem.txt", "w", encoding="utf-8") as f:',
          '    f.write("Lan 8.5\\n")',
          '    f.write("Minh 9.0\\n")',
          '```',
          '',
          'Ba phần cần nhớ:',
          '',
          '1. **Tên tệp** — `"diem.txt"`',
          '2. **Chế độ mở** — `"r"` đọc, `"w"` ghi đè, `"a"` ghi thêm vào cuối',
          '3. **`encoding="utf-8"`** — bắt buộc khi có tiếng Việt, nếu không sẽ lỗi hoặc hiện chữ lạ',
          '',
          '**Vì sao dùng `with`?** Nó tự động đóng tệp khi khối lệnh kết thúc, kể cả khi có lỗi ' +
            'xảy ra giữa chừng. Quên đóng tệp có thể làm mất dữ liệu vừa ghi.',
          '',
          '⚠️ Chế độ `"w"` **xoá sạch** nội dung cũ. Muốn ghi thêm, dùng `"a"`.',
        ], [
          '`with open(ten, che_do, encoding="utf-8") as f:`',
          '`"r"` đọc · `"w"` ghi đè · `"a"` ghi thêm',
          '`with` tự đóng tệp, kể cả khi có lỗi',
          'Luôn dùng `encoding="utf-8"` với tiếng Việt',
        ]),
        theory('Ba cách đọc tệp', [
          '```python',
          '# Cách 1: đọc toàn bộ thành một chuỗi',
          'with open("diem.txt", "r", encoding="utf-8") as f:',
          '    noi_dung = f.read()',
          '',
          '# Cách 2: đọc thành danh sách các dòng',
          'with open("diem.txt", "r", encoding="utf-8") as f:',
          '    cac_dong = f.readlines()',
          '',
          '# Cách 3: duyệt từng dòng — tiết kiệm bộ nhớ nhất, dùng nhiều nhất',
          'with open("diem.txt", "r", encoding="utf-8") as f:',
          '    for dong in f:',
          '        print(dong.strip())',
          '```',
          '',
          '💡 Mỗi dòng đọc lên đều còn ký tự xuống dòng ở cuối. `.strip()` cắt bỏ khoảng trắng ' +
            'và ký tự xuống dòng ở hai đầu — gần như lúc nào cũng cần.',
          '',
          '**Tệp không tồn tại** sẽ gây `FileNotFoundError`, nên hãy kết hợp với `try`/`except` ' +
            'đã học ở buổi 27:',
          '',
          '```python',
          'try:',
          '    with open("khong_co.txt", "r", encoding="utf-8") as f:',
          '        print(f.read())',
          'except FileNotFoundError:',
          '    print("Khong tim thay tep!")',
          '```',
        ], [
          '`for dong in f:` là cách đọc phổ biến nhất',
          '`.strip()` để bỏ ký tự xuống dòng ở cuối mỗi dòng',
          'Luôn dự phòng `FileNotFoundError`',
        ]),
        example('Sổ điểm lưu ra tệp', 'Ghi rồi đọc lại, có xử lý lỗi đầy đủ.', [
          '# --- Ghi du lieu ra tep ---',
          'hoc_sinh = [("Lan", 8.5), ("Minh", 9.0), ("Hoa", 7.5)]',
          '',
          'with open("diem.txt", "w", encoding="utf-8") as f:',
          '    for ten, diem in hoc_sinh:',
          '        f.write(f"{ten} {diem}\\n")',
          '',
          'print("Da ghi xong.")',
          '',
          '# --- Doc lai va thong ke ---',
          'try:',
          '    tong = 0',
          '    so_luong = 0',
          '    with open("diem.txt", "r", encoding="utf-8") as f:',
          '        for dong in f:',
          '            phan = dong.strip().split()',
          '            if len(phan) == 2:',
          '                print(f"{phan[0]:<6}: {phan[1]}")',
          '                tong += float(phan[1])',
          '                so_luong += 1',
          '',
          '    print(f"Trung binh: {tong / so_luong:.2f}")',
          'except FileNotFoundError:',
          '    print("Chua co tep diem.txt")',
        ], {
          output: [
            'Da ghi xong.',
            'Lan   : 8.5',
            'Minh  : 9.0',
            'Hoa   : 7.5',
            'Trung binh: 8.33',
          ].join('\n'),
          notes: [
            '`f.write()` không tự xuống dòng, nên phải tự thêm `\\n`.',
            '`dong.strip().split()` vừa cắt ký tự xuống dòng vừa tách thành các phần.',
            '`if len(phan) == 2` bỏ qua dòng trống ở cuối tệp — một chi tiết nhỏ nhưng hay gây lỗi.',
          ],
        }),
        playground('Sân chơi: nhật ký học tập', [
          'Viết chương trình ghi thêm một dòng nhật ký vào tệp mỗi lần chạy, rồi in lại toàn bộ nhật ký.',
          '',
          'Dùng chế độ `"a"` để không ghi đè những dòng cũ.',
        ], [
          'from datetime import date',
          '',
          'ghi_chu = "Hom nay minh hoc ve doc ghi tep"',
          '',
          'with open("nhat_ky.txt", "a", encoding="utf-8") as f:',
          '    f.write(f"{date.today()} - {ghi_chu}\\n")',
          '',
          'print("=== NHAT KY ===")',
          'with open("nhat_ky.txt", "r", encoding="utf-8") as f:',
          '    for dong in f:',
          '        print(dong.strip())',
        ], 'Chạy chương trình nhiều lần và thấy nhật ký dài thêm chứ không bị ghi đè.'),
        challenge({
          slug: 'p-b28-ghi-va-doc-lai-tep',
          title: 'Ghi danh sách ra tệp rồi đọc lại',
          statement: [
            'Dòng đầu là `N`. `N` dòng tiếp theo, mỗi dòng một số nguyên.',
            '',
            'Chương trình phải:',
            '',
            '1. Ghi `N` số đó ra tệp `so.txt`, **mỗi số một dòng**',
            '2. Đọc lại tệp `so.txt`',
            '3. In ra **hai dòng**:',
            '',
            '```',
            'Tong: <tong>',
            'So dong: <n>',
            '```',
            '',
            'Bài này kiểm tra em ghi và đọc lại đúng, nên bắt buộc phải thực sự đi qua tệp.',
          ].join('\n'),
          hints: [
            'Ghi bằng `"w"` để tệp luôn sạch ở mỗi lần chạy.',
            'Nhớ thêm `\\n` sau mỗi số khi ghi.',
            'Khi đọc lại, dùng `.strip()` trước khi `int()`.',
          ],
          starterCode: [
            'n = int(input())',
            '',
            'with open("so.txt", "w", encoding="utf-8") as f:',
            '    for i in range(n):',
            '        so = input()',
            '        # ghi so ra tep',
            '',
            '# Đọc lại và tính tổng',
          ].join('\n'),
          solutionCode: [
            'n = int(input())',
            '',
            'with open("so.txt", "w", encoding="utf-8") as f:',
            '    for i in range(n):',
            '        f.write(input().strip() + "\\n")',
            '',
            'tong = 0',
            'so_dong = 0',
            'with open("so.txt", "r", encoding="utf-8") as f:',
            '    for dong in f:',
            '        dong = dong.strip()',
            '        if dong != "":',
            '            tong += int(dong)',
            '            so_dong += 1',
            '',
            'print(f"Tong: {tong}")',
            'print(f"So dong: {so_dong}")',
          ].join('\n'),
          tier: 'THU_THACH',
          judgeMode: 'IO_MATCH',
          tests: [
            sample('3\n10\n20\n30\n', 'Tong: 60\nSo dong: 3\n', 'Ba số được ghi ra rồi đọc lại đủ.'),
            sample('1\n5\n', 'Tong: 5\nSo dong: 1\n'),
            hidden('4\n1\n2\n3\n4\n', 'Tong: 10\nSo dong: 4\n', 25),
            hidden('2\n-5\n5\n', 'Tong: 0\nSo dong: 2\n', 25),
            hidden('5\n100\n200\n300\n400\n500\n', 'Tong: 1500\nSo dong: 5\n', 25),
            hidden('3\n0\n0\n0\n', 'Tong: 0\nSo dong: 3\n', 25),
          ],
        }),
      ],
    },

    {
      order: 29,
      slug: 'b29-lam-viec-voi-json',
      title: 'Làm việc với JSON',
      summary:
        'Định dạng dữ liệu được dùng ở khắp mọi nơi trên Internet. Lưu được cả từ điển và danh sách ' +
        'lồng nhau chỉ trong một dòng lệnh.',
      objectives: [
        'Giải thích được JSON là gì và vì sao nó phổ biến',
        'Ghi dữ liệu Python ra tệp JSON bằng `json.dump`',
        'Đọc tệp JSON vào Python bằng `json.load`',
        'Xử lý được cấu trúc JSON lồng nhau',
      ],
      difficulty: 4,
      status: 'ADVANCED',
      teacherNotes:
        'Lesson 11 (tiếp). Trọng tâm là JSON vì nó dùng được ngay ở khoá Nâng cao (Web API) ' +
        'và khoá Pygame (lưu điểm cao, lưu tiến độ).',
      blocks: [
        theory('JSON — ngôn ngữ chung của dữ liệu', [
          'Với tệp văn bản thường, muốn lưu một từ điển em phải tự nghĩ cách viết ra rồi tự đọc lại. ' +
            'Rất phiền và dễ sai.',
          '',
          '**JSON** giải quyết chuyện đó. Nó là một định dạng chuẩn mà gần như mọi ngôn ngữ lập trình ' +
            'đều đọc được.',
          '',
          '```json',
          '{',
          '  "ten": "Lan",',
          '  "tuoi": 14,',
          '  "diem": [8.5, 9.0, 7.5],',
          '  "dang_hoc": true',
          '}',
          '```',
          '',
          'Trông rất giống từ điển Python phải không? Một vài khác biệt nhỏ:',
          '',
          '| Python | JSON |',
          '|---|---|',
          '| `True` / `False` | `true` / `false` |',
          '| `None` | `null` |',
          '| Nháy đơn hoặc kép | **Chỉ nháy kép** |',
          '',
          'Thư viện `json` lo hết việc chuyển đổi qua lại giúp em.',
        ], [
          'JSON là định dạng dữ liệu chuẩn, mọi ngôn ngữ đều đọc được',
          'Cú pháp gần giống từ điển Python',
          'JSON chỉ dùng nháy kép, `true`/`false` viết thường',
        ]),
        theory('Bốn hàm cần nhớ', [
          '| Hàm | Việc nó làm |',
          '|---|---|',
          '| `json.dump(du_lieu, f)` | Ghi dữ liệu Python **ra tệp** |',
          '| `json.load(f)` | Đọc **từ tệp** vào Python |',
          '| `json.dumps(du_lieu)` | Đổi thành **chuỗi** JSON |',
          '| `json.loads(chuoi)` | Đọc **từ chuỗi** JSON |',
          '',
          'Mẹo nhớ: có chữ `s` ở cuối nghĩa là làm việc với **s**tring (chuỗi).',
          '',
          '```python',
          'import json',
          '',
          'du_lieu = {"ten": "Lan", "diem": [8.5, 9.0]}',
          '',
          '# Ghi ra tệp',
          'with open("hs.json", "w", encoding="utf-8") as f:',
          '    json.dump(du_lieu, f, ensure_ascii=False, indent=2)',
          '',
          '# Đọc lại',
          'with open("hs.json", "r", encoding="utf-8") as f:',
          '    doc_lai = json.load(f)',
          '',
          'print(doc_lai["ten"])        # Lan',
          '```',
          '',
          'Hai tham số nên dùng khi ghi:',
          '',
          '- `ensure_ascii=False` — giữ nguyên tiếng Việt có dấu thay vì đổi thành mã khó đọc',
          '- `indent=2` — xuống dòng và thụt lề để người đọc được',
        ], [
          '`dump`/`load` làm việc với tệp; `dumps`/`loads` với chuỗi',
          '`ensure_ascii=False` để giữ tiếng Việt có dấu',
          '`indent=2` để tệp JSON dễ đọc',
        ]),
        example('Lưu và đọc hồ sơ lớp học', 'JSON xử lý được cấu trúc lồng nhau mà tệp văn bản thường rất khó.', [
          'import json',
          '',
          'lop = {',
          '    "ten_lop": "7A1",',
          '    "si_so": 3,',
          '    "hoc_sinh": [',
          '        {"ten": "Lan", "diem": [8.5, 9.0, 7.5]},',
          '        {"ten": "Minh", "diem": [7.0, 8.0, 9.0]},',
          '        {"ten": "Hoa", "diem": [9.5, 9.0, 10.0]},',
          '    ],',
          '}',
          '',
          '# Ghi ra tep',
          'with open("lop.json", "w", encoding="utf-8") as f:',
          '    json.dump(lop, f, ensure_ascii=False, indent=2)',
          '',
          '# Doc lai va thong ke',
          'with open("lop.json", "r", encoding="utf-8") as f:',
          '    du_lieu = json.load(f)',
          '',
          'print(f"Lop {du_lieu[\'ten_lop\']} - si so {du_lieu[\'si_so\']}")',
          'print("-" * 30)',
          '',
          'for hs in du_lieu["hoc_sinh"]:',
          '    diem = hs["diem"]',
          '    tb = sum(diem) / len(diem)',
          '    print(f"{hs[\'ten\']:<6}: {diem} -> TB {tb:.2f}")',
        ], {
          output: [
            'Lop 7A1 - si so 3',
            '------------------------------',
            'Lan   : [8.5, 9.0, 7.5] -> TB 8.33',
            'Minh  : [7.0, 8.0, 9.0] -> TB 8.00',
            'Hoa   : [9.5, 9.0, 10.0] -> TB 9.50',
          ].join('\n'),
          notes: [
            'Cấu trúc này có từ điển chứa danh sách, trong danh sách lại có từ điển — JSON xử lý gọn gàng.',
            'Đọc lên là dùng được ngay, không cần tự tách chuỗi như với tệp văn bản thường.',
          ],
        }),
        playground('Sân chơi: hồ sơ nhân vật game', [
          'Tạo hồ sơ một nhân vật game bằng từ điển, lưu ra JSON, rồi đọc lại và nâng cấp nhân vật.',
          '',
          'Đây chính là cách các trò chơi lưu tiến độ — em sẽ dùng lại kỹ thuật này ở khoá Pygame.',
        ], [
          'import json',
          '',
          'nhan_vat = {',
          '    "ten": "Rong Lua",',
          '    "cap_do": 1,',
          '    "mau": 100,',
          '    "vat_pham": ["kiem go", "khien"],',
          '}',
          '',
          'with open("nhan_vat.json", "w", encoding="utf-8") as f:',
          '    json.dump(nhan_vat, f, ensure_ascii=False, indent=2)',
          '',
          'with open("nhan_vat.json", "r", encoding="utf-8") as f:',
          '    nv = json.load(f)',
          '',
          'nv["cap_do"] += 1',
          'nv["vat_pham"].append("giay than toc")',
          'print(nv)',
        ], 'Lưu và đọc lại được hồ sơ nhân vật, kể cả phần danh sách vật phẩm.'),
        challenge({
          slug: 'p-b29-json-thong-ke-lop',
          title: 'Thống kê lớp học từ JSON',
          statement: [
            'Dòng đầu là `N` — số học sinh.',
            '',
            '`N` dòng tiếp theo, mỗi dòng có dạng `<ten> <diem>` (điểm là số thực).',
            '',
            'Chương trình phải:',
            '',
            '1. Xây một từ điển dạng `{"hoc_sinh": [{"ten": ..., "diem": ...}, ...]}`',
            '2. Ghi ra tệp `lop.json`',
            '3. Đọc lại tệp đó',
            '4. In ra **hai dòng**:',
            '',
            '```',
            'Si so: <n>',
            'Trung binh: <tb>',
            '```',
            '',
            '`<tb>` hiển thị **2 chữ số thập phân**.',
          ].join('\n'),
          hints: [
            'Xây danh sách các từ điển nhỏ bằng vòng lặp trước, rồi bọc vào từ điển lớn.',
            'Dùng `json.dump` với `ensure_ascii=False`.',
            'Sau khi `json.load`, truy cập `du_lieu["hoc_sinh"]` để lấy danh sách.',
          ],
          starterCode: [
            'import json',
            '',
            'n = int(input())',
            'danh_sach = []',
            '',
            'for i in range(n):',
            '    phan = input().split()',
            '    # Thêm {"ten": ..., "diem": ...} vào danh_sach',
            '',
            '# Ghi ra JSON, đọc lại, rồi thống kê',
          ].join('\n'),
          solutionCode: [
            'import json',
            '',
            'n = int(input())',
            'danh_sach = []',
            'for i in range(n):',
            '    phan = input().split()',
            '    danh_sach.append({"ten": phan[0], "diem": float(phan[1])})',
            '',
            'with open("lop.json", "w", encoding="utf-8") as f:',
            '    json.dump({"hoc_sinh": danh_sach}, f, ensure_ascii=False, indent=2)',
            '',
            'with open("lop.json", "r", encoding="utf-8") as f:',
            '    du_lieu = json.load(f)',
            '',
            'hs = du_lieu["hoc_sinh"]',
            'tong = 0',
            'for x in hs:',
            '    tong += x["diem"]',
            '',
            'print(f"Si so: {len(hs)}")',
            'print(f"Trung binh: {tong / len(hs):.2f}")',
          ].join('\n'),
          tier: 'NANG_CAO',
          judgeMode: 'IO_MATCH',
          tests: [
            sample(
              '3\nLan 8.5\nMinh 9\nHoa 7.5\n',
              'Si so: 3\nTrung binh: 8.33\n',
              'Tổng 25 chia 3 được 8.333..., làm tròn 8.33.',
            ),
            sample('1\nAn 10\n', 'Si so: 1\nTrung binh: 10.00\n'),
            hidden('2\nA 0\nB 10\n', 'Si so: 2\nTrung binh: 5.00\n', 25),
            hidden('4\nA 5\nB 6\nC 7\nD 8\n', 'Si so: 4\nTrung binh: 6.50\n', 25),
            hidden('5\nA 1\nB 2\nC 3\nD 4\nE 5\n', 'Si so: 5\nTrung binh: 3.00\n', 25),
            hidden('3\nX 9.99\nY 9.99\nZ 9.99\n', 'Si so: 3\nTrung binh: 9.99\n', 25),
          ],
        }),
      ],
    },
  ],
};

export const module9: ModuleSpec = {
  slug: 'tong-ket-khoa-hoc',
  title: 'Tổng kết khoá học',
  description: 'Buổi cuối: hoàn thiện một dự án của riêng em và nhìn lại chặng đường 30 buổi.',
  lessons: [
    {
      order: 30,
      slug: 'b30-du-an-cuoi-khoa',
      title: 'Dự án cuối khoá & Trình bày',
      summary:
        'Tự chọn một đề tài, xây dựng chương trình hoàn chỉnh và giới thiệu nó với lớp.',
      objectives: [
        'Lập kế hoạch cho một chương trình từ đầu đến cuối',
        'Kết hợp nhiều kiến thức đã học trong một sản phẩm',
        'Trình bày được ý tưởng và cách làm của mình',
      ],
      difficulty: 4,
      status: 'RECOMMENDED',
      teacherNotes:
        'Buổi tổng kết (⟨derived⟩). Học sinh dừng ở buổi 16 vẫn đã hoàn thành khoá học; buổi này ' +
        'dành cho các em muốn làm thêm một sản phẩm của riêng mình.',
      isDerived: true,
      blocks: [
        theory('Làm một dự án như thế nào?', [
          'Một dự án nhỏ vẫn nên đi theo bốn bước:',
          '',
          '**1. Chọn đề tài** — thứ em thật sự muốn dùng. Vài gợi ý:',
          '',
          '- Sổ quản lý chi tiêu cá nhân (List + Dictionary + tệp)',
          '- Trò chơi đố vui nhiều câu hỏi (List + vòng lặp + rẽ nhánh)',
          '- Máy tính điểm trung bình cả năm (nhập, tính, lưu JSON)',
          '- Trò chơi đoán từ (chuỗi + vòng lặp + điều kiện)',
          '',
          '**2. Chia nhỏ** — viết ra 3–5 việc con. Ví dụ với sổ chi tiêu: nhập khoản chi → lưu vào danh sách → ' +
            'ghi ra tệp → đọc lại và thống kê.',
          '',
          '**3. Làm từng phần, chạy thử ngay** — đừng viết hết 100 dòng rồi mới chạy. ' +
            'Viết 10 dòng, chạy thử, sửa, rồi viết tiếp.',
          '',
          '**4. Hoàn thiện** — thêm xử lý lỗi bằng `try`/`except`, thêm ghi chú, đặt tên biến cho dễ đọc.',
        ], [
          'Chọn đề tài mình thật sự muốn dùng',
          'Chia nhỏ thành 3–5 việc con',
          'Viết ít, chạy thử ngay, rồi mới viết tiếp',
        ]),
        example('Bộ khung một dự án hoàn chỉnh', 'Dùng làm mẫu để em bắt đầu.', [
          'import json',
          '',
          '# ===== CAC HAM TIEN ICH =====',
          '',
          'def doc_du_lieu(ten_tep):',
          '    try:',
          '        with open(ten_tep, "r", encoding="utf-8") as f:',
          '            return json.load(f)',
          '    except FileNotFoundError:',
          '        return []',
          '',
          'def ghi_du_lieu(ten_tep, du_lieu):',
          '    with open(ten_tep, "w", encoding="utf-8") as f:',
          '        json.dump(du_lieu, f, ensure_ascii=False, indent=2)',
          '',
          'def them_khoan_chi(danh_sach, mo_ta, so_tien):',
          '    danh_sach.append({"mo_ta": mo_ta, "so_tien": so_tien})',
          '    return danh_sach',
          '',
          'def thong_ke(danh_sach):',
          '    if len(danh_sach) == 0:',
          '        return 0, 0',
          '    tong = sum(x["so_tien"] for x in danh_sach)',
          '    return tong, tong / len(danh_sach)',
          '',
          '# ===== CHUONG TRINH CHINH =====',
          '',
          'if __name__ == "__main__":',
          '    chi_tieu = doc_du_lieu("chi_tieu.json")',
          '',
          '    chi_tieu = them_khoan_chi(chi_tieu, "An sang", 25000)',
          '    chi_tieu = them_khoan_chi(chi_tieu, "Mua but", 15000)',
          '',
          '    ghi_du_lieu("chi_tieu.json", chi_tieu)',
          '',
          '    tong, tb = thong_ke(chi_tieu)',
          '    print(f"So khoan  : {len(chi_tieu)}")',
          '    print(f"Tong chi  : {tong:,} dong")',
          '    print(f"Trung binh: {tb:,.0f} dong")',
        ], {
          output: ['So khoan  : 2', 'Tong chi  : 40,000 dong', 'Trung binh: 20,000 dong'].join('\n'),
          notes: [
            'Cấu trúc "các hàm ở trên, chương trình chính ở dưới" giúp code dễ đọc và dễ sửa.',
            '`doc_du_lieu` trả về danh sách rỗng khi chưa có tệp — chương trình chạy được ngay lần đầu.',
            'Đây là bộ khung em có thể sao chép và đổi thành đề tài của mình.',
          ],
        }),
        playground('Sân chơi: bắt đầu dự án của em', [
          'Không có yêu cầu cố định. Hãy bắt đầu viết dự án của riêng em ở đây.',
          '',
          'Cứ viết một phần nhỏ rồi chạy thử. Không cần hoàn hảo ngay từ đầu.',
        ], [
          '# Du an cua em',
          '# De tai: ...',
          '# Cac viec can lam:',
          '#   1.',
          '#   2.',
          '#   3.',
          '',
        ], 'Có được bộ khung dự án chạy được, dù còn đơn giản.'),
        projectBlock(
          'Nộp dự án cuối khoá',
          [
            'Nộp tệp `.py` của em cùng một mô tả ngắn.',
            '',
            '**Trong phần mô tả, hãy trả lời ba câu:**',
            '',
            '1. Chương trình của em làm gì?',
            '2. Em đã dùng những kiến thức nào đã học?',
            '3. Phần nào khó nhất, và em đã giải quyết ra sao?',
            '',
            '**Thầy cô sẽ xem theo các tiêu chí:**',
            '',
            '- Chương trình chạy được và làm đúng việc đã mô tả',
            '- Có sử dụng ít nhất ba nhóm kiến thức khác nhau (ví dụ: vòng lặp, danh sách, hàm)',
            '- Code có ghi chú và tên biến dễ hiểu',
            '- Có xử lý ít nhất một trường hợp dữ liệu sai',
          ],
          'CUSTOM',
          [
            'Chọn được đề tài và viết ra 3–5 việc cần làm',
            'Hoàn thành phần nhập và xử lý dữ liệu',
            'Hoàn thành phần hiển thị kết quả',
            'Thêm xử lý lỗi và ghi chú, rồi nộp bài',
          ],
          { minutes: 60 },
        ),
        quizBlock({
          slug: 'q-b30-tong-ket-khoa',
          title: 'Tổng kết kiến thức toàn khoá',
          passingScore: 60,
          questions: [
            {
              type: 'MULTIPLE_CHOICE',
              prompt: 'Cấu trúc dữ liệu nào phù hợp nhất để lưu điểm theo tên môn học?',
              explanation: 'Từ điển cho phép tra cứu theo tên môn, đúng nhu cầu ở đây.',
              choices: [
                { text: 'Dictionary — từ điển', isCorrect: true },
                { text: 'List — danh sách' },
                { text: 'Tuple' },
                { text: 'Một biến số thực' },
              ],
            },
            {
              type: 'MULTIPLE_CHOICE',
              prompt: 'Vì sao nên dùng `with open(...)` thay vì `open(...)` rồi tự đóng?',
              explanation: '`with` tự đóng tệp kể cả khi có lỗi xảy ra giữa chừng.',
              choices: [
                { text: 'Vì `with` tự đóng tệp, kể cả khi có lỗi', isCorrect: true },
                { text: 'Vì `with` chạy nhanh hơn' },
                { text: 'Vì `with` cho phép ghi tiếng Việt' },
                { text: 'Không có khác biệt' },
              ],
            },
            {
              type: 'MULTIPLE_CHOICE',
              prompt: 'Sự khác nhau cơ bản giữa `return` và `print` trong một hàm là gì?',
              explanation:
                '`return` trả giá trị về cho nơi gọi để dùng tiếp; `print` chỉ hiện ra màn hình.',
              choices: [
                { text: '`return` trả giá trị về nơi gọi; `print` chỉ hiện ra màn hình', isCorrect: true },
                { text: 'Không có khác biệt, chỉ khác cách viết' },
                { text: '`print` nhanh hơn `return`' },
                { text: '`return` chỉ dùng được với số' },
              ],
            },
            {
              type: 'TRUE_FALSE',
              prompt: 'Mở tệp bằng chế độ `"w"` sẽ xoá hết nội dung cũ của tệp.',
              explanation: 'Đúng. Muốn giữ nội dung cũ và ghi thêm, phải dùng chế độ `"a"`.',
              choices: [{ text: 'Đúng', isCorrect: true }, { text: 'Sai' }],
            },
            {
              type: 'SHORT_ANSWER',
              prompt:
                'Hãy mô tả ngắn gọn dự án cuối khoá của em: nó làm gì, và em đã dùng những kiến thức nào ' +
                'trong 30 buổi vừa qua?',
              explanation:
                'Câu này không có đáp án đúng sai. Thầy cô đọc để hiểu em đã kết nối các kiến thức ra sao.',
              points: 25,
            },
          ],
        }),
        reflection(
          'Nhìn lại 30 buổi',
          'Ở buổi 1, em đã viết một câu về điều mình muốn làm được. Hãy đọc lại câu đó. ' +
            'Em đã đi được tới đâu? Và bước tiếp theo của em là gì — khoá Pygame, hay khoá Nâng cao?',
        ),
      ],
    },
  ],
};
