/**
 * Python Cơ Bản — Module 3 & 4 (Buổi 8–16).
 *
 * Session 16 is the guaranteed-completion checkpoint. The lesson plan notes that
 * some students will max out at Loops, so everything up to here is REQUIRED and a
 * student who stops at session 16 is shown as having completed the course —
 * progress is computed over resolved-required lessons, not over all 30.
 */
import type { ModuleSpec } from '../types.ts';
import {
  challenge,
  example,
  hidden,
  playground,
  projectBlock,
  quizBlock,
  reflection,
  sample,
  theory,
} from '../builders.ts';

export const module3: ModuleSpec = {
  slug: 'cau-truc-dieu-khien',
  title: 'Cấu trúc điều khiển',
  description:
    'Dạy chương trình biết ra quyết định. Từ buổi này, chương trình không còn chạy thẳng một mạch ' +
    'mà rẽ nhánh tuỳ theo dữ liệu.',
  lessons: [
    {
      order: 8,
      slug: 'b08-cau-lenh-if-else',
      title: 'Câu lệnh `if` / `else`',
      summary:
        'Cấu trúc rẽ nhánh đầu tiên: nếu điều kiện đúng thì làm việc này, ngược lại thì làm việc kia.',
      objectives: [
        'Viết được câu lệnh `if` với điều kiện đúng cú pháp',
        'Bổ sung nhánh `else` cho trường hợp còn lại',
        'Giải thích được vai trò của dấu hai chấm và của thụt lề trong Python',
        'Đọc và sửa được lỗi `IndentationError`',
      ],
      difficulty: 2,
      status: 'REQUIRED',
      teacherNotes: 'Lesson 4. Thụt lề là điểm học sinh sai nhiều nhất — cho luyện thật kỹ.',
      blocks: [
        theory('Rẽ nhánh với `if`', [
          'Cho đến giờ, chương trình của em chạy thẳng từ trên xuống. `if` cho phép nó **chọn đường**.',
          '',
          '```python',
          'diem = 8',
          'if diem >= 5:',
          '    print("Ban da qua mon")',
          '```',
          '',
          'Hai chi tiết cú pháp bắt buộc:',
          '',
          '1. **Dấu hai chấm `:`** ở cuối dòng `if`. Thiếu là lỗi ngay.',
          '2. **Thụt lề** 4 dấu cách cho khối lệnh bên trong.',
          '',
          'Ở hầu hết ngôn ngữ khác, thụt lề chỉ để cho đẹp. Trong Python, **thụt lề chính là cú pháp** — ' +
            'nó quyết định lệnh nào thuộc về `if` và lệnh nào không.',
          '',
          '```python',
          'if diem >= 5:',
          '    print("Qua mon")      # thuộc if — chỉ chạy khi điều kiện đúng',
          'print("Ket thuc")         # KHÔNG thuộc if — luôn chạy',
          '```',
        ], [
          'Dòng `if` luôn kết thúc bằng dấu `:`',
          'Thụt lề 4 dấu cách xác định khối lệnh — đây là cú pháp, không phải trang trí',
          'Điều kiện phải cho ra True hoặc False',
        ]),
        theory('Thêm nhánh `else`', [
          '`else` bắt mọi trường hợp còn lại. Không có điều kiện đi kèm, và cũng kết thúc bằng dấu `:`.',
          '',
          '```python',
          'if diem >= 5:',
          '    print("Qua mon")',
          'else:',
          '    print("Can co gang them")',
          '```',
          '',
          'Một cặp `if`/`else` luôn chạy **đúng một** trong hai nhánh — không bao giờ cả hai, không bao giờ không nhánh nào.',
        ], [
          '`else` không có điều kiện',
          '`if`/`else` luôn chạy đúng một nhánh',
        ]),
        example(
          'Kiểm tra số chẵn lẻ',
          'Bài toán kinh điển: dùng phép chia lấy dư `%` đã học ở buổi 2.',
          [
            'so = int(input("Nhap mot so nguyen: "))',
            '',
            'if so % 2 == 0:',
            '    print(f"{so} la so chan")',
            'else:',
            '    print(f"{so} la so le")',
            '',
            'print("Da kiem tra xong")   # dòng này luôn chạy',
          ],
          {
            output: ['7 la so le', 'Da kiem tra xong'].join('\n'),
            notes: [
              'Ví dụ tương ứng với đầu vào 7.',
              'Dòng `print("Da kiem tra xong")` không thụt lề nên nằm ngoài if/else và luôn được thực hiện.',
              '`so % 2 == 0` đọc là: "phần dư khi chia 2 có bằng 0 không".',
            ],
          },
        ),
        playground('Sân chơi: đủ tuổi hay chưa?', [
          'Viết chương trình hỏi tuổi và cho biết người đó đã đủ 15 tuổi để tham gia câu lạc bộ lập trình chưa.',
          '',
          'Sau đó thử **cố tình xoá thụt lề** ở dòng `print` bên trong `if` và chạy lại — ' +
            'hãy đọc kỹ thông báo lỗi mà Python đưa ra. Biết mặt lỗi trước sẽ đỡ hoảng khi gặp lỗi thật.',
        ], [
          'tuoi = int(input("Em bao nhieu tuoi? "))',
          '',
          'if tuoi >= 15:',
          '    print("Du tuoi tham gia")',
          'else:',
          '    print("Chua du tuoi, hen em nam sau")',
        ], 'Chạy đúng cả hai nhánh và nhận diện được lỗi IndentationError khi xoá thụt lề.'),
        challenge({
          slug: 'p-b08-so-lon-nhat-hai-so',
          title: 'Số lớn hơn trong hai số',
          statement: [
            'Đọc **hai số nguyên** trên hai dòng, in ra số lớn hơn.',
            '',
            'Nếu hai số bằng nhau, in ra `Hai so bang nhau`.',
            '',
            'Đầu ra chỉ gồm **một dòng**.',
          ].join('\n'),
          hints: [
            'Xét ba trường hợp: a > b, b > a, và a bằng b.',
            'Em có thể lồng một `if`/`else` bên trong nhánh `else` của cái ngoài.',
            'Nhớ thụt lề thêm 4 dấu cách cho mỗi mức lồng nhau.',
          ],
          starterCode: ['a = int(input())', 'b = int(input())', '', '# So sánh a và b'].join('\n'),
          solutionCode: [
            'a = int(input())',
            'b = int(input())',
            'if a > b:',
            '    print(a)',
            'else:',
            '    if b > a:',
            '        print(b)',
            '    else:',
            '        print("Hai so bang nhau")',
          ].join('\n'),
          tier: 'CO_BAN',
          judgeMode: 'IO_MATCH',
          tests: [
            sample('7\n3\n', '7\n', '7 lớn hơn 3.'),
            sample('4\n4\n', 'Hai so bang nhau\n', 'Trường hợp đặc biệt cần xử lý riêng.'),
            hidden('-5\n-9\n', '-5\n', 20),
            hidden('0\n100\n', '100\n', 20),
            hidden('-1\n-1\n', 'Hai so bang nhau\n', 30),
            hidden('999999\n1000000\n', '1000000\n', 30),
          ],
        }),
        quizBlock({
          slug: 'q-b08-if-else',
          title: 'Kiểm tra nhanh: if / else',
          questions: [
            {
              type: 'MULTIPLE_CHOICE',
              prompt: 'Dòng `if diem >= 5` thiếu thứ gì để chạy được?',
              explanation: 'Mọi dòng `if` phải kết thúc bằng dấu hai chấm.',
              choices: [
                { text: 'Dấu hai chấm `:` ở cuối dòng', isCorrect: true },
                { text: 'Dấu chấm phẩy `;` ở cuối dòng' },
                { text: 'Cặp ngoặc tròn quanh điều kiện' },
                { text: 'Từ khoá `then`' },
              ],
            },
            {
              type: 'TRUE_FALSE',
              prompt: 'Trong Python, thụt lề chỉ để code nhìn đẹp hơn, không ảnh hưởng đến cách chạy.',
              explanation:
                'Sai. Thụt lề là cú pháp: nó quyết định lệnh nào nằm trong khối `if` và lệnh nào nằm ngoài.',
              choices: [{ text: 'Đúng' }, { text: 'Sai', isCorrect: true }],
            },
            {
              type: 'MULTIPLE_CHOICE',
              prompt: 'Điều kiện nào kiểm tra một số `n` có chia hết cho 3 không?',
              explanation: 'Chia hết nghĩa là phần dư bằng 0, tức `n % 3 == 0`.',
              choices: [
                { text: 'n % 3 == 0', isCorrect: true },
                { text: 'n / 3 == 0' },
                { text: 'n // 3 == 0' },
                { text: 'n % 3 != 0' },
              ],
            },
          ],
        }),
      ],
    },

    {
      order: 9,
      slug: 'b09-elif-va-dieu-kien-long-nhau',
      title: '`elif` và điều kiện lồng nhau',
      summary:
        'Khi có nhiều hơn hai trường hợp, `elif` giúp chương trình gọn và dễ đọc hơn hẳn so với việc lồng nhiều `if`.',
      objectives: [
        'Dùng `elif` để xử lý nhiều trường hợp liên tiếp',
        'Giải thích được vì sao thứ tự các nhánh `elif` lại quan trọng',
        'Viết được điều kiện lồng nhau khi thật sự cần',
        'Chọn được giữa `elif` và điều kiện lồng nhau cho từng bài toán',
      ],
      difficulty: 3,
      status: 'REQUIRED',
      teacherNotes: 'Lesson 4 (tiếp). Nhấn mạnh: các nhánh elif được xét lần lượt từ trên xuống.',
      blocks: [
        theory('`elif` — thêm bao nhiêu nhánh cũng được', [
          '`elif` là viết tắt của *else if*. Nó cho phép xét nhiều trường hợp nối tiếp nhau:',
          '',
          '```python',
          'diem = 8.5',
          '',
          'if diem >= 8:',
          '    xep_loai = "Gioi"',
          'elif diem >= 6.5:',
          '    xep_loai = "Kha"',
          'elif diem >= 5:',
          '    xep_loai = "Trung binh"',
          'else:',
          '    xep_loai = "Can co gang"',
          '```',
          '',
          '**Quy tắc vàng:** Python xét từ trên xuống và **dừng ngay** ở nhánh đầu tiên đúng. ' +
            'Các nhánh còn lại không được xét nữa.',
          '',
          'Vì vậy **thứ tự rất quan trọng**. Nếu viết `elif diem >= 5` lên trước `if diem >= 8`, ' +
            'thì điểm 9 cũng sẽ rơi vào nhánh đầu tiên và bị xếp sai.',
        ], [
          '`elif` xét lần lượt từ trên xuống, dừng ở nhánh đúng đầu tiên',
          'Sắp xếp điều kiện từ chặt nhất đến lỏng nhất',
          'Một chuỗi if/elif/else chỉ chạy đúng một nhánh',
        ]),
        theory('Điều kiện lồng nhau', [
          'Đôi khi một quyết định phụ thuộc vào quyết định trước đó. Khi ấy ta **lồng** `if` vào trong `if`:',
          '',
          '```python',
          'if da_dang_ky:',
          '    if diem >= 8:',
          '        print("Duoc nhan hoc bong")',
          '    else:',
          '        print("Da dang ky nhung diem chua du")',
          'else:',
          '    print("Chua dang ky")',
          '```',
          '',
          'Mỗi mức lồng thêm 4 dấu cách thụt lề nữa.',
          '',
          '**Mẹo:** lồng quá ba tầng là dấu hiệu nên viết lại. Thường có thể gộp điều kiện bằng `and`:',
          '',
          '```python',
          'if da_dang_ky and diem >= 8:',
          '    print("Duoc nhan hoc bong")',
          '```',
        ], [
          'Mỗi mức lồng = thêm 4 dấu cách',
          'Lồng quá sâu thì nên gộp điều kiện bằng `and`',
        ]),
        example('Xếp loại học lực', 'Chú ý thứ tự các nhánh — thử đảo hai nhánh giữa và xem kết quả sai thế nào.', [
          'diem = float(input("Nhap diem trung binh: "))',
          '',
          'if diem >= 8:',
          '    xep_loai = "Gioi"',
          'elif diem >= 6.5:',
          '    xep_loai = "Kha"',
          'elif diem >= 5:',
          '    xep_loai = "Trung binh"',
          'else:',
          '    xep_loai = "Can co gang"',
          '',
          'print(f"Diem {diem} xep loai: {xep_loai}")',
        ], {
          output: 'Diem 7.0 xep loai: Kha',
          notes: [
            'Với điểm 7.0: nhánh `>= 8` sai, nhánh `>= 6.5` đúng nên dừng tại đó.',
            'Nếu đảo `elif diem >= 5` lên trước `elif diem >= 6.5`, điểm 7.0 sẽ bị xếp nhầm thành "Trung binh".',
          ],
        }),
        playground('Sân chơi: đổi điểm số sang điểm chữ', [
          'Hệ điểm chữ: A từ 8.5, B từ 7.0, C từ 5.5, D từ 4.0, còn lại là F.',
          '',
          'Viết chuỗi `if`/`elif`/`else` cho đúng thứ tự, rồi thử với các mốc 8.5, 8.4, 4.0, 3.9.',
        ], [
          'diem = float(input("Nhap diem: "))',
          '',
          'if diem >= 8.5:',
          '    print("A")',
          '# Thêm các nhánh elif còn lại',
        ], 'Chương trình xếp đúng điểm chữ ở mọi mốc ranh giới.'),
        challenge({
          slug: 'p-b09-xep-loai-hoc-luc',
          title: 'Xếp loại học lực',
          statement: [
            'Đọc **một số thực** là điểm trung bình, in ra xếp loại theo bảng sau:',
            '',
            '| Điểm | Xếp loại |',
            '|---|---|',
            '| Từ 8.0 trở lên | `Gioi` |',
            '| Từ 6.5 đến dưới 8.0 | `Kha` |',
            '| Từ 5.0 đến dưới 6.5 | `Trung binh` |',
            '| Dưới 5.0 | `Can co gang` |',
            '',
            'Nếu điểm nằm ngoài khoảng 0–10, in ra `Diem khong hop le`.',
            '',
            'Đầu ra chỉ gồm **một dòng**.',
          ].join('\n'),
          hints: [
            'Kiểm tra tính hợp lệ của điểm **trước tiên**, bằng một nhánh `if` riêng ở đầu.',
            'Sau đó dùng chuỗi elif, sắp xếp từ mốc cao nhất xuống thấp nhất.',
            'Điều kiện hợp lệ có thể viết gọn: `0 <= diem <= 10`.',
          ],
          starterCode: ['diem = float(input())', '', '# Kiểm tra hợp lệ trước, rồi mới xếp loại'].join('\n'),
          solutionCode: [
            'diem = float(input())',
            'if diem < 0 or diem > 10:',
            '    print("Diem khong hop le")',
            'elif diem >= 8:',
            '    print("Gioi")',
            'elif diem >= 6.5:',
            '    print("Kha")',
            'elif diem >= 5:',
            '    print("Trung binh")',
            'else:',
            '    print("Can co gang")',
          ].join('\n'),
          tier: 'CO_BAN',
          judgeMode: 'IO_MATCH',
          tests: [
            sample('8.5\n', 'Gioi\n', '8.5 lớn hơn mốc 8.0.'),
            sample('6.5\n', 'Kha\n', 'Đúng bằng mốc 6.5 thì vẫn thuộc loại Khá.'),
            sample('-2\n', 'Diem khong hop le\n', 'Điểm âm phải bị loại trước khi xếp loại.'),
            hidden('10\n', 'Gioi\n', 15),
            hidden('7.99\n', 'Kha\n', 15),
            hidden('5\n', 'Trung binh\n', 15),
            hidden('4.99\n', 'Can co gang\n', 15),
            hidden('0\n', 'Can co gang\n', 20),
            hidden('10.1\n', 'Diem khong hop le\n', 20),
          ],
        }),
      ],
    },

    {
      order: 10,
      slug: 'b10-luyen-tap-phan-loai-ra-quyet-dinh',
      title: 'Luyện tập: Phân loại & Ra quyết định',
      summary:
        'Một buổi luyện tập dày đặc để cấu trúc rẽ nhánh trở thành phản xạ trước khi bước sang vòng lặp.',
      objectives: [
        'Chuyển được một bảng quy tắc thành chuỗi `if`/`elif`/`else`',
        'Kết hợp toán tử logic với rẽ nhánh',
        'Xử lý đúng các giá trị ở ranh giới',
      ],
      difficulty: 3,
      status: 'REQUIRED',
      teacherNotes:
        'Buổi luyện tập (⟨derived⟩). Học sinh nhanh có thể làm thêm bài Nâng cao ở cuối buổi.',
      isDerived: true,
      blocks: [
        theory('Ba lỗi hay gặp khi viết điều kiện', [
          '**Lỗi 1 — sai thứ tự nhánh.** Luôn sắp từ điều kiện chặt nhất xuống lỏng nhất.',
          '',
          '**Lỗi 2 — quên trường hợp ranh giới.** Đề bài nói "từ 8 trở lên" thì phải là `>= 8`, không phải `> 8`. ' +
            'Hãy luôn tự thử với đúng giá trị mốc.',
          '',
          '**Lỗi 3 — viết `if` liên tiếp thay vì `elif`.** Hai đoạn dưới đây cho kết quả khác nhau:',
          '',
          '```python',
          '# SAI: cả hai nhánh đều có thể chạy',
          'if diem >= 5:',
          '    print("Qua mon")',
          'if diem >= 8:',
          '    print("Gioi")',
          '',
          '# ĐÚNG: chỉ một nhánh chạy',
          'if diem >= 8:',
          '    print("Gioi")',
          'elif diem >= 5:',
          '    print("Qua mon")',
          '```',
        ], [
          'Sắp nhánh từ chặt đến lỏng',
          'Luôn thử với giá trị đúng ở mốc ranh giới',
          '`if` liên tiếp có thể chạy nhiều nhánh; `elif` thì không',
        ]),
        example('Tính tiền vé tham quan', 'Một bảng giá thật, chuyển thẳng thành code.', [
          '# Bảng giá: dưới 6 tuổi miễn phí, 6-15 tuổi giá 20000,',
          '# 16-60 tuổi giá 50000, trên 60 tuổi giá 25000',
          '',
          'tuoi = int(input("Nhap tuoi: "))',
          '',
          'if tuoi < 6:',
          '    gia = 0',
          'elif tuoi <= 15:',
          '    gia = 20000',
          'elif tuoi <= 60:',
          '    gia = 50000',
          'else:',
          '    gia = 25000',
          '',
          'print(f"Gia ve: {gia:,} dong")',
        ], {
          output: 'Gia ve: 20,000 dong',
          notes: [
            'Ví dụ tương ứng với tuổi 12.',
            'Nhờ thứ tự nhánh, ở dòng `elif tuoi <= 15` ta đã chắc chắn tuổi >= 6 rồi nên không cần viết lại.',
            '`{gia:,}` thêm dấu phân cách hàng nghìn — một mẹo f-string từ buổi 6.',
          ],
        }),
        playground('Sân chơi: máy tính BMI', [
          'BMI = cân nặng (kg) chia cho bình phương chiều cao (m).',
          '',
          'Phân loại: dưới 18.5 là thiếu cân, 18.5–24.9 là bình thường, 25 trở lên là thừa cân.',
          '',
          'Nhớ dùng `**` cho phép bình phương.',
        ], [
          'can_nang = float(input("Can nang (kg): "))',
          'chieu_cao = float(input("Chieu cao (m): "))',
          '',
          'bmi = can_nang / (chieu_cao ** 2)',
          'print(f"BMI cua ban: {bmi:.1f}")',
          '',
          '# Thêm phần phân loại bằng if/elif/else',
        ], 'Tính đúng BMI và phân loại được cả ba nhóm.'),
        challenge({
          slug: 'p-b10-nam-nhuan',
          title: 'Kiểm tra năm nhuận',
          statement: [
            'Đọc **một số nguyên** là năm, cho biết đó có phải năm nhuận không.',
            '',
            'Quy tắc: một năm là năm nhuận nếu nó **chia hết cho 4** nhưng **không chia hết cho 100**, ' +
              'hoặc **chia hết cho 400**.',
            '',
            'In ra `Nam nhuan` hoặc `Khong phai nam nhuan`.',
          ].join('\n'),
          hints: [
            'Viết điều kiện thành một biểu thức logic dùng `and`, `or`.',
            'Chia hết cho 4 nghĩa là `nam % 4 == 0`.',
            'Nhớ đặt ngoặc: `(nam % 4 == 0 and nam % 100 != 0) or nam % 400 == 0`.',
          ],
          starterCode: ['nam = int(input())', '', '# Kiểm tra điều kiện năm nhuận'].join('\n'),
          solutionCode: [
            'nam = int(input())',
            'if (nam % 4 == 0 and nam % 100 != 0) or nam % 400 == 0:',
            '    print("Nam nhuan")',
            'else:',
            '    print("Khong phai nam nhuan")',
          ].join('\n'),
          tier: 'THU_THACH',
          judgeMode: 'IO_MATCH',
          tests: [
            sample('2024\n', 'Nam nhuan\n', '2024 chia hết cho 4 và không chia hết cho 100.'),
            sample('1900\n', 'Khong phai nam nhuan\n', '1900 chia hết cho 100 nhưng không chia hết cho 400.'),
            sample('2000\n', 'Nam nhuan\n', '2000 chia hết cho 400 nên vẫn là năm nhuận.'),
            hidden('2026\n', 'Khong phai nam nhuan\n', 20),
            hidden('2100\n', 'Khong phai nam nhuan\n', 20),
            hidden('1600\n', 'Nam nhuan\n', 30),
            hidden('2023\n', 'Khong phai nam nhuan\n', 30),
          ],
        }),
        challenge({
          slug: 'p-b10-tam-giac',
          title: 'Ba cạnh có tạo thành tam giác?',
          statement: [
            'Đọc **ba số thực** trên ba dòng, là độ dài ba cạnh.',
            '',
            'Ba đoạn tạo thành tam giác khi **tổng hai cạnh bất kỳ luôn lớn hơn cạnh còn lại** ' +
              '(và mọi cạnh đều dương).',
            '',
            'Nếu tạo thành tam giác, in thêm loại tam giác:',
            '',
            '- `Tam giac deu` — ba cạnh bằng nhau',
            '- `Tam giac can` — đúng hai cạnh bằng nhau',
            '- `Tam giac thuong` — ba cạnh khác nhau',
            '',
            'Nếu không tạo thành tam giác, in `Khong phai tam giac`.',
          ].join('\n'),
          hints: [
            'Kiểm tra cả ba bất đẳng thức: a+b>c, a+c>b, b+c>a.',
            'Đừng quên cạnh phải dương.',
            'Tam giác đều phải xét trước tam giác cân, vì tam giác đều cũng có hai cạnh bằng nhau.',
          ],
          starterCode: [
            'a = float(input())',
            'b = float(input())',
            'c = float(input())',
            '',
            '# Kiểm tra tam giác rồi phân loại',
          ].join('\n'),
          solutionCode: [
            'a = float(input())',
            'b = float(input())',
            'c = float(input())',
            '',
            'if a <= 0 or b <= 0 or c <= 0:',
            '    print("Khong phai tam giac")',
            'elif a + b > c and a + c > b and b + c > a:',
            '    if a == b and b == c:',
            '        print("Tam giac deu")',
            '    elif a == b or b == c or a == c:',
            '        print("Tam giac can")',
            '    else:',
            '        print("Tam giac thuong")',
            'else:',
            '    print("Khong phai tam giac")',
          ].join('\n'),
          tier: 'NANG_CAO',
          judgeMode: 'IO_MATCH',
          tests: [
            sample('3\n4\n5\n', 'Tam giac thuong\n', 'Ba cạnh khác nhau và thoả bất đẳng thức tam giác.'),
            sample('5\n5\n5\n', 'Tam giac deu\n'),
            sample('1\n2\n10\n', 'Khong phai tam giac\n', '1 + 2 không lớn hơn 10.'),
            hidden('5\n5\n8\n', 'Tam giac can\n', 20),
            hidden('0\n4\n5\n', 'Khong phai tam giac\n', 20),
            hidden('2\n2\n4\n', 'Khong phai tam giac\n', 30),
            hidden('7\n10\n7\n', 'Tam giac can\n', 30),
          ],
        }, { isOptional: true, markdown: 'Bài Nâng cao dành cho bạn nào muốn thử sức thêm. Không bắt buộc.' }),
      ],
    },

    {
      order: 11,
      slug: 'b11-du-an-nho-doan-so',
      title: 'Dự án nhỏ: Chương trình đoán số (một lượt)',
      summary:
        'Ghép toàn bộ Module 3 thành một trò chơi nhỏ. Phiên bản nhiều lượt sẽ được hoàn thiện ở buổi 14 khi có vòng lặp.',
      objectives: [
        'Xây dựng một chương trình hoàn chỉnh có nhập, xử lý rẽ nhánh và xuất',
        'Sinh số ngẫu nhiên bằng module `random`',
        'Đưa ra phản hồi hữu ích cho người chơi',
      ],
      difficulty: 3,
      status: 'REQUIRED',
      teacherNotes:
        'Buổi dự án nhỏ (⟨derived⟩), khép lại Module 3. Chỉ một lượt đoán vì học sinh chưa học vòng lặp.',
      isDerived: true,
      blocks: [
        theory('Số ngẫu nhiên với `random`', [
          'Python có sẵn công cụ sinh số ngẫu nhiên. Muốn dùng, ta **nhập** nó vào chương trình:',
          '',
          '```python',
          'import random',
          '',
          'so_bi_mat = random.randint(1, 100)   # số nguyên ngẫu nhiên từ 1 đến 100',
          '```',
          '',
          '`random.randint(a, b)` cho một số nguyên ngẫu nhiên **bao gồm cả** `a` và `b`.',
          '',
          'Dòng `import` luôn đặt ở **đầu tệp**. Em sẽ học kỹ về module ở buổi 26.',
          '',
          '💡 Khi cần chương trình cho kết quả giống nhau mỗi lần chạy để dễ kiểm tra, ' +
            'dùng `random.seed(42)` trước khi sinh số.',
        ], [
          '`import random` đặt ở đầu tệp',
          '`random.randint(1, 100)` cho số nguyên từ 1 đến 100',
        ]),
        example('Đoán số — một lượt', 'Chương trình hoàn chỉnh dùng đúng những gì đã học.', [
          'import random',
          '',
          'so_bi_mat = random.randint(1, 100)',
          'print("Toi dang nghi ve mot so tu 1 den 100.")',
          '',
          'doan = int(input("Ban doan so may? "))',
          '',
          'if doan == so_bi_mat:',
          '    print("Chinh xac! Ban gioi qua!")',
          'elif doan < so_bi_mat:',
          '    print(f"So cua toi lon hon {doan}.")',
          'else:',
          '    print(f"So cua toi nho hon {doan}.")',
          '',
          'print(f"So bi mat la {so_bi_mat}.")',
        ], {
          output: [
            'Toi dang nghi ve mot so tu 1 den 100.',
            'So cua toi lon hon 30.',
            'So bi mat la 67.',
          ].join('\n'),
          notes: [
            'Vì dùng số ngẫu nhiên nên mỗi lần chạy kết quả sẽ khác nhau.',
            'Ở buổi 14, em sẽ dùng vòng lặp `while` để cho người chơi đoán tới khi đúng.',
          ],
        }),
        playground('Sân chơi: thêm gợi ý "nóng / lạnh"', [
          'Nâng cấp trò chơi: nếu đoán lệch không quá 5 đơn vị thì báo "Rat gan!", lệch không quá 15 thì "Kha gan".',
          '',
          'Gợi ý: khoảng lệch là `abs(doan - so_bi_mat)`. Hàm `abs()` cho giá trị tuyệt đối.',
        ], [
          'import random',
          '',
          'so_bi_mat = random.randint(1, 100)',
          'doan = int(input("Ban doan so may? "))',
          'khoang_lech = abs(doan - so_bi_mat)',
          '',
          '# Thêm if/elif/else dựa trên khoang_lech',
        ], 'Trò chơi đưa ra được gợi ý nóng/lạnh dựa trên khoảng lệch.'),
        projectBlock(
          'Dự án buổi 11: trò chơi đoán số của riêng em',
          [
            'Hoàn thiện trò chơi theo ý em. Một vài hướng gợi ý:',
            '',
            '- Cho người chơi chọn mức khó (dễ 1–50, khó 1–1000)',
            '- Thêm lời chào có tên người chơi bằng f-string',
            '- Tính điểm dựa trên độ chính xác của lượt đoán',
            '',
            'Nộp tệp `.py` của em để thầy cô xem và góp ý.',
          ],
          'CUSTOM',
          [
            'Chương trình chạy được và sinh số ngẫu nhiên đúng phạm vi',
            'Có đủ ba nhánh phản hồi: đúng, lớn hơn, nhỏ hơn',
            'Có ít nhất một tính năng mở rộng do em tự nghĩ ra',
          ],
        ),
        reflection(
          'Nhìn lại Module 3',
          'Trong ba buổi vừa rồi, chỗ nào làm em thấy khó nhất? Em đã vượt qua nó bằng cách nào?',
        ),
      ],
    },
  ],
};

export const module4: ModuleSpec = {
  slug: 'vong-lap',
  title: 'Vòng lặp',
  description:
    'Dạy chương trình biết lặp lại công việc. Đây là mốc quan trọng nhất của khoá cơ bản — ' +
    'hoàn thành module này là em đã nắm được bộ công cụ đủ để tự viết chương trình thật.',
  lessons: [
    {
      order: 12,
      slug: 'b12-vong-lap-for-va-range',
      title: 'Vòng lặp `for` và `range()`',
      summary: 'Lặp một số lần biết trước — nền tảng của mọi bài toán tính tổng, đếm và duyệt.',
      objectives: [
        'Viết được vòng lặp `for` với `range()`',
        'Dùng đủ ba dạng của `range()`: một, hai và ba tham số',
        'Tích luỹ kết quả qua các vòng lặp bằng biến cộng dồn',
        'Duyệt được từng ký tự của một chuỗi',
      ],
      difficulty: 3,
      status: 'REQUIRED',
      teacherNotes: 'Lesson 5. Nhấn mạnh range(a, b) không bao gồm b — học sinh nhầm rất nhiều.',
      blocks: [
        theory('`for` và `range()`', [
          'Muốn in "Xin chao" năm lần, em không cần viết năm dòng `print`:',
          '',
          '```python',
          'for i in range(5):',
          '    print("Xin chao")',
          '```',
          '',
          'Ba dạng của `range()`:',
          '',
          '| Cách viết | Sinh ra các số |',
          '|---|---|',
          '| `range(5)` | 0, 1, 2, 3, 4 |',
          '| `range(2, 6)` | 2, 3, 4, 5 |',
          '| `range(0, 10, 2)` | 0, 2, 4, 6, 8 |',
          '',
          '⚠️ **Điểm quan trọng nhất:** `range(a, b)` **không bao gồm** `b`. ' +
            '`range(1, 11)` cho các số từ 1 đến 10.',
          '',
          'Biến `i` nhận lần lượt từng giá trị. Nếu không cần dùng đến nó, người ta thường đặt tên là `_`.',
        ], [
          '`range(n)` đếm từ 0 tới n-1',
          '`range(a, b)` không bao gồm b',
          '`range(a, b, buoc)` cho phép nhảy cách',
        ]),
        theory('Biến cộng dồn', [
          'Kỹ thuật quan trọng nhất khi dùng vòng lặp: một biến giữ kết quả tích luỹ qua các vòng.',
          '',
          '```python',
          'tong = 0                  # 1. khởi tạo TRƯỚC vòng lặp',
          'for i in range(1, 11):',
          '    tong = tong + i       # 2. cập nhật TRONG vòng lặp',
          'print(tong)               # 3. dùng SAU vòng lặp',
          '```',
          '',
          'Ba bước này luôn đi cùng nhau. Quên bước 1 sẽ báo lỗi; đặt bước 1 vào trong vòng lặp thì ' +
            'biến bị đặt lại mỗi vòng và kết quả luôn sai.',
          '',
          'Viết gọn: `tong += i` tương đương `tong = tong + i`. Tương tự có `-=`, `*=`, `/=`.',
        ], [
          'Khởi tạo trước vòng lặp, cập nhật trong, dùng sau',
          '`tong += i` là cách viết gọn của `tong = tong + i`',
        ]),
        example('Ba ví dụ kinh điển', 'Đọc kỹ vị trí của biến khởi tạo so với vòng lặp.', [
          '# 1. Tính tổng từ 1 đến 10',
          'tong = 0',
          'for i in range(1, 11):',
          '    tong += i',
          'print(f"Tong 1..10 = {tong}")',
          '',
          '# 2. Bảng cửu chương 7',
          'for i in range(1, 11):',
          '    print(f"7 x {i} = {7 * i}")',
          '',
          '# 3. Duyệt từng ký tự của chuỗi',
          'for ky_tu in "Da Lat":',
          '    print(ky_tu)',
        ], {
          output: [
            'Tong 1..10 = 55',
            '7 x 1 = 7',
            '7 x 2 = 14',
            '... (đến 7 x 10 = 70)',
            'D',
            'a',
            ' ',
            'L',
            'a',
            't',
          ].join('\n'),
          notes: [
            'Ví dụ 3 cho thấy `for` duyệt được cả chuỗi, không chỉ `range()`.',
            'Dấu cách trong "Da Lat" cũng là một ký tự và cũng được in ra.',
          ],
        }),
        playground('Sân chơi: đếm ngược', [
          'Dùng `range()` với bước âm để đếm ngược từ 10 về 1.',
          '',
          'Gợi ý: `range(10, 0, -1)`. Hãy thử đổi số 0 thành 1 và xem thiếu mất số nào.',
        ], [
          'for i in range(10, 0, -1):',
          '    print(i)',
          'print("Bat dau!")',
        ], 'Đếm ngược đúng từ 10 về 1 và giải thích được vì sao tham số thứ hai là 0.'),
        challenge({
          slug: 'p-b12-tong-va-trung-binh',
          title: 'Tổng và trung bình N số',
          statement: [
            'Dòng đầu là số nguyên `N`. `N` dòng tiếp theo, mỗi dòng một số thực.',
            '',
            'In ra **hai dòng**:',
            '',
            '```',
            'Tong: <tong>',
            'Trung binh: <trung_binh>',
            '```',
            '',
            'Cả hai đều hiển thị **đúng 2 chữ số thập phân**.',
          ].join('\n'),
          hints: [
            'Đọc N trước, rồi lặp đúng N lần để đọc các số còn lại.',
            'Khởi tạo `tong = 0` TRƯỚC vòng lặp.',
            'Trung bình là tổng chia cho N.',
          ],
          starterCode: [
            'n = int(input())',
            'tong = 0',
            '',
            'for i in range(n):',
            '    so = float(input())',
            '    # cộng dồn vào tong',
            '',
            '# In kết quả',
          ].join('\n'),
          solutionCode: [
            'n = int(input())',
            'tong = 0',
            'for i in range(n):',
            '    tong += float(input())',
            'print(f"Tong: {tong:.2f}")',
            'print(f"Trung binh: {tong / n:.2f}")',
          ].join('\n'),
          tier: 'CO_BAN',
          judgeMode: 'IO_MATCH',
          tests: [
            sample('3\n8\n9\n7\n', 'Tong: 24.00\nTrung binh: 8.00\n', '8 + 9 + 7 = 24, chia 3 được 8.'),
            sample('2\n5.5\n4.5\n', 'Tong: 10.00\nTrung binh: 5.00\n'),
            hidden('1\n7.25\n', 'Tong: 7.25\nTrung binh: 7.25\n', 20),
            hidden('4\n1\n2\n3\n4\n', 'Tong: 10.00\nTrung binh: 2.50\n', 20),
            hidden('5\n0\n0\n0\n0\n0\n', 'Tong: 0.00\nTrung binh: 0.00\n', 30),
            hidden('3\n1.111\n2.222\n3.333\n', 'Tong: 6.67\nTrung binh: 2.22\n', 30),
          ],
        }),
      ],
    },

    {
      order: 13,
      slug: 'b13-vong-lap-while',
      title: 'Vòng lặp `while`',
      summary:
        'Lặp khi chưa biết trước số lần — dùng khi điều kiện dừng phụ thuộc vào dữ liệu chạy thật.',
      objectives: [
        'Viết được vòng lặp `while` với điều kiện dừng rõ ràng',
        'Nhận ra và sửa được vòng lặp vô hạn',
        'Chọn đúng giữa `for` và `while` cho từng bài toán',
      ],
      difficulty: 3,
      status: 'REQUIRED',
      teacherNotes: 'Lesson 5 (tiếp). Cho học sinh cố tình tạo vòng lặp vô hạn một lần để hiểu vì sao nó xảy ra.',
      blocks: [
        theory('`while` — lặp khi điều kiện còn đúng', [
          '`for` dùng khi **biết trước** số lần lặp. `while` dùng khi **chưa biết**:',
          '',
          '```python',
          'so_du = 100',
          'while so_du > 0:',
          '    so_du -= 30',
          '    print(f"Con lai {so_du}")',
          '```',
          '',
          'Python kiểm tra điều kiện **trước mỗi vòng**. Khi điều kiện thành False, vòng lặp dừng.',
          '',
          '**Ba thứ một vòng `while` luôn cần:**',
          '',
          '1. Biến điều kiện được khởi tạo **trước** vòng lặp',
          '2. Điều kiện dừng ở dòng `while`',
          '3. Một dòng **thay đổi** biến điều kiện bên trong vòng lặp',
          '',
          'Thiếu điều thứ 3 là có vòng lặp vô hạn.',
        ], [
          '`for` khi biết trước số lần, `while` khi chưa biết',
          'Điều kiện được kiểm tra trước mỗi vòng',
          'Phải có dòng thay đổi biến điều kiện, nếu không sẽ lặp mãi',
        ]),
        theory('Vòng lặp vô hạn — nhận diện và tránh', [
          'Đoạn dưới đây chạy mãi không dừng:',
          '',
          '```python',
          'dem = 1',
          'while dem <= 5:',
          '    print(dem)',
          '    # QUÊN dòng dem += 1',
          '```',
          '',
          '`dem` không bao giờ đổi, nên `dem <= 5` mãi mãi là True.',
          '',
          'Trong DYE LMS, chương trình chạy quá thời gian cho phép sẽ bị dừng và báo ' +
            '**Quá thời gian (TLE)**. Đó thường là dấu hiệu của vòng lặp vô hạn.',
          '',
          'Khi gặp TLE, hãy tự hỏi: *biến trong điều kiện `while` có thay đổi ở đâu không?*',
        ], [
          'Vòng lặp vô hạn = quên cập nhật biến điều kiện',
          'Kết quả "Quá thời gian" thường là dấu hiệu của vòng lặp vô hạn',
        ]),
        example('So sánh `for` và `while`', 'Cùng một kết quả, hai cách viết.', [
          '# Cách 1: for — biết trước là 5 lần',
          'for i in range(1, 6):',
          '    print(i)',
          '',
          'print("---")',
          '',
          '# Cách 2: while — tự quản lý biến đếm',
          'dem = 1',
          'while dem <= 5:',
          '    print(dem)',
          '    dem += 1',
          '',
          'print("---")',
          '',
          '# Việc chỉ while làm được: lặp đến khi người dùng nhập số 0',
          'tong = 0',
          'so = int(input("Nhap so (0 de dung): "))',
          'while so != 0:',
          '    tong += so',
          '    so = int(input("Nhap so (0 de dung): "))',
          'print(f"Tong: {tong}")',
        ], {
          notes: [
            'Hai cách đầu cho kết quả giống hệt nhau — với số lần biết trước, `for` gọn hơn.',
            'Ví dụ cuối không viết được bằng `for` vì không ai biết người dùng sẽ nhập bao nhiêu số.',
            'Chú ý dòng `input()` xuất hiện hai lần: một lần trước vòng lặp, một lần cuối vòng lặp.',
          ],
        }),
        playground('Sân chơi: đoán số nhiều lượt', [
          'Bây giờ em đã có đủ công cụ để hoàn thiện trò chơi ở buổi 11: cho người chơi đoán tới khi đúng.',
        ], [
          'import random',
          '',
          'so_bi_mat = random.randint(1, 100)',
          'doan = int(input("Ban doan so may? "))',
          '',
          'while doan != so_bi_mat:',
          '    if doan < so_bi_mat:',
          '        print("Lon hon nhe!")',
          '    else:',
          '        print("Nho hon nhe!")',
          '    doan = int(input("Doan lai: "))',
          '',
          'print("Chinh xac!")',
        ], 'Trò chơi chạy đúng tới khi người chơi đoán ra, và biết đếm số lượt đã dùng.'),
        challenge({
          slug: 'p-b13-tong-chu-so',
          title: 'Tổng các chữ số của một số',
          statement: [
            'Đọc **một số nguyên không âm**, tính tổng các chữ số của nó.',
            '',
            'Ví dụ: 1234 → 1 + 2 + 3 + 4 = 10.',
            '',
            'In ra **một dòng** chứa tổng.',
          ].join('\n'),
          hints: [
            'Chữ số cuối cùng của `n` là `n % 10`.',
            'Bỏ chữ số cuối đi bằng `n = n // 10`.',
            'Lặp `while n > 0` cho tới khi không còn chữ số nào.',
            'Chú ý trường hợp n bằng 0.',
          ],
          starterCode: [
            'n = int(input())',
            'tong = 0',
            '',
            '# Dùng while, % 10 và // 10',
          ].join('\n'),
          solutionCode: [
            'n = int(input())',
            'tong = 0',
            'while n > 0:',
            '    tong += n % 10',
            '    n = n // 10',
            'print(tong)',
          ].join('\n'),
          tier: 'CO_BAN',
          judgeMode: 'IO_MATCH',
          tests: [
            sample('1234\n', '10\n', '1 + 2 + 3 + 4 = 10.'),
            sample('0\n', '0\n', 'Số 0 có tổng chữ số bằng 0 — vòng lặp không chạy lần nào.'),
            hidden('9\n', '9\n', 20),
            hidden('999\n', '27\n', 20),
            hidden('1000000\n', '1\n', 30),
            hidden('987654321\n', '45\n', 30),
          ],
        }),
      ],
    },

    {
      order: 14,
      slug: 'b14-break-continue-vong-lap-long-nhau',
      title: '`break`, `continue` và vòng lặp lồng nhau',
      summary:
        'Điều khiển vòng lặp tinh tế hơn: thoát sớm, bỏ qua một vòng, và lặp trong lặp để tạo bảng và hình.',
      objectives: [
        'Dùng `break` để thoát khỏi vòng lặp ngay lập tức',
        'Dùng `continue` để bỏ qua phần còn lại của vòng hiện tại',
        'Viết được vòng lặp lồng nhau và hiểu thứ tự chạy của chúng',
      ],
      difficulty: 4,
      status: 'REQUIRED',
      teacherNotes: 'Lesson 5 (tiếp). Vòng lặp lồng nhau là bước chuẩn bị cho phần vẽ hình ở buổi 15.',
      blocks: [
        theory('`break` và `continue`', [
          '**`break`** — thoát khỏi vòng lặp ngay lập tức, bỏ qua mọi vòng còn lại.',
          '',
          '```python',
          'for i in range(1, 101):',
          '    if i * i > 500:',
          '        print(f"So dau tien co binh phuong > 500 la {i}")',
          '        break',
          '```',
          '',
          '**`continue`** — bỏ qua phần còn lại của vòng **hiện tại**, nhảy sang vòng kế tiếp.',
          '',
          '```python',
          'for i in range(1, 11):',
          '    if i % 2 == 0:',
          '        continue          # bỏ qua số chẵn',
          '    print(i)              # chỉ in số lẻ',
          '```',
          '',
          'Cả hai đều chỉ tác động đến vòng lặp **gần nhất** bao quanh chúng.',
        ], [
          '`break` thoát hẳn vòng lặp',
          '`continue` bỏ qua vòng hiện tại, đi tiếp vòng sau',
          'Cả hai chỉ ảnh hưởng đến vòng lặp gần nhất',
        ]),
        theory('Vòng lặp lồng nhau', [
          'Một vòng lặp có thể nằm trong một vòng lặp khác:',
          '',
          '```python',
          'for hang in range(1, 4):',
          '    for cot in range(1, 4):',
          '        print(f"({hang},{cot})", end=" ")',
          '    print()               # xuống dòng sau mỗi hàng',
          '```',
          '',
          '**Cách chạy:** vòng ngoài chạy một lần thì vòng trong chạy **trọn vẹn** một lượt. ' +
            'Vòng ngoài 3 lần × vòng trong 3 lần = 9 lần in.',
          '',
          '💡 `print(..., end=" ")` in xong không xuống dòng mà thêm một dấu cách. ' +
            '`print()` không tham số thì chỉ xuống dòng. Hai mẹo này dùng rất nhiều khi vẽ bảng.',
        ], [
          'Vòng ngoài chạy 1 lần → vòng trong chạy trọn 1 lượt',
          '`end=" "` để in không xuống dòng',
          '`print()` rỗng để xuống dòng',
        ]),
        example('Bảng cửu chương đầy đủ', 'Hai vòng lặp lồng nhau tạo ra một bảng hoàn chỉnh.', [
          'for bang in range(2, 6):',
          '    for i in range(1, 11):',
          '        print(f"{bang} x {i} = {bang * i}", end="   ")',
          '    print()',
          '    print("-" * 60)',
        ], {
          output: [
            '2 x 1 = 2   2 x 2 = 4   2 x 3 = 6   ...   2 x 10 = 20',
            '------------------------------------------------------------',
            '3 x 1 = 3   3 x 2 = 6   3 x 3 = 9   ...   3 x 10 = 30',
            '------------------------------------------------------------',
            '...',
          ].join('\n'),
          notes: [
            '`"-" * 60` nhân chuỗi — cho ra 60 dấu gạch ngang. Đây là mẹo hay dùng để kẻ dòng.',
            'Dòng `print()` rỗng phải nằm trong vòng ngoài nhưng ngoài vòng trong. Thụt lề quyết định điều đó.',
          ],
        }),
        playground('Sân chơi: tìm số nguyên tố đầu tiên lớn hơn 100', [
          'Dùng vòng lặp lồng nhau và `break`.',
          '',
          'Ý tưởng: với mỗi số, thử chia nó cho các số từ 2 tới căn bậc hai của nó. ' +
            'Nếu chia hết cho số nào thì không phải nguyên tố.',
        ], [
          'so = 101',
          'while True:',
          '    la_nguyen_to = True',
          '    for uoc in range(2, int(so ** 0.5) + 1):',
          '        if so % uoc == 0:',
          '            la_nguyen_to = False',
          '            break',
          '    if la_nguyen_to:',
          '        print(so)',
          '        break',
          '    so += 1',
        ], 'Chương trình tìm đúng số nguyên tố đầu tiên lớn hơn 100 và em giải thích được vai trò của từng `break`.'),
        challenge({
          slug: 'p-b14-tim-uoc-so',
          title: 'Liệt kê các ước số',
          statement: [
            'Đọc **một số nguyên dương N**, in ra tất cả các ước số của N theo thứ tự tăng dần, ' +
              'cách nhau bằng **một dấu cách**, trên **một dòng**.',
            '',
            'Ví dụ N = 12 → `1 2 3 4 6 12`',
            '',
            'Chú ý: cuối dòng không có dấu cách thừa.',
          ].join('\n'),
          hints: [
            'Duyệt các số từ 1 đến N, kiểm tra `N % i == 0`.',
            'Để không có dấu cách thừa, hãy gom kết quả vào một chuỗi rồi in một lần.',
            'Hoặc dùng `print(i, end=" ")` rồi chấp nhận — nhưng bài này yêu cầu không có dấu cách cuối.',
          ],
          starterCode: [
            'n = int(input())',
            'ket_qua = ""',
            '',
            '# Duyệt từ 1 đến n, nối các ước số vào chuỗi ket_qua',
          ].join('\n'),
          solutionCode: [
            'n = int(input())',
            'ket_qua = ""',
            'for i in range(1, n + 1):',
            '    if n % i == 0:',
            '        if ket_qua == "":',
            '            ket_qua = str(i)',
            '        else:',
            '            ket_qua = ket_qua + " " + str(i)',
            'print(ket_qua)',
          ].join('\n'),
          tier: 'THU_THACH',
          judgeMode: 'IO_MATCH',
          tests: [
            sample('12\n', '1 2 3 4 6 12\n', '12 chia hết cho 1, 2, 3, 4, 6 và 12.'),
            sample('7\n', '1 7\n', 'Số nguyên tố chỉ có hai ước.'),
            hidden('1\n', '1\n', 20),
            hidden('16\n', '1 2 4 8 16\n', 20),
            hidden('100\n', '1 2 4 5 10 20 25 50 100\n', 30),
            hidden('97\n', '1 97\n', 30),
          ],
        }),
      ],
    },

    {
      order: 15,
      slug: 'b15-luyen-tap-ve-hinh-va-bang',
      title: 'Luyện tập: Vẽ hình & Bảng cửu chương',
      summary:
        'Buổi luyện tập vui: dùng vòng lặp lồng nhau để vẽ các hình bằng ký tự và in bảng số đẹp mắt.',
      objectives: [
        'Vận dụng vòng lặp lồng nhau để tạo hình theo mẫu',
        'Điều khiển việc xuống dòng bằng `end=` và `print()`',
        'Dùng phép nhân chuỗi để vẽ nhanh',
      ],
      difficulty: 3,
      status: 'REQUIRED',
      teacherNotes:
        'Buổi luyện tập (⟨derived⟩). Bài vẽ hình rất hiệu quả để học sinh "thấy" được vòng lặp lồng nhau.',
      isDerived: true,
      blocks: [
        theory('Vẽ hình bằng ký tự', [
          'Mỗi **hàng** của hình là một lần chạy vòng ngoài. Mỗi **ký tự** trên hàng là một lần chạy vòng trong.',
          '',
          'Có hai cách vẽ một hàng:',
          '',
          '```python',
          '# Cách 1: vòng lặp trong',
          'for j in range(5):',
          '    print("*", end="")',
          'print()',
          '',
          '# Cách 2: nhân chuỗi — gọn hơn nhiều',
          'print("*" * 5)',
          '```',
          '',
          'Với tam giác, số ký tự mỗi hàng thay đổi theo chỉ số hàng:',
          '',
          '```python',
          'for hang in range(1, 6):',
          '    print("*" * hang)',
          '```',
        ], [
          'Vòng ngoài = hàng, vòng trong = ký tự trên hàng',
          '`"*" * n` là cách vẽ một hàng nhanh nhất',
          'Số ký tự phụ thuộc chỉ số hàng thì hình sẽ là tam giác',
        ]),
        example('Bốn hình cơ bản', 'Đọc kỹ mối liên hệ giữa chỉ số hàng và số ký tự.', [
          'n = 5',
          '',
          'print("1. Hinh vuong")',
          'for hang in range(n):',
          '    print("*" * n)',
          '',
          'print("\\n2. Tam giac vuong")',
          'for hang in range(1, n + 1):',
          '    print("*" * hang)',
          '',
          'print("\\n3. Tam giac nguoc")',
          'for hang in range(n, 0, -1):',
          '    print("*" * hang)',
          '',
          'print("\\n4. Tam giac can")',
          'for hang in range(1, n + 1):',
          '    khoang_trang = " " * (n - hang)',
          '    sao = "*" * (2 * hang - 1)',
          '    print(khoang_trang + sao)',
        ], {
          output: [
            '4. Tam giac can',
            '    *',
            '   ***',
            '  *****',
            ' *******',
            '*********',
          ].join('\n'),
          notes: [
            'Hình 4 là hình khó nhất: mỗi hàng có `(n - hang)` dấu cách rồi `(2*hang - 1)` dấu sao.',
            'Hãy tự kiểm tra công thức với hàng 1: 4 dấu cách + 1 sao. Đúng như hình.',
            '`\\n` bên trong chuỗi là ký tự xuống dòng.',
          ],
        }),
        playground('Sân chơi: vẽ hình của em', [
          'Thử vẽ các hình sau:',
          '',
          '- Hình chữ nhật rỗng (chỉ có viền)',
          '- Hình thoi',
          '- Bàn cờ xen kẽ `#` và khoảng trắng',
          '',
          'Cứ thử và sai thoải mái — vẽ hình là cách học vòng lặp thú vị nhất.',
        ], [
          'n = 5',
          '',
          '# Hình chữ nhật rỗng',
          'for hang in range(n):',
          '    if hang == 0 or hang == n - 1:',
          '        print("*" * n)',
          '    else:',
          '        print("*" + " " * (n - 2) + "*")',
        ], 'Vẽ được ít nhất hai hình khác nhau bằng vòng lặp lồng nhau.'),
        challenge({
          slug: 'p-b15-tam-giac-so',
          title: 'Tam giác số',
          statement: [
            'Đọc **một số nguyên dương N**, in ra tam giác số như sau.',
            '',
            'Với N = 4:',
            '',
            '```',
            '1',
            '1 2',
            '1 2 3',
            '1 2 3 4',
            '```',
            '',
            'Các số trên cùng hàng cách nhau **một dấu cách**, cuối hàng **không** có dấu cách thừa.',
          ].join('\n'),
          hints: [
            'Vòng ngoài chạy từ 1 đến N — đó là số hàng.',
            'Vòng trong ở hàng thứ `h` chạy từ 1 đến `h`.',
            'Gom các số của một hàng vào chuỗi rồi in một lần để tránh dấu cách thừa.',
          ],
          starterCode: [
            'n = int(input())',
            '',
            'for hang in range(1, n + 1):',
            '    dong = ""',
            '    # Nối các số từ 1 đến hang vào chuỗi dong',
            '    print(dong)',
          ].join('\n'),
          solutionCode: [
            'n = int(input())',
            'for hang in range(1, n + 1):',
            '    dong = ""',
            '    for so in range(1, hang + 1):',
            '        if dong == "":',
            '            dong = str(so)',
            '        else:',
            '            dong = dong + " " + str(so)',
            '    print(dong)',
          ].join('\n'),
          tier: 'CO_BAN',
          judgeMode: 'IO_MATCH',
          tests: [
            sample('4\n', '1\n1 2\n1 2 3\n1 2 3 4\n', 'Hàng thứ h chứa các số từ 1 đến h.'),
            sample('1\n', '1\n', 'N = 1 chỉ có một hàng.'),
            hidden('2\n', '1\n1 2\n', 20),
            hidden('5\n', '1\n1 2\n1 2 3\n1 2 3 4\n1 2 3 4 5\n', 30),
            hidden('3\n', '1\n1 2\n1 2 3\n', 50),
          ],
        }),
        challenge({
          slug: 'p-b15-kim-tu-thap',
          title: 'Kim tự tháp cân',
          statement: [
            'Đọc **một số nguyên dương N**, in ra kim tự tháp bằng dấu `*`.',
            '',
            'Với N = 4:',
            '',
            '```',
            '   *',
            '  ***',
            ' *****',
            '*******',
            '```',
            '',
            'Hàng thứ `h` có `N - h` dấu cách đứng trước, rồi `2h - 1` dấu sao. ' +
              'Cuối hàng **không** có khoảng trắng thừa.',
          ].join('\n'),
          hints: [
            'Số dấu cách của hàng h là `n - h`.',
            'Số dấu sao của hàng h là `2 * h - 1`.',
            'Dùng phép nhân chuỗi cho cả hai phần rồi nối lại.',
          ],
          starterCode: ['n = int(input())', '', 'for h in range(1, n + 1):', '    # Ghép khoảng trắng và dấu sao'].join('\n'),
          solutionCode: [
            'n = int(input())',
            'for h in range(1, n + 1):',
            '    print(" " * (n - h) + "*" * (2 * h - 1))',
          ].join('\n'),
          tier: 'NANG_CAO',
          judgeMode: 'IO_MATCH',
          tests: [
            sample('4\n', '   *\n  ***\n *****\n*******\n', 'Hàng 1 có 3 dấu cách và 1 dấu sao.'),
            sample('1\n', '*\n'),
            hidden('2\n', ' *\n***\n', 25),
            hidden('3\n', '  *\n ***\n*****\n', 25),
            hidden('5\n', '    *\n   ***\n  *****\n *******\n*********\n', 50),
          ],
        }, { isOptional: true, markdown: 'Bài Nâng cao. Hãy tự viết công thức ra giấy trước khi code.' }),
      ],
    },

    {
      order: 16,
      slug: 'b16-on-tap-va-kiem-tra-giua-khoa',
      title: 'Ôn tập & Kiểm tra giữa khoá',
      summary:
        'Tổng kết toàn bộ nền tảng từ buổi 1 đến buổi 15. Hoàn thành buổi này là em đã nắm trọn ' +
        'bộ công cụ cốt lõi của Python và có thể tự viết chương trình thật.',
      objectives: [
        'Hệ thống lại biến, kiểu dữ liệu, toán tử, rẽ nhánh và vòng lặp',
        'Giải được bài toán tổng hợp cần kết hợp nhiều kiến thức',
        'Tự đánh giá được mình đang vững ở đâu và cần luyện thêm chỗ nào',
      ],
      difficulty: 3,
      status: 'REQUIRED',
      teacherNotes:
        'MỐC QUAN TRỌNG (⟨derived⟩): đây là mốc hoàn thành đảm bảo. Theo kế hoạch bài giảng, ' +
        'có học sinh sẽ dừng lại quanh Lesson 5 (vòng lặp). Hệ thống tính tiến độ theo các bài BẮT BUỘC ' +
        'được phân cho từng em, nên học sinh dừng ở buổi 16 vẫn hiển thị hoàn thành 100% khoá học. ' +
        'Từ buổi 20 trở đi nội dung là tuỳ chọn.',
      blocks: [
        theory('Bản đồ kiến thức 15 buổi đầu', [
          '| Chủ đề | Công cụ chính | Buổi |',
          '|---|---|---|',
          '| Tính toán | `+ - * / // % **` | 1–2 |',
          '| Lưu dữ liệu | biến, `int` `float` `str` `bool` | 3 |',
          '| Đổi kiểu | `int()` `float()` `str()` | 4 |',
          '| So sánh & logic | `== != > <`, `and` `or` `not` | 5 |',
          '| Giao tiếp | `input()`, `print()`, f-string | 6–7 |',
          '| Rẽ nhánh | `if` `elif` `else` | 8–11 |',
          '| Lặp | `for` `range()`, `while` | 12–13 |',
          '| Điều khiển lặp | `break`, `continue`, lồng nhau | 14–15 |',
          '',
          '**Ba lỗi thường gặp nhất — hãy tự kiểm tra:**',
          '',
          '1. Dùng `=` khi cần `==`',
          '2. Quên `int()` quanh `input()` khi cần tính toán',
          '3. Quên cập nhật biến điều kiện trong `while` → vòng lặp vô hạn',
        ], [
          'Em đã có đủ công cụ để viết chương trình thật',
          'Ba lỗi kinh điển: `=` vs `==`, quên ép kiểu, vòng lặp vô hạn',
        ]),
        example('Một chương trình dùng gần hết mọi thứ đã học', 'Đọc và chỉ ra từng kiến thức xuất hiện ở đâu.', [
          '# Thong ke diem cua ca lop',
          'n = int(input("So hoc sinh: "))',
          '',
          'tong = 0',
          'cao_nhat = -1',
          'thap_nhat = 11',
          'so_dat = 0',
          '',
          'for i in range(n):',
          '    diem = float(input(f"Diem hoc sinh {i + 1}: "))',
          '',
          '    if diem < 0 or diem > 10:',
          '        print("  Diem khong hop le, bo qua")',
          '        continue',
          '',
          '    tong += diem',
          '    if diem > cao_nhat:',
          '        cao_nhat = diem',
          '    if diem < thap_nhat:',
          '        thap_nhat = diem',
          '    if diem >= 5:',
          '        so_dat += 1',
          '',
          'print(f"Trung binh : {tong / n:.2f}")',
          'print(f"Cao nhat   : {cao_nhat:.1f}")',
          'print(f"Thap nhat  : {thap_nhat:.1f}")',
          'print(f"So dat     : {so_dat}/{n}")',
        ], {
          notes: [
            '`cao_nhat` khởi tạo bằng -1 để mọi điểm hợp lệ đều lớn hơn nó ở lần so sánh đầu.',
            '`thap_nhat` khởi tạo bằng 11 với lý do ngược lại.',
            '`continue` bỏ qua điểm không hợp lệ mà không làm dừng cả vòng lặp.',
          ],
        }),
        playground('Sân chơi ôn tập tự do', [
          'Không có yêu cầu cố định. Hãy thử viết lại một trong các chương trình đã làm mà không nhìn bài cũ:',
          '',
          '- Xếp loại học lực',
          '- Tổng các chữ số',
          '- Tam giác số',
          '',
          'Viết lại được từ đầu nghĩa là em đã thật sự hiểu, chứ không chỉ nhớ.',
        ], ['# Không gian tự do — viết lại một chương trình cũ theo trí nhớ', ''], 'Viết lại được ít nhất một chương trình cũ mà không cần xem lại bài.'),
        challenge({
          slug: 'p-b16-kiem-tra-thong-ke-diem',
          title: 'Kiểm tra giữa khoá: Thống kê điểm',
          statement: [
            'Dòng đầu là số nguyên `N` — số học sinh. `N` dòng tiếp theo, mỗi dòng một điểm (số thực).',
            '',
            'In ra **bốn dòng** theo đúng mẫu:',
            '',
            '```',
            'Trung binh: <tb>',
            'Cao nhat: <max>',
            'Thap nhat: <min>',
            'So ban dat: <dem>',
            '```',
            '',
            '- `<tb>` hiển thị **2 chữ số thập phân**',
            '- `<max>`, `<min>` hiển thị **1 chữ số thập phân**',
            '- `<dem>` là số bạn có điểm **từ 5.0 trở lên**',
            '',
            'Đề bảo đảm N ≥ 1 và mọi điểm đều nằm trong khoảng 0–10.',
          ].join('\n'),
          hints: [
            'Cần bốn biến tích luỹ: tổng, cao nhất, thấp nhất, số bạn đạt.',
            'Khởi tạo cao nhất bằng một số rất nhỏ và thấp nhất bằng một số rất lớn.',
            'Hoặc: đọc điểm đầu tiên rồi gán nó cho cả cao nhất và thấp nhất.',
          ],
          starterCode: [
            'n = int(input())',
            'tong = 0',
            'cao_nhat = -1',
            'thap_nhat = 11',
            'so_dat = 0',
            '',
            'for i in range(n):',
            '    diem = float(input())',
            '    # Cập nhật bốn biến ở trên',
            '',
            '# In bốn dòng kết quả',
          ].join('\n'),
          solutionCode: [
            'n = int(input())',
            'tong = 0',
            'cao_nhat = -1',
            'thap_nhat = 11',
            'so_dat = 0',
            '',
            'for i in range(n):',
            '    diem = float(input())',
            '    tong += diem',
            '    if diem > cao_nhat:',
            '        cao_nhat = diem',
            '    if diem < thap_nhat:',
            '        thap_nhat = diem',
            '    if diem >= 5:',
            '        so_dat += 1',
            '',
            'print(f"Trung binh: {tong / n:.2f}")',
            'print(f"Cao nhat: {cao_nhat:.1f}")',
            'print(f"Thap nhat: {thap_nhat:.1f}")',
            'print(f"So ban dat: {so_dat}")',
          ].join('\n'),
          tier: 'CO_BAN',
          judgeMode: 'IO_MATCH',
          totalPoints: 100,
          tests: [
            sample(
              '4\n8\n5\n9.5\n3\n',
              'Trung binh: 6.38\nCao nhat: 9.5\nThap nhat: 3.0\nSo ban dat: 3\n',
              'Tổng 25.5 chia 4 được 6.375, làm tròn 2 chữ số là 6.38. Ba bạn từ 5 trở lên.',
            ),
            sample('1\n10\n', 'Trung binh: 10.00\nCao nhat: 10.0\nThap nhat: 10.0\nSo ban dat: 1\n'),
            hidden('3\n0\n0\n0\n', 'Trung binh: 0.00\nCao nhat: 0.0\nThap nhat: 0.0\nSo ban dat: 0\n', 20),
            hidden('2\n5\n4.99\n', 'Trung binh: 5.00\nCao nhat: 5.0\nThap nhat: 5.0\nSo ban dat: 1\n', 20),
            hidden(
              '5\n7\n8\n9\n10\n6\n',
              'Trung binh: 8.00\nCao nhat: 10.0\nThap nhat: 6.0\nSo ban dat: 5\n',
              30,
            ),
            hidden(
              '6\n1.5\n2.5\n3.5\n4.5\n5.5\n6.5\n',
              'Trung binh: 4.00\nCao nhat: 6.5\nThap nhat: 1.5\nSo ban dat: 2\n',
              30,
            ),
          ],
        }, { title: 'Bài kiểm tra giữa khoá', markdown: 'Bài tổng hợp của 15 buổi đầu. Cứ bình tĩnh làm từng bước: nhập → xử lý → xuất.' }),
        quizBlock({
          slug: 'q-b16-on-tap-giua-khoa',
          title: 'Kiểm tra lý thuyết giữa khoá',
          passingScore: 70,
          questions: [
            {
              type: 'MULTIPLE_CHOICE',
              prompt: '`range(1, 11)` sinh ra bao nhiêu số?',
              explanation: 'Từ 1 đến 10, tức 10 số. Giá trị 11 không được bao gồm.',
              choices: [
                { text: '10 số', isCorrect: true },
                { text: '11 số' },
                { text: '12 số' },
                { text: '9 số' },
              ],
            },
            {
              type: 'MULTIPLE_CHOICE',
              prompt: 'Lệnh nào thoát hẳn khỏi vòng lặp?',
              explanation: '`break` thoát vòng lặp. `continue` chỉ bỏ qua vòng hiện tại.',
              choices: [
                { text: 'break', isCorrect: true },
                { text: 'continue' },
                { text: 'stop' },
                { text: 'exit' },
              ],
            },
            {
              type: 'MULTIPLE_CHOICE',
              prompt: 'Vì sao `int(input())` lại cần thiết khi muốn tính toán?',
              explanation: '`input()` luôn trả về chuỗi, nên phải ép về số trước khi tính.',
              choices: [
                { text: 'Vì `input()` luôn trả về chuỗi', isCorrect: true },
                { text: 'Vì `input()` chạy chậm nếu không ép kiểu' },
                { text: 'Vì Python bắt buộc mọi biến phải khai báo kiểu' },
                { text: 'Không cần thiết, chỉ để cho đẹp' },
              ],
            },
            {
              type: 'TRUE_FALSE',
              prompt: 'Vòng lặp `while` thiếu dòng cập nhật biến điều kiện sẽ chạy mãi không dừng.',
              explanation: 'Đúng. Đây là nguyên nhân phổ biến nhất của kết quả "Quá thời gian".',
              choices: [{ text: 'Đúng', isCorrect: true }, { text: 'Sai' }],
            },
            {
              type: 'FILL_BLANK',
              prompt: 'Toán tử nào cho phần dư của phép chia?',
              explanation: 'Toán tử `%`, ví dụ `17 % 5` cho 2.',
              acceptedAnswers: ['%', 'dấu %', 'modulo', 'chia lấy dư', 'phần trăm'],
              matchMode: 'normalised',
            },
            {
              type: 'SHORT_ANSWER',
              prompt:
                'Bằng lời của em, hãy giải thích sự khác nhau giữa vòng lặp `for` và vòng lặp `while`. ' +
                'Cho một ví dụ mỗi loại.',
              explanation:
                '`for` dùng khi biết trước số lần lặp (ví dụ: in bảng cửu chương 10 dòng). ' +
                '`while` dùng khi số lần lặp phụ thuộc dữ liệu chạy thật (ví dụ: lặp tới khi người dùng nhập 0).',
              points: 20,
            },
          ],
        }),
        reflection(
          'Chặng đường 16 buổi',
          'Em đã đi được nửa khoá học và nắm trọn phần nền tảng. Hãy viết ra: điều gì em tự hào nhất ' +
            'khi tự làm được, và điều gì em muốn tìm hiểu sâu hơn ở nửa sau?',
        ),
      ],
    },
  ],
};
