/**
 * Python Cơ Bản — Module 5–9 (Buổi 17–30).
 *
 * Teacher notes enforced here:
 *   • Note 4  — trigonometry (sin/cos) is tiered NANG_CAO in session 17, so the
 *     Cơ bản track never renders it. It is an opportunity, not an obstacle.
 *   • Note 5  — List and Dictionary carry the practical load (6 graded exercises).
 *     Tuple and Set stay THEORY + QUIZ with zero coding blocks.
 *   • Note 6  — try/except stays practical; no custom exception classes.
 *   • Note 7  — Text and JSON only. The `csv` module appears nowhere.
 *   • Note 8  — every session from 20 onward is OPTIONAL or ADVANCED.
 */
import type { ModuleSpec } from '../types.ts';
import {
  challenge,
  example,
  hidden,
  playground,
  quizBlock,
  reflection,
  sample,
  theory,
} from '../builders.ts';

export const module5: ModuleSpec = {
  slug: 'thu-vien-chuan-huu-ich',
  title: 'Thư viện chuẩn hữu ích',
  description:
    'Python đi kèm sẵn rất nhiều công cụ. Ba buổi này giới thiệu `math`, `datetime` và `calendar` — ' +
    'những thứ dùng được ngay trong bài tập hằng ngày.',
  lessons: [
    {
      order: 17,
      slug: 'b17-module-math',
      title: 'Module `math`',
      summary:
        'Căn bậc hai, làm tròn, số pi và các hàm toán học có sẵn — không phải tự viết lại từ đầu.',
      objectives: [
        'Nhập và sử dụng module `math`',
        'Dùng `math.sqrt`, `math.floor`, `math.ceil`, `math.pi`',
        'Phân biệt `round()`, `math.floor()` và `math.ceil()`',
      ],
      difficulty: 2,
      status: 'REQUIRED',
      teacherNotes:
        'Lesson 6. GHI CHÚ QUAN TRỌNG: phân hoá bài tập lượng giác (sin/cos). Các phần lượng giác ' +
        'được gắn mức NÂNG CAO để chỉ hiện với học sinh đang học ở nhánh nâng cao — tránh gây nản ' +
        'cho các bạn khác. Phần math cơ bản vẫn là bắt buộc cho tất cả.',
      blocks: [
        theory('Dùng module có sẵn', [
          'Python đi kèm một bộ thư viện gọi là **thư viện chuẩn**. Module `math` là một trong số đó.',
          '',
          '```python',
          'import math',
          '',
          'print(math.sqrt(16))    # 4.0  — căn bậc hai',
          'print(math.pi)          # 3.141592653589793',
          '```',
          '',
          'Các hàm hay dùng nhất:',
          '',
          '| Hàm | Ý nghĩa | Ví dụ |',
          '|---|---|---|',
          '| `math.sqrt(x)` | Căn bậc hai | `math.sqrt(25)` → `5.0` |',
          '| `math.floor(x)` | Làm tròn **xuống** | `math.floor(3.9)` → `3` |',
          '| `math.ceil(x)` | Làm tròn **lên** | `math.ceil(3.1)` → `4` |',
          '| `math.pow(x, y)` | Luỹ thừa | `math.pow(2, 3)` → `8.0` |',
          '| `math.pi` | Hằng số π | `3.14159...` |',
          '',
          '`round()` là hàm có sẵn của Python (không cần `math`), làm tròn theo quy tắc thông thường.',
        ], [
          '`import math` để dùng các hàm toán học',
          '`floor` làm tròn xuống, `ceil` làm tròn lên, `round` làm tròn thông thường',
          '`math.sqrt()` luôn trả về số thực',
        ]),
        example('Ba kiểu làm tròn cạnh nhau', 'Cùng một số, ba kết quả khác nhau.', [
          'import math',
          '',
          'x = 3.7',
          'print(f"round({x})       = {round(x)}")',
          'print(f"math.floor({x}) = {math.floor(x)}")',
          'print(f"math.ceil({x})  = {math.ceil(x)}")',
          '',
          'y = 3.2',
          'print(f"round({y})       = {round(y)}")',
          'print(f"math.floor({y}) = {math.floor(y)}")',
          'print(f"math.ceil({y})  = {math.ceil(y)}")',
          '',
          '# Ứng dụng: chu vi và diện tích hình tròn',
          'r = 5',
          'print(f"Chu vi   = {2 * math.pi * r:.2f}")',
          'print(f"Dien tich = {math.pi * r ** 2:.2f}")',
        ], {
          output: [
            'round(3.7)       = 4',
            'math.floor(3.7) = 3',
            'math.ceil(3.7)  = 4',
            'round(3.2)       = 3',
            'math.floor(3.2) = 3',
            'math.ceil(3.2)  = 4',
            'Chu vi   = 31.42',
            'Dien tich = 78.54',
          ].join('\n'),
          notes: [
            '`ceil` luôn làm tròn lên, kể cả 3.2 cũng thành 4.',
            '`floor` luôn làm tròn xuống, kể cả 3.7 cũng thành 3.',
          ],
        }),
        playground('Sân chơi: khoảng cách giữa hai điểm', [
          'Công thức khoảng cách: √((x₂−x₁)² + (y₂−y₁)²).',
          '',
          'Hãy dùng `math.sqrt` để tính.',
        ], [
          'import math',
          '',
          'x1, y1 = 0, 0',
          'x2, y2 = 3, 4',
          '',
          'khoang_cach = math.sqrt((x2 - x1) ** 2 + (y2 - y1) ** 2)',
          'print(f"Khoang cach: {khoang_cach:.2f}")',
        ], 'Tính đúng khoảng cách giữa hai điểm bất kỳ.'),
        challenge({
          slug: 'p-b17-hinh-tron',
          title: 'Chu vi và diện tích hình tròn',
          statement: [
            'Đọc **một số thực** là bán kính `r`, in ra **hai dòng**:',
            '',
            '```',
            'Chu vi: <chu_vi>',
            'Dien tich: <dien_tich>',
            '```',
            '',
            'Cả hai hiển thị **2 chữ số thập phân**. Dùng `math.pi`.',
          ].join('\n'),
          hints: ['Chu vi = 2 × π × r.', 'Diện tích = π × r².', 'Nhớ `import math` ở đầu tệp.'],
          starterCode: ['import math', '', 'r = float(input())', '', '# Tính và in'].join('\n'),
          solutionCode: [
            'import math',
            'r = float(input())',
            'print(f"Chu vi: {2 * math.pi * r:.2f}")',
            'print(f"Dien tich: {math.pi * r ** 2:.2f}")',
          ].join('\n'),
          tier: 'CO_BAN',
          judgeMode: 'IO_MATCH',
          tests: [
            sample('5\n', 'Chu vi: 31.42\nDien tich: 78.54\n', '2 × π × 5 ≈ 31.42.'),
            sample('1\n', 'Chu vi: 6.28\nDien tich: 3.14\n'),
            hidden('0\n', 'Chu vi: 0.00\nDien tich: 0.00\n', 25),
            hidden('2.5\n', 'Chu vi: 15.71\nDien tich: 19.63\n', 25),
            hidden('10\n', 'Chu vi: 62.83\nDien tich: 314.16\n', 25),
            hidden('0.5\n', 'Chu vi: 3.14\nDien tich: 0.79\n', 25),
          ],
        }),
        theory('Lượng giác trong Python', [
          'Module `math` cũng có sẵn các hàm lượng giác. Điều cần nhớ nhất: ' +
            'Python làm việc với **radian**, không phải độ.',
          '',
          '```python',
          'import math',
          '',
          'goc_do = 30',
          'goc_radian = math.radians(goc_do)      # đổi độ sang radian',
          '',
          'print(math.sin(goc_radian))            # 0.4999999999999999',
          'print(math.cos(goc_radian))            # 0.8660254037844387',
          '```',
          '',
          '⚠️ Chú ý `sin(30°)` cho `0.4999999999999999` chứ không phải đúng `0.5`. ' +
            'Máy tính lưu số thực gần đúng, nên kết quả có sai số rất nhỏ. Khi hiển thị, ' +
            'hãy làm tròn bằng `{x:.4f}`.',
        ], [
          '`math.radians(do)` đổi độ sang radian trước khi tính',
          '`math.sin`, `math.cos`, `math.tan` nhận tham số là radian',
          'Số thực có sai số nhỏ — hãy làm tròn khi hiển thị',
        ], { tier: 'NANG_CAO', minutes: 15 }),
        example('Bảng giá trị sin và cos', 'Ghép lượng giác với vòng lặp đã học ở Module 4.', [
          'import math',
          '',
          'print("Goc |    sin |    cos")',
          'print("-" * 24)',
          '',
          'for do in range(0, 91, 15):',
          '    rad = math.radians(do)',
          '    print(f"{do:3d} | {math.sin(rad):6.3f} | {math.cos(rad):6.3f}")',
        ], {
          output: [
            'Goc |    sin |    cos',
            '------------------------',
            '  0 |  0.000 |  1.000',
            ' 15 |  0.259 |  0.966',
            ' 30 |  0.500 |  0.866',
            ' 45 |  0.707 |  0.707',
            ' 60 |  0.866 |  0.500',
            ' 75 |  0.966 |  0.259',
            ' 90 |  1.000 |  0.000',
          ].join('\n'),
          notes: [
            '`{do:3d}` căn phải số nguyên trong 3 ô; `{x:6.3f}` căn phải số thực trong 6 ô với 3 chữ số thập phân.',
            'Ở 45°, sin và cos bằng nhau — đúng như trong hình học.',
          ],
          tier: 'NANG_CAO',
        }),
        challenge({
          slug: 'p-b17-chieu-cao-cot-co',
          title: 'Tính chiều cao cột cờ',
          statement: [
            'Đứng cách chân cột cờ `d` mét và nhìn lên đỉnh cột với góc nâng `a` độ. ' +
              'Chiều cao cột cờ là `d × tan(a)`.',
            '',
            'Đọc **hai dòng**: `d` (số thực, mét) và `a` (số thực, độ).',
            '',
            'In ra **một dòng**: `Chieu cao: <h>` với `<h>` là **2 chữ số thập phân**.',
          ].join('\n'),
          hints: [
            'Đổi độ sang radian trước bằng `math.radians(a)`.',
            'Dùng `math.tan(rad)`.',
          ],
          starterCode: [
            'import math',
            '',
            'd = float(input())',
            'a = float(input())',
            '',
            '# Đổi sang radian rồi tính',
          ].join('\n'),
          solutionCode: [
            'import math',
            'd = float(input())',
            'a = float(input())',
            'h = d * math.tan(math.radians(a))',
            'print(f"Chieu cao: {h:.2f}")',
          ].join('\n'),
          tier: 'NANG_CAO',
          judgeMode: 'IO_MATCH',
          tests: [
            sample('10\n45\n', 'Chieu cao: 10.00\n', 'Góc 45° cho tan bằng 1, nên chiều cao bằng khoảng cách.'),
            sample('20\n30\n', 'Chieu cao: 11.55\n'),
            hidden('15\n60\n', 'Chieu cao: 25.98\n', 30),
            hidden('5\n0\n', 'Chieu cao: 0.00\n', 30),
            hidden('12.5\n37.5\n', 'Chieu cao: 9.59\n', 40),
          ],
        }, {
          isOptional: true,
          markdown:
            'Thử thách Nâng cao dành cho các bạn muốn khám phá thêm về lượng giác. ' +
            'Không làm bài này cũng không ảnh hưởng đến tiến độ của em.',
        }),
      ],
    },

    {
      order: 18,
      slug: 'b18-datetime-ngay-gio',
      title: '`datetime` — làm việc với ngày giờ',
      summary: 'Lấy ngày hiện tại, định dạng ngày tháng, và tính khoảng cách giữa hai mốc thời gian.',
      objectives: [
        'Lấy được ngày giờ hiện tại bằng `datetime`',
        'Định dạng ngày tháng theo ý muốn với `strftime`',
        'Tính được số ngày giữa hai mốc thời gian',
      ],
      difficulty: 3,
      status: 'REQUIRED',
      teacherNotes: 'Lesson 6 (tiếp). Bài tính số ngày còn lại đến sinh nhật rất được học sinh hứng thú.',
      blocks: [
        theory('Ngày giờ trong Python', [
          '```python',
          'from datetime import date, datetime',
          '',
          'hom_nay = date.today()',
          'print(hom_nay)                  # 2026-08-16',
          'print(hom_nay.day)              # 16',
          'print(hom_nay.month)            # 8',
          'print(hom_nay.year)             # 2026',
          '```',
          '',
          'Cách viết `from datetime import date` nghĩa là *"từ module datetime, lấy ra công cụ date"*. ' +
            'Sau đó dùng thẳng `date` mà không cần viết `datetime.date`.',
          '',
          '**Tự tạo một ngày:** `date(2026, 8, 16)` — theo thứ tự năm, tháng, ngày.',
          '',
          '**Trừ hai ngày** cho ra một khoảng thời gian, và `.days` lấy ra số ngày:',
          '',
          '```python',
          'sinh_nhat = date(2026, 12, 25)',
          'con_lai = sinh_nhat - hom_nay',
          'print(con_lai.days)             # 131',
          '```',
        ], [
          '`date.today()` cho ngày hôm nay',
          '`date(nam, thang, ngay)` để tự tạo một ngày',
          'Trừ hai ngày rồi lấy `.days` để biết cách nhau bao nhiêu ngày',
        ]),
        theory('Định dạng ngày với `strftime`', [
          'Ngày mặc định hiện theo kiểu `2026-08-16`. Muốn kiểu Việt Nam `16/08/2026`, dùng `strftime`:',
          '',
          '```python',
          'print(hom_nay.strftime("%d/%m/%Y"))    # 16/08/2026',
          '```',
          '',
          '| Mã | Ý nghĩa | Ví dụ |',
          '|---|---|---|',
          '| `%d` | Ngày (2 chữ số) | `16` |',
          '| `%m` | Tháng (2 chữ số) | `08` |',
          '| `%Y` | Năm (4 chữ số) | `2026` |',
          '| `%H:%M` | Giờ:phút | `14:30` |',
          '',
          'Ghi nhớ: `%Y` viết hoa cho năm đủ 4 chữ số.',
        ], ['`strftime("%d/%m/%Y")` để hiện ngày kiểu Việt Nam', '`%Y` hoa là năm 4 chữ số']),
        example('Ứng dụng đếm ngược', 'Kết hợp datetime với f-string và rẽ nhánh.', [
          'from datetime import date',
          '',
          'hom_nay = date.today()',
          'tet = date(2027, 2, 6)',
          '',
          'con_lai = (tet - hom_nay).days',
          '',
          'print(f"Hom nay la {hom_nay.strftime(\'%d/%m/%Y\')}")',
          'print(f"Tet Nguyen Dan: {tet.strftime(\'%d/%m/%Y\')}")',
          '',
          'if con_lai > 0:',
          '    print(f"Con {con_lai} ngay nua den Tet!")',
          'elif con_lai == 0:',
          '    print("Hom nay la Tet!")',
          'else:',
          '    print(f"Tet da qua {-con_lai} ngay")',
        ], {
          notes: [
            'Chú ý dấu nháy đơn bên trong f-string dùng nháy kép — không được trùng loại nháy.',
            'Kết quả thay đổi theo ngày chạy thật, nên bài này không có bài chấm tự động.',
          ],
        }),
        playground('Sân chơi: em đã sống bao nhiêu ngày?', [
          'Nhập ngày sinh của em rồi tính xem em đã sống được bao nhiêu ngày.',
          '',
          'Thử tính thêm: bao nhiêu tuần? Bao nhiêu giờ?',
        ], [
          'from datetime import date',
          '',
          'ngay_sinh = date(2012, 5, 20)   # đổi thành ngày sinh của em',
          'hom_nay = date.today()',
          '',
          'so_ngay = (hom_nay - ngay_sinh).days',
          'print(f"Em da song {so_ngay} ngay")',
          'print(f"Tuong duong {so_ngay // 7} tuan")',
        ], 'Tính đúng số ngày đã sống và đổi được sang tuần.'),
        challenge({
          slug: 'p-b18-so-ngay-giua-hai-moc',
          title: 'Số ngày giữa hai mốc thời gian',
          statement: [
            'Đọc **sáu số nguyên** trên sáu dòng: năm, tháng, ngày của mốc thứ nhất, ' +
              'rồi năm, tháng, ngày của mốc thứ hai.',
            '',
            'In ra **một dòng** là số ngày giữa hai mốc, luôn là **số không âm**.',
            '',
            'Ví dụ: 2026-01-01 và 2026-01-31 cách nhau 30 ngày.',
          ].join('\n'),
          hints: [
            'Tạo hai đối tượng `date(nam, thang, ngay)`.',
            'Trừ hai ngày rồi lấy `.days`.',
            'Dùng `abs()` để kết quả luôn không âm.',
          ],
          starterCode: [
            'from datetime import date',
            '',
            'n1 = int(input())',
            't1 = int(input())',
            'd1 = int(input())',
            'n2 = int(input())',
            't2 = int(input())',
            'd2 = int(input())',
            '',
            '# Tạo hai ngày rồi tính khoảng cách',
          ].join('\n'),
          solutionCode: [
            'from datetime import date',
            '',
            'n1 = int(input())',
            't1 = int(input())',
            'd1 = int(input())',
            'n2 = int(input())',
            't2 = int(input())',
            'd2 = int(input())',
            '',
            'ngay_1 = date(n1, t1, d1)',
            'ngay_2 = date(n2, t2, d2)',
            'print(abs((ngay_2 - ngay_1).days))',
          ].join('\n'),
          tier: 'THU_THACH',
          judgeMode: 'IO_MATCH',
          tests: [
            sample(
              '2026\n1\n1\n2026\n1\n31\n',
              '30\n',
              'Từ mùng 1 đến 31 tháng 1 là 30 ngày.',
            ),
            sample('2026\n8\n16\n2026\n8\n16\n', '0\n', 'Cùng một ngày thì khoảng cách bằng 0.'),
            hidden('2024\n1\n1\n2025\n1\n1\n', '366\n', 25),
            hidden('2025\n1\n1\n2026\n1\n1\n', '365\n', 25),
            hidden('2026\n12\n31\n2026\n1\n1\n', '364\n', 25),
            hidden('2000\n1\n1\n2026\n8\n16\n', '9724\n', 25),
          ],
        }),
      ],
    },

    {
      order: 19,
      slug: 'b19-calendar-va-luyen-tap',
      title: '`calendar` & Luyện tập tổng hợp',
      summary:
        'In lịch tháng, kiểm tra năm nhuận bằng thư viện, và ôn lại toàn bộ Module 5 trước khi ' +
        'bước sang phần tuỳ chọn của khoá học.',
      objectives: [
        'In được lịch tháng và lịch năm bằng module `calendar`',
        'Dùng `calendar.isleap()` thay cho việc tự viết điều kiện năm nhuận',
        'Kết hợp `math`, `datetime` và `calendar` trong một chương trình',
      ],
      difficulty: 2,
      status: 'REQUIRED',
      teacherNotes:
        'Lesson 6 (kết). Đây là buổi BẮT BUỘC cuối cùng. Từ buổi 20 trở đi, nội dung là tuỳ chọn ' +
        'theo tốc độ của từng học sinh.',
      blocks: [
        theory('Module `calendar`', [
          '```python',
          'import calendar',
          '',
          'print(calendar.month(2026, 8))       # in lịch tháng 8/2026',
          'print(calendar.isleap(2024))         # True',
          'print(calendar.monthrange(2026, 2))  # (6, 28) — thứ đầu tháng và số ngày',
          '```',
          '',
          '| Hàm | Trả về |',
          '|---|---|',
          '| `calendar.month(nam, thang)` | Chuỗi lịch tháng đã định dạng sẵn |',
          '| `calendar.isleap(nam)` | `True`/`False` — năm nhuận hay không |',
          '| `calendar.monthrange(nam, thang)` | Cặp (thứ của ngày 1, số ngày trong tháng) |',
          '',
          'Ở buổi 10 em đã tự viết điều kiện năm nhuận. `calendar.isleap()` làm đúng việc đó chỉ trong một dòng. ' +
            'Đây là bài học lớn của lập trình: **trước khi tự viết, hãy xem thư viện đã có sẵn chưa.**',
        ], [
          '`calendar.month()` in lịch tháng',
          '`calendar.isleap()` thay thế cho điều kiện năm nhuận tự viết',
          'Luôn kiểm tra thư viện chuẩn trước khi tự viết lại',
        ]),
        example('Lịch tháng và số ngày', 'Kết hợp calendar với vòng lặp.', [
          'import calendar',
          '',
          'nam = 2026',
          '',
          '# Số ngày của từng tháng trong năm',
          'for thang in range(1, 13):',
          '    _, so_ngay = calendar.monthrange(nam, thang)',
          '    ten_thang = calendar.month_name[thang]',
          '    print(f"{ten_thang:<10}: {so_ngay} ngay")',
          '',
          'print()',
          'print(f"{nam} co phai nam nhuan? {calendar.isleap(nam)}")',
        ], {
          output: [
            'January   : 31 ngay',
            'February  : 28 ngay',
            'March     : 31 ngay',
            '...',
            'December  : 31 ngay',
            '',
            '2026 co phai nam nhuan? False',
          ].join('\n'),
          notes: [
            '`monthrange` trả về hai giá trị cùng lúc; dấu `_` nghĩa là "giá trị này tôi không dùng".',
            '`{ten_thang:<10}` căn trái trong 10 ô, giúp cột thẳng hàng.',
          ],
        }),
        playground('Sân chơi: lịch sinh nhật', [
          'In lịch của tháng sinh nhật em, và cho biết sinh nhật năm nay rơi vào thứ mấy.',
          '',
          'Gợi ý: `date(nam, thang, ngay).strftime("%A")` cho tên thứ trong tuần.',
        ], [
          'import calendar',
          'from datetime import date',
          '',
          'thang_sinh = 5',
          'ngay_sinh = 20',
          '',
          'print(calendar.month(2026, thang_sinh))',
          'print(date(2026, thang_sinh, ngay_sinh).strftime("%A"))',
        ], 'In được lịch tháng sinh nhật và xác định đúng thứ trong tuần.'),
        challenge({
          slug: 'p-b19-so-ngay-trong-thang',
          title: 'Số ngày trong tháng',
          statement: [
            'Đọc **hai số nguyên** trên hai dòng: năm và tháng.',
            '',
            'In ra **một dòng** là số ngày của tháng đó.',
            '',
            'Nếu tháng không nằm trong khoảng 1–12, in ra `Thang khong hop le`.',
          ].join('\n'),
          hints: [
            'Kiểm tra tháng hợp lệ trước.',
            '`calendar.monthrange(nam, thang)` trả về một cặp; số ngày là phần tử thứ hai.',
            'Có thể viết `_, so_ngay = calendar.monthrange(nam, thang)`.',
          ],
          starterCode: [
            'import calendar',
            '',
            'nam = int(input())',
            'thang = int(input())',
            '',
            '# Kiểm tra hợp lệ rồi lấy số ngày',
          ].join('\n'),
          solutionCode: [
            'import calendar',
            '',
            'nam = int(input())',
            'thang = int(input())',
            '',
            'if thang < 1 or thang > 12:',
            '    print("Thang khong hop le")',
            'else:',
            '    _, so_ngay = calendar.monthrange(nam, thang)',
            '    print(so_ngay)',
          ].join('\n'),
          tier: 'CO_BAN',
          judgeMode: 'IO_MATCH',
          tests: [
            sample('2024\n2\n', '29\n', '2024 là năm nhuận nên tháng 2 có 29 ngày.'),
            sample('2026\n2\n', '28\n', '2026 không nhuận nên tháng 2 chỉ có 28 ngày.'),
            sample('2026\n13\n', 'Thang khong hop le\n'),
            hidden('2026\n1\n', '31\n', 20),
            hidden('2026\n4\n', '30\n', 20),
            hidden('2000\n2\n', '29\n', 30),
            hidden('2026\n0\n', 'Thang khong hop le\n', 30),
          ],
        }),
        reflection(
          'Chốt phần nền tảng',
          'Em vừa hoàn thành toàn bộ phần bắt buộc của khoá Python Cơ Bản. Từ buổi sau, nội dung là ' +
            'tuỳ chọn — em có thể đi tiếp cùng lớp, hoặc quay lại luyện thêm những phần muốn vững hơn. ' +
            'Em muốn chọn hướng nào?',
        ),
      ],
    },
  ],
};

export const module6: ModuleSpec = {
  slug: 'cau-truc-du-lieu-python',
  title: 'Cấu trúc dữ liệu Python',
  description:
    'List và Dictionary — hai công cụ giúp chương trình xử lý được nhiều dữ liệu cùng lúc. ' +
    'Phần này là tuỳ chọn: em có thể học ngay, hoặc quay lại khi đã thật vững phần trước.',
  lessons: [
    {
      order: 20,
      slug: 'b20-list-danh-sach',
      title: 'List — Danh sách',
      summary:
        'Một biến chứa được nhiều giá trị. Đây là công cụ được dùng nhiều nhất trong mọi chương trình Python.',
      objectives: [
        'Tạo danh sách và truy cập phần tử bằng chỉ số',
        'Thêm, sửa, xoá phần tử của danh sách',
        'Duyệt danh sách bằng vòng lặp `for`',
        'Dùng `len()`, `sum()`, `max()`, `min()` trên danh sách',
      ],
      difficulty: 3,
      status: 'OPTIONAL',
      teacherNotes:
        'Lesson 7. GHI CHÚ: List là trọng tâm thực hành. Cho làm nhiều bài tập, không dừng ở lý thuyết.',
      blocks: [
        theory('Danh sách — nhiều giá trị trong một tên', [
          'Thay vì `diem1`, `diem2`, `diem3`..., ta dùng **một** danh sách:',
          '',
          '```python',
          'diem = [8, 9, 7, 10, 6]',
          '```',
          '',
          '**Chỉ số bắt đầu từ 0.** Đây là điều dễ nhầm nhất:',
          '',
          '```python',
          'print(diem[0])     # 8  — phần tử ĐẦU TIÊN',
          'print(diem[4])     # 6  — phần tử thứ năm',
          'print(diem[-1])    # 6  — chỉ số âm đếm từ cuối',
          'print(len(diem))   # 5  — số phần tử',
          '```',
          '',
          'Danh sách có 5 phần tử thì chỉ số hợp lệ là 0, 1, 2, 3, 4. Truy cập `diem[5]` sẽ báo `IndexError`.',
          '',
          '**Sửa phần tử:** `diem[0] = 9` — danh sách thay đổi được, khác với chuỗi.',
        ], [
          'Chỉ số bắt đầu từ 0',
          '`diem[-1]` là phần tử cuối cùng',
          '`len(ds)` cho số phần tử',
          'Danh sách sửa được: `ds[0] = gia_tri_moi`',
        ]),
        theory('Các thao tác thường dùng', [
          '| Thao tác | Ý nghĩa |',
          '|---|---|',
          '| `ds.append(x)` | Thêm `x` vào cuối |',
          '| `ds.insert(i, x)` | Chèn `x` vào vị trí `i` |',
          '| `ds.remove(x)` | Xoá **lần xuất hiện đầu tiên** của `x` |',
          '| `ds.pop()` | Lấy ra và xoá phần tử cuối |',
          '| `ds.sort()` | Sắp xếp tăng dần, sửa trực tiếp danh sách |',
          '| `ds.reverse()` | Đảo ngược thứ tự |',
          '| `x in ds` | `True` nếu `x` có trong danh sách |',
          '',
          'Bốn hàm dùng được ngay trên danh sách số: `len()`, `sum()`, `max()`, `min()`.',
          '',
          '**Duyệt danh sách** có hai cách:',
          '',
          '```python',
          '# Cách 1: duyệt trực tiếp giá trị — gọn, dùng khi không cần chỉ số',
          'for d in diem:',
          '    print(d)',
          '',
          '# Cách 2: duyệt theo chỉ số — dùng khi cần biết vị trí',
          'for i in range(len(diem)):',
          '    print(f"Hoc sinh {i + 1}: {diem[i]}")',
          '```',
        ], [
          '`append` thêm cuối, `pop` lấy ra cuối',
          '`sum`, `max`, `min`, `len` dùng thẳng trên danh sách số',
          'Duyệt trực tiếp khi không cần chỉ số, duyệt theo `range(len())` khi cần',
        ]),
        example('Sổ điểm bằng danh sách', 'Một chương trình thực tế dùng gần hết các thao tác trên.', [
          'diem = [8, 9, 7, 10, 6]',
          '',
          'print(f"Danh sach   : {diem}")',
          'print(f"So hoc sinh : {len(diem)}")',
          'print(f"Tong diem   : {sum(diem)}")',
          'print(f"Trung binh  : {sum(diem) / len(diem):.2f}")',
          'print(f"Cao nhat    : {max(diem)}")',
          'print(f"Thap nhat   : {min(diem)}")',
          '',
          '# Thêm một điểm mới',
          'diem.append(9.5)',
          'print(f"Sau khi them: {diem}")',
          '',
          '# Sắp xếp',
          'diem.sort()',
          'print(f"Sau khi sap : {diem}")',
          '',
          '# Đếm số bạn đạt',
          'so_dat = 0',
          'for d in diem:',
          '    if d >= 5:',
          '        so_dat += 1',
          'print(f"So ban dat  : {so_dat}/{len(diem)}")',
        ], {
          output: [
            'Danh sach   : [8, 9, 7, 10, 6]',
            'So hoc sinh : 5',
            'Tong diem   : 40',
            'Trung binh  : 8.00',
            'Cao nhat    : 10',
            'Thap nhat   : 6',
            'Sau khi them: [8, 9, 7, 10, 6, 9.5]',
            'Sau khi sap : [6, 7, 8, 9, 9.5, 10]',
            'So ban dat  : 6/6',
          ].join('\n'),
          notes: [
            '`sort()` sửa trực tiếp danh sách gốc, không tạo danh sách mới.',
            'Nhờ có `sum()` và `len()`, tính trung bình chỉ mất một dòng thay vì cả vòng lặp.',
          ],
        }),
        playground('Sân chơi: danh sách môn học của em', [
          'Tạo một danh sách các môn em đang học, rồi thử:',
          '',
          '- Thêm một môn mới bằng `append`',
          '- Xoá một môn bằng `remove`',
          '- Sắp xếp theo bảng chữ cái bằng `sort`',
          '- Kiểm tra một môn có trong danh sách không bằng `in`',
        ], [
          'mon_hoc = ["Toan", "Van", "Anh", "Ly"]',
          '',
          'mon_hoc.append("Tin hoc")',
          'print(mon_hoc)',
          '',
          'mon_hoc.sort()',
          'print(mon_hoc)',
          '',
          'print("Tin hoc" in mon_hoc)',
        ], 'Thao tác thành thạo append, remove, sort và toán tử `in`.'),
        challenge({
          slug: 'p-b20-thong-ke-danh-sach',
          title: 'Thống kê danh sách số',
          statement: [
            'Dòng đầu là số nguyên `N`. Dòng thứ hai chứa `N` số nguyên cách nhau bằng dấu cách.',
            '',
            'In ra **bốn dòng**:',
            '',
            '```',
            'Tong: <tong>',
            'Lon nhat: <max>',
            'Nho nhat: <min>',
            'Trung binh: <tb>',
            '```',
            '',
            '`<tb>` hiển thị **2 chữ số thập phân**.',
            '',
            '💡 Đọc cả dòng số bằng: `so = list(map(int, input().split()))`',
          ].join('\n'),
          hints: [
            '`input().split()` tách dòng thành danh sách các chuỗi.',
            '`map(int, ...)` đổi từng chuỗi thành số nguyên.',
            'Sau đó dùng thẳng `sum()`, `max()`, `min()`, `len()`.',
          ],
          starterCode: [
            'n = int(input())',
            'so = list(map(int, input().split()))',
            '',
            '# Dùng sum, max, min, len',
          ].join('\n'),
          solutionCode: [
            'n = int(input())',
            'so = list(map(int, input().split()))',
            'print(f"Tong: {sum(so)}")',
            'print(f"Lon nhat: {max(so)}")',
            'print(f"Nho nhat: {min(so)}")',
            'print(f"Trung binh: {sum(so) / len(so):.2f}")',
          ].join('\n'),
          tier: 'CO_BAN',
          judgeMode: 'IO_MATCH',
          tests: [
            sample(
              '5\n8 9 7 10 6\n',
              'Tong: 40\nLon nhat: 10\nNho nhat: 6\nTrung binh: 8.00\n',
              'Tổng 40 chia 5 phần tử được 8.00.',
            ),
            sample('1\n42\n', 'Tong: 42\nLon nhat: 42\nNho nhat: 42\nTrung binh: 42.00\n'),
            hidden('3\n-5 0 5\n', 'Tong: 0\nLon nhat: 5\nNho nhat: -5\nTrung binh: 0.00\n', 25),
            hidden('4\n1 1 1 1\n', 'Tong: 4\nLon nhat: 1\nNho nhat: 1\nTrung binh: 1.00\n', 25),
            hidden('6\n10 20 30 40 50 60\n', 'Tong: 210\nLon nhat: 60\nNho nhat: 10\nTrung binh: 35.00\n', 25),
            hidden('3\n1 2 2\n', 'Tong: 5\nLon nhat: 2\nNho nhat: 1\nTrung binh: 1.67\n', 25),
          ],
        }),
        challenge({
          slug: 'p-b20-loc-so-chan',
          title: 'Lọc các số chẵn',
          statement: [
            'Dòng đầu là `N`. Dòng thứ hai chứa `N` số nguyên cách nhau bằng dấu cách.',
            '',
            'In ra **một dòng** chứa các số **chẵn** theo đúng thứ tự ban đầu, cách nhau bằng một dấu cách.',
            '',
            'Nếu không có số chẵn nào, in ra `Khong co so chan`.',
          ].join('\n'),
          hints: [
            'Tạo một danh sách rỗng `ket_qua = []` rồi `append` các số chẵn vào.',
            'Kiểm tra chẵn bằng `so % 2 == 0`.',
            'Để in danh sách số cách nhau bằng dấu cách: `" ".join(map(str, ket_qua))`.',
          ],
          starterCode: [
            'n = int(input())',
            'so = list(map(int, input().split()))',
            'chan = []',
            '',
            '# Duyệt và lọc',
          ].join('\n'),
          solutionCode: [
            'n = int(input())',
            'so = list(map(int, input().split()))',
            'chan = []',
            'for x in so:',
            '    if x % 2 == 0:',
            '        chan.append(x)',
            '',
            'if len(chan) == 0:',
            '    print("Khong co so chan")',
            'else:',
            '    print(" ".join(map(str, chan)))',
          ].join('\n'),
          tier: 'THU_THACH',
          judgeMode: 'IO_MATCH',
          tests: [
            sample('6\n1 2 3 4 5 6\n', '2 4 6\n', 'Giữ nguyên thứ tự xuất hiện ban đầu.'),
            sample('3\n1 3 5\n', 'Khong co so chan\n'),
            hidden('4\n2 4 6 8\n', '2 4 6 8\n', 25),
            hidden('1\n0\n', '0\n', 25),
            hidden('5\n-4 -3 -2 -1 0\n', '-4 -2 0\n', 25),
            hidden('2\n7 7\n', 'Khong co so chan\n', 25),
          ],
        }),
      ],
    },

    {
      order: 21,
      slug: 'b21-list-nang-cao',
      title: 'Thực hành nâng cao với List',
      summary:
        'Cắt lát danh sách, sao chép đúng cách, danh sách lồng nhau, và list comprehension — ' +
        'cách viết gọn đặc trưng của Python.',
      objectives: [
        'Cắt lát danh sách bằng cú pháp `ds[a:b]`',
        'Phân biệt gán tham chiếu và sao chép danh sách',
        'Làm việc với danh sách lồng nhau (ma trận)',
        'Viết được list comprehension đơn giản',
      ],
      difficulty: 4,
      status: 'OPTIONAL',
      teacherNotes:
        'Buổi thực hành nâng cao cho List (⟨derived⟩). Phần sao chép danh sách là bẫy kinh điển, ' +
        'nên cho học sinh gặp lỗi trước rồi mới giải thích.',
      isDerived: true,
      blocks: [
        theory('Cắt lát (slicing)', [
          '`ds[a:b]` lấy ra một **danh sách mới** gồm các phần tử từ chỉ số `a` đến **trước** `b`.',
          '',
          '```python',
          'so = [10, 20, 30, 40, 50]',
          '',
          'print(so[1:4])    # [20, 30, 40]  — từ 1 đến trước 4',
          'print(so[:3])     # [10, 20, 30]  — từ đầu',
          'print(so[2:])     # [30, 40, 50]  — đến cuối',
          'print(so[-2:])    # [40, 50]      — hai phần tử cuối',
          'print(so[::2])    # [10, 30, 50]  — cách một lấy một',
          'print(so[::-1])   # [50, 40, 30, 20, 10] — đảo ngược',
          '```',
          '',
          'Quy tắc "đến trước b" giống hệt `range(a, b)` mà em đã quen ở buổi 12.',
        ], [
          '`ds[a:b]` lấy từ a đến TRƯỚC b',
          '`ds[::-1]` là cách đảo ngược danh sách nhanh nhất',
          'Cắt lát luôn tạo ra danh sách MỚI',
        ]),
        theory('Bẫy sao chép danh sách', [
          'Đây là lỗi mà gần như ai học Python cũng mắc một lần:',
          '',
          '```python',
          'a = [1, 2, 3]',
          'b = a              # KHÔNG phải sao chép!',
          'b.append(4)',
          'print(a)           # [1, 2, 3, 4]  — a cũng bị đổi!',
          '```',
          '',
          'Dòng `b = a` chỉ tạo thêm **một cái tên nữa** trỏ vào **cùng một danh sách**. ' +
            'Giống như dán thêm nhãn thứ hai lên cùng một chiếc hộp.',
          '',
          'Muốn sao chép thật sự, dùng một trong ba cách:',
          '',
          '```python',
          'b = a.copy()',
          'b = a[:]           # cắt lát toàn bộ',
          'b = list(a)',
          '```',
          '',
          'Với ba cách này, sửa `b` không ảnh hưởng tới `a`.',
        ], [
          '`b = a` không sao chép — hai tên cùng trỏ một danh sách',
          'Dùng `a.copy()`, `a[:]` hoặc `list(a)` để sao chép thật',
        ]),
        theory('Danh sách lồng nhau và list comprehension', [
          '**Danh sách lồng nhau** dùng để biểu diễn bảng hoặc ma trận:',
          '',
          '```python',
          'bang = [[1, 2, 3],',
          '        [4, 5, 6],',
          '        [7, 8, 9]]',
          '',
          'print(bang[0])       # [1, 2, 3]  — hàng đầu tiên',
          'print(bang[1][2])    # 6          — hàng 1, cột 2',
          '```',
          '',
          '**List comprehension** là cách viết gọn để tạo danh sách mới từ danh sách cũ:',
          '',
          '```python',
          '# Cách dài',
          'binh_phuong = []',
          'for x in range(1, 6):',
          '    binh_phuong.append(x ** 2)',
          '',
          '# Cách gọn — cùng kết quả',
          'binh_phuong = [x ** 2 for x in range(1, 6)]',
          '# [1, 4, 9, 16, 25]',
          '',
          '# Có kèm điều kiện lọc',
          'chan = [x for x in range(1, 11) if x % 2 == 0]',
          '# [2, 4, 6, 8, 10]',
          '```',
        ], [
          '`bang[hang][cot]` để truy cập ô trong ma trận',
          '`[bieu_thuc for x in day]` tạo danh sách mới',
          'Thêm `if dieu_kien` ở cuối để lọc',
        ]),
        example('Ba kỹ thuật trong một bài', 'Xử lý bảng điểm nhiều môn của nhiều học sinh.', [
          '# Mỗi hàng là điểm 3 môn của một học sinh',
          'bang_diem = [',
          '    [8, 9, 7],',
          '    [6, 7, 8],',
          '    [10, 9, 9],',
          ']',
          'ten = ["An", "Binh", "Chi"]',
          '',
          'for i in range(len(bang_diem)):',
          '    diem = bang_diem[i]',
          '    tb = sum(diem) / len(diem)',
          '    print(f"{ten[i]:<6}: {diem}  -> TB = {tb:.2f}")',
          '',
          'print()',
          '',
          '# List comprehension: lấy điểm môn đầu tiên của mọi học sinh',
          'mon_1 = [hang[0] for hang in bang_diem]',
          'print(f"Diem mon 1: {mon_1}")',
          'print(f"Cao nhat mon 1: {max(mon_1)}")',
          '',
          '# Lọc học sinh có trung bình từ 8 trở lên',
          'gioi = [ten[i] for i in range(len(bang_diem)) if sum(bang_diem[i]) / 3 >= 8]',
          'print(f"Dat tu 8.0 tro len: {gioi}")',
        ], {
          output: [
            'An    : [8, 9, 7]  -> TB = 8.00',
            'Binh  : [6, 7, 8]  -> TB = 7.00',
            'Chi   : [10, 9, 9]  -> TB = 9.33',
            '',
            'Diem mon 1: [8, 6, 10]',
            'Cao nhat mon 1: 10',
            "Dat tu 8.0 tro len: ['An', 'Chi']",
          ].join('\n'),
          notes: [
            '`hang[0]` lấy phần tử đầu của mỗi hàng — đó chính là điểm môn 1.',
            'List comprehension cuối kết hợp cả tạo mới lẫn lọc trong một dòng.',
          ],
        }),
        playground('Sân chơi: thử bẫy sao chép', [
          'Chạy đoạn code dưới đây và quan sát. Sau đó **sửa dòng thứ hai** thành `b = a.copy()` ' +
            'và chạy lại để thấy khác biệt.',
          '',
          'Đây là loại lỗi khó phát hiện nhất khi chương trình lớn dần.',
        ], [
          'a = [1, 2, 3]',
          'b = a',
          'b.append(999)',
          '',
          'print(f"a = {a}")',
          'print(f"b = {b}")',
        ], 'Giải thích được vì sao `a` bị thay đổi và sửa được bằng `.copy()`.'),
        challenge({
          slug: 'p-b21-dao-nguoc-va-cat-lat',
          title: 'Cắt lát và đảo ngược',
          statement: [
            'Dòng đầu là `N`. Dòng hai chứa `N` số nguyên. Dòng ba chứa hai số `a` và `b`.',
            '',
            'In ra **hai dòng**:',
            '',
            '1. Đoạn con từ chỉ số `a` đến **trước** `b`, cách nhau bằng dấu cách',
            '2. Cả danh sách ban đầu **đảo ngược**, cách nhau bằng dấu cách',
            '',
            'Đề bảo đảm `0 <= a < b <= N`.',
          ].join('\n'),
          hints: [
            'Cắt lát: `so[a:b]`.',
            'Đảo ngược: `so[::-1]`.',
            'In danh sách số: `" ".join(map(str, ds))`.',
          ],
          starterCode: [
            'n = int(input())',
            'so = list(map(int, input().split()))',
            'a, b = map(int, input().split())',
            '',
            '# Cắt lát và đảo ngược',
          ].join('\n'),
          solutionCode: [
            'n = int(input())',
            'so = list(map(int, input().split()))',
            'a, b = map(int, input().split())',
            'print(" ".join(map(str, so[a:b])))',
            'print(" ".join(map(str, so[::-1])))',
          ].join('\n'),
          tier: 'THU_THACH',
          judgeMode: 'IO_MATCH',
          tests: [
            sample(
              '5\n10 20 30 40 50\n1 4\n',
              '20 30 40\n50 40 30 20 10\n',
              'so[1:4] lấy chỉ số 1, 2, 3 — không lấy chỉ số 4.',
            ),
            sample('3\n1 2 3\n0 3\n', '1 2 3\n3 2 1\n'),
            hidden('4\n7 8 9 10\n0 1\n', '7\n10 9 8 7\n', 25),
            hidden('6\n1 1 2 3 5 8\n2 5\n', '2 3 5\n8 5 3 2 1 1\n', 25),
            hidden('2\n-1 -2\n0 2\n', '-1 -2\n-2 -1\n', 25),
            hidden('5\n5 4 3 2 1\n3 5\n', '2 1\n1 2 3 4 5\n', 25),
          ],
        }),
        challenge({
          slug: 'p-b21-ma-tran-tong-hang',
          title: 'Tổng mỗi hàng của ma trận',
          statement: [
            'Dòng đầu chứa hai số `H` và `C` — số hàng và số cột.',
            '',
            '`H` dòng tiếp theo, mỗi dòng chứa `C` số nguyên.',
            '',
            'In ra `H` dòng, dòng thứ `i` là **tổng của hàng thứ `i`**.',
          ].join('\n'),
          hints: [
            'Đọc từng hàng vào một danh sách rồi `append` vào danh sách lớn.',
            'Hoặc tính tổng ngay khi vừa đọc xong mỗi hàng.',
            '`sum(hang)` cho tổng một hàng.',
          ],
          starterCode: [
            'h, c = map(int, input().split())',
            'ma_tran = []',
            '',
            'for i in range(h):',
            '    hang = list(map(int, input().split()))',
            '    ma_tran.append(hang)',
            '',
            '# In tổng từng hàng',
          ].join('\n'),
          solutionCode: [
            'h, c = map(int, input().split())',
            'ma_tran = []',
            'for i in range(h):',
            '    ma_tran.append(list(map(int, input().split())))',
            '',
            'for hang in ma_tran:',
            '    print(sum(hang))',
          ].join('\n'),
          tier: 'NANG_CAO',
          judgeMode: 'IO_MATCH',
          tests: [
            sample('3 3\n1 2 3\n4 5 6\n7 8 9\n', '6\n15\n24\n', '1+2+3=6, 4+5+6=15, 7+8+9=24.'),
            sample('1 4\n10 20 30 40\n', '100\n'),
            hidden('2 2\n0 0\n0 0\n', '0\n0\n', 30),
            hidden('2 3\n-1 -2 -3\n1 2 3\n', '-6\n6\n', 30),
            hidden('4 1\n5\n10\n15\n20\n', '5\n10\n15\n20\n', 40),
          ],
        }, { isOptional: true }),
      ],
    },

    {
      order: 22,
      slug: 'b22-dictionary-tu-dien',
      title: 'Dictionary — Từ điển',
      summary:
        'Lưu dữ liệu theo cặp khoá–giá trị. Khi danh sách không đủ vì em cần tra cứu theo tên chứ không theo vị trí.',
      objectives: [
        'Tạo từ điển và truy cập giá trị bằng khoá',
        'Thêm, sửa, xoá cặp khoá–giá trị',
        'Duyệt từ điển bằng `.items()`, `.keys()`, `.values()`',
        'Dùng `.get()` để tránh lỗi khi khoá không tồn tại',
      ],
      difficulty: 3,
      status: 'OPTIONAL',
      teacherNotes:
        'Lesson 7 (tiếp). GHI CHÚ: Dictionary cũng là trọng tâm thực hành cùng với List. ' +
        'Cho làm nhiều bài, đặc biệt là bài đếm tần suất.',
      blocks: [
        theory('Từ điển — tra cứu theo tên', [
          'Danh sách tra cứu theo **vị trí**: `diem[0]`. Từ điển tra cứu theo **khoá**:',
          '',
          '```python',
          'diem = {"Toan": 8, "Van": 7, "Anh": 9}',
          '',
          'print(diem["Toan"])    # 8',
          '```',
          '',
          'Mỗi phần tử là một cặp `khoa: gia_tri`, ngăn cách bằng dấu phẩy, bọc trong dấu ngoặc nhọn `{}`.',
          '',
          '| Thao tác | Cách viết |',
          '|---|---|',
          '| Thêm hoặc sửa | `diem["Ly"] = 6` |',
          '| Xoá | `del diem["Van"]` |',
          '| Kiểm tra khoá tồn tại | `"Toan" in diem` |',
          '| Số cặp | `len(diem)` |',
          '',
          '⚠️ Truy cập khoá không tồn tại sẽ báo `KeyError`. Dùng `.get()` để an toàn:',
          '',
          '```python',
          'print(diem.get("Su"))        # None — không báo lỗi',
          'print(diem.get("Su", 0))     # 0    — giá trị mặc định',
          '```',
        ], [
          'Từ điển dùng `{khoa: gia_tri}`',
          'Truy cập bằng `d[khoa]`, an toàn hơn là `d.get(khoa, mac_dinh)`',
          'Khoá phải là duy nhất',
        ]),
        theory('Duyệt từ điển', [
          '```python',
          'diem = {"Toan": 8, "Van": 7, "Anh": 9}',
          '',
          '# Duyệt khoá (mặc định)',
          'for mon in diem:',
          '    print(mon)',
          '',
          '# Duyệt cả khoá lẫn giá trị — cách dùng nhiều nhất',
          'for mon, d in diem.items():',
          '    print(f"{mon}: {d}")',
          '',
          '# Chỉ giá trị',
          'print(sum(diem.values()))    # 24',
          '```',
          '',
          '**Ứng dụng kinh điển — đếm tần suất:**',
          '',
          '```python',
          'chu = "banana"',
          'dem = {}',
          'for c in chu:',
          '    dem[c] = dem.get(c, 0) + 1',
          '# {\'b\': 1, \'a\': 3, \'n\': 2}',
          '```',
          '',
          'Mẹo `dem.get(c, 0) + 1` gộp hai việc: nếu chưa có thì bắt đầu từ 0, nếu có rồi thì cộng thêm 1.',
        ], [
          '`.items()` cho cả khoá và giá trị',
          '`.values()` cho danh sách giá trị, dùng được với `sum()`, `max()`',
          '`d[k] = d.get(k, 0) + 1` là mẫu đếm tần suất chuẩn',
        ]),
        example('Sổ điểm bằng từ điển', 'So sánh với cách dùng danh sách ở buổi 20.', [
          'diem = {"Toan": 8, "Van": 7, "Anh": 9, "Ly": 6}',
          '',
          'print("=== BANG DIEM ===")',
          'for mon, d in diem.items():',
          '    print(f"{mon:<6}: {d}")',
          '',
          'print()',
          'print(f"So mon      : {len(diem)}")',
          'print(f"Trung binh  : {sum(diem.values()) / len(diem):.2f}")',
          '',
          '# Tìm môn có điểm cao nhất',
          'mon_cao_nhat = max(diem, key=diem.get)',
          'print(f"Mon cao nhat: {mon_cao_nhat} ({diem[mon_cao_nhat]})")',
          '',
          '# Thêm và sửa',
          'diem["Hoa"] = 7.5',
          'diem["Ly"] = 7',
          'print(f"Sau cap nhat: {diem}")',
          '',
          '# Truy cập an toàn',
          'print(f"Diem Su     : {diem.get(\'Su\', \'chua co\')}")',
        ], {
          output: [
            '=== BANG DIEM ===',
            'Toan  : 8',
            'Van   : 7',
            'Anh   : 9',
            'Ly    : 6',
            '',
            'So mon      : 4',
            'Trung binh  : 7.50',
            'Mon cao nhat: Anh (9)',
            "Sau cap nhat: {'Toan': 8, 'Van': 7, 'Anh': 9, 'Ly': 7, 'Hoa': 7.5}",
            'Diem Su     : chua co',
          ].join('\n'),
          notes: [
            '`max(diem, key=diem.get)` tìm khoá có giá trị lớn nhất — một mẹo rất hữu ích.',
            '`diem["Ly"] = 7` sửa giá trị cũ; `diem["Hoa"] = 7.5` thêm mới. Cùng một cú pháp.',
          ],
        }),
        playground('Sân chơi: từ điển Việt–Anh', [
          'Tạo một từ điển nhỏ dịch từ tiếng Việt sang tiếng Anh, rồi viết chương trình tra từ.',
          '',
          'Nhớ dùng `.get()` để khi tra từ chưa có thì báo lịch sự thay vì lỗi.',
        ], [
          'tu_dien = {',
          '    "sach": "book",',
          '    "but": "pen",',
          '    "truong": "school",',
          '}',
          '',
          'tu = input("Nhap tu tieng Viet: ")',
          'print(tu_dien.get(tu, "Chua co tu nay trong tu dien"))',
        ], 'Chương trình tra được từ có sẵn và không báo lỗi với từ chưa có.'),
        challenge({
          slug: 'p-b22-dem-tan-suat-ky-tu',
          title: 'Đếm tần suất ký tự',
          statement: [
            'Đọc **một dòng** là một chuỗi chỉ gồm chữ cái thường, không có dấu cách.',
            '',
            'In ra tần suất mỗi ký tự, **mỗi ký tự một dòng**, sắp xếp theo **thứ tự bảng chữ cái**, ' +
              'theo mẫu:',
            '',
            '```',
            '<ky_tu>: <so_lan>',
            '```',
            '',
            'Ví dụ với `banana`:',
            '',
            '```',
            'a: 3',
            'b: 1',
            'n: 2',
            '```',
          ].join('\n'),
          hints: [
            'Dùng mẫu đếm: `dem[c] = dem.get(c, 0) + 1`.',
            'Để sắp xếp theo bảng chữ cái: `for c in sorted(dem):`.',
            '`sorted()` trên từ điển cho danh sách khoá đã sắp xếp.',
          ],
          starterCode: [
            'chuoi = input()',
            'dem = {}',
            '',
            '# Đếm từng ký tự',
            '',
            '# In theo thứ tự bảng chữ cái',
          ].join('\n'),
          solutionCode: [
            'chuoi = input()',
            'dem = {}',
            'for c in chuoi:',
            '    dem[c] = dem.get(c, 0) + 1',
            '',
            'for c in sorted(dem):',
            '    print(f"{c}: {dem[c]}")',
          ].join('\n'),
          tier: 'CO_BAN',
          judgeMode: 'IO_MATCH',
          tests: [
            sample('banana\n', 'a: 3\nb: 1\nn: 2\n', 'Sắp theo bảng chữ cái: a, b, n.'),
            sample('aaa\n', 'a: 3\n'),
            hidden('abc\n', 'a: 1\nb: 1\nc: 1\n', 25),
            hidden('z\n', 'z: 1\n', 25),
            hidden('mississippi\n', 'i: 4\nm: 1\np: 2\ns: 4\n', 25),
            hidden('hello\n', 'e: 1\nh: 1\nl: 2\no: 1\n', 25),
          ],
        }),
        challenge({
          slug: 'p-b22-so-diem-theo-mon',
          title: 'Bảng điểm theo môn',
          statement: [
            'Dòng đầu là `N` — số môn học.',
            '',
            '`N` dòng tiếp theo, mỗi dòng có dạng `<ten_mon> <diem>` (tên môn không chứa dấu cách, ' +
              'điểm là số thực).',
            '',
            'In ra **hai dòng**:',
            '',
            '```',
            'Trung binh: <tb>',
            'Cao nhat: <ten_mon>',
            '```',
            '',
            '`<tb>` hiển thị **2 chữ số thập phân**. `<ten_mon>` là môn có điểm cao nhất ' +
              '(đề bảo đảm chỉ có một môn cao nhất).',
          ].join('\n'),
          hints: [
            'Tách mỗi dòng bằng `.split()` — phần đầu là tên, phần sau là điểm.',
            'Lưu vào từ điển: `diem[ten] = float(gia_tri)`.',
            'Môn cao nhất: `max(diem, key=diem.get)`.',
          ],
          starterCode: [
            'n = int(input())',
            'diem = {}',
            '',
            'for i in range(n):',
            '    phan = input().split()',
            '    # phan[0] là tên môn, phan[1] là điểm',
            '',
            '# Tính trung bình và tìm môn cao nhất',
          ].join('\n'),
          solutionCode: [
            'n = int(input())',
            'diem = {}',
            'for i in range(n):',
            '    phan = input().split()',
            '    diem[phan[0]] = float(phan[1])',
            '',
            'print(f"Trung binh: {sum(diem.values()) / len(diem):.2f}")',
            'print(f"Cao nhat: {max(diem, key=diem.get)}")',
          ].join('\n'),
          tier: 'THU_THACH',
          judgeMode: 'IO_MATCH',
          tests: [
            sample(
              '3\nToan 8\nVan 7\nAnh 9\n',
              'Trung binh: 8.00\nCao nhat: Anh\n',
              '(8 + 7 + 9) / 3 = 8.00, và Anh có điểm cao nhất.',
            ),
            sample('1\nToan 10\n', 'Trung binh: 10.00\nCao nhat: Toan\n'),
            hidden('4\nToan 5\nVan 6\nAnh 7\nLy 8\n', 'Trung binh: 6.50\nCao nhat: Ly\n', 25),
            hidden('2\nHoa 9.5\nSinh 4.5\n', 'Trung binh: 7.00\nCao nhat: Hoa\n', 25),
            hidden('3\nA 0\nB 0.1\nC 0\n', 'Trung binh: 0.03\nCao nhat: B\n', 25),
            hidden('5\nM1 1\nM2 2\nM3 3\nM4 4\nM5 10\n', 'Trung binh: 4.00\nCao nhat: M5\n', 25),
          ],
        }),
      ],
    },

    {
      order: 23,
      slug: 'b23-tuple-set-khai-niem',
      title: 'Tuple & Set — Tìm hiểu khái niệm',
      summary:
        'Hai kiểu dữ liệu còn lại của Python, giới thiệu ở mức khái niệm để em nhận ra khi gặp lại. ' +
        'Buổi này không có bài tập lập trình.',
      objectives: [
        'Nhận biết tuple qua dấu ngoặc tròn và tính không thay đổi được',
        'Nhận biết set qua tính không trùng lặp và không có thứ tự',
        'Nêu được khi nào nên chọn tuple hoặc set thay cho list',
      ],
      difficulty: 2,
      status: 'OPTIONAL',
      teacherNotes:
        'Lesson 7 (kết). GHI CHÚ QUAN TRỌNG: Tuple và Set chỉ dạy Ở MỨC LÝ THUYẾT. ' +
        'Không giao bài tập lập trình cho hai kiểu này — phần thực hành nặng đã dồn cho List và Dictionary. ' +
        'Mục tiêu chỉ là để học sinh nhận ra chúng khi gặp trong code người khác.',
      blocks: [
        theory('Tuple — danh sách không sửa được', [
          'Tuple trông giống list nhưng dùng dấu ngoặc **tròn** và **không sửa được** sau khi tạo:',
          '',
          '```python',
          'toa_do = (10, 20)',
          'print(toa_do[0])       # 10  — đọc thì giống list',
          '',
          'toa_do[0] = 99         # LỖI: TypeError',
          '```',
          '',
          '**Khi nào dùng tuple?** Khi dữ liệu đi thành bộ cố định và không nên thay đổi:',
          '',
          '- Toạ độ một điểm: `(x, y)`',
          '- Màu RGB: `(255, 128, 0)`',
          '- Ngày tháng năm: `(2026, 8, 16)`',
          '',
          '💡 Em đã dùng tuple mà chưa biết: `calendar.monthrange()` ở buổi 19 trả về một tuple, ' +
            'và `a, b = map(int, ...)` cũng là cách "mở" một tuple ra hai biến.',
        ], [
          'Tuple dùng ngoặc tròn `( )`, list dùng ngoặc vuông `[ ]`',
          'Tuple KHÔNG sửa được sau khi tạo',
          'Dùng tuple cho dữ liệu cố định đi thành bộ',
        ]),
        theory('Set — tập hợp không trùng lặp', [
          'Set dùng dấu ngoặc **nhọn** và có hai đặc điểm:',
          '',
          '1. **Không chứa phần tử trùng lặp** — thêm phần tử đã có thì không có gì xảy ra',
          '2. **Không có thứ tự** — không truy cập được bằng chỉ số',
          '',
          '```python',
          'mon = {"Toan", "Van", "Toan", "Anh"}',
          'print(mon)             # {\'Toan\', \'Van\', \'Anh\'} — chỉ còn 3',
          'print(len(mon))        # 3',
          '',
          'print(mon[0])          # LỖI: set không có chỉ số',
          '```',
          '',
          '**Ứng dụng thực tế nhất:** loại bỏ trùng lặp khỏi một danh sách.',
          '',
          '```python',
          'so = [1, 2, 2, 3, 3, 3]',
          'khac_nhau = list(set(so))    # [1, 2, 3]',
          '```',
          '',
          'Set cũng làm được phép toán tập hợp như trong Toán: giao `&`, hợp `|`, hiệu `-`.',
        ], [
          'Set dùng ngoặc nhọn `{ }` và tự loại bỏ trùng lặp',
          'Set không có thứ tự nên không truy cập bằng chỉ số',
          '`list(set(ds))` là cách nhanh nhất để loại trùng',
        ]),
        example('Bốn kiểu cạnh nhau', 'Cùng một dữ liệu, bốn cách lưu trữ khác nhau.', [
          '# LIST — có thứ tự, sửa được, cho phép trùng',
          'ds = [3, 1, 2, 3]',
          'ds.append(4)',
          'print(f"List : {ds}")',
          '',
          '# TUPLE — có thứ tự, KHÔNG sửa được, cho phép trùng',
          'tp = (3, 1, 2, 3)',
          'print(f"Tuple: {tp}  (khong the them/sua)")',
          '',
          '# SET — KHÔNG thứ tự, sửa được, KHÔNG trùng',
          'st = {3, 1, 2, 3}',
          'print(f"Set  : {st}  (da loai trung)")',
          '',
          '# DICT — cặp khoá:giá trị, khoá không trùng',
          'dt = {"a": 3, "b": 1, "c": 2}',
          'print(f"Dict : {dt}")',
          '',
          'print()',
          'print("Chon kieu nao?")',
          'print("- Nhieu gia tri, can thu tu, hay thay doi  -> LIST")',
          'print("- Bo gia tri co dinh, khong doi            -> TUPLE")',
          'print("- Chi can biet co gi, khong quan tam so lan -> SET")',
          'print("- Tra cuu theo ten                          -> DICT")',
        ], {
          output: [
            'List : [3, 1, 2, 3, 4]',
            'Tuple: (3, 1, 2, 3)  (khong the them/sua)',
            'Set  : {1, 2, 3}  (da loai trung)',
            "Dict : {'a': 3, 'b': 1, 'c': 2}",
            '',
            'Chon kieu nao?',
            '- Nhieu gia tri, can thu tu, hay thay doi  -> LIST',
            '- Bo gia tri co dinh, khong doi            -> TUPLE',
            '- Chi can biet co gi, khong quan tam so lan -> SET',
            '- Tra cuu theo ten                          -> DICT',
          ].join('\n'),
          notes: [
            'Set in ra `{1, 2, 3}` — số 3 chỉ còn một lần và thứ tự đã khác lúc tạo.',
            'Trong khoá học này, em sẽ dùng LIST và DICT là chính. Hai kiểu còn lại chỉ cần nhận ra khi gặp.',
          ],
        }),
        quizBlock({
          slug: 'q-b23-tuple-set',
          title: 'Kiểm tra nhanh: Tuple & Set',
          questions: [
            {
              type: 'MULTIPLE_CHOICE',
              prompt: 'Điểm khác biệt lớn nhất giữa tuple và list là gì?',
              explanation: 'Tuple không thể sửa sau khi tạo, còn list thì sửa được thoải mái.',
              choices: [
                { text: 'Tuple không sửa được sau khi tạo', isCorrect: true },
                { text: 'Tuple chỉ chứa được số' },
                { text: 'Tuple không có thứ tự' },
                { text: 'Tuple không dùng được vòng lặp' },
              ],
            },
            {
              type: 'MULTIPLE_CHOICE',
              prompt: '`len({1, 2, 2, 3, 3, 3})` cho kết quả nào?',
              explanation: 'Set loại bỏ phần tử trùng, chỉ còn 1, 2, 3 nên độ dài là 3.',
              choices: [
                { text: '3', isCorrect: true },
                { text: '6' },
                { text: '2' },
                { text: 'Báo lỗi' },
              ],
            },
            {
              type: 'MULTIPLE_CHOICE',
              prompt: 'Muốn loại bỏ các giá trị trùng lặp khỏi danh sách `ds`, cách nào nhanh nhất?',
              explanation: 'Đổi sang set để loại trùng, rồi đổi lại thành list.',
              choices: [
                { text: 'list(set(ds))', isCorrect: true },
                { text: 'ds.remove_duplicates()' },
                { text: 'ds.unique()' },
                { text: 'tuple(ds)' },
              ],
            },
            {
              type: 'TRUE_FALSE',
              prompt: 'Có thể truy cập phần tử của set bằng chỉ số, ví dụ `s[0]`.',
              explanation: 'Sai. Set không có thứ tự nên không có khái niệm chỉ số.',
              choices: [{ text: 'Đúng' }, { text: 'Sai', isCorrect: true }],
            },
            {
              type: 'SHORT_ANSWER',
              prompt:
                'Em sẽ chọn kiểu dữ liệu nào để lưu danh sách các bạn đã nộp bài (mỗi bạn chỉ tính một lần, ' +
                'không quan tâm thứ tự)? Vì sao?',
              explanation:
                'Set là lựa chọn hợp lý: nó tự loại trùng nên một bạn nộp hai lần cũng chỉ tính một, ' +
                'và ta không cần thứ tự. Dùng list cũng được nhưng phải tự kiểm tra trùng.',
              points: 15,
            },
          ],
        }),
      ],
    },
  ],
};
