/**
 * Expansion pack — Python Nâng Cao, sessions 16–30.
 *
 * The API sessions (19–22) parse a response body supplied on stdin rather than
 * calling `requests`. That is not a shortcut around note 16 — it is the same
 * reasoning the note encodes. The sandbox has no egress, so an exercise that
 * fetched a live URL could only ever be graded on whether someone else's server
 * happened to be up. What a student actually gets wrong is reading the body:
 * a missing key, a nested list, a status code they forgot to check.
 *
 * The sorting sessions keep n small. These are IO_MATCH exercises about
 * understanding an algorithm, not the PERFORMANCE scenarios session 30 already
 * carries for the 100 → 100 000 contrast that note 17 requires.
 */
import { challenge, hidden, sample } from '../../builders.ts';

import type { BoSungKhoaHoc } from './ap-dung.ts';

export const boSungNangCao2: BoSungKhoaHoc = {
  'nc-b16-socket-udp-va-tong-ket': {
    khoi: [
      challenge({
        slug: 'p-bs-nc-b16-sap-xep-lai-goi-udp',
        title: 'Sắp xếp lại gói UDP đến sai thứ tự',
        statement: [
          'UDP không đảm bảo thứ tự, nên mỗi gói mang theo số thứ tự.',
          '',
          'Đọc số lượng `n` rồi `n` dòng `<stt>|<noi dung>` đến theo thứ tự bất kỳ.',
          '',
          'In ra nội dung đã xếp đúng theo `stt` tăng dần, mỗi dòng một nội dung.',
        ].join('\n'),
        hints: ['Lưu vào dict với khoá là stt rồi duyệt các khoá đã sắp xếp.'],
        starterCode: ['n = int(input())', 'goi = {}', '', '# Nhận rồi sắp xếp'].join('\n'),
        solutionCode: [
          'n = int(input())',
          'goi = {}',
          'for _ in range(n):',
          '    stt, noi_dung = input().split("|")',
          '    goi[int(stt)] = noi_dung',
          'for k in sorted(goi):',
          '    print(goi[k])',
        ].join('\n'),
        tier: 'THU_THACH',
        judgeMode: 'IO_MATCH',
        tests: [
          sample('3\n2|the\n1|xin\n3|gioi\n', 'xin\nthe\ngioi\n', 'Gói tới lộn xộn nhưng ghép lại đúng.'),
          hidden('2\n1|a\n2|b\n', 'a\nb\n', 30),
        ],
      }),
      challenge({
        slug: 'p-bs-nc-b16-phat-hien-thieu-goi',
        title: 'Gói nào chưa tới',
        statement: [
          'Đọc **tổng số gói được gửi** rồi số lượng `n` và `n` số thứ tự đã nhận',
          '(đánh số từ 1).',
          '',
          'In ra các số thứ tự **còn thiếu**, tăng dần, cách nhau một dấu cách.',
          'Nếu không thiếu gì, in ra `Du`.',
        ].join('\n'),
        hints: ['`set` giúp kiểm tra đã nhận hay chưa rất nhanh.'],
        starterCode: ['tong = int(input())', 'n = int(input())', '', '# Tìm gói thiếu'].join('\n'),
        solutionCode: [
          'tong = int(input())',
          'n = int(input())',
          'da_nhan = set()',
          'for _ in range(n):',
          '    da_nhan.add(int(input()))',
          'thieu = [str(i) for i in range(1, tong + 1) if i not in da_nhan]',
          'if len(thieu) == 0:',
          '    print("Du")',
          'else:',
          '    print(" ".join(thieu))',
        ].join('\n'),
        tier: 'THU_THACH',
        judgeMode: 'IO_MATCH',
        tests: [
          sample('5\n3\n1\n3\n5\n', '2 4\n', 'Thiếu gói 2 và 4.'),
          sample('3\n3\n1\n2\n3\n', 'Du\n', 'Nhận đủ cả ba.'),
          hidden('4\n0\n', '1 2 3 4\n', 30),
        ],
      }),
    ],
  },

  'nc-b17-regex-co-ban': {
    khoi: [
      challenge({
        slug: 'p-bs-nc-b17-tim-tat-ca-so',
        title: 'Rút hết các số trong câu',
        statement: [
          'Đọc một dòng bất kỳ.',
          '',
          'In ra tất cả các **cụm chữ số** xuất hiện, cách nhau một dấu cách.',
          'Nếu không có số nào, in ra `Khong co`.',
        ].join('\n'),
        hints: ['`re.findall(r"[0-9]+", s)` lấy hết các cụm chữ số.'],
        starterCode: ['import re', '', 's = input()', '', '# Tìm các cụm số'].join('\n'),
        solutionCode: [
          'import re',
          '',
          's = input()',
          'so = re.findall(r"[0-9]+", s)',
          'if len(so) == 0:',
          '    print("Khong co")',
          'else:',
          '    print(" ".join(so))',
        ].join('\n'),
        tier: 'CO_BAN',
        judgeMode: 'IO_MATCH',
        tests: [
          sample('Lop 7A1 co 32 ban va 2 giao vien\n', '7 1 32 2\n', '7 và 1 tách ra vì có chữ A ở giữa.'),
          sample('khong co chu so\n', 'Khong co\n', 'Không khớp gì cả.'),
          hidden('abc123\n', '123\n', 30),
        ],
      }),
      challenge({
        slug: 'p-bs-nc-b17-kiem-tra-ma-lop',
        title: 'Mã lớp có đúng định dạng không',
        statement: [
          'Mã lớp hợp lệ gồm: **một chữ số**, **một chữ cái in hoa**, **một chữ số**.',
          'Ví dụ `7A1`.',
          '',
          'Đọc số lượng `n` rồi `n` mã. In `Dung` hoặc `Sai` cho từng mã.',
        ].join('\n'),
        hints: ['`re.fullmatch` bắt buộc khớp toàn bộ chuỗi, khác với `search`.'],
        starterCode: ['import re', '', 'n = int(input())', '', '# Kiểm tra từng mã'].join('\n'),
        solutionCode: [
          'import re',
          '',
          'n = int(input())',
          'for _ in range(n):',
          '    ma = input()',
          '    if re.fullmatch(r"[0-9][A-Z][0-9]", ma):',
          '        print("Dung")',
          '    else:',
          '        print("Sai")',
        ].join('\n'),
        tier: 'THU_THACH',
        judgeMode: 'IO_MATCH',
        tests: [
          sample('3\n7A1\n7a1\n12A3\n', 'Dung\nSai\nSai\n', 'Chữ thường và độ dài sai đều bị loại.'),
          hidden('2\n0Z9\n7A\n', 'Dung\nSai\n', 30),
        ],
      }),
    ],
  },

  'nc-b18-regex-nang-cao': {
    khoi: [
      challenge({
        slug: 'p-bs-nc-b18-nhom-tach-ngay',
        title: 'Tách ngày tháng bằng nhóm',
        statement: [
          'Đọc một dòng chứa một ngày dạng `dd/mm/yyyy`.',
          '',
          'Dùng **nhóm** trong regex để in ra ba dòng:',
          '`Ngay: <dd>`, `Thang: <mm>`, `Nam: <yyyy>`.',
          '',
          'Nếu không tìm thấy ngày nào, in ra `Khong tim thay`.',
        ].join('\n'),
        hints: ['Cặp ngoặc tròn tạo một nhóm; `m.group(1)` lấy nhóm đầu.'],
        starterCode: ['import re', '', 's = input()', '', '# Tách bằng nhóm'].join('\n'),
        solutionCode: [
          'import re',
          '',
          's = input()',
          'm = re.search(r"([0-9]{2})/([0-9]{2})/([0-9]{4})", s)',
          'if m is None:',
          '    print("Khong tim thay")',
          'else:',
          '    print(f"Ngay: {m.group(1)}")',
          '    print(f"Thang: {m.group(2)}")',
          '    print(f"Nam: {m.group(3)}")',
        ].join('\n'),
        tier: 'THU_THACH',
        judgeMode: 'IO_MATCH',
        tests: [
          sample('Han nop la 05/09/2026 nhe\n', 'Ngay: 05\nThang: 09\nNam: 2026\n', 'Ba nhóm lấy ra ba phần.'),
          sample('khong co ngay\n', 'Khong tim thay\n', 'Không khớp mẫu nào.'),
          hidden('01/01/2000\n', 'Ngay: 01\nThang: 01\nNam: 2000\n', 30),
        ],
      }),
      challenge({
        slug: 'p-bs-nc-b18-che-so-dien-thoai',
        title: 'Che bớt số điện thoại',
        statement: [
          'Đọc một dòng. Thay mọi dãy **10 chữ số liền nhau** bằng',
          'ba chữ số đầu cộng `*******`.',
          '',
          'In ra dòng đã thay.',
        ].join('\n'),
        hints: ['`re.sub` nhận một hàm thay thế.', 'Trong hàm đó, `m.group(0)` là phần khớp.'],
        starterCode: ['import re', '', 's = input()', '', '# Thay thế'].join('\n'),
        solutionCode: [
          'import re',
          '',
          's = input()',
          'print(re.sub(r"[0-9]{10}", lambda m: m.group(0)[:3] + "*******", s))',
        ].join('\n'),
        tier: 'NANG_CAO',
        judgeMode: 'IO_MATCH',
        tests: [
          sample('Goi 0912345678 nhe\n', 'Goi 091******* nhe\n', 'Giữ ba số đầu, che bảy số sau.'),
          hidden('0123456789 va 0987654321\n', '012******* va 098*******\n', 30),
          hidden('khong co so\n', 'khong co so\n', 30),
        ],
      }),
    ],
  },

  'nc-b19-requests-get': {
    khoi: [
      challenge({
        slug: 'p-bs-nc-b19-dung-query-string',
        title: 'Dựng query string',
        statement: [
          'Đọc số lượng `n` rồi `n` dòng `<khoa>=<gia tri>`.',
          '',
          'In ra query string hoàn chỉnh: các cặp nối bằng `&`, có dấu `?` ở đầu.',
          'Nếu `n` bằng 0, in ra chuỗi rỗng (một dòng trống).',
        ].join('\n'),
        hints: ['`"&".join(...)` nối các cặp.'],
        starterCode: ['n = int(input())', '', '# Dựng query string'].join('\n'),
        solutionCode: [
          'n = int(input())',
          'cap = [input() for _ in range(n)]',
          'if n == 0:',
          '    print("")',
          'else:',
          '    print("?" + "&".join(cap))',
        ].join('\n'),
        tier: 'CO_BAN',
        judgeMode: 'IO_MATCH',
        tests: [
          sample('2\nlop=7A1\nsap_xep=ten\n', '?lop=7A1&sap_xep=ten\n', 'Dấu ? chỉ xuất hiện một lần, ở đầu.'),
          hidden('1\na=1\n', '?a=1\n', 30),
          hidden('0\n', '\n', 30),
        ],
      }),
      challenge({
        slug: 'p-bs-nc-b19-doc-than-phan-hoi',
        title: 'Đọc thân phản hồi JSON',
        statement: [
          'Dòng đầu là **mã trạng thái**, dòng thứ hai là **thân phản hồi** dạng JSON.',
          '',
          'Nếu mã là 200, in ra giá trị của khoá `ten`.',
          'Nếu không, in ra `Loi <mã>` và không đụng tới thân phản hồi.',
        ].join('\n'),
        hints: ['Kiểm tra mã trạng thái TRƯỚC khi phân tích thân — thân của một lỗi thường không có cấu trúc em mong đợi.'],
        starterCode: [
          'import json',
          '',
          'ma = int(input())',
          'than = input()',
          '',
          '# Kiểm tra mã rồi mới đọc',
        ].join('\n'),
        solutionCode: [
          'import json',
          '',
          'ma = int(input())',
          'than = input()',
          'if ma == 200:',
          '    print(json.loads(than)["ten"])',
          'else:',
          '    print(f"Loi {ma}")',
        ].join('\n'),
        tier: 'THU_THACH',
        judgeMode: 'IO_MATCH',
        tests: [
          sample('200\n{"ten": "Lan", "tuoi": 12}\n', 'Lan\n', 'Mã 200 nên đọc thân bình thường.'),
          sample('404\nkhong phai json\n', 'Loi 404\n', 'Không phân tích thân khi mã báo lỗi.'),
          hidden('200\n{"ten": "Minh"}\n', 'Minh\n', 30),
        ],
      }),
    ],
  },

  'nc-b20-post-headers-status': {
    khoi: [
      challenge({
        slug: 'p-bs-nc-b20-doc-header',
        title: 'Tra một header',
        statement: [
          'Đọc số lượng `n` rồi `n` dòng header dạng `<Ten>: <gia tri>`.',
          'Dòng cuối là **tên header cần tra**.',
          '',
          'Tên header **không phân biệt hoa thường**. In ra giá trị, hoặc `Khong co`.',
        ].join('\n'),
        hints: ['Chuẩn hoá tên về chữ thường khi lưu và khi tra.', '`split(": ", 1)` tránh cắt nhầm dấu hai chấm trong giá trị.'],
        starterCode: ['n = int(input())', 'bang = {}', '', '# Đọc rồi tra'].join('\n'),
        solutionCode: [
          'n = int(input())',
          'bang = {}',
          'for _ in range(n):',
          '    ten, gt = input().split(": ", 1)',
          '    bang[ten.lower()] = gt',
          'can = input().lower()',
          'if can in bang:',
          '    print(bang[can])',
          'else:',
          '    print("Khong co")',
        ].join('\n'),
        tier: 'THU_THACH',
        judgeMode: 'IO_MATCH',
        tests: [
          sample(
            '2\nContent-Type: application/json\nX-Token: abc123\ncontent-type\n',
            'application/json\n',
            'Tra được dù viết thường hết.',
          ),
          sample('1\nA: 1\nB\n', 'Khong co\n', 'Không có header B.'),
          hidden('1\nHost: dyelms.vn\nHOST\n', 'dyelms.vn\n', 30),
        ],
      }),
      challenge({
        slug: 'p-bs-nc-b20-thu-lai-khi-loi',
        title: 'Thử lại bao nhiêu lần',
        statement: [
          'Chỉ nên thử lại với lỗi **5xx** (lỗi phía server), tối đa `k` lần.',
          'Lỗi 4xx là do phía mình nên thử lại cũng vô ích.',
          '',
          'Đọc `k`, rồi số lượng `n`, rồi `n` mã trạng thái của các lần gọi liên tiếp.',
          '',
          'In ra số lần **thực sự thử lại**. Dừng ngay khi gặp mã 2xx hoặc 4xx.',
        ].join('\n'),
        hints: ['Lần gọi đầu tiên không tính là “thử lại”.'],
        starterCode: ['k = int(input())', 'n = int(input())', '', '# Đếm số lần thử lại'].join('\n'),
        solutionCode: [
          'k = int(input())',
          'n = int(input())',
          'thu_lai = 0',
          'dung = False',
          'for _ in range(n):',
          '    ma = int(input())',
          '    if dung:',
          '        continue',
          '    if ma // 100 == 5 and thu_lai < k:',
          '        thu_lai = thu_lai + 1',
          '    else:',
          '        dung = True',
          'print(thu_lai)',
        ].join('\n'),
        tier: 'NANG_CAO',
        judgeMode: 'IO_MATCH',
        tests: [
          sample('3\n3\n500\n500\n200\n', '2\n', 'Hai lỗi server nên thử lại hai lần rồi thành công.'),
          sample('3\n2\n404\n500\n', '0\n', 'Lỗi 404 dừng ngay, không thử lại.'),
          hidden('1\n3\n500\n500\n500\n', '1\n', 30),
        ],
      }),
    ],
  },

  'nc-b21-phan-tich-json-mo-hinh-hoa': {
    khoi: [
      challenge({
        slug: 'p-bs-nc-b21-duyet-mang-json',
        title: 'Duyệt mảng trong JSON',
        statement: [
          'Đọc một dòng JSON là **mảng các đối tượng**, mỗi đối tượng có `ten` và `diem`.',
          '',
          'In ra tên của những bạn có `diem` từ 8 trở lên, mỗi tên một dòng,',
          'giữ nguyên thứ tự trong mảng.',
        ].join('\n'),
        hints: ['`json.loads` trả về list các dict.'],
        starterCode: [
          'import json',
          '',
          'ds = json.loads(input())',
          '',
          '# Lọc theo điểm',
        ].join('\n'),
        solutionCode: [
          'import json',
          '',
          'ds = json.loads(input())',
          'for m in ds:',
          '    if m["diem"] >= 8:',
          '        print(m["ten"])',
        ].join('\n'),
        tier: 'THU_THACH',
        judgeMode: 'IO_MATCH',
        tests: [
          sample(
            '[{"ten": "Lan", "diem": 9}, {"ten": "Minh", "diem": 6}, {"ten": "Hoa", "diem": 8}]\n',
            'Lan\nHoa\n',
            'Minh dưới 8 nên không in.',
          ),
          hidden('[{"ten": "A", "diem": 7}]\n', '', 30),
        ],
      }),
      challenge({
        slug: 'p-bs-nc-b21-khoa-long-nhau',
        title: 'Lấy giá trị lồng sâu',
        statement: [
          'Đọc một dòng JSON, rồi một **đường dẫn khoá** dạng `a.b.c`.',
          '',
          'In ra giá trị ở đường dẫn đó, hoặc `Khong co` nếu thiếu một khoá bất kỳ.',
        ].join('\n'),
        hints: ['Tách đường dẫn bằng `split(".")` rồi đi từng bước.', 'Kiểm tra khoá tồn tại ở mỗi bước.'],
        starterCode: [
          'import json',
          '',
          'du_lieu = json.loads(input())',
          'duong_dan = input().split(".")',
          '',
          '# Đi từng bước',
        ].join('\n'),
        solutionCode: [
          'import json',
          '',
          'du_lieu = json.loads(input())',
          'duong_dan = input().split(".")',
          'hien_tai = du_lieu',
          'ok = True',
          'for k in duong_dan:',
          '    if isinstance(hien_tai, dict) and k in hien_tai:',
          '        hien_tai = hien_tai[k]',
          '    else:',
          '        ok = False',
          '        break',
          'if ok:',
          '    print(hien_tai)',
          'else:',
          '    print("Khong co")',
        ].join('\n'),
        tier: 'NANG_CAO',
        judgeMode: 'IO_MATCH',
        tests: [
          sample('{"lop": {"gv": {"ten": "Co Lan"}}}\nlop.gv.ten\n', 'Co Lan\n', 'Đi qua ba tầng khoá.'),
          sample('{"lop": {}}\nlop.gv.ten\n', 'Khong co\n', 'Thiếu khoá gv nên dừng.'),
          hidden('{"a": 1}\na\n', '1\n', 30),
        ],
      }),
    ],
  },

  'nc-b22-du-an-tra-cuu-api': {
    khoi: [
      challenge({
        slug: 'p-bs-nc-b22-gop-nhieu-trang',
        title: 'Gộp dữ liệu nhiều trang',
        statement: [
          'API trả dữ liệu theo trang. Đọc số trang `n`, rồi `n` dòng JSON,',
          'mỗi dòng là một mảng tên.',
          '',
          'In ra tổng số tên, rồi tất cả các tên **không trùng lặp**,',
          'theo thứ tự xuất hiện, mỗi tên một dòng.',
        ].join('\n'),
        hints: ['Một list giữ thứ tự, một set để kiểm tra đã có chưa.'],
        starterCode: ['import json', '', 'n = int(input())', '', '# Gộp các trang'].join('\n'),
        solutionCode: [
          'import json',
          '',
          'n = int(input())',
          'ket = []',
          'da_co = set()',
          'tong = 0',
          'for _ in range(n):',
          '    for t in json.loads(input()):',
          '        tong = tong + 1',
          '        if t not in da_co:',
          '            da_co.add(t)',
          '            ket.append(t)',
          'print(tong)',
          'for t in ket:',
          '    print(t)',
        ].join('\n'),
        tier: 'THU_THACH',
        judgeMode: 'IO_MATCH',
        tests: [
          sample('2\n["Lan", "Minh"]\n["Minh", "Hoa"]\n', '4\nLan\nMinh\nHoa\n', 'Tổng đếm cả trùng, danh sách thì không.'),
          hidden('1\n["a"]\n', '1\na\n', 30),
        ],
      }),
      challenge({
        slug: 'p-bs-nc-b22-bao-cao-tra-cuu',
        title: 'Báo cáo kết quả tra cứu',
        statement: [
          'Đọc số lượng `n` rồi `n` dòng `<tu khoa>|<so ket qua>`.',
          '',
          'In ra ba dòng:',
          '',
          '- `Tong: <tổng số kết quả>`',
          '- `Nhieu nhat: <từ khoá>` (bằng nhau thì lấy từ xuất hiện trước)',
          '- `Khong co ket qua: <số từ khoá có 0 kết quả>`',
        ].join('\n'),
        hints: ['Một lần duyệt là đủ cho cả ba con số.'],
        starterCode: ['n = int(input())', '', '# Tổng hợp báo cáo'].join('\n'),
        solutionCode: [
          'n = int(input())',
          'tong = 0',
          'ten_max = ""',
          'max_kq = -1',
          'rong = 0',
          'for _ in range(n):',
          '    tu, sl = input().split("|")',
          '    sl = int(sl)',
          '    tong = tong + sl',
          '    if sl == 0:',
          '        rong = rong + 1',
          '    if sl > max_kq:',
          '        max_kq = sl',
          '        ten_max = tu',
          'print(f"Tong: {tong}")',
          'print(f"Nhieu nhat: {ten_max}")',
          'print(f"Khong co ket qua: {rong}")',
        ].join('\n'),
        tier: 'THU_THACH',
        judgeMode: 'IO_MATCH',
        tests: [
          sample(
            '3\npython|10\npygame|0\nmicrobit|10\n',
            'Tong: 20\nNhieu nhat: python\nKhong co ket qua: 1\n',
            'python và microbit bằng nhau, giữ từ xuất hiện trước.',
          ),
          hidden('1\na|0\n', 'Tong: 0\nNhieu nhat: a\nKhong co ket qua: 1\n', 30),
        ],
      }),
    ],
  },

  'nc-b23-do-phuc-tap-big-o': {
    khoi: [
      challenge({
        slug: 'p-bs-nc-b23-dem-phep-so-sanh',
        title: 'Đếm số phép so sánh',
        statement: [
          'Tìm kiếm tuyến tính so sánh từng phần tử cho tới khi gặp mục tiêu.',
          '',
          'Đọc số lượng `n`, dãy `n` số trên một dòng, rồi **giá trị cần tìm**.',
          '',
          'In ra số phép so sánh đã thực hiện. Không tìm thấy thì bằng `n`.',
        ].join('\n'),
        hints: ['Đếm mỗi lần chạm vào một phần tử.'],
        starterCode: [
          'n = int(input())',
          'ds = [int(x) for x in input().split()]',
          'muc_tieu = int(input())',
          '',
          '# Đếm số lần so sánh',
        ].join('\n'),
        solutionCode: [
          'n = int(input())',
          'ds = [int(x) for x in input().split()]',
          'muc_tieu = int(input())',
          'dem = 0',
          'for x in ds:',
          '    dem = dem + 1',
          '    if x == muc_tieu:',
          '        break',
          'print(dem)',
        ].join('\n'),
        tier: 'CO_BAN',
        judgeMode: 'IO_MATCH',
        tests: [
          sample('5\n4 8 15 16 23\n15\n', '3\n', 'Tìm thấy ở vị trí thứ ba.'),
          sample('5\n4 8 15 16 23\n99\n', '5\n', 'Không có thì phải duyệt hết.'),
          hidden('3\n1 2 3\n1\n', '1\n', 30),
        ],
      }),
      challenge({
        slug: 'p-bs-nc-b23-uoc-luong-thao-tac',
        title: 'Ước lượng số thao tác theo Big-O',
        statement: [
          'Đọc `n` rồi một chữ: `HANG SO`, `TUYEN TINH`, `BINH PHUONG`.',
          '',
          'In ra số thao tác ước lượng: 1, n, hoặc n × n tương ứng.',
        ].join('\n'),
        hints: ['Đây là bảng tra đơn giản, mục đích là cảm nhận độ lớn.'],
        starterCode: ['n = int(input())', 'loai = input()', '', '# Ước lượng'].join('\n'),
        solutionCode: [
          'n = int(input())',
          'loai = input()',
          'if loai == "HANG SO":',
          '    print(1)',
          'elif loai == "TUYEN TINH":',
          '    print(n)',
          'else:',
          '    print(n * n)',
        ].join('\n'),
        tier: 'CO_BAN',
        judgeMode: 'IO_MATCH',
        tests: [
          sample('1000\nBINH PHUONG\n', '1000000\n', 'Một triệu thao tác cho n = 1000.'),
          hidden('1000\nTUYEN TINH\n', '1000\n', 30),
          hidden('1000\nHANG SO\n', '1\n', 30),
        ],
      }),
    ],
  },

  'nc-b24-tim-kiem-tuyen-tinh-nhi-phan': {
    khoi: [
      challenge({
        slug: 'p-bs-nc-b24-tim-nhi-phan',
        title: 'Tìm kiếm nhị phân',
        statement: [
          'Đọc số lượng `n`, một dãy **đã sắp xếp tăng dần**, rồi giá trị cần tìm.',
          '',
          'In ra **chỉ số** (đếm từ 0) của giá trị đó, hoặc `-1` nếu không có.',
        ].join('\n'),
        hints: ['Giữ hai biên `trai` và `phai`, so sánh với phần tử giữa.', '`giua = (trai + phai) // 2`.'],
        starterCode: [
          'n = int(input())',
          'ds = [int(x) for x in input().split()]',
          'x = int(input())',
          '',
          '# Tìm kiếm nhị phân',
        ].join('\n'),
        solutionCode: [
          'n = int(input())',
          'ds = [int(x) for x in input().split()]',
          'x = int(input())',
          'trai = 0',
          'phai = n - 1',
          'kq = -1',
          'while trai <= phai:',
          '    giua = (trai + phai) // 2',
          '    if ds[giua] == x:',
          '        kq = giua',
          '        break',
          '    if ds[giua] < x:',
          '        trai = giua + 1',
          '    else:',
          '        phai = giua - 1',
          'print(kq)',
        ].join('\n'),
        tier: 'THU_THACH',
        judgeMode: 'IO_MATCH',
        tests: [
          sample('5\n1 3 5 7 9\n7\n', '3\n', '7 nằm ở chỉ số 3.'),
          sample('5\n1 3 5 7 9\n4\n', '-1\n', '4 không có trong dãy.'),
          hidden('1\n42\n42\n', '0\n', 30),
          hidden('6\n2 4 6 8 10 12\n2\n', '0\n', 30),
        ],
      }),
      challenge({
        slug: 'p-bs-nc-b24-so-buoc-nhi-phan',
        title: 'Nhị phân đi bao nhiêu bước',
        statement: [
          'Cùng bài toán trên, nhưng in ra **số lần lặp** của vòng `while`',
          'thay vì chỉ số.',
          '',
          'Con số này cho thấy vì sao nhị phân nhanh hơn tuyến tính rất nhiều.',
        ].join('\n'),
        hints: ['Đếm mỗi vòng lặp, kể cả vòng tìm thấy.'],
        starterCode: [
          'n = int(input())',
          'ds = [int(x) for x in input().split()]',
          'x = int(input())',
          '',
          '# Đếm số bước',
        ].join('\n'),
        solutionCode: [
          'n = int(input())',
          'ds = [int(x) for x in input().split()]',
          'x = int(input())',
          'trai = 0',
          'phai = n - 1',
          'buoc = 0',
          'while trai <= phai:',
          '    buoc = buoc + 1',
          '    giua = (trai + phai) // 2',
          '    if ds[giua] == x:',
          '        break',
          '    if ds[giua] < x:',
          '        trai = giua + 1',
          '    else:',
          '        phai = giua - 1',
          'print(buoc)',
        ].join('\n'),
        tier: 'THU_THACH',
        judgeMode: 'IO_MATCH',
        tests: [
          sample('7\n1 2 3 4 5 6 7\n4\n', '1\n', 'Phần tử giữa trúng ngay lần đầu.'),
          hidden('7\n1 2 3 4 5 6 7\n1\n', '3\n', 30),
          hidden('7\n1 2 3 4 5 6 7\n8\n', '3\n', 30),
        ],
      }),
    ],
  },

  'nc-b25-jump-interpolation-exponential': {
    khoi: [
      challenge({
        slug: 'p-bs-nc-b25-jump-search',
        title: 'Jump Search',
        statement: [
          'Đọc `n`, một dãy **đã sắp xếp**, rồi giá trị cần tìm.',
          '',
          'Nhảy từng bước `b` (đọc ở dòng cuối) cho tới khi vượt qua giá trị,',
          'rồi tìm tuyến tính trong khối đó.',
          '',
          'In ra chỉ số tìm được, hoặc `-1`.',
        ].join('\n'),
        hints: ['Nhảy tới khi `ds[min(i + b, n) - 1] >= x`.', 'Sau đó quét tuyến tính trong khoảng vừa xác định.'],
        starterCode: [
          'n = int(input())',
          'ds = [int(v) for v in input().split()]',
          'x = int(input())',
          'b = int(input())',
          '',
          '# Jump search',
        ].join('\n'),
        solutionCode: [
          'n = int(input())',
          'ds = [int(v) for v in input().split()]',
          'x = int(input())',
          'b = int(input())',
          'i = 0',
          'while i < n and ds[min(i + b, n) - 1] < x:',
          '    i = i + b',
          'kq = -1',
          'for j in range(i, min(i + b, n)):',
          '    if ds[j] == x:',
          '        kq = j',
          '        break',
          'print(kq)',
        ].join('\n'),
        tier: 'NANG_CAO',
        judgeMode: 'IO_MATCH',
        tests: [
          sample('8\n1 3 5 7 9 11 13 15\n9\n3\n', '4\n', 'Nhảy hai khối rồi quét thấy 9 ở chỉ số 4.'),
          sample('8\n1 3 5 7 9 11 13 15\n4\n3\n', '-1\n', '4 không có trong dãy.'),
          hidden('4\n2 4 6 8\n8\n2\n', '3\n', 30),
        ],
      }),
      challenge({
        slug: 'p-bs-nc-b25-tang-gap-doi',
        title: 'Tìm biên bằng cách tăng gấp đôi',
        statement: [
          'Exponential search bắt đầu ở 1 rồi **nhân đôi** cho tới khi vượt qua giá trị.',
          '',
          'Đọc `n`, một dãy đã sắp xếp, rồi giá trị `x`.',
          '',
          'In ra chỉ số đầu tiên `i` (dạng 1, 2, 4, 8, …) mà `ds[i] >= x`,',
          'hoặc `n` nếu không có chỉ số nào như vậy trong dãy.',
        ].join('\n'),
        hints: ['Bắt đầu i = 1, nhân đôi mỗi vòng.', 'Dừng khi i vượt quá n - 1.'],
        starterCode: [
          'n = int(input())',
          'ds = [int(v) for v in input().split()]',
          'x = int(input())',
          '',
          '# Tăng gấp đôi',
        ].join('\n'),
        solutionCode: [
          'n = int(input())',
          'ds = [int(v) for v in input().split()]',
          'x = int(input())',
          'i = 1',
          'kq = n',
          'while i < n:',
          '    if ds[i] >= x:',
          '        kq = i',
          '        break',
          '    i = i * 2',
          'print(kq)',
        ].join('\n'),
        tier: 'NANG_CAO',
        judgeMode: 'IO_MATCH',
        tests: [
          sample('8\n1 2 4 8 16 32 64 128\n10\n', '4\n', 'Chỉ số 1, 2 chưa đủ; chỉ số 4 có giá trị 16.'),
          hidden('8\n1 2 4 8 16 32 64 128\n1000\n', '8\n', 30),
          hidden('4\n1 5 9 13\n5\n', '1\n', 30),
        ],
      }),
    ],
  },

  'nc-b26-sap-xep-co-ban': {
    khoi: [
      challenge({
        slug: 'p-bs-nc-b26-bubble-mot-luot',
        title: 'Bubble sort — một lượt',
        statement: [
          'Đọc `n` và một dãy.',
          '',
          'Thực hiện **đúng một lượt** bubble sort (đổi chỗ các cặp liền kề sai thứ tự,',
          'đi từ trái sang phải một lần) rồi in ra dãy, cách nhau một dấu cách.',
        ].join('\n'),
        hints: ['Một lượt đủ để đẩy phần tử lớn nhất về cuối.'],
        starterCode: [
          'n = int(input())',
          'ds = [int(v) for v in input().split()]',
          '',
          '# Một lượt bubble',
        ].join('\n'),
        solutionCode: [
          'n = int(input())',
          'ds = [int(v) for v in input().split()]',
          'for i in range(n - 1):',
          '    if ds[i] > ds[i + 1]:',
          '        ds[i], ds[i + 1] = ds[i + 1], ds[i]',
          'print(" ".join(str(v) for v in ds))',
        ].join('\n'),
        tier: 'THU_THACH',
        judgeMode: 'IO_MATCH',
        tests: [
          sample('5\n5 1 4 2 8\n', '1 4 2 5 8\n', 'Số 8 đã trôi về cuối sau một lượt.'),
          hidden('3\n3 2 1\n', '2 1 3\n', 30),
          hidden('3\n1 2 3\n', '1 2 3\n', 30),
        ],
      }),
      challenge({
        slug: 'p-bs-nc-b26-selection-sort-day-du',
        title: 'Selection sort đầy đủ',
        statement: [
          'Đọc `n` và một dãy. Sắp xếp tăng dần bằng **selection sort**',
          '(mỗi lượt tìm phần tử nhỏ nhất còn lại rồi đưa về đầu phần chưa sắp).',
          '',
          'In ra dãy đã sắp xếp, cách nhau một dấu cách.',
          '',
          'Không dùng `sorted()` — mục tiêu là tự viết thuật toán.',
        ].join('\n'),
        hints: ['Vòng ngoài đi qua từng vị trí, vòng trong tìm phần tử nhỏ nhất.'],
        starterCode: [
          'n = int(input())',
          'ds = [int(v) for v in input().split()]',
          '',
          '# Selection sort',
        ].join('\n'),
        solutionCode: [
          'n = int(input())',
          'ds = [int(v) for v in input().split()]',
          'for i in range(n):',
          '    nho_nhat = i',
          '    for j in range(i + 1, n):',
          '        if ds[j] < ds[nho_nhat]:',
          '            nho_nhat = j',
          '    ds[i], ds[nho_nhat] = ds[nho_nhat], ds[i]',
          'print(" ".join(str(v) for v in ds))',
        ].join('\n'),
        tier: 'THU_THACH',
        judgeMode: 'IO_MATCH',
        tests: [
          sample('5\n5 1 4 2 8\n', '1 2 4 5 8\n', 'Dãy đã tăng dần.'),
          hidden('4\n-1 -5 0 3\n', '-5 -1 0 3\n', 30),
          hidden('1\n7\n', '7\n', 30),
        ],
      }),
    ],
  },

  'nc-b27-merge-sort': {
    khoi: [
      challenge({
        slug: 'p-bs-nc-b27-tron-hai-day',
        title: 'Trộn hai dãy đã sắp xếp',
        statement: [
          'Đọc `n` và dãy thứ nhất, rồi `m` và dãy thứ hai — **cả hai đã sắp xếp tăng dần**.',
          '',
          'Trộn thành một dãy tăng dần và in ra, cách nhau một dấu cách.',
          '',
          'Đây là bước “merge” — phần lõi của merge sort.',
        ].join('\n'),
        hints: ['Hai con trỏ, mỗi lần lấy phần tử nhỏ hơn.', 'Đừng quên phần đuôi còn lại của một trong hai dãy.'],
        starterCode: [
          'n = int(input())',
          'a = [int(v) for v in input().split()]',
          'm = int(input())',
          'b = [int(v) for v in input().split()]',
          '',
          '# Trộn hai dãy',
        ].join('\n'),
        solutionCode: [
          'n = int(input())',
          'a = [int(v) for v in input().split()]',
          'm = int(input())',
          'b = [int(v) for v in input().split()]',
          'i = 0',
          'j = 0',
          'kq = []',
          'while i < n and j < m:',
          '    if a[i] <= b[j]:',
          '        kq.append(a[i])',
          '        i = i + 1',
          '    else:',
          '        kq.append(b[j])',
          '        j = j + 1',
          'while i < n:',
          '    kq.append(a[i])',
          '    i = i + 1',
          'while j < m:',
          '    kq.append(b[j])',
          '    j = j + 1',
          'print(" ".join(str(v) for v in kq))',
        ].join('\n'),
        tier: 'THU_THACH',
        judgeMode: 'IO_MATCH',
        tests: [
          sample('3\n1 3 5\n3\n2 4 6\n', '1 2 3 4 5 6\n', 'Hai dãy cài răng lược vào nhau.'),
          hidden('2\n1 2\n2\n3 4\n', '1 2 3 4\n', 30),
          hidden('1\n5\n1\n1\n', '1 5\n', 30),
        ],
      }),
      challenge({
        slug: 'p-bs-nc-b27-merge-sort-day-du',
        title: 'Merge sort đầy đủ',
        statement: [
          'Đọc `n` và một dãy. Sắp xếp tăng dần bằng **merge sort đệ quy**.',
          '',
          'In ra dãy đã sắp xếp, cách nhau một dấu cách.',
        ].join('\n'),
        hints: ['Chia đôi, sắp xếp từng nửa, rồi trộn lại.', 'Dãy có 1 phần tử thì đã sắp xếp rồi.'],
        starterCode: [
          'def merge_sort(ds):',
          '    # Chia để trị',
          '    pass',
          '',
          'n = int(input())',
          'ds = [int(v) for v in input().split()]',
        ].join('\n'),
        solutionCode: [
          'def tron(a, b):',
          '    i = 0',
          '    j = 0',
          '    kq = []',
          '    while i < len(a) and j < len(b):',
          '        if a[i] <= b[j]:',
          '            kq.append(a[i])',
          '            i = i + 1',
          '        else:',
          '            kq.append(b[j])',
          '            j = j + 1',
          '    return kq + a[i:] + b[j:]',
          '',
          'def merge_sort(ds):',
          '    if len(ds) <= 1:',
          '        return ds',
          '    giua = len(ds) // 2',
          '    return tron(merge_sort(ds[:giua]), merge_sort(ds[giua:]))',
          '',
          'n = int(input())',
          'ds = [int(v) for v in input().split()]',
          'print(" ".join(str(v) for v in merge_sort(ds)))',
        ].join('\n'),
        tier: 'NANG_CAO',
        judgeMode: 'IO_MATCH',
        tests: [
          sample('6\n5 2 9 1 5 6\n', '1 2 5 5 6 9\n', 'Giá trị trùng nhau vẫn giữ đủ.'),
          hidden('1\n1\n', '1\n', 30),
          hidden('5\n5 4 3 2 1\n', '1 2 3 4 5\n', 30),
        ],
      }),
    ],
  },

  'nc-b28-quick-sort': {
    khoi: [
      challenge({
        slug: 'p-bs-nc-b28-phan-hoach',
        title: 'Phân hoạch quanh chốt',
        statement: [
          'Đọc `n`, một dãy, rồi **giá trị chốt**.',
          '',
          'In ra ba dòng: các phần tử **nhỏ hơn** chốt, **bằng** chốt, và **lớn hơn** chốt,',
          'mỗi dòng cách nhau một dấu cách, giữ nguyên thứ tự xuất hiện.',
          '',
          'Dòng nào rỗng thì in một dòng trống.',
        ].join('\n'),
        hints: ['Ba list riêng, một lần duyệt.'],
        starterCode: [
          'n = int(input())',
          'ds = [int(v) for v in input().split()]',
          'chot = int(input())',
          '',
          '# Phân hoạch',
        ].join('\n'),
        solutionCode: [
          'n = int(input())',
          'ds = [int(v) for v in input().split()]',
          'chot = int(input())',
          'nho = [v for v in ds if v < chot]',
          'bang = [v for v in ds if v == chot]',
          'lon = [v for v in ds if v > chot]',
          'print(" ".join(str(v) for v in nho))',
          'print(" ".join(str(v) for v in bang))',
          'print(" ".join(str(v) for v in lon))',
        ].join('\n'),
        tier: 'THU_THACH',
        judgeMode: 'IO_MATCH',
        tests: [
          sample('6\n5 2 9 5 1 7\n5\n', '2 1\n5 5\n9 7\n', 'Hai phần tử bằng chốt nằm ở dòng giữa.'),
          hidden('3\n1 2 3\n5\n', '1 2 3\n\n\n', 30),
        ],
      }),
      challenge({
        slug: 'p-bs-nc-b28-quick-sort-day-du',
        title: 'Quick sort đầy đủ',
        statement: [
          'Đọc `n` và một dãy. Sắp xếp tăng dần bằng **quick sort đệ quy**,',
          'lấy phần tử **đầu tiên** làm chốt.',
          '',
          'In ra dãy đã sắp xếp, cách nhau một dấu cách.',
        ].join('\n'),
        hints: ['Phân hoạch rồi gọi đệ quy hai nửa.', 'Dãy rỗng hoặc một phần tử là điểm dừng.'],
        starterCode: [
          'def quick_sort(ds):',
          '    # Chốt là phần tử đầu tiên',
          '    pass',
          '',
          'n = int(input())',
          'ds = [int(v) for v in input().split()]',
        ].join('\n'),
        solutionCode: [
          'def quick_sort(ds):',
          '    if len(ds) <= 1:',
          '        return ds',
          '    chot = ds[0]',
          '    nho = [v for v in ds[1:] if v < chot]',
          '    lon = [v for v in ds[1:] if v >= chot]',
          '    return quick_sort(nho) + [chot] + quick_sort(lon)',
          '',
          'n = int(input())',
          'ds = [int(v) for v in input().split()]',
          'print(" ".join(str(v) for v in quick_sort(ds)))',
        ].join('\n'),
        tier: 'NANG_CAO',
        judgeMode: 'IO_MATCH',
        tests: [
          sample('6\n5 2 9 1 5 6\n', '1 2 5 5 6 9\n', 'Phần tử bằng chốt đi về nhánh phải nên không mất.'),
          hidden('5\n1 2 3 4 5\n', '1 2 3 4 5\n', 30),
          hidden('4\n-2 -8 0 3\n', '-8 -2 0 3\n', 30),
        ],
      }),
    ],
  },

  'nc-b29-heap-va-heap-sort': {
    khoi: [
      challenge({
        slug: 'p-bs-nc-b29-k-phan-tu-nho-nhat',
        title: 'K phần tử nhỏ nhất',
        statement: [
          'Đọc `n`, một dãy, rồi `k`.',
          '',
          'In ra `k` phần tử nhỏ nhất theo thứ tự tăng dần, cách nhau một dấu cách.',
          '',
          'Dùng module `heapq`.',
        ].join('\n'),
        hints: ['`heapq.nsmallest(k, ds)` trả về đúng danh sách cần.'],
        starterCode: [
          'import heapq',
          '',
          'n = int(input())',
          'ds = [int(v) for v in input().split()]',
          'k = int(input())',
          '',
          '# Lấy k phần tử nhỏ nhất',
        ].join('\n'),
        solutionCode: [
          'import heapq',
          '',
          'n = int(input())',
          'ds = [int(v) for v in input().split()]',
          'k = int(input())',
          'print(" ".join(str(v) for v in heapq.nsmallest(k, ds)))',
        ].join('\n'),
        tier: 'THU_THACH',
        judgeMode: 'IO_MATCH',
        tests: [
          sample('6\n9 4 7 1 8 2\n3\n', '1 2 4\n', 'Ba giá trị nhỏ nhất, đã sắp xếp.'),
          hidden('3\n5 5 5\n2\n', '5 5\n', 30),
          hidden('4\n-1 -9 3 0\n1\n', '-9\n', 30),
        ],
      }),
      challenge({
        slug: 'p-bs-nc-b29-heap-sort-day-du',
        title: 'Heap sort',
        statement: [
          'Đọc `n` và một dãy.',
          '',
          'Đẩy hết vào một heap rồi lấy ra lần lượt để có dãy tăng dần.',
          'In ra dãy đã sắp xếp, cách nhau một dấu cách.',
        ].join('\n'),
        hints: ['`heapq.heappush` và `heapq.heappop`.', 'Heap của Python luôn lấy ra phần tử nhỏ nhất trước.'],
        starterCode: [
          'import heapq',
          '',
          'n = int(input())',
          'ds = [int(v) for v in input().split()]',
          '',
          '# Heap sort',
        ].join('\n'),
        solutionCode: [
          'import heapq',
          '',
          'n = int(input())',
          'ds = [int(v) for v in input().split()]',
          'h = []',
          'for v in ds:',
          '    heapq.heappush(h, v)',
          'kq = []',
          'while h:',
          '    kq.append(heapq.heappop(h))',
          'print(" ".join(str(v) for v in kq))',
        ].join('\n'),
        tier: 'NANG_CAO',
        judgeMode: 'IO_MATCH',
        tests: [
          sample('5\n3 1 4 1 5\n', '1 1 3 4 5\n', 'Lấy ra khỏi heap là đã tăng dần.'),
          hidden('1\n0\n', '0\n', 30),
          hidden('4\n-3 -1 -2 -4\n', '-4 -3 -2 -1\n', 30),
        ],
      }),
    ],
  },

  'nc-b30-thu-thach-hieu-nang-big-o': {
    khoi: [
      challenge({
        slug: 'p-bs-nc-b30-so-sanh-hai-cach',
        title: 'Hai cách, hai số phép so sánh',
        statement: [
          'Đọc `n`, một dãy **đã sắp xếp**, rồi giá trị `x`.',
          '',
          'In ra hai dòng:',
          '',
          '- `Tuyen tinh: <số phép so sánh>`',
          '- `Nhi phan: <số phép so sánh>`',
          '',
          'Cả hai đếm số lần chạm vào một phần tử, kể cả lần tìm thấy.',
        ].join('\n'),
        hints: ['Chạy lần lượt hai thuật toán trên cùng dữ liệu.'],
        starterCode: [
          'n = int(input())',
          'ds = [int(v) for v in input().split()]',
          'x = int(input())',
          '',
          '# Đếm cho cả hai cách',
        ].join('\n'),
        solutionCode: [
          'n = int(input())',
          'ds = [int(v) for v in input().split()]',
          'x = int(input())',
          'tt = 0',
          'for v in ds:',
          '    tt = tt + 1',
          '    if v == x:',
          '        break',
          'trai = 0',
          'phai = n - 1',
          'np = 0',
          'while trai <= phai:',
          '    np = np + 1',
          '    giua = (trai + phai) // 2',
          '    if ds[giua] == x:',
          '        break',
          '    if ds[giua] < x:',
          '        trai = giua + 1',
          '    else:',
          '        phai = giua - 1',
          'print(f"Tuyen tinh: {tt}")',
          'print(f"Nhi phan: {np}")',
        ].join('\n'),
        tier: 'NANG_CAO',
        judgeMode: 'IO_MATCH',
        tests: [
          sample('7\n1 2 3 4 5 6 7\n7\n', 'Tuyen tinh: 7\nNhi phan: 3\n', 'Phần tử cuối là trường hợp xấu nhất của tuyến tính.'),
          hidden('7\n1 2 3 4 5 6 7\n4\n', 'Tuyen tinh: 4\nNhi phan: 1\n', 30),
        ],
      }),
      challenge({
        slug: 'p-bs-nc-b30-tong-ket-khoa-nang-cao',
        title: 'Tổng kết khoá nâng cao',
        statement: [
          'Đọc số lượng `n` rồi `n` dòng `<chuong>|<diem>`.',
          '',
          'In ra điểm trung bình của **từng chương**, theo thứ tự chương xuất hiện lần đầu,',
          'mỗi dòng theo mẫu `<chuong>: <trung binh 1 chữ số thập phân>`.',
        ].join('\n'),
        hints: ['Hai dict: một cộng tổng, một đếm số bài.', 'Dictionary giữ thứ tự thêm vào.'],
        starterCode: ['n = int(input())', '', '# Gom theo chương'].join('\n'),
        solutionCode: [
          'n = int(input())',
          'tong = {}',
          'dem = {}',
          'for _ in range(n):',
          '    ch, d = input().split("|")',
          '    d = int(d)',
          '    if ch in tong:',
          '        tong[ch] = tong[ch] + d',
          '        dem[ch] = dem[ch] + 1',
          '    else:',
          '        tong[ch] = d',
          '        dem[ch] = 1',
          'for ch in tong:',
          '    print(f"{ch}: {tong[ch] / dem[ch]:.1f}")',
        ].join('\n'),
        tier: 'THU_THACH',
        judgeMode: 'IO_MATCH',
        tests: [
          sample(
            '4\nOOP|8\nMang|9\nOOP|10\nMang|7\n',
            'OOP: 9.0\nMang: 8.0\n',
            'OOP xuất hiện trước nên đứng trước.',
          ),
          hidden('1\nRegex|10\n', 'Regex: 10.0\n', 30),
        ],
      }),
    ],
  },
};
