/**
 * Expansion pack — Python Nâng Cao, sessions 1–10 (the OOP chapter).
 *
 * ── Why every exercise here is UNIT_TEST and not IO_MATCH ────────────────────
 * `packages/db/src/curriculum.test.ts` asserts that EVERY problem in this
 * chapter is judged by unit tests, and the reason is in the test's own name:
 * I/O matching cannot check inheritance. A student can print the right answer
 * from a single function and never write a class at all — stdout looks identical
 * either way, so an IO_MATCH exercise here would grade the output of the lesson
 * while ignoring the lesson.
 *
 * A pytest suite can assert the things this chapter is actually about: that a
 * subclass really inherits, that a property rejects a bad value, that a class
 * variable is shared, that an abstract base refuses instantiation.
 *
 * The judge writes the submission to `solution.py` and the suite below to
 * `test_bai.py`, so every suite imports `from solution import ...`. It runs on
 * PY_TEST (`dye-judge-pytest:3.12`), the only seeded image with pytest.
 */
import { challenge } from '../../builders.ts';

import type { BoSungKhoaHoc } from './ap-dung.ts';

export const boSungNangCaoOOP: BoSungKhoaHoc = {
  'nc-b01-gioi-thieu-oop-mo-hinh-hoa': {
    khoi: [
      challenge({
        slug: 'p-bs-nc-b01-mo-hinh-hoa-sach',
        title: 'Mô hình hoá một quyển sách',
        statement: [
          'Viết class `Sach` với ba thuộc tính `ten`, `tac_gia`, `so_trang`',
          'và một phương thức `mo_ta()` trả về chuỗi:',
          '',
          '```',
          '<ten> - <tac_gia> (<so_trang> trang)',
          '```',
          '',
          'Đây là bước đầu của tư duy mô hình hoá: gom dữ liệu liên quan vào **một** đối tượng.',
        ].join('\n'),
        hints: ['`__init__` nhận ba tham số và gán vào `self`.', 'f-string ghép ba giá trị lại thành một chuỗi.'],
        starterCode: [
          'class Sach:',
          '    def __init__(self, ten, tac_gia, so_trang):',
          '        # Gán ba thuộc tính',
          '        pass',
          '',
          '    def mo_ta(self):',
          '        # Trả về chuỗi mô tả',
          '        pass',
        ].join('\n'),
        solutionCode: [
          'class Sach:',
          '    def __init__(self, ten, tac_gia, so_trang):',
          '        self.ten = ten',
          '        self.tac_gia = tac_gia',
          '        self.so_trang = so_trang',
          '',
          '    def mo_ta(self):',
          '        return f"{self.ten} - {self.tac_gia} ({self.so_trang} trang)"',
        ].join('\n'),
        tier: 'CO_BAN',
        judgeMode: 'UNIT_TEST',
        runtimeImage: 'PY_TEST',
        unitTestCode: [
          'from solution import Sach',
          '',
          '',
          'def test_giu_du_ba_thuoc_tinh():',
          '    s = Sach("De Men", "To Hoai", 180)',
          '    assert s.ten == "De Men"',
          '    assert s.tac_gia == "To Hoai"',
          '    assert s.so_trang == 180',
          '',
          '',
          'def test_mo_ta_dung_mau():',
          '    s = Sach("De Men", "To Hoai", 180)',
          '    assert s.mo_ta() == "De Men - To Hoai (180 trang)"',
          '',
          '',
          'def test_moi_doi_tuong_giu_du_lieu_rieng():',
          '    a = Sach("A", "X", 10)',
          '    b = Sach("B", "Y", 20)',
          '    assert a.mo_ta() == "A - X (10 trang)"',
          '    assert b.mo_ta() == "B - Y (20 trang)"',
        ].join('\n'),
      }),
      challenge({
        slug: 'p-bs-nc-b01-mo-hinh-hoa-diem',
        title: 'Điểm trên mặt phẳng',
        statement: [
          'Viết class `Diem` với `x`, `y` và hai phương thức:',
          '',
          '- `di_chuyen(dx, dy)` — cộng thêm vào `x` và `y`',
          '- `khoang_cach_goc()` — trả về khoảng cách tới gốc toạ độ',
          '',
          'Khoảng cách là số thực; không cần làm tròn.',
        ].join('\n'),
        hints: ['`(self.x ** 2 + self.y ** 2) ** 0.5` là căn bậc hai.', '`di_chuyen` sửa `self`, không trả về gì.'],
        starterCode: [
          'class Diem:',
          '    def __init__(self, x, y):',
          '        self.x = x',
          '        self.y = y',
          '',
          '    def di_chuyen(self, dx, dy):',
          '        pass',
          '',
          '    def khoang_cach_goc(self):',
          '        pass',
        ].join('\n'),
        solutionCode: [
          'class Diem:',
          '    def __init__(self, x, y):',
          '        self.x = x',
          '        self.y = y',
          '',
          '    def di_chuyen(self, dx, dy):',
          '        self.x = self.x + dx',
          '        self.y = self.y + dy',
          '',
          '    def khoang_cach_goc(self):',
          '        return (self.x ** 2 + self.y ** 2) ** 0.5',
        ].join('\n'),
        tier: 'CO_BAN',
        judgeMode: 'UNIT_TEST',
        runtimeImage: 'PY_TEST',
        unitTestCode: [
          'from solution import Diem',
          '',
          '',
          'def test_di_chuyen_sua_chinh_doi_tuong():',
          '    d = Diem(1, 2)',
          '    d.di_chuyen(3, 4)',
          '    assert d.x == 4',
          '    assert d.y == 6',
          '',
          '',
          'def test_khoang_cach_tam_giac_3_4_5():',
          '    assert Diem(3, 4).khoang_cach_goc() == 5.0',
          '',
          '',
          'def test_goc_toa_do():',
          '    assert Diem(0, 0).khoang_cach_goc() == 0.0',
          '',
          '',
          'def test_di_chuyen_am():',
          '    d = Diem(0, 0)',
          '    d.di_chuyen(-3, -4)',
          '    assert d.khoang_cach_goc() == 5.0',
        ].join('\n'),
      }),
    ],
  },

  'nc-b02-class-object-thuoc-tinh-phuong-thuc': {
    khoi: [
      challenge({
        slug: 'p-bs-nc-b02-class-hinh-chu-nhat',
        title: 'Class hình chữ nhật',
        statement: [
          'Viết class `HinhChuNhat` nhận `dai` và `rong` trong `__init__`,',
          'với hai phương thức `chu_vi()` và `dien_tich()`.',
        ].join('\n'),
        hints: ['Cả hai phương thức đọc `self.dai` và `self.rong`.'],
        starterCode: [
          'class HinhChuNhat:',
          '    def __init__(self, dai, rong):',
          '        self.dai = dai',
          '        self.rong = rong',
          '',
          '    # Thêm chu_vi và dien_tich',
        ].join('\n'),
        solutionCode: [
          'class HinhChuNhat:',
          '    def __init__(self, dai, rong):',
          '        self.dai = dai',
          '        self.rong = rong',
          '',
          '    def chu_vi(self):',
          '        return (self.dai + self.rong) * 2',
          '',
          '    def dien_tich(self):',
          '        return self.dai * self.rong',
        ].join('\n'),
        tier: 'CO_BAN',
        judgeMode: 'UNIT_TEST',
        runtimeImage: 'PY_TEST',
        unitTestCode: [
          'from solution import HinhChuNhat',
          '',
          '',
          'def test_chu_vi():',
          '    assert HinhChuNhat(5, 3).chu_vi() == 16',
          '',
          '',
          'def test_dien_tich():',
          '    assert HinhChuNhat(5, 3).dien_tich() == 15',
          '',
          '',
          'def test_hinh_vuong():',
          '    h = HinhChuNhat(4, 4)',
          '    assert h.chu_vi() == 16',
          '    assert h.dien_tich() == 16',
          '',
          '',
          'def test_canh_bang_mot():',
          '    assert HinhChuNhat(1, 1).dien_tich() == 1',
        ].join('\n'),
      }),
      challenge({
        slug: 'p-bs-nc-b02-dem-doi-tuong',
        title: 'Biến của lớp đếm số đối tượng',
        statement: [
          'Viết class `HocSinh` với:',
          '',
          '- **biến của lớp** `so_luong`, bắt đầu từ 0',
          '- `__init__(self, ten)` lưu `ten` và **tăng `so_luong` thêm 1**',
          '',
          'Biến của lớp dùng chung cho mọi đối tượng — đó là điều bài này kiểm tra.',
        ].join('\n'),
        hints: ['Khai báo `so_luong = 0` ngay trong thân class.', 'Tăng bằng `HocSinh.so_luong += 1`, không phải `self.so_luong += 1`.'],
        starterCode: [
          'class HocSinh:',
          '    so_luong = 0',
          '',
          '    def __init__(self, ten):',
          '        self.ten = ten',
          '        # Tăng biến của lớp',
        ].join('\n'),
        solutionCode: [
          'class HocSinh:',
          '    so_luong = 0',
          '',
          '    def __init__(self, ten):',
          '        self.ten = ten',
          '        HocSinh.so_luong = HocSinh.so_luong + 1',
        ].join('\n'),
        tier: 'THU_THACH',
        judgeMode: 'UNIT_TEST',
        runtimeImage: 'PY_TEST',
        unitTestCode: [
          'from solution import HocSinh',
          '',
          '',
          'def test_bat_dau_tu_khong():',
          '    assert HocSinh.so_luong == 0',
          '',
          '',
          'def test_tang_theo_so_doi_tuong():',
          '    truoc = HocSinh.so_luong',
          '    HocSinh("Lan")',
          '    HocSinh("Minh")',
          '    HocSinh("Hoa")',
          '    assert HocSinh.so_luong == truoc + 3',
          '',
          '',
          'def test_dung_chung_chu_khong_rieng_tung_doi_tuong():',
          '    truoc = HocSinh.so_luong',
          '    a = HocSinh("A")',
          '    b = HocSinh("B")',
          '    assert a.so_luong == truoc + 2',
          '    assert b.so_luong == truoc + 2',
          '',
          '',
          'def test_van_giu_ten_rieng():',
          '    a = HocSinh("An")',
          '    assert a.ten == "An"',
        ].join('\n'),
      }),
    ],
  },

  'nc-b03-constructor-init': {
    khoi: [
      challenge({
        slug: 'p-bs-nc-b03-init-gia-tri-mac-dinh',
        title: 'Constructor với giá trị mặc định',
        statement: [
          'Viết class `TaiKhoan` với `__init__(self, chu, so_du=0)`.',
          '',
          'Thêm phương thức `mo_ta()` trả về `"<chu>: <so_du>"`.',
        ].join('\n'),
        hints: ['Tham số mặc định viết ngay trong danh sách tham số.'],
        starterCode: [
          'class TaiKhoan:',
          '    def __init__(self, chu, so_du=0):',
          '        pass',
          '',
          '    def mo_ta(self):',
          '        pass',
        ].join('\n'),
        solutionCode: [
          'class TaiKhoan:',
          '    def __init__(self, chu, so_du=0):',
          '        self.chu = chu',
          '        self.so_du = so_du',
          '',
          '    def mo_ta(self):',
          '        return f"{self.chu}: {self.so_du}"',
        ].join('\n'),
        tier: 'CO_BAN',
        judgeMode: 'UNIT_TEST',
        runtimeImage: 'PY_TEST',
        unitTestCode: [
          'from solution import TaiKhoan',
          '',
          '',
          'def test_dung_mac_dinh_khi_thieu():',
          '    assert TaiKhoan("Lan").so_du == 0',
          '',
          '',
          'def test_nhan_so_du_truyen_vao():',
          '    assert TaiKhoan("Minh", 5000).so_du == 5000',
          '',
          '',
          'def test_mo_ta():',
          '    assert TaiKhoan("Lan").mo_ta() == "Lan: 0"',
          '    assert TaiKhoan("Minh", 250).mo_ta() == "Minh: 250"',
        ].join('\n'),
      }),
      challenge({
        slug: 'p-bs-nc-b03-init-kiem-tra-du-lieu',
        title: 'Constructor tự kiểm tra dữ liệu',
        statement: [
          'Viết class `Diem` với `__init__(self, gia_tri)`.',
          '',
          'Nếu `gia_tri` nằm ngoài khoảng 0–10 thì **kẹp về biên gần nhất**,',
          'rồi lưu vào thuộc tính `gia_tri`.',
          '',
          'Kẹp ngay trong constructor thì mọi đối tượng đều hợp lệ từ lúc sinh ra.',
        ].join('\n'),
        hints: ['`max(0, min(10, gia_tri))` làm cả hai chiều một lúc.'],
        starterCode: [
          'class Diem:',
          '    def __init__(self, gia_tri):',
          '        # Kẹp về khoảng 0..10',
          '        pass',
        ].join('\n'),
        solutionCode: [
          'class Diem:',
          '    def __init__(self, gia_tri):',
          '        self.gia_tri = max(0, min(10, gia_tri))',
        ].join('\n'),
        tier: 'THU_THACH',
        judgeMode: 'UNIT_TEST',
        runtimeImage: 'PY_TEST',
        unitTestCode: [
          'from solution import Diem',
          '',
          '',
          'def test_gia_tri_hop_le_giu_nguyen():',
          '    assert Diem(5).gia_tri == 5',
          '',
          '',
          'def test_kep_can_duoi():',
          '    assert Diem(-2).gia_tri == 0',
          '',
          '',
          'def test_kep_can_tren():',
          '    assert Diem(15).gia_tri == 10',
          '',
          '',
          'def test_dung_hai_bien():',
          '    assert Diem(0).gia_tri == 0',
          '    assert Diem(10).gia_tri == 10',
        ].join('\n'),
      }),
    ],
  },

  'nc-b04-destructor-vong-doi': {
    khoi: [
      challenge({
        slug: 'p-bs-nc-b04-vong-doi-tai-nguyen',
        title: 'Vòng đời của một kết nối',
        statement: [
          'Viết class `KetNoi` với:',
          '',
          '- `__init__(self, ten)` — lưu `ten`, đặt `dang_mo = True`',
          '- `dong()` — đặt `dang_mo = False`',
          '- `trang_thai()` — trả `"mo"` hoặc `"dong"`',
          '',
          'Gọi `dong()` nhiều lần vẫn an toàn.',
        ].join('\n'),
        hints: ['`dong()` chỉ gán `False`, không cần kiểm tra gì trước.'],
        starterCode: [
          'class KetNoi:',
          '    def __init__(self, ten):',
          '        pass',
          '',
          '    def dong(self):',
          '        pass',
          '',
          '    def trang_thai(self):',
          '        pass',
        ].join('\n'),
        solutionCode: [
          'class KetNoi:',
          '    def __init__(self, ten):',
          '        self.ten = ten',
          '        self.dang_mo = True',
          '',
          '    def dong(self):',
          '        self.dang_mo = False',
          '',
          '    def trang_thai(self):',
          '        if self.dang_mo:',
          '            return "mo"',
          '        return "dong"',
        ].join('\n'),
        tier: 'CO_BAN',
        judgeMode: 'UNIT_TEST',
        runtimeImage: 'PY_TEST',
        unitTestCode: [
          'from solution import KetNoi',
          '',
          '',
          'def test_moi_tao_thi_dang_mo():',
          '    k = KetNoi("db")',
          '    assert k.dang_mo is True',
          '    assert k.trang_thai() == "mo"',
          '',
          '',
          'def test_dong_thi_doi_trang_thai():',
          '    k = KetNoi("db")',
          '    k.dong()',
          '    assert k.trang_thai() == "dong"',
          '',
          '',
          'def test_dong_nhieu_lan_van_an_toan():',
          '    k = KetNoi("db")',
          '    k.dong()',
          '    k.dong()',
          '    assert k.trang_thai() == "dong"',
          '',
          '',
          'def test_hai_ket_noi_doc_lap():',
          '    a = KetNoi("a")',
          '    b = KetNoi("b")',
          '    a.dong()',
          '    assert b.trang_thai() == "mo"',
        ].join('\n'),
      }),
      challenge({
        slug: 'p-bs-nc-b04-dem-doi-tuong-con-song',
        title: 'Đếm kết nối đang mở',
        statement: [
          'Viết class `KetNoi` giữ **biến của lớp** `dang_mo` đếm số kết nối chưa đóng.',
          '',
          '- tạo mới: tăng 1',
          '- `dong()`: giảm 1, nhưng **chỉ lần đầu** — đóng hai lần không giảm hai lần',
        ].join('\n'),
        hints: ['Cần một cờ trên từng đối tượng để nhớ nó đã đóng chưa.'],
        starterCode: [
          'class KetNoi:',
          '    dang_mo = 0',
          '',
          '    def __init__(self, ten):',
          '        pass',
          '',
          '    def dong(self):',
          '        pass',
        ].join('\n'),
        solutionCode: [
          'class KetNoi:',
          '    dang_mo = 0',
          '',
          '    def __init__(self, ten):',
          '        self.ten = ten',
          '        self.da_dong = False',
          '        KetNoi.dang_mo = KetNoi.dang_mo + 1',
          '',
          '    def dong(self):',
          '        if not self.da_dong:',
          '            self.da_dong = True',
          '            KetNoi.dang_mo = KetNoi.dang_mo - 1',
        ].join('\n'),
        tier: 'NANG_CAO',
        judgeMode: 'UNIT_TEST',
        runtimeImage: 'PY_TEST',
        unitTestCode: [
          'from solution import KetNoi',
          '',
          '',
          'def test_tao_thi_tang():',
          '    truoc = KetNoi.dang_mo',
          '    KetNoi("a")',
          '    KetNoi("b")',
          '    assert KetNoi.dang_mo == truoc + 2',
          '',
          '',
          'def test_dong_thi_giam():',
          '    truoc = KetNoi.dang_mo',
          '    k = KetNoi("a")',
          '    k.dong()',
          '    assert KetNoi.dang_mo == truoc',
          '',
          '',
          'def test_dong_hai_lan_chi_giam_mot():',
          '    truoc = KetNoi.dang_mo',
          '    k = KetNoi("a")',
          '    k.dong()',
          '    k.dong()',
          '    assert KetNoi.dang_mo == truoc',
        ].join('\n'),
      }),
    ],
  },

  'nc-b05-dong-goi-encapsulation': {
    khoi: [
      challenge({
        slug: 'p-bs-nc-b05-getter-setter',
        title: 'Số dư chỉ đổi qua phương thức',
        statement: [
          'Viết class `Vi` giữ số dư trong thuộc tính riêng `_so_du`.',
          '',
          '- `nap(x)` — cộng thêm x, **bỏ qua** nếu x ≤ 0',
          '- `rut(x)` — trừ đi x, **bỏ qua** nếu x ≤ 0 hoặc không đủ tiền',
          '- `so_du()` — trả về số dư hiện tại',
          '',
          'Số dư không bao giờ được âm.',
        ].join('\n'),
        hints: ['Kiểm tra điều kiện **bên trong** phương thức — đó chính là ý nghĩa của đóng gói.'],
        starterCode: [
          'class Vi:',
          '    def __init__(self, so_du):',
          '        self._so_du = so_du',
          '',
          '    # nap, rut, so_du',
        ].join('\n'),
        solutionCode: [
          'class Vi:',
          '    def __init__(self, so_du):',
          '        self._so_du = so_du',
          '',
          '    def nap(self, x):',
          '        if x > 0:',
          '            self._so_du = self._so_du + x',
          '',
          '    def rut(self, x):',
          '        if 0 < x <= self._so_du:',
          '            self._so_du = self._so_du - x',
          '',
          '    def so_du(self):',
          '        return self._so_du',
        ].join('\n'),
        tier: 'THU_THACH',
        judgeMode: 'UNIT_TEST',
        runtimeImage: 'PY_TEST',
        unitTestCode: [
          'from solution import Vi',
          '',
          '',
          'def test_nap_va_rut_binh_thuong():',
          '    v = Vi(100)',
          '    v.nap(50)',
          '    v.rut(30)',
          '    assert v.so_du() == 120',
          '',
          '',
          'def test_bo_qua_nap_am():',
          '    v = Vi(0)',
          '    v.nap(-10)',
          '    assert v.so_du() == 0',
          '',
          '',
          'def test_khong_rut_qua_so_du():',
          '    v = Vi(50)',
          '    v.rut(500)',
          '    assert v.so_du() == 50',
          '',
          '',
          'def test_rut_het_duoc():',
          '    v = Vi(50)',
          '    v.rut(50)',
          '    assert v.so_du() == 0',
        ].join('\n'),
      }),
      challenge({
        slug: 'p-bs-nc-b05-property-nhiet-do',
        title: 'Thuộc tính có kiểm soát bằng @property',
        statement: [
          'Viết class `CamBien` với `@property` tên `nhiet_do`.',
          '',
          'Setter chỉ nhận giá trị trong khoảng −50 đến 100; ngoài khoảng đó thì',
          '**giữ nguyên giá trị cũ**.',
        ].join('\n'),
        hints: ['`@property` cho getter, `@nhiet_do.setter` cho setter.', 'Lưu giá trị thật trong `self._gt`.'],
        starterCode: [
          'class CamBien:',
          '    def __init__(self, gt):',
          '        self._gt = gt',
          '',
          '    # property + setter',
        ].join('\n'),
        solutionCode: [
          'class CamBien:',
          '    def __init__(self, gt):',
          '        self._gt = gt',
          '',
          '    @property',
          '    def nhiet_do(self):',
          '        return self._gt',
          '',
          '    @nhiet_do.setter',
          '    def nhiet_do(self, gt):',
          '        if -50 <= gt <= 100:',
          '            self._gt = gt',
        ].join('\n'),
        tier: 'NANG_CAO',
        judgeMode: 'UNIT_TEST',
        runtimeImage: 'PY_TEST',
        unitTestCode: [
          'from solution import CamBien',
          '',
          '',
          'def test_doc_duoc_nhu_thuoc_tinh():',
          '    c = CamBien(20)',
          '    assert c.nhiet_do == 20',
          '',
          '',
          'def test_gan_gia_tri_hop_le():',
          '    c = CamBien(20)',
          '    c.nhiet_do = 30',
          '    assert c.nhiet_do == 30',
          '',
          '',
          'def test_tu_choi_gia_tri_qua_lon():',
          '    c = CamBien(20)',
          '    c.nhiet_do = 999',
          '    assert c.nhiet_do == 20',
          '',
          '',
          'def test_tu_choi_gia_tri_qua_nho():',
          '    c = CamBien(20)',
          '    c.nhiet_do = -100',
          '    assert c.nhiet_do == 20',
          '',
          '',
          'def test_nhan_dung_hai_bien():',
          '    c = CamBien(0)',
          '    c.nhiet_do = 100',
          '    assert c.nhiet_do == 100',
          '    c.nhiet_do = -50',
          '    assert c.nhiet_do == -50',
        ].join('\n'),
      }),
    ],
  },

  'nc-b06-ke-thua-inheritance': {
    khoi: [
      challenge({
        slug: 'p-bs-nc-b06-lop-con-goi-super',
        title: 'Lớp con gọi `super()`',
        statement: [
          '`Nguoi` có `ten` và `gioi_thieu()` trả về `"Toi la <ten>"`.',
          '',
          'Viết `GiaoVien(Nguoi)` thêm thuộc tính `mon`, với `__init__` **gọi `super()`**',
          'thay vì tự gán lại `self.ten`.',
          '',
          'Thêm `day()` trả về `"<ten> day <mon>"`.',
        ].join('\n'),
        hints: ['`super().__init__(ten)` chạy constructor của lớp cha.'],
        starterCode: [
          'class Nguoi:',
          '    def __init__(self, ten):',
          '        self.ten = ten',
          '',
          '    def gioi_thieu(self):',
          '        return f"Toi la {self.ten}"',
          '',
          '',
          'class GiaoVien(Nguoi):',
          '    def __init__(self, ten, mon):',
          '        pass',
          '',
          '    def day(self):',
          '        pass',
        ].join('\n'),
        solutionCode: [
          'class Nguoi:',
          '    def __init__(self, ten):',
          '        self.ten = ten',
          '',
          '    def gioi_thieu(self):',
          '        return f"Toi la {self.ten}"',
          '',
          '',
          'class GiaoVien(Nguoi):',
          '    def __init__(self, ten, mon):',
          '        super().__init__(ten)',
          '        self.mon = mon',
          '',
          '    def day(self):',
          '        return f"{self.ten} day {self.mon}"',
        ].join('\n'),
        tier: 'CO_BAN',
        judgeMode: 'UNIT_TEST',
        runtimeImage: 'PY_TEST',
        unitTestCode: [
          'from solution import GiaoVien, Nguoi',
          '',
          '',
          'def test_thuc_su_ke_thua():',
          '    assert issubclass(GiaoVien, Nguoi)',
          '    assert isinstance(GiaoVien("Co Lan", "Toan"), Nguoi)',
          '',
          '',
          'def test_thua_huong_phuong_thuc_cua_cha():',
          '    g = GiaoVien("Co Lan", "Toan")',
          '    assert g.gioi_thieu() == "Toi la Co Lan"',
          '',
          '',
          'def test_phuong_thuc_rieng():',
          '    assert GiaoVien("Thay Minh", "Tin hoc").day() == "Thay Minh day Tin hoc"',
        ].join('\n'),
      }),
      challenge({
        slug: 'p-bs-nc-b06-mo-rong-phuong-thuc',
        title: 'Mở rộng phương thức của cha',
        statement: [
          '`Hinh` có `mo_ta()` trả về `"Hinh"`.',
          '',
          'Viết `HinhTron(Hinh)` nhận `r`, ghi đè `mo_ta()` để trả về',
          '`"<mô tả của cha> tron ban kinh <r>"` — **gọi lại `super().mo_ta()`**',
          'chứ không viết cứng chữ `"Hinh"`.',
        ].join('\n'),
        hints: ['`super().mo_ta()` lấy kết quả của lớp cha rồi em nối thêm.'],
        starterCode: [
          'class Hinh:',
          '    def mo_ta(self):',
          '        return "Hinh"',
          '',
          '',
          'class HinhTron(Hinh):',
          '    def __init__(self, r):',
          '        self.r = r',
          '',
          '    def mo_ta(self):',
          '        pass',
        ].join('\n'),
        solutionCode: [
          'class Hinh:',
          '    def mo_ta(self):',
          '        return "Hinh"',
          '',
          '',
          'class HinhTron(Hinh):',
          '    def __init__(self, r):',
          '        self.r = r',
          '',
          '    def mo_ta(self):',
          '        return f"{super().mo_ta()} tron ban kinh {self.r}"',
        ].join('\n'),
        tier: 'THU_THACH',
        judgeMode: 'UNIT_TEST',
        runtimeImage: 'PY_TEST',
        unitTestCode: [
          'from solution import Hinh, HinhTron',
          '',
          '',
          'def test_ghi_de_mo_ta():',
          '    assert HinhTron(5).mo_ta() == "Hinh tron ban kinh 5"',
          '',
          '',
          'def test_van_la_con_cua_hinh():',
          '    assert issubclass(HinhTron, Hinh)',
          '',
          '',
          'def test_dung_lai_ket_qua_cua_cha():',
          '    # Doi mo_ta cua lop cha thi ket qua cua lop con phai doi theo.',
          '    goc = Hinh.mo_ta',
          '    try:',
          '        Hinh.mo_ta = lambda self: "Khoi"',
          '        assert HinhTron(2).mo_ta() == "Khoi tron ban kinh 2"',
          '    finally:',
          '        Hinh.mo_ta = goc',
        ].join('\n'),
      }),
    ],
  },

  'nc-b07-da-ke-thua-va-mro': {
    khoi: [
      challenge({
        slug: 'p-bs-nc-b07-thu-tu-mro',
        title: 'Thứ tự phân giải phương thức',
        statement: [
          'Viết bốn lớp:',
          '',
          '- `A` với `chao()` trả `"A"`',
          '- `B(A)` với `chao()` trả `"B"`',
          '- `C(A)` với `chao()` trả `"C"`',
          '- `D(B, C)` **không** định nghĩa lại `chao()`',
          '',
          'Thêm hàm `ten_mro()` trả về danh sách tên các lớp trong `D.__mro__`.',
        ].join('\n'),
        hints: ['MRO đi từ trái sang phải theo thứ tự khai báo lớp cha.', '`k.__name__` cho tên của một lớp.'],
        starterCode: [
          'class A:',
          '    def chao(self):',
          '        return "A"',
          '',
          '',
          '# Them B, C, D va ten_mro()',
        ].join('\n'),
        solutionCode: [
          'class A:',
          '    def chao(self):',
          '        return "A"',
          '',
          '',
          'class B(A):',
          '    def chao(self):',
          '        return "B"',
          '',
          '',
          'class C(A):',
          '    def chao(self):',
          '        return "C"',
          '',
          '',
          'class D(B, C):',
          '    pass',
          '',
          '',
          'def ten_mro():',
          '    return [k.__name__ for k in D.__mro__]',
        ].join('\n'),
        tier: 'NANG_CAO',
        judgeMode: 'UNIT_TEST',
        runtimeImage: 'PY_TEST',
        unitTestCode: [
          'from solution import A, B, C, D, ten_mro',
          '',
          '',
          'def test_D_lay_chao_cua_B():',
          '    assert D().chao() == "B"',
          '',
          '',
          'def test_mro_dung_thu_tu():',
          '    assert ten_mro() == ["D", "B", "C", "A", "object"]',
          '',
          '',
          'def test_quan_he_ke_thua():',
          '    assert issubclass(D, B)',
          '    assert issubclass(D, C)',
          '    assert issubclass(B, A)',
        ].join('\n'),
      }),
      challenge({
        slug: 'p-bs-nc-b07-mixin-cong-them',
        title: 'Mixin thêm một khả năng',
        statement: [
          'Viết `LuuDuocMixin` có `luu()` trả về `"Da luu <ten>"`,',
          'dựa vào thuộc tính `ten` của lớp cắm nó vào.',
          '',
          'Rồi viết `TaiLieu(LuuDuocMixin)` nhận `ten` trong `__init__`.',
        ].join('\n'),
        hints: ['Mixin không tự có `ten` — nó dùng `self.ten` của lớp kết hợp.'],
        starterCode: [
          'class LuuDuocMixin:',
          '    # Them luu()',
          '    pass',
          '',
          '',
          'class TaiLieu(LuuDuocMixin):',
          '    def __init__(self, ten):',
          '        self.ten = ten',
        ].join('\n'),
        solutionCode: [
          'class LuuDuocMixin:',
          '    def luu(self):',
          '        return f"Da luu {self.ten}"',
          '',
          '',
          'class TaiLieu(LuuDuocMixin):',
          '    def __init__(self, ten):',
          '        self.ten = ten',
        ].join('\n'),
        tier: 'THU_THACH',
        judgeMode: 'UNIT_TEST',
        runtimeImage: 'PY_TEST',
        unitTestCode: [
          'from solution import LuuDuocMixin, TaiLieu',
          '',
          '',
          'def test_luu_dung_ten():',
          '    assert TaiLieu("bao-cao.txt").luu() == "Da luu bao-cao.txt"',
          '',
          '',
          'def test_thuc_su_la_mixin():',
          '    assert issubclass(TaiLieu, LuuDuocMixin)',
          '',
          '',
          'def test_cam_duoc_vao_lop_khac():',
          '    class Anh(LuuDuocMixin):',
          '        def __init__(self, ten):',
          '            self.ten = ten',
          '',
          '    assert Anh("hoa.png").luu() == "Da luu hoa.png"',
        ].join('\n'),
      }),
    ],
  },

  'nc-b08-da-hinh-polymorphism': {
    khoi: [
      challenge({
        slug: 'p-bs-nc-b08-cung-mot-vong-lap',
        title: 'Một vòng lặp cho nhiều loại hình',
        statement: [
          'Viết `Vuong(canh)` và `ChuNhat(dai, rong)`, cả hai có `dien_tich()`.',
          '',
          'Thêm hàm `tong_dien_tich(ds)` nhận một danh sách hình bất kỳ',
          'và trả về tổng diện tích — **không được kiểm tra kiểu** bên trong.',
        ].join('\n'),
        hints: ['Vòng lặp chỉ gọi `h.dien_tich()`; đó chính là đa hình.'],
        starterCode: [
          'class Vuong:',
          '    def __init__(self, canh):',
          '        self.canh = canh',
          '',
          '',
          'class ChuNhat:',
          '    def __init__(self, dai, rong):',
          '        self.dai = dai',
          '        self.rong = rong',
          '',
          '',
          'def tong_dien_tich(ds):',
          '    pass',
        ].join('\n'),
        solutionCode: [
          'class Vuong:',
          '    def __init__(self, canh):',
          '        self.canh = canh',
          '',
          '    def dien_tich(self):',
          '        return self.canh * self.canh',
          '',
          '',
          'class ChuNhat:',
          '    def __init__(self, dai, rong):',
          '        self.dai = dai',
          '        self.rong = rong',
          '',
          '    def dien_tich(self):',
          '        return self.dai * self.rong',
          '',
          '',
          'def tong_dien_tich(ds):',
          '    tong = 0',
          '    for h in ds:',
          '        tong = tong + h.dien_tich()',
          '    return tong',
        ].join('\n'),
        tier: 'THU_THACH',
        judgeMode: 'UNIT_TEST',
        runtimeImage: 'PY_TEST',
        unitTestCode: [
          'from solution import ChuNhat, Vuong, tong_dien_tich',
          '',
          '',
          'def test_tung_hinh():',
          '    assert Vuong(3).dien_tich() == 9',
          '    assert ChuNhat(2, 5).dien_tich() == 10',
          '',
          '',
          'def test_tong_hon_hop():',
          '    assert tong_dien_tich([Vuong(3), ChuNhat(2, 5)]) == 19',
          '',
          '',
          'def test_danh_sach_rong():',
          '    assert tong_dien_tich([]) == 0',
          '',
          '',
          'def test_nhan_ca_lop_moi_khong_biet_truoc():',
          '    # Da hinh that su: mot lop hoan toan la van chay duoc.',
          '    class TamGiac:',
          '        def dien_tich(self):',
          '            return 6',
          '',
          '    assert tong_dien_tich([Vuong(2), TamGiac()]) == 10',
        ].join('\n'),
      }),
      challenge({
        slug: 'p-bs-nc-b08-tieng-keu-con-vat',
        title: 'Mỗi con vật một tiếng kêu',
        statement: [
          'Viết `DongVat` với `keu()` trả `"..."`, rồi `Cho(DongVat)` trả `"Gau gau"`',
          'và `Meo(DongVat)` trả `"Meo meo"`.',
          '',
          'Thêm `tat_ca_tieng_keu(ds)` trả về danh sách tiếng kêu của từng con.',
        ].join('\n'),
        hints: ['Lớp cha là phương án dự phòng cho loài chưa có lớp riêng.'],
        starterCode: [
          'class DongVat:',
          '    def keu(self):',
          '        return "..."',
          '',
          '',
          '# Them Cho, Meo va tat_ca_tieng_keu',
        ].join('\n'),
        solutionCode: [
          'class DongVat:',
          '    def keu(self):',
          '        return "..."',
          '',
          '',
          'class Cho(DongVat):',
          '    def keu(self):',
          '        return "Gau gau"',
          '',
          '',
          'class Meo(DongVat):',
          '    def keu(self):',
          '        return "Meo meo"',
          '',
          '',
          'def tat_ca_tieng_keu(ds):',
          '    return [con.keu() for con in ds]',
        ].join('\n'),
        tier: 'CO_BAN',
        judgeMode: 'UNIT_TEST',
        runtimeImage: 'PY_TEST',
        unitTestCode: [
          'from solution import Cho, DongVat, Meo, tat_ca_tieng_keu',
          '',
          '',
          'def test_tung_loai():',
          '    assert Cho().keu() == "Gau gau"',
          '    assert Meo().keu() == "Meo meo"',
          '    assert DongVat().keu() == "..."',
          '',
          '',
          'def test_ke_thua_dung():',
          '    assert issubclass(Cho, DongVat)',
          '    assert issubclass(Meo, DongVat)',
          '',
          '',
          'def test_danh_sach_hon_hop():',
          '    assert tat_ca_tieng_keu([Cho(), Meo(), DongVat()]) == [',
          '        "Gau gau",',
          '        "Meo meo",',
          '        "...",',
          '    ]',
        ].join('\n'),
      }),
    ],
  },

  'nc-b09-truu-tuong-abstraction-abc': {
    khoi: [
      challenge({
        slug: 'p-bs-nc-b09-abc-bat-buoc-cai-dat',
        title: 'Lớp trừu tượng bắt buộc cài đặt',
        statement: [
          'Dùng `ABC` và `@abstractmethod` viết `PhuongTien` có `di_chuyen()` trừu tượng.',
          '',
          'Rồi viết `XeDap(PhuongTien)` trả `"Dap xe"`.',
          '',
          'Tạo trực tiếp `PhuongTien()` phải ném `TypeError`.',
        ].join('\n'),
        hints: ['`from abc import ABC, abstractmethod`.', 'Python tự chặn việc tạo lớp còn phương thức trừu tượng.'],
        starterCode: [
          'from abc import ABC, abstractmethod',
          '',
          '',
          '# PhuongTien va XeDap',
        ].join('\n'),
        solutionCode: [
          'from abc import ABC, abstractmethod',
          '',
          '',
          'class PhuongTien(ABC):',
          '    @abstractmethod',
          '    def di_chuyen(self):',
          '        pass',
          '',
          '',
          'class XeDap(PhuongTien):',
          '    def di_chuyen(self):',
          '        return "Dap xe"',
        ].join('\n'),
        tier: 'NANG_CAO',
        judgeMode: 'UNIT_TEST',
        runtimeImage: 'PY_TEST',
        unitTestCode: [
          'import pytest',
          '',
          'from solution import PhuongTien, XeDap',
          '',
          '',
          'def test_lop_con_chay_duoc():',
          '    assert XeDap().di_chuyen() == "Dap xe"',
          '',
          '',
          'def test_khong_tao_duoc_lop_truu_tuong():',
          '    with pytest.raises(TypeError):',
          '        PhuongTien()',
          '',
          '',
          'def test_thieu_cai_dat_thi_cung_bi_chan():',
          '    class XeMay(PhuongTien):',
          '        pass',
          '',
          '    with pytest.raises(TypeError):',
          '        XeMay()',
        ].join('\n'),
      }),
      challenge({
        slug: 'p-bs-nc-b09-giao-dien-chung',
        title: 'Cùng một giao diện, hai cách tính',
        statement: [
          'Viết `Thue(ABC)` với `tinh(x)` trừu tượng.',
          '',
          '- `ThueCoDinh` — 10% của x',
          '- `ThueBac` — 5% nếu x ≤ 1000, ngược lại 15%',
          '',
          'Cả hai trả về **số nguyên**, làm tròn xuống.',
        ].join('\n'),
        hints: ['`x * 10 // 100` vừa tính vừa làm tròn xuống.'],
        starterCode: [
          'from abc import ABC, abstractmethod',
          '',
          '',
          '# Thue, ThueCoDinh, ThueBac',
        ].join('\n'),
        solutionCode: [
          'from abc import ABC, abstractmethod',
          '',
          '',
          'class Thue(ABC):',
          '    @abstractmethod',
          '    def tinh(self, x):',
          '        pass',
          '',
          '',
          'class ThueCoDinh(Thue):',
          '    def tinh(self, x):',
          '        return x * 10 // 100',
          '',
          '',
          'class ThueBac(Thue):',
          '    def tinh(self, x):',
          '        if x <= 1000:',
          '            return x * 5 // 100',
          '        return x * 15 // 100',
        ].join('\n'),
        tier: 'THU_THACH',
        judgeMode: 'UNIT_TEST',
        runtimeImage: 'PY_TEST',
        unitTestCode: [
          'from solution import Thue, ThueBac, ThueCoDinh',
          '',
          '',
          'def test_thue_co_dinh():',
          '    assert ThueCoDinh().tinh(2000) == 200',
          '',
          '',
          'def test_thue_bac_thap():',
          '    assert ThueBac().tinh(500) == 25',
          '',
          '',
          'def test_thue_bac_cao():',
          '    assert ThueBac().tinh(2000) == 300',
          '',
          '',
          'def test_dung_mot_giao_dien():',
          '    assert issubclass(ThueCoDinh, Thue)',
          '    assert issubclass(ThueBac, Thue)',
          '    for t in (ThueCoDinh(), ThueBac()):',
          '        assert isinstance(t.tinh(1000), int)',
        ].join('\n'),
      }),
    ],
  },

  'nc-b10-pep8-va-du-an-oop': {
    khoi: [
      challenge({
        slug: 'p-bs-nc-b10-doi-ten-theo-pep8',
        title: 'Đổi tên theo PEP8',
        statement: [
          'PEP8 đặt tên biến và hàm theo `snake_case`.',
          '',
          'Viết hàm `sang_snake(ten)` đổi một tên `camelCase` sang `snake_case`.',
          '',
          'Ví dụ `soLuongHocSinh` thành `so_luong_hoc_sinh`.',
        ].join('\n'),
        hints: ['Gặp chữ hoa thì chèn `_` rồi đổi sang chữ thường.'],
        starterCode: ['def sang_snake(ten):', '    pass'].join('\n'),
        solutionCode: [
          'def sang_snake(ten):',
          '    kq = ""',
          '    for c in ten:',
          '        if c.isupper():',
          '            kq = kq + "_" + c.lower()',
          '        else:',
          '            kq = kq + c',
          '    return kq',
        ].join('\n'),
        tier: 'THU_THACH',
        judgeMode: 'UNIT_TEST',
        runtimeImage: 'PY_TEST',
        unitTestCode: [
          'from solution import sang_snake',
          '',
          '',
          'def test_nhieu_tu():',
          '    assert sang_snake("soLuongHocSinh") == "so_luong_hoc_sinh"',
          '',
          '',
          'def test_hai_tu():',
          '    assert sang_snake("tinhTong") == "tinh_tong"',
          '',
          '',
          'def test_mot_chu():',
          '    assert sang_snake("x") == "x"',
          '',
          '',
          'def test_da_dung_chuan_thi_giu_nguyen():',
          '    assert sang_snake("da_dung_roi") == "da_dung_roi"',
        ].join('\n'),
      }),
      challenge({
        slug: 'p-bs-nc-b10-quan-ly-thu-vien',
        title: 'Mô hình hoá một thư viện nhỏ',
        statement: [
          'Viết class `ThuVien` với:',
          '',
          '- `them(ten)` — thêm một quyển sách',
          '- `muon(ten)` — bỏ một quyển ra, trả `True` nếu mượn được, `False` nếu không có',
          '- `con_lai()` — số sách còn trong thư viện',
          '',
          'Đặt tên theo PEP8 và giữ danh sách sách trong thuộc tính riêng.',
        ].join('\n'),
        hints: ['`list.remove` bỏ phần tử đầu tiên khớp.', 'Kiểm tra `in` trước khi remove để không ném lỗi.'],
        starterCode: [
          'class ThuVien:',
          '    def __init__(self):',
          '        self._sach = []',
          '',
          '    # them, muon, con_lai',
        ].join('\n'),
        solutionCode: [
          'class ThuVien:',
          '    def __init__(self):',
          '        self._sach = []',
          '',
          '    def them(self, ten):',
          '        self._sach.append(ten)',
          '',
          '    def muon(self, ten):',
          '        if ten in self._sach:',
          '            self._sach.remove(ten)',
          '            return True',
          '        return False',
          '',
          '    def con_lai(self):',
          '        return len(self._sach)',
        ].join('\n'),
        tier: 'THU_THACH',
        judgeMode: 'UNIT_TEST',
        runtimeImage: 'PY_TEST',
        unitTestCode: [
          'from solution import ThuVien',
          '',
          '',
          'def test_them_va_dem():',
          '    tv = ThuVien()',
          '    tv.them("DeMen")',
          '    tv.them("Doraemon")',
          '    assert tv.con_lai() == 2',
          '',
          '',
          'def test_muon_duoc():',
          '    tv = ThuVien()',
          '    tv.them("DeMen")',
          '    assert tv.muon("DeMen") is True',
          '    assert tv.con_lai() == 0',
          '',
          '',
          'def test_muon_sach_khong_co():',
          '    tv = ThuVien()',
          '    assert tv.muon("Conan") is False',
          '    assert tv.con_lai() == 0',
          '',
          '',
          'def test_hai_ban_sao_cung_ten():',
          '    tv = ThuVien()',
          '    tv.them("A")',
          '    tv.them("A")',
          '    assert tv.muon("A") is True',
          '    assert tv.con_lai() == 1',
        ].join('\n'),
      }),
    ],
  },
};
