/**
 * Expansion pack — Lập trình game với Pygame, sessions 16–30.
 *
 * Same rule as part 1: the logic is extracted and judged on stdin/stdout, never
 * `import pygame`. See the header of ./pygame-1.ts.
 *
 * Sessions 27–30 are polish, packaging and presentation. The exercises there
 * check the things that actually break a demo in front of a class — a frame
 * budget blown, a save file that does not round-trip, an asset list with a
 * missing file — rather than inventing new gameplay for sessions whose point is
 * finishing what the student already has.
 */
import { challenge, hidden, sample } from '../../builders.ts';

import type { BoSungKhoaHoc } from './ap-dung.ts';

export const boSungPygame2: BoSungKhoaHoc = {
  'pg-b16-du-an-pong-hoan-chinh': {
    khoi: [
      challenge({
        slug: 'p-bs-pg-b16-pong-ai-bat-duoc',
        title: 'Paddle có đỡ kịp không',
        statement: [
          'Bóng ở `(bx, by)` bay với vận tốc `(vx, vy)`. Paddle nằm ở cột `px`,',
          'trải từ `py` tới `py + h - 1`.',
          '',
          'Đọc `bx by vx vy` rồi `px py h`. Mô phỏng từng khung cho tới khi `bx` **đạt hoặc vượt** `px`.',
          'In ra `Do duoc` nếu lúc đó `by` nằm trong khoảng paddle, ngược lại `Truot`.',
        ].join('\n'),
        hints: ['Chỉ cần lặp cho tới khi bóng tới cột paddle.', 'So sánh by với py và py + h - 1.'],
        starterCode: [
          'bx, by, vx, vy = [int(v) for v in input().split()]',
          'px, py, h = [int(v) for v in input().split()]',
          '',
          '# Mô phỏng tới khi bóng tới paddle',
        ].join('\n'),
        solutionCode: [
          'bx, by, vx, vy = [int(v) for v in input().split()]',
          'px, py, h = [int(v) for v in input().split()]',
          'while bx < px:',
          '    bx = bx + vx',
          '    by = by + vy',
          'if py <= by <= py + h - 1:',
          '    print("Do duoc")',
          'else:',
          '    print("Truot")',
        ].join('\n'),
        tier: 'THU_THACH',
        judgeMode: 'IO_MATCH',
        tests: [
          sample('0 50 10 0\n100 40 20\n', 'Do duoc\n', 'Bóng bay ngang tới đúng giữa paddle.'),
          sample('0 0 10 10\n100 40 20\n', 'Truot\n', 'Bóng xuống quá nhanh: tới cột paddle thì đã ở y = 100, dưới mép dưới.'),
          hidden('0 10 5 0\n50 0 5\n', 'Truot\n', 25),
          hidden('0 10 5 0\n50 10 1\n', 'Do duoc\n', 25),
        ],
      }),
      challenge({
        slug: 'p-bs-pg-b16-pong-ty-so',
        title: 'Ai thắng ván Pong',
        statement: [
          'Dòng đầu là số lượng `n`. `n` dòng sau, mỗi dòng là `TRAI` hoặc `PHAI` —',
          'bên ghi điểm ở pha đó.',
          '',
          'Ván đấu kết thúc ngay khi một bên đạt **11 điểm**. In ra `<tên bên thắng> <điểm bên kia>`.',
          'Nếu chưa bên nào tới 11, in ra `Chua ket thuc`.',
        ].join('\n'),
        hints: ['Dừng đếm ngay khi một bên tới 11.'],
        starterCode: ['n = int(input())', 'trai = 0', 'phai = 0', '', '# Đếm điểm'].join('\n'),
        solutionCode: [
          'n = int(input())',
          'trai = 0',
          'phai = 0',
          'thang = ""',
          'for _ in range(n):',
          '    ben = input()',
          '    if thang != "":',
          '        continue',
          '    if ben == "TRAI":',
          '        trai = trai + 1',
          '    else:',
          '        phai = phai + 1',
          '    if trai == 11:',
          '        thang = "TRAI"',
          '    elif phai == 11:',
          '        thang = "PHAI"',
          'if thang == "TRAI":',
          '    print(f"TRAI {phai}")',
          'elif thang == "PHAI":',
          '    print(f"PHAI {trai}")',
          'else:',
          '    print("Chua ket thuc")',
        ].join('\n'),
        tier: 'THU_THACH',
        judgeMode: 'IO_MATCH',
        tests: [
          sample(
            '12\nTRAI\nTRAI\nTRAI\nTRAI\nTRAI\nTRAI\nTRAI\nTRAI\nTRAI\nTRAI\nTRAI\nPHAI\n',
            'TRAI 0\n',
            'Bên trái đạt 11 trước, pha sau không tính nữa.',
          ),
          sample('3\nTRAI\nPHAI\nTRAI\n', 'Chua ket thuc\n', 'Chưa ai tới 11.'),
          hidden(
            '11\nPHAI\nPHAI\nPHAI\nPHAI\nPHAI\nPHAI\nPHAI\nPHAI\nPHAI\nPHAI\nPHAI\n',
            'PHAI 0\n',
            30,
          ),
        ],
      }),
    ],
  },

  'pg-b17-tile-map-va-man-choi': {
    khoi: [
      challenge({
        slug: 'p-bs-pg-b17-dem-o-tuong',
        title: 'Đếm ô tường trong bản đồ',
        statement: [
          'Đọc **số hàng** `h`, rồi `h` dòng bản đồ gồm các ký tự `.` (trống) và `#` (tường).',
          '',
          'In ra số ô tường.',
        ].join('\n'),
        hints: ['`dong.count("#")` đếm ký tự trong một chuỗi.'],
        starterCode: ['h = int(input())', 'tong = 0', '', '# Đếm ô tường'].join('\n'),
        solutionCode: [
          'h = int(input())',
          'tong = 0',
          'for _ in range(h):',
          '    tong = tong + input().count("#")',
          'print(tong)',
        ].join('\n'),
        tier: 'CO_BAN',
        judgeMode: 'IO_MATCH',
        tests: [
          sample('3\n#..#\n....\n####\n', '6\n', 'Hai ở hàng đầu, bốn ở hàng cuối.'),
          hidden('1\n....\n', '0\n', 25),
          hidden('2\n##\n##\n', '4\n', 25),
        ],
      }),
      challenge({
        slug: 'p-bs-pg-b17-tim-diem-xuat-phat',
        title: 'Tìm điểm xuất phát trên bản đồ',
        statement: [
          'Đọc **số hàng** `h`, rồi `h` dòng bản đồ. Ký tự `S` là điểm xuất phát.',
          '',
          'In ra toạ độ của `S` theo mẫu `<cột> <hàng>`, đếm từ 0.',
          'Nếu bản đồ không có `S`, in ra `Khong tim thay`.',
        ].join('\n'),
        hints: ['`dong.find("S")` trả về -1 khi không có.'],
        starterCode: ['h = int(input())', '', '# Tìm S'].join('\n'),
        solutionCode: [
          'h = int(input())',
          'vt = ""',
          'for y in range(h):',
          '    dong = input()',
          '    x = dong.find("S")',
          '    if x != -1 and vt == "":',
          '        vt = f"{x} {y}"',
          'if vt == "":',
          '    print("Khong tim thay")',
          'else:',
          '    print(vt)',
        ].join('\n'),
        tier: 'THU_THACH',
        judgeMode: 'IO_MATCH',
        tests: [
          sample('3\n....\n..S.\n....\n', '2 1\n', 'S ở cột 2, hàng 1.'),
          sample('2\n....\n....\n', 'Khong tim thay\n', 'Bản đồ không có điểm xuất phát.'),
          hidden('1\nS...\n', '0 0\n', 25),
        ],
      }),
    ],
  },

  'pg-b18-nhan-vat-platformer': {
    khoi: [
      challenge({
        slug: 'p-bs-pg-b18-dung-tren-nen',
        title: 'Nhân vật đứng trên nền',
        statement: [
          'Nhân vật cao `h`, đang ở độ cao `y` (toạ độ đỉnh đầu), rơi `v` mỗi khung.',
          'Mặt nền ở `nen`.',
          '',
          'Đọc `y h v nen` rồi số khung `n`. In ra `y` sau n khung, biết chân nhân vật',
          '(`y + h`) **không được lún xuống dưới nền**.',
        ].join('\n'),
        hints: ['Khi y + h vượt nen thì đặt y = nen - h.'],
        starterCode: [
          'y, h, v, nen = [int(t) for t in input().split()]',
          'n = int(input())',
          '',
          '# Rơi rồi chặn ở nền',
        ].join('\n'),
        solutionCode: [
          'y, h, v, nen = [int(t) for t in input().split()]',
          'n = int(input())',
          'for _ in range(n):',
          '    y = y + v',
          '    if y + h > nen:',
          '        y = nen - h',
          'print(y)',
        ].join('\n'),
        tier: 'THU_THACH',
        judgeMode: 'IO_MATCH',
        tests: [
          sample('0 20 30 100\n5\n', '80\n', 'Chân chạm nền nên đỉnh đầu dừng ở 80.'),
          hidden('0 10 5 100\n2\n', '10\n', 25),
          hidden('50 50 100 100\n1\n', '50\n', 25),
        ],
      }),
      challenge({
        slug: 'p-bs-pg-b18-nhay-hai-lan',
        title: 'Nhảy đúp',
        statement: [
          'Nhân vật được nhảy tối đa **2 lần** trước khi chạm đất lại.',
          '',
          'Đọc số lượng `n` rồi `n` lệnh: `JUMP` hoặc `LAND`.',
          '`LAND` đặt lại bộ đếm về 0. `JUMP` chỉ được chấp nhận khi đã nhảy dưới 2 lần.',
          '',
          'In ra tổng số cú nhảy **được chấp nhận**.',
        ].join('\n'),
        hints: ['Một biến đếm số lần nhảy kể từ lần chạm đất gần nhất.'],
        starterCode: ['n = int(input())', 'dem = 0', 'tong = 0', '', '# Xử lý lệnh'].join('\n'),
        solutionCode: [
          'n = int(input())',
          'dem = 0',
          'tong = 0',
          'for _ in range(n):',
          '    lenh = input()',
          '    if lenh == "LAND":',
          '        dem = 0',
          '    elif lenh == "JUMP" and dem < 2:',
          '        dem = dem + 1',
          '        tong = tong + 1',
          'print(tong)',
        ].join('\n'),
        tier: 'THU_THACH',
        judgeMode: 'IO_MATCH',
        tests: [
          sample('4\nJUMP\nJUMP\nJUMP\nLAND\n', '2\n', 'Cú thứ ba bị từ chối vì chưa chạm đất.'),
          hidden('6\nJUMP\nJUMP\nLAND\nJUMP\nJUMP\nJUMP\n', '4\n', 25),
          hidden('2\nLAND\nLAND\n', '0\n', 25),
        ],
      }),
    ],
  },

  'pg-b19-camera-va-cuon-man-hinh': {
    khoi: [
      challenge({
        slug: 'p-bs-pg-b19-camera-bam-nhan-vat',
        title: 'Camera bám nhân vật',
        statement: [
          'Đọc **rộng màn hình**, **rộng bản đồ** và **x của nhân vật**.',
          '',
          'In ra toạ độ x của camera sao cho nhân vật nằm giữa màn hình,',
          'nhưng camera **không được ra ngoài bản đồ**.',
        ].join('\n'),
        hints: ['Camera lý tưởng = x nhân vật − nửa màn hình.', 'Kẹp trong khoảng 0 tới rộng bản đồ − rộng màn hình.'],
        starterCode: [
          'man = int(input())',
          'ban_do = int(input())',
          'x = int(input())',
          '',
          '# Tính camera',
        ].join('\n'),
        solutionCode: [
          'man = int(input())',
          'ban_do = int(input())',
          'x = int(input())',
          'cam = x - man // 2',
          'cam = max(0, min(ban_do - man, cam))',
          'print(cam)',
        ].join('\n'),
        tier: 'THU_THACH',
        judgeMode: 'IO_MATCH',
        tests: [
          sample('800\n2000\n1000\n', '600\n', 'Nhân vật ở giữa nên camera lùi lại 400.'),
          sample('800\n2000\n100\n', '0\n', 'Gần mép trái nên camera dừng ở 0.'),
          hidden('800\n2000\n1900\n', '1200\n', 25),
          hidden('800\n800\n400\n', '0\n', 25),
        ],
      }),
      challenge({
        slug: 'p-bs-pg-b19-toa-do-man-hinh',
        title: 'Đổi toạ độ thế giới sang màn hình',
        statement: [
          'Đọc **camera x**, rồi số lượng `n`, rồi `n` toạ độ x của các vật trong thế giới.',
          '',
          'In ra toạ độ trên màn hình của từng vật, cách nhau một dấu cách.',
          '',
          'Toạ độ màn hình = toạ độ thế giới − camera.',
        ].join('\n'),
        hints: ['Cùng một phép trừ áp cho mọi vật.'],
        starterCode: ['cam = int(input())', 'n = int(input())', '', '# Đổi toạ độ'].join('\n'),
        solutionCode: [
          'cam = int(input())',
          'n = int(input())',
          'kq = []',
          'for _ in range(n):',
          '    kq.append(str(int(input()) - cam))',
          'print(" ".join(kq))',
        ].join('\n'),
        tier: 'CO_BAN',
        judgeMode: 'IO_MATCH',
        tests: [
          sample('100\n3\n100\n150\n80\n', '0 50 -20\n', 'Vật ở 80 nằm bên trái màn hình nên toạ độ âm.'),
          hidden('0\n2\n5\n10\n', '5 10\n', 25),
          hidden('500\n1\n500\n', '0\n', 25),
        ],
      }),
    ],
  },

  'pg-b20-ai-ke-dich-co-ban': {
    khoi: [
      challenge({
        slug: 'p-bs-pg-b20-duoi-theo-nguoi-choi',
        title: 'Kẻ địch đuổi theo người chơi',
        statement: [
          'Kẻ địch ở `e`, người chơi ở `p`, kẻ địch đi `s` đơn vị mỗi khung về phía người chơi.',
          '',
          'Đọc `e p s n`. In ra vị trí kẻ địch sau n khung.',
          'Nếu bước đi sẽ **vượt qua** người chơi thì dừng đúng tại vị trí người chơi.',
        ].join('\n'),
        hints: ['So sánh khoảng cách còn lại với bước đi.'],
        starterCode: [
          'e, p, s, n = [int(v) for v in input().split()]',
          '',
          '# Đuổi theo',
        ].join('\n'),
        solutionCode: [
          'e, p, s, n = [int(v) for v in input().split()]',
          'for _ in range(n):',
          '    if abs(p - e) <= s:',
          '        e = p',
          '    elif e < p:',
          '        e = e + s',
          '    else:',
          '        e = e - s',
          'print(e)',
        ].join('\n'),
        tier: 'THU_THACH',
        judgeMode: 'IO_MATCH',
        tests: [
          sample('0 100 30 3\n', '90\n', 'Ba bước 30 đưa kẻ địch tới 90.'),
          sample('0 100 30 4\n', '100\n', 'Bước thứ tư chỉ còn 10 nên dừng đúng ở người chơi.'),
          hidden('100 0 40 2\n', '20\n', 25),
          hidden('50 50 10 5\n', '50\n', 25),
        ],
      }),
      challenge({
        slug: 'p-bs-pg-b20-tuan-tra-qua-lai',
        title: 'Kẻ địch tuần tra qua lại',
        statement: [
          'Kẻ địch tuần tra giữa `trai` và `phai`, bắt đầu ở `x` đi về phía phải với bước `s`.',
          '',
          'Đọc `trai phai x s n`. In ra vị trí sau n khung.',
          'Khi tới hoặc vượt biên, kẹp về đúng biên và đổi hướng.',
        ].join('\n'),
        hints: ['Giữ một biến hướng và đảo dấu khi chạm biên.'],
        starterCode: [
          'trai, phai, x, s, n = [int(v) for v in input().split()]',
          '',
          '# Tuần tra',
        ].join('\n'),
        solutionCode: [
          'trai, phai, x, s, n = [int(v) for v in input().split()]',
          'huong = 1',
          'for _ in range(n):',
          '    x = x + s * huong',
          '    if x >= phai:',
          '        x = phai',
          '        huong = -1',
          '    elif x <= trai:',
          '        x = trai',
          '        huong = 1',
          'print(x)',
        ].join('\n'),
        tier: 'THU_THACH',
        judgeMode: 'IO_MATCH',
        tests: [
          sample('0 100 90 20 1\n', '100\n', 'Chạm biên phải nên dừng đúng ở 100.'),
          hidden('0 100 90 20 2\n', '80\n', 25),
          hidden('0 50 0 10 5\n', '50\n', 25),
        ],
      }),
    ],
  },

  'pg-b21-ai-nang-cao-may-trang-thai': {
    khoi: [
      challenge({
        slug: 'p-bs-pg-b21-ai-ba-trang-thai',
        title: 'Máy trạng thái của kẻ địch',
        statement: [
          'Kẻ địch có ba trạng thái theo **khoảng cách** tới người chơi:',
          '',
          '- lớn hơn 100: `TUAN TRA`',
          '- từ 30 đến 100: `DUOI`',
          '- nhỏ hơn 30: `TAN CONG`',
          '',
          'Đọc số lượng `n` rồi `n` khoảng cách. In trạng thái của từng khung, mỗi dòng một trạng thái.',
        ].join('\n'),
        hints: ['Xét từ mốc lớn xuống mốc nhỏ.'],
        starterCode: ['n = int(input())', '', '# In trạng thái từng khung'].join('\n'),
        solutionCode: [
          'n = int(input())',
          'for _ in range(n):',
          '    d = int(input())',
          '    if d > 100:',
          '        print("TUAN TRA")',
          '    elif d >= 30:',
          '        print("DUOI")',
          '    else:',
          '        print("TAN CONG")',
        ].join('\n'),
        tier: 'CO_BAN',
        judgeMode: 'IO_MATCH',
        tests: [
          sample('3\n150\n50\n10\n', 'TUAN TRA\nDUOI\nTAN CONG\n', 'Mỗi khoảng cách rơi vào một trạng thái.'),
          hidden('2\n100\n30\n', 'DUOI\nDUOI\n', 25),
          hidden('1\n101\n', 'TUAN TRA\n', 25),
        ],
      }),
      challenge({
        slug: 'p-bs-pg-b21-dem-lan-doi-trang-thai',
        title: 'Đếm số lần đổi trạng thái',
        statement: [
          'Cùng luật trạng thái như bài trước.',
          '',
          'Đọc số lượng `n` rồi `n` khoảng cách. In ra **số lần trạng thái thay đổi**',
          'so với khung ngay trước đó. Khung đầu tiên không tính là một lần đổi.',
        ].join('\n'),
        hints: ['Nhớ trạng thái của khung trước để so sánh.'],
        starterCode: ['n = int(input())', '', '# Đếm số lần đổi'].join('\n'),
        solutionCode: [
          'n = int(input())',
          'truoc = ""',
          'doi = 0',
          'for _ in range(n):',
          '    d = int(input())',
          '    if d > 100:',
          '        tt = "TUAN TRA"',
          '    elif d >= 30:',
          '        tt = "DUOI"',
          '    else:',
          '        tt = "TAN CONG"',
          '    if truoc != "" and tt != truoc:',
          '        doi = doi + 1',
          '    truoc = tt',
          'print(doi)',
        ].join('\n'),
        tier: 'THU_THACH',
        judgeMode: 'IO_MATCH',
        tests: [
          sample('4\n150\n50\n40\n10\n', '2\n', 'Đổi ở khung 2 và khung 4.'),
          hidden('3\n10\n10\n10\n', '0\n', 25),
          hidden('2\n150\n10\n', '1\n', 25),
        ],
      }),
    ],
  },

  'pg-b22-power-up-vat-pham-kho-do': {
    khoi: [
      challenge({
        slug: 'p-bs-pg-b22-kho-do-co-han',
        title: 'Kho đồ có sức chứa',
        statement: [
          'Kho chứa tối đa `k` món.',
          '',
          'Đọc `k`, rồi số lượng `n`, rồi `n` tên vật phẩm nhặt được theo thứ tự.',
          'Khi kho đầy thì bỏ qua vật phẩm mới.',
          '',
          'In ra các món trong kho, mỗi món một dòng, theo thứ tự nhặt.',
        ].join('\n'),
        hints: ['Kiểm tra `len(kho) < k` trước khi thêm.'],
        starterCode: ['k = int(input())', 'n = int(input())', 'kho = []', '', '# Nhặt đồ'].join('\n'),
        solutionCode: [
          'k = int(input())',
          'n = int(input())',
          'kho = []',
          'for _ in range(n):',
          '    mon = input()',
          '    if len(kho) < k:',
          '        kho.append(mon)',
          'for mon in kho:',
          '    print(mon)',
        ].join('\n'),
        tier: 'CO_BAN',
        judgeMode: 'IO_MATCH',
        tests: [
          sample('2\n3\nkiem\nkhien\nnon\n', 'kiem\nkhien\n', 'Kho đầy sau hai món nên bỏ qua món thứ ba.'),
          hidden('5\n2\na\nb\n', 'a\nb\n', 25),
          hidden('1\n3\nx\ny\nz\n', 'x\n', 25),
        ],
      }),
      challenge({
        slug: 'p-bs-pg-b22-power-up-het-han',
        title: 'Power-up còn hiệu lực bao lâu',
        statement: [
          'Power-up kéo dài `t` khung kể từ lúc nhặt.',
          '',
          'Đọc `t`, rồi số lượng `n`, rồi `n` dòng: `NHAT` hoặc `TICK`.',
          '`NHAT` đặt lại thời gian còn lại về `t`. `TICK` giảm đi 1 (không xuống dưới 0).',
          '',
          'In ra thời gian còn lại ở cuối.',
        ].join('\n'),
        hints: ['Nhặt lại khi đang còn hiệu lực thì đặt lại về đầy, không cộng dồn.'],
        starterCode: ['t = int(input())', 'n = int(input())', 'con = 0', '', '# Theo dõi hiệu lực'].join('\n'),
        solutionCode: [
          't = int(input())',
          'n = int(input())',
          'con = 0',
          'for _ in range(n):',
          '    lenh = input()',
          '    if lenh == "NHAT":',
          '        con = t',
          '    elif con > 0:',
          '        con = con - 1',
          'print(con)',
        ].join('\n'),
        tier: 'THU_THACH',
        judgeMode: 'IO_MATCH',
        tests: [
          sample('5\n4\nNHAT\nTICK\nTICK\nTICK\n', '2\n', 'Nhặt được 5, tick ba lần còn 2.'),
          sample('5\n3\nTICK\nTICK\nTICK\n', '0\n', 'Chưa nhặt gì nên vẫn là 0.'),
          hidden('3\n5\nNHAT\nTICK\nNHAT\nTICK\nTICK\n', '1\n', 25),
        ],
      }),
    ],
  },

  'pg-b23-nhieu-man-choi-va-luu-tien-do': {
    khoi: [
      challenge({
        slug: 'p-bs-pg-b23-mo-khoa-man',
        title: 'Màn nào đã mở khoá',
        statement: [
          'Một màn được mở khoá khi màn **ngay trước** đã hoàn thành. Màn 1 luôn mở.',
          '',
          'Đọc số màn `m`, rồi một dòng gồm `m` số 0 hoặc 1 — 1 nghĩa là đã hoàn thành.',
          '',
          'In ra số hiệu **màn cao nhất đang mở khoá**.',
        ].join('\n'),
        hints: ['Đi từ màn 1, dừng lại ở màn đầu tiên chưa hoàn thành.'],
        starterCode: [
          'm = int(input())',
          'xong = [int(v) for v in input().split()]',
          '',
          '# Tìm màn mở khoá cao nhất',
        ].join('\n'),
        solutionCode: [
          'm = int(input())',
          'xong = [int(v) for v in input().split()]',
          'mo = 1',
          'for i in range(m):',
          '    if xong[i] == 1:',
          '        mo = i + 2',
          '    else:',
          '        break',
          'if mo > m:',
          '    mo = m',
          'print(mo)',
        ].join('\n'),
        tier: 'THU_THACH',
        judgeMode: 'IO_MATCH',
        tests: [
          sample('5\n1 1 0 0 0\n', '3\n', 'Xong hai màn nên màn 3 đang mở.'),
          sample('3\n1 1 1\n', '3\n', 'Xong hết thì màn cao nhất vẫn là màn 3.'),
          hidden('4\n0 0 0 0\n', '1\n', 25),
          hidden('4\n1 0 1 1\n', '2\n', 25),
        ],
      }),
      challenge({
        slug: 'p-bs-pg-b23-luu-va-doc-tien-do',
        title: 'Lưu tiến độ rồi đọc lại',
        statement: [
          'Đọc **tên người chơi**, **màn** và **điểm**, mỗi giá trị một dòng.',
          '',
          'Ghi một dòng `ten|man|diem` vào tệp `save.txt`, rồi **đọc lại tệp**',
          'và in ra theo mẫu `<ten> - man <man> - <diem> diem`.',
        ].join('\n'),
        hints: ['`"|".join(...)` để ghép, `.split("|")` để tách ra lại.'],
        starterCode: [
          'ten = input()',
          'man = input()',
          'diem = input()',
          '',
          '# Ghi rồi đọc lại',
        ].join('\n'),
        solutionCode: [
          'ten = input()',
          'man = input()',
          'diem = input()',
          'with open("save.txt", "w", encoding="utf-8") as f:',
          '    f.write("|".join([ten, man, diem]))',
          'with open("save.txt", "r", encoding="utf-8") as f:',
          '    a, b, c = f.read().split("|")',
          'print(f"{a} - man {b} - {c} diem")',
        ].join('\n'),
        tier: 'THU_THACH',
        judgeMode: 'IO_MATCH',
        tests: [
          sample('Lan\n3\n1200\n', 'Lan - man 3 - 1200 diem\n', 'Ghi ra rồi đọc lại đúng ba phần.'),
          hidden('Minh\n1\n0\n', 'Minh - man 1 - 0 diem\n', 30),
        ],
      }),
    ],
  },

  'pg-b24-tong-hop-1-platformer': {
    khoi: [
      challenge({
        slug: 'p-bs-pg-b24-thu-thap-xu',
        title: 'Nhặt xu dọc đường',
        statement: [
          'Đọc một dòng bản đồ gồm `.` (trống), `o` (xu) và `#` (tường).',
          'Nhân vật đi từ trái sang phải, **dừng lại khi gặp tường**.',
          '',
          'In ra số xu nhặt được trước khi dừng.',
        ].join('\n'),
        hints: ['Duyệt từng ký tự, `break` khi gặp tường.'],
        starterCode: ['ban_do = input()', 'xu = 0', '', '# Đi và nhặt'].join('\n'),
        solutionCode: [
          'ban_do = input()',
          'xu = 0',
          'for c in ban_do:',
          '    if c == "#":',
          '        break',
          '    if c == "o":',
          '        xu = xu + 1',
          'print(xu)',
        ].join('\n'),
        tier: 'CO_BAN',
        judgeMode: 'IO_MATCH',
        tests: [
          sample('..o.o#oo\n', '2\n', 'Hai xu trước bức tường; hai xu sau không lấy được.'),
          hidden('#ooo\n', '0\n', 25),
          hidden('oooo\n', '4\n', 25),
        ],
      }),
      challenge({
        slug: 'p-bs-pg-b24-tinh-diem-man-choi',
        title: 'Tính điểm cuối màn',
        statement: [
          'Đọc **số xu**, **thời gian còn lại** và **số mạng còn lại**.',
          '',
          'Điểm = xu × 10 + thời gian × 5 + mạng × 100.',
          '',
          'In ra tổng điểm.',
        ].join('\n'),
        hints: ['Chỉ là một phép tính, nhưng đọc kỹ hệ số của từng phần.'],
        starterCode: [
          'xu = int(input())',
          'tg = int(input())',
          'mang = int(input())',
          '',
          '# Tính điểm',
        ].join('\n'),
        solutionCode: [
          'xu = int(input())',
          'tg = int(input())',
          'mang = int(input())',
          'print(xu * 10 + tg * 5 + mang * 100)',
        ].join('\n'),
        tier: 'CO_BAN',
        judgeMode: 'IO_MATCH',
        tests: [
          sample('10\n20\n3\n', '500\n', '100 + 100 + 300.'),
          hidden('0\n0\n0\n', '0\n', 25),
          hidden('5\n1\n1\n', '155\n', 25),
        ],
      }),
    ],
  },

  'pg-b25-tong-hop-2-space-invaders': {
    khoi: [
      challenge({
        slug: 'p-bs-pg-b25-ban-trung-dich',
        title: 'Đạn có trúng hàng địch không',
        statement: [
          'Đọc **x của viên đạn**, rồi số lượng `n`, rồi `n` toạ độ `x w` của từng kẻ địch',
          '(x là mép trái, w là chiều rộng).',
          '',
          'In ra **chỉ số** (đếm từ 0) của kẻ địch đầu tiên bị trúng, hoặc `Truot`.',
          'Trúng khi `x <= dan < x + w`.',
        ].join('\n'),
        hints: ['Duyệt theo thứ tự và dừng ở kẻ địch đầu tiên trúng.'],
        starterCode: ['dan = int(input())', 'n = int(input())', '', '# Kiểm tra từng kẻ địch'].join('\n'),
        solutionCode: [
          'dan = int(input())',
          'n = int(input())',
          'kq = "Truot"',
          'for i in range(n):',
          '    x, w = [int(v) for v in input().split()]',
          '    if kq == "Truot" and x <= dan < x + w:',
          '        kq = str(i)',
          'print(kq)',
        ].join('\n'),
        tier: 'THU_THACH',
        judgeMode: 'IO_MATCH',
        tests: [
          sample('50\n3\n0 20\n40 20\n80 20\n', '1\n', 'Đạn ở 50 nằm trong kẻ địch thứ hai.'),
          sample('30\n2\n0 20\n40 20\n', 'Truot\n', 'Đạn lọt vào khe giữa hai kẻ địch.'),
          hidden('0\n1\n0 1\n', '0\n', 25),
          hidden('20\n1\n0 20\n', 'Truot\n', 25),
        ],
      }),
      challenge({
        slug: 'p-bs-pg-b25-han-ban-lien-tiep',
        title: 'Giới hạn tốc độ bắn',
        statement: [
          'Súng cần nghỉ `d` khung giữa hai phát bắn.',
          '',
          'Đọc `d`, rồi số lượng `n`, rồi `n` số khung mà người chơi bấm bắn (tăng dần).',
          '',
          'In ra số phát **thực sự bắn ra**. Phát đầu tiên luôn được bắn.',
        ].join('\n'),
        hints: ['Nhớ khung của phát bắn gần nhất.', 'Bắn được khi khung hiện tại − khung trước ≥ d.'],
        starterCode: ['d = int(input())', 'n = int(input())', '', '# Đếm số phát bắn'].join('\n'),
        solutionCode: [
          'd = int(input())',
          'n = int(input())',
          'lan_cuoi = -1000000',
          'ban = 0',
          'for _ in range(n):',
          '    k = int(input())',
          '    if k - lan_cuoi >= d:',
          '        ban = ban + 1',
          '        lan_cuoi = k',
          'print(ban)',
        ].join('\n'),
        tier: 'THU_THACH',
        judgeMode: 'IO_MATCH',
        tests: [
          sample('5\n4\n0\n2\n5\n11\n', '3\n', 'Phát ở khung 2 bị chặn vì mới nghỉ 2 khung.'),
          hidden('1\n3\n0\n1\n2\n', '3\n', 25),
          hidden('10\n3\n0\n1\n2\n', '1\n', 25),
        ],
      }),
    ],
  },

  'pg-b26-tong-hop-3-maze-quiz-gui': {
    khoi: [
      challenge({
        slug: 'p-bs-pg-b26-di-trong-me-cung',
        title: 'Đi trong mê cung',
        statement: [
          'Đọc **số hàng** `h`, rồi `h` dòng mê cung (`.` trống, `#` tường).',
          'Dòng tiếp theo là toạ độ xuất phát `x y`, dòng cuối là chuỗi lệnh `LRUD`.',
          '',
          'Đi từng bước; bước nào đâm vào tường hoặc ra ngoài mê cung thì **bỏ qua**.',
          '',
          'In ra vị trí cuối theo mẫu `<x> <y>`.',
        ].join('\n'),
        hints: ['Tính vị trí thử trước, chỉ chấp nhận nếu hợp lệ.', 'Nhớ kiểm tra cả biên lẫn ký tự tường.'],
        starterCode: ['h = int(input())', 'me = [input() for _ in range(h)]', '', '# Đi từng bước'].join('\n'),
        solutionCode: [
          'h = int(input())',
          'me = [input() for _ in range(h)]',
          'x, y = [int(v) for v in input().split()]',
          'lenh = input()',
          'for p in lenh:',
          '    nx = x',
          '    ny = y',
          '    if p == "L":',
          '        nx = x - 1',
          '    elif p == "R":',
          '        nx = x + 1',
          '    elif p == "U":',
          '        ny = y - 1',
          '    elif p == "D":',
          '        ny = y + 1',
          '    if 0 <= ny < h and 0 <= nx < len(me[ny]) and me[ny][nx] != "#":',
          '        x = nx',
          '        y = ny',
          'print(f"{x} {y}")',
        ].join('\n'),
        tier: 'NANG_CAO',
        judgeMode: 'IO_MATCH',
        tests: [
          sample('3\n...\n.#.\n...\n0 0\nRRD\n', '2 1\n', 'Đi phải hai lần rồi xuống, tránh được tường ở giữa.'),
          sample('3\n...\n.#.\n...\n0 0\nDD\n', '0 2\n', 'Cột 0 không có tường nên đi thẳng xuống được.'),
          hidden('2\n..\n..\n0 0\nLLUU\n', '0 0\n', 25),
          hidden('3\n...\n.#.\n...\n1 0\nD\n', '1 0\n', 25),
        ],
      }),
      challenge({
        slug: 'p-bs-pg-b26-cham-diem-quiz',
        title: 'Chấm điểm phần quiz',
        statement: [
          'Đọc số câu `n`, rồi `n` dòng đáp án đúng, rồi `n` dòng bài làm.',
          '',
          'In ra `<số câu đúng>/<tổng số câu>`.',
        ].join('\n'),
        hints: ['Đọc hết đáp án trước rồi mới đọc bài làm.'],
        starterCode: ['n = int(input())', '', '# So từng câu'].join('\n'),
        solutionCode: [
          'n = int(input())',
          'dung = [input() for _ in range(n)]',
          'lam = [input() for _ in range(n)]',
          'diem = 0',
          'for i in range(n):',
          '    if dung[i] == lam[i]:',
          '        diem = diem + 1',
          'print(f"{diem}/{n}")',
        ].join('\n'),
        tier: 'CO_BAN',
        judgeMode: 'IO_MATCH',
        tests: [
          sample('3\nA\nB\nC\nA\nC\nC\n', '2/3\n', 'Câu thứ hai sai.'),
          hidden('2\nX\nY\nX\nY\n', '2/2\n', 25),
          hidden('1\nA\nB\n', '0/1\n', 25),
        ],
      }),
    ],
  },

  'pg-b27-go-loi-va-toi-uu': {
    khoi: [
      challenge({
        slug: 'p-bs-pg-b27-vuot-ngan-sach-khung',
        title: 'Khung hình nào vượt ngân sách',
        statement: [
          'Ở 60 FPS, mỗi khung có ngân sách khoảng **16 mili giây**.',
          '',
          'Đọc số lượng `n` rồi `n` thời gian xử lý (mili giây).',
          'In ra số hiệu các khung **vượt quá 16**, đếm từ 1, cách nhau một dấu cách.',
          '',
          'Nếu không khung nào vượt, in ra `Muot`.',
        ].join('\n'),
        hints: ['Ghi lại chỉ số khi phát hiện khung chậm.'],
        starterCode: ['n = int(input())', 'cham = []', '', '# Tìm khung chậm'].join('\n'),
        solutionCode: [
          'n = int(input())',
          'cham = []',
          'for i in range(n):',
          '    t = int(input())',
          '    if t > 16:',
          '        cham.append(str(i + 1))',
          'if len(cham) == 0:',
          '    print("Muot")',
          'else:',
          '    print(" ".join(cham))',
        ].join('\n'),
        tier: 'CO_BAN',
        judgeMode: 'IO_MATCH',
        tests: [
          sample('5\n10\n20\n12\n30\n8\n', '2 4\n', 'Khung 2 và 4 vượt ngân sách.'),
          sample('3\n10\n12\n16\n', 'Muot\n', 'Đúng 16 vẫn nằm trong ngân sách.'),
          hidden('1\n17\n', '1\n', 25),
        ],
      }),
      challenge({
        slug: 'p-bs-pg-b27-fps-trung-binh',
        title: 'FPS trung bình',
        statement: [
          'Đọc số lượng `n` rồi `n` thời gian mỗi khung (mili giây).',
          '',
          'In ra FPS trung bình, làm tròn tới **1 chữ số thập phân**.',
          '',
          'FPS = 1000 chia cho thời gian trung bình của một khung.',
        ].join('\n'),
        hints: ['Tính thời gian trung bình trước, rồi mới lấy 1000 chia cho nó.'],
        starterCode: ['n = int(input())', 'tong = 0', '', '# Tính FPS'].join('\n'),
        solutionCode: [
          'n = int(input())',
          'tong = 0',
          'for _ in range(n):',
          '    tong = tong + int(input())',
          'print(f"{1000 / (tong / n):.1f}")',
        ].join('\n'),
        tier: 'THU_THACH',
        judgeMode: 'IO_MATCH',
        tests: [
          sample('4\n16\n16\n16\n16\n', '62.5\n', '1000 chia 16 bằng 62,5.'),
          hidden('2\n10\n30\n', '50.0\n', 25),
          hidden('1\n40\n', '25.0\n', 25),
        ],
      }),
    ],
  },

  'pg-b28-hoan-thien-do-hoa-am-thanh': {
    khoi: [
      challenge({
        slug: 'p-bs-pg-b28-kiem-tra-tai-nguyen',
        title: 'Tài nguyên nào còn thiếu',
        statement: [
          'Đọc số lượng `c` rồi `c` tên tệp **cần có**.',
          'Rồi đọc số lượng `d` và `d` tên tệp **đang có**.',
          '',
          'In ra các tệp còn thiếu, mỗi tệp một dòng, theo thứ tự trong danh sách cần có.',
          'Nếu không thiếu gì, in ra `Du het`.',
        ].join('\n'),
        hints: ['`if ten not in dang_co` là đủ.'],
        starterCode: ['c = int(input())', '', '# So hai danh sách'].join('\n'),
        solutionCode: [
          'c = int(input())',
          'can = [input() for _ in range(c)]',
          'd = int(input())',
          'co = [input() for _ in range(d)]',
          'thieu = [t for t in can if t not in co]',
          'if len(thieu) == 0:',
          '    print("Du het")',
          'else:',
          '    for t in thieu:',
          '        print(t)',
        ].join('\n'),
        tier: 'CO_BAN',
        judgeMode: 'IO_MATCH',
        tests: [
          sample('3\nnhac.wav\nnen.png\nhero.png\n2\nnen.png\nhero.png\n', 'nhac.wav\n', 'Chỉ thiếu tệp nhạc.'),
          sample('2\na.png\nb.png\n2\na.png\nb.png\n', 'Du het\n', 'Có đủ cả hai.'),
          hidden('1\nx.wav\n0\n', 'x.wav\n', 25),
        ],
      }),
      challenge({
        slug: 'p-bs-pg-b28-am-luong-theo-khoang-cach',
        title: 'Âm lượng nhỏ dần theo khoảng cách',
        statement: [
          'Âm lượng bằng 100 khi khoảng cách bằng 0, và giảm dần đều về 0 khi',
          'khoảng cách đạt `xa`.',
          '',
          'Đọc `xa` rồi `d`. In ra âm lượng, làm tròn xuống thành số nguyên.',
          'Khoảng cách từ `xa` trở lên thì âm lượng bằng 0.',
        ].join('\n'),
        hints: ['Âm lượng = 100 × (xa − d) ÷ xa, và không âm.'],
        starterCode: ['xa = int(input())', 'd = int(input())', '', '# Tính âm lượng'].join('\n'),
        solutionCode: [
          'xa = int(input())',
          'd = int(input())',
          'if d >= xa:',
          '    print(0)',
          'else:',
          '    print(100 * (xa - d) // xa)',
        ].join('\n'),
        tier: 'THU_THACH',
        judgeMode: 'IO_MATCH',
        tests: [
          sample('100\n50\n', '50\n', 'Nửa đường thì còn một nửa âm lượng.'),
          sample('100\n200\n', '0\n', 'Quá xa thì không nghe thấy gì.'),
          hidden('100\n0\n', '100\n', 25),
          hidden('30\n10\n', '66\n', 25),
        ],
      }),
    ],
  },

  'pg-b29-dong-goi-va-nop-du-an': {
    khoi: [
      challenge({
        slug: 'p-bs-pg-b29-kiem-tra-cau-truc-thu-muc',
        title: 'Kiểm tra cấu trúc thư mục nộp bài',
        statement: [
          'Bài nộp phải có đủ ba tệp: `main.py`, `README.md` và ít nhất một tệp trong `assets/`.',
          '',
          'Đọc số lượng `n` rồi `n` đường dẫn tệp.',
          '',
          'In ra `Hop le` nếu đủ cả ba điều kiện, ngược lại in ra `Thieu`.',
        ].join('\n'),
        hints: ['`t.startswith("assets/")` kiểm tra đường dẫn trong thư mục con.'],
        starterCode: ['n = int(input())', '', '# Kiểm tra ba điều kiện'].join('\n'),
        solutionCode: [
          'n = int(input())',
          'tep = [input() for _ in range(n)]',
          'co_main = "main.py" in tep',
          'co_readme = "README.md" in tep',
          'co_asset = False',
          'for t in tep:',
          '    if t.startswith("assets/"):',
          '        co_asset = True',
          'if co_main and co_readme and co_asset:',
          '    print("Hop le")',
          'else:',
          '    print("Thieu")',
        ].join('\n'),
        tier: 'CO_BAN',
        judgeMode: 'IO_MATCH',
        tests: [
          sample('3\nmain.py\nREADME.md\nassets/hero.png\n', 'Hop le\n', 'Đủ cả ba điều kiện.'),
          sample('2\nmain.py\nREADME.md\n', 'Thieu\n', 'Không có tệp nào trong assets.'),
          hidden('4\nassets/a.png\nassets/b.png\nmain.py\nREADME.md\n', 'Hop le\n', 25),
          hidden('1\nmain.py\n', 'Thieu\n', 25),
        ],
      }),
      challenge({
        slug: 'p-bs-pg-b29-tong-dung-luong',
        title: 'Gói bài nộp nặng bao nhiêu',
        statement: [
          'Đọc số lượng `n` rồi `n` dòng `<tên tệp> <dung lượng KB>`.',
          '',
          'In ra tổng dung lượng theo **MB**, làm tròn 2 chữ số thập phân (1 MB = 1024 KB),',
          'và ở dòng thứ hai in `Qua nang` nếu vượt 25 MB, ngược lại `OK`.',
        ].join('\n'),
        hints: ['Cộng hết KB rồi mới đổi sang MB.'],
        starterCode: ['n = int(input())', 'tong = 0', '', '# Cộng dung lượng'].join('\n'),
        solutionCode: [
          'n = int(input())',
          'tong = 0',
          'for _ in range(n):',
          '    ten, kb = input().split()',
          '    tong = tong + int(kb)',
          'mb = tong / 1024',
          'print(f"{mb:.2f}")',
          'if mb > 25:',
          '    print("Qua nang")',
          'else:',
          '    print("OK")',
        ].join('\n'),
        tier: 'THU_THACH',
        judgeMode: 'IO_MATCH',
        tests: [
          sample('2\nmain.py 24\nhero.png 1000\n', '1.00\nOK\n', '1024 KB đúng bằng 1 MB.'),
          hidden('1\nbig.wav 30720\n', '30.00\nQua nang\n', 30),
          hidden('1\na.py 0\n', '0.00\nOK\n', 30),
        ],
      }),
    ],
  },

  'pg-b30-trinh-bay-va-tong-ket': {
    khoi: [
      challenge({
        slug: 'p-bs-pg-b30-phan-bo-thoi-gian',
        title: 'Chia thời gian thuyết trình',
        statement: [
          'Đọc **tổng số phút** và số phần `n`, rồi `n` trọng số (số nguyên dương).',
          '',
          'Chia thời gian theo trọng số, mỗi phần làm tròn xuống, in mỗi phần một dòng.',
          '',
          'Phần thời gian dư ra vì làm tròn thì cộng hết cho **phần cuối cùng**.',
        ].join('\n'),
        hints: ['Tính từng phần bằng `tong * w // tong_w`.', 'Phần cuối = tổng trừ đi các phần đã chia.'],
        starterCode: ['tong = int(input())', 'n = int(input())', '', '# Chia thời gian'].join('\n'),
        solutionCode: [
          'tong = int(input())',
          'n = int(input())',
          'w = [int(input()) for _ in range(n)]',
          'tong_w = sum(w)',
          'da_chia = 0',
          'for i in range(n - 1):',
          '    phan = tong * w[i] // tong_w',
          '    da_chia = da_chia + phan',
          '    print(phan)',
          'print(tong - da_chia)',
        ].join('\n'),
        tier: 'THU_THACH',
        judgeMode: 'IO_MATCH',
        tests: [
          sample('10\n3\n1\n1\n1\n', '3\n3\n4\n', 'Dư 1 phút được dồn cho phần cuối.'),
          hidden('12\n2\n1\n1\n', '6\n6\n', 30),
          hidden('7\n1\n5\n', '7\n', 30),
        ],
      }),
      challenge({
        slug: 'p-bs-pg-b30-tong-ket-khoa-hoc',
        title: 'Tổng kết cả khoá',
        statement: [
          'Đọc số lượng `n` rồi `n` dòng `<tên bài> <điểm>`.',
          '',
          'In ra ba dòng: `So bai: <n>`, `Tong diem: <tổng>`,',
          'và `Bai cao nhat: <tên>` — nếu bằng điểm thì lấy bài **xuất hiện trước**.',
        ].join('\n'),
        hints: ['Chỉ thay bài dẫn đầu khi gặp điểm lớn hơn hẳn.'],
        starterCode: ['n = int(input())', '', '# Tổng kết'].join('\n'),
        solutionCode: [
          'n = int(input())',
          'tong = 0',
          'ten_max = ""',
          'diem_max = -1',
          'for _ in range(n):',
          '    ten, diem = input().split()',
          '    diem = int(diem)',
          '    tong = tong + diem',
          '    if diem > diem_max:',
          '        diem_max = diem',
          '        ten_max = ten',
          'print(f"So bai: {n}")',
          'print(f"Tong diem: {tong}")',
          'print(f"Bai cao nhat: {ten_max}")',
        ].join('\n'),
        tier: 'CO_BAN',
        judgeMode: 'IO_MATCH',
        tests: [
          sample(
            '3\npong 80\nmaze 95\nplatformer 95\n',
            'So bai: 3\nTong diem: 270\nBai cao nhat: maze\n',
            'maze và platformer bằng điểm, giữ bài xuất hiện trước.',
          ),
          hidden('1\ngame 100\n', 'So bai: 1\nTong diem: 100\nBai cao nhat: game\n', 30),
        ],
      }),
    ],
  },
};
