/**
 * Expansion pack — Lập trình game với Pygame, sessions 1–15.
 *
 * ── Why none of these import pygame ──────────────────────────────────────────
 * The judge runs each submission in a container with no display, no audio device
 * and no network. `import pygame` would either fail outright or block waiting for
 * a video driver, and the student would be told their logic was wrong.
 *
 * So these follow the pattern the course already uses: the GAME LOGIC is
 * extracted and judged on stdin/stdout — where the ball is after n frames,
 * whether two rectangles overlap, what the score becomes after a combo. That is
 * also the half worth practising. Drawing a rectangle is a call to look up;
 * knowing where the rectangle should BE is the part that makes a game work.
 */
import { challenge, hidden, sample } from '../../builders.ts';

import type { BoSungKhoaHoc } from './ap-dung.ts';

export const boSungPygame1: BoSungKhoaHoc = {
  'pg-b01-gioi-thieu-va-cua-so-dau-tien': {
    khoi: [
      challenge({
        slug: 'p-bs-pg-b01-kich-thuoc-cua-so',
        title: 'Tâm của cửa sổ game',
        statement: [
          'Đọc **chiều rộng** và **chiều cao** cửa sổ (hai số nguyên, mỗi số một dòng).',
          '',
          'In ra toạ độ tâm theo mẫu `<x> <y>`, dùng phép chia lấy phần nguyên.',
        ].join('\n'),
        hints: ['Tâm nằm ở nửa chiều rộng và nửa chiều cao.', 'Toạ độ pixel luôn là số nguyên nên dùng `//`.'],
        starterCode: ['rong = int(input())', 'cao = int(input())', '', '# In toạ độ tâm'].join('\n'),
        solutionCode: [
          'rong = int(input())',
          'cao = int(input())',
          'print(f"{rong // 2} {cao // 2}")',
        ].join('\n'),
        tier: 'CO_BAN',
        judgeMode: 'IO_MATCH',
        tests: [
          sample('800\n600\n', '400 300\n', 'Cửa sổ 800×600 có tâm ở (400, 300).'),
          hidden('640\n480\n', '320 240\n', 25),
          hidden('1025\n769\n', '512 384\n', 25),
        ],
      }),
      challenge({
        slug: 'p-bs-pg-b01-dat-giua-man-hinh',
        title: 'Đặt nhân vật vào giữa',
        statement: [
          'Đọc bốn số, mỗi số một dòng: **rộng cửa sổ**, **cao cửa sổ**,',
          '**rộng nhân vật**, **cao nhân vật**.',
          '',
          'In ra toạ độ góc trên trái để nhân vật nằm chính giữa, theo mẫu `<x> <y>`.',
        ].join('\n'),
        hints: ['Góc trái = nửa cửa sổ trừ đi nửa nhân vật.'],
        starterCode: [
          'rong = int(input())',
          'cao = int(input())',
          'w = int(input())',
          'h = int(input())',
          '',
          '# Tính góc trên trái',
        ].join('\n'),
        solutionCode: [
          'rong = int(input())',
          'cao = int(input())',
          'w = int(input())',
          'h = int(input())',
          'print(f"{(rong - w) // 2} {(cao - h) // 2}")',
        ].join('\n'),
        tier: 'CO_BAN',
        judgeMode: 'IO_MATCH',
        tests: [
          sample('800\n600\n40\n40\n', '380 280\n', 'Trừ đi nửa kích thước nhân vật.'),
          hidden('640\n480\n64\n32\n', '288 224\n', 25),
          hidden('100\n100\n100\n100\n', '0 0\n', 25),
        ],
      }),
    ],
  },

  'pg-b02-on-python-qua-hinh-ve': {
    khoi: [
      challenge({
        slug: 'p-bs-pg-b02-luoi-o-vuong',
        title: 'Toạ độ các ô trong lưới',
        statement: [
          'Đọc **số cột**, **số hàng** và **kích thước ô** (ba số nguyên).',
          '',
          'In ra toạ độ góc trên trái của từng ô, mỗi ô một dòng theo mẫu `<x> <y>`,',
          'duyệt theo **từng hàng từ trên xuống**, trong mỗi hàng đi từ trái sang phải.',
        ].join('\n'),
        hints: ['Hai vòng lặp lồng nhau: hàng ở ngoài, cột ở trong.', 'x = cột × kích thước, y = hàng × kích thước.'],
        starterCode: [
          'cot = int(input())',
          'hang = int(input())',
          'o = int(input())',
          '',
          '# In toạ độ từng ô',
        ].join('\n'),
        solutionCode: [
          'cot = int(input())',
          'hang = int(input())',
          'o = int(input())',
          'for h in range(hang):',
          '    for c in range(cot):',
          '        print(f"{c * o} {h * o}")',
        ].join('\n'),
        tier: 'CO_BAN',
        judgeMode: 'IO_MATCH',
        tests: [
          sample('2\n2\n10\n', '0 0\n10 0\n0 10\n10 10\n', 'Hết hàng trên rồi mới xuống hàng dưới.'),
          hidden('3\n1\n5\n', '0 0\n5 0\n10 0\n', 25),
          hidden('1\n3\n20\n', '0 0\n0 20\n0 40\n', 25),
        ],
      }),
      challenge({
        slug: 'p-bs-pg-b02-mau-xen-ke',
        title: 'Bàn cờ đen trắng',
        statement: [
          'Đọc **số cột** và **số hàng**.',
          '',
          'In ra bàn cờ: mỗi hàng một dòng, ô sáng là `.` và ô tối là `#`.',
          'Ô ở góc trên trái là ô sáng.',
        ].join('\n'),
        hints: ['Ô sáng khi tổng hàng + cột là số chẵn.'],
        starterCode: ['cot = int(input())', 'hang = int(input())', '', '# Vẽ bàn cờ'].join('\n'),
        solutionCode: [
          'cot = int(input())',
          'hang = int(input())',
          'for h in range(hang):',
          '    dong = ""',
          '    for c in range(cot):',
          '        if (h + c) % 2 == 0:',
          '            dong = dong + "."',
          '        else:',
          '            dong = dong + "#"',
          '    print(dong)',
        ].join('\n'),
        tier: 'THU_THACH',
        judgeMode: 'IO_MATCH',
        tests: [
          sample('4\n2\n', '.#.#\n#.#.\n', 'Hàng dưới lệch pha so với hàng trên.'),
          hidden('1\n1\n', '.\n', 25),
          hidden('3\n3\n', '.#.\n#.#\n.#.\n', 25),
        ],
      }),
    ],
  },

  'pg-b03-dieu-kien-vong-lap-qua-vat-roi': {
    khoi: [
      challenge({
        slug: 'p-bs-pg-b03-roi-den-day',
        title: 'Bao nhiêu khung hình thì chạm đáy',
        statement: [
          'Một vật ở độ cao `y = 0` rơi xuống với tốc độ `v` pixel mỗi khung hình.',
          'Đáy màn hình ở `y = day`.',
          '',
          'Đọc `day` rồi `v`. In ra số khung hình cần để `y` **đạt hoặc vượt** `day`.',
        ].join('\n'),
        hints: ['Cộng dồn cho tới khi đủ, đếm số vòng lặp.'],
        starterCode: ['day = int(input())', 'v = int(input())', '', '# Đếm khung hình'].join('\n'),
        solutionCode: [
          'day = int(input())',
          'v = int(input())',
          'y = 0',
          'khung = 0',
          'while y < day:',
          '    y = y + v',
          '    khung = khung + 1',
          'print(khung)',
        ].join('\n'),
        tier: 'CO_BAN',
        judgeMode: 'IO_MATCH',
        tests: [
          sample('100\n30\n', '4\n', 'Sau 3 khung mới tới 90, cần thêm một khung nữa.'),
          hidden('100\n100\n', '1\n', 25),
          hidden('99\n10\n', '10\n', 25),
        ],
      }),
      challenge({
        slug: 'p-bs-pg-b03-nay-lai-mot-lan',
        title: 'Nảy lại khi chạm đáy',
        statement: [
          'Vật ở `y = 0`, rơi `v` pixel mỗi khung. Khi `y` vượt quá `day`,',
          'nó **nảy lại**: đặt `y = day` và đổi hướng.',
          '',
          'Đọc `day`, `v` và **số khung** `n`. In ra vị trí `y` sau đúng n khung.',
        ].join('\n'),
        hints: ['Giữ một biến hướng: 1 là đi xuống, -1 là đi lên.', 'Kiểm tra cả hai biên: đáy và đỉnh (y = 0).'],
        starterCode: [
          'day = int(input())',
          'v = int(input())',
          'n = int(input())',
          '',
          '# Mô phỏng n khung',
        ].join('\n'),
        solutionCode: [
          'day = int(input())',
          'v = int(input())',
          'n = int(input())',
          'y = 0',
          'huong = 1',
          'for _ in range(n):',
          '    y = y + v * huong',
          '    if y >= day:',
          '        y = day',
          '        huong = -1',
          '    elif y <= 0:',
          '        y = 0',
          '        huong = 1',
          'print(y)',
        ].join('\n'),
        tier: 'THU_THACH',
        judgeMode: 'IO_MATCH',
        tests: [
          sample('100\n40\n3\n', '100\n', 'Khung 3 chạm đáy nên bị kẹp về đúng 100.'),
          hidden('100\n40\n5\n', '20\n', 25),
          hidden('50\n10\n2\n', '20\n', 25),
        ],
      }),
    ],
  },

  'pg-b04-ham-danh-sach-qua-sprite-di-chuyen': {
    khoi: [
      challenge({
        slug: 'p-bs-pg-b04-di-chuyen-nhieu-sprite',
        title: 'Dịch chuyển cả nhóm sprite',
        statement: [
          'Dòng đầu là số lượng `n`. `n` dòng sau, mỗi dòng là toạ độ `x y` của một sprite.',
          'Dòng cuối là độ dịch `dx dy`.',
          '',
          'In ra vị trí mới của từng sprite, mỗi sprite một dòng, giữ nguyên thứ tự.',
        ].join('\n'),
        hints: ['Đọc từng dòng rồi cộng thêm độ dịch.'],
        starterCode: ['n = int(input())', '', '# Dịch từng sprite'].join('\n'),
        solutionCode: [
          'n = int(input())',
          'sprite = []',
          'for _ in range(n):',
          '    x, y = input().split()',
          '    sprite.append((int(x), int(y)))',
          'dx, dy = input().split()',
          'dx = int(dx)',
          'dy = int(dy)',
          'for x, y in sprite:',
          '    print(f"{x + dx} {y + dy}")',
        ].join('\n'),
        tier: 'CO_BAN',
        judgeMode: 'IO_MATCH',
        tests: [
          sample('2\n0 0\n10 10\n5 -5\n', '5 -5\n15 5\n', 'Cả hai sprite dịch cùng một lượng.'),
          hidden('1\n100 100\n0 0\n', '100 100\n', 25),
          hidden('3\n1 1\n2 2\n3 3\n-1 -1\n', '0 0\n1 1\n2 2\n', 25),
        ],
      }),
      challenge({
        slug: 'p-bs-pg-b04-giu-trong-man-hinh',
        title: 'Giữ sprite trong màn hình',
        statement: [
          'Đọc **rộng**, **cao** màn hình, rồi toạ độ `x y` của sprite.',
          '',
          'Nếu sprite ra ngoài biên, kéo nó về sát biên gần nhất.',
          'In ra toạ độ hợp lệ theo mẫu `<x> <y>`.',
          '',
          'Toạ độ hợp lệ nằm trong khoảng 0 tới rộng − 1 và 0 tới cao − 1.',
        ].join('\n'),
        hints: ['Kẹp giá trị bằng `max(0, min(gioi_han, gia_tri))`.'],
        starterCode: [
          'rong = int(input())',
          'cao = int(input())',
          'x, y = input().split()',
          '',
          '# Kẹp về trong màn hình',
        ].join('\n'),
        solutionCode: [
          'rong = int(input())',
          'cao = int(input())',
          'x, y = input().split()',
          'x = max(0, min(rong - 1, int(x)))',
          'y = max(0, min(cao - 1, int(y)))',
          'print(f"{x} {y}")',
        ].join('\n'),
        tier: 'THU_THACH',
        judgeMode: 'IO_MATCH',
        tests: [
          sample('800\n600\n900 -20\n', '799 0\n', 'x vượt phải nên kẹp về 799, y âm nên kẹp về 0.'),
          hidden('100\n100\n50 50\n', '50 50\n', 25),
          hidden('10\n10\n-5 99\n', '0 9\n', 25),
        ],
      }),
    ],
  },

  'pg-b05-cua-so-game-loop-fps': {
    khoi: [
      challenge({
        slug: 'p-bs-pg-b05-so-khung-hinh',
        title: 'Bao nhiêu khung hình trong ngần ấy giây',
        statement: [
          'Đọc **FPS** và **số giây**, mỗi số một dòng.',
          '',
          'In ra tổng số khung hình được vẽ.',
        ].join('\n'),
        hints: ['FPS là số khung mỗi giây.'],
        starterCode: ['fps = int(input())', 'giay = int(input())', '', '# Tính số khung'].join('\n'),
        solutionCode: ['fps = int(input())', 'giay = int(input())', 'print(fps * giay)'].join('\n'),
        tier: 'CO_BAN',
        judgeMode: 'IO_MATCH',
        tests: [
          sample('60\n3\n', '180\n', '60 khung mỗi giây, trong 3 giây.'),
          hidden('30\n10\n', '300\n', 25),
          hidden('1\n1\n', '1\n', 25),
        ],
      }),
      challenge({
        slug: 'p-bs-pg-b05-thoi-gian-moi-khung',
        title: 'Mỗi khung hình dài bao lâu',
        statement: [
          'Đọc **FPS**.',
          '',
          'In ra thời gian của một khung hình tính bằng **mili giây**,',
          'làm tròn tới 2 chữ số thập phân.',
        ].join('\n'),
        hints: ['Một giây có 1000 mili giây.'],
        starterCode: ['fps = int(input())', '', '# Tính thời gian một khung'].join('\n'),
        solutionCode: ['fps = int(input())', 'print(f"{1000 / fps:.2f}")'].join('\n'),
        tier: 'CO_BAN',
        judgeMode: 'IO_MATCH',
        tests: [
          sample('60\n', '16.67\n', '1000 chia 60 xấp xỉ 16,67 mili giây.'),
          hidden('30\n', '33.33\n', 25),
          hidden('100\n', '10.00\n', 25),
        ],
      }),
    ],
  },

  'pg-b06-ve-hinh-ket-hop-tai-anh': {
    khoi: [
      challenge({
        slug: 'p-bs-pg-b06-thu-nho-anh',
        title: 'Thu nhỏ ảnh giữ tỉ lệ',
        statement: [
          'Đọc **rộng** và **cao** của ảnh gốc, rồi **chiều rộng mới**.',
          '',
          'In ra kích thước mới theo mẫu `<rộng> <cao>`, giữ nguyên tỉ lệ,',
          'chiều cao làm tròn xuống thành số nguyên.',
        ].join('\n'),
        hints: ['Tỉ lệ = rộng mới chia rộng cũ.', 'Cao mới = cao cũ × tỉ lệ, rồi lấy phần nguyên.'],
        starterCode: [
          'rong = int(input())',
          'cao = int(input())',
          'rong_moi = int(input())',
          '',
          '# Tính kích thước mới',
        ].join('\n'),
        solutionCode: [
          'rong = int(input())',
          'cao = int(input())',
          'rong_moi = int(input())',
          'print(f"{rong_moi} {int(cao * rong_moi / rong)}")',
        ].join('\n'),
        tier: 'THU_THACH',
        judgeMode: 'IO_MATCH',
        tests: [
          sample('800\n600\n400\n', '400 300\n', 'Thu một nửa thì cao cũng còn một nửa.'),
          hidden('100\n50\n25\n', '25 12\n', 25),
          hidden('640\n480\n640\n', '640 480\n', 25),
        ],
      }),
      challenge({
        slug: 'p-bs-pg-b06-xep-anh-thanh-hang',
        title: 'Xếp ảnh thành một hàng',
        statement: [
          'Đọc **số ảnh**, **rộng mỗi ảnh** và **khoảng cách** giữa hai ảnh liền nhau.',
          '',
          'In ra toạ độ x của từng ảnh, cách nhau một dấu cách, ảnh đầu ở x = 0.',
        ].join('\n'),
        hints: ['Ảnh thứ i nằm ở i × (rộng + khoảng cách).'],
        starterCode: [
          'n = int(input())',
          'w = int(input())',
          'k = int(input())',
          '',
          '# In các toạ độ x',
        ].join('\n'),
        solutionCode: [
          'n = int(input())',
          'w = int(input())',
          'k = int(input())',
          'print(" ".join(str(i * (w + k)) for i in range(n)))',
        ].join('\n'),
        tier: 'CO_BAN',
        judgeMode: 'IO_MATCH',
        tests: [
          sample('4\n50\n10\n', '0 60 120 180\n', 'Mỗi bước là 50 + 10.'),
          hidden('1\n30\n5\n', '0\n', 25),
          hidden('3\n100\n0\n', '0 100 200\n', 25),
        ],
      }),
    ],
  },

  'pg-b07-xu-ly-su-kien-ban-phim-chuot': {
    khoi: [
      challenge({
        slug: 'p-bs-pg-b07-di-theo-phim',
        title: 'Đi theo dãy phím',
        statement: [
          'Nhân vật bắt đầu ở `(0, 0)`.',
          '',
          'Đọc một dòng gồm các ký tự `L`, `R`, `U`, `D` (trái, phải, lên, xuống),',
          'mỗi phím dịch **1 đơn vị**. Trục y hướng xuống.',
          '',
          'In ra vị trí cuối theo mẫu `<x> <y>`.',
        ].join('\n'),
        hints: ['Trong đồ hoạ, y tăng khi đi xuống.'],
        starterCode: ['phim = input()', 'x = 0', 'y = 0', '', '# Xử lý từng phím'].join('\n'),
        solutionCode: [
          'phim = input()',
          'x = 0',
          'y = 0',
          'for p in phim:',
          '    if p == "L":',
          '        x = x - 1',
          '    elif p == "R":',
          '        x = x + 1',
          '    elif p == "U":',
          '        y = y - 1',
          '    elif p == "D":',
          '        y = y + 1',
          'print(f"{x} {y}")',
        ].join('\n'),
        tier: 'CO_BAN',
        judgeMode: 'IO_MATCH',
        tests: [
          sample('RRD\n', '2 1\n', 'Hai bước phải và một bước xuống.'),
          hidden('LLLL\n', '-4 0\n', 25),
          hidden('UDUD\n', '0 0\n', 25),
        ],
      }),
      challenge({
        slug: 'p-bs-pg-b07-click-trung-nut',
        title: 'Cú click có trúng nút không',
        statement: [
          'Đọc **x y w h** của một nút (góc trên trái, rộng, cao) trên một dòng.',
          'Dòng sau là toạ độ `cx cy` của cú click.',
          '',
          'In ra `Trung` nếu click nằm trong nút, ngược lại `Truot`.',
          '',
          'Cạnh trái và cạnh trên tính là trúng; cạnh phải và cạnh dưới thì không.',
        ].join('\n'),
        hints: ['Trúng khi x ≤ cx < x + w và y ≤ cy < y + h.'],
        starterCode: [
          'x, y, w, h = [int(v) for v in input().split()]',
          'cx, cy = [int(v) for v in input().split()]',
          '',
          '# Kiểm tra va chạm điểm với hình chữ nhật',
        ].join('\n'),
        solutionCode: [
          'x, y, w, h = [int(v) for v in input().split()]',
          'cx, cy = [int(v) for v in input().split()]',
          'if x <= cx < x + w and y <= cy < y + h:',
          '    print("Trung")',
          'else:',
          '    print("Truot")',
        ].join('\n'),
        tier: 'THU_THACH',
        judgeMode: 'IO_MATCH',
        tests: [
          sample('10 10 100 40\n50 20\n', 'Trung\n', 'Điểm nằm gọn trong nút.'),
          sample('10 10 100 40\n110 20\n', 'Truot\n', 'x = 110 đúng bằng cạnh phải nên không tính.'),
          hidden('0 0 5 5\n0 0\n', 'Trung\n', 25),
          hidden('0 0 5 5\n5 5\n', 'Truot\n', 25),
        ],
      }),
    ],
  },

  'pg-b08-sprite-group-va-paddle': {
    khoi: [
      challenge({
        slug: 'p-bs-pg-b08-paddle-trong-bien',
        title: 'Paddle không ra khỏi sân',
        statement: [
          'Đọc **rộng sân**, **rộng paddle**, **x hiện tại** và **độ dịch dx**.',
          '',
          'In ra x mới sau khi dịch, đã kẹp để paddle luôn nằm trọn trong sân.',
        ].join('\n'),
        hints: ['x hợp lệ nằm trong khoảng 0 tới rộng sân − rộng paddle.'],
        starterCode: [
          'san = int(input())',
          'w = int(input())',
          'x = int(input())',
          'dx = int(input())',
          '',
          '# Dịch rồi kẹp',
        ].join('\n'),
        solutionCode: [
          'san = int(input())',
          'w = int(input())',
          'x = int(input())',
          'dx = int(input())',
          'print(max(0, min(san - w, x + dx)))',
        ].join('\n'),
        tier: 'CO_BAN',
        judgeMode: 'IO_MATCH',
        tests: [
          sample('800\n100\n750\n20\n', '700\n', 'Đi tiếp sẽ lòi ra ngoài nên dừng ở 700.'),
          hidden('800\n100\n10\n-50\n', '0\n', 25),
          hidden('800\n100\n300\n50\n', '350\n', 25),
        ],
      }),
      challenge({
        slug: 'p-bs-pg-b08-dem-sprite-con-song',
        title: 'Còn bao nhiêu sprite',
        statement: [
          'Dòng đầu là số lượng `n`. `n` dòng sau, mỗi dòng là máu của một sprite.',
          '',
          'In ra số sprite còn sống (máu **lớn hơn 0**) và tổng máu còn lại,',
          'theo mẫu `<số sprite> <tổng máu>`.',
        ].join('\n'),
        hints: ['Chỉ cộng máu của những sprite còn sống.'],
        starterCode: ['n = int(input())', '', '# Đếm và cộng'].join('\n'),
        solutionCode: [
          'n = int(input())',
          'song = 0',
          'tong = 0',
          'for _ in range(n):',
          '    mau = int(input())',
          '    if mau > 0:',
          '        song = song + 1',
          '        tong = tong + mau',
          'print(f"{song} {tong}")',
        ].join('\n'),
        tier: 'CO_BAN',
        judgeMode: 'IO_MATCH',
        tests: [
          sample('4\n10\n0\n5\n-3\n', '2 15\n', 'Chỉ hai sprite còn máu dương.'),
          hidden('2\n0\n0\n', '0 0\n', 25),
          hidden('3\n1\n1\n1\n', '3 3\n', 25),
        ],
      }),
    ],
  },

  'pg-b09-chuyen-dong-co-ban': {
    khoi: [
      challenge({
        slug: 'p-bs-pg-b09-vi-tri-sau-n-khung',
        title: 'Vị trí sau n khung hình',
        statement: [
          'Đọc `x`, `y`, `vx`, `vy` và `n` — mỗi số một dòng.',
          '',
          'In ra vị trí sau n khung hình theo mẫu `<x> <y>`.',
        ].join('\n'),
        hints: ['Chuyển động đều: cộng vận tốc n lần, hoặc nhân thẳng.'],
        starterCode: [
          'x = int(input())',
          'y = int(input())',
          'vx = int(input())',
          'vy = int(input())',
          'n = int(input())',
          '',
          '# Tính vị trí mới',
        ].join('\n'),
        solutionCode: [
          'x = int(input())',
          'y = int(input())',
          'vx = int(input())',
          'vy = int(input())',
          'n = int(input())',
          'print(f"{x + vx * n} {y + vy * n}")',
        ].join('\n'),
        tier: 'CO_BAN',
        judgeMode: 'IO_MATCH',
        tests: [
          sample('0\n0\n3\n-2\n10\n', '30 -20\n', 'Nhân vận tốc với số khung.'),
          hidden('5\n5\n0\n0\n100\n', '5 5\n', 25),
          hidden('10\n10\n-1\n-1\n10\n', '0 0\n', 25),
        ],
      }),
      challenge({
        slug: 'p-bs-pg-b09-nay-hai-bien',
        title: 'Bóng nảy giữa hai tường',
        statement: [
          'Bóng ở `x`, chạy với vận tốc `v` mỗi khung, giữa hai tường `x = 0` và `x = rong`.',
          '',
          'Đọc `rong`, `x`, `v`, `n`. In ra vị trí sau n khung, có nảy khi chạm tường.',
        ].join('\n'),
        hints: ['Chạm tường thì kẹp về đúng biên và đảo dấu vận tốc.'],
        starterCode: [
          'rong = int(input())',
          'x = int(input())',
          'v = int(input())',
          'n = int(input())',
          '',
          '# Mô phỏng',
        ].join('\n'),
        solutionCode: [
          'rong = int(input())',
          'x = int(input())',
          'v = int(input())',
          'n = int(input())',
          'for _ in range(n):',
          '    x = x + v',
          '    if x >= rong:',
          '        x = rong',
          '        v = -v',
          '    elif x <= 0:',
          '        x = 0',
          '        v = -v',
          'print(x)',
        ].join('\n'),
        tier: 'THU_THACH',
        judgeMode: 'IO_MATCH',
        tests: [
          sample('100\n90\n20\n1\n', '100\n', 'Chạm tường phải nên dừng đúng ở 100.'),
          hidden('100\n90\n20\n2\n', '80\n', 25),
          hidden('10\n0\n-5\n1\n', '0\n', 25),
        ],
      }),
    ],
  },

  'pg-b10-chuyen-dong-nang-cao': {
    khoi: [
      challenge({
        slug: 'p-bs-pg-b10-tang-toc-dan',
        title: 'Tăng tốc dần',
        statement: [
          'Vận tốc bắt đầu bằng `v`, mỗi khung tăng thêm gia tốc `a`.',
          '',
          'Đọc `v`, `a`, `n`. In ra **quãng đường** đi được sau n khung.',
          '',
          'Mỗi khung: cộng gia tốc vào vận tốc trước, rồi mới cộng vận tốc vào quãng đường.',
        ].join('\n'),
        hints: ['Thứ tự cập nhật quan trọng — đọc kỹ đề.'],
        starterCode: [
          'v = int(input())',
          'a = int(input())',
          'n = int(input())',
          '',
          '# Cộng dồn quãng đường',
        ].join('\n'),
        solutionCode: [
          'v = int(input())',
          'a = int(input())',
          'n = int(input())',
          's = 0',
          'for _ in range(n):',
          '    v = v + a',
          '    s = s + v',
          'print(s)',
        ].join('\n'),
        tier: 'THU_THACH',
        judgeMode: 'IO_MATCH',
        tests: [
          sample('0\n1\n3\n', '6\n', 'Vận tốc 1, 2, 3 nên quãng đường là 1 + 2 + 3.'),
          hidden('10\n0\n5\n', '50\n', 25),
          hidden('5\n-1\n5\n', '10\n', 25),
        ],
      }),
      challenge({
        slug: 'p-bs-pg-b10-gioi-han-toc-do',
        title: 'Giới hạn tốc độ tối đa',
        statement: [
          'Vận tốc bắt đầu bằng 0 và tăng thêm `a` mỗi khung, nhưng **không vượt quá** `vmax`.',
          '',
          'Đọc `a`, `vmax`, `n`. In ra vận tốc sau n khung.',
        ].join('\n'),
        hints: ['Kẹp bằng `min(vmax, v + a)`.'],
        starterCode: [
          'a = int(input())',
          'vmax = int(input())',
          'n = int(input())',
          '',
          '# Tăng tốc có trần',
        ].join('\n'),
        solutionCode: [
          'a = int(input())',
          'vmax = int(input())',
          'n = int(input())',
          'v = 0',
          'for _ in range(n):',
          '    v = min(vmax, v + a)',
          'print(v)',
        ].join('\n'),
        tier: 'CO_BAN',
        judgeMode: 'IO_MATCH',
        tests: [
          sample('3\n10\n5\n', '10\n', 'Tới khung thứ tư thì chạm trần và dừng ở đó.'),
          hidden('2\n100\n5\n', '10\n', 25),
          hidden('5\n5\n1\n', '5\n', 25),
        ],
      }),
    ],
  },

  'pg-b11-vat-ly-trong-luc-nhay': {
    khoi: [
      challenge({
        slug: 'p-bs-pg-b11-nhay-va-roi',
        title: 'Nhân vật nhảy rồi rơi',
        statement: [
          'Nhân vật ở `y = 0` (mặt đất), nhảy lên với vận tốc `v` (số âm là đi lên).',
          'Mỗi khung: `v` tăng thêm trọng lực `g`, rồi `y` cộng thêm `v`.',
          '',
          'Đọc `v`, `g`, `n`. In ra `y` sau n khung, nhưng **không cho xuống dưới mặt đất**',
          '(nếu `y > 0` thì đặt về 0).',
        ].join('\n'),
        hints: ['Trục y hướng xuống nên nhảy lên là vận tốc âm.'],
        starterCode: [
          'v = int(input())',
          'g = int(input())',
          'n = int(input())',
          '',
          '# Mô phỏng nhảy',
        ].join('\n'),
        solutionCode: [
          'v = int(input())',
          'g = int(input())',
          'n = int(input())',
          'y = 0',
          'for _ in range(n):',
          '    v = v + g',
          '    y = y + v',
          '    if y > 0:',
          '        y = 0',
          'print(y)',
        ].join('\n'),
        tier: 'THU_THACH',
        judgeMode: 'IO_MATCH',
        tests: [
          sample('-10\n2\n3\n', '-18\n', 'Vận tốc từng khung là -8, -6, -4 nên y cộng dồn thành -18.'),
          hidden('-10\n2\n10\n', '0\n', 25),
          hidden('0\n5\n3\n', '0\n', 25),
        ],
      }),
      challenge({
        slug: 'p-bs-pg-b11-do-cao-lon-nhat',
        title: 'Nhảy cao nhất tới đâu',
        statement: [
          'Cùng mô hình nhảy như bài trước.',
          '',
          'Đọc `v`, `g`, `n`. In ra **độ cao lớn nhất** đạt được, tính bằng giá trị y nhỏ nhất',
          '(vì y càng nhỏ càng cao).',
        ].join('\n'),
        hints: ['Theo dõi giá trị nhỏ nhất của y trong suốt quá trình.'],
        starterCode: [
          'v = int(input())',
          'g = int(input())',
          'n = int(input())',
          '',
          '# Theo dõi điểm cao nhất',
        ].join('\n'),
        solutionCode: [
          'v = int(input())',
          'g = int(input())',
          'n = int(input())',
          'y = 0',
          'cao_nhat = 0',
          'for _ in range(n):',
          '    v = v + g',
          '    y = y + v',
          '    if y > 0:',
          '        y = 0',
          '    if y < cao_nhat:',
          '        cao_nhat = y',
          'print(cao_nhat)',
        ].join('\n'),
        tier: 'THU_THACH',
        judgeMode: 'IO_MATCH',
        tests: [
          sample('-10\n2\n10\n', '-20\n', 'Điểm cao nhất là lúc vận tốc vừa đổi dấu.'),
          hidden('0\n1\n5\n', '0\n', 25),
          hidden('-6\n3\n5\n', '-3\n', 25),
        ],
      }),
    ],
  },

  'pg-b12-phat-hien-va-cham': {
    khoi: [
      challenge({
        slug: 'p-bs-pg-b12-hai-hinh-chu-nhat',
        title: 'Hai hình chữ nhật có chạm nhau không',
        statement: [
          'Mỗi dòng là một hình chữ nhật: `x y w h`.',
          '',
          'In ra `Cham` nếu hai hình chồng lên nhau, ngược lại `Khong`.',
          '',
          'Chỉ chạm mép ngoài (cạnh sát nhau, không chồng phần diện tích nào) thì tính là `Khong`.',
        ].join('\n'),
        hints: ['Hai hình KHÔNG chạm khi một hình nằm hẳn về một phía của hình kia.', 'Xét bốn trường hợp tách rời rồi phủ định.'],
        starterCode: [
          'ax, ay, aw, ah = [int(v) for v in input().split()]',
          'bx, by, bw, bh = [int(v) for v in input().split()]',
          '',
          '# Kiểm tra chồng lấn',
        ].join('\n'),
        solutionCode: [
          'ax, ay, aw, ah = [int(v) for v in input().split()]',
          'bx, by, bw, bh = [int(v) for v in input().split()]',
          'tach = ax + aw <= bx or bx + bw <= ax or ay + ah <= by or by + bh <= ay',
          'if tach:',
          '    print("Khong")',
          'else:',
          '    print("Cham")',
        ].join('\n'),
        tier: 'THU_THACH',
        judgeMode: 'IO_MATCH',
        tests: [
          sample('0 0 10 10\n5 5 10 10\n', 'Cham\n', 'Hai hình chồng nhau ở góc.'),
          sample('0 0 10 10\n10 0 10 10\n', 'Khong\n', 'Sát mép nhưng không chồng phần nào.'),
          hidden('0 0 100 100\n10 10 5 5\n', 'Cham\n', 25),
          hidden('0 0 5 5\n0 6 5 5\n', 'Khong\n', 25),
        ],
      }),
      challenge({
        slug: 'p-bs-pg-b12-khoang-cach-hai-tam',
        title: 'Hai hình tròn có chạm nhau không',
        statement: [
          'Mỗi dòng là một hình tròn: `x y r`.',
          '',
          'In ra `Cham` nếu khoảng cách giữa hai tâm **nhỏ hơn hoặc bằng** tổng hai bán kính,',
          'ngược lại in `Khong`.',
        ].join('\n'),
        hints: ['So sánh bình phương khoảng cách với bình phương tổng bán kính để tránh căn.'],
        starterCode: [
          'ax, ay, ar = [int(v) for v in input().split()]',
          'bx, by, br = [int(v) for v in input().split()]',
          '',
          '# So sánh khoảng cách',
        ].join('\n'),
        solutionCode: [
          'ax, ay, ar = [int(v) for v in input().split()]',
          'bx, by, br = [int(v) for v in input().split()]',
          'dx = ax - bx',
          'dy = ay - by',
          'if dx * dx + dy * dy <= (ar + br) * (ar + br):',
          '    print("Cham")',
          'else:',
          '    print("Khong")',
        ].join('\n'),
        tier: 'THU_THACH',
        judgeMode: 'IO_MATCH',
        tests: [
          sample('0 0 5\n8 0 5\n', 'Cham\n', 'Khoảng cách 8 nhỏ hơn tổng bán kính 10.'),
          sample('0 0 2\n10 0 2\n', 'Khong\n', 'Khoảng cách 10 lớn hơn tổng bán kính 4.'),
          hidden('0 0 5\n10 0 5\n', 'Cham\n', 25),
          hidden('0 0 1\n0 3 1\n', 'Khong\n', 25),
        ],
      }),
    ],
  },

  'pg-b13-phan-hoi-va-cham-va-logic': {
    khoi: [
      challenge({
        slug: 'p-bs-pg-b13-mat-mau-va-chet',
        title: 'Trừ máu sau các cú va chạm',
        statement: [
          'Đọc **máu ban đầu**, rồi số lượng `n`, rồi `n` dòng sát thương.',
          '',
          'Trừ dần máu. Nếu máu **xuống 0 hoặc thấp hơn**, in ra `Game over` và dừng lại',
          'không xét các cú sau. Nếu sống sót hết, in ra máu còn lại.',
        ].join('\n'),
        hints: ['Dùng `break` khi máu hết.', 'Nhớ vẫn phải đọc hết đầu vào hay không? Ở đây không cần — chương trình dừng là được.'],
        starterCode: ['mau = int(input())', 'n = int(input())', '', '# Trừ máu dần'].join('\n'),
        solutionCode: [
          'mau = int(input())',
          'n = int(input())',
          'chet = False',
          'for _ in range(n):',
          '    st = int(input())',
          '    mau = mau - st',
          '    if mau <= 0:',
          '        chet = True',
          '        break',
          'if chet:',
          '    print("Game over")',
          'else:',
          '    print(mau)',
        ].join('\n'),
        tier: 'THU_THACH',
        judgeMode: 'IO_MATCH',
        tests: [
          sample('100\n3\n30\n30\n30\n', '10\n', 'Còn 10 máu sau ba cú.'),
          sample('50\n3\n30\n30\n30\n', 'Game over\n', 'Cú thứ hai làm máu xuống dưới 0.'),
          hidden('10\n1\n10\n', 'Game over\n', 25),
          hidden('10\n1\n9\n', '1\n', 25),
        ],
      }),
      challenge({
        slug: 'p-bs-pg-b13-huong-nay-lai',
        title: 'Nảy theo cạnh bị chạm',
        statement: [
          'Đọc `vx vy` rồi một chữ: `NGANG` hoặc `DOC`.',
          '',
          '`NGANG` nghĩa là chạm tường trái hoặc phải — đảo dấu `vx`.',
          '`DOC` nghĩa là chạm trần hoặc sàn — đảo dấu `vy`.',
          '',
          'In ra vận tốc mới theo mẫu `<vx> <vy>`.',
        ].join('\n'),
        hints: ['Chỉ một thành phần vận tốc đổi dấu, thành phần kia giữ nguyên.'],
        starterCode: [
          'vx, vy = [int(v) for v in input().split()]',
          'canh = input()',
          '',
          '# Đảo dấu đúng thành phần',
        ].join('\n'),
        solutionCode: [
          'vx, vy = [int(v) for v in input().split()]',
          'canh = input()',
          'if canh == "NGANG":',
          '    vx = -vx',
          'else:',
          '    vy = -vy',
          'print(f"{vx} {vy}")',
        ].join('\n'),
        tier: 'CO_BAN',
        judgeMode: 'IO_MATCH',
        tests: [
          sample('3 4\nNGANG\n', '-3 4\n', 'Chạm tường bên nên chỉ vx đổi dấu.'),
          sample('3 4\nDOC\n', '3 -4\n', 'Chạm trần hoặc sàn nên chỉ vy đổi dấu.'),
          hidden('-2 -5\nNGANG\n', '2 -5\n', 25),
        ],
      }),
    ],
  },

  'pg-b14-diem-so-mang-hud-am-thanh': {
    khoi: [
      challenge({
        slug: 'p-bs-pg-b14-diem-nhan-he-so',
        title: 'Điểm nhân theo hệ số',
        statement: [
          'Dòng đầu là số lượng `n`. `n` dòng sau, mỗi dòng là điểm của một lần ăn.',
          'Dòng cuối là **hệ số nhân**.',
          '',
          'In ra tổng điểm sau khi nhân hệ số.',
        ].join('\n'),
        hints: ['Cộng hết rồi mới nhân là đủ.'],
        starterCode: ['n = int(input())', '', '# Cộng rồi nhân hệ số'].join('\n'),
        solutionCode: [
          'n = int(input())',
          'tong = 0',
          'for _ in range(n):',
          '    tong = tong + int(input())',
          'he_so = int(input())',
          'print(tong * he_so)',
        ].join('\n'),
        tier: 'CO_BAN',
        judgeMode: 'IO_MATCH',
        tests: [
          sample('3\n10\n20\n30\n2\n', '120\n', 'Tổng 60 nhân hệ số 2.'),
          hidden('1\n5\n1\n', '5\n', 25),
          hidden('2\n0\n0\n10\n', '0\n', 25),
        ],
      }),
      challenge({
        slug: 'p-bs-pg-b14-hien-thanh-mau',
        title: 'Thanh máu trên HUD',
        statement: [
          'Đọc **máu hiện tại**, **máu tối đa** và **độ dài thanh** (số ô).',
          '',
          'In ra thanh máu: số ô đầy là `#`, số ô còn lại là `-`.',
          'Số ô đầy = máu hiện tại × độ dài ÷ máu tối đa, làm tròn xuống.',
        ].join('\n'),
        hints: ['Dùng `//` để làm tròn xuống.', '`"#" * day + "-" * (dai - day)`.'],
        starterCode: [
          'mau = int(input())',
          'toi_da = int(input())',
          'dai = int(input())',
          '',
          '# Vẽ thanh máu',
        ].join('\n'),
        solutionCode: [
          'mau = int(input())',
          'toi_da = int(input())',
          'dai = int(input())',
          'day = mau * dai // toi_da',
          'print("#" * day + "-" * (dai - day))',
        ].join('\n'),
        tier: 'THU_THACH',
        judgeMode: 'IO_MATCH',
        tests: [
          sample('50\n100\n10\n', '#####-----\n', 'Một nửa máu nên một nửa thanh đầy.'),
          hidden('100\n100\n5\n', '#####\n', 25),
          hidden('0\n100\n5\n', '-----\n', 25),
          hidden('33\n100\n10\n', '###-------\n', 25),
        ],
      }),
    ],
  },

  'pg-b15-menu-quan-ly-trang-thai': {
    khoi: [
      challenge({
        slug: 'p-bs-pg-b15-chuyen-trang-thai-menu',
        title: 'Chuyển trạng thái theo lệnh',
        statement: [
          'Game bắt đầu ở trạng thái `MENU`.',
          '',
          'Đọc số lượng `n` rồi `n` lệnh, mỗi lệnh một dòng:',
          '',
          '- `START`: từ `MENU` sang `PLAY`',
          '- `PAUSE`: từ `PLAY` sang `PAUSED`',
          '- `RESUME`: từ `PAUSED` sang `PLAY`',
          '- `QUIT`: từ bất kỳ đâu về `MENU`',
          '',
          'Lệnh không hợp lệ ở trạng thái hiện tại thì **bỏ qua**. In ra trạng thái cuối.',
        ].join('\n'),
        hints: ['Một biến chuỗi giữ trạng thái là đủ.', 'Kiểm tra cả lệnh lẫn trạng thái hiện tại trước khi đổi.'],
        starterCode: ['n = int(input())', 'trang_thai = "MENU"', '', '# Xử lý từng lệnh'].join('\n'),
        solutionCode: [
          'n = int(input())',
          'trang_thai = "MENU"',
          'for _ in range(n):',
          '    lenh = input()',
          '    if lenh == "START" and trang_thai == "MENU":',
          '        trang_thai = "PLAY"',
          '    elif lenh == "PAUSE" and trang_thai == "PLAY":',
          '        trang_thai = "PAUSED"',
          '    elif lenh == "RESUME" and trang_thai == "PAUSED":',
          '        trang_thai = "PLAY"',
          '    elif lenh == "QUIT":',
          '        trang_thai = "MENU"',
          'print(trang_thai)',
        ].join('\n'),
        tier: 'THU_THACH',
        judgeMode: 'IO_MATCH',
        tests: [
          sample('3\nSTART\nPAUSE\nRESUME\n', 'PLAY\n', 'Đi hết ba bước rồi quay lại PLAY.'),
          sample('2\nPAUSE\nSTART\n', 'PLAY\n', 'PAUSE ở MENU là không hợp lệ nên bị bỏ qua.'),
          hidden('1\nQUIT\n', 'MENU\n', 25),
          hidden('4\nSTART\nQUIT\nSTART\nPAUSE\n', 'PAUSED\n', 25),
        ],
      }),
      challenge({
        slug: 'p-bs-pg-b15-chon-muc-menu',
        title: 'Con trỏ trong menu',
        statement: [
          'Menu có `m` mục, con trỏ bắt đầu ở mục **0**.',
          '',
          'Đọc `m`, rồi số lượng `n`, rồi `n` phím `U` hoặc `D`.',
          '`D` xuống một mục, `U` lên một mục. Con trỏ **quay vòng**:',
          'từ mục cuối bấm `D` thì về mục 0.',
          '',
          'In ra chỉ số mục đang chọn.',
        ].join('\n'),
        hints: ['Phép `%` làm việc quay vòng rất gọn.'],
        starterCode: [
          'm = int(input())',
          'n = int(input())',
          'vt = 0',
          '',
          '# Di chuyển con trỏ',
        ].join('\n'),
        solutionCode: [
          'm = int(input())',
          'n = int(input())',
          'vt = 0',
          'for _ in range(n):',
          '    p = input()',
          '    if p == "D":',
          '        vt = (vt + 1) % m',
          '    elif p == "U":',
          '        vt = (vt - 1) % m',
          'print(vt)',
        ].join('\n'),
        tier: 'THU_THACH',
        judgeMode: 'IO_MATCH',
        tests: [
          sample('3\n4\nD\nD\nD\nD\n', '1\n', 'Sau ba lần D thì về 0, lần thứ tư sang 1.'),
          sample('3\n1\nU\n', '2\n', 'Từ mục 0 đi lên thì quay xuống mục cuối.'),
          hidden('5\n2\nD\nU\n', '0\n', 25),
        ],
      }),
    ],
  },
};
