import 'server-only';

/**
 * Content-addressed blob storage for project files.
 *
 * ── Why the disk layout looks like this ──────────────────────────────────────
 * Files live at `<root>/<xx>/<sha256>` where `xx` is the first two hex
 * characters of the hash. Nothing a student typed appears anywhere in that path.
 * A filename is a label in a database column; it is never joined onto a
 * filesystem root, so there is no traversal to defend against — the defence is
 * that the dangerous operation does not exist.
 *
 * ── Why it is not the public directory ───────────────────────────────────────
 * The root is outside `public/`, deliberately. Anything under `public/` is
 * served by the framework as a static file with a guessed content type; a `.py`
 * or `.json` placed there would be reachable at a predictable URL with no
 * authorization at all. Every read goes through a route handler that checks who
 * is asking first.
 *
 * ── What is never done here ──────────────────────────────────────────────────
 * Nothing in this module executes anything. There is no spawn, no import of a
 * stored file, no dynamic require. Uploaded bytes are data, and the only code
 * that ever runs student Python is the Phase 8 sandbox.
 */
import { mkdir, readFile, rm, stat, writeFile } from 'node:fs/promises';
import { dirname, join, resolve, sep } from 'node:path';

import type { KhoLuuTru } from '@dye/core';

/** Storage root. Outside `public/` and outside the Next.js build output. */
export const GOC_LUU_TRU = resolve(
  process.env['PROJECT_STORAGE_DIR'] ?? join(process.cwd(), '..', '..', 'uploads', 'projects'),
);

/** Hex SHA-256 and nothing else. */
const KHOA_HOP_LE = /^[0-9a-f]{2}\/[0-9a-f]{64}$/;

/**
 * Resolve a storage key to an absolute path, refusing anything unexpected.
 *
 * Keys are generated by `khoaLuuTru()` from a hash, so a malformed one means a
 * bug or tampering rather than an unusual filename. Both are worth refusing
 * loudly, and the containment check below survives future refactors that might
 * start accepting keys from somewhere less trustworthy.
 */
function duongDanCuaKhoa(key: string): string {
  if (!KHOA_HOP_LE.test(key)) {
    throw new Error('khoa luu tru khong hop le');
  }

  const duongDan = resolve(join(GOC_LUU_TRU, key));
  if (!duongDan.startsWith(GOC_LUU_TRU + sep)) {
    throw new Error('khoa luu tru thoat ra ngoai thu muc goc');
  }
  return duongDan;
}

export const khoDuAn: KhoLuuTru = {
  async ghi(key, data) {
    const duongDan = duongDanCuaKhoa(key);
    await mkdir(dirname(duongDan), { recursive: true });

    // Content-addressed: identical bytes produce an identical path, so a
    // re-upload of the same asset is a no-op rather than a rewrite.
    try {
      const s = await stat(duongDan);
      if (s.size === data.length) return;
    } catch {
      // Not there yet — fall through and write it.
    }

    await writeFile(duongDan, data);
  },

  async doc(key) {
    try {
      const buf = await readFile(duongDanCuaKhoa(key));
      return new Uint8Array(buf);
    } catch {
      return null;
    }
  },

  async xoa(key) {
    await rm(duongDanCuaKhoa(key), { force: true });
  },
};
